### ISSUE TITLE
[varLib] Reactivate shared tuples?

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1001]
Since font variations have been [deactivated in WebKit](https://bugs.webkit.org/show_bug.cgi?id=173618) and the Safari Technology Preview on macOS 10.12, should we reactivate the shared tuple mechanism?

https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/TupleVariation.py#L517

Maybe the bug is already fixed, because the [current report for CoreText](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/CoreText.html#GVAR-1) shows the test as OK.

**Comment by behdad** [comment]
Good question..

**Comment by behdad** [comment]
Sascha, would you be able to test?

**Comment by jenskutilek** [comment]
A word of caution ... I tried to reactivate the code, but it can result in invalid gvar data.

What happens is that the size of the resulting data using private points is always compared with the compiled data using shared points for all points of a glyph. However, if any of the tuple variations don't use all glyph points (e.g. because they rely on the IUP mechanism), and the shared points version would save space, the ‘incomplete’ tuple is compiled with shared points, and thus loses its point indices. The compiled font will be invalid, and on decompilation, a traceback is thrown.

You can see this for yourself if you uncomment the line mentioned earlier and try to ttx the test file [Mutator_IUP.ttx](https://github.com/fonttools/fonttools/blob/master/Tests/varLib/data/master_ttx_varfont_ttf/Mutator_IUP.ttx).

**Comment by jenskutilek** [comment]
#1009 reactivates the shared points logic and should also fix the bug described in the previous comment.

**Comment by anthrotype** [comment]
@jenskutilek anything more to do about this issue, or we can close?

**Comment by jenskutilek** [comment]
Oops, I missed this. We can close it.
