### ISSUE TITLE
[feaLib] "Expected name id < 255" check

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1003]
@brawer is it OK to remove this check from feaLib's `parse_nameid_`?
```python
        if nameID > 255:
            raise FeatureLibError("Expected name id < 255",
                                  self.cur_token_location_)
```
I ran into it while working on a project that requires hardcoding some nameids, and I can't think of a reason for blocking them, specially since they're outside the reserved range.

**Comment by behdad** [comment]
Humm.  That check looks clearly wrong to me.

**Comment by behdad** [comment]
CC @brawer 

Miguel, I think you can remove it, yes.

**Comment by anthrotype** [comment]
I agree it is wrong, but still the Adobe Feature File Specification says about the `nameid <id>`:

> An <id> is a number specifying the id of the name string to be added to the name table. This number must be in the registered id range 0, 7-255.

so perhaps the spec should be adjusted.

**Comment by miguelsousa** [comment]
The spec is clearly wrong. `makeotf` has no problem with nameids above 255. I'll take care of the changes later. Thanks.

**Comment by miguelsousa** [comment]
FDK bug https://github.com/adobe-type-tools/afdko/issues/189

**Comment by Arno-Enslin** [comment]
From the OT spec:

> Name IDs 256 to 32767, inclusive, are reserved for font-specific names such as those referenced by a font's layout features.

Instead of removing the check, wouldn't it be better to check, whether the ID is < 32767 (or 32768)?

**Comment by miguelsousa** [comment]
@Arno-Enslin https://github.com/fonttools/fonttools/commit/12b7c60a6817f43557802695c1af9180d1b3c53a
