### ISSUE TITLE
[subset] CodePageRanges are not subset

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1005]
CodePageRanges are left untouched by the subsetter.

**Comment by anthrotype** [comment]
It could be added at some point, but I don't see it as a high priority.

The codepages to unicode tables are defined the python [`encodings`](https://github.com/python/cpython/tree/master/Lib/encodings) module. We just have to decide how much of a codepage a font needs to cover for it to be "functional".

In a related fontmake issue, Read said that makeotf uses a 1/3 rule:
https://github.com/googlei18n/fontmake/issues/304

From my own experiments, I recall that FontLab was using a ~95% rule.

**Comment by miguelsousa** [comment]
The UnicodeRanges bits are being subset correctly, so why not just derive the CodePageRanges bits from those?

**Comment by behdad** [comment]
FWIW this is not necessary for webfont subsetting so I like it to be an option if it turns out to be expensive (which I think it is).

**Comment by codeman38** [comment]
> The codepages to unicode tables are defined in the python encodings module.

This doesn't seem to be true for multibyte CJK codecs - they're only available as C headers in the _cjkcodecs module (https://github.com/python/cpython/tree/2.7/Modules/cjkcodecs), which aren't directly exposed to Python as far as I can tell.

**Comment by khaledhosny** [comment]
Fixed in #3328
