### ISSUE TITLE
Deprecate (or revamp?) progress bar interface from xmlReader and xmlWriter

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1008]
https://github.com/fonttools/fonttools/pull/1007#discussion_r128479598

If nobody is using this anymore, we could print a warning whenever one sets the `progress` argument in `TTFont.saveXML` and `TTFont.importXML`; then in a couple of releases drop all the code the uses that (== less code to maintain).

On modern machines, dumping/compiling ttx files usually doesn't take more than a few seconds.

**Comment by justvanrossum** [comment]
I agree it's not needed anymore. However, people don't upgrade that often, so please leave that warning in a few releases longer :)
However: I think it's ok to remove the code earlier, just keep the API compatible longer by ignoring the argument (with a warning).

**Comment by anthrotype** [comment]
Yes, we can keep the argument and the warning forever. I just meant we can make the argument ineffective in a couple of releases (or more), but initially it would still keep working (but with a pending deprecation warning).
