### ISSUE TITLE
[merge] Merge CFF tables

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#101]
Includes mapping subroutines as well as FDSelectors, etc.

**Comment by justvanrossum** [comment]
I currently don't see any CFF code in fontTools/merge.py at all. Is this issue a reminder for CFF merging in general? As opposed to "making it merge correctly"? :)

**Comment by behdad** [comment]
I think you're right.  Adjusting.

**Comment by behdad** [comment]
Done.
