### ISSUE TITLE
[varLib] Clarification regarding avar segment maps

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1011]
The [avar spec](https://www.microsoft.com/typography/otspec/avar.htm) says:

> Axis value maps can be provided for any axis, but are required only if the normalization mapping for an axis is being modified. If the segment map for a given axis has any value maps, then it must include at least three value maps: -1 to -1, 0 to 0, and 1 to 1. These value mappings are essential to the design of the variation mechanisms and are required even if no additional maps are specified for a given axis.

 1. Currently, `varLib._add_fvar_avar` doesn’t enforce this. Should it?

 2. When an axis doesn’t cover the full range from -1 to 1, it makes no sense to include the entries as described.

For example, take a wdth axis from Condensed to Normal. The mappings may be:

```
-1.0 to -1.0
-0.5 to -0.3
 0.0 to  0.0
```

What would an additional 1 to 1 mapping, as required by the spec, do? There is no master at 1.0 for this axis. If something has to be added to the segment map, it should be `1.0 to 0.0`, making the range from 0 to 1 effectively flat. If that is the intent of the spec, the wording should be changed.

**Comment by PeterConstable** [comment]
Yes, varLib should enforce this to ensure fonts are valid. This is an old requirement, originating in [GX](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6avar.html):

"A segment must always have at least three correspondence pairs: minus one mapping to minus one, zero mapping to zero, and one mapping to one."

Your example considers a width axis from Condensed to Normal, but those values are defined only in "user" space, not normalized space. The 'avar' table is a transformation entirely within normalized space which is always defined as having axes going from -1 to +1. An 'fvar' table may happen to define an axis in which default and min or default and max are the same, in which case nothing changes between -1 and 0, or between 0 and +1. But that is a consideration in the mapping from "user" space to normalized space that is independent of the 'avar' transformation that happens entirely within normalized space.

**Comment by jenskutilek** [comment]
I see ... in that case the normalization done in varLib may be buggy. If I understand it correctly, for my example the normalization should look like this:

```
User space   Design space    Normalized
 50       ->  50             -1.0 -> -1.0
 75       ->  85             -0.5 ->  0.4
100       -> 100              0.0 ->  1.0 (default)
100       -> 100              1.0 ->  1.0
```

Is that correct?

**Comment by PeterConstable** [comment]
Basically, yes. The one comment is that, since the user range max is the same as the default, then selectable instances can never land in normalized space in the range (0, +1].

So your earlier question, "What would an additional 1 to 1 mapping do?" is valid: it will not have any effect in cases like this. But it has trivial impact and is a small thing for font tools to do.

**Comment by behdad** [comment]
I'll follow up on the OpenType list thread.  I like to suggest we only require 0->0 mapping.  The others are not needed really.

**Comment by jenskutilek** [comment]
Thanks all. #1014 fixes the issue about the default mappings. The rest was a misinterpretation on my part.
