### ISSUE TITLE
[ttLib] `name` module Macintosh langtags errata

### ISSUE THREAD

**Issue by Pal3love** [fonttools/fonttools#1013]
In module ttLib.tables._n_a_m_e:

(Line 700) 9: 'no'  ->  9: 'nb': 
'no' is the marcolangtag of Norwegian Bokmål ('nb', Mac langID 9), and Norwegian Nynorsk ('nn', Mac langID 151).

(Line 731) 40: 'si'  ->  40: 'sl':
It should be Slovenian, not Sinhalese, whose Mac langID is 76.

Thanks so much!

**Comment by anthrotype** [comment]
@Pal3love I think the first is already correct. The Macintosh langID 9 is simply called "Norwegian", so 'no' should be the correct language tag.

On the second one, you're right. the langID 40 is Slovenian, whose BCP47 tag is 'sl', not 'si' (which is Sinhalese, Mac langID 76).

I'll fix that, thanks for spotting.

https://www.microsoft.com/typography/otspec/name.htm
http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
