### ISSUE TITLE
are widths illegal in CFF2 charstrings?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1018]
the CFF2 spec says

> CFF2 CharStrings do not contain a value for advance width.

Does that mean we should validate on decompile and raise if charstring turns out to have a width?

Or, conversely, that we should drop the width when we compile the charstring as CFF2?

Remember that we are currently using the same `T2CharString` class, as well as the same decompiler and outline extractor classes for both Type2 CFF CharStrings and CFF2 CharStrings.

(I know the name is confusing and we are planning to rename it to a generic `CFFCharString`, keeping the old one as alias for backward compatibility.)

**Comment by anthrotype** [comment]
as @behdad noted, the `T2CharStringPen` (another double-duty class that would have to be renamed) already disallows to pass a width in if CFF2, although the `assert` in in the pen's `getCharString` method. Perhaps that should be moved to the CFFCharString constructor.

**Comment by anthrotype** [comment]
of course, I know widths are illegal in CFF2; my question above was more whether and how much we should police this, and how make sure we don't end up with extra (illegal) widths in CFF2 charstrings when the `CFFFontSet` container is converted from CFF to CFF2.

**Comment by behdad** [comment]
> how make sure we don't end up with extra (illegal) widths in CFF2 charstrings when the CFFFontSet container is converted from CFF to CFF2.

I'm not sure if we need to do that...

**Comment by khaledhosny** [comment]
Closing per comment above.
