### ISSUE TITLE
[varLib.mutator] support scalar calculation not working correctly

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1020]
The IUP interpolation doesn't seem to always do the right thing. For example, with

`$ fonttools varLib.mutator Skia.ttf wght=1.75 wdth=0.62`

I get this result:
<img width="164" alt="mutator" src="https://user-images.githubusercontent.com/4246121/28656638-58be42d4-72a3-11e7-8163-f1035233a4a5.png">

While in FontView I get this (at approximately the same location):

<img width="163" alt="fontview" src="https://user-images.githubusercontent.com/4246121/28656664-857c4834-72a3-11e7-8345-5157c6a8e74b.png">

**Comment by justvanrossum** [comment]
I've been trying to find the cause of the differences, and right now I conclude it's actually not the IUP code but something deeper. My current suspicion is that it has to do with intermediate regions, which is what's being used for that Q tail. I'll try to investigate further.

**Comment by justvanrossum** [comment]
I found the problem by comparing the support scalars used by FreeType. This section in `ttgxvar.c` is not implemented in varLib's `supportScalar()` function:

```c
      if ( tuple_coords[i] == 0 )
      {
        FT_TRACE6(( "      tuple coordinate is zero, ignored\n", i ));
        continue;
      }
```
The patch to fix would be this:
```diff
diff --git a/Lib/fontTools/varLib/models.py b/Lib/fontTools/varLib/models.py
index 36f8856..9912ef9 100644
--- a/Lib/fontTools/varLib/models.py
+++ b/Lib/fontTools/varLib/models.py
@@ -86,6 +86,9 @@ def supportScalar(location, support):
                        scalar = 0.
                        break
                v = location[axis]
+               if peak == 0.0:
+                       # peak is at the default, ignore (XXX why?, see FT ttgxvar.c, line 1040 (rev?))
+                       continue
                if v == peak:
                        continue
                if v <= lower or upper <= v:
```

I will try to locate the documentation that specifies this.

**Comment by justvanrossum** [comment]
Here it is, from https://www.microsoft.com/typography/otspec/otvarcommonformats.htm:

```If the given axis should not factor into the scalar calculation for a region, then this is achieved by setting peakCoord to zero. In this case, startCoord can be any non-positive value, and endCoord can be any non-negative value. It is recommended either that all three be set to zero, or that startCoord be set to -1.0 and endCoord be set to +1.0.```

**Comment by anthrotype** [comment]
Thanks @justvanrossum!

**Comment by justvanrossum** [comment]
@behdad, the possibly better fix would be the loosen this test in `TupleVariation.py`

```python
	for axis in axisTags:
		region = start[axis], peak[axis], end[axis]
		if region != (0.0, 0.0, 0.0):
			axes[axis] = region
```
to something like
```python
	for axis in axisTags:
		region = start[axis], peak[axis], end[axis]
		if region[1] != 0.0:
			axes[axis] = region
```
I think that means the exact same thing. What do you think?

**Comment by behdad** [comment]
> I found the problem by comparing the support scalars used by FreeType. This section in ttgxvar.c is not implemented in varLib's supportScalar() function:

Thanks.  Correct fix is to move it out of that function into the mutator code.  I'll fix that.

**Comment by behdad** [comment]
> I think that means the exact same thing. What do you think?

I'm not even sure that check should be there at all.  Let me think.

**Comment by justvanrossum** [comment]
Hm, it makes a lot of sense to me to omit irrelevant axes from the location dict. That's what it's doing now, except it misses irrelevant axes (== peak coord at zero) that have non-zero values for start or end coords.

**Comment by behdad** [comment]
> Hm, it makes a lot of sense to me to omit irrelevant axes from the axes dict. That's what it's doing now, except it misses irrelevant axes (== peak coord at zero) that have non-zero values for start or end coords.

But this is the compile/decompile code.  It shouldn't throw things away, specially if there's more than one way to encode something and it's not just a byte-encoding issue.

**Comment by behdad** [comment]
Donno.  Not sure whether to leave it as is, or remove the current condition.  I'm definitely not supporting of relaxing it.

**Comment by justvanrossum** [comment]
> But this is the compile/decompile code. It shouldn't throw things away, specially if there's more than one way to encode something and it's not just a byte-encoding issue.

> Donno. Not sure whether to leave it as is, or remove the current condition. I'm definitely not supporting of relaxing it.

The spec clearly says that a peak coord of zero means the axis should be ignored and that in that case the start and end values are irrelevant (as long as start <= peak <= end is ensured). The current decompile test makes it easier or other code to deal with that: an irrelevant axis is simply not there (also not in the gvar TTX output). The original implementation of `supportScalar()` nicely used that aspect, by not even needing a `peakCoord == 0` test.

I think the decompile test is a very elegant solution, that now just needs to ignore the start and end coords to work correctly according to the spec. We'd not be throwing away anything that has semantic significance.

**Comment by jenskutilek** [comment]
What’s not clear to me: When a region with peak 0 should be ignored, how could I achieve this scenario:

* axis `wght` from -1 to 1
* axis `ascn` which should lengthen the ascenders for the default weight (wght = 0), but not the extreme weights

The tuple variation entry for long ascenders could look something like this:

```xml
<glyphVariations glyph="h">
    <tuple>
        <coord axis="wght" min="-0.5" value="0.0" max="0.5"/>
        <coord axis="ascn" value="1.0"/>
        <delta pt="0" x="0" y="0"/>
        <delta pt="1" x="0" y="100"/>
        <delta pt="3" x="0" y="0"/>
    </tuple>
```
... except it is ignored because of the peak value = 0.0, and the restriction that min and max need to be either positive or negative. How would I go on about implementing such a region? Or is it not possible?

**Comment by PeterConstable** [comment]
You need to divide the region into two.

**Comment by jenskutilek** [comment]
Hm… if I divide the region, the peak values still would need to be at 0:

```xml
    <tuple>
        <coord axis="wght" min="-0.5" value="0.0" max="0.0"/>
        <coord axis="ascn" value="1.0"/>
        <delta pt="8" x="0" y="0"/>
        <delta pt="9" x="0" y="100"/>
        <delta pt="11" x="0" y="0"/>
    </tuple>
    <tuple>
        <coord axis="wght" min="0.0" value="0.0" max="0.5"/>
        <coord axis="ascn" value="1.0"/>
        <delta pt="8" x="0" y="0"/>
        <delta pt="9" x="0" y="100"/>
        <delta pt="11" x="0" y="0"/>
      </tuple>
```

One workaround I can think of is to add "counter deltas" which reverse the effect of the first delta:

```xml
    <tuple>
        <coord axis="ascn" value="1.0"/>
        <delta pt="8" x="0" y="0"/>
        <delta pt="9" x="0" y="100"/>
        <delta pt="11" x="0" y="0"/>
    </tuple>
    <tuple>
        <coord axis="ascn" value="1.0"/>
        <coord axis="wght" min="-1.0" value="-1.0" max="-0.5"/>
        <delta pt="8" x="0" y="0"/>
        <delta pt="9" x="0" y="-100"/>
        <delta pt="11" x="0" y="0"/>
    </tuple>
    <tuple>
        <coord axis="ascn" value="1.0"/>
        <coord axis="wght" min="0.5" value="1.0" max="1.0"/>
        <delta pt="8" x="0" y="0"/>
        <delta pt="9" x="0" y="-100"/>
        <delta pt="11" x="0" y="0"/>
    </tuple>
```
But that seems rather like a dirty hack …

**Comment by PeterConstable** [comment]
Think about it the other way: the longest ascenders are at the default, and the peak in either direction shortens them.

Btw, 'ascn' is not a registered axis. Please conform to the spec and use uppercase, "ASCN".

**Comment by behdad** [comment]
> Hm… if I divide the region, the peak values still would need to be at 0:

All those restrictions are trying to make sure "default" instance is what you get from glyf table, with no gvar contributions.

**Comment by behdad** [comment]
> But this is the compile/decompile code. It shouldn't throw things away, specially if there's more than one way to encode something and it's not just a byte-encoding issue.
> 
>     Donno. Not sure whether to leave it as is, or remove the current condition. I'm definitely not supporting of relaxing it.
> 
> The spec clearly says that a peak coord of zero means the axis should be ignored and that in that case the start and end values are irrelevant (as long as start <= peak <= end is ensured). The current decompile test makes it easier or other code to deal with that: an irrelevant axis is simply not there (also not in the gvar TTX output). The original implementation of supportScalar() nicely used that aspect, by not even needing a peakCoord == 0 test.
> 
> I think the decompile test is a very elegant solution, that now just needs to ignore the start and end coords to work correctly according to the spec. We'd not be throwing away anything that has semantic significance.

Just!  It's *you* who wanted Coverage table Format parameter back even though it held no semantic value whatsoever!  Make up your mind.

**Comment by justvanrossum** [comment]
> Just! It's you who wanted Coverage table Format parameter back even though it held no semantic value whatsoever! Make up your mind.

I did not miss the irony of that!
- could it be that maybe I'm slowly coming around the your point of view? :)
- the Coverage table discussion was (in hindsight) colored by the annoying code breakage of that change.

Also, there is a lot of inconsistency in fonttools, because, well, its history is _long_. Times change, contributors have different styles and views, consensus changes. This is your code, and I know your view, I think in _this_ context it's better to follow your lead and go for a semantic representation. The design of  'gvar' support in fonttools is about semantics, like how shared tuples are pretty much abstracted away. To now insist on keeping two values that should be ignored according to the spec seems a little silly to me in the light of your overall design.

**Comment by behdad** [comment]
This has been fixed since.
