### ISSUE TITLE
[varLib / ttLib] pen/GlyphSet API would be very handy for variable fonts

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1021]
I would love the TTFont().getGlyphSet() API to be extended with variable font support. This is how I imagine this to work:

```python
f = TTFont("myvarfont.ttf")
gs = f.getGlyphSet()
gs.setLocation({'wght': 120, 'wdth': 300})
g = gs['a']
g.draw(somePen)
print(g.width)
print(g.height)
```

To do this properly, varLib will have to grow a cleaner API to work with coordinates and deltas.

I have attached a very rough and sketchy implementation that uses some hacked up bits from `varLib.mutator`. I think this shows which parts of varLib need to be redesigned for easier reuse.

[ttVarGlyphSet.py.zip](https://github.com/fonttools/fonttools/files/1179014/ttVarGlyphSet.py.zip)

See also #1020

**Comment by behdad** [comment]
Sounds about right.  I'll give it a shot.

**Comment by behdad** [comment]
My notes:
Here's the interpolating code for one glyf: https://github.com/fonttools/fonttools/blob/a3f988fbf621142d7d9b3e68a69725b88f358869/Lib/fontTools/varLib/mutator.py#L197-L210

**Comment by behdad** [comment]
Changes need to go here:
needs to go here: https://github.com/fonttools/fonttools/blob/a3f988fbf621142d7d9b3e68a69725b88f358869/Lib/fontTools/ttLib/ttFont.py#L652

**Comment by behdad** [comment]
I'm looking into this. My thoughts are to change the glyf table draw to optionally take gvar and location and do it on the fly, without compiling a new glyf. It's a bit messy having to pass all the parameters around though. WDYT @justvanrossum ?

**Comment by justvanrossum** [comment]
To do it on the fly is a great, but I wouldn't want to burden the glyf module with it. Can the implementation be separate, near the TTGlyphSet code?

Maybe factor out drawing to a pen from a list of coordinates + flags array, so it can be more reusable.

**Comment by behdad** [comment]
> To do it on the fly is a great, but I wouldn't want to burden the glyf module with it. Can the implementation be separate, near the TTGlyphSet code?

Okay I'll see if that can be done. Good idea.  It's possible if we pass the location to `getGlyphSet`. I think that's a fine idea. Then we can reuse your implementation.

> Maybe factor out drawing to a pen from a list of coordinates + flags array, so it can be more reusable.

Sure that can be done.
