### ISSUE TITLE
[ttLib.tables.O_S_2f_2] Should consistency check between `OS/2` fsSelection and `head` macStyle be necessary?

### ISSUE THREAD

**Issue by Pal3love** [fonttools/fonttools#1022]
In current version of fontTools, there is `OS/2` fsSelection and `head` macStyle consistency check upon compile. Intuitively it makes sense because those bits (and nameID 2 in the `name` table as well) control the Windows style-linking mechanism together.

For the latest fonts however, I found that many bundled fonts with weight bolder than "medium," like "semi-bold," "extra-bold" or "heavy," have inconsistencies between fsSelection and macStyle. It seems like the designer did it on purpose. For example, Verdana Pro Semibold, bundled with the latest Windows 10, has the following settings:
`head`: macStyle = 0x0000 (Regular)
`OS/2`: fsSelection = 0x0120 (**Bold** and WWS), usWeightClass = 600 (Semi-bold)
`name`: (platformID 3, platEncID 1, langID 0x0409,) nameID 2: Regular

Verdana Pro Black, bundled with the latest Windows 10, has the following settings:
`head`: macStyle = 0x0000 (Regular)
`OS/2`: fsSelection = 0x0120 (**Bold** and WWS), usWeightClass = 900 (Heavy)
`name`: (platformID 3, platEncID 1, langID 0x0409,) nameID 2: Regular

Georgia Pro Black, bundled with the latest Windows 10, has the following settings:
`head`: macStyle = 0x0000 (Regular)
`OS/2`: fsSelection = 0x0120 (**Bold** and WWS), usWeightClass = 900 (Heavy)
`name`: (platformID 3, platEncID 1, langID 0x0409,) nameID 2: Regular

Hiragino Sans W6, bundled with macOS Sierra, has the following settings:
`head`: macStyle = 0x0000 (Regular)
`OS/2`: fsSelection = 0x0020 (**Bold**), usWeightClass = 600 (Semi-bold)
`name`: (platformID 3, platEncID 1, langID 0x0409,) nameID 2: Regular

Hiragino Sans W9, bundled with macOS Sierra, has the following settings:
`head`: macStyle = 0x0000 (Regular)
`OS/2`: fsSelection = 0x0020 (**Bold**), usWeightClass = 900 (Heavy)
`name`: (platformID 3, platEncID 1, langID 0x0409,) nameID 2: Regular

Even more interesting, in some cases, especially when using the 3rd party rasterizers like FreeType on Windows, `head`-`OS/2` consistent fonts with "extra-bold" or "heavy" like weight will result in a "smear bold," but inconsistent fonts like above work normally. Although the latest OT Spec still insists that macStyle and fsSelection should be consistent, I was wondering if the necessity of that consistency check could be reevaluated.

Thanks!

**Comment by Pal3love** [comment]
UPDATE:
My friend from Microsoft told me that Windows GDI will **forcibly** turn off the auto bold once fsSelection is set to **bold**, so this might be the reason why those fonts I listed above have such inconsistencies. Set fsSelection to bold can avoid **all possible auto-bolds** on Windows.

**Comment by anthrotype** [comment]
Interesting. Thanks for the info.
Could anyone try on a Windows machine and confirm this is the case?
I'd be fine with removing the warning.

**Comment by Pal3love** [comment]
Auto-bolding with usWeightClass >= 700 on Windows is rather a rare case, because the font's fsSelection has to be regular or anything else other than bold, and a 3rd-party rasterizer on Windows is required. For me, I use MacType, a front-end of FreeType on Windows, and that's why I had a chance to meet and hence, observe those trivia.

**Comment by moyogo** [comment]
From https://www.microsoft.com/typography/otspec/head.htm
> Note that the macStyle bits must agree with the 'OS/2' table fsSelection bits. The fsSelection bits are used over the macStyle bits in Microsoft Windows.

We’re just following the specs. I’m fine with removing the warning but I’d strongly prefer the specs be updated especially since a major implementation might benefit from not following that statement.

**Comment by nriley** [comment]
This check also fails when there is a bitmap font with a 'bhed' table but no 'head' table (they're both the same format, so it should not be a big deal to check one instead of the other!)
