### ISSUE TITLE
Problem running ttx on MacOS 10.12.6, python 2.7.11

### ISSUE THREAD

**Issue by mjsharpe** [fonttools/fonttools#1037]
Attempting to run ttx from fonttools-3.15.1 invariably leads to the same error message. I didn't find any similar problem in the issues list or on the fonttools forum. Any suggestions?

$ ttx ../STIXMath-Regular.otf
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ttx", line 11, in <module>
    sys.exit(main())
TypeError: main() takes exactly 1 argument (0 given)
$ ttx --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ttx", line 11, in <module>
    sys.exit(main())
TypeError: main() takes exactly 1 argument (0 given)

**Comment by jenskutilek** [comment]
How do you get Python 2.7.11 on macOS 10.12.6, did you install it yourself? The official Python version shipped by Apple is 2.7.10.

Also, usually fontTools are not installed into `/Library/Frameworks/Python.framework/`.

In general, it’s not a good idea to mess with the preinstalled Python on macOS.

**Comment by mjsharpe** [comment]
Hi Jens,
Thanks for your response. I installed 2.7.11 from the Python binary distribution site. It installs into /Library/Frameworks/Python.framework/ and sets PATH to pick this up before the Apple installation of 2.7.10. I then used pip from 2.7.11 to install fonttools. I've never had trouble with using a python version this way. 

I believe i've found the problem in ttx and corrected it on my machine. The last like of ttx reads
sys.exit(main())
and doesn't work until I replace it with
sys.exit(main(sys.argv[1:]))

I don't know if this issue only affects the Mac version.

**Comment by anthrotype** [comment]
This is strange. You should not see any such error if you install fonttools then normal way via pip. Can you please make sure fonttools is properly installed? Try uninstalling and reinstalling it using pip. Make sure there is no other fontTools apart from the pip installed one that may be polluting your PYTHONPATH

**Comment by mjsharpe** [comment]
I think I understand now where the problem lies. It appears that pip uninstall fonttools does not remove the contents of the fontTools subfolder of FontTools, leaving in place a quite old (2013) version of ttx.py that works differently from the current one. After I replaced the contents of FontTools/fontTools with the files from a new installation on a machine that had not previous installation of FontTools, ttx works without modification. (I don't see anything strange about the permissions on fontTools or its contents and I haven't tried to track down why pip  is not updating some but all subfolders of FontTools.)

**Comment by anthrotype** [comment]
Just remove anything you had previously manually installed and install again with pip.
There should no longer be a container "FontTools" folder if you install the latest fonttools using pip.
We dropped that long time ago.
