### ISSUE TITLE
ImportError: No module named fontTools.ttx

### ISSUE THREAD

**Issue by hkaraoglu** [fonttools/fonttools#1043]
```
Traceback (most recent call last):
  File "/usr/bin/ttx", line 7, in <module>
    from fontTools.ttx import main
ImportError: No module named fontTools.ttx
```

**Comment by anthrotype** [comment]
@hkaraoglu hi, sorry for the late reply.
It looks like fonttools wasn't properly installed, or it was removed/uninstalled but the scripts were left behind in `/usr/bin` folder.
Have been able to resolve it in the meantime?
How did you install fonttools?
Try to reinstall it, by doing `pip uninstall fonttools` and then again `pip install fonttools`.
