### ISSUE TITLE
Merge failure for Noto

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#1057]
This merge command:

```sh
fonttools merge \
    ../noto-source/master_ttf_interpolatable/NotoSans-Regular.ttf \
    ../noto-source/master_ttf_interpolatable/NotoSansCypriot-Regular.ttf
```

fails with the following error:

```
Traceback (most recent call last):
  File "./fonttools", line 12, in <module>
    sys.exit(main())
  File "/home/sascha/src/fonttools/Lib/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 1079, in <module>
    sys.exit(main())
  File "/home/sascha/src/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 1072, in main
    font = merger.merge(args)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 913, in merge
    table = clazz(tag).merge(self, tables)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 575, in merge
    assert (table is not None and table is not NotImplemented), "Have duplicates to resolve for font %d but no GSUB" % (i + 1)
AssertionError: Have duplicates to resolve for font 2 but no GSUB
```

The same error happens for quite a few other fonts in Noto. Examples are NotoSansCarian-Regular.ttf or NotoSansDeseret-Regular.ttf, but there's more. See the attached [merge-failures.zip](https://github.com/fonttools/fonttools/files/1311746/merge-failures.zip) for some fonts I'm trying to merge.

This might also be a problem with the Noto sources, but I'm not sure what exactly would be wrong, or how exactly the vendor should be told to change the sources so that the shards can be merged into a single font.

**Comment by brawer** [comment]
I’m running a script to find all shards that cause merge failures, but it it won’t finish before I board my flight. Here’s the merge failures my script has found so far: NotoSansAnatolianHieroglyphs, NotoSansBamum, NotoSansCarian, NotoSansCuneiform, NotoSansCypriot, NotoSansDeseret, NotoSansDevanagari, NotoSansEgyptianHieroglyphs, NotoSansGlagolitic, NotoSansImperialAramaic.

@behdad, can you tell if this is a fonttools problem or a source problem? If the latter, how to fix the sources? Devanagari had been working fine before your recent changes to pyftmerge, so I suspect the issue is in fonttools.

**Comment by behdad** [comment]
I need to resurrect some of https://github.com/fonttools/fonttools/pull/880 to fix this.

**Comment by anthrotype** [comment]
@behdad This still fails, even after fde3cf6, if a font one is attempting to merge has any duplicate glyphs that are not equivalent but the font does not have a GSUB table.

In his PR, Bo demoted those to a `log.warning`. Shall we do the same?

**Comment by behdad** [comment]
> Shall we do the same?

IMO no. We should check what glyphs those are and fix the sources IMO. If there's a legit reason to it, I can think of other ways.

**Comment by anthrotype** [comment]
I agree, but raise at the first occurrence may be too harsh. Printing a warning and skipping them would allow to get the list of glyphs that can't be merged and act accordingly (make them draw the same, or add a GSUB with non-empty scripts and langsys)

**Comment by behdad** [comment]
As you wish.

**Comment by anthrotype** [comment]
how exactly would you fix the sources?
in the other thread (https://github.com/fonttools/fonttools/issues/712#issuecomment-278500850) you wrote:

> Add GSUB for font without it. We need to identify the script tag to use. AND it is only safe to do so if we know there is no script-specific shaping logic for that script. In general, it's easiest to avoid this approach.

who should be responsible for adding the GSUB, fonttools or the font developer?

**Comment by behdad** [comment]
> how exactly would you fix the sources?

The difference might be as simple as the width of the space glyph. Which we should just fix...

> in the other thread (#712 (comment)) you wrote:
> 
>     Add GSUB for font without it. We need to identify the script tag to use. AND it is only safe to do so if we know there is no script-specific shaping logic for that script. In general, it's easiest to avoid this approach.
> 
> who should be responsible for adding the GSUB, fonttools or the font developer?

The merge tool. But first we need to verify there actually is a need for this.

**Comment by miloush** [comment]
I believe I have hit this issue as well.

`pyftmerge NotoSansTamilSupplement-Regular.ttf NotoSansTamil-Regular.ttf` works but

`pyftmerge NotoSansTamil-Regular.ttf NotoSansTamilSupplement-Regular.ttf` returns

```
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\InformatiX\AppData\Roaming\Python\Python37\Scripts\pyftmerge.exe\__main__.py", line 7, in <module>
  File "C:\Users\InformatiX\AppData\Roaming\Python\Python37\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "C:\Users\InformatiX\AppData\Roaming\Python\Python37\site-packages\fontTools\merge.py", line 1198, in main
    font = merger.merge(args)
  File "C:\Users\InformatiX\AppData\Roaming\Python\Python37\site-packages\fontTools\merge.py", line 1035, in merge
    table = clazz(tag).merge(self, tables)
  File "C:\Users\InformatiX\AppData\Roaming\Python\Python37\site-packages\fontTools\merge.py", line 644, in merge
    assert (table is not None and table is not NotImplemented), "Have duplicates to resolve for font %d but no GSUB: %s" % (i + 1, dups)
AssertionError: Have duplicates to resolve for font 2 but no GSUB: {'NULL': 'NULL#1', 'CR': 'CR#1'}
```

I believe the order should not matter.

**Comment by behdad** [comment]
We should discard differences in the first three gid's of TT fonts, and possibly resolve and discard diffs between space glyph as well.

**Comment by behdad** [comment]
We have at least downgraded this to a warning now...
