### ISSUE TITLE
fontTools/misc/sstruct.py:75: DeprecationWarning: integer argument expected, got float

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#1064]
```
from fontTools.ttLib import TTFont

f = TTFont(u"anybinary.otf")

hhea = f["hhea"]
print hhea.minLeftSideBearing
print hhea.minRightSideBearing
print hhea.xMaxExtent
print hhea.advanceWidthMax

hhea.recalc(f)

print hhea.minLeftSideBearing
print hhea.minRightSideBearing # becomes a float, not nice
print hhea.xMaxExtent  # becomes a float, not nice
print hhea.advanceWidthMax  
```

**Comment by typemytype** [comment]
those `math.ceil` and `math.floor` must be an `int`

see https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_h_h_e_a.py#L71
also in vhea see https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_v_h_e_a.py#L70

**Comment by typemytype** [comment]
at least in py2, I just see in  py3 math.ceil returns a int, pff

**Comment by anthrotype** [comment]
Thanks @typemytype

**Comment by typemytype** [comment]
(I cannot reopen)

similar issue:

```
 File "/Users/frederik/Documents/dev/fonttools/Lib/fontTools/ttLib/tables/_g_l_y_f.py", line 354, in compile
    data = sstruct.pack(glyphHeaderFormat, self)
  File "/Users/frederik/Documents/dev/fonttools/Lib/fontTools/misc/sstruct.py", line 75, in pack
    data = struct.pack(*(formatstring,) + tuple(elements))
/Users/frederik/Documents/dev/fonttools/Lib/fontTools/misc/sstruct.py:75: DeprecationWarning: integer argument expected, got float
  data = struct.pack(*(formatstring,) + tuple(elements))
```

**Comment by anthrotype** [comment]
hm. where do those floats come from?

**Comment by typemytype** [comment]
dont know (yet)

**Comment by typemytype** [comment]
what is the status of this?

**Comment by anthrotype** [comment]
I couldn’t repro, can you?

**Comment by justvanrossum** [comment]
I can't repro either, even with a font that has a glyph with float bounds (ie. no extremes) larger than any other glyph.
[BoundsTest.otf.zip](https://github.com/fonttools/fonttools/files/1482215/BoundsTest.otf.zip)

**Comment by justvanrossum** [comment]
Oh duh, that was the old issue, which is fixed.

**Comment by anthrotype** [comment]
closing as we can't repoduce the issue. please reopen in case you manage to replicate it
