### ISSUE TITLE
[varLib] mutator and cvt/cvar

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1066]
Looking for clarification on the cvar table ...

I created the branch [varlib-mutator-cvar](https://github.com/fonttools/fonttools/tree/varlib-mutator-cvar) where I added code to interpolate the cvar table with the same rules as the glyf variations: https://github.com/fonttools/fonttools/blob/varlib-mutator-cvar/Lib/fontTools/varLib/mutator.py#L155

To find out if the code is correct, I added a cvar table with VTT to a test font based on [the existing testing data](https://github.com/fonttools/fonttools/blob/varlib-mutator-cvar/Tests/varLib/data/test_results/BuildMain.ttx).

The cvt contains only 2 example entries, index 0 is the x-height of the master fonts (variable) and index 1 is the cap height (identical in all masters)

The master setup with corresponding CV 0 is like this:

```
cntr=1 wght=-1: 470          cntr=1 wght=0: 474          cntr=1 wght=1: 487
cntr=0 wght=-1: 470          cntr=0 wght=0: 474          cntr=0 wght=1: 487
(cntr=-1 doesn’t exist)      ()                          ()
```

The cvar table in the VTT-compiled font looks like this:

```xml
 <cvar>
   <version major="1" minor="0"/>
   <tuple>
<!-- <coord axis="cntr" value="0.0"/> -->
     <coord axis="wght" value="-1.0"/>
     <delta cvt="0" value="-4"/>
   </tuple>
   <tuple>
<!-- <coord axis="cntr" value="0.0"/> -->
     <coord axis="wght" value="1.0"/>
     <delta cvt="0" value="13"/>
   </tuple>
   <tuple>
     <coord axis="cntr" value="1.0"/>
     <coord axis="wght" value="1.0"/>
     <delta cvt="0" value="13"/>
   </tuple>
 </cvar>
```

What’s confusing me is that while the delta for c=1,w=-1 is omitted, which seems correct to me:

```
default + (0,-1) + (1,0) + (1,-1)
   474 +     -4 +     0 +      0 = 470
```

... the other corner delta 1,1 (13) is explicitly stored, so when I add them:

```
default + (0,1) + (1,0) + (1,1)
   474 +    13 +     0 +   13 = 500
```

But what I entered in VTT for the (1,1) master (Black High Contrast) is 487. So there seems to be an additional 13 added where it should not be.

Not sure if my code is correct, and VTT is wrong, or vice versa … any thoughts?

[BuildMain.ttf.zip](https://github.com/fonttools/fonttools/files/1359116/BuildMain.ttf.zip)

**Comment by moyogo** [comment]
@jenskutilek When I open BuildMain.ttf in VTT, it shows the Varied CVT `0: 487 (13)` in the Variation CVT window.

**Comment by jenskutilek** [comment]
Thanks for having a look!

Yes, in VTT the variation cvts look correct, but when I generate an instance with varLib.mutator using my code, the instance wght=1000 cntr=100 has cvt 0 = 500 (474 + 13 + 13). I’m not sure if the error is in my code or the VTT-generated cvar.

**Comment by moyogo** [comment]
From what I saw, the deltas entered in VTT don’t always match what is rendered even in VTT.

**Comment by anthrotype** [comment]
@jenskutilek please open a PR from that branch so we can comment the code in-line

**Comment by jenskutilek** [comment]
PR: https://github.com/fonttools/fonttools/pull/1067

**Comment by robmck-ms** [comment]
I'm not sure that VTT is computing off-axis deltas for cvar correctly. It appears to be not including the contribution of on-axis deltas. I'm investigating. Meanwhile, I wouldn't take VTT's cvar entry for this as an authoritative reference.

**Comment by robmck-ms** [comment]
I.e. in Jens' example above, the entry for (cntr=0,wght=1) contributes a delta of 13, thus the delta at (cntr=1,wght=1) should be 0 (so that the net delta is 13). And, with a delta of 0, the entry for (cntr=1,wght=1) shouldn't have even been emitted.

**Comment by jenskutilek** [comment]
Thanks. Closing because this is not a fontTools issue.
