### ISSUE TITLE
Travis build on Python 3.6 fails

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1068]
Currently the Travis builds on Python 3.6 fail during `install.sh`. Example:
https://travis-ci.org/fonttools/fonttools/jobs/285520779

```bash
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! (RuntimeError)
The command "./.travis/install.sh" failed and exited with 1 during .
```

I dont’t know much about either Travis or Homebrew …

**Comment by anthrotype** [comment]
upstream bug in Travis CI or homebrew...

https://github.com/travis-ci/travis-ci/issues/8552

we can temporarily allow it to fail until they fix it or we find a workaround.

**Comment by anthrotype** [comment]
@jenskutilek Ok, I temporarily commented out the python3.6 osx build. You can merge master in your PR branch to avoid seeing those unrelated failures.

**Comment by jenskutilek** [comment]
Thank you!

**Comment by anthrotype** [comment]
Let's keep it open as reminder to reenable the failing OS X build once they fix the upstream issue
