### ISSUE TITLE
[ttx] Add compact XML format for cmap format13

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#107]
I wanted to create a cmap table that maps all of Unicode to the same glyph.  Ended up hand-coding the bytes:

https://github.com/behdad/tofudetector/commit/b86463e0a50e861de155d28793bda5e3a862b0a0

Writing that in XML requires one line per Unicode character...  We should add a range-compressed XML format for format13.

**Comment by kenlunde** [comment]
@behdad I spent the past week or so migrating various projects on SourceForge to GitHub, and Adobe Blank is the last one I am dealing with. I am currently in the process of rebuilding it to include only two glyphs (CIDs 0 and 1) and the Format 13 'cmap' subtable. It should be quite small.

**Comment by behdad** [comment]
@kenlunde Sounds good.  Looks like by next month'ish, Chrome should also happily accept those; and Firefox should have been for a while now.  So, time is just about right.

**Comment by kenlunde** [comment]
@behdad Because the Format 13 'cmap' subtable doesn't have broad support, I will release the new version of Adobe Blank with a new name and as a separate project. (Check your email when you have a chance, because I sent something to you.)
