### ISSUE TITLE
add a programmatic interface to mutator.py

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1070]
Right now it's set up as only a command line tool.
It would useful to have something like the subsetter module.

**Comment by behdad** [comment]
@garretrieger

**Comment by anthrotype** [comment]
ca7c359 

I just added an `instantiateVariableFont` function that takes a variable TTFont and a dictionary of axes locations, and returns a new static TTFont.

@behdad @garretrieger @rsheeter Is that what you had in mind?

**Comment by rsheeter** [comment]
Yes, awesome! Hm. Bonus points if it can partially instantiate. For
example, I want to keep wght but pin a specific wdth, dropping data
relating to varying wdth.

**Comment by justvanrossum** [comment]
Also relates to #1021

**Comment by behdad** [comment]
> Bonus points if it can partially instantiate.

Will happen eventually, but not any time soon.

**Comment by behdad** [comment]
I'm merging because I like to touch this module.  Might rename the entry point.

**Comment by behdad** [comment]
Oh, this is not a PR :D

**Comment by anthrotype** [comment]
> Might rename the entry point.

please do, I wasn't sure either.

**Comment by behdad** [comment]
Let's leave it as is.
