### ISSUE TITLE
Instantiating a STAT table or DesignAxisRecord

### ISSUE THREAD

**Issue by robmck-ms** [fonttools/fonttools#1072]
Dumb question: How do you programmatically instantiate a new STAT table. `font['STAT'] = newTable('STAT')` does instantiate a STAT table object, but it doesn't have a `table` member, etc. Seems like the constructor doesn't fully set everything up?

While I'm at it: How do you instantiate a new DesignAxisRecord to add to an existing STAT table? 

There doesn't seem to be a lot of docs on tables & objects managed by otData/otConverters/etc.

**Comment by jenskutilek** [comment]
I haven’t tried it myself, but it should be analogous to this snippet generating a HVAR table from varLib:

```python
from fontTools.ttLib.tables import otTables

HVAR = font["HVAR"] = newTable('HVAR')
hvar = HVAR.table = otTables.HVAR()
hvar.Version = 0x00010000
# ...
```

**Comment by jenskutilek** [comment]
All objects seem to come from `fontTools.ttLib.tables.otTables` and you have to figure out how to combine them:

```
from fontTools.ttLib.tables import otTables as ot

STAT = font["STAT"] = newTable('STAT')
stat = STAT.table = ot.STAT()
stat.Version = 0x00010001
stat.DesignAxisRecord = ot.AxisRecordArray()
stat.DesignAxisRecord.Axis = [ot.AxisRecord(), ot.AxisRecord()]
# I'm not sure if you have to set the count yourself:
stat.DesignAxisCount = 2
`

**Comment by robmck-ms** [comment]
This is great. Thanks!
