### ISSUE TITLE
Glyph side-bearing attributes

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fonttools#1074]
It would be nice to have these attributes in the glyf table or any other suitable table.

```
>>> font['glyf']['a'].lsb
50

>>> font['glyf']['a'].rsb
50
```

I've needed these attributes on a few occasions. My usual approach is:

```
lsb = font['glyf']['a'].xMin
rsb = font['hmtx'].metrics['a'][0] - font['glyf']['a'].xMax
```

I understand that glyph side bearings may be a concept of font editors and not any font spec.

More than happy to implement this and submit a pr if people approve.

**Comment by khaledhosny** [comment]
The left side bearing and glyph advance are stored in the `hmtx` table, the right side bearing is the difference between x max and glyph advance.

**Comment by khaledhosny** [comment]
```python
adv = font['hmtx'].metrics['a'][0]
lsb = font['hmtx'].metrics['a'][1]
rsb = adv - font['glyf']['a'].xMax
```

**Comment by m4rc1e** [comment]
@khaledhosny Thanks, I pretty much the same thing in my example.

**Comment by anthrotype** [comment]
For higher level stuff that's shared among glyf/CFF glyphs there is the ttLib._TTGlyph class. That already has both advance width and lsb. You could add a property that returns the rsb as well.

**Comment by anthrotype** [comment]
That's the objects that you get when you do TTFont.getGlyphSet()

**Comment by m4rc1e** [comment]
@anthrotype I see :-)

```
>>> a = font.getGlyphSet()['a']
>>> dir(a)
[..., 'draw', 'height', 'lsb', 'tsb', 'width']
```

Mind if I implement rsb?

**Comment by anthrotype** [comment]
If don't mind if you do, thanks :)

**Comment by anthrotype** [comment]
For consistency then you should also add a `bsb` (bottom side bearing) property if font has vmtx table.

Although I'm not super concinced of the necessity of these extra attributes at this level.. I think they are a bit fictitious, in the sense that they are not "there" in the font, but only derived from other data. It has to be clear to the user that there is no "right side bearing" value in the sfnt tables.

**Comment by m4rc1e** [comment]
Closing due to discussion in #1075
