### ISSUE TITLE
Error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fonttools#1076]
![31041355-425f948a-a56a-11e7-9389-ca011a83904a](https://user-images.githubusercontent.com/213676/31638519-dc049db0-b2b2-11e7-8977-d3140ebdc06d.png)

Interestingly, when trying to use ttx to inspect the file contents I get a similar error, which makes me believe this is a case of corrupted TTF files:

![31041363-6697f626-a56a-11e7-9725-c51b41ed8c87](https://user-images.githubusercontent.com/213676/31638562-10f438b4-b2b3-11e7-91cc-82c7d70534d0.png)

More detailed info at:
https://github.com/googlefonts/fontbakery/issues/1596

**Comment by felipesanches** [comment]
To replicate this bug, you can run ttx on the **ofl/seoulnamsan/SeoulNamsan-Bold.ttf** from the google/fonts git repo (at commit bb5c17d9c67039166a4f1f5894cdd2629156d13d).

**Comment by anthrotype** [comment]
the font looks broken, nothing we can do
