### ISSUE TITLE
Rearrange tables order

### ISSUE THREAD

**Issue by davidseah** [fonttools/fonttools#1077]
Will it be possible to have a feature that allows us to rearrange the tables order? Something like the GlyphOrder.

**Comment by justvanrossum** [comment]
Check `fontTools.ttLib.reorderFontTables()`

**Comment by behdad** [comment]
I'm curious. Why do you need that?

**Comment by davidseah** [comment]
@behdad we are looking into the possibility to stream our TTF files, allowing just enough data to draw the first few glyphs while loading the rest of the TTF data.
