### ISSUE TITLE
varLib "IUP" delta optimization as an optional feature instead of on by default

### ISSUE THREAD

**Issue by andyclymer** [fonttools/fonttools#1084]
Some variable font implementations seem to have problems drawing glyphs that have "IUP" delta optimizations.

Currently, `_add_gvar()` sets the optimize option to be True as a default, but the API for disabling optimization could be easier to get to if the option was available as an argument of the `build()` method as well.

https://github.com/fonttools/fonttools/blob/3fbc4688eb5ef1057c58ae8bc12a1ba0b59b12d5/Lib/fontTools/varLib/__init__.py#L656

**Comment by anthrotype** [comment]
yes, maybe we could have an `optimize=True` argument to `varLib.build`. Would you like to work on a pull request?
Which implementations are you referring to, if I may ask?

**Comment by behdad** [comment]
Can you share details about which implementations have this problem?  I think I've heard Adobe's does.

**Comment by brawer** [comment]
Any implementations that aren’t yet covered by https://github.com/unicode-org/text-rendering-tests? If we’re talking about CoreText, is this covered by test case [GVAR-9](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/CoreText.html#GVAR-9) or do we need to add another test to the test suite? (Afaik Apple has fixed test case GVAR-9 in macOS 10.13; I just haven’t yet set up a box for reproducing that it’s been fixed).

**Comment by andyclymer** [comment]
I'm specifically observing it in Adobe's implementation. I'm sure it's probably just a bug on their end, but for now it could be nice to have the optimization as an option.

**Comment by behdad** [comment]
Is this communicated to Adobe?
@readroberts @miguelsousa

**Comment by jenskutilek** [comment]
Yes, I sent a bug report with a demo font.

**Comment by readroberts** [comment]
And it is now in the internal Adobe bug database, and has been reproduced. Should be fixed at some point.

**Comment by andyclymer** [comment]
Thanks everyone!

**Comment by brawer** [comment]
@jenskutilek, would you be interested in contributing your test font (just a subset with few failing glyphs) to Unicode’s test suite? https://github.com/unicode-org/text-rendering-tests

**Comment by jenskutilek** [comment]
I opened an issue with the test font: https://github.com/unicode-org/text-rendering-tests/issues/42

**Comment by behdad** [comment]
I'm open to disabling this for now, until Adobe has a new release so we can just tell people "Update XXX".

**Comment by behdad** [comment]
FWIW here's the patch:
```patch
diff --git a/Lib/fontTools/varLib/__init__.py b/Lib/fontTools/varLib/__init__.py
index 589b96fb..76c01ae0 100644
--- a/Lib/fontTools/varLib/__init__.py
+++ b/Lib/fontTools/varLib/__init__.py
@@ -263,7 +263,7 @@ def _SetCoordinates(font, glyphName, coord):
        # XXX Handle vertical
        font["hmtx"].metrics[glyphName] = horizontalAdvanceWidth, leftSideBearing
 
-def _add_gvar(font, model, master_ttfs, tolerance=0.5, optimize=True):
+def _add_gvar(font, model, master_ttfs, tolerance=0.5, optimize=False):
 
        assert tolerance >= 0
 
```

**Comment by anthrotype** [comment]
I'm going ahead and set optimize=False by default for now until Adobe apps will ship a fix.
I will also add a `-O` (or `--optimize`) option to `fontTools varLib` console script so that "advanced" users can optionally turn it on with their interpolatable ttfs.

If anybody prefers a different solution, please speak up now.
