### ISSUE TITLE
Apple kern tables are wrongly compiled

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1089]
The Apple kern table (with uint32 version) has different subtable format than the OpenType one.  We ignore this when compiling kern subtables.
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6kern.html
https://www.microsoft.com/typography/otspec/kern.htm

**Comment by anthrotype** [comment]
could this one also be related? https://github.com/fonttools/fonttools/issues/999

**Comment by behdad** [comment]
Yep.

**Comment by anthrotype** [comment]
it looks like in the decompile code we do set an `subtable.apple = True` attribute when kern table version is 1. We just ignore it while compiling the subtables. It shouldn't be difficult to fix.

**Comment by behdad** [comment]
Definitely not hard.  Just clumsy.  Note that `tupleIndex` is loaded from Apple tables but not stored in XML...  Also, coverage bits mean different things in OT versus Apple spec.  Moreover, the subtable version field of OpenType is bogus and unused.

**Comment by anthrotype** [comment]
yes, and for the Apple `coverage` field only the low byte is kept (`coverage & 0xFF`), i.e. the one wich defines the subtable format, the high byte is thrown away.
There seems to be a confusion between the subtable version number (only in OT kern) and the kern subtable format.

Also we set the "subtable.apple" attribute only when decompiling from binary, but not when reading kern table version="1.0" from XML.

**Comment by anthrotype** [comment]
I'm still confused about that "version" field in the OpenType kern _subtable_ header (not the kern _table_ version, which is always 0 in the OpenType spec, and 1.0 in Apple TrueType spec). As you know this subtable header "version" is no longer present in Apple's kern table version=1.0.
Then, in both the specs, the last 8 bits of the `coverage` (ushort) field is specified as the "the _format_ of the subtable": 0 and 2 for OpenType spec, and 0, 1, 2, 3 for Apple TrueType spec.

Format 0 kern subtables are the only ones that will be properly interpreted by Windows, as the OT spec notes. Therefore all the kern version=0 tables out there that are meant to work on Windows have only format-0 subtables; these all unsurprisingly have subtable header "version" 0.

Now, the OT spec also has format-2 kern subtables (two-dimensional array of kerning values). Even if Windows does not support this, I am wondering would the subtable header "version" of a theoretical format-2 kern subtable (inside a kern version 0 table) also be _2_ (like its "format"), or would it be _0_ (like the bogus header version), if one wished to follow the OpenType kern spec?

My real question is, can't we just ignore such bogus "version" field which is only in the old kern spec and which will unlikely ever be updated again, and only read and use the subtable "format" from the coverage bits when we want to distinguish the various subtables?

The kern table version (be it 0 or 1.0) is still what distinguishes the two flavors of kern: one has ushorts for for version, nTables and subtable length, the other has ulong, etc.

**Comment by anthrotype** [comment]
also, shall we load in the subtable `coverage` attribute only the bits 0-7 (high byte) and in the `format` attribute the low byte containing the actual subtable format? Then upon compile we would bitwise-OR them into a single `coverage` USHORT.
We only support format 0 for now, so my suggestion above wouldn't change anything. But in the future it's conceivable we add support for other kern subtable formats (harbuzz is adding support for AAT kern too).
