### ISSUE TITLE
ImportError: No module named fontTools.ttLib.standardGlyphOrder

### ISSUE THREAD

**Issue by rbmntjs** [fonttools/fonttools#1099]
I’ve reinstalled pretty much every part in order to only arrive at this error when running makeOTF. The files are there, it worked perfectly through `pip install fonttools`, but somehow the command line doesn’t know how to find it. I don’t know that this is necessarily on your plate, but, I don’t know what else to do anymore.

**Comment by anthrotype** [comment]
That module is definitely there in our source distribution package (.zip) as well as in the wheel (.whl) package that we upload to the Python Package Index (which you get when you pip install fonttools).
So it sounds like a downstream packaging issue in the AFDKO, sorry.
