### ISSUE TITLE
How to use fonttools to create a new OTF/TTF font?

### ISSUE THREAD

**Issue by jamadagni** [fonttools/fonttools#1102]
Hello. I hope it is OK to ask such a question here. If not, please point to where I can do that.

I want to do something like:

```
from fonttools import TTFont
newfont = TTFont()
g1 = newfont.addglyph()
g1.addChar(<unicode-codepoint1>)
g1.addChar(<unicode-codepoint2>)
g1.moveTo(<p1>)
g1.quadTo(<c>,<p2>)
g1.lineTo(<p3>)
g1.closePath()
g1.moveTo(<p4>)
...
g2 = ...
...
newfont.write("myfont.ttf")

```
And likewise using cubicTo() or such for OTFont.

Is this currently possible using fonttools? If so, kindly provide a simple guide as to how this can be done.

Thanks!

**Comment by anthrotype** [comment]
hello!
the short answer is no, I'm afraid.

Or rather, you could... but fontTools is very low level library to work with, if you're not familiar with the structure of OpenType fonts.

You could programmatically build a [UFO](http://unifiedfontobject.org/) using tools like [defcon](https://github.com/typesupply/defcon), and then pass this object to a compiler like [ufo2ft](https://github.com/googlei18n/ufo2ft), which internally uses fontTools to build up the various OpenType tables from the source data contained in the UFO.
You can look at ufo2ft code to see how it calls fontTools to build the open type font from scratch.

Or you could just pass the UFO path to a command-line tool like [fontmake](https://github.com/googlei18n/fontmake), which will use ufo2ft to build the OTF or TTF font.

**Comment by jamadagni** [comment]
Thank you for your kind reply. That is very clear now. I will ask any further questions on the relevant forums (defcon etc).
