### ISSUE TITLE
inspect.py should use GObject Introspection

### ISSUE THREAD

**Issue by jbicha** [fonttools/fonttools#1107]
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/inspect.py uses the really old pygtkcompat import. It should be switched to use regular pygobject and GObject Introspection.

This might be the issue that caused https://github.com/fonttools/fonttools/issues/93 ( I needed to make sure that python3-gi [or python-gi for the python2 version] and gir1.2-gtk-3.0 were installed on my Debian/Ubuntu system to avoid the import error.)

**Comment by behdad** [comment]
inspect.py is unmaintained.  If you can send a pull-request, we'll happily merge.  Otherwise, we might even remove it.
