### ISSUE TITLE
[unicodedata] script and script_extension return names in different format

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1109]
I just noticed that `script` function returns long script names (e.g. "Bengali") whereas `script_extension` returns short ones (e.g. `{"Beng"}`). This reflects the fact that in Scripts.txt they use the long names, whereas in ScriptExtensions.txt the short ones.

The problem is with the current implementation of `script_extension` that delegates to `script` whenever a codepoint has not been explicitly assigned a script extension: it returns a set containing a single script name, however using the long format which is inconsistent with the other results from script_extension function.

So, we also need to parse the [PropertyValueAliases.txt](http://www.unicode.org/Public/UCD/latest/ucd/PropertyValueAliases.txt) and load the mapping between long and short script names, and return one or the other, but not a mix of the two.

Would you prefer that both `script` and `script_extension` functions return the long version, or that both return the short version? 

Or we keep the difference, and `script` returns the long version ("Bengali"), whereas the `script_extension` returns the short name ("Beng").

**Comment by anthrotype** [comment]
I think it makes more sense to return the long script names in both the `script` and `script_extension` functions.

**Comment by anthrotype** [comment]
I'm also thinking that we could replace the `_` with a space in the script names that contain more than one word. They are equivalent, because of the "loose matching of property names and values" whereby "the case distinctions, whitespace, hyphens, and '_' are ignored."
I think the space-separated long script names are more human readable.

Let me know if you prefer to keep the underscore separated long script names instead ("Egyptian_Hieroglyphs").

**Comment by twardoch** [comment]
I think it would be best if the `script` and `script_extension` functions always returned the Unicode script codes (4-letter names). The Unicode script codes should be a reference for other functions. 

- `Scripts.py` should get a `NAMES` dictionary which maps the script codes to the longer names (with `_` kept, so it’s closer to UnicodeData)
- a `script_name` function could take a script code and would return the long name (with `_` replaced by ` `); this would in a sense mirror the `unicodadata.name` function which returns the character name for a Unicode codepoint; people could query Scripts.NAMES for a unique list of the script codes

**Comment by twardoch** [comment]
(The Unicode script codes are useful as keys for a variety of reasons. I’ve got some code that I’d contribute that would make use of them.)

**Comment by anthrotype** [comment]
Thanks Adam. Ok, I'll have both functions return the four-character script codes and add a `script_name` function as well.
