### ISSUE TITLE
My HarfBuzz-based Unicode script to OpenType script mapping builder

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#1112]
Hi @anthrotype 

Please check out my [`hb_scripts3.py`](https://github.com/twardoch/feaLab/blob/master/Lib/feaLab/hb_scripts3.py) mini-module. 

It’s a mini-module to convert between Unicode and OpenType script tags. It uses the [harfpy](https://github.com/ldo/harfpy) ctypes-based Python 3 bindings for HarfBuzz. Use [my fork](https://github.com/twardoch/harfpy) until my [PR](https://github.com/ldo/harfpy/pull/12) is merged upstream. It uses the Unicode-to-OpenType script tag [conversion logic from HarfBuzz](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-tag.cc). 

Perhaps you might want to move the essential bits into `MetaTools` as a new builder for stuff in `unicodedata`. I would have made it myself but since the HarfBuzz bindings I used are Python 3 only, I didn’t have to mingle directly with the tools inside `MetaTools`. I think it’s OK to have a Python 3-only tool with a HarfBuzz dependancy in `MetaTools` though, right? 

I’ve already written a function in my `hb_scripts3.py` module called `getIsoToOtScriptMap` which takes all the Unicode script tags and makes a dict like this: 

```
OTSCRIPTS = { 
    'Adlm': ['adlm'],
...
    'Arab': ['arab'],
...
    'Beng': ['bng2', 'beng'],
...
    'Cyrl': ['cyrl'],
    'Deva': ['dev2', 'deva'],
...
    'Latn': ['latn'],
...
    'Yiii': ['yi  '],
    'Zanb': ['zanb'],
    'Zinh': ['DFLT'],
    'Zyyy': ['DFLT'],
    'Zzzz': ['DFLT']
}
```

As you notice, the values are lists because of the OT scripts that have multiple implementations. 

Then, you could provide some simple functions in `unicodedata` for looking up the OT scripts based on that OTSCRIPTS mapping — this is why I asked you to use the Unicode script tags (short names) as keys, btw :) 

I have also written a simple function `updateLanguageSystemsInFea` which uses the code to auto-generate `languagesystem` statements in a FEA based on a series of Unicode codepoints (normally, the font’s `cmap` table). Feel free to rewrite it to use the updated `fontTools.unicodedata` thing and then use it in `ufo2ft` as a `languageSystemWriter` or something.

**Comment by anthrotype** [comment]
Thanks Adam!

having some way to map between Unicode/iso script codes and OpenType script tags would indeed be useful in fontTools.unicodedata; as well as updating the FEA languagesystems based on the font's cmap for ufo2ft's feature writers.

I wonder if we need to pull in harfbuzz for that. Maybe we could write a python implementation of "hb-ot-tag.cc".

I'll have a look later.

**Comment by twardoch** [comment]
I think if HB is only used to build the map, then it's even better — we only have one source to pull the data from. If @behdad updates the logic in hb-ot-tag.cc, we only need to adopt our builder.

**Comment by anthrotype** [comment]
the conversion logic in `hb_ot_tags_from_script` (and the related funcs `hb_ot_old_tag_from_script` and `hb_ot_new_tag_from_script`) looks pretty simple
```
 Most of the script tags are the same as the ISO 15924 tag but lowercased.
 So we just do that, and handle the exceptional cases in a switch.
```
we could do the same here in pure python

**Comment by twardoch** [comment]
Actually, you’re right. It would be much simpler since only that portion needs to be ported, and there’s other stuff in hb-ot-tag.cc that we don’t need.
