### ISSUE TITLE
pyftinspect "import gtk" means it won't run on macOS

### ISSUE THREAD

**Issue by gingerbeardman** [fonttools/fonttools#1115]
```matt$ pyftinspect Delima/Delima-Regular.ttf 
Traceback (most recent call last):
  File "/usr/local/bin/pyftinspect", line 7, in <module>
    from fontTools.inspect import main
  File "/Library/Python/2.7/site-packages/fontTools/inspect.py", line 19, in <module>
    import gtk
ImportError: No module named gtk
```

how do I get gtk module on macOS?

**Comment by anthrotype** [comment]
try `brew install pygtk`

**Comment by gingerbeardman** [comment]
I did, didn't help

**Comment by anthrotype** [comment]
you sure you're using the homebrew python (usually `/usr/local/bin/python` and `/usr/local/bin/python3`) and not a different python binary from somewhere else (the built-in system `/usr/bin/python`)?

python packages installed via homebrew can only be imported from the homebrew python.

**Comment by gingerbeardman** [comment]
you're right, even though i have homebrew python install `which python` states i'm using system python. thanks!

**Comment by gingerbeardman** [comment]
I give up, in a world of pain here

**Comment by chrissimpkins** [comment]
@gingerbeardman try using `python2 [module path]` if you are executing the script directly or remove fontTools from Py2 (`pip uninstall fontTools`) and reinstall on Homebrew Python3 (installed with `brew install python3`) with `pip3 install fontTools`.  

I've recently had this issue too with Homebrew installed Python versions.  I think that macOS updates are removing the links to the Homebrew Python installs and my attempts to re-link `python` to  Homebrew Py2 do not work.  This leads to a situation where `python` != `python2`.  Unfortunately, `pip` is still associated with the Homebrew Py2 on my system so execution of anything with `python [script]` fails to pick up pip installed packages.  `python` defaults to system (currently 2.7.10 for me), `python2` to homebrew Py2 (2.7.14), and `python3` to homebrew Py3 (3.6.3) on my system.

Alternatively, run from within a virtualenv with whatever Py version you want and all of the proper dependencies installed.  Maybe that takes care of the problem?

**Comment by gingerbeardman** [comment]
so i am now running the correct python /usr/local/bin/python but still no joy

ffffffffffffffffffffffffffff

**Comment by chrissimpkins** [comment]
Here is what I get when I try to import gtk (Homebrew pygtk v2.24.0_1) in Py2.7.14:

```
Python 2.7.14 (default, Sep 25 2017, 09:53:22)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtk
/usr/local/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'PangoRenderer'
  from gtk import _gtk
/usr/local/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_once_init_leave: assertion 'result != 0' failed
  from gtk import _gtk
/usr/local/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  from gtk import _gtk
/usr/local/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
[1]    86775 segmentation fault  python2
```

@anthrotype may be worth a deeper dive.  I have never used pyftinspect so can't say how long this has been the case, but it appears that gtk is having issues on OS X platform in current release version.

**Comment by gingerbeardman** [comment]
A bit drastic but I nuked homebrew and started again from scratch

(install homebrew)
brew install python
(check/fix python)
brew install pygtk
pip install fonttools

...now it's working

and relax :)

thanks for sticking with me

**Comment by chrissimpkins** [comment]
Until the next macOS update ;)

**Comment by khaledhosny** [comment]
pyftinspect isn't that useful really, it does not tel you much that you can't find reading ttx output.

**Comment by gingerbeardman** [comment]
Also, it's effectively the same as FTXViewer from the Apple Font Tool Suite 

I wish I had known this before hand X)

**Comment by chrissimpkins** [comment]
@gingerbeardman here is the fix for the Homebrew Python / system Python issue:

https://github.com/googlefonts/tools/issues/40#issuecomment-347694194 

It may not matter here anymore but it will fix other Python issues that are bound to come up on OS X with this problem.

**Comment by gingerbeardman** [comment]
Thanks, I eventually spotted that but had got in such a mess it was easier to nuke homebrew (and thus newer python) and start again. Just checked my .bash_profile and i did use that caveat method. annoying that it doesn't pause for user input when it displays that!!!
