### ISSUE TITLE
Post table problem after straight ttf>ttx>ttf (no changes)

### ISSUE THREAD

**Issue by gingerbeardman** [fonttools/fonttools#1119]
test fonts: http://ashokabuildcon.com/tushar/NewWebsite/css/fonts/

ttf/ttx/ttf#1 [files.zip](https://github.com/fonttools/fonttools/files/1509348/files.zip)

```bash
matt$ ttx tt0003c_.ttf 
Dumping "tt0003c_.ttf" to "tt0003c_.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'kern' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'PCLT' table...

matt$ ttx tt0003c_.ttx
Compiling "tt0003c_.ttx" to "tt0003c_#1.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'fpgm' table...
Parsing 'prep' table...
Parsing 'cvt ' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Parsing 'kern' table...
Parsing 'name' table...
Parsing 'post' table...
Parsing 'PCLT' table...

matt$ open tt0003c_#1.ttf 
```

Font Book says:
<img width="735" alt="screen shot 2017-11-28 at 10 02 10" src="https://user-images.githubusercontent.com/49612/33313657-3b68ac74-d423-11e7-8ed5-68a840b2bc28.png">

**Comment by jenskutilek** [comment]
This is the only change in the `post` table after recompilation:

![bildschirmfoto 2017-11-28 um 11 35 32](https://user-images.githubusercontent.com/3185950/33315672-9ce412be-d431-11e7-8ba8-c0acbdd8cb30.png)

I think hash symbols are not allowed in glyph names, perhaps that is the problem?

```xml
<psNames>
      <psName name="Delta#1" psName="Delta"/>
      <psName name="Omega#1" psName="Omega"/>
    </psNames>
```

**Comment by anthrotype** [comment]
The psName is what gets written in the post table, but since it may not be unique fonttools internally adds “#” to the name used in the GlyphOrder.

**Comment by anthrotype** [comment]
so, does FontBook also complain about the original font?

you could also try Apple's ftxvalidator command line tool (in the Apple Font Tools suite, google around), which should give you a more verbose output of what they think it's wrong.

**Comment by anthrotype** [comment]
I just checked. The font contains two glyphs named "Delta" and two glyphs named "Omega". The post table spec does not forbid duplicate names. In the original `post` table, one "Omega" glyph is mapped to index 159 in the Macintosh standard set, whereas the other "Omega" is in the extra names (indices > 258); the same for the two "Delta" glyphs: one is mapped to index 168 in the Macintosh set, the other is listed in the extra names.

Now, after roundtripping with fonttools, in the recompiled post table both the two Deltas and the two Omegas are listed in the extra names.

this is because we first check if a psName is in the extra names (both "Delta" and "Omega" are there, in the original post table), and only _after_ if it is in the standard order (both "Delta" and "Omega" are also listed here, but the first if branch already matched):
https://github.com/fonttools/fonttools/blob/1d6dd50d5246e0ee295eb5d2d363c68973be3a43/Lib/fontTools/ttLib/tables/_p_o_s_t.py#L166-L168

this is the reason for the the binary difference that @jenskutilek noticed.

However, having said that, I'm still not sure why would FontBook complain.

Maybe, it's simply the fact that (both the original and roundtripped) font has duplicate glyph names, rather than the fact that they are encoded as standard or extra names.

could someone with a mac try to see if the original font also gets the invalid post table error message?

**Comment by jenskutilek** [comment]
FontBook doesn't complain about the original font.

**Comment by anthrotype** [comment]
we could check if a psName is in both extraDict and standardGlyphOrder, and if so, add it to the latter, but only the first time; all subsequent psNames that happen to be in both, we only add to the extra names set.

wdyt?

**Comment by justvanrossum** [comment]
What if we change the renaming scheme to `Delta.1`?

**Comment by anthrotype** [comment]
but then we won't be able to roundtrip anymore. I prefer to keep what was there.

can you try to apply this patch and check again in FontBook?

```diff
diff --git a/Lib/fontTools/ttLib/tables/_p_o_s_t.py b/Lib/fontTools/ttLib/tables/_p_o_s_t.py
index 5cf430ef..a7243abf 100644
--- a/Lib/fontTools/ttLib/tables/_p_o_s_t.py
+++ b/Lib/fontTools/ttLib/tables/_p_o_s_t.py
@@ -157,13 +157,20 @@ class table__p_o_s_t(DefaultTable.DefaultTable):
 		extraNames = self.extraNames
 		for i in range(len(extraNames)):
 			extraDict[extraNames[i]] = i
+		duplicates = set()
 		for glyphID in range(numGlyphs):
 			glyphName = glyphOrder[glyphID]
 			if glyphName in self.mapping:
 				psName = self.mapping[glyphName]
 			else:
 				psName = glyphName
-			if psName in extraDict:
+			if psName in standardGlyphOrder and psName in extraDict:
+				if psName in duplicates:
+					index = 258 + extraDict[psName]
+				else:
+					index = standardGlyphOrder.index(psName)
+					duplicates.add(psName)
+			elif psName in extraDict:
 				index = 258 + extraDict[psName]
 			elif psName in standardGlyphOrder:
 				index = standardGlyphOrder.index(psName)
```

**Comment by anthrotype** [comment]
with that patch the Omega and Delta are encoded in the same way as the original post table.

there's still one byte difference, because in the original the glyph "pi" was in the extra name whereas it *should* have been in the standard set.

**Comment by twardoch** [comment]
I'd be in favor of writing duplicate names *or* using a suffix with a period, but *not* with a hash :)

**Comment by anthrotype** [comment]
I say it again: we have never written duplicate names with a hash.
maybe the comment that TTX writes is not clear enough.

```xml
    <psNames>
      <!-- This file uses unique glyph names based on the information
           found in the 'post' table. Since these names might not be unique,
           we have to invent artificial names in case of clashes. In order to
           be able to retain the original information, we need a name to
           ps name mapping for those cases where they differ. That's what
           you see below.
            -->
      <psName name="Delta#1" psName="Delta"/>
      <psName name="Omega#1" psName="Omega"/>
    </psNames>
```

**Comment by gingerbeardman** [comment]
Thanks for all the input so far!

Looks like all queries were answered before my return.

**Comment by gingerbeardman** [comment]
ftxvalidator output

```bash
$ ftxvalidator tt0003c.ttf 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>kATSFontTestResultKey</key>
	<array>
		<string>kATSFontTestSeverityInformation</string>
		<string>kATSFontTestSeverityMinorError</string>
	</array>
</dict>
</plist>
```

```bash
$ ftxvalidator tt0003c_#1.ttf 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>kATSFontTestResultKey</key>
	<array>
		<string>kATSFontTestSeverityInformation</string>
		<string>kATSFontTestSeverityFatalError</string>
		<string>kATSFontTestSeverityMinorError</string>
	</array>
</dict>
</plist>
```

**Comment by anthrotype** [comment]
thanks, but that doesn't help much. I remember there were some options to get more detailed information on a per-table basis. Unfortunately I don't have a mac at hand right now.

If you save that patch to a text file, and do
```
$ git apply post.diff
```

then pass the original font through the patched ttx, and test again in FontBook, does it still raise the error in post table?

**Comment by gingerbeardman** [comment]
Yes

**Comment by gingerbeardman** [comment]
I'm also seeing more than one byte difference?

```
cmp -l tt0003c_#1.ttf tt0003c_#2.ttf 
  115   4  76
  116 306 276
  263 312 126
  264 142 162
  286 102 103
  287 344  36
  288 200 170
```

**Comment by anthrotype** [comment]
It still complains?! You 100% sure you are using the fonttools you modified? (pip install -e .)
I explained the one byte difference above (the “pi” glyph).

**Comment by gingerbeardman** [comment]
I'm not 100% sure, I installed font tools through pip so patched the file at `/Library/Python/2.7/site-packages/fontTools/ttLib/tables/` which is the only location on my computer that file was found.

**Comment by anthrotype** [comment]
Ok. I’ll check on my Mac once I get home tonight

**Comment by gingerbeardman** [comment]
@jenskutilek what app are you using to do hex compare?

**Comment by gingerbeardman** [comment]
OK I found the extra option, this is the ttf>ttx>ttf font as in the OP, not with the patch

$ ftxvalidator -T tt0003c_#1.ttf

```
Swiss 721 WGL4 BT
	Swiss721BT-Roman
	DD2ECA62|Swiss 721
	kATSFontTestTrueTypeFontData
	Fatal Minor Info 
	com.apple.TrueType.cmap.usability
		‘cmap’ table usability
		This test ensures the ‘cmap’ table has at least one usable subtable.
		NA
			(No messages)
	com.apple.TrueType.hmtx.usability
		‘hmtx’ table usability
		This test ensures the horizontal metrics table, ‘hmtx’, is valid.
		Info 
			hmtx: Glyph 176 has a width of 2363, which is greater than the font\U2019s em (2048); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 198 has a width of 2587, which is greater than the font\U2019s em (2048); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 328 has a width of 965, which is greater than 40 percent of the font\U2019s em (that is, 819); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 329 has a width of 965, which is greater than 40 percent of the font\U2019s em (that is, 819); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 331 has a width of 965, which is greater than 40 percent of the font\U2019s em (that is, 819); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 333 has a width of 965, which is greater than 40 percent of the font\U2019s em (that is, 819); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 340 has a width of 965, which is greater than 40 percent of the font\U2019s em (that is, 819); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 346 has a width of 965, which is greater than 40 percent of the font\U2019s em (that is, 819); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 352 has a width of 965, which is greater than 40 percent of the font\U2019s em (that is, 819); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 371 has a width of 1024, which is greater than 40 percent of the font\U2019s em (that is, 819); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 565 has a width of 2169, which is greater than the font\U2019s em (2048); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 566 has a width of 2230, which is greater than the font\U2019s em (2048); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 595 has a width of 2120, which is greater than the font\U2019s em (2048); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 596 has a width of 2136, which is greater than the font\U2019s em (2048); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 601 has a width of 2111, which is greater than the font\U2019s em (2048); this may be incorrect.
				kATSFontTestSeverityInformation
			hmtx: Glyph 652 has a width of 2173, which is greater than the font\U2019s em (2048); this may be incorrect.
				kATSFontTestSeverityInformation
	com.apple.TrueType.loca.usability
		‘loca’ table usability
		This test ensures the glyph data location table, ‘loca’, is valid.
		NA
			(No messages)
	com.apple.TrueType.name.usability
		‘name’ table usability
		This test ensures the ‘name’ table is valid.
		NA
			(No messages)
	com.apple.TrueType.post.usability
		‘post’ table usability
		This test ensures the ‘post’ table is valid.
		Fatal 
			post: The name data overflow the table bounds.
				kATSFontTestSeverityFatalError
	com.apple.TrueType.usability
		‘sfnt’ required tables
		This test ensures the ‘sfnt’ has all the required tables.
		NA
			(No messages)
	com.apple.TrueType.head.structure
		‘head’ table structure
		This test ensures the structure of the header table, ‘head’, accords with the specification.
		NA
			(No messages)
	com.apple.TrueType.hhea.structure
		‘hhea’ table structure
		This test ensures the structure of the horizontal header table, ‘hhea’, accords with the specification.
		NA
			(No messages)
	com.apple.TrueType.maxp.structure
		‘maxp’ table structure
		This test ensures the structure of the maximum profile table, ‘maxp’, accords with the specification.
		Minor 
			maxp: The table\U2019s maxSizeOfInstructions field is 2827; it should be 206
				kATSFontTestSeverityMinorError
	com.apple.TrueType.name.structure
		‘name’ table structure
		This test ensures the ‘name’ table is structurally sound.
		NA
			(No messages)
	com.apple.TrueType.glyf.usability
		‘glyf’ table structure
		This test ensures the ‘glyf’ table is structurally sound.
		Info 
			glyf: Glyph 1 has no visual appearance
				kATSFontTestSeverityInformation
			glyf: Glyph 2 has no visual appearance
				kATSFontTestSeverityInformation
			glyf: Glyph 3 has no visual appearance
				kATSFontTestSeverityInformation
			glyf: Glyph 172 has no visual appearance
				kATSFontTestSeverityInformation
	com.apple.TrueType.glyf.instructions
		‘glyf’ table instructions
		This test ensures the instructions embedded in a ‘glyf’ table are sound.
		NA
			(No messages)
	com.apple.TrueType.fpgm.instructions
		‘fpgm’ table instructions
		This test ensures the instructions embedded in a ‘fpgm’ table are sound.
		NA
			(No messages)
	com.apple.TrueType.prep.instructions
		‘prep’ table instructions
		This test ensures the instructions embedded in a ‘prep’ table are sound.
		NA
			(No messages)
	com.apple.TrueType.kern.structure
		‘kern’ table structure and contents
		This test ensures the kerning table, ‘kern’, is valid.
		NA
			(No messages)
	com.apple.duplicates
		Duplicate fonts
		This test verifies the presence of installed fonts with the same name.
		NA
			(No messages)
```

**Comment by anthrotype** [comment]
Hm, sounds bad.
And what about the original font, and the one after tha patch is applied?

**Comment by anthrotype** [comment]
ok, I run ftxvalidator on the roundtripped font after applying the patch and now it says

```
	com.apple.TrueType.post.usability
		‘post’ table usability
		This test ensures the ‘post’ table is valid.
		Technical
			post: The table has more name data than are required for the glyphs in the font.
				kATSFontTestSeverityTechnicalError
```

so the severity is now "technical", whatever that means

The original font does't raise any warning/error though. 😟

**Comment by anthrotype** [comment]
note that even with the patch applied the ttx files are the same because this is a low level difference in the way the table bytes are packed. They have the same content as far as ttx is concerned. It's just ftxvalidator or FontBook that complain for some reason which I haven't figured out yet.

**Comment by gingerbeardman** [comment]
Ah, thanks for the explanation. I need to get up to speed on a lot of this.

**Comment by anthrotype** [comment]
https://www.sweetscape.com/010editor is an opensource hex editor that can parse TTF files

there's also synalyze it! pro (commercial app) 

i'll debug this tomorrow, thanks @gingerbeardman for bringing this up

**Comment by gingerbeardman** [comment]
my pleasure, i'm interested in the reason and the resolution.

I have synalyze it! pro, it's great. i used it recently to map an old game rom as a grammar.

**Comment by chrissimpkins** [comment]
Is any of that Font Book validation source open?   I have been manually running that with font releases...

**Comment by anthrotype** [comment]
I believe ftxvalidator uses the same API as FontBook, so you can automate running the former with some shell script.
you can get it from https://developer.apple.com/download/more/?=font

I don't think it's "open source" though

**Comment by gingerbeardman** [comment]
As above, output seems relatively easy to digest/parse in code thanks to the tab indentation

**Comment by anthrotype** [comment]
I think df1e8c7 fixes it

@gingerbeardman could you please try to install fonttools from github and confirm this fixes the issue?
you can do something like

```
python -m pip install --upgrade --editable git+https://github.com/fonttools/fonttools#egg=fonttools
```

Note that this time you should see a few differences in the ttx dumps between the original and the round-tripped font. This is because the original had three glyhps ("pi", "Omega" and "Delta") in the extra names (index > 258), but those names are already in the standard macintosh set, so they don't need to be explicitly listed there. ftxvalidator is very picky about that.

I should probably add some unit tests for post table at some point.

**Comment by gingerbeardman** [comment]
Boom. It's fixed. Nicely done! Thanks for everything.

So it was the duplicate glyphs in extra names that were the problem with ftxvalidator?

Aside: if you're interested, those ancient Bitstream ttNNNNc_.ttf files are used on my old Sony eBook Reader but it only shipped with regular sans/serif/mono. By completing those families the device now uses the proper weights, whereas previously it synthesised b/i/bi using the regular weight. The device is also quite particular about the font names so I am using ttx to rename the Pan-European WGL4 fonts as non-WGL4 fonts. 👍

**Comment by anthrotype** [comment]
great!

> So it was the duplicate glyphs in extra names that were the problem with ftxvalidator?

I think so, yes
