### ISSUE TITLE
[subset] retain feature without adding all glyphs

### ISSUE THREAD

**Issue by justanotherfoundry** [fonttools/fonttools#1121]
Sorry if this has been asked before.

In my webfonts, I would like to keep superior 1, 2 and 3, and they should be available via the sups feature. Is this possible?

• I have defined exactly the glyphs I want to keep in the final font. The basic subsetting works as expected.
• If I add sups to options.layout_features then it force-retains all superiors, which I do not want.
• If I do not add sups to options.layout_features then the sups feature is removed entirely although three of the glyphs used by it are still in the font.

Of course, there are similar scenarios for other features I would like to retain, but not without force-adding all the associated glyphs.

Thanks!

**Comment by justanotherfoundry** [comment]
By the way, the doc says, “Glyph variants used by the preserved features are added to the specified subset glyph set.” Maybe it could be clearer about what “used by” means?
As far as I have tried, it adds only target glyphs, i.e. those that will be substituted for a glyph that is retained in any case?

**Comment by twardoch** [comment]
We had a discussion about this a long time ago:
https://github.com/fonttools/fonttools/issues/43

**Comment by behdad** [comment]
Yeah this seems like a distinct feature.  Current subsetter produces a font that is functionally identical to the original file.  This feature goes against that.

Looks like might be easier done by a tool / feature to remove certain glyphs (and paths to getting them).

**Comment by justanotherfoundry** [comment]
Thanks for your comments. I had a feeling this ma have been discussed before, just didn’t look back far enough.
Looks like the --partial-features option as described by Adam is exactly what would solve my problem (and what I would even have expected to be the default behaviour).

> Current subsetter produces a font that is functionally identical to the original file. This feature goes against that.

Not sure I understand how you mean that. As soon as I remove any glyphs or features the font is no longer functionally identical, is it?

---

So, for me this is simply a practical problem.

I have moved from pre-subset FontLab source files to subsetting on export via Macro to using fonttools for subsetting, which is more elegant and powerful as it allows me to easily add (i.e. retain) more glyphs if a client wants them in their webfonts. Unfortunately, the removal of partial features is thwarting this otherwise elegant system.

For now, my work-around is to retain all glyphs on export but to manually comment out those lines in the feature code that would otherwise force-add glyphs I do not want in my final webfonts. Doesn’t feel like the perfect solution, though.

**Comment by behdad** [comment]
> Current subsetter produces a font that is functionally identical to the original file. This feature goes against that.
> 
> Not sure I understand how you mean that. As soon as I remove any glyphs or features the font is no longer functionally identical, is it?

Functionally identical for same input text, if such text is supported by the subset font.

**Comment by twardoch** [comment]
If you use text, then it makes sense. But the subsetter also accepts a list of glyphs — then we cannot really talk about "text" anymore. 

I think if I'm specifying text or Unicodes plus features, the subsetter should work as it does now, but if I provide a list of glyph identifiers, the subsetter should take that as the actual requirement, and then adapt the features and cmap accordingly. It should not add any more glyphs into the result except the glyphs need to render the conponents in the glyphs I request.

**Comment by twardoch** [comment]
Basically, we're taking about two kinds of inputs and outputs: 

1. I ask for Unicodes and features, and I get the glyphs that express my request (this works now)
2. What Tim is asking for (and I did, 4 years ago) is: I ask for glyphs, and I get the Unicodes and features that can be used to express my request

Then we subset.

**Comment by justvanrossum** [comment]
(Digesting this, and the 4-year-old thread, recapping mostly for my own understanding.)

Behdad's design for the subsetter clearly comes from a language perspective. OT features that are needed for language support for the requested character set better not be broken ("identical result for identical input, if all input is in subset"). The features that Tim and Adam are talking about are "advanced typographic" features which are often optional (the "d" in "dlig" gives that away :) ) and it should be up to the user to decide what's reasonable to keep and not to keep. Apparently pyftsubset currently doesn't really support that notion. I don't know pyftsubset well enough to see how much work it would be to implement the desired behavior, but it would be useful for many, I'm sure.

**Comment by justanotherfoundry** [comment]
In analogy to Adam’s comment, one could say that the two use cases for the subsetter are 

(1) The user subsets the font based on the text that is known to be used with the font.
(2) The foundry subsets the font based on their judgement of which glyphs are important, so as to find a balance of file size and usefulness, to create a general-purpose webfont.

Right now, the subsetter is nearly perfect for task (2). Why not make it perfect?

Maybe it boils down to the old question of what to leave up to the user, as Just mentioned. It seems engineers have always liked the idea of _not_ making decisions on behalf of the user (i.e. postponing decisions), whereas designers are used to _making decisions_ – in fact, that is what they are paid for. Maybe this is why Behdad rejects the idea of (2)?

At JAF, we put great effort into optimizing the file size of the general-purpose webfonts we offer, starting with the PS to TT conversion, manual hinting, composites, palettized kerning and, of course, the glyph set. Some glyphs create more file size than others, some characters bay be possible to omit, and maybe some characters need to be supported in their basic shape but do not really need the feature-based alternates. We end up with around 18 kB for the woff2 versions of our fonts. I believe if foundries try really hard to optimize the general-purpose fonts (and task (2) is part of this) then there is less need for (1). Speaking of Latin fonts, of course.

**Comment by justvanrossum** [comment]
Ideally, two components of the subsetter should be accessible separately:
1. based on characters and features, give me a list of glyphs that should stay
2. subset based on a specified list of glyphs

**Comment by behdad** [comment]
Don't get me wrong. I'm not rejecting the use case you are requesting. I was just describing my line of thinking when I wrote this code for years ago.

If we can fully spec the request I'll eventually implement it. I'm thinking about it already.

**Comment by anthrotype** [comment]
on a slightly related topic, I am thinking of adding support for subsetting features at the source level (the UFO features.fea) by adding a subsetGlyphs method to feaLib ast elements, i.e. the objects returned by the feaLib parser used to build OpenType tables, which already know how to serialize themselves back to string.

This is for fontmake to be able to subset the generated fonts at the source level rather than on the binary tables through the fonttools subsetter.

I'm thinking of a method to be added to all all ast elements that takes a set of glyph names and return True if there is something left or False if the whole element (e.g class definition, rule, block, etc.) has been emptied and should thus be dropped. E.g.

```python
def subsetGlyphs(self, subset):
    self.glyphs = [g for g in self.glyphs if g in subset]
    return bool(self.glyphs)
```

Do you think is worth it/reasonable thing to do, or am I putting myself in a can of worms?

(I know I should have opened a separate issue, sorry)

**Comment by jenskutilek** [comment]
What about nested classes like this:

```
@class12 = [@class1 @class2];
sub  @class12 @class3' by @class4;
```

Will the proposed mechanism know that class 12 is empty if both 1 and 2 are empty? Or maybe multiple subsetting passes are needed.

**Comment by anthrotype** [comment]
of course, yes. A class reference is empty if the class it points to is empty.

**Comment by anthrotype** [comment]
> Ideally, two components of the subsetter should be accessible separately:
> 1. based on characters and features, give me a list of glyphs that should stay
> 2. subset based on a specified list of glyphs

FYI, @behdad has just added a new `--no-layout-closure` that implements subsetting based on an explicit set of glyphs, with commit https://github.com/fonttools/fonttools/commit/022536212be4cf022a2cb9a286fec8be1931d19b

>   --no-layout-closure
>     Do not expand glyph set to add glyphs produced by OpenType layout
>     features.  Instead, OpenType layout features will be subset to only
>     rules that are relevant to the otherwise-specified glyph set.
