### ISSUE TITLE
[ttLib.tables.C_P_A_L] ValueError: invalid literal for int() with base 16: ''

### ISSUE THREAD

**Issue by TheEssemCraft** [fonttools/fonttools#1122]
Whenever I try to build my COLR/CPAL/GSUB font, it throws this error and crashes:

```
Parsing 'CPAL' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttx.py", line 389, in main
    process(jobs, options)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttx.py", line 363, in process
    action(input, output, options)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttx.py", line 274, in ttCompile
    ttf.importXML(input)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 374, in importXML
    reader.read()
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/xmlReader.py", line 48, in read
    self._parseFile(self.file)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/xmlReader.py", line 73, in _parseFile
    parser.Parse(chunk, 0)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/xmlReader.py", line 141, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/tables/C_P_A_L_.py", line 212, in fromXML
    color.fromXML(element[0], element[1], element[2], ttFont)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/tables/C_P_A_L_.py", line 258, in fromXML
    self.green = int(value[2:4], 16)
ValueError: invalid literal for int() with base 16: ''
```

I am using version 3.20.1. I have tried other versions, but they throw the same error. Here's the full log: https://travis-ci.org/TheEssemCraft/twemoji-colr/builds/311894231

**Comment by anthrotype** [comment]
it seems like in the ttx file of your CPAL table there is some "color" element which contains an empty "value" attribute. The value of the color "value" attribute must be an hex string (optionally prefixed with `#`), from 6 to 8 digits: 2 for red, 2 for green, 2 for blue and optionally 2 for alpha.
Ensure none of the color values are empty and retry, thanks

**Comment by anthrotype** [comment]
either empty, or incomplete. I see it's crashing on the green, so it may be that it only has the first two digits for red, and lacks the other four for green and blue... just guessing

**Comment by TheEssemCraft** [comment]
@anthrotype Would you mind telling me the index for this color element? Thanks.

**Comment by anthrotype** [comment]
I have no idea, sorry... you'll have to `grep` for it in your TTX file

**Comment by TheEssemCraft** [comment]
What's a possible regex I could use for this? I'm bad at making them.

**Comment by anthrotype** [comment]
try something like 
```
grep -Ern '<color .*value="#?[0-9A-Fa-f]+"' directorty/containing/*.ttx
```

or if you want to specify a specific number of hex digits, say minium 0, maximum 8, you could do

```
grep -Ern '<color .*value="#?[0-9A-Fa-f]{0,8}"' directorty/containing/*.ttx
```

**Comment by TheEssemCraft** [comment]
Never mind, I figured it out by just looking through the code. Here's the culprit:
```
<color index="65" value="ff"/>
```
As you can see, the value is just `ff`. I looked through my layerizing javascript, and I think I found something:
```
function expandColor(c) {
    if (c == undefined) {
        return c;
    }
    c = c.toLowerCase();
    if (c == 'none') {
        return c;
    }
    if (c == 'red') {
        c = '#f00';
    } else if (c == 'green') {
        c = '#0f0';
    } else if (c == 'blue') {
        c = '#00f';
    }
    // c is a hex color that might be shorthand (3 instead of 6 digits)
    if (c.substr(0, 1) == '#' && c.length == 4) {
        c = '#' + c.substr(1, 1) + c.substr(1, 1)
                + c.substr(2, 1) + c.substr(2, 1)
                + c.substr(3, 1) + c.substr(3, 1);
    }
    return c + 'ff';
}
```
So something is wrong with `c`. Any ideas? Here's the full script: https://github.com/TheEssemCraft/twemoji-colr/blob/master/layerize.js

**Comment by anthrotype** [comment]
I don't have the time to debug your javascript. I can only point you to the code where fontTools parses the CPAL color element from the TTX file: 

https://github.com/fonttools/fonttools/blob/f0e0954afc787d53c595a472c2346754c8f6f3d7/Lib/fontTools/ttLib/tables/C_P_A_L_.py#L253-L260

as you can see, it seems that (besides the optional leading `#` symbol) fonttools is expecting from 6 to 8 digits. The first three sets of digit pairs is for red green and blue. The fourth optional pair of digit is for the alpha and can be omitted.

So you have to make your script output colors in this format if you wish fonttools to be able to parse and compile it.

**Comment by TheEssemCraft** [comment]
Ok. Thanks!
