### ISSUE TITLE
3 problems (bugs?) in S_V_G_.py  - SVGinOT font with colorPalette

### ISSUE THREAD

**Issue by glukfonts** [fonttools/fonttools#1124]
Hello,
I try to compile my SVGinOpenType font with colorPalettes and found 3 bugs(?) in file **fontTools/ttLib/tables/S_V_G_.py**. I used great **fonttools/ttx 3.20.1**

1. in line 356 is:
	(356) colorPalette.fromXML( **(** name, attrib, content **)**, ttFont)              
	but in class colorPalette definition :
	(369) fromXML(self, name, attrs, content, ttFont)

2. for line 346 I have error message:
	(346) element = element.strip()
	 AttributeError: 'tuple' object has no attribute 'strip'
	
3. for line 288:
	(288) writer.writeraw(str(uiNameID))
	AttributeError: 'XMLWriter' object has no attribute 'writeraw'

I have successfully converted my .xml file to .ttf and from .ttf to .xml with 3 temporary corrections:
1. (line 356) colorPalette.fromXML(name, attrib, content, ttFont)
2. (line346) #element = element.strip() and I remove all spaces, newlines (\n) from my xml (<colorPalettes> part) :)
3. (288) writer._writeraw(str(uiNameID)) I use _writeraw method instead writeraw (Python 3.4.12)

Regards,
Grzegorz (gluk)

**Comment by behdad** [comment]
@anthrotype any chance you can check this?  Looks like SVG table can use some tests.
And if it's *that* untested in the wild, maybe it's ok if we change a bunch of how it works, which looked like might be needed last time I checked.

**Comment by anthrotype** [comment]
sure, I'll have a look when I'm back in January.

**Comment by anthrotype** [comment]
@glukfonts can you please check that it works after this commit c427494 ?

you can install fonttools from the github repository with pip
```
pip install -e git+https://github.com/fonttools/fonttools.git#egg=fonttools
```

or just `git clone https://github.com/fonttools/fonttools` then `cd fonttools` and `pip install -e .`

As you may know, the current SVG OpenType table uses the color palettes defined in the CPAL table instead of its own color palettes, as it was in earlier versions.

@readroberts @miguelsousa, to improve the test coverage of this module, it would be nice to have some test fonts. Do you know where I could find some good open-source SVG-OT fonts to add to the test suite?

**Comment by anthrotype** [comment]
@glukfonts fonttools 3.21.1 was just released, you should be able to simple `pip install --upgrade fonttools` and then try dumping your SVG table with that.
Please let me know if that works

**Comment by miguelsousa** [comment]
@anthrotype [EmojiOne Color](https://github.com/adobe-fonts/emojione-color). It doesn't have color palettes though.

**Comment by glukfonts** [comment]
Hello @anthrotype 
I have successfully converted my .xml file to .ttf and from .ttf to .xml with fontools 3.21.1dev0

I know that current SVGinOpenType table uses color palettes in CPAL table,  but so far no application support SVG OpenType+CPAL. I wanted to check if the previous version (with colorPalettes within S_V_G table) is supported in any application :)

Regards,
Grzegorz (gluk)

**Comment by miguelsousa** [comment]
@glukfonts neither setup of colorPalettes is supported anywhere at the moment, AFAIK. It's unlikely that the non-CPAL setup will ever be supported.
