### ISSUE TITLE
ttx: out of range error converting Neue Haas Grotesk TTF

### ISSUE THREAD

**Issue by gingerbeardman** [fonttools/fonttools#1126]
Source of the TTF files:
https://github.com/cid-harvard/atlas-economic-complexity/find/06ee6ee01fc692a983321aceea8325b8834260c2
search for ".ttf"

This zip will last 14 days (feel free to edit/remove the link out when you've downloaded): https://transfer.sh/tsaQu/nhg.zip

Generally the error is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/ttProgram.py", line 235, in toXML
    assembly = self.getAssembly()
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/ttProgram.py", line 229, in getAssembly
    self._disassemble(preserve=preserve)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/ttProgram.py", line 461, in _disassemble
    value = (bytecode[i] << 8) | bytecode[i+1]
IndexError: array index out of range

ERROR: An exception occurred during the decompilation of glyph program:
```

Terminal output:
https://gist.github.com/gingerbeardman/d22ea80c3c4aae5353a930040522cd73

ttx --version
3.20.1

ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88

**Comment by anthrotype** [comment]
hm.. the hinting data in those fonts seem to be broken. Where did they come from?

**Comment by gingerbeardman** [comment]
from the cid-harvard GitHub project I linked 😨

**Comment by anthrotype** [comment]
the error is saying that our ttProgram module's `opcodeDict` is missing the opcode with value `64`.
Now, that op code is indeed missing if I pretty-print that dictionary:

```
[...]
62: ('MIAP', 1, 62, 'MoveIndirectAbsPt'),
 63: ('MIAP', 1, 62, 'MoveIndirectAbsPt'),
 66: ('WS', 0, 0, 'WriteStore'),
 67: ('RS', 0, 0, 'ReadStore')
[...]
```

I don't know...

**Comment by anthrotype** [comment]
ignore what I wrote, sorry... 0x40 (or 64 in decimal) is the opcode of NPUSHB (the KeyError is normal, as those special opcodes are handled separately).

The real issue is the IndexError at line 455, which happens probably because the instruction stream for that glyf was truncated somehow, as the NPUSHB is requesting to read more values than are in the bytecode array.

Yes, definitely a broken font.

**Comment by gingerbeardman** [comment]
Ah, sorry for wasting time. I should have checked...

Font Book and ftxvalidator also complain.

**Comment by gingerbeardman** [comment]
Here's a FontVal page for one of the files.

A bunch of warnings but only one error, usWeightClass not valid value.

> Font Validator Report - ed18aa48-557e-4d1f-a53c-58399a7c1bc4.ttf
> 
> Show	 Info	 Pass	 Warning	 Error
> Run DateTime:	13 December 2017 16:23
> Machine Name:	MacBookPro-Matt
> Font file:	/Users/matt/Downloads/2017-12-13/nhg/ed18aa48-557e-4d1f-a53c-58399a7c1bc4.ttf
> 
> Error code	Message	Details
> 
> Index: 0, NeueHaasGroteskDisp W01, Version 1.01, 06/05/2014
> 
> 
> Table Tag	Table Offset	Table Length	Table Checksum
> OS/2	0x0000010c	0x00000060	0x65be6180
> VDMX	0x0000016c	0x000005e0	0x6e07758a
> cmap	0x0000074c	0x0000017a	0x9aa8ba11
> cvt	0x000008c8	0x000001e2	0x08370950
> fpgm	0x00000aac	0x00000aa2	0x630e9dd9
> gasp	0x00001550	0x00000008	0xffff0004
> glyf	0x00001558	0x00007aa0	0x8289b696
> head	0x00008ff8	0x00000036	0xfc4ffd8e
> hhea	0x00009030	0x00000024	0x07e40460
> hmtx	0x00009054	0x00000370	0xba7c20a2
> kern	0x000093c4	0x0000b444	0xecf7ffdc
> loca	0x00014808	0x00000374	0x00322710
> maxp	0x00014b7c	0x00000020	0x03340110
> name	0x00014b9c	0x0000167d	0x997e85d2
> post	0x0001621c	0x00000020	0xff880014
> prep	0x0001623c	0x00000257	0xa3e08d9d
> 
> General Font Information
> Error code	Message	Details
> W0022	Recommended table is missing	hdmx
> W0022	Recommended table is missing	DSIG
> W0020	Tables are not in optimal order	table 'OS/2' precedes table 'head'
> 
> 
> OS/2
> 
> Error code	Message	Details
> W2106	The version number is valid, but less than 5	3
> E2133	The usWeightClass is not a valid value	450
> W2101	A CodePage bit is set in ulCodePageRange, but the font is missing some of the printable characters from that codepage	bit #4, Turkish (missing chars: U011E U0130 U015E U011F U015F)
> W2101	A CodePage bit is set in ulCodePageRange, but the font is missing some of the printable characters from that codepage	bit #19, Korean Wansung (17003 missing, first ten missing chars are: UAC02 UAC03 UAC05 UAC06 UAC0B UAC0C UAC0D UAC0E UAC0F UAC18)
> W2101	A CodePage bit is set in ulCodePageRange, but the font is missing some of the printable characters from that codepage	bit #21, Korean Johab (17019 missing, first ten missing chars are: U11A8 U11A9 U11AA U11AB U11AC U11AD U11AE U11AF U11B0 U11B1)
> W2101	A CodePage bit is set in ulCodePageRange, but the font is missing some of the printable characters from that codepage	bit #29, Mac character set (23 missing, first ten missing chars are: U2260 U221E U2264 U2265 U2202 U2211 U220F U03C0 U222B U2126)
> W2101	A CodePage bit is set in ulCodePageRange, but the font is missing some of the printable characters from that codepage	bit #56, IBM Turkish (34 missing, first ten missing chars are: U0130 U015E U015F U011E U011F U2591 U2592 U2593 U2502 U2524)
> W2101	A CodePage bit is set in ulCodePageRange, but the font is missing some of the printable characters from that codepage	bit #62, WE/Latin 1 (30 missing, first ten missing chars are: U2591 U2592 U2593 U2502 U2524 U2563 U2551 U2557 U255D U2510)
> 
> 
> VDMX
> 
> Error code	Message	Details
> W2500	The VDMX data doesn't match the data calculated by the rasterizer	The differences were smaller than the tolerance, so they may well be valid if the VDMX was hand-tuned
> 
> 
> cmap
> 
> Error code	Message	Details
> W0302	The table does not contain any Apple subtables	
> W0301	Apple logo mapping test not performed, cmap 1,0 not present	
> 
> 
> cvt 
> 
> Error code	Message	Details
> 
> 
> fpgm
> 
> Error code	Message	Details
> 
> 
> gasp
> 
> Error code	Message	Details
> 
> 
> glyf
> 
> Error code	Message	Details
> W1111	Duplicated knots	Glyph index 8
> W1111	Duplicated knots	Glyph index 9
> W1111	Duplicated knots	Glyph index 23
> W1111	Duplicated knots	Glyph index 91
> W1111	Duplicated knots	Glyph index 113
> W1112	Not all extremes are marked with the on-curve control points	Glyph index 199
> 
> 
> head
> 
> Error code	Message	Details
> W1302	Non-linear scaling flag (bit 4) is set, but hdmx table is not present	
> W1303	Non-linear scaling flag (bit 4) is set, but LTSH table is not present	
> W1313	The unitsPerEm value is not a power of two	1000
> 
> 
> hhea
> 
> Error code	Message	Details
> 
> 
> hmtx
> 
> Error code	Message	Details
> 
> 
> kern
> 
> Error code	Message	Details
> 
> 
> loca
> 
> Error code	Message	Details
> 
> 
> maxp
> 
> Error code	Message	Details
> 
> 
> name
> 
> Error code	Message	Details
> W2004	The description strings are inconsistent	(1,0,0,10)='Designed by Christian Schwartz 2004?2010. Originally designed 1957-1961 by Max Miedinger with art direction by Eduard Hoffmann. Released as Neue Haas Grotesk by the Haas'sche Schriftgiesserei, and then revised and released as Helvetica by Linotype AG. Revival originally commissioned in 2004 by Mark Porter at The Guardian. Completed in 2010 for Richard Turley at Bloomberg Businessweek. Thinnest weight designed by Berton Hasebe.', (3,1,1033,10)='Designed by Christian Schwartz 20042010. Originally designed 1957-1961 by Max Miedinger with art direction by Eduard Hoffmann. Released as Neue Haas Grotesk by the Haas'sche Schriftgiesserei, and then revised and released as Helvetica by Linotype AG. Revival originally commissioned in 2004 by Mark Porter at The Guardian. Completed in 2010 for Richard Turley at Bloomberg Businessweek. Thinnest weight designed by Berton Hasebe.'
> 
> 
> post
> 
> Error code	Message	Details
> W2304	Apple recommends against using post table format 3 under most circumstances	
> 
> 
> prep
> 
> Error code	Message	Details
> 
> 
> Rasterization Test, BW
> 
> Error code	Message	Details
> 
> 
> Rasterization Test, Grayscale
> 
> Error code	Message	Details
> 
> 
> Rasterization Test, ClearType
> 
> Error code	Message	Details
> 
> 
> Note: The Font Validator's helpfile contains detailed information about each error message. The latest OpenType specification is available at the Microsoft Typography website.

[FontVal.pdf](https://github.com/fonttools/fonttools/files/1556226/FontVal.pdf)
