### ISSUE TITLE
License assignment seems off

### ISSUE THREAD

**Issue by CJ-Wright** [fonttools/fonttools#1127]
The license assignment in the docs says "BSD-style" but it seems to most closely match an [MIT](https://fedoraproject.org/wiki/Licensing:MIT#Old_Style_with_legal_disclaimer) style.
Can I get some clarification?

**Comment by anthrotype** [comment]
oops.. you're actually right! The text is almost identical to the MIT license.

@justvanrossum?

**Comment by justvanrossum** [comment]
The let's make the docs say "MIT-style".

**Comment by CJ-Wright** [comment]
all credit to @synapticarbors

**Comment by anthrotype** [comment]
Thanks for spotting!

how about this? 783abb6

I wonder how it could have been wrong for so many years..

**Comment by CJ-Wright** [comment]
Awesome! Thank you!
