### ISSUE TITLE
EBDT section in inconsistent order.

### ISSUE THREAD

**Issue by jarrodlombardo** [fonttools/fonttools#1131]
When running ttx multiple times on the same file, I get different ttx files each time. The <EBDT> section is in a different order each time. With the example input ttf file, I get one of 4 different output ttx, seemingly at random. Attached is the ttf and 4 different output ttx.

[cour.zip](https://github.com/fonttools/fonttools/files/1569238/cour.zip)

**Comment by jarrodlombardo** [comment]
I've only experienced this issue with this one file. The other ~50 ttf files I've run ttx on give the same single ttx consistently. I'm using fonttools 3.20.1.

**Comment by anthrotype** [comment]
Thanks. That code is not very well tested (not sure even if it’s tested at all).
It’s probably written with python 2 in mind, and now with python 3 there is some unsorted collection like a set or a dict which gets randomised at every run (it’s a feature of py3)

**Comment by anthrotype** [comment]
In the meantime as a workaround, you could try setting the PYTHONHASHSEED environment variable (set it to any integer value), and you should get deterministic output also on Python 3.

**Comment by behdad** [comment]
Hopefully fixed with Python 3. Closing as no one is working on EBDT.
