### ISSUE TITLE
Subsetted font cannot be used as webfont

### ISSUE THREAD

**Issue by MatTheCat** [fonttools/fonttools#1134]
I tried subsetting Roboto-Regular.otf v2.138 but resulting woff and woff2 files cannot be used as webfonts. Chrome just says

> Failed to decode downloaded font

but ots-sanitize (6.1.1) returns

> File sanitized successfully!

I used these commands (fonttools 3.21.0):

```bash
pyftsubset --output-file=normal.woff --flavor=woff --with-zopfli --text-file=glyphs.txt --desubroutinize out/RobotoOTF/Roboto-Regular.otf

pyftsubset --output-file=normal.woff2 --flavor=woff2  --text-file=glyphs.txt --desubroutinize out/RobotoOTF/Roboto-Regular.otf
```

Did I make a mistake? Or how can I debug this?

**Comment by anthrotype** [comment]
The command line you used is correct. Can you post the contents of the glyphs.txt file so we could try to replicate this?
What version of chrome?

**Comment by MatTheCat** [comment]
I'm using Chrome 63.0.3239.108 but fonts don't work on Firefox 57.0.2 either (I didn't test on any other).

glyphs.txt contains

```
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¥¨©«®´¸»¿ÀÁÂÃÄÆÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜßàáâãäæçèéêëìíîïñòóôõöùúûüÿŒœŸˆ˚˜–—‘’‚“”„•…‹›€™
```

**Comment by anthrotype** [comment]
Thanks.
Where did you download robotics from?
if you don’t subset the fonts, do they load?

**Comment by anthrotype** [comment]
*Roboto, not “robotics”

(I’m typing from my phone)

**Comment by MatTheCat** [comment]
> Where did you download robotics from?

I cloned the google/roboto repository and followed the instructions.

> if you don’t subset the fonts, do they load?

I'll try

**Comment by MatTheCat** [comment]
Ouch Chrome cannot load the original OTF file I might had to start here sorry. Unless you see what's wrong I'll open an issue on their repo, thanks!
