### ISSUE TITLE
[ttx] add option to keep head modified timestamp

### ISSUE THREAD

**Issue by MalcolmWooden** [fonttools/fonttools#1135]
When compiling from ttx to font file the head "modified" timestamp is always updated to the current date/time, even if the --recalc-timestamp option is used or not.

**Comment by anthrotype** [comment]
Hi Malcolm,
no, it's not set to the current time, unless to you pass --recalc-timestamp.
By default the head.modified field is set to the modification time of the TTX file itself:

https://github.com/fonttools/fonttools/blob/5e23b0545ba78f9ce27d8f758edfe4dd0ed5395b/Lib/fontTools/ttx.py#L276-L279

It's true that there currently is no option to keep the original TTF's `modified` value. Only to either update to current date (with --recalc-timestamp), or to use the TTX file's modification time (without option).

Maybe we could add a --no-recalc-timestamp option as well, that would mean "do not touch the original modified timestamp".

I'll look into it when I get the change, thanks for the report.

**Comment by MalcolmWooden** [comment]
Hi Cosimo,
Thanks for looking at this, I was trying to update a bunch of fonts to have the same modification date and time by editing the "modified" value in the <head> table of the ttx files. I didn't catch on that ttx uses the ttx file's timestamp for this value.

It maybe a useful option to have - make modified value as stated in the ttx file.

**Comment by khaledhosny** [comment]
You can use `SOURCE_DATE_EPOCH` env variable I think, by setting it to the original font modification time.

**Comment by anthrotype** [comment]
> You can use SOURCE_DATE_EPOCH env variable

hm, it should.. but if you look at the code I linked to above, it looks like the TTX modification timestamp will prevail when compiling a TTX file from the ttx command line script.

That would be a bug indeed.

**Comment by anthrotype** [comment]
actually it works if you set SOURCE_DATE_EPOCH _and_ also pass --recalc-timestamp option to ttx (thus skipping that if statement), which is slightly counter-intuitive to me.
Or perhaps it's fine.

**Comment by anthrotype** [comment]
ok, it's by design. Sourcing the environment variable is done inside timestampNow, which in turn is only called if `recalcTimestamp` (argument to TTFont constructor) is True, else the modified fields is kept as it was:

https://github.com/fonttools/fonttools/blob/5e23b0545ba78f9ce27d8f758edfe4dd0ed5395b/Lib/fontTools/ttLib/tables/_h_e_a_d.py#L67-L68

So, @MalcolmWooden for the time being you could do something like this:

```
$ export SOURCE_DATE_EPOCH=012345789
$ ttx --recalc-timestamp MyFont.ttx
```

the original timestamp to use with SOURCE_DATE_EPOCH you can read with this script:

```python
import sys
from fontTools.ttLib import TTFont
from fontTools.misc.timeTools import epoch_diff

font = TTFont(sys.argv[1])
source_date_epoch = font['head'].modified + epoch_diff

print(source_date_epoch)
```

you need to add `epoch_diff` because SOURCE_DATE_EPOCH uses the Unix epoch (1970) whereas the opentype epoch is 1904.

**Comment by bjh21** [comment]
Looks like `--no-recalc-timestamp` was added by #1455, so this issue is resolved now.
