### ISSUE TITLE
Add support for MERG table

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1138]
https://www.microsoft.com/typography/otspec/merg.htm

See https://github.com/googlei18n/noto-fonts/issues/1009#issuecomment-355206909

**Comment by behdad** [comment]
Note that MERG table seems to be one of those dead-on-arrival ones.  One person commented: "What’s more, Microsoft has shipped fonts with the same 12-byte MERG that does not specify any overlaps."

**Comment by khaledhosny** [comment]
Well the spec says:
> If a 'MERG' table is provided but there no declarations are made for any pairs, then the intended interpretation is that no merging is necessary. (Some implementations may still merge glyphs before antialiasing, however.)

**Comment by khaledhosny** [comment]
But anyway, the fact that the rasterizer needs to know if the glyph run is RTL or LTR means FreeTYpe can’t practically use this, and most likely any rasterizer that is not tied to a layout engine.

**Comment by behdad** [comment]
Closing until someone implements.
