### ISSUE TITLE
misc.bezierTools.calcQuadraticArcLength(...approximate_fallback...)

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1142]
I just noticed (by way of https://github.com/robofab-developers/fontPens/pull/6) the `approximate_fallback=False` in the fonttools API. I think that should be removed. Instead, we should document what the approximate error of `approximateQuadraticArcLength` is, and how the speed compares to `calcQuadraticArcLength`.

We should also move the _addCubicRecursive  from perimeterPen to bezierTools as an alternative to `approximateCubicArcLength` and call it something, don't know what. Also, document approximate error of `approximateCubicArcLength`.

cc @jenskutilek @anthrotype

**Comment by anthrotype** [comment]
ok. What is the approximate error of approximateQuadraticArcLength and approximateCubicArcLength?

the fallback behaviour can be reimplemented in fontPens.

**Comment by behdad** [comment]
See perimeterPen constructor for empirical approximate errors of those.

**Comment by behdad** [comment]
I'm not even sure what the fallback is supposed to do.  Right now it's called when a cusp is detected.  I'll go ahead and just fix the cusp case in the code.

**Comment by behdad** [comment]
I'm working removing fallback and implementing cusp now.

**Comment by behdad** [comment]
Please fix fontPen to remove the approximate_fallback argument.

**Comment by behdad** [comment]
We should add `_addCubicRecursive` as `calcCubicArcLength` that takes tolerance.  We can add a tolerance argument to `calcQuadraticArcLength` as well, even though that function always computes the exact length.

**Comment by behdad** [comment]
Re the error of the `approximateQuadraticArcLength`, as can be seen in the https://github.com/fonttools/fonttools/commit/5dd888da1da0dc3e4c14df8825433a08392bb80d commit, the error can be up to 14% for the most degenerate case.  But for well-behaved curves it's much much smaller. Same about the Cubic one.  Ok, maybe leave out the error thing, just say these are very fast fairly accurate approximations.

**Comment by anthrotype** [comment]
>  We can add a tolerance argument to calcQuadraticArcLength as well, even though that function always computes the exact length

hm, I don't see why..
