### ISSUE TITLE
subsetter needs an option to drop outlines for LRM, RLM, ZWJ, and ZWNJ

### ISSUE THREAD

**Issue by roozbehp** [fonttools/fonttools#1146]
Currently the subsetter has an option to drop the outlines for notdef, but it could also drop outlines for LRM, RLM, ZWJ, and ZWNJ with practically no loss of functionality too. Many fonts contain outlines for these characters (due to https://www.microsoft.com/typography/otfntdev/glyphs.htm) that almost never end up getting used.

**Comment by moyogo** [comment]
Would it make sense to replace `--no-notdef-outline` by something like `--drop-outline-gids=<NNN>[,<NNN>...]`, `--drop-outline-glyphs=<glyphname>[,<glyphname>...]` or `--drop-outline-unicodes=<XXXX>[,<XXXX>...]` to let the user specify which glyphs’ outline should be dropped? The defaults could be ``--drop-outline-gids=0` and, if that makes sense, `--drop-outline-unicodes=200C,200D,200E,200F`.

**Comment by anthrotype** [comment]
Yeah, I like that
