### ISSUE TITLE
feaLib should not error if enum pos conflict with preceding single pair pos

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1147]
the Adobe feature file spec says about enum pos:

> 6.b.ii. Enumerating pairs
> [...] Since this representation is convenient for generating a large number of specific pairs, it may be used even when some of the pairs generated by the 'enum' rules are incorrect. Specific pairs generated by an 'enum' rule may be overridden by specifying preceding single pairs. Because of this case, it is not an error when specific kern pairs conflict because they have the same glyphs. When specific kern pair rules conflict, the first rule specified is used, and later conflicting rule are skipped.

Consider this snippet of feature code:
```
@Y_LC = [y yacute ydieresis];
@SMALL_PUNC = [comma semicolon period];

feature kern {
  pos yacute semicolon -70;  # specific pair
  enum pos @Y_LC semicolon -80;  # specific pairs
  pos @Y_LC @SMALL_PUNC -100;  # class pair
} kern;
```

Compiling with feaLib produces this error: `Already defined position for pair yacute semicolon ...`

Whereas, compiling with makeotf only produces a warning and the more specific pair pos takes precedence over the following conflicting enum pos rules.

```
makeotfexe [WARNING] <...> Pair positioning has conflicting statements in 'kern' feature;
choosing the first value: yacute semicolon
```

In ufo2ft we even have a method to prevent such feaLib error:
See https://github.com/googlei18n/ufo2ft/issues/205

I think feaLib should do the same as makeotf. Resolve the conflict automatically in favour of the more specific pair pos rules between specific glyphs that has occurred before a conflicting enum pos rule, and just emit a warning (or even an info message, because this notation is just a convenience for the user).

**Comment by anthrotype** [comment]
I also noticed that makeotf prints the same warning message if two single-glyph pair pos rules conflict with each other as in

```
pos yacute semicolon -70;
pos yacute semicolon -80;
```

the first always wins. I think we shall do the same.

**Comment by anthrotype** [comment]
On the other hand, if we were to relax this "Already defined" from an error to a warning for pair pos rules, why should we not also do it for the other rules (e.g. single pos, single sub, multiple sub, alternate sub)? :thinking:

**Comment by brawer** [comment]
Warnings tend to get ignored. Shouldn’t designers rather write correct sources? No strong opinions though, I’m not a font designer.

**Comment by anthrotype** [comment]
I tend to agree on that. But the spec clearly states that enum pos can be used like that, and gives a way to systematically resolve such conflicts (take the preceding pos rule)

**Comment by brawer** [comment]
Ah, in that case...

**Comment by anthrotype** [comment]
I want to demote this from WARNING to a DEBUG logging message so that it doesn't clutter the console output of tools like fontmake.
This kind of message appears quite too often, creates noise and a sense of false alarm. It is triggered whenever specific pairs generated by an 'enum' rule are overridden by preceding single pairs (which according to the Feature File spec is a valid case).
Since I removed the code in glyphsLib and ufo2ft that would prune these conflicting kerning pairs upfront (ie. before passing the feature file to feaLib) as it was redundant given that feaLib no longer raises an error (but takes the first one), now we are seeing many such warnings and I think we should just mute them as debug messages.

**Comment by khaledhosny** [comment]
I believe this can be closed now.
