### ISSUE TITLE
pyftmerge error messages when merging variable font

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#1149]
I'm not sure if `pyftmerge` does what I assume (merge two fonts so character support, glyphs and layout features are combined into one font), partly because `pyftmerge --help` gives an error and I didn't see any hints in the soure code.

I'm trying to merge two (variable) fonts to create a COLR/CPAL color font. One font has the fill, the other the outlines. They are the same, except for the glyph shapes and the variable data (stat, name, fvar, etc.) My process is:

0. Dump both fonts to `.ttx`
1. Rename glyph names in the outline by appending `.outline`
2. Remove all entries from the `cmap` table (as they will be referenced from the `colr` table)
3. Convert back to `.ttf` and merge them with `pyftmerge`

What I hope this does: combine boths into one file, fixing clashes in variable tables (e.g. the nameIDs of axes, DesignAxisRecords, etc.) so axes and glyphVariations are mapped to the correct glyphs. I'd then insert my own COLR/CPAL tables to hook up the `.outline` glyphs to the normal glyphs and have them work as color glyphs.

But I run into an error, regardless if I try to merge the two original variable fonts, or the original fill with my hacked-up outline one:

```
➤ pyftmerge font-fill.ttf font-outline.ttf
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'pyftmerge')()
  File "/Users/roel/code/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/roel/code/fonttools/Lib/fontTools/merge.py", line 1071, in main
    font = merger.merge(args)
  File "/Users/roel/code/fonttools/Lib/fontTools/merge.py", line 912, in merge
    table = clazz(tag).merge(self, tables)
  File "/Users/roel/code/fonttools/Lib/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/Users/roel/code/fonttools/Lib/fontTools/merge.py", line 957, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/Users/roel/code/fonttools/Lib/fontTools/merge.py", line 121, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in lst)
  File "/Users/roel/code/fonttools/Lib/fontTools/merge.py", line 105, in mergeObjects
    logic = clazz.mergeMap
AttributeError: type object 'VarStore' has no attribute 'mergeMap'
```

Swapping filenames (as I saw suggested in another issue) doesn't make a difference.

I know I'm making a ton of assumptions, so maybe I'm misusing `pyftmerge` or going about this way too hacky. Any advice is appreciated!

**Comment by anthrotype** [comment]
> I'm trying to merge two (variable) fonts

**Comment by anthrotype** [comment]
> pyftmerge --help gives an error and I didn't see any hints in the soure code

yep, sorry -- a known issue: https://github.com/fonttools/fonttools/issues/524

> I'm trying to merge two (variable) fonts

pyftmerge has not been updated to support variable fonts yet.

**Comment by behdad** [comment]
Right.  There's some nontrivial code to be written to merge VariationStores.

**Comment by behdad** [comment]
What you can do is to merge the master TTFs then build variable font.

**Comment by RoelN** [comment]
Ah, thanks for clearing that up, and for the suggestion. I'll give that a shot!

**Comment by miguelsousa** [comment]
Same as #1059

**Comment by anthrotype** [comment]
true. let's track this in one place
