### ISSUE TITLE
[subset] Ignore empty glyphs

### ISSUE THREAD

**Issue by aaronbell** [fonttools/fonttools#1158]
I am working with a set of fonts that have blank glyphs that I would like to remove (inconsistent between the different fonts). Unfortunately, they're interspersed among other glyphs, so it isn't super simple to define a character range that ignores them. 

Is there a mechanism in subset that would allow for ignoring blank glyphs (as in, do not contain paths or components)?

**Comment by behdad** [comment]
You can easily inspect the fonts using fonttools to find empty glyphs, and then call subsetter via Python to remove them. I don't think we want to add anything to subsetter itself for this. Makes sense?

**Comment by aaronbell** [comment]
Basically you're saying that one should review all the glyphs in a font, identify the ones that are not empty, then subset them down. Seems a bit backward to me and more complicated for users than a mechanism to ignore empty glyphs.

**Comment by behdad** [comment]
Ignoring empty glyphs is a very niche and arbitrary request. If we were to add options for anything someone asks, pyftsubset will grow into an unusably complex tool.  The help message is already so long that no one reads it...

Also, are those empty glyphs referenced from any Unicode?  If yes, that's a broken font . If no, then just subset with `--unicodes='*'` and that will drop unreachable glyphs.
