### ISSUE TITLE
pyftsubset: Dotted I doesn't get subset

### ISSUE THREAD

**Issue by O7JaniB** [fonttools/fonttools#1162]
I don't know if this was reported or I am doing something wrong but.
I'm using pyftsubset to subset some characters from an otf font (I don't believe it matters which font) but one character (dotted I) is not getting subset:
https://www.fileformat.info/info/unicode/char/0130/index.htm
the only way the character would be subset is if I do --unicodes='*', but that is not what I want... I if do --unicodes=U+0130 it just doesn't get through (
everything else works)

What is interesting is that I've tried to run the command with --verbose
pyftsubset font.otf --output-file=newfont.otf --unicodes=U+0130 --verbose
```
Text: ''
Unicodes: [304]
Glyphs: []
Gids: []
maxp pruned
cmap pruned
post pruned
CFF  pruned
GPOS pruned
GSUB pruned
kern dropped
name pruned
Added .notdef to subset
Closing glyph list over 'GSUB': 2 glyphs before
Glyph names: ['.notdef', 'Idotaccent']
Glyph IDs:   [0, 259]
Closed glyph list over 'GSUB': 2 glyphs after
Glyph names: ['.notdef', 'Idotaccent']
Glyph IDs:   [0, 259]
Retaining 2 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
cmap subsetted
post subsetted
CFF  subsetted
GPOS subsetted
GSUB subsetted
hmtx subsetted
name subsetting not needed
OS/2 Unicode ranges pruned: [2]
CFF  pruned
GPOS pruned
GSUB pruned
Input font: 109192 bytes: font.otf
Subset font:   1096 bytes: newfont.otf
```
And it looks ok, but if I type the character in with the font it doesn't get shown, like there is no glyph for it while if I try it on the original (input) font it works ok. Am I missing something?

**Comment by anthrotype** [comment]
What you did should work.
Could you send me the font and the exact command line that you used to subset in a private message at cosimo [at] anthrotype [dot] com

**Comment by anthrotype** [comment]
@O7JaniB thanks for sending me the files. Yes, it looks like the CFF outline for the "Idotaccent" glyph is not being subsetted properly.

If I add "U+02D9" (glyph "dotaccent") to your unicodes list, then it seems to work: i.e. I can type the character 0x0130 and it shows the "Idotaccent" glyph instead of empty glyph.

This looks like a bug to me. The subsetter should take care of this automatically, you shouldn't need to manually add to the set the "components" of the all glyphs you want to keep. I'll investigate and report back here.

**Comment by behdad** [comment]
Ok. Figured out what's going on. endchar operator in CFF can act like the deprecated seac operator. This aspect is not implemented in the subsetter. It's not super had to do, but not trivial either. I'll do it at some point soonish hopefully.

**Comment by miguelsousa** [comment]
> This aspect is not implemented in the subsetter.

@behdad should there be an issue to track this?

**Comment by behdad** [comment]
I already fixed it.
