### ISSUE TITLE
unclosed file

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#1164]
got this unclosed file warning with this:

```python
f = TTFont("path/to/Font.otf")
f.close()
```

```traceback
fonttools/Lib/fontTools/ttLib/ttFont.py:129: ResourceWarning: unclosed file <_io.BufferedReader name=...
```

**Comment by anthrotype** [comment]
that should have been fixed with #1160
I'm not getting the warning, even when i run python with `-Wall` option. I tried with python 3.6.4
