### ISSUE TITLE
[ttx] Implement JSON format for export / import

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#117]
Useful.

**Comment by anthrotype** [comment]
I like the idea of an alternative dump format, but without replacing xml as such, at least initially. There are very fast/optimized json decoder/encoder written in c o rust, e.g. the one Adrien uses in tfont or many others, so I don’t think we need to bother manually coding our own.

**Comment by anthrotype** [comment]
If speed is a concern, this is the fastest, apparently:
https://github.com/ijl/orjson

But, like with lxml, it would be good to use stdlib etree by default and have the third party module as optional extra requirement.

I think if we do this, it should be one of those new features that are only python3, so it’s for fonttools 4.x series

**Comment by justvanrossum** [comment]
I'm (as usual) far less interested in absolute speed than in scalability.

It for sure shouldn't replace our current XML format — at least not in the next 5 to 10 years :)

And indeed, it would be a FontTools 4 feature, Py3-only. If only because of the dict-keys-keeping-their-insertion-order feature, which is _so_ useful in contexts like this.

If we can decide on a framework of how to do it (and we decide we want it at all) I think this is a great project for new contributors.

**Comment by khaledhosny** [comment]
I think https://github.com/caryll/otfcc is the C tool @justvanrossum was thinking about, I haven’t used it myself though.

**Comment by anthrotype** [comment]
FWIW, I read @be5invis is planning to deprecate otfcc in favour of some other TypeScript library of his https://github.com/caryll/otfcc/issues/59#issuecomment-450603013

of course, supporting JSON in ttx would be a good regardless of otfcc

Hey.. how about a `.ttj` file extension, coupled with a new `fonttools ttj` cli entry point?

**Comment by justvanrossum** [comment]
`.ttj` sounds good, but json output could potentially be a new option for the `ttx` tool.

**Comment by be5invis** [comment]
Please note that OTFCC’s JSON format lies a slightly higher than TTX: it provides a more semantic representation of font data so a programmer can manipulate it more directly. One example of that (and my new lib) is variations: it directly stores GVAR data into the point coordinates rather than store it separately.


________________________________
发件人: Just van Rossum <notifications@github.com>
发送时间: 星期二, 一月 15, 2019 19:58
收件人: fonttools/fonttools
抄送: Belleve Invis; Mention
主题: Re: [fonttools/fonttools] [ttx] Implement JSON format for export / import (#117)


.ttj sounds good, but json output could potentially be a new option for the ttx tool.

―

**Comment by justvanrossum** [comment]
> Please note that OTFCC’s JSON format lies a slightly higher than TTX [...]

I don't think I'd want to go that route for ttx-json, although we should probably drop the semantically irrelevant details from the binary format that TTX currently still dumps here and there.

**Comment by behdad** [comment]
I think we should only do a json writer/reader by just replacing the Reader/Writer classes.  Ie. do an automatic XML serialization in json.

Also, for suffix, I'm for `ttxj`.

**Comment by behdad** [comment]
> > I think we should only do a json writer/reader by just replacing the Reader/Writer classes. Ie. do an automatic XML serialization in json.
> 
> While that definitely sounds like the least amount of work, wouldn't that give us a more-verbose-than-necessary json representation?

Correct.  I guess we should first define what the goal is.  Is it to be human-readable / editable? Or machine?

**Comment by justvanrossum** [comment]
> Correct. I guess we should first define what the goal is. Is it to be human-readable / editable? Or machine?

For me: both, and simplicity will benefit both. The output can (in many cases) be simpler and cleaner than our current XML output, which makes it easier to process as well. I don't really see the added value of XML-packaged-as-json.

I see this as a (possibly) better format than TTX, eventually replacing it. I haven't done a solid survey yet, but every time I look at a bit of TTX and imagine the same data as json, json wins.

**Comment by behdad** [comment]
> I see this as a (possibly) better format than TTX, eventually replacing it. I haven't done a solid survey yet, but every time I look at a bit of TTX and imagine the same data as json, json wins.

There's no doubt in that.  But also the TTX format can be improved... But a diverging format means more work for fonttools developers, which is not something I'm very excited about...

**Comment by justvanrossum** [comment]
> But a diverging format means more work for fonttools developers, which is not something I'm very excited about...

Yeah, that is a very important consideration indeed. The cost vs. benefits need to be assessed way more carefully.

**Comment by behdad** [comment]
The benefit of a mechanically generated json is for use in servers, to send down to web clients...

**Comment by justvanrossum** [comment]
Cases where json won't win: where we have a language within the language. For example T2 charstrings and TT instructions. json doesn't do multiline strings, so those things will look worse than what we have now.

**Comment by anthrotype** [comment]
how bad would be using array of lines?

**Comment by justvanrossum** [comment]
Not bad, but worse than what we have now :)

**Comment by anthrotype** [comment]
I know, it's off topic, and risk opening a pandora box.. but [toml](https://github.com/toml-lang/toml) is becoming quite popular nowadays as well. just sayin'.

**Comment by justvanrossum** [comment]
Hm, not impressed:
```
>>> glyphs = dict(a=dict(width=600, points=[dict(x=12, y=24), dict(x=56, y=67)]))
>>> print(toml.dumps(glyphs))
[a]
width = 600
[[a.points]]
x = 12
y = 24

[[a.points]]
x = 56
y = 67
```

**Comment by anthrotype** [comment]
(that `points` list of dicts could probably be just a list of tuples, but nevermind)

**Comment by anthrotype** [comment]
that looks nice

**Comment by justvanrossum** [comment]
Should we open a separate issue to freely discuss alternative dump formats?

**Comment by anthrotype** [comment]
yeah, that's better.

**Comment by justvanrossum** [comment]
For any non-json dump format discussion, please use #1457

**Comment by yisibl** [comment]
JSON5 can support comments.
