### ISSUE TITLE
[cffLib] Question about Encoding data specified by TopDict.Encoding

### ISSUE THREAD

**Issue by derwind** [fonttools/fonttools#1177]
I am confused in parsing Encoding data in CFF.

* The problem: I converted a font by update_encoding.py and confirmed the result by inspect_encoding.py, then unexpected result was shown, where these scripts are as follows:

[update_encoding.py]
```python
font = TTFont(sys.argv[1])
topDict = font["CFF "].cff.topDictIndex[0]

encoding = [".notdef"] * 256
encoding[0x20] = "space"
encoding[0x41] = "A"
encoding[0x42] = "B"
encoding[0x43] = "C"

topDict.Encoding = encoding
font.save("out.otf")
```

[inspect_encoding.py]
```python
font = TTFont(sys.argv[1])
topDict = font["CFF "].cff.topDictIndex[0]
print(topDict.Encoding)
```

* Result:
I used Source Sans Pro as a test font and got the result:
```python
['.notdef', '.notdef', 'space', 'A', 'B', 'C', 'D', 'E', 'F', 'G', ...]
```
I expect that 'space' appears at 32nd position in the list because its unicode is 0x20, and it is also strange that 'D', 'E', ... appear because I don't set them to the encoding data.

* My environment:
  * macOS High Sierra 10.13.3
  * Python 2.7.14
  * fontTools.\_\_version\_\_: '3.22.1.dev0'

* Further detail:
I investigated source codes and found some strange behavior.
I inserted `print(file.tell())` just before calling parseEncoding1 in EncodingConverter.read in cffLib/\_\_init\_\_.py and also inserted same code at the top of parseEncoding1.

My log said:
```
27996
27995
```
This result seems to me that the file pointer rewinded for some reason when entering parseEncoding1.
I don't know whether this problem depends on my environment.

**Comment by behdad** [comment]
What are you trying to do?

**Comment by derwind** [comment]
In short I tried to check the implementation of my OTF parser by using fontTools.

To understand the structure of OpenType fonts deeply, I have developed my OTF parser.
I usually check whether my implementations are correct by ttx and fontTools.
The other day I checked the implementaion of my parser's functionality of parsing Encoding data in CFF.

First, I compared the log of my parser and that of ttx. It was as expected.
Next, I compared the log of my parser and that of fontTools, i.e. show_encoding.py mentioned in my previous comment, but it seemed strange.

I investigated the strange behavior and found that the Encoding data changed by the snippet below:

```
font = TTFont(sys.argv[1])
if hasattr(font["CFF "].cff.topDictIndex[0], "Encoding"):
    font["CFF "].cff.topDictIndex[0].Encoding
font.save("out.otf")
```

This snippet simply reads Encoding data of the given font if it exists and save the font as another font.
Before running this snippet, Encoding data dumped by ttx is as follows:
```
      <Encoding>
        <map code="0x20" name="space"/>
        <map code="0x41" name="A"/>
        <map code="0x42" name="B"/>
        <map code="0x43" name="C"/>
      </Encoding>
```

but after running the snippet, ttx's log says:

```
      <Encoding>
        <map code="0x2" name="space"/>
        <map code="0x3" name="A"/>
        <map code="0x4" name="B"/>
        <map code="0x5" name="C"/>
        <map code="0x6" name="D"/>
        <map code="0x7" name="E"/>
        ...
```

So I suspect that there may be some problem in parseEncoding1 in EncodingConverter.read in cffLib/\_\_init\_\_.py.

**Comment by behdad** [comment]
Maybe @readroberts understands what's going on.

**Comment by behdad** [comment]
You should come help us instead of writing your own parsers and throwing them away ;).

**Comment by readroberts** [comment]
This is a bug in cffLib.py. What happens is that when the code in 'EncodingConverter()' goes to parse the encoding, it calls:
encoding = parseEncoding0(parent.charset, file, haveSupplement,
						parent.strings)
In this workflow, the charset has not yet been read. Referencing it causes it to be read before parseEncoding0 is called. By the time you get to the first line parseEncoding0, the file pointer is set to the end of the charset data. This happens to precede the encoding, so file.tell() shows that you are at the start of the encoding data. However, the code expects that the first byte of the formatting has been read, and the file pointer should be pointing at the start+1. A simple fix is to reference 'parent.charset' and 'parent.strings' before 'file.seek(value)' in EncodingConverter.

**Comment by derwind** [comment]
@readroberts @behdad Thank you for helpful comments!
I didn't notice implicit function call related to 'charset' and 'strings'.

Actually, accessing to 'charset' and 'strings' before 'Encoding' fixes the problem.
I checked this as follow:
```
for attr in ["charset", "strings"]:
    if hasattr(topDict, attr):
        getattr(topDict, attr)
if hasattr(topDict, "Encoding"):
    encoding = topDict.Encoding
    ...
```

But generally it seems difficult for a programmer to do this, because he or she needs to deeply know the implementation  of fontTools.
Although it may not be the best solution, I would like to suggest ad-hoc fix to lazy loads as below:
```
--- a/Lib/fontTools/cffLib/__init__.py
+++ b/Lib/fontTools/cffLib/__init__.py
@@ -1479,12 +1479,13 @@ class EncodingConverter(SimpleConverter):
                        if haveSupplement:
                                raise NotImplementedError("Encoding supplements are not yet supported")
                        fmt = fmt & 0x7f
+                       pos = file.tell()
                        if fmt == 0:
                                encoding = parseEncoding0(parent.charset, file, haveSupplement,
-                                               parent.strings)
+                                               parent.strings, pos)
                        elif fmt == 1:
                                encoding = parseEncoding1(parent.charset, file, haveSupplement,
-                                               parent.strings)
+                                               parent.strings, pos)
                        return encoding
 
        def write(self, parent, value):
@@ -1523,7 +1524,8 @@ class EncodingConverter(SimpleConverter):
                return encoding
 
 
-def parseEncoding0(charset, file, haveSupplement, strings):
+def parseEncoding0(charset, file, haveSupplement, strings, pos):
+       file.seek(pos)
        nCodes = readCard8(file)
        encoding = [".notdef"] * 256
        for glyphID in range(1, nCodes + 1):
@@ -1533,7 +1535,8 @@ def parseEncoding0(charset, file, haveSupplement, strings):
        return encoding
 
 
-def parseEncoding1(charset, file, haveSupplement, strings):
+def parseEncoding1(charset, file, haveSupplement, strings, pos):
+       file.seek(pos)
        nRanges = readCard8(file)
        encoding = [".notdef"] * 256
        glyphID = 1
```

BTW I usually use fontTools to parse fonts and solve many problems. Also I sometimes check the implementation.
Developing my own parser from scratch is purely to understand the spec and the structure, and to keep my coding skill :)

**Comment by anthrotype** [comment]
> make such behind-the-scene lazy loads always seek the file back where it was

I also prefer this solution. Basically in the `read` methods of all the `*Converter` classes that do any file `seek` or `read`, we need to `tell` the current position and seek to it after we have read that chunk of data.

**Comment by derwind** [comment]
In this case, should I create a pull-request? or should I wait for someone to be assigned?

**Comment by behdad** [comment]
Pull Request is highly appreciated. Thanks!

**Comment by anthrotype** [comment]
Fixed with #1187

**Comment by behdad** [comment]
@derwind seriously. Would you be willing to help implement CFF in HarfBuzz?

**Comment by derwind** [comment]
@behdad I would like to contribute something (e.g. some pull-requests) to harfbuzz as best I can because I've also used `hb-view` and `hb-shape` to validate GSUB.
But I don't quite get what "implement CFF in harfbuzz" means so far...

**Comment by behdad** [comment]
> But I don't quite get what "implement CFF in harfbuzz" means so far...

@derwind We want to implement reading CFF tables, for various reasons.

**Comment by derwind** [comment]
@behdad Apart from this, actually I have plan to implement reading CFF in my own tool (excluding CFF2 so far).
So I don't know how much I can help, but I hope that I can contribute some.
