### ISSUE TITLE
[ttLib] add generic opener function returning either TTFont or TTCollection

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1183]
as discussed in #1181 

it should take a file as first positional argument and all the rest of the kwargs will be forwarded to the TTFont and TTCollection constructors.

It should read the first four bytes using the `guessFileType` function (see https://github.com/fonttools/fonttools/issues/1155), then dispatch the file to either TTFont or TTCollection classes, and return the new object.

I'm not sure how to call this though. `openTTFontOrCollection`?

(Note this is a different thing from https://github.com/fonttools/fonttools/issues/814, which would return a "glyph set", i.e. a mapping of glyph names to glyph objects with a draw method)

**Comment by jenskutilek** [comment]
Could a unified class used for both single fonts and collections perhaps?

A font could be treated as a collection with just 1 member, and when saving, the ttc wrapper would be optimized away. It might break too many existing scripts though ...

**Comment by anthrotype** [comment]
> Could a unified class used for both single fonts and collections perhaps?

hm.. I don't like that. They are different beasts. A TTCollection containing only one TTFont (although useless) is not the same thing as a single TTFont, in the same way as a list of one item is different from the item itself. One is the container, the other the contained.
I prefer to keep the distinction.

**Comment by behdad** [comment]
Closing as not planned?
