### ISSUE TITLE
Subsetting layout features does not update OS/2 → usMaxContext

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#1191]
1. `pyftsubset SourceSansPro-Black.ttf  --glyphs="*" --layout-features=""`
2. `ttx -o - -t OS/2 SourceSansPro-Black.subset.ttf | grep usMaxContext`

Here, usMaxContext is 3 when it should  be zero (no layout features).

Is this even relevant?

**Comment by behdad** [comment]
It's fine to move. But yeah, that fiends should not be used by anything.

**Comment by behdad** [comment]
Please make sure subsetter defaults to NOT recomputing this.

**Comment by miguelsousa** [comment]
That's the default.
