### ISSUE TITLE
ttx fails roundtripping NotoSans-VF.ttf

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1195]
Get binary from:
https://drive.google.com/drive/folders/1uZSioduV6-7-n16eIRNT3xgggnIftxjx

ttx'ing back to binary fails.  Need to debug :(.

**Comment by anthrotype** [comment]
I’ll have a look today

**Comment by anthrotype** [comment]
I downloaded the font from the url above, run ttx back and forth with it and it completed successfully without errors.
I'm using fonttools master at current commit (efca91e7) and python 3.6.4 on macOS.
I'll try with 2.7.x. Can you paste the error you see?

**Comment by behdad** [comment]
Thanks I'll try again and report.

**Comment by behdad** [comment]
Yeah works for me as well. Should have been my faulty table repacker perhaps.
