### ISSUE TITLE
[sfnt] Reading TTC fails on Python 3

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1207]
https://github.com/fonttools/fonttools/blob/1d1acbb651885970ce045d8b6a83b13b0746b132/Lib/fontTools/ttLib/sfnt.py#L577

`self.TTCTag` is a string, not bytes, so comparing it with b"ttcf" yields False.

It's probably also a problem when writing, in `writeTTCHeader()`.

If the fix is to remove the b prefix I'll gladly do that.

**Comment by justvanrossum** [comment]
I mean, I've tested that removing the b prefix indeed fixes it, I'm just not sure whether that's going to be the preferred fix :)

**Comment by anthrotype** [comment]
for things like that, we need to use our `Tag` class defined in `py23` that does the encoding/decoding automatically. We also use this in `sfnt` module for the sfntVersion or the table tags:
https://github.com/fonttools/fonttools/blob/1d1acbb651885970ce045d8b6a83b13b0746b132/Lib/fontTools/misc/py23.py#L135-L171

I'll fix that. 

PS: ttCollection needs tests.

**Comment by anthrotype** [comment]
actually, Just is correct. When we use the `sstruct` module to unpack, this will return native `str` values; and when we `sstruct.pack`, it will auto-encode a `str` to ascii using `tobytes`.
We don't need to use that `Tag` class for `TTCTag`. I thought about it for consistency with the current treatment of `sfntVersion`.

BTW, why does `sstruct.unpack` passes over a `UnicodeDecodeError` exception:

https://github.com/fonttools/fonttools/blob/1d1acbb651885970ce045d8b6a83b13b0746b132/Lib/fontTools/misc/sstruct.py#L94-L98

that means the `value` will stay `bytes`, and will not be converted to `str` if it's not valid ascii. So, `struct.unpack` may still return `bytes` in some circumstances (e.g. broken fonts cf. #1209).
