### ISSUE TITLE
add unit tests for ttCollection module

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1210]
#1207

**Comment by chrissimpkins** [comment]
Suggestions for *.ttc currently in repository test data directories to use for these tests?  There is this in the ttx test data directory: https://github.com/fonttools/fonttools/blob/master/Tests/ttx/data/TestTTC.ttc

**Comment by behdad** [comment]
Volunteers?

**Comment by behdad** [comment]
There's a couple tests there now at least.
