### ISSUE TITLE
[varLib] An issue in varLib.builder.buildVarData()  causes building CFF2 VF fonts to fail

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#1212]
varLib.builder.buildVarData() now has an argument 'optimize' with a default value of True. This triggers calling varLib.builder.VarData_CalculateNumShorts(). This function removes all region references that aren't referenced by a data item. Since the CFF2 VarDataStore structure has no items, all the regions get optimized away, leaving a RegionCount of 0. Work-around is to set optimize=False for CFF2 fonts when calling this function directly. I suggest that the optimization be suppressed when there are no data items, effectively asking the function to use the region index tuple that is passed in. If not, then a little in-line documentation would help alert a developer to set optimization to False.

The cffLib.py library has some logic that keeps this from being a problem with CFF fonts that have only 2 masters, so I didn't notice this until recently.

**Comment by behdad** [comment]
> The cffLib.py library has some logic that keeps this from being a problem with CFF fonts that have only 2 masters, so I didn't notice this until recently.

The optimization is recent.

I did think about your usecase. But I mistakenly thought CFF2 relies on the VarRegionList order, NOT the region order of the first VarData.

The fix indeed is to disable optimization on your side. I like the optimizer to default to optimizing everything out, which is relevant to all use-cases other than CFF2.

**Comment by readroberts** [comment]
Is there a case for a VarData to exist with no regions referenced at all? When this happens, I would think a better solution would be to omit the VarData entirely. Of course, this is still a reason to optimize everything out, so as to find the case. I am fine with disabling the optimization from the outside.

**Comment by behdad** [comment]
> Is there a case for a VarData to exist with no regions referenced at all? When this happens, I would think a better solution would be to omit the VarData entirely.

Sure. That happens during subsetting. The optimizer optimizes, and the outer layer removes VarData entirely.  A VarData with no regions can still have data lines (1 only, for "no variations"), which might happen if, eg, someone is subsetting the variation space itself...

Easier if you disable it from outside. Thanks.
