### ISSUE TITLE
[varLib] varLib._add_HVAR() fails when there are no width deltas between the masters.

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#1213]
When there are no width differences between the masters, all the HVAR glyph deltas are 0. In OTTables.py.VarIdxMap.preWrite(), which is called under 'advanceMapping.compile()' in  _add_HVAR, mapping is reduced to one item, but the logic assumes at least two items exist. This is bug- I can imagine that a test VF font could have only one delta tuple, and be valid.  However, I think it also necessary in varLib._add_HVAR() to check if there any differences, and return without creating an HVAR table if there aren't. A test using the 'uniq' variable is simple. I encountered this case while trying to build a VF from SourceCodePro, which is a monospaced font, and where all the masters have the same width.

**Comment by behdad** [comment]
Can we push the fix for this?

**Comment by behdad** [comment]
We must create HVAR. It's presence has semantic significance. If it's missing, layout engines have to load glyph shape to deduce advance variation. If there's no advance variation, empty HVAR should be encoded.

**Comment by anthrotype** [comment]
ok

**Comment by anthrotype** [comment]
so just to be clear, the current code is correct and there's nothing else to do?

**Comment by behdad** [comment]
Sounds about right.

**Comment by behdad** [comment]
Sounds about right.
