### ISSUE TITLE
i'm sorry it's just a normal problem while using this lib

### ISSUE THREAD

**Issue by Dashu-Xu** [fonttools/fonttools#1217]
how can i get the chinese character from a .ttf font file with fonttools through python?

**Comment by justvanrossum** [comment]
Something like this should work:

```python
from fontTools.ttLib import TTFont
from fontTools.pens.basePen import _TestPen

p = 'a/font/containing/chinese/charaters.ttf'

f = TTFont(p)
cmap = f.getBestCmap()  # look up the encoding
char = "\u4F5C"  # a char to try
glyphName = cmap[ord(char)]
glyphSet = f.getGlyphSet()
glyph = glyphSet[glyphName]
pen = _TestPen(glyphSet)
glyph.draw(pen)
```

**Comment by Dashu-Xu** [comment]
i'm sorry , the problem is that i have no idea which character containing in this .ttf file, and your code seems  like try to guess whether a character in or not.
i find some code in the internet but i don't know whether it will help with this problem.

```python
def getTTCharMap(font): 

	if isinstance(font, str):
		font = ttLib.TTFont(font)

	if not 'cmap' in font:
		raise Exception('missing cmap table')

	gl = {}
	bestCodeSubTable = None
	bestCodeSubTableFormat = 0

	for st in font['cmap'].tables:
		if st.platformID == 0:  # 0=unicode, 1=mac, 2=(reserved), 3=microsoft
			if st.format > bestCodeSubTableFormat:
				bestCodeSubTable = st
				bestCodeSubTableFormat = st.format

	if bestCodeSubTable is not None:
		for cp, glyphname in bestCodeSubTable.cmap.items():
			if cp in gl:
				raise Exception('duplicate unicode-to-glyphname mapping: U+%04X => %r and %r' % (
					cp, glyphname, gl[cp]))
			gl[cp] = glyphname

	return gl
```
the ttf file is here:
[demo.zip](https://github.com/fonttools/fonttools/files/1821815/demo.zip)

i just want get all of the characters in the file , by the way , i don't want try with every chinese character cause it will take loooooong time.
hope my poor English don't bother you, thank you very much :-)

**Comment by justvanrossum** [comment]
`cmap.keys()` will give you all the code points in the font, `glyphSet.keys()` will give you all the glyph names in the font.

In recent fonttools, much of the function you quote can be done with `f.getBestCmap()`.

**Comment by Dashu-Xu** [comment]
![pic](https://user-images.githubusercontent.com/26664692/37557985-d85bdf86-2a47-11e8-9ac2-ff1c9012fa71.png)
thaks bro, but what i want is the character in with red box not the green one, i can open the ttf file with other tools by hands,  but i want get all chinese character with python code .

**Comment by justvanrossum** [comment]
The code I posted earlier demonstrates how you can extract outlines from a font.

**Comment by Dashu-Xu** [comment]
so…can I know which chinese character it is from the outline? (I'm sorry I know nothing about ttf file )

**Comment by justvanrossum** [comment]
Uhm, fonttools is not an optical character recognition library...

**Comment by Dashu-Xu** [comment]
thanks bro，can you give me some advice about get chinese character from a . ttf file? A Lib or something else

**Comment by Dashu-Xu** [comment]
Now I have a .fft font file, it contain  some chinese character as I show you before , I want a Lib help me get them and show in Python console . For example I have a font file with English character "A" , I want use a Lib read this file and output a str like character A in Python console.

**Comment by justvanrossum** [comment]
I'm not sure I can help you. It depends on what application you specifically mean with "Python console". But it seems that fonttools is not the tool to accomplish what you need.

Depending on your shell environment, printing unicode characters may just work. It does in Terminal on macOS:

```
>>> print("\u4F5C")
作
```

**Comment by justvanrossum** [comment]
(This is Python 3 btw. which does unicode a lot better than Python 2.)

**Comment by Dashu-Xu** [comment]
if i want print a character "作" like the way you show me , i should have  the unencode character "\u4F5C",
can you tell me if i have a font file , how can i get the character in the red box 
![pic](https://user-images.githubusercontent.com/26664692/37562796-f5860780-2aab-11e8-9b23-684a245959c4.png)

**Comment by justvanrossum** [comment]
You still don't tell me what exactly you mean by "get the character in the red box". Get the character how? Where? In what environment? What platform? What application?

**Comment by justvanrossum** [comment]
What did you try, what was the result, what was the result that you expected.

**Comment by Dashu-Xu** [comment]
for example , i have a font file and i open it with a software named "High-Logic FontCreator" , then i got the  picture like this
![default](https://user-images.githubusercontent.com/26664692/37562902-5f1f9e02-2aae-11e8-9598-6688306445ac.PNG)
i want get the character "A" with python code , what should i do?
i'm using win10 , python3.5 , i try to get all character in the font file, it seems like i open a font file abc.ttf with python and get output "A","B","C",..."Z"

**Comment by Dashu-Xu** [comment]
i want it become a str and print it use python

**Comment by justvanrossum** [comment]
Perhaps you mean:

```python
from fontTools.ttLib import TTFont

p = 'path/to/font.ttf'

f = TTFont(p)
cmap = f.getBestCmap()  # look up the encoding

for char in sorted(cmap):
    print(chr(char))
```

**Comment by Dashu-Xu** [comment]
that's the solution! thank you bro
