### ISSUE TITLE
Glyph transformations (skew, rotate, scale)

### ISSUE THREAD

**Issue by klonuo** [fonttools/fonttools#1218]
Hi,

it is not clear if it is possible to do transformation to TTF glyphs with this package?

Thanks

**Comment by m4rc1e** [comment]
@klonuo there is a Transforms module, https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/misc/transform.py

For an idea on how to use it. See Roboto's approach to making Italics https://github.com/google/roboto/blob/master/scripts/lib/fontbuild/italics.py

**Comment by klonuo** [comment]
Thanks Mark
