### ISSUE TITLE
Add kernLib

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1221]
Implement a library for producing optimal kerning tables. This involves three pieces: load, optimize, save.

The main input object we'll work with is a huge matrix of glyph-glyph kern values. Ie. no classes. All classes are expanded. One of the sparse matrix representations should be good enough. The load functions load kerning data from variety of formats (UFO, binary, AFDKO, ...) into the matrix form.

The optimizer, which might have various tunable parameters, takes the input kern matrix and produces optimal classes left and right classes, the class-based kern matrix, and the residual exception kern matrix. Though, that can be divided into deducing classes, and separately breaking the matrix down.  There will be tolerance parameters. Possibly even bucketize the values to get better compression (an idea that Tim Ahrens introduced to me); eg. by rounding X number of lower bits to 0.

The save routines convert the optimization output to various formats: UFO kern groups / dict, GPOS subtables, AAT kerx subtables, AFDKO dump, etc.

Optimizer should have tunable parameters that can optimize both for OpenType and AAT kerning formats.

**Comment by behdad** [comment]
Note that this has nothing to do with autokerning. This is a purely font binary file size optimizer.  This, however, might be able to find unintended kerning errors.

A few years ago I started some experiments with Singular Value Decomposition as well as k-Clustering. Neither was satisfactory or finished.  That code is here: https://github.com/behdad/playground/blob/master/eigenkernfea/eigenkernfea.py

**Comment by justanotherfoundry** [comment]
A few first thoughts:

• For reference, [here](https://github.com/justanotherfoundry/font-production/tree/master/palettize%20kerning) is the kerning palettization code Behdad mentioned.
• Could there be a parameter that allows for slightly lossy compression (i.e. kerning class generation) apart from the palettization? In other words, a certain allowed deviation of the final pair value compared to the input.
• Conceptually, should the input matrix distinguish between explicit zero values (i.e. the type designer says, “this kerning value must be zero”) and undefined values? Of course, one would rarely find zero-value kerning when reading in an OT font but I feel it may be valuable when using “design input” directly.
• Would it make sense to try and use a source that defines which pairs could possibly occur, or, more precisely, how likely a pair is to occur? I am thinking of a pair frequency list like the one I have  [here](https://github.com/justanotherfoundry/freemix-fontlab/blob/master/Macros/System/Modules/FMX_pair_frequencies.py). Knowing (or, assuming) that certain pairs will not occur in real life will allow for more grouping, i.e. fewer classes and exceptions.
The approach could be to say, the tool limits the number of pairs to x, while minimizing the total error (missing or slightly off kerning values) in a typical document. I am regularly doing this when creating webfonts for my clients (other type designers and foundries).
One challenge is to deduce the frequency of glyph pairs that do not have Unicode values but are activated via OT features. They could adopt the frequencies of their respective “parent glyph(s)” but possibly with a factor (say, A.sc-V.sc is less likely to occur than A-V).

**Comment by justanotherfoundry** [comment]
Singular Value Decomposition and k-Clustering are far beyond my knowledge of computer science, but, from a quick look at the illustrations in Wikipedia, it seems that these methods treat the data as points in a real 2D space, in other words, the order of the rows and columns is relevant. Is this right?

In contrast, in our 2D expanded kerning matrix, one could re-order the columns or rows without any effect on the font (but drastically changing which points are close to each other). In that sense, our matrix has additional irrelevant information (the order of rows and columns), which me must ignore when determining the classes. But maybe I am completely misunderstanding what your code does.

**Comment by m4rc1e** [comment]
Slightly off topic but I'm on/off writing a kerning differ.

I use a similar approach. I expand the classes into pairs, then compare. Here's a gist on my flatten implementation. https://gist.github.com/m4rc1e/59017729923ac4930dcd76823c0acb91

**Comment by moyogo** [comment]
@m4rc1e how does that tool differ from https://github.com/adobe-type-tools/kern-dump?

**Comment by m4rc1e** [comment]
@moyogo thanks, never realised this existed. This does exactly what I need https://github.com/adobe-type-tools/kern-dump/blob/master/getKerningPairsFromOTF.py.

**Comment by behdad** [comment]
> Singular Value Decomposition and k-Clustering are far beyond my knowledge of computer science, but, from a quick look at the illustrations in Wikipedia, it seems that these methods treat the data as points in a real 2D space, in other words, the order of the rows and columns is relevant. Is this right?

No. They treat the data for each row as a point in a high-dimensional space, with each column a dimension...

**Comment by behdad** [comment]
Will happen when it happens.
