### ISSUE TITLE
[designspaceLib] normalize() does not consider axisMap

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1226]

**Comment by anthrotype** [comment]
is this still an issue? If so, can you elaborate what needs fixing? thanks

**Comment by LettError** [comment]
Example, a system with 2 axes, `pop` and `snap` with masters at `0` and `100`. The snap axis has a map that scales `0` -> `33` and `100` to `66`.

![image](https://user-images.githubusercontent.com/1243961/45485420-dea20d00-b757-11e8-83fd-fdbc7b3f93d4.png)

The user sees the `snap` axis go between 33 and 66. The `pop` axis is unaffected and goes between `0` and `100`.

Normalising this system would only change the coordinates of the masters in the designspace. Not the mapped value in the UI. So how should normalise() use the axisMap?

**Comment by behdad** [comment]
Umm. I might be wrong but I thought axisMap works the other way around. Ie. it maps from user-visible system to internal linear-interpolation system.  Ie. in your example, user sees 0,100.

**Comment by behdad** [comment]
I need to look at the code and be back here.  I know there was a problem.  Details not fully in my head.

**Comment by LettError** [comment]
Reading the code, I see I remembered wrong. I'll take another look.

**Comment by LettError** [comment]
There is a test with normalisation and a map. Does this not do the right thing?
https://github.com/fonttools/fonttools/blob/4bf522abe3b2c65f54699b748336f31a9ce8a3ea/Tests/designspaceLib/designspace_test.py#L607

**Comment by anthrotype** [comment]
@LettError that test case looks good to me
