### ISSUE TITLE
mutator: drop varfont-specific name records from generated instance

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1227]
Currently varLib.mutator doesn't remove from the generated instance's name table all the fvar axis names and the named instance names.

When making the variable font, varLib finds unused nameIDs > 255 and adds the fvar names incrementally.

Is it ok/safe to simply drop all nameIDs >= 256 when making an instance with mutator?
Or should we collect the nameIDs actually used by the fvar (and STAT) and drop only those?
Probably the latter.

**Comment by justvanrossum** [comment]
Stylistic sets can have descriprive names, too, in that range.
