### ISSUE TITLE
Unhandled exception on Gudea fonts

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#1229]
In the current google/fonts.git repo there are 3 files which [edit: @evanadams reports that] ttx fails to process:

```
ERROR: Unhandled exception has occurred
    ofl/gudea/Gudea-Bold.ttf
    ofl/gudea/Gudea-Italic.ttf
    ofl/gudea/Gudea-Regular.ttf
```

Direct links to download those files:

* https://github.com/google/fonts/blob/883939708704a19a295e0652036369d22469e8dc/ofl/gudea/Gudea-Regular.ttf?raw=true
* https://github.com/google/fonts/blob/883939708704a19a295e0652036369d22469e8dc/ofl/gudea/Gudea-Bold.ttf?raw=true
* https://github.com/google/fonts/blob/883939708704a19a295e0652036369d22469e8dc/ofl/gudea/Gudea-Italic.ttf?raw=true

**Comment by anthrotype** [comment]
@davelab6 could you please copypaste the full traceback of the exception? thanks

**Comment by m4rc1e** [comment]
I was not able to replicate this using fontTools 3.4.0.

**Comment by m4rc1e** [comment]
With fontTools 3.24.2 (pip installable version) using Python2. I get the following traceback.

```
Dumping "/Users/marc/Downloads/Gudea-Regular.ttf" to "/Users/marc/Downloads/Gudea-Regular#1.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'prep' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttx.py", line 399, in main
    process(jobs, options)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttx.py", line 373, in process
    action(input, output, options)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttx.py", line 270, in ttDump
    newlinestr=options.newlinestr)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 221, in saveXML
    self._saveXML(writer, **kwargs)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 276, in _saveXML
    self._tableToXML(tableWriter, tag, splitGlyphs=splitGlyphs)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 307, in _tableToXML
    table.toXML(writer, self)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 93, in toXML
    self.table.toXML2(writer, font)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 741, in toXML2
    conv.xmlWrite(xmlWriter, font, value, conv.name, [])
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 407, in xmlWrite
    value.toXML(xmlWriter, font, attrs, name=name)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 794, in toXML
    BaseTable.toXML(self, xmlWriter, font, attrs, name)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 722, in toXML
    self.toXML2(xmlWriter, font)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/ttLib/tables/otTables.py", line 895, in toXML2
    xmlWriter.simpletag("ClassDef", [("glyph", glyphName), ("class", cls)])
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/misc/xmlWriter.py", line 104, in simpletag
    attrdata = self.stringifyattrs(*args, **kwargs)
  File "/Users/marc/Desktop/enver/lib/python2.7/site-packages/fontTools/misc/xmlWriter.py", line 156, in stringifyattrs
    data = data + ' %s="%s"' % (attr, escapeattr(value))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

```
Looks like the std encode/decode issue.

**Comment by m4rc1e** [comment]
3.24.2 works just fine with Python 3.

@davelab6 could you find out which version of fontTools he is using and what version of Python?

**Comment by davelab6** [comment]
This is actually encountered by @evanadams - Evan, what version did you try?

3.16 also worked well for me:

```
$ ttx --version
3.16.0
$ cd fonts/ofl/gudea/
$ ttx *ttf
Dumping "Gudea-Bold.ttf" to "Gudea-Bold.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'prep' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'DSIG' table...
Dumping "Gudea-Italic.ttf" to "Gudea-Italic.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'prep' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'DSIG' table...
Dumping "Gudea-Regular.ttf" to "Gudea-Regular.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'prep' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'DSIG' table...
$
```

**Comment by anthrotype** [comment]
hmm, looks like the font has some invalid glyph name in post table, containing non-ascii characters..
still, the xmlWriter should not choke on that.

**Comment by anthrotype** [comment]
if you dump just the post table with `ttx -t post ...` you can see there's a glyph name which is being decoded with some garbage bytes:

```
<psName name="CÂrculo0"/>
```

**Comment by anthrotype** [comment]
when fonttools unpacks a postscript string from a binary `post` table, it uses `latin-1` as default encoding:
https://github.com/fonttools/fonttools/blob/a523a697164a4cdc721a06dec80791d4b1496f12/Lib/fontTools/ttLib/tables/_p_o_s_t.py#L266

the xmlWriter should be fixed to handle that gracefully

**Comment by anthrotype** [comment]
oh I see. it's because the name of the attribute is a unicode string (`u"glyph"`), whereas the attribute value is a bytes string (`b"CÂ�rculo0"`), and when doing `%` string interpolation in python2 with mixed types of arguments, they are all coerced to unicode using the default encoding ("ascii").
I'll fix that

**Comment by anthrotype** [comment]
(as usual, the `unicode_literals` future import causes more troubles than it solves)

**Comment by anthrotype** [comment]
it would be interesting to know how these fonts were generated, and how that glyph ended up with that a postscript glyph name containing non-ascii characters.
The encoding of glyph names in the post table is undefined (the OT spec simply says they are "Pascal strings", i.e array of characters with the first byte being the length of the array).

In python 3, we use 'latin-1' encoding (ISO-8859-1) because that's the first 256 Unicode codepoints so we can store that byte array in a str, and encode it back without changes.

When decompiling the post table in python 2, however we don't do any decoding (`tostr` simply returns the bytes string unchanged, as it's already a native python2 `str`).

Maybe that's the problem, and we should instead always decompile the post table `extraNames` using the `tounicode(..., "latin-1")` so that on both py2 and py3 we get unicode strings as result -- and later on there won't be implicit coercion to ascii when calling the xmlWriter `stringifyattrs` function...

**Comment by evanadams** [comment]
You guys seem to have this well understood.

To answer the previous questions, I used ttx version 3.24.2 and python version 2.7.13.

**Comment by anthrotype** [comment]
@evanadams how did you build the fonts? Using what tool/font editor? That glyph postscript name should have been normalised to something plain ascii.

**Comment by evanadams** [comment]
@anthrotype I didn't build the fonts, instead, I downloaded them.  I went to https://github.com/google/fonts and hit the download button.

**Comment by davelab6** [comment]
They were built with flab5 many many years ago.

**Comment by khaledhosny** [comment]
Python 2-only issue.

**Comment by 0xff00ff** [comment]
Hello, dont want to create new question, but I have the same error with another font.
I found it here https://www.dafont.com/sansation.font
ttx cant dump TSIV table of this font.

I tryed to play with this error, and changed this file /usr/lib/python3/dist-packages/fontTools/misc/py23.py 
I changed function tounicode from
`def tounicode(s, encoding="ascii", errors="strict"):`
to
`def tounicode(s, encoding="latin", errors="strict"):`
and after that changes font was dumped without any error

I use ttx 4.16.1 

![image](https://user-images.githubusercontent.com/669518/116674589-84f4bc80-a9ad-11eb-91a6-c062f613dc3d.png)

**Comment by anthrotype** [comment]
this is a different issue, please file a separate bug report
