### ISSUE TITLE
[designspaceLib] "layer" attribute to sourcedescriptor (edited)

### ISSUE THREAD

**Issue by LettError** [fonttools/fonttools#1238]
Following up on the pre-robothon 2018 talk for `support` layers in designspaces. 

We discussed a couple of steps to enable supporting outlines to specific glyphs. The use case would be a variable font can have `n` masters for most glyphs, but one or more need some extra help and they can have `n+i` additional shapes. If you

* A new `support` attribute in the source element indicates the name of the UFO3 layer the glyph geometry is coming from. (does it need a naming scheme or convention?)
* **The layer does not need to have a complete glyphset, only the glyphs that are present in the layer will be processed.**
* The layer does not need to be in a specific UFO - it can be in the default UFO, but can be any ufo really.
* The `designspace` consumer should be able to handle a varying number of masters in each glyph.

To do:
1. I guess this requires a change to the specification:
 https://github.com/fonttools/fonttools/blob/master/Doc/source/designspaceLib/readme.rst#attributes
2. Add support to `varlib` (what else `cu2qu` ? ) to support a varying number of masters per glyph. 

Kerning is specifically not a part of this proposal because it is difficult to store kerning tables with glyphs that are not present in the font.

**Comment by anthrotype** [comment]
> does it need a naming scheme or convention?

no, I think the support layer name could be abritrary, anything suitable for identifying it among the other layers. What marks it as "support" is the fact that it's been used as such in the designspace.

> Add support to varlib (what else cu2qu ? ) to support a varying number of masters per glyph

yes. Plus, in ufo2ft compileTTF and compileOTF function one should also be able to specify from which layer to get the glyph set (currently it only compiles the glyphs from a font's default layer); and also it should skip generating OTL tables for these "incomplete" support master ttfs.

**Comment by anthrotype** [comment]
For those who were not there while we discussed this, the idea is that one can add additional `<source>` elements which may or may not reference the same `filename` UFO as other sources, and which have an additional `support="some ufo3 layer"` attribute which marks these as special masters containing support outlines only for specific glyphs.
The authoring tools should include these support layers to obtain the list of masters for each glyph (matched between different fonts and layers by their name).

**Comment by anthrotype** [comment]
yes, actually that makes sense. I don't see why only the extra "support" layers should be allowed to have sparse glyph sets, any source (besides the base master) could be like that.
I also think the name "layer" is clearer than "support".

**Comment by justvanrossum** [comment]
> except in the neutral or base master's default layer

Except in the layer specified to get the base master glyphs from, which is the default layer if no other layer is specified.

**Comment by behdad** [comment]
Agree. The name "support" doesn't make sense to me. Any source can come from another layer. Any source can be sparse. Initially, base source must have all glyphs.

**Comment by LettError** [comment]
* Proposal for adding a `layer` attribute to the `source` element in the document
* `layerName` attribute for SourceDescriptor
* SourceDescriptor object reads and writes the layerName.

https://github.com/fonttools/fonttools/commit/1c6c35dc388f877f66c25dd5dac9986e40288103

This is not ready for a PR.

**Comment by LettError** [comment]
Done. https://github.com/fonttools/fonttools/pull/1253

**Comment by anthrotype** [comment]
Thank you Erik.
I'm thinking we should also bump the designspace "format" version, to mark the fact that sources now have this new optional "layer" attribute and designspace consumers need to be updated to deal with that.

It would be nice if the format string would contain both a major and a minor version instead of a single digit, so we could distinguish between new backward-compatible features (like this one) and breaking changes.
However, if we do change that, this very change could be a backward incompatible one, as other tools may assume format is meant to be read as an integer, not a dot-separated version string.

In light of that, it may be ok to bump the version from 3 to 4, and do the same every time we do any change. I understand we did not follow this rule in the past, e.g. when we added a `<lib>` element. But better late than never. If we don't use that format field, then it will become meaningless pretty soon.

**Comment by LettError** [comment]
Ok.

**Comment by LettError** [comment]
Ok to close?

**Comment by anthrotype** [comment]
I'd say, let's keep it open until we address the second part of the issue:

> Add support to varlib (what else cu2qu ? ) to support a varying number of masters per glyph.

**Comment by anthrotype** [comment]
or if you prefer, go on and close this and open a new separate issue for the latter, thanks

**Comment by LettError** [comment]
Just trying to prune some of the long-open-stale-issues.
