### ISSUE TITLE
When stripping .notdef, the first available character gets mapped to .notdef

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#1239]
When dumping a font with only AZaz and no .notdef, the A gets mapped to .notdef in the ttx:

`$ pyftsubset LatoLatin-Regular.supersubset.ttf --verbose --unicodes="U+0041-007a" --no-notdef-glyph --output-file=output.ttf`

```
    <GlyphID id="0" name=".notdef"/>
    ...

    <mtx name=".notdef" width="1354" lsb="6"/>
    ...

    <TTGlyph name=".notdef" xMin="6" yMin="0" xMax="1348" yMax="1433">
      <contour>
        <pt x="944" y="532" on="1"/>
        <pt x="719" y="1115" on="1"/>
        <pt x="709" y="1141" on="0"/>
        <pt x="687" y="1210" on="0"/>
        <pt x="677" y="1249" on="1"/>
        <pt x="656" y="1168" on="0"/>
        <pt x="634" y="1114" on="1"/>
        <pt x="409" y="532" on="1"/>
      </contour>
      <contour>
        <pt x="1348" y="0" on="1"/>
        <pt x="1198" y="0" on="1"/>
        <pt x="1172" y="0" on="0"/>
        <pt x="1140" y="26" on="0"/>
        <pt x="1132" y="46" on="1"/>
        <pt x="998" y="392" on="1"/>
        <pt x="355" y="392" on="1"/>
        <pt x="221" y="46" on="1"/>
        <pt x="215" y="28" on="0"/>
        <pt x="181" y="0" on="0"/>
        <pt x="156" y="0" on="1"/>
        <pt x="6" y="0" on="1"/>
        <pt x="579" y="1433" on="1"/>
        <pt x="775" y="1433" on="1"/>
      </contour>
      <instructions/>
    </TTGlyph>

    etc.
```

I see this in the ttx dump. but this might have happened to [the font](https://www.zachleat.com/web/css/fonts/lato/2.0/LatoLatin-Regular.supersubset.woff2) in the pyftsubset step?
 
I though maybe the first character in the range gets ignored, but the same happens with `U+0040-007a` instead of `U+0041-007a`.

**Comment by behdad** [comment]
Is the font missing glyph names?

**Comment by RoelN** [comment]
I'm not sure I understand, in the `GlyphOrder` table you mean? (They do there)

**Comment by anthrotype** [comment]
don't pass the `--no-notdef-glyph` option, unless you also have `.notdef` in the list of glyph ids or names to keep. You always want to keep the .notdef glyph (at index 0), optionally without the outline.

**Comment by behdad** [comment]
Dropping .notdef glyph in a webfont does NOT make sense. Don't do it. We should change subsetter help output to warn against doing it.

**Comment by RoelN** [comment]
I'm not — this was just an exercise, but decided to report the bug in case this indicated a bigger problem. Feel free to close!
