### ISSUE TITLE
[designspaceLib] rules element enhancement

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1243]
If we want to use the `<rule>` element to specify feature variations, we need a bit more than the current `<condition>` element to achieve the level of expressiveness that #1240's `addFeatureVariations()` offers.

https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#50-rules-element

As it stands, the `<rule>` element contains one or more `<condition>` elements, followed by `<sub>` elements. In the context of #1240, this means only "rectangular" (*) regions can be specified. To specify more complex regions we would need to group conditions.

*) "rectangular" if we're talking about a two-dimensional design space. In reality there are N dimensions.

Current syntax:

```xml
<rules>
  <rule name="named.rule.1”>
    <condition minimum="155" maximum="190" name="weight" />
    <condition minimum="50" maximum="100" name="width" />
    <sub name="dollar" byname="dollar.alt”/>
  </rule>
</rules>
```

Proposed new syntax:

```xml
<rules>
  <rule name="named.rule.1”>
    <conditionset>
      <condition minimum="155" maximum="190" name="weight" />
      <condition minimum="50" maximum="100" name="width" />
    </conditionset>
    <conditionset>
      <condition ... />
      <condition ... />
    </conditionset>
    <sub name="dollar" byname="dollar.alt”/>
  </rule>
</rules>
```
The `<condition>` elements within a `<conditionset>` element form an `AND` chain: all conditions must be true to make the `<conditionset>` true. Only one `<conditionset>` needs to be true to trigger the rule, so the set of `<conditionset>` elements together form an `OR` chain. (Apologies if I'm using odd terminology, I hope the intent is clear.)

A `<conditionset>` would correspond to a `Space` in `featureVar.py` terminology, and a set of `<conditionset>` elements would correspond to a `Region`:
https://github.com/fonttools/fonttools/blob/0f1c6b3cf4465a5cf47c959ec5a24e28c3bb352f/Lib/fontTools/varLib/featureVars.py#L94-L102

I'm not sure to what extent the `<rule>` element is already in active use, but I can imagine (keeping) allowing "bare" `<condition>` elements, which together would imply a single `<conditionset>`. Perhaps that's even desirable apart from bw-compat reasons, as it keeps the simple case simple.

**Comment by LettError** [comment]
Proposal for adding `conditionset` to the `rule` element in designspace and a `conditionSet` attribute to the `ruleDescriptor` object: https://github.com/fonttools/fonttools/commit/066a9c9061f39a5af5114870f17f445c215b9056 .

**Comment by LettError** [comment]
The `name` attribute of the `rule` element should be optional. It's not needed when compiling a font.

**Comment by behdad** [comment]
SGTM.

**Comment by anthrotype** [comment]
spec updated to support `conditionset` in `rule` elements (#1254), now RuleDescriptor needs to be changed accordingly.

**Comment by LettError** [comment]
I'm writing something for that.

**Comment by anthrotype** [comment]
oh.. I was also working on that :grimacing:

**Comment by anthrotype** [comment]
i'm gonna push to a WIP branch and we can work on it together

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/pull/1255 and subsequent clean-ups implemented conditionSets for the RuleDescriptor object
