### ISSUE TITLE
[varLib.mutator] Mutator doesn't evaluate FeatureVariations

### ISSUE THREAD

**Issue by robmck-ms** [fonttools/fonttools#1244]
Mutator doesn't evaluate the instance coordinate against FeatureVariations in GPOS/GSUB. So, if you have a font that makes use of FeatureVariations, and generate an instance at a place where something interesting happens (e.g. currency symbols switch to alternate forms that don't have a slash all the way through), you don't get the alternate behavior. 

I'd guess that mutator could just evaluate the condition sets and fix up the references to lookup tables accordingly in the instance. Pruning unused lookups might be tricky, but leaving a few unused (and probably small) lookups might not be too bad in the meantime.

**Comment by behdad** [comment]
Can you share a test font please?

**Comment by justvanrossum** [comment]
I could build one, but that would take a while. Maybe @thundernixon or @petrvanblokland have a test font that uses FeatureVariations that's suitable for testing this? Or @irenevl? Or @thomgb?

**Comment by petrvanblokland** [comment]
I'll  make one today.

**Comment by robmck-ms** [comment]
You can also use Bahnschrift, which has 10 characters that use feature variations (e.g. dollar, oslash, etc). 

Email me privately if you need a copy for testing purposes.

**Comment by behdad** [comment]
Any volunteers to take a look at this?

**Comment by robmck-ms** [comment]
Thanks!
