### ISSUE TITLE
Compile TTC 

### ISSUE THREAD

**Issue by vXBaKeRXv** [fonttools/fonttools#1247]
Easy enough to get the new TTCollection lib to extract a TTC.
 Cant manage to figure out how to compile a set of fonts into a TTC with FontTools. 
Can someone produce a example ?
Thanks!

The open source Adobe FDK tools is gone. It would be nice to fall back on using only FontTools.
otc2otf.py
otf2otc.py

**Comment by behdad** [comment]
Something like:
```py
  ttc = TTCollection()
  ttc.fonts = [TTFont('file1.ttf'), TTFont('file2.ttf'), ...]
  ttc.save('out.ttc')
```

**Comment by behdad** [comment]
Someone should implement otc2otf and otf2otc.

**Comment by vXBaKeRXv** [comment]
@benkiel I guess this source is dead. Thanks! https://github.com/adobe-type-tools/afdko/blob/master/FDK/Tools/SharedData/FDKScripts/otf2otc.py

@behdad Ahhh I was close... I knew it wasn't to complex. You Rock! Thanks -

This would be great! 
"Someone should implement otc2otf and otf2otc."

**Comment by diaowinner** [comment]
> @benkiel I guess this source is dead. Thanks! https://github.com/adobe-type-tools/afdko/blob/master/FDK/Tools/SharedData/FDKScripts/otf2otc.py

This link is still dead, is it <https://github.com/adobe-type-tools/afdko/blob/master/python/afdko/otf2otc.py>?

**Comment by behdad** [comment]
You can also now do:
```
$ fonttools ttLib font1.ttf font2.ttf ... -o font.ttc
```
