### ISSUE TITLE
[subset] Drops user nameIDs

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1251]
Subsetter drops all names other than specified. This includes names referenced from fvar / GSUB / GPOS etc.

Maybe we should NOT drop user nameIDs. Ie. the ones >= 256.

When we have the logic for, we can drop those if we also remove the reference to them.

**Comment by behdad** [comment]
Or just do the right thing and collect all referenced user nameIDs and subset to those.

**Comment by anthrotype** [comment]
actually we do keep names referenced by fvar:

https://github.com/fonttools/fonttools/blob/ae4472860f1c95b4a967bebe927c601473bd2f37/Lib/fontTools/subset/__init__.py#L2662-L2669

basically we need to do the same for the FeatureParams tables used in stylistic sets, character variants, size features, and what else?

**Comment by miguelsousa** [comment]
The `CPAL` table can also contain references to `name` table IDs.

**Comment by justvanrossum** [comment]
It currently (fonttools 4.16.1) keeps names from `fvar` and `STAT`, but still not from `CPAL`, `GPOS` or `GSUB`.

**Comment by jenskutilek** [comment]
It seems that if the subsetter is told to drop the `STAT` table, any user nameIDs referenced in it are still kept in the font.

**Comment by khaledhosny** [comment]
This seems to have been long fixed.
