### ISSUE TITLE
[varLib] Extrapolate

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1252]
This is @LettError 's favorite feature. We should support it. I have ideas.

**Comment by LettError** [comment]
Here "extrapolate" should mean "allowing the calculation of shapes outside the +/- 1.0 range", right?

**Comment by behdad** [comment]
> Does this mean merely not clamping to normalized +/- 1.0 within interpolation in mutator/models?

No, requires more work than just that.

**Comment by LettError** [comment]
Sorry to see.

**Comment by behdad** [comment]
> Sorry to see.

I feel nerdsniped now. Lemme think about it. :)
