### ISSUE TITLE
[varLib] Building CFF VF's broken by commit ca7cd857 on Feb 19

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#1258]
In `__init__.py`, `_merge_TTHinting()` is now called **if 'cvar' is not in 'exclude'**, rather than **if 'glyf' is in the font**. For CFF2 fonts, this causes `_merge_TTHinting` to be called, which naturally fails. The test for 'cvar' (currently at line 770) needs to add **`and 'glyf' in vf`**, like the previous lines.

**Comment by anthrotype** [comment]
this commit https://github.com/fonttools/fonttools/pull/1211/commits/8d2214c32b7f1c8a5ab95212ec5b8c70977e1b6d from PR #1211 (still open) fixes that.
Shall I cherry pick that into master? What's the status of that PR?

**Comment by anthrotype** [comment]
Fixed by https://github.com/fonttools/fonttools/commit/4da8f43eeb1e5ad6eb2a3288633392a46f8e3a33
