### ISSUE TITLE
[designspaceLib]: explicitly require POSIX file paths?

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#1259]
On my Windows machine, I stumbled into this error after I set the instance file paths to `WindowsPath`s:
```Python
[...]
    for instance in designspace.instances:
        instance.filename = Path(
            "..", "build", "instance_ufos", Path(instance.filename).name  # line 336
        )
        instance.path = None
    designspace.updatePaths()
[...]
```
```
Traceback (most recent call last):
  File "C:\UsersLocal\nikolaus.waxweiler\Development\...\venv\lib\site-packages\doit\action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\UsersLocal\nikolaus.waxweiler\Development\...\dodohelper.py", line 336, in glyphs2ufo
    "..", "build", "instance_ufos", Path(instance.filename).name
  File "C:\UsersLocal\nikolaus.waxweiler\Development\...\venv\lib\site-packages\fontTools\designspaceLib\__init__.py", line 71, in setter
    value = posix(value)
  File "C:\UsersLocal\nikolaus.waxweiler\Development\...\venv\lib\site-packages\fontTools\designspaceLib\__init__.py", line 56, in posix
    new_path = posixpath.join(*path.split(os.path.sep))
AttributeError: 'WindowsPath' object has no attribute 'split'
```
Using `.as_posix()` on the Path in the above line 336 makes it work on Windows. Should the documentation be updated to mandate POSIX paths when they work cross-platform?

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#6-notes

> Both filename and path must use forward slashes (/) as path separators, even on Windows.

**Comment by madig** [comment]
Whoops, didn't find that one. Maybe a more explicit error message would have helped. Can write something soon.

**Comment by anthrotype** [comment]
never mind

**Comment by madig** [comment]
Maybe it pays to make it a `Path` object.

**Comment by anthrotype** [comment]
@LettError I see two methods that do basically the same thing: [updateFilenameFromPath](https://github.com/fonttools/fonttools/blob/53ad36e42b539a31b58782aa5a52f5a64abecc92/Lib/fontTools/designspaceLib/__init__.py#L1139-L1153) and [updatePaths](https://github.com/fonttools/fonttools/blob/53ad36e42b539a31b58782aa5a52f5a64abecc92/Lib/fontTools/designspaceLib/__init__.py#L1071-L1117), can we simplify and get rid of one? I'd just keep the latter.

**Comment by LettError** [comment]
Ok
