### ISSUE TITLE
fontTools merge.py: mark2mark OT feature broken

### ISSUE THREAD

**Issue by BlackFoundry** [fonttools/fonttools#1260]
When merging a freshly compiled font from "NotoSansThai-MM.glyphs" font with "NotoSans-Regular.ttf" (Latin) the "mkmk" OT feature seems to be broken when testing the resulting font (mark to mark not stacking as intended)

test case:
[gist](https://gist.github.com/BlackFoundry/7950dde3b67e2deded3729065fb894ec)
resulting NotoSansThaiOnly-Regular.ttf works as expected
while NotoSansMergedThai-Regular.ttf does not.

I am still investigating, but any insight would be much appreciated.

**Comment by BlackFoundry** [comment]
Didn't found the reason of why, and not sure whether it comes from GPOS 'mkmk' or GSUB 'ccmp' features yet.
But swapping the order of the fonts to merge solved the issue: first Thai, second Latin.

**Comment by behdad** [comment]
Is this still valid?

**Comment by BlackFoundry** [comment]
yes: 
if Thai First, Latin second, mark to mark positioning works.
if Latin first, Thai second, mark to mark positioning does not work

**Comment by behdad** [comment]
What's a good test sequence?  Marks in Thai don't work or Latin?

**Comment by miloush** [comment]
Might be related (but also not): merging Noto Sans Grantha before Tamil results in broken vowel attachments and substitutions (red):

![image](https://user-images.githubusercontent.com/10546952/116980178-d5c22900-acbd-11eb-9076-3651d6e452da.png)

Merging Tamil first i.e. `pyftmerge NotoSansTamil-Regular.ttf NotoSansGrantha-Regular.ttf` works as expected (blue). The test string above is ப்பிபீபுபூவு.

**Comment by BlackFoundry** [comment]
Yes I think the Tamil issue you show is related.
@behdad sorry I missed your message from 28 Nov 2018 😅!!

Marks in Thai do not work properly when merged with ordered list: [Latin, Thai]
Thai behaves normally when merged with ordered list: [Thai, Latin]

**Comment by behdad** [comment]
I'm... hacking on the merger as we speak...

**Comment by behdad** [comment]
Basically, we don't merge LookupFlags properly. I'll get on it.

**Comment by behdad** [comment]
Fix in https://github.com/fonttools/fonttools/pull/2474
Please test.

**Comment by dscorbett** [comment]
Are mark classes merged properly too?

**Comment by satbyy** [comment]
@behdad  I tested the same sequence shared above by @miloush . I think the bug still exists:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/17479988/146183292-40bf6ee5-0f0f-4322-8755-ea5fbc63851f.png">

As before, merging Tamil first seems to work.  I pulled both #2473  and #2474 before testing. The test string is ப்பிபீபுபூவு. After a fresh clone:

```
git pull origin pull/2473/head:behdad
git checkout behdad
git fetch origin pull/2474/head && git cherry-pick FETCH_HEAD
pip install .
fonttools merge NotoSansTamil-Regular.ttf NotoSansGrantha-Regular.ttf
mv merged.ttf tamil-grantha.ttf
fonttools merge NotoSansGrantha-Regular.ttf NotoSansTamil-Regular.ttf
mv merged.ttf grantha-tamil.ttf
 ```

**Comment by anthrotype** [comment]
let's keep open until somebody confirms whether the bug reported by @satbyy in https://github.com/fonttools/fonttools/issues/1260#issuecomment-994732395 is related to MarkFilteringSets not being merged (should be fixed by #2474) or something else

**Comment by dscorbett** [comment]
The Grantha/Tamil issue is #2475.

**Comment by behdad** [comment]
> The Grantha/Tamil issue is #2475.

Indeed.

**Comment by behdad** [comment]
> Are mark classes merged properly too?

Mark classes are not renumbered so the existing merge logic works fine.
