### ISSUE TITLE
[varLib.mutator] Does not mutate weight/width/italicAngle

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1264]
Because those are not in MVAR, but in standard axes. Quoting MVAR spec:

> Note: The OS/2.usWeightClass, OS/2.usWidthClass and post.italicAngle values are not supported by variation data in the 'MVAR' table. This is because values for these three fields correspond directly to input axis values for the 'wght', 'wdth' and 'slnt' variation axes. See the discussion of these axes in the OpenType Design-Variation Axis Tag Registry for details on the relationship between these fields and the corresponding design axes.

There's probably some binary flags that we can also tweak, re boldness, italicness, etc of the font.

**Comment by anthrotype** [comment]
> There's probably some binary flags that we can also tweak, re boldness, italicness, etc of the font

OK, it's clear what to do with OS/2.usWeightClass, usWidthClass and post.italicAngle.

But, about the `OS/2.fsSelection` or `head.macStyle` which @behdad is hinting at in his comment -- when exactly do we want to set the bold flags? Say, when the location on the `wght`
axis and the corresponding OS/2.usWeightClass is _exactly_ 700? But not when it's 699 or 900 or whatever?

And about the "italic" font selection flags, I think we should not set those based on "slnt" axis. The latter should only be correlated to the "post.italicAngle". The "ital" registered axis might be used instead, but again if we do that, where do we put the threshold? When it's 100% italic, or >= 50 %?
This all seem a bit arbitrary to me.

**Comment by behdad** [comment]
Thanks for working on this.

Re bold bit, I think anything > SemiBold should be marked as bold...

**Comment by anthrotype** [comment]
hmm I'm not sure that's a good idea.
Usually in a family where there are several bolder variants, only one of them, namely the "Bold", around 700 weightClass, is the one that gets the bold fontSelection/macStyle flags enabled. A "Black" or similar are bolder than Bold, but they don't usually get the bold flag enabled.

**Comment by anthrotype** [comment]
(dind't mean to close, sorry)

**Comment by anthrotype** [comment]
actually, maybe for setting the Bold (and Italic) font selection flags, we should not look at the OS/2 weightClass at all, but rather we should use the STAT tables. Hm, yeah :thinking: 
ok i'll merge this for now, will work on the latter later.

**Comment by m4rc1e** [comment]
Google Fonts only sets fsSelection bit 7 and macStyle to bold for the Bold style only. SemiBold, Black, ExtraBlack etc are set to Regular.

**Comment by m4rc1e** [comment]
We have a sheet outlining how we set bits and names for each style, https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0. Some of this may be out of date though.

**Comment by anthrotype** [comment]
OS/2 weight/width class and post.italicAngle have been implmented already wit hhttps://github.com/fonttools/fonttools/pull/1276

for the OS/2.fsSelection and head.macStyle bits, I'm not sure what we should do. Maybe simply check the nameID=2 (legacy style name used for RBBI style-linking) and set Bold/Italic flags when the string exactly match either "Italic", "Bold" and "Bold Italic"?

**Comment by behdad** [comment]
mutator is on the way to be deprecated in favor of instancer module.
