### ISSUE TITLE
Suggested addition of error print in debugging VF building

### ISSUE THREAD

**Issue by petrvanblokland** [fonttools/fonttools#1268]
I am using this useful local change, to get an indication for what is causing the doubling, instead of plain assert.

	def getMasterLocationsSortKeyFunc(locations, axisOrder=[]):
		assert {} in locations, "Base master not found."
		axisPoints = {}
		for loc in locations:
			if len(loc) != 1:
				continue
			axis = next(iter(loc))
			value = loc[axis]
			if axis not in axisPoints:
				axisPoints[axis] = {0.}
			#assert value not in axisPoints[axis]
			if value in axisPoints[axis]:
				print('Value "%s" in axisPoints["%s"] -->  %s' % (value, axis, axisPoints))
				raise ValueError
			axisPoints[axis].add(value)

**Comment by behdad** [comment]
Thanks. You can add the debug message to the assert itself as its second argument. Feel free to send a pull-request.
