### ISSUE TITLE
[varLib] 2D designspace with 6 masters creates wrong var font

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1269]
The enclosed designspace contains two axes, "FOOO" and "BARR". There are masters at all four corners, as well as intermediate masters in the middle of the "BARR" axis at both "FOOO" master positions.

At FOOO=0 all is well. At FOOO=1, the resulting shape at BARR=0.5 is wrong, and does not match the master at that position.

Below is the complete gvar. 

What is curious is that the FOOO=0 BARR=1 delta location is given as:
```xml
        <coord axis="BARR" max="1.0" min="0.5" value="1.0"/>
```
yet the FOOO=1 BARR=1 delta location is given as:

```xml
        <coord axis="FOOO" value="1.0"/>
        <coord axis="BARR" value="1.0"/>
```
Note the missing (and therefore different) `min` and `max` values for "BARR".

```xml
  <gvar>
    <version value="1"/>
    <reserved value="0"/>
    <glyphVariations glyph="uni0041">
      <tuple>
        <coord axis="FOOO" value="1.0"/>
        <delta pt="0" x="50" y="-233"/>
        <delta pt="1" x="-233" y="-50"/>
        <delta pt="2" x="-50" y="233"/>
        <delta pt="3" x="233" y="50"/>
        <delta pt="4" x="0" y="0"/>
        <delta pt="5" x="0" y="0"/>
        <delta pt="6" x="0" y="233"/>
        <delta pt="7" x="0" y="233"/>
      </tuple>
      <tuple>
        <coord axis="BARR" max="1.0" min="0.0" value="0.5"/>
        <delta pt="0" x="300" y="-21"/>
        <delta pt="1" x="229" y="-50"/>
        <delta pt="2" x="200" y="21"/>
        <delta pt="3" x="271" y="50"/>
        <delta pt="4" x="0" y="0"/>
        <delta pt="5" x="0" y="0"/>
        <delta pt="6" x="0" y="21"/>
        <delta pt="7" x="0" y="21"/>
      </tuple>
      <tuple>
        <coord axis="BARR" max="1.0" min="0.5" value="1.0"/>
        <delta pt="0" x="500" y="0"/>
      </tuple>
      <tuple>
        <coord axis="FOOO" value="1.0"/>
        <coord axis="BARR" max="1.0" min="0.0" value="0.5"/>
        <delta pt="0" x="190" y="64"/>
        <delta pt="1" x="64" y="-190"/>
        <delta pt="2" x="-190" y="-64"/>
        <delta pt="3" x="-64" y="190"/>
        <delta pt="4" x="0" y="0"/>
        <delta pt="5" x="0" y="0"/>
        <delta pt="6" x="0" y="-64"/>
        <delta pt="7" x="0" y="-64"/>
      </tuple>
      <tuple>
        <coord axis="FOOO" value="1.0"/>
        <coord axis="BARR" value="1.0"/>
        <delta pt="0" x="0" y="-125"/>
        <delta pt="1" x="-125" y="0"/>
        <delta pt="2" x="0" y="125"/>
        <delta pt="3" x="125" y="0"/>
        <delta pt="4" x="0" y="0"/>
        <delta pt="5" x="0" y="0"/>
        <delta pt="6" x="0" y="125"/>
        <delta pt="7" x="0" y="125"/>
      </tuple>
    </glyphVariations>
  </gvar>
```

If I manually edit the TTX so that last delta location contains min and max for BARR, to match the other BARR=1 delta location, and recompile, I get a font that works as expected.

[fonttools-bug-report.zip](https://github.com/fonttools/fonttools/files/2074036/fonttools-bug-report.zip)

Cc. @thundernixon

**Comment by thundernixon** [comment]
Thanks so much for helping file a simplified version of this issue, @justvanrossum!

In case it's useful to show how this affects a real-world font, I'll show a few letters of a current project. I'm showing this in FontView, but the same error appears in browsers, Illustrator, etc. I have a font with a "genre" axis and a weight axis. The first genre works well across weights, but the middle weight of the second genre is "dropping out," and merely showing an interpolation of the extreme light and heavy masters. (This is a monospace font, but the problem happens in proportional glyphs, too).

Good: Lightest weight, genre 1
![image](https://user-images.githubusercontent.com/7355414/41032555-135eb984-6984-11e8-827e-07cf54f4b89b.png)

Good: middle weight, genre 1
![image](https://user-images.githubusercontent.com/7355414/41032578-242d3db2-6984-11e8-9a6f-ca2913167c2f.png)

Good: heavy weight, genre 1
![image](https://user-images.githubusercontent.com/7355414/41032582-270b4290-6984-11e8-8ef4-2c3ac9d02984.png)

Good: light weight, genre 2
![image](https://user-images.githubusercontent.com/7355414/41032711-89c6bc02-6984-11e8-8ddb-6d2c1f694bb3.png)

Bad: middle weight, genre 2 😬
![image](https://user-images.githubusercontent.com/7355414/41032732-93720900-6984-11e8-9aaa-64e9f6f08939.png)

Good: heavy weight, genre 2
![image](https://user-images.githubusercontent.com/7355414/41032744-9ecf29a4-6984-11e8-9234-29f6d2d1c9eb.png)

**Comment by anthrotype** [comment]
Thanks both for the detailed report. It might have to do with the improved support-resolution algorithm @behdad worked on recentely.

To help visualise the designspace with an interactive 3d plot, you could try running this command:

```
$ fonttools varLib.plot fonttools-issue-report.designspace
```

Which gives this (here it's a static png, but in the matplotlib window, you can also zoom, pan, etc.):

![figure_1](https://user-images.githubusercontent.com/6939968/41036375-c38c3e14-6987-11e8-9134-382f5cdb41fe.png)

**Comment by justvanrossum** [comment]
@behdad can you please have a look? This is a fairly serious bug.

**Comment by behdad** [comment]
Will do today.

**Comment by behdad** [comment]
I can confirm the bug.  Investigating.

**Comment by behdad** [comment]
Ok, fixed. Sorry about that again.

**Comment by anthrotype** [comment]
@behdad thank you! :+1:

**Comment by justvanrossum** [comment]
Yes, thanks, @behdad!
