### ISSUE TITLE
Request to not configure logging as an import-time side-effect (on Python 2)

### ISSUE THREAD

**Issue by mdickinson** [fonttools/fonttools#1277]
We just tracked down some surprising behaviour in our test runs to the fact that `fontTools` configures logging at import time, swapping out the default `Logger` class for a custom implementation and adding a handler of last resort. The relevant code is in the `py23` module [here](https://github.com/fonttools/fonttools/blob/b2d47132bf17d093c2b57d558ad08f181ea2dfd4/Lib/fontTools/misc/py23.py#L472-L483). I understand the motivation here (having consistent behaviour between Python 2 and Python 3), but it's a surprise to find a library doing logging configuration: in general, my understanding of logging best practices is that logging configuration should be the domain of an application (where a test runner also counts as a form of application) using libraries that do logging, rather than the libraries themselves. (Imagine if each of the many libraries being used in an application tried to do its own logging configuration...)

Would you consider removing the logging configuration as an import-time side-effect of importing `fontTools`?

Code to reproduce the issue. Part of the surprise here is just in the logger's repr resulting from the patched `Logger` class: seeing `fontTools.misc.py23` turn up in the `repr` of a logger that has nothing to do with the `fontTools` library.

```
Enthought Deployment Manager -- https://www.enthought.com
Python 2.7.13 |Enthought, Inc. (x86_64)| (default, Mar  2 2017, 08:20:50) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.lastResort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'lastResort'
>>> import fontTools
>>> logging.lastResort
<fontTools.misc.py23._StderrHandler object at 0x1007a4310>
```

**Comment by anthrotype** [comment]
Thanks for opening this issue.
Just out of curiosity, what is this "surprising behaviour in your test runs"?
I don't really see what we are doing here as a "logging configuration", but rather more like adding a compatibility shim to enable logging code to behave the same way on python 2 and 3.
the recommendation to set lastResort to None, comes from the python 3 docs actually:
https://docs.python.org/3.6/howto/logging.html#what-happens-if-no-configuration-is-provided

**Comment by anthrotype** [comment]
But I see your point that just the mere `import fontTools` should not automatically swap the default python2 Logger class with one that defines a lastResort handler (like the python3 Logger).
I'll move that code to our own `configLogger` function, which is used only by our own command line scripts.
I'll fix this soon, sorry the trouble!

**Comment by mdickinson** [comment]
> what is this "surprising behaviour in your test runs"

Simply that we were seeing messages printed out during the test run, and since they didn't have any kind of "WARNING: ..." prefix, it wasn't immediately clear that they were coming from the logging system. When it did become clear that they were logging messages, it wasn't clear _why_ they were being printed out, and we needed to do some digging to find out how this was happening. This is (currently, at least) a Python 2-only application, and the behaviour we expect to see if no logging is configured is the usual "No handlers could be found" message. `fontTools` is just one of many (over 100) packages used by the application. The new messages started showing up in the test suite after various package updates, and it wasn't clear which of those updates caused the behaviour change.

> the recommendation to set lastResort to None, comes from the python 3 docs actually

Understood; that's definitely the right way for a Python 3 application to get back the Python 2 behaviour. But it's surprising when a Python 2 application isn't following the usual logging behaviour, without the application having explicitly configured the logging system.

**Comment by anthrotype** [comment]
fixed by https://github.com/fonttools/fonttools/commit/e6a5db543d8a5be34db5d007a9d5634ae2a2edde

a new release is coming before end of the week

thanks for using fonttools!

**Comment by mdickinson** [comment]
Wow! Thanks for the quick fix!
