### ISSUE TITLE
feaLib shouldn’t ignore subtable statements 

### ISSUE THREAD

**Issue by moyogo** [fonttools/fonttools#1279]
The AFDKO syntax spec says:
> **4.g. subtable**
> The feature file implementation must insert subtable breaks among the rules for a particular lookup if needed. For example, if a set of alternate substitution rules specified in the feature file exceeds the subtable size limit, several subtables must be automatically created.
>
>The "subtable" statement may be used as follows:
>`  subtable;`
>to explicitly force a subtable break after the previous rule.
>
>This is intended for use with only Pair Adjustment Positioning Format 2 (i.e. pair class kerning). See 6.b.iii for details. This hint to the compiler is required for class kerning, as it is difficult for a compiler to determine where to best place a subtable break in this lookup type, in order to reduce lookup size.

I tested writing a kern feature lookup with inserted `subtable` statements. As is, fonttools generates GPOS that is 94114 bytes for one of our fonts. If it was applying the `subtable` statements the GPOS would be 55712 bytes.

**Comment by miguelsousa** [comment]
Judging from comments that Behdad has made about the results of [otf-making-benchmark](https://github.com/adobe-type-tools/otf-making-benchmark) I don't think it's the ignoring of `subtable` that's causing the significant size difference; makeotf uses some tricks to reduce the size of GPOS that are not implemented in feaLib.

**Comment by miguelsousa** [comment]
@moyogo see https://github.com/adobe-type-tools/otf-making-benchmark/issues/1
I haven't had any time to dedicate to this project unfortunately.

**Comment by moyogo** [comment]
I think these are two separate issues. While a lookup without any subtable statements should be compiled as efficiently as possible, a lookup with subtable statements should be compiled as specified.

**Comment by anthrotype** [comment]
it's in the spec, so I guess we should support manual `subtable` breaks.
