### ISSUE TITLE
Recursive dis- / assembling

### ISSUE THREAD

**Issue by Vampire** [fonttools/fonttools#1284]
It would be nice if you support recursive disassembling and assembling.

What I mean you can see if you e. g. convert FiraCode font. In the glyphs you have instructions, but the disassembly is `NPUSHB`, all remaining bytes except one `CALL`.

If I got this right, then the bytes pushed to stack are executed as function until `ENDF` is found, so the bytes on the stack should be reversed, then disassembled, taking into account when instructions would consume bytes from the stack and showing them as arguments instead of dissembling them to instructions until an `ENDF` is found that is an instruction and not data. If there was more pushed to the stack it should be shown as data, unless another `CALL` uses them.

For reassembling this should of course also be taken into consideration.

Otherwise it might be hard to impossible to modify such a glyph correctly.

**Comment by justvanrossum** [comment]
That's not at all how CALL works. See https://developer.apple.com/fonts/TrueType-Reference-Manual/RM05/Chap5.html#CALL

**Comment by Vampire** [comment]
Ah sorry, totally got that wrong then.
So, if there is in the glyph
```asm
NPUSHB[ ]	/* 42 values pushed */
45 40 39 38 30 23 22 20 19 13 7 6 4 3 0 15 1 2 1 74 0 2 1 2 131
0 0 1 0 132 0 1 1 73 1 76 30 17 30 3 9 23
CALL[ ]	/* CallFunction */
```
how do you know and modify what is called?
Could this be analyzed / shown a bit more extensive, like some pointer at where it jumps to in the file?

**Comment by justvanrossum** [comment]
I think it's calling "function 23" which will be defined in the pre-program (the `prep` table) or in the font-program (the `fpgm` table).

**Comment by Vampire** [comment]
Yes, I think so too.
But it would nice to have this clearer, e. g. having there `CALL[23]` and at the `FDEF` e. g. `FDEF[23]	/* FunctionDefinition 23 */` or similar, so that you can more easily navigate between those connection points.

**Comment by behdad** [comment]
That's beyond what disassembling is..

**Comment by Vampire** [comment]
Yes, it is a little additional analyzing, but it would be super handy to have it and greatly improve the usefulness of the disassembly.

**Comment by behdad** [comment]
It's more than "a little additional analyzing". In fact, someone did a Master's thesis on just the initial steps of analyzing TrueType bytecode...

https://uwspace.uwaterloo.ca/bitstream/handle/10012/9116/Man_Wenzhu.pdf

Pat Lam has a fork of fonttools on github with code for that.  Cannot find right now.

**Comment by lemzwerg** [comment]
Indirect function calls will be never displayable as you suggest.  For example, the bytecode might use your value 23 only if the ppem value is 17 to 20, and the font variation axis 7 is in the range 0.3 to 0.4. For everything else, the stack value might be constructed to be 24.  The same holds for almost everything else: In many cases, CVT and storage area values are depending on various conditions like stroke width at a given display resolution.

It is extremely hard, tiresome, and frustrating to read and _understand_ foreign bytecode...
