### ISSUE TITLE
Does fontTools do what fastfont.exe did?

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#1286]
There used to be an old tool from Microsoft call fastfont.exe which repacked TrueType/OpenType fonts in an optimized way. 

However I can no longer find it on the MS site (https://www.google.com/search?q=ms+font+tools+%22fastfont.exe%22) 

I wonder if fontTools, when it writes out a binary, uses the same optimization techniques?

**Comment by benkiel** [comment]
AFAIK it does.

**Comment by anthrotype** [comment]
all fastfont.exe does is ensure the sfnt tables are sorted according to the "recommended" ordering, so yes, fonttools SfntWriter always does that by default.
