### ISSUE TITLE
[ttx] Recommend allowing the <extfileimagedata> value in EBDT/CBDT table to use a relative path

### ISSUE THREAD

**Issue by LIXiangChen** [fonttools/fonttools#1288]
Another problem is, currently the top-level-folder where the dumped images saved is named `bitmaps/`, if dump multiple fonts in the same directory will be confused, I recommend changing the folder to the same name as the source font file or the XML file.

Example:

**Directory Structure**
```
| ColorEmoji.ttf    // Source file
| ColorEmoji.ttf/    // Images folder that auto created
    | strike0/
        | u1F438.png
        | ...
| ColorEmoji.ttx    // XML file
```

**`<extfileimagedata>` in EBDT/CBDT table**
```
<extfileimagedata value="ColorEmoji.ttf/strike0/u1F438.png"/>
```

**Comment by anthrotype** [comment]
doesn't the existing `ttx -d <outputfolder>` option also work for this use case?

**Comment by LIXiangChen** [comment]
Oh, thank you. It should be that when I tested, the path was misspelled, which caused the program error.

**Comment by anthrotype** [comment]
no prob! can we close this?

**Comment by LIXiangChen** [comment]
Ok, but why only use relative path when specifying the `-d` option instead of using it all the time?

**Comment by anthrotype** [comment]
sorry I don't get what you mean by "relative path" in this context?

**Comment by LIXiangChen** [comment]
Very strange... I just tried it again, the <extfileimagedata> path is a relative path. But in my impression it has always been an absolute path... Maybe my memory is in a mess. Sorry, please close the issue.

**Comment by anthrotype** [comment]
oh, I get it now! yes, if you pass an absolute path to ttx as the input file, you'll get an absolute path written out in the ttx dump for the bitmaps folder. If you use -d option, similarly, you can use a relative path and that will be used. So, the code doesn't enforce relative or absolute, let's the user decide. Sounds good to me.

**Comment by anthrotype** [comment]
no need to be sorry! you're always welcome to open issues or ask questions here or in the chat room https://gitter.im/fonttools-dev/Lobby
I myself am not very familiar with that part of the code base that deals with color font formats, that's why initially I didn't know what you were referring to.

**Comment by LIXiangChen** [comment]
Oh I see. `<extfileimagedata>` is a relative path or absolute path depending on the `inputfile` path. I usually like to drag file into the command window, which will input an absolute path, so `<extfileimagedata>` is also an absolute path. It's smart!
