### ISSUE TITLE
Cannot parse some pfb files

### ISSUE THREAD

**Issue by dadasutasudadas** [fonttools/fonttools#1293]
When I tried to parse a pfb file created with Fontlab 5.2.1 Win, it cause an error.
I set it to logging level "DEBUG".
There are PFB that parse() succeeds and some PFB that fails.
How can I overcome this error?

```
>>> import fontTools
>>> fontTools.__version__
'3.28.0'

>>> from fontTools.t1Lib import T1Font
>>> pfb=T1Font("font.pfb")
>>> pfb.parse()
ps error:
- - - - - - -
ifelsenown { save true } { false } ifelse }
>>>
{ 100 dict /internaldict known not
- - - - - - -
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python2.7/site-packages/fontTools/t1Lib/__init__.py", line 92, in parse
    self.font = psLib.suckfont(self.data, self.encoding)
  File "/lib/python2.7/site-packages/fontTools/misc/psLib.py", line 358, in suckfont
    interpreter.interpret(data)
  File "/lib/python2.7/site-packages/fontTools/misc/psLib.py", line 194, in interpret
    handle_object(object)
  File "/lib/python2.7/site-packages/fontTools/misc/psLib.py", line 220, in handle_object
    object.function()
  File "/lib/python2.7/site-packages/fontTools/misc/psOperators.py", line 355, in ps_ifelse
    self.call_procedure(proc2)
  File "/lib/python2.7/site-packages/fontTools/misc/psLib.py", line 227, in call_procedure
    handle_object(item)
  File "/lib/python2.7/site-packages/fontTools/misc/psLib.py", line 220, in handle_object
    object.function()
  File "/lib/python2.7/site-packages/fontTools/misc/psOperators.py", line 250, in ps_exec
    self.call_procedure(obj)
  File "/lib/python2.7/site-packages/fontTools/misc/psLib.py", line 227, in call_procedure
    handle_object(item)
  File "/lib/python2.7/site-packages/fontTools/misc/psLib.py", line 213, in handle_object
    object = self.resolve_name(object.value)
  File "/lib/python2.7/site-packages/fontTools/misc/psLib.py", line 234, in resolve_name
    raise PSError('name error: ' + str(name))
fontTools.misc.psLib.PSError: name error: ,ifelse
```

**Comment by justvanrossum** [comment]
Can you add a test font to this issue?

**Comment by dadasutasudadas** [comment]
Thank you for your quick reply. I attached a test font.
[test.zip](https://github.com/fonttools/fonttools/files/2179373/test.zip)

**Comment by dadasutasudadas** [comment]
I attached another test font. This data can be pase ().
[test2.zip](https://github.com/fonttools/fonttools/files/2179436/test2.zip)

**Comment by anthrotype** [comment]
@dadasutasudadas how was the pfb generated? what editor?
I was able to parse it with `fontTools.t1Lib` after using the afdko's `tx` tool, by converting the .pfb to Type-1 .pfa format, like so:

```
$ tx -t1 test.pfb > test.pfa
```

[test.pfa.zip](https://github.com/fonttools/fonttools/files/2224585/test.pfa.zip)

I'm not familiar with postscript language, but that comman in the reported error message looks suspicious:

```
PSError: name error: ,ifelse
```

**Comment by miguelsousa** [comment]
> how was the pfb generated? what editor?

>>pfb file created with Fontlab 5.2.1 Win

**Comment by anthrotype** [comment]
oh I see, you mentioned that already, I'd missed that line :sweat_smile:

**Comment by dadasutasudadas** [comment]
I understood that the cause of the problem is the pfb output method of Fontlab 5.2.1. OtherSubrs was not output correctly.
I checked OtherSubrs using t1disasm and confirmed the existence of unnecessary "comma" such as ", ifelse", ",}", ", dup".
When "Generate Flex hints" check is on, this "impurity" is mixed.
Compared with the example given in Appendix 3 of Adobe Type 1 Font Format, I can see that "," is unnecessary
I will report these problems to Fontlab.

Although this is hopeful, it is desirable for me to run the program by outputting an error rather than stopping the program even if an illegal operator is found.
Is it reasonable to expect that psLib etc will be updated as such?

**Comment by justvanrossum** [comment]
As far as I can see FontLab emits invalid PostScript, so this font is simply broken. I'm not sure how `tx` manages to make sense out of it.

It is not reasonable to expect fontTools to handle arbitraraly buggy fonts.

**Comment by justvanrossum** [comment]
@twardoch
