### ISSUE TITLE
pyftsubset generated WOFF2 renders fine on Firefox/Chrome but shows gibberish on Safari

### ISSUE THREAD

**Issue by kaushalmodi** [fonttools/fonttools#1294]
Hello,

For quite some time, this issue had been bugging me -- See https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/issues/3.

For some reason, the text from my blog showed up as gibberish on Safari, but worked fine on Firefox/Chrome.

After countless hours of debug, tweaking CSS, changing fonts, etc, I narrowed down to the issue that Safari cannot render the pyftsubset generated WOFF2.

I have the .ttf version of the fonts, and I generate the woff and woff2 using this:

```
pyftsubset font.ttf  --layout-features="" --unicodes="U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF" --flavor=woff  --with-zopfli --output-file=font.woff
pyftsubset font.woff --layout-features="" --unicodes="U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF" --flavor=woff2 --output-file=font.woff2
```

If I use woff2 font, Safari shows my blog (https://scripter.co) like this (older screenshot, so content is different):

![](https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/uploads/75a1a51ce6804cddc692fc58231fc170/image.png)

You can even live-test this woff2/Safari issue by visiting https://woff2--scripter-co.netlify.com/ on Safari (iOS as I have consistently recreated this issue on mobile Safari on iPhone 8). If you visit https://test--scripter-co.netlify.com/ on the same browser, you will not see that issue as there I am using just the WOFF version of fonts.

But if I use the woff font, the text shows up fine.

Take the pyftsubset generated Merriweather-Regular.woff2 from [here][1] as an example.

- Using those files, would it be possible to help fix this rendering issue on Safari?
- Are my pyftsubset commands above correct?

[1]: https://gitlab.com/kaushalmodi/hugo-theme-refined/tree/woff2/static/fonts/merriweather/2.002/subset

**Comment by jenskutilek** [comment]
The fonts you see in Safari are fallback fonts, not your webfonts.

You have to omit the quotes in your pyftsubset command line for the --unicodes parameter:

```bash
pyftsubset font.ttf  --layout-features="" --unicodes=U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF --flavor=woff  --with-zopfli --output-file=font.woff
pyftsubset font.woff --layout-features="" --unicodes=U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF --flavor=woff2 --output-file=font.woff2
```

So your fonts are basically empty except for the notdef glyph. Strange bug in Safari though that this affects the text rendering in this way.

**Comment by anthrotype** [comment]
Hm, that the quotes in the argument value make a difference I would consider a bug. A command line parser should take care of those transparently, but pyftsubset uses its own parser rather than argparse module or similar. We should fix that.

**Comment by anthrotype** [comment]
@kaushalmodi can you tell me which operating system and which shell environment you're using to run pyftsubset? Maybe also the python version, and the fonttools version.
 
I've just tried your command (with and without quotes) in bash on Linux, and it works in both cases, producing the same WOFF2 font (and it's not empty, but contains the correct glyphs requested).

I believe it's the shell itself is the one that takes care of quotes. Python doesn't even see them.

```bash
$ python -c "import sys; print(sys.argv[1:])" --unicodes=U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF
['--unicodes=U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF']
$ python -c "import sys; print(sys.argv[1:])" --unicodes="U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF"
['--unicodes=U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF']
```

**Comment by anthrotype** [comment]
I checked myself on all three platforms and it's not the presence of the quotes in command line option.
Those are automatically stripped from the string that gets stored in sys.argv list (unless one escapes them with backslash, but that's not the issue here).

We need more information to debug this.

**Comment by anthrotype** [comment]
like @jenskutilek said, the woff2 merriweather fonts that you are using on https://woff2--scripter-co.netlify.com/ are defintely broken, as they are basically empty, only contain .notdef glyph. Maybe the reason it works in Chrome and not in Safari is that the former will attempt to sanitise the fonts and if the WOFF2 are broken it tries the WOFF ones (which are not empty in your case).

Now the mystery to solve is, how did you exactly produce those broken WOFF2 fonts.
Can you upload the original (non-compressed) Merriweather ttf files that you used with pyftsubset and the exact command line you used (plus information as to your python and OS environment).

Thanks.

**Comment by anthrotype** [comment]
I just downloaded the official Merriweather from https://fonts.google.com/specimen/Merriweather, then run the pyftsubset commands similar to the ones you wrote in your original post.
You can see the result in this zip file. Both the woff and woff2 subsets are identical to each other and working fine as intended:

[fonttools-issue-1294.zip](https://github.com/fonttools/fonttools/files/2188105/fonttools-issue-1294.zip)

**Comment by anthrotype** [comment]
@jenskutilek where did you get the impression that removing the quotes would make any difference? Did you encounter an issue like that already that we can reproduce?

**Comment by kaushalmodi** [comment]
Wow, thank you guys for the prompt responses!  Looks like I could have created confusion by trying to "simplify" the recipe.. here's my actual wrapper script:

```
git clone https://gitlab.com/kaushalmodi/hugo-theme-refined 
cd hugo-theme-refined/static-src/fonts
./create_font_subsets.sh
```

Above will create the woff and woff2 fonts in `hugo-theme-refined/static/fonts/<font name>/<version>/<subset>/`. 

The original non-subsetted ttf are in `hugo-theme-refined/static-src/fonts/<font name>/<version>/ttf/`.

I hope this helps reproduce the issue.

- The pyftsubset commands are almost identical between the woff and woff2 generation, so I am surprised why it would work for one and not another. 
- If you look at the git commit history of that repo, I have been trying different things to make woff2 work (you can look at the recent branches).. earlier I did ttf -> woff2 conversion.. that didn't work either.

I am on RHEL 6.6, using tcsh shell, updated to the latest Python 3.7 and rebuilt the fonttools using pip3 about a week after 3.7 release (don't remember the version, not at my computer right now).

**Comment by anthrotype** [comment]
thanks for the info @kaushalmodi 
since you're here, could you try running this in your tsch shell for me please:
```sh
python -c "import sys; print(sys.argv[1:])" --unicodes="U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF"
```

verify that it prints this and the quotes are stripped:
```
['--unicodes=U+0020-007E,U+00A7-00BE,U+2000-205E,U+00C0-00FF']
```

this is just to rule out completely the earlier suggestion that this may have to do with the presence of quotes in the --unicodes= option string, thanks.

**Comment by anthrotype** [comment]
@kaushalmodi also, please have a look at the `subset.sh` shell script that is inside the zip I uploaded before. Maybe try change the shebang that currently points to `#!/bin/bash` to use your tsch shell, and see if it works and outputs correct woff and woff2 fonts. Perhaps first remove that `subset` subdirectory which contains already made webfonts.

**Comment by kaushalmodi** [comment]
> could you try running this in your tsch shell for me please: 

Actually I am running the bash script, so you can consider that I am running in bash shell. Also the quoting should not matter because as you see, I am passing the unicode values internally in the bash script via variables (so the double quotes won't be getting passed as value).

Also the same value of `$unicodes` is used for both woff and woff2 generation. 

I'll be at my computer in 3 hours. I'll still try out your suggested commands then and report back. 

> Maybe try change the shebang that currently points to #!/bin/bash to use your tsch shell,

That wouldn't work as the script is in bash syntax (quite different than the tcsh syntax). Essentially, it can be ignored that I am using tcsh.. Assume that my shell is bash.

I'll try out your script once at computer. 

Were you able to reproduce the issue by cloning my repo and running that script?

Thanks.

**Comment by anthrotype** [comment]
i'm on it

**Comment by anthrotype** [comment]
oh I see where the misunderstanding is now!

For the woff2 webfonts, you're calling pyftsubset without giving any glyph subset specifiction, thus the subsetter is keeping no glyphs leaving you with only the .notdef!

https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/master/static-src/fonts/create_font_subset.sh#L60

You have two options:

1) re-run the pyftsubset script using the uncompressed TTF as original, with the same options as for the WOFF 1.0, but with different flavor (woff2).

2) run the subsetter on the already subsetted WOFF and use `"*"` as positional argument following the first (the input file). This will tell pyftsubset to keep all the glyphs. The help explain this here:

https://github.com/fonttools/fonttools/blob/a526b7170ca5bb8428edf13b8ca83e3b9596002d/Lib/fontTools/subset/__init__.py#L44-L46

3) use ttx to decompress the subsetted woff fonts (e.g. `ttx -o font.ttx font.woff`) and then again use ttx to recompile the TTX file as a compressed woff2 font (e.g. `ttx -o font.woff2 --flavor woff2 font.ttx`)

I would recommend option 1 or 3, for correctness, even though you it may be seen as wasteful to re-subset the font, or to go through an intermediate XML representation with ttx. The subsetter has a lot of preset defaults that are geared towards webfont use. To make it "only" compress a font, without also doing other optimizations which may not be desired, one may have to pass other counter-options that basically tell it what _not_ to do.  

In the future, I would like to add a command-line interface for the `fontTools.woff2` module (and a corresponding one for woff) that one could use to just convert to/from WOFF2 and TTF/OTF, e.g. `fonttools woff2 <INPUT> -o <OUTPUT>` and same for woff, from the console. This way the subsetting phase could be done separately (and only once) from the web-font compressing stage.

We do already have something like that, but it's currently only in the ./Snippets directory, as a way of example, but not installed as part of the library.

**Comment by anthrotype** [comment]
i'll keep this open in case you have questions.

**Comment by kaushalmodi** [comment]
I was actually using option 1 before yesterday: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/6a9a5e526558910a847d9fab6fc0853252e52ab2/static-src/fonts/create_font_subset.sh

In that older version, notice that I was using the same ttf as source font, and still that issue showed up on Safari. 

I'll try option 3 as soon as I get to a computer!

Side question: It didn't occur to me until now to look for it . Is there a debug switch that prints a summary of number of glyphs on the output font file?

Also is there a user friendly (for someone knowing nothing of woff\2 internals) command line method to print all the glyphs from an input font?

**Comment by kaushalmodi** [comment]
> For the woff2 webfonts, you're calling pyftsubset without giving any glyph subset specification (nor any --unicodes

That's embarrassing.. a terrible oversight on my part. Thanks for pointing that out.. it all makes sense now.

**Comment by anthrotype** [comment]
you can use pyftsubset with --verbose option, it will tell you each steps it's currently doing including the final glyph set that it's actually keeping after evaluating all the options

**Comment by kaushalmodi** [comment]
I appreciate your help. Such a silly mistake.. wasted so many hours, mine and yours. Sorry about that.

**Comment by anthrotype** [comment]
> Also is there a user friendly (for someone knowing nothing of woff\2 internals) command line method to print all the glyphs from an input font?

you can use ttx to print the `GlyphOrder` table (which is not really an OpenType 'table', but it's where fontTools internally stores the information as to what is the glyph name and the order of the glyphs in a font).

```sh
$ ttx -o - -t GlyphOrder MyAwesomeFont-Regular.ttf
```

`-o -` is to print to standard output instead of to a file.

**Comment by anthrotype** [comment]
No problem! Glad we could find the solution :+1:

**Comment by kaushalmodi** [comment]
@anthrotype Thanks. `--verbose` ended up too verbose for my use case of finding out the number of glyphs. But `ttx -q -o - -t <font file> | grep -c '<GlyphID id'` works.

Was wondering.. would it be useful in general for `pyftsubset` to add a minimal 1-liner confirmation message at the end, like *"Exported N glyphs to FONTFILENAME"*?

**Comment by jenskutilek** [comment]
> @jenskutilek where did you get the impression that removing the quotes would make any difference? Did you encounter an issue like that already that we can reproduce?

No, sorry, I just saw that the fonts are empty and noticed the difference in the command line from the help output. I didn't actually test if the quotes made a difference. Sorry for the sloppy testing ;)
