### ISSUE TITLE
pyftsubset should write file extension matching the output flavor (woff, woff2, etc.)

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1298]
currently it always defaults to the input font's extension, and that may be confusing.

**Comment by justinpenner** [comment]
@anthrotype's fix for this has regressed at some point. `flavor=woff2` is once again outputting a woff2 file with a .ttf extension.

To reproduce in fontTools 4.43.1:
`pyftsubset font.ttf --flavor=woff2 --unicodes="U+0000-00FF"`

**Comment by behdad** [comment]
Quite possibly my fault. Lemme check.

**Comment by behdad** [comment]
Fixed again. Sorry about that.

**Comment by justinpenner** [comment]
I think you just broke the world record for the fastest fixed issue in an open source project. Thanks!
