### ISSUE TITLE
[ttx] about <created>/<modified> value format in `head` table

### ISSUE THREAD

**Issue by LIXiangChen** [fonttools/fonttools#1299]
I found that the "day of month" have no leading zero, though, there will be an extra space in front of it, like this:

![img](https://user-images.githubusercontent.com/8857634/43047906-79dd75b8-8e11-11e8-9616-d2eb44080cf4.png)

I think this should be fixed, either remove extra space or use a format with leading zero.

**Comment by moyogo** [comment]
This is how Python 3 formats it.

**Comment by moyogo** [comment]
See #455 and #462.

**Comment by anthrotype** [comment]
Like Denis said. That's how the POSIX C asctime function works. The returned string is always 25 characters long, and the day of the month is padded with space. It's not worth changing this.
