### ISSUE TITLE
Add font slicer

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1312]
I think @twardoch requested this before.  Google Fonts can probably use it too.  We want functionality that analyzes GSUB/GPOS, and return sets of characters that all need to be in the same slice of the font.  This is useful for slicing fonts for CSS serving optimization tricks.

**Comment by behdad** [comment]
cc @garretrieger

**Comment by behdad** [comment]
FWIW here's a unionfind implementation I made quickly back in 2015 when @twardoch requested this feature from me privately: https://gist.github.com/behdad/0d36c27b6a664726a5b9c6050fc27d42

**Comment by behdad** [comment]
I want to note that if we have a mark glyph, then it will bundle up all bases that define an attachment for that mark.  Just making sure we all on the same page about that.

**Comment by garretrieger** [comment]
Related to this we probably also want to consider codepoints that can participate in unicode compositions and decompositions as noted in this harfbuzz issue: https://github.com/harfbuzz/harfbuzz/issues/2283
