### ISSUE TITLE
Unknown Color Emoji - CBDT/CBLC  ( imageFormat="20" )

### ISSUE THREAD

**Issue by vXBaKeRXv** [fonttools/fonttools#1321]
The Fitbit Color Emoji seems to be using a unknown graphic type.  No PNG chunks and imageFormat 20 don't exist.  Anyone know how the images are stored ?

http://www.mediafire.com/file/jf5e185eqelcea6/Fitbit+Noto+Emoji.zip

# Dict for CBDT extended formats.
cbdt_bitmap_classes = {
	17: cbdt_bitmap_format_17,
	18: cbdt_bitmap_format_18,
	19: cbdt_bitmap_format_19,
}

**Comment by behdad** [comment]
This is bizarre indeed.

**Comment by behdad** [comment]
Figured out what was going on?
