### ISSUE TITLE
[dfont] Fix mystery +2

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1324]
https://github.com/fonttools/fonttools/blob/90176ef842581fea880272bee84433c7d31be88c/Lib/fontTools/misc/macRes.py#L85

See: https://github.com/harfbuzz/harfbuzz/commit/3789c557ca06aef430726f4942cafecac6fe4eef

**Comment by anthrotype** [comment]
I don't remember... I believe I just ported @brawer's code to python: 
https://github.com/jatovm/classpath/blob/master/gnu/java/awt/font/opentype/MacResourceFork.java

I was also reading this
https://developer.apple.com/library/archive/documentation/mac/pdf/MoreMacintoshToolbox.pdf#page=151

**Comment by behdad** [comment]
> What else we need to do here?

Nope.  We read the count, then use the offset+2.  The count should be read at offset.
```

		absTypeListOffset = self.absTypeListOffset
		numTypesData = self._read(2, absTypeListOffset)
		self.numTypes, = struct.unpack('>H', numTypesData)
		absTypeListOffset2 = absTypeListOffset + 2
```

**Comment by behdad** [comment]
Oh.  Yes you're right.  I see.  Ok, this is correct.

**Comment by anthrotype** [comment]
told ya
