### ISSUE TITLE
Pyftsubset preserving all cmap tables from source OTF

### ISSUE THREAD

**Issue by PaulHanslow** [fonttools/fonttools#1337]
Pyftsubset is subsetting but preserving all the cmap subtables in the original source OTF files, including the format 12 subtable even thought it's longer needed because the subset OTF contains no non-Plane-0 characters. Can code be added to pyftsubset to strip out cmap tables which are unrequired in the output OTF file?

Currently Font Validator is producing the following error message in the OS/2 table:
The surrogates bit (bit #57) is clear in the ulUnicodeRange, but the cmap contains a surrogates encoding.

**Comment by anthrotype** [comment]
yea, that would be a nice thing to have.

**Comment by behdad** [comment]
This was fixed in 06913cc715.
