### ISSUE TITLE
Change ufoLib creator value?

### ISSUE THREAD

**Issue by benkiel** [fonttools/fonttools#1339]
https://github.com/fonttools/fonttools/blob/13cf8ef1ab2184f6d8dd4e475f1032b413c4ae26/Lib/fontTools/ufoLib/__init__.py#L789

Should this change to `org.fonttools.ufolib`?

**Comment by anthrotype** [comment]
hm, yeah I thought about that. Problem is, we don't own `org.fonttools` unfortunately.
For similar reverse domain UFO keys in the past we used "com.github.fonttools.*`, for example in ufo2ft for the data files in TTX format

**Comment by benkiel** [comment]
Ah, yeah, that then. Would make sense to be sure that one can know where the UFOLib is coming from. I'll work up a PR.

**Comment by benkiel** [comment]
See #1340
