### ISSUE TITLE
The glyph names in <sub> in <rule> in designspace need to be “production names”

### ISSUE THREAD

**Issue by MrBrezina** [fonttools/fonttools#1349]
Perhaps this should be clarified in the spec? Because, one might assume that if designspace refers to UFOs, these names should be the designer-friendly names used when displaying UFOs in editors. (Sorry, do not know what is the nomenclature here.) Currently, it seems these need to be the production names (in cases where they are different).

**Comment by justvanrossum** [comment]
@letterror?

**Comment by LettError** [comment]
There are different consumers of designspaces. Which code needs production names?

**Comment by justvanrossum** [comment]
I assume the varlib compiler.

**Comment by anthrotype** [comment]
fontmake just calls calls varLib.build with a designspace file as input and a "finder" callable that translates the UFO sources' paths into the respective master TTF paths. From there, it's fonttools doing its thing, there's nothing fontmake can do. The glyph renaming has already happened (in ufo2ft).
I'll have to think about at which level is best to tackle this, but I do agree it'd be better if the designspace file contained the design-friendly names that are in the UFOs.

**Comment by readroberts** [comment]
Seconded.

**Comment by anthrotype** [comment]
I know how to fix this in fontmake. When producing a variable font from a designspace, it should tell ufo2ft to _not_ do the renaming when compiling the master TTFs, and then it should call the ufo2ft PostProcessor on the variable font after it is generated by `varLib.build`.

**Comment by anthrotype** [comment]
If I do fix this properly (by doing the postscriptNames glyph renaming _after_ the variable font is built, instead of on the interpolatable master TTFs), then any existing designspace documents that worked around this by using final production names in their `<rules>` will break.
Is this acceptable?

**Comment by justvanrossum** [comment]
> Is this acceptable?

I would think/hope that people will be happy to no longer need to use production names in their rules...

**Comment by MrBrezina** [comment]
> > Is this acceptable?

> I would think/hope that people will be happy to no longer need to use production names in their rules...

Very happy

**Comment by anthrotype** [comment]
fontmake v1.10 will do the right thing now.
https://github.com/googlefonts/fontmake/releases/tag/v1.10.0

if you used final production names in your DesignSpaces `<rules>`, you should change them now to use human-readable names. The renaming now happens after the varfont is built (as of ufo2ft 2.9.0).
