### ISSUE TITLE
[subset] subr# assumed to prefix callsubr/callgsubr

### ISSUE THREAD

**Issue by blueshade7** [fonttools/fonttools#1350]
Maybe this is just a limitation, but discovered this CFF subsetter shortcoming by thought-experiment & verified using mod-fonts.

Subsetter appears to assume a callsubr/callgsubr operator must be prefixed by a (biased) subroutine number.
Type 2 CharString Format does not mandate this. If a subr number is left on the stack on call to another subroutine, or on return from a subroutine, subsetter fails.

Attached two modified copies of Source Sans Pro containing such subroutine calls, tested with/without desubroutinize.
A subr number passed on call appears to work with no-desubroutinize, but other three combinations fail.

```
% pyftsubset subrno_passed_on_call.otf --text=A --output-file=output.otf --desubroutinize
Traceback (most recent call last):
```
*SNIP*
```
  File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2419, in execute
    assert idx >= 2
AssertionError

% pyftsubset subrno_passed_on_call.otf --text=A --output-file=output.otf --no-desubroutinize

% pyftsubset subrno_passed_on_return.otf --text=A --output-file=output.otf --desubroutinize
Traceback (most recent call last):
```
*SNIP*
```
  File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2421, in execute
    assert type(desubroutinized[idx - 2]) == int
AssertionError

% pyftsubset subrno_passed_on_return.otf --text=A --output-file=output.otf --no-desubroutinize
Traceback (most recent call last):
```
*SNIP*
```
  File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2209, in subset_subroutines
    assert isinstance(p[i-1], int)
AssertionError
```

**Comment by behdad** [comment]
It's a limitation, correct.

**Comment by blueshade7** [comment]
[mod fonts.zip](https://github.com/fonttools/fonttools/files/2517126/mod.fonts.zip)
