### ISSUE TITLE
[varlib.build] Support different sets of master designs for different glyphs

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#1355]
I am starting to look at how do this. The motivation is that Adobe is planning to deliver a CJK variable font late next year, which will have 64K glyphs. This was developed with our internal tool that supports different sets of master designs for different glyphs, but only a a few hundred of glyph use this feature. I can build this VF now, but only by snapshotting the the source data to make an intermediate master at each transition  between one set of masters and another, in any glyph. This means that instead of having 2 masters for nearly 64K glyphs and 4 to 8 master designs for a small number of other glyphs, the font has 36 masters for 64K glyphs, which is a lot of bloat, and probably larger than the full set of named instances as regular fonts.

There are many issues here, but an  initial API  issue is how decide which glyphs use which masters. I had hoped to be able start with fully populated master designs, and try to figure out for each glyph independently what masters actually affected it, given the data from each of the masters. I would be delighted to hear otherwise, but I have the moment convinced myself that this is not practical for a design with multiple intermediate fonts. My next thought is to specify this externally. I note the designspace file element 'glyph' with the attribute 'mute', which would do this nicely. This is now supported only in the context of  MutatorMath, but I suggest that it be adopted for use in varlib.  Thoughts?

**Comment by behdad** [comment]
So, what's wrong with this model: masters can have different glyphs.  The base master must have all glyphs.  varLib then checks for each glyph, which masters have it.

Only maters that have GPOS will particilate in GPOS modeling.

**Comment by behdad** [comment]
While this works on the varLib level, we need to figure out how to get fro Glyphs/UFO to such "sparse" masters which lack GPOS, OS/2, some glyphs, etc.

**Comment by behdad** [comment]
Let's implement this in varLub' glyf and your CFF2 table and refine from there.

**Comment by miguelsousa** [comment]
> Prepolator is the only workflow

I'm assuming you meant Superpolator

**Comment by justvanrossum** [comment]
> So, what's wrong with this model: masters can have different glyphs. The base master must have all glyphs. varLib then checks for each glyph, which masters have it.
>
> Only maters that have GPOS will particilate in GPOS modeling. Same for other tables (OS/2, ...)

Yes, I think that's what needs to happen.

**Comment by anthrotype** [comment]
A few months ago, we added a new `layerName` attribute to the designspace source element
https://github.com/fonttools/fonttools/pull/1253

One of the primary use cases was indeed to support storing additional sets of masters that only apply to particular glyphs (aka "brace trick" in Glyphs.app jargon).

This is not implemented yet in varLib (https://github.com/fonttools/fonttools/issues/1308).

> we need to figure out how to get fro Glyphs/UFO to such "sparse" masters which lack GPOS, OS/2, some glyphs, etc.

The compiler (e.g. fontmake) would need to build this "sparse" masters in the form of incomplete TTF files that only contain the data that varies from the base master, e.g. `glyf` and `hmtx` (and probably also maxp, post, etc. the minimum to be able to read them as TTFont); then varLib would check for each glyph for the base master, which other masters contain it, and apply the deltas accordingly.

**Comment by justvanrossum** [comment]
> A few months ago, we added a new layerName attribute to the designspace source element
#1253
>
> One of the primary use cases was indeed to support storing additional sets of masters that only apply to particular glyphs

But the `layerName` attribute is perpendicular to this issue: a "normal" UFO master should be able to be sparse just the same.

**Comment by behdad** [comment]
> But the `layerName` attribute is perpendicular to this issue: a "normal" UFO master should be able to be sparse just the same.

Agree.

**Comment by behdad** [comment]
> > 
> 
> The compiler (e.g. fontmake) would need to build this "sparse" masters in the form of incomplete TTF files that only contain the data that varies from the base master, e.g. `glyf` and `hmtx` (and probably also maxp, post, etc. the minimum to be able to read them as TTFont); then varLib would check for each glyph for the base master, which other masters contain it, and apply the deltas accordingly.

Right.  I can look into the varLib side.  You figure out how the compiler determines this.

**Comment by readroberts** [comment]
Supplying sparse masters needs to be supported, and in many cases will be sufficient, to specify which regions should be used for a given delta tuple. However, I think that there are two cases for which the masters cannot be sparse, and that therefore some meta data is need to indicated which regions can be skipped for some glyphs. The two cases are kern pairs and GPOS contextual statements. Both may involve glyphs that need different sets of regions, and the values in the GPOS tables may be different for all the regions involved, even though some glyphs may use a subset of the regions for their outline data. The source fonts for all these regions will all need to have teh glyps involved. Does anyone see a way around this?

**Comment by davelab6** [comment]
@anthrotype @readroberts I am curious if you have any updates on this, and what the next steps might be? :)

**Comment by readroberts** [comment]
@davelab6  Sparse masters are now well supported on the master branch for variable fonts with TrueType glyph data. I have a branch that supports variable fonts with CFF2 glyph data, which is just awaiting review:
https://github.com/fonttools/fonttools/pull/1475

**Comment by miguelsousa** [comment]
Fixed via #1591
