### ISSUE TITLE
What's the reason for the default choice of cmapPreferences on getBestCmap method?

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fonttools#1367]
https://github.com/fonttools/fonttools/blob/349cd94d171cf4e1e7541884df0d12bb6d4e841a/Lib/fontTools/ttLib/tables/_c_m_a_p.py#L41-L54

What's the reasoning behind this specific ordering, by default? Could it please be explicitly mentioned in the docstring?

**Comment by anthrotype** [comment]
read here for the various platform IDs and platform-encoding IDs (used by both cmap and name table):
https://docs.microsoft.com/en-us/typography/opentype/spec/name#platform-encoding-and-language-ids

basically the idea is windows platform (3) is preferred over "unicode" platform (0) as the former is more common (although they are equivalent); full repertoire is preferred over BMP plane only, for obvious reasons.

**Comment by felipesanches** [comment]
please consider improving the docstring ;-)

**Comment by justvanrossum** [comment]
please consider contributing a PR ;-)

**Comment by felipesanches** [comment]
sure. I am just not really sure yet how to better express these ideas in the docstring.

**Comment by behdad** [comment]
The code this was based on has more context.  I thought I copied that in fonttools.  But the code looks rewritten.
https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-cmap-table.hh#L984

**Comment by behdad** [comment]
But, the point of docstring is not to explain the implementation.  It's to describe the functionality and interface.

**Comment by felipesanches** [comment]
well... could be a comment then.

The sequence of numbers requires one to know by heart the values of each platform ID and encoding ID. And the specific ordering seems arbitrary unless there's some reasoning stated to clarify why it may be a reasonable default.

**Comment by behdad** [comment]
> The sequence of numbers requires one to know by heart the values of each platform ID and encoding ID. And the specific ordering seems arbitrary unless there's some reasoning stated to clarify why it may be a reasonable default.

Why would one need to know what they mean anyway?  And no, it doesn't require one to know them by heart.  It requires one to open the spec page, which is what all of us developers do every day.  If someone doesn't know the cmap or name table architectures, they have no reason to be care about the sequence of numbers here.

**Comment by felipesanches** [comment]
"explicit is better than implicit", "readability counts"...

**Comment by behdad** [comment]
You could have sent a PR in the time you spent replying to this thread. :)

**Comment by khaledhosny** [comment]
Closing, nothing actionable here. If someone wants to improve the docs, a PR is welcomed.

**Comment by davelab6** [comment]
> Why would one need to know what they mean anyway?

To understand the code. We should dislike magic numbers, and it is elitist to expect people to know name-id values by heart.

The actionable step is for fontttools experienced contributors who do understand the code and these magic values to explain them; it isn't reasonable to expect inexperienced contributors to understand the magic.

**Comment by davelab6** [comment]
Thanks behdad!

**Comment by felipesanches** [comment]
thanks! :-)
