### ISSUE TITLE
[varLib] Change varStore storage format?

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1369]
Currently we store delta rows as lists. Can be tuples. Of course in the builder API we accept both. But what gets stored will be different, and ttx output will be different (showing "(1, 2, ...)" instead of "[1, 2, ...]"). @anthrotype do you think it's worth it?

**Comment by anthrotype** [comment]
@behdad you would prefer to store them internally as tuples so that they are immutable and you don't need to worry when sharing objects, right?

we could change VarDataValue.xmlWrite method to convert it to a list so its repr stays the same in the xml output

**Comment by behdad** [comment]
> @behdad you would prefer to store them internally as tuples so that they are immutable and you don't need to worry when sharing objects, right?

That would be a nice side effect, but wasn't my intent.  Just disabled optimization in existing code and things showed up as tuples instead of list.  We use tuples in some stages to be hashable so we can detect duplicates...  Would be nice to ensure one or the other.

> we could change VarDataValue.xmlWrite method to convert it to a list so its repr stays the same in the xml output

Right...
