### ISSUE TITLE
[varLib] Shifting composite glyphs in macOS

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1381]
https://github.com/googlei18n/fontmake/issues/481

I had noticed this macOS rendering behaviour a long time ago, but the fix occurred to me only today. varLib could work around it by adding dummy entries to glyphs without necessary deltas to make sure they get an entry in the gvar table.

You can see it very clearly in [Normschrift](https://www.axis-praxis.org/specimens/normschrift) e.g. in ö (composites at default positions, no gvar entry), but not in Ö (dieresis is y-shifted so there is a gvar entry).

**Comment by behdad** [comment]
Right.  I saw the same when I read your comment in other issue.  It's slightly trickier than I like it to be, as the empty entries are optimized out during the compile process, so varLib needs a way to communicate it to the compiler that we want to retain empty entries for those glyphs..

**Comment by behdad** [comment]
Humm, or maybe not.

**Comment by Lorp** [comment]
This bug in macOS 12.4 seems to apply to fonts that have the workaround:

[Variable fonts rendering bug: composite glyphs disappear when all deltas are zero](https://feedbackassistant.apple.com/feedback/11009662)

**Comment by anthrotype** [comment]
I get "Feedback not found". @Lorp can you copy/paste the content of the bug report here?

 > apply to fonts that have the workaround:

so IIUC, removing the workaround fixes the bug on macOS 12.4?
