### ISSUE TITLE
Better installation instructions

### ISSUE THREAD

**Issue by mekkablue** [fonttools/fonttools#1391]
The current installation instructions are not sufficient for making ttx work. To illustrate the issue:

```bash
$ pip install fonttools
Requirement already satisfied: fonttools in /Library/Python/2.7/site-packages (3.32.0)
$ ttx
-bash: ttx: command not found
```

Or:

```bash
$ pip install -e .
Obtaining file://~/Repositories/GitHub/fonttools
    Complete output from command python setup.py egg_info:
    error in fonttools setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in ~/Repositories/GitHub/fonttools/
```

**Comment by anthrotype** [comment]
Try to upgrade pip then retry to install fonttools. Pass —upgrade option

**Comment by anthrotype** [comment]
Before you upgrade pip, what version of pip do you have that raises that error?

**Comment by anthrotype** [comment]
Also the version of setuptools may be relevant. Try do pip list to see what version is installed in your env.

**Comment by mekkablue** [comment]
Reopening this issue, because (re)installation of fonttools remains a painful experience on macOS. Still no help in the readme, no useful help in a Google search. So, unless there is a requirement to keep fonttools inaccessible, please reconsider improving the installation instructions, or find a better way of installing fonttools.

Running `sudo pip install fonttools` gives me either:

```
Requirement already satisfied: fonttools in /Library/Python/2.7/site-packages (3.44.0)
```

or:

```
ERROR: Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'
```

I have no idea what that means, and there is no further help provided on what can be done to get fonttools installed. Googling the error message brings up [this article](https://marcelog.github.io/articles/mac_osx_python_pip_install_operation_not_permitted.html) which recommends the `--user` flag, which I do, and which results in another:

```
Requirement already satisfied: fonttools in /Library/Python/2.7/site-packages (3.44.0)
```

And alas, trying `ttx` returns the familiar:

```
-bash: ttx: command not found
```

And when I try `pip install -e .` in the fonttools directory, I finally get a different error message:

```
ERROR: Package 'fonttools' requires a different Python: 2.7.10 not in '>=3.6'
```

Which leads me to think it may be a Python version issue. However, I have not found the documentation for installing and running fonttools in a different Python version than the system default, which is a frequent case on macOS.

IOW: installing and running fonttools/ttx on macOS Mojave in late 2019 is not possible with the current instructions.

**Comment by anthrotype** [comment]
> Running sudo pip install fonttools

sudo is the problem, you should not be doing that in the first place. The OS python should not be modified by the user. If you want to use the system's python distribution and extend it with third party packages from PyPI, you have to use the `--user` flag, which will install it in the /Users/Library/Python... folders.

**Comment by anthrotype** [comment]
also, python 2.7 is no longer supported. I strongly recommend you install python3 using homebrew if you are on MacOS, or simply download one of the official installers from Python.org website. These will not require you to use `sudo`. You can simply `pip install --upgrade fonttools` and they will do the right thing. The scripts will be in /usr/local/bin which is already in the `$PATH` so everything will work as expected.

**Comment by anthrotype** [comment]
for homebrew the command is `brew install python` which will install Python 3.

**Comment by mekkablue** [comment]
I have Python 3 installed. The `--upgrade` flag is still working into Python 2.7:

```
mekkabook-air:fonttools mekka$ pip install --upgrade fonttools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: fonttools in /Library/Python/2.7/site-packages (3.44.0)
```

What worked eventually was cd’ing into the fonttools folder and running:

```
python3 setup.py install
```

Also undocumented, but now `ttx` gives me the command help.

**Comment by mekkablue** [comment]
> sudo is the problem

Also without `sudo`, with and without the `--user` flag, the pip installation did not work. Same results as above. I tried uninstalling & reinstalling fonttools, uninstalling & reinstalling pip, all to no avail.

**Comment by anthrotype** [comment]
no, please don't use `setup.py install` which triggers the use of deprecated setuptools easy_install functionality. Always use `pip` to install, even from a local source checkout: `pip install -e .` with `.` meaning the current directory where the setup.py script is located.

You probably have pip installed for both the python2.7 and the python3 distributions on your local macine.

Check if you have `pip3` command which is linked to it. Try to run `pip3 --version` and verify that it is linked with the correct python3's site-packages directories.

Or alternatively call pip with the fully qualified command name as in `python3 -m pip` or `python3.7 -m pip` so that you are certain that you are installing to the right pythons.

**Comment by mekkablue** [comment]
> Check if you have pip3 command which is linked to your python3. Try to run pip3 --version and verify that it is linked with the correct python3's site-packages directories.

```
mekkabook-air:fonttools mekka$ pip3
-bash: pip3: command not found
```

🤷‍♂️

> Or alternatively call pip with the fully qualified command name as in python3 -m pip or python3.7 -m pip so that you are certain that you are installing to the right pythons.

This works:

```
python3 -m pip uninstall fonttools
python3 -m pip install fonttools
```

After the first command `ttx` stopped working as expected (=making sure no other fonttools installation was interfering), and after the second line, I got `ttx` to output the command help again.

Can we add this to the installation instructions in the readme?

**Comment by m4rc1e** [comment]
For severals year I had terrible python setups on OS X. It would usually end up with dependency hell as I installed everything to the system Python and neglected virtualenvs.

For the installation notes in the readme, it may be a really nice idea to link to an article such as Digital Ocean's on [setting up Python for OS X](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-macos). It covers installing xcode, brew, creating a virtualenv and pip.

I feel this is needed because many folks use Python in font editors so their understanding of it on a system may be more limited.

**Comment by anthrotype** [comment]
> Can we add this to the installation instructions in the readme?

yes and no. I mean, all this is generic python setup info that is available online, e.g. the official Python documentation or https://packaging.python.org/. Fonttools is not different from any other python package. I don't think we need to tell people how to set up their python environment.
For example, suggesting people to call python as `python3` will work for your setup on MacOS or most Linuxes, but on Windows all pythons are simply caled `python.exe` and you call different versions using the py.exe launcher with some option to select the major.minor version.
I know, at the beginning this all looks complicated. But you can ask here, or on the Gitter fonttools chat for support and somebody will always be available to answer.

Ok, if you insist and want to send a PR, we can review it.

**Comment by mekkablue** [comment]
It boils down to: the installation instructions provided will not work on macOS. Currently, the instructions is doing a good job on excluding Mac users. I assume this is not intended.

1. The FontTools readme contains extra hints for Windows users, but not for Mac users.

2. Most type designers working with a Mac will try to install it and give up after the first error message. If they dare to ask, and are lucky, they get your attention right away.

3. More advanced users (=occasional CLI users) will try around until something works, googling, trying things they find on stackoverflow, on the way messing up their environment variables and installations/dependencies.

**Comment by benkiel** [comment]
Likely better as another issue, but this speaks to needing some better docs for fontTools. Both an overview of what the package is for (see the many issues opened by folks thinking it does one thing where other packages are a better fit), install instructions, and an overview of the different modules/functions in fontTools. So much has been added in the last couple of years, little documented beyond release notes and GitHub issues.

Trust me, I know how hard it is to write good documentation, keep it up-to-date, and the like (see fontParts), but this could be a really good summer of code project or the like.

**Comment by twardoch** [comment]
```
brew install python; python3 -m pip install --user --upgrade fonttools
```

**Comment by twardoch** [comment]
I've made this

https://github.com/twardoch/fontsurgery-tools/

Time to update it. I've also made 

https://github.com/twardoch/fonttools-py27

I’ll kill the commandline tools there, so it’s 
lib-only. I plan to keep it with some occasional fixes for cases where Py3 is not usable. And I’ll switch my fontsurgery tools installer to do Py3-only first. 

Maybe I'll do a convenience metapackage on pypi that’ll just install assorted packages. In most cases, inexperienced users are better served with “a bundle”.

**Comment by anthrotype** [comment]
(you don't need --user with brew python)

**Comment by anthrotype** [comment]
> https://github.com/twardoch/fonttools-py27

you are welcome to "upstream" those backported changes if you like. We have `py27` branch, but nobody was interested in updating that.

**Comment by jenskutilek** [comment]
> brew install python; python3 -m pip install --user --upgrade fonttools

For that to work, users would need to install Homebrew first. Does it have any advantage for a normal user over using the official Python installer from python.org? For me, Homebrew is just another easy way to mess up your system ...

```bash
python3 -m pip install --user --upgrade brotli zopfli fonttools
```

for me ;)

**Comment by anthrotype** [comment]
python.org installer are ok too.

@jenskutilek to install all the extra requirements you can do `pip install fonttools[all]`

**Comment by anthrotype** [comment]
similarly, for the python.org distributions, you don't need `--user` flag because the site-packages folder under /Library/Frameworks/Python... is not write-protected like the one under /System hence it does't require sud (well, unless you're sharing your machine with other users)

**Comment by anthrotype** [comment]
Also note when installing with `--user` the executable scripts are not placed under /usr/local/bin, but under the user's bin directory (in my case /Users/clupo/Library/Python/3.7/bin). This is not already in the `$PATH`, so you will have to append to it in your shell config file (e.g. `.bashrc`).
So `--user` adds a further layer of complexity.
Whereas /usr/local/bin/ is already in the default executable `$PATH`.

**Comment by benkiel** [comment]
So, a better guide to this would be good. I'll make a PR tomorrow.

**Comment by twardoch** [comment]
Cosimo, you're right. I started doing --user because of the built-in Python 2.7. But since Mac does not include Py3, simplest is best, and no --user is simpler for Py3.

**Comment by mekkablue** [comment]
So, to sum things up, my current Mac installation instructions for Catalina, July 2020:

1. Install Homebrew: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`
2. Install Python3 through homebrew: `brew install python`
3. Install fonttools: `python3 -m pip install --upgrade brotli zopfli fonttools`

Please CMIIW

**Comment by BoldMonday** [comment]
Is Homebrew still necessary to install Python 3? I used it in the past but found it hard to upgrade to newer Python versions.

On my current Mojave machine I installed Python 3.8.2 with the official installer from Python.org. Seems to work fine.

**Comment by chrissimpkins** [comment]
Homebrew had significant issues with the 3.8.x rollout.  3.8 just landed as the default python3 on my Catalina system in the last ~ week.  While it is not required to have the latest/greatest python3 for a fonttools install, it is possible that many on macOS have been moving away from Homebrew as a py3 package manager for this reason.  When CI services can land a Py version earlier than a local desktop package manager it is generally a bad sign... :)

FWIW, builds / installs from the cPython source works fine on macOS too.  I am building the 3.9 branch on Catalina without issues using the README docs.

**Comment by khaledhosny** [comment]
Catalina also has /usr/bin/python3 stub that will prompt the user to install command line tools on first call, so that might be a more convenient way to install Python 3 as well.

**Comment by RoelN** [comment]
This might not be relevant if you don't use `asdf`, but this has bitten me in the arse often enough that I need to leave a comment for my future self:

If you're using the `asdf` version manager, be sure to run `asdf reshim python` after installing through pip, otherwise it will not find the `ttx` executable.

**Comment by behdad** [comment]
Anything actionable here?
