### ISSUE TITLE
CFF2 code cleanup

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#1392]
Random things looking around right now:

- What's CFF2Subr class for?  It doesn't make any sense to me.  Why is it called Subr, but has a draw() method?  What is different from T2CharString?  Apparently nothing, just the isCFF2.  I thought we agreed we don't want to carry that flag on the objects...  I like to see those removed from T2CharString.  I checked all the occurences, they don't seem essential.  I'm even fine removing check_program completely...

- The code that you (Read) moved from `subset.__init__` to `subset.cff`, some of it needs to go back to `subset.__init__`.  Pretty much everything that the is part of subsetter's internal working needs to go back.  The goal was to refactor the common functionality to a separate module and reuse from mutator, not just move code directly.  In particular, I think I want to see .desubroutinize() and .remove_hints() methods on both CFF and CFF2 tables.  Maybe also .remove_unused_subroutines()?  Ideally they should share most of the code.

- When do you think you will get to implement CFF2 subsetting?

**Comment by readroberts** [comment]
@behdad  The current CFF2Subr class should be renamed to CFF2Charstring - the name is an artifact of early work. It is needed to carry a different draw() method than T2Charstring. The isCFF2 field is indeed no longer needed in psCharStrings.py, and I will get rid of it.

For the subset work, I'm happy to add .desubroutinize(), remove_hints(), and remove_unused_subroutines methods on both CFF and CFF2 tables. Looks to me like this will mean promoting sections of the 'prune_post_subset method' to separate methods, and then calling these from from the three CFF/CFF2 methods. I'm not so clear on the refactoring - let's talk about the goal by email or phone.

 I think I can work on the CFF2 subsetting next week.

**Comment by behdad** [comment]
> @behdad The current CFF2Subr class should be renamed to CFF2Charstring - the name is an artifact of early work. It is needed to carry a different draw() method than T2Charstring. The isCFF2 field is indeed no longer needed in psCharStrings.py, and I will get rid of it.

The different `draw()` method only deals with width differently?  I think we can have one function only that sets width if private has width fields?  Either that or another way of sniffing whether we are running as CFF2 or not and oblige.

> For the subset work, I'm happy to add .desubroutinize(), remove_hints(), and remove_unused_subroutines methods on both CFF and CFF2 tables. Looks to me like this will mean promoting sections of the 'prune_post_subset method' to separate methods, and then calling these from from the three CFF/CFF2 methods.

Exactly.

> I'm not so clear on the refactoring - let's talk about the goal by email or phone.

Just the above breaking would be enough.  I might give it a go myself.  I'm just not sure how well-tested the uses of that code is, so I'm afraid I might break things if I don't spend enough time and care.

> I think I can work on the CFF2 subsetting next week.

That's great.

**Comment by readroberts** [comment]
Fixed in PR #1397
