### ISSUE TITLE
feature request: feaLib.builder appendOpenTypeFeatures

### ISSUE THREAD

**Issue by BlackFoundry** [fonttools/fonttools#1394]
Similar to 'addOpenTypeFeatures' but wouldn't overwrite existing features, just append additional GSUB / GPOS lookups to existing ones and update features accordingly.

https://github.com/fonttools/fonttools/blob/d53a26acaef4b3672af5b36df818fd22ebee4c69/Lib/fontTools/feaLib/builder.py#L20

**Comment by khaledhosny** [comment]
Duplicate of #599
