### ISSUE TITLE
ScriptCount, etc are confusing

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#141]
Hi all,

If I make a new `TTFont` from a binary font, and then try to access the `ScriptCount` attribute of the `ScriptList` subtable of the `GPOS` table, I do get the correct value: 

```
ttFont1 = TTFont("Arial.ttf")
print getattr(ttFont1['GPOS'].table.ScriptList, 'ScriptCount')

>>  5
```

However, if make a new empty font, import the data from XML, and then try to access that same attribute, I get an AttributeError instead:

```
ttFont2 = TTFont()
ttFont2.importXML("Arial.ttx")
print getattr(ttFont2['GPOS'].table.ScriptList, 'ScriptCount')
```

Here is the traceback:

```
Traceback (most recent call last):
  File "/Users/cosimolupo/Documents/BitBucket/miscellanea/ftTest2", line 14, in <module>
    print getattr(ttFont_2['GPOS'].table.ScriptList, 'ScriptCount')
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 531, in __getattr__
    raise AttributeError(attr)
AttributeError: ScriptCount
```

It seems to me the exception is raised because the BaseTable instance could not find a 'reader' attribute. 

I was assuming that the Python objects that are returned from either a binary conversion or an xml conversion are by all means identical to each other, in a way that one could convert _from_ either binary, xml or python _to_ any of the three, without losing data in the process.

Am I wrong is assuming this, or is this just a bug to be fixed?

Thank you for your great work.

All best,

Cosimo

**Comment by anthrotype** [comment]
Saving a font imported from XML seems to be working for me after 45fa26b.
Thanks Behdad for finally fixing this!
I guess we should add some tests to verify this properly.

Now I wonder if "ttx" could be considered as just another "flavor" of sfnt, like "woff", "woff2"...
So one could do, say, `TTFont("MyFont.ttx")`, call `save()` on it, or give a ttx file to the subsetter, etc.

**Comment by behdad** [comment]
> Saving a font imported from XML seems to be working for me after 45fa26b.

Ah, right.  I failed to find this issue. :)

> I guess we should add some tests to verify this properly.

We should. The mtiLib tests do, and I'm adding some more tests that will also do.

> Now I wonder if "ttx" could be considered as just another "flavor" of sfnt, like "woff", "woff2"...
> So one could do, say, TTFont("MyFont.ttx"), call save() on it, or give a ttx file to the subsetter, etc.

Agree.

**Comment by anthrotype** [comment]
Thanks Ben. I understand your concerns about the suitability of TTX files as long term source storag. However, I was merely pointing out an implementation detail: i.e., now that XML->Python->XML is possible, TTX files *could* (didn't say *should*) be considered "equivalent" to binary sfnt formats for fontTools.ttLib as far as input/output is concerned. I must admit I haven't explored all the implications of that yet.

Nevertheless, note that all the bugfixes and new features that have been added in the past couple of years are (or were meant to be) backward-compatible, in the sense that a TTX file produced with an older fonttools can still be compiled with current one (not the other way around, of course). Well, if that's not the case, I encourage you to submit a bug report ;)

Needless to say, if we ever agree together to modify the format in backward incompatible ways, we'll make sure to increase the major version, give users advance notice and provide ways to update their sources.

**Comment by benkiel** [comment]
@anthrotype Understood. I'm not opposed at all to making it a flavor, I just wanted to raise the historical understanding of a TTX file — there have been decisions make in the past (the Delft sprint comes to mind) where changes to the format have been made that were breaking with older versions of TTX (the DSIG table and something to do with how TTF hints were handled, if I'm remembering correctly)

**Comment by behdad** [comment]
> I just wanted to raise the historical understanding of a TTX file — there have been decisions make in the past (the Delft sprint comes to mind) where changes to the format have been made that were breaking with older versions of TTX (the DSIG table and something to do with how TTF hints were handled, if I'm remembering correctly)

I tried to go in the opposite direction.  A lot of changes I made early on where towards making XML more stable, archival, and hold only semantic meaning.  That's before @justvanrossum coerced us into reverting the Coverage Format change and in general giving up on that vision.

No hard feelings though.  Life is short.  There are way more important things to worry about...

**Comment by justvanrossum** [comment]
I'm all for more stability in the format, actually. But I don't think it's fair to say that has much to do with "hold[ing] only semantic meaning" or not.

**Comment by anthrotype** [comment]
OK now that the original XML-to-XML issue is finally solved, we can close this.
Thanks Behdad for fixing this, and everyone for the feedback.
