### ISSUE TITLE
much space

### ISSUE THREAD

**Issue by VivaRado** [fonttools/fonttools#1410]
https://github.com/fonttools/fonttools/blob/6e1e0b73f1d82a0a3d1e6307164dddcadcf20df6/Lib/fontTools/varLib/merger.py#L861

**Comment by anthrotype** [comment]
sorry but this is just noise, if you care about that you can send a PR. It takes you the same amont of time as opening the issue.

**Comment by VivaRado** [comment]
Done: https://github.com/VivaRado/fonttools

**Comment by anthrotype** [comment]
done what?

**Comment by VivaRado** [comment]
Forked and PR
