### ISSUE TITLE
designspaceLib: InstanceDescriptor.mutedGlyphNames intentionally a dud?

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#1417]
An `InstanceDescriptor`'s `mutedGlyphNames` list is created in `__init__` and mentioned in https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#attributes-1, but it is neither read from nor written to disk in `designspaceLib.__init__`. Is this intentional?

**Comment by anthrotype** [comment]
@LettError do you know what's that for?
