### ISSUE TITLE
rename deprecated methods in latest pyfilesystem2 API (fs >= 2.2.0)

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1424]
A few methods like getbytes, setbytes and similar have been renamed in fs module 2.2.0, they now issue a deprecation warning:

https://github.com/PyFilesystem/pyfilesystem2/releases/tag/2.1.2

we should rename them and bump required fs module in install_requires

**Comment by willmcgugan** [comment]
Apologies, I messed up the release version. Here's the link:

https://github.com/PyFilesystem/pyfilesystem2/releases/tag/v2.2.0

**Comment by plant99** [comment]
Hey, @willmcgugan .
I would like to work on this issue, if you are busy to change the function names, and up the version in 'install_requires'.

**Comment by willmcgugan** [comment]
@plant99 not my project, but I imagine they would be happy to accept a PR...

**Comment by anthrotype** [comment]
> I would like to work on this issue
@plant99 of course, you're welcome to send a PR! thanks
