### ISSUE TITLE
[voltLib] GroupDefinition.glyphSet() is broken

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#1442]
Take the following simple test vtp file:
```
DEF_GROUP "test"
 ENUM
   GLYPH "a"
 END_ENUM
END_GROUP
```

Processing it with this simple program:
```python
import sys
from fontTools.voltLib.ast import GroupDefinition
from fontTools.voltLib.parser import Parser

ast = Parser(sys.argv[1]).parse()
for statement in ast.statements:
    if isinstance(statement, GroupDefinition):
        print(statement.name)
        print(statement.glyphSet())
```

This raises:
```
test
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(statement.glyphSet())
  File "/lib/python3.7/site-packages/fontTools/voltLib/ast.py", line 75, in glyphSet
    self.glyphs_ = self.enum.glyphSet(groups)
AttributeError: 'tuple' object has no attribute 'glyphSet'
```

It looks like there is some confusion here; the code seems to expect the enum to be `Lexer.Enum` which is not used anywhere actually as `Parser.parse_coverage_()` returns a tuple. If this is indeed the intention, then `Parser.parse_coverage_()` should be fixed to return `Lexer.Enum` (I tried that quickly, but it seems to a chain reaction of other things that need to be fixed, so I’d like to have some confirmation before attempting that.

@moyogo

**Comment by moyogo** [comment]
Yes, `Parser.parse_coverage_()` isn’t done. Using tuples was a temporary hack. It should return a `ast.Enum` object, groups names should be `ast.GroupName` objects and glyph ranges should be unpacked.

**Comment by khaledhosny** [comment]
I fixed this (fixing the tests was way harder than fixing the code!). Now I’m questioning the use of sets for the glyphs, it seems to me that in many situations the order of the glyphs must be preserved and I’m not sure it is the job of the parser to remove duplicates or if it should at all.

**Comment by moyogo** [comment]
VOLT is fine with groups having glyphs more than once. You’re right, the parser shouldn’t remove duplicates.
