### ISSUE TITLE
Pair position lookup NULL value record compiled incorrectly

### ISSUE THREAD

**Issue by bobh0303** [fonttools/fonttools#1459]
I'm converting a VOLT project to FEA. The project contains a number of pair position lookups where only the _second_ glyph has a non-empty valuerecord. ttx decompiles such lookups to the following (glyph names changed to protect the innocent, etc.):
```
        <!-- SubTableCount=1 -->
        <PairPos index="0" Format="1">
          <Coverage Format="1">
            <Glyph value="glyph1"/>
          </Coverage>
          <ValueFormat1 value="0"/>
          <ValueFormat2 value="5"/>
          <!-- PairSetCount=1 -->
          <PairSet index="0">
            <!-- PairValueCount=1 -->
            <PairValueRecord index="0">
              <SecondGlyph value="glyph2"/>
              <Value2 XPlacement="-180" XAdvance="-90"/>
            </PairValueRecord>
          </PairSet>
        </PairPos>
```
Note that ValueFormat1 is 0, meaning that valuerecord for the first glyph is empty, and Valueformat2 is 5, and thus the only ValueRecord provided is for glyph2.

It would seem that the obvious way to express this in FEA is:

```
    pos glyph1 <NULL> glyph2 <-180 0 -90 0>;
```
however when I try that, the result is that the non-empty value record is applied to _glyph1_:

```
        <PairPos index="0" Format="1">
          <Coverage Format="1">
            <Glyph value="glyph1"/>
          </Coverage>
          <ValueFormat1 value="5"/>
          <ValueFormat2 value="0"/>
          <!-- PairSetCount=1 -->
          <PairSet index="0">
            <!-- PairValueCount=1 -->
            <PairValueRecord index="0">
              <SecondGlyph value="glyph2"/>
              <Value1 XPlacement="-180" XAdvance="-90"/>
            </PairValueRecord>
          </PairSet>
        </PairPos>
```
Note that ValueFormat1 is now 5 (rather than 0).

I'll guess that the `<NULL>` valuerecord is being ignored, resulting in an effective rule of
```
    pos glyph1 glyph2 <-180 0 -90 0>;
```
which is what Adobe calls a _Format B_ pair position syntax which, [they say](https://rawgit.com/adobe-type-tools/afdko/develop/docs/OpenTypeFeatureFileSpecification.html#6.b), is shorthand for
```
    pos glyph1 <-180 0 -90 0> glyph2 <NULL>;
```

Bob

PS: Yes, I know I could effect the correct rendering by putting in a non-empty value record for the first glyph, e.g.:
```
 pos glyph1 0 glyph2 <-180 0 -90 0>;
```
But this causes the lookup to include two actual valuerecords rather than one.

**Comment by anthrotype** [comment]
@bobh0303 Thanks for the report. I'll look into it

**Comment by anthrotype** [comment]
it appears the feaLib parser does not distinguish between the absence of a valuerecord element following the first glyph in the pair pos statement, and a value of <NULL>; in both cases it returns None

https://github.com/fonttools/fonttools/blob/af0e78e2eb7831dda1f7d513836e55cb78abcd21/Lib/fontTools/feaLib/parser.py#L1153-L1156

and a None value triggers the switch to the compact format B (e.g. `pos a v -30;`):

https://github.com/fonttools/fonttools/blob/af0e78e2eb7831dda1f7d513836e55cb78abcd21/Lib/fontTools/feaLib/parser.py#L599-L607

we need to distinguish the two, and do the right thing.

**Comment by bobh0303** [comment]
> I wonder what makeotf makes of your pair pos statement pos glyph1 <NULL> glyph2 <-180 0 -90 0>;

It aborts with a syntax error:
```
syntax error at "NULL" missing { NUM GNAME } [S.fea 31]
makeotfexe [FATAL] <Surma> aborting because of errors
```

It looks to me like there are currently six places in the Adobe spec, including three in the valuerecord area, that indicate their syntax is "Not Implemented" by their tools.

**Comment by anthrotype** [comment]
@bobh0303 Thanks for checking. Maybe you could open an issue on the afdko repo as well, referencing this.
The fix is on master, let me know if that works for you now.

**Comment by bobh0303** [comment]
Many thanks for the quick responses! The compiled code now looks correct to me, with the non-empty value record being applied to glyph2:
```
        <!-- SubTableCount=1 -->
        <PairPos index="0" Format="1">
          <Coverage Format="1">
            <Glyph value="glyph1"/>
          </Coverage>
          <ValueFormat1 value="0"/>
          <ValueFormat2 value="5"/>
          <!-- PairSetCount=1 -->
          <PairSet index="0">
            <!-- PairValueCount=1 -->
            <PairValueRecord index="0">
              <SecondGlyph value="glyph2"/>
              <Value2 XPlacement="-180" XAdvance="-90"/>
            </PairValueRecord>
          </PairSet>
        </PairPos>
```
