### ISSUE TITLE
[feaLib] Special case of contextual positioning not supported

### ISSUE THREAD

**Issue by punchcutter** [fonttools/fonttools#1468]
Just ran into this trying to run fontmake on a Glyphs source file with added contextual kerning. 

From https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#6.h.v
> In order to make pair positioning rules easier to read and write as contextual kern pairs, the feature file syntax will identify a special case of contextual rule which contains only one marked glyph or glyph class, followed by one or more un-marked glyph or glyph class, plus a value record. This will be treated as a contextual pair positioning statement, and will be the only one case where a value record may follow an un-marked glyph.

The example shown is 

`position L' quoteright -150;` 

but makeotf will also allow a more complicated sequence like 

`pos @someclass' @anotherclass [someglyph anotherglyph moreglyphs] <30 0 30 0>;`

When this format is used feaLib loses the ValueRecord at https://github.com/fonttools/fonttools/blob/18ac453781029783e1d340ada7699df966c2b04b/Lib/fontTools/feaLib/parser.py#L407

Handling this would need an update to `asFea()` at https://github.com/fonttools/fonttools/blob/18ac453781029783e1d340ada7699df966c2b04b/Lib/fontTools/feaLib/ast.py#L1066 if 100% round tripping were desired. As is it will only do the standard format and put the ValueRecord after the `'`.

**Comment by anthrotype** [comment]
@punchcutter thanks for the report. I can have a look at this after I'm back to work in the second week of February -- unless sombody else wishes to tackle this before.

**Comment by marekjez86** [comment]
@punchcutter : thanks for debugging the problem

**Comment by marekjez86** [comment]
@anthrotype : any update on this?
cc @davelab6 
I cannot assign bugs in this repository hence I'm using comments

**Comment by anthrotype** [comment]
Thanks for checking. I am busy with internal training for at least another two weeks, I am afraid I won't be able to look into this before then.

**Comment by punchcutter** [comment]
It's not a huge deal and isn't blocking anything, but I'll send a pull request today.

**Comment by anthrotype** [comment]
that'd be awesome! thanks
