### ISSUE TITLE
[ufoLib] change requested for woffMetaDataDescription  validator 

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#1471]
see https://github.com/robotools/defconAppKit/issues/26

I dont see a reason why the `text` must be required in a provided dict. I guess this could be similar to `fontInfoWOFFMetadataLicenseValidator`.

I can make a PR if this is necessary?

**Comment by typemytype** [comment]
http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#woff-metadata-description-record

the `text` value:

> A list of WOFF Metadata Text Records for the description. This list must contain at least one text record. 

(this is the same for `fontInfoWOFFMetadataLicenseValidator`)

**Comment by benkiel** [comment]
Looking at the WOFF spec (https://www.w3.org/TR/2012/REC-WOFF-20121213/#Metadata), the _text_ element is required, where the url is not required (the opposite of the license element). So, the UFO spec is correct for the description element, but is not correct for the license element (there the WOFF spec says that "zero or more" text elements, the description says "one or more"). I'll open a PR for the UFO spec for the license element. If I read the ufoLib validator correctly, it is fine.
