### ISSUE TITLE
[varLib / instancer] leaves DSIG in static instance; should remove

### ISSUE THREAD

**Issue by robmck-ms** [fonttools/fonttools#1480]
Looks like varLib.mutator does not strip DSIG when generating static instances, thus the instance has the VF's DSIG. If that DSIG was not a dummy DSIG, then the DSIG will be invalid for the static instance. Probably would be good to just strip DSIG or replace it with a dummy.

This is a minor issue since practically nothing validates DSIGs, but anyway...

**Comment by robmck-ms** [comment]
Good point. I haven't tried that, but I don't see anything for DSIG in varLIb/__init__.py for it, so...

**Comment by behdad** [comment]
Fixed mutator. Reopening to check varLib.
