### ISSUE TITLE
[snippets] Renaming glyphs

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#149]
For TrueType, something like this works:

``` python
    font = fontTools.ttLib.TTFont(inpath)
    glyphnames = font.getGlyphOrder()
        # Do the renaming in glyphnames...
    font = fontTools.ttLib.TTFont(inpath) # load again
    font.setGlyphOrder(glyphnames)
    post = font['post']
    font.save(outpath)
```

For cff, we need to set font['CFF '].cff.topDictIndex[0].charset, but also to remap font['CFF '].cff.topDictIndex[0].CharStrings as in https://github.com/behdad/fonttools/issues/147.

**Comment by brawer** [comment]
Should we add a `TTFont.renameGlyphs` method that knows how to handle different flavors?

**Comment by behdad** [comment]
> Should we add a TTFont.renameGlyphs method that knows how to handle different flavors?

No. Higher-level operations like this do NOT belong in ttLib IMO.
