### ISSUE TITLE
Remove .gitattributes in release tarballs

### ISSUE THREAD

**Issue by medicalwei** [fonttools/fonttools#1491]
As we are packaging Debian package for fonttools to build fonts, we have problems that your .gitattributes in your tarball interferes our [git-buildpackage][1] packaging layout.  This causes the integrity check between the packaging repo (which auto converts CRLF into LF) and the tarballs (some files in CRLF) fail due to the line ending difference.

We can workaround the issue at the moment by stripping out .gitattributes during packaging, but .gitattributes shouldn't appear in release tarball since it is only used for git repo management.

[1]: https://honk.sigxcpu.org/piki/projects/git-buildpackage/

**Comment by khaledhosny** [comment]
I don’t see any `.gitattributes` files in the [latest release archive](https://github.com/fonttools/fonttools/releases/download/3.44.0/fonttools-3.44.0.zip).
