### ISSUE TITLE
svgLib: Support import of shapes

### ISSUE THREAD

**Issue by rsheeter** [fonttools/fonttools#1492]
#1141 helps a lot when importing arcs. However, shapes (https://www.w3.org/TR/SVG11/shapes.html) silently drop. Can we start adding support for shapes? - spec explains how to map them to <path> and we know how to handle <path>.

**Comment by khaledhosny** [comment]
Anything still missing after #1508?

**Comment by miguelsousa** [comment]
#1563 added support for `<ellipse>` and #1564 added support for `<polyline>` as well as **matrix** transform functions.

Looking at https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Basic_Shapes it seems that only `<line>` is left to be supported.

**Comment by miguelsousa** [comment]
Just added support for `<line>` in #1564 as well.

**Comment by anthrotype** [comment]
Thanks Miguel, I’ll take a look tomorrow.
