### ISSUE TITLE
How do I use pyftsubset from python and not command line?

### ISSUE THREAD

**Issue by xandervx** [fonttools/fonttools#1505]
I have been trying to find how to use pyftsubset from python and not command line but the documentation is as good as 0. I am not so advanced in the font file inner working and cannot really spend weeks trying to understand how the fonttools codebase works. With jupyter I tried !pyftsubset ... , but some of the ttf files through errors and, hence, stops the command line execution but I cannot catch and escape those errors in jupyter. So back to the question, if the library was written in python, how do I do font subsetting directly within the python environment?

**Comment by jenskutilek** [comment]
Here’s some untested sample code.

```python
from fontTools.subset import Options
from fontTools.subset import Subsetter
from fontTools.ttLib import TTFont

fontObject = TTFont("../../path/to/font.ttf")
subset_glyphs = ["A", "B", "C", "Adieresis"]

options = Options()
options.drop_tables = []
options.glyph_names = True
options.layout_features = "*"
options.legacy_cmap = True
options.name_IDs = "*"
options.name_languages = "*"
options.name_legacy = True
options.notdef_outline = True
options.recalc_bounds = True
options.recommended_glyphs = True
options.symbol_cmap = True

subsetter = Subsetter(options=options)
subsetter.populate(glyphs=subset_glyphs)
subsetter.subset(fontObject)

fontObject.save("../../path/to/subsetted_font.ttf")
fontObject.close()
```

You can also use `subsetter.populate` with `unicodes` instead of `glyphs` (glyph names).
