### ISSUE TITLE
empty Blues operators in CFF PrivateDict rejected by OTS

### ISSUE THREAD

**Issue by ahmet-celik** [fonttools/fonttools#152]
Used [DroidSansFallback font](https://github.com/android/platform_frameworks_base/blob/master/data/fonts/DroidSansFallback.ttf).
Used following command to convert ttf file to woff

``` python
def save_as_woff(input):
  from fontTools.ttLib import TTFont
  font = TTFont(input)
  font.flavor = 'woff'
  font.save(input+'.woff')
```

This function worked for other fonts but this one.
Issue is generated woff file could not loaded in Chrome Version 36.0.1985.143
Tool used [fontTools/samfishman:decompressing](https://github.com/samfishman/fonttools/commit/f9bbe6890e4bbf870aaaabee4c379a4fc858d157)

**Comment by zar-nicolas20** [comment]
Once a woff (CFF) is subsetted with pyftsubset, this is not decoded by Chrome in Windows 7. That doesn't happen. Could that be related with this issue?

**Comment by alphachung** [comment]
Faced the same problem as well. To work around this, after I subsetted the fonts with pyftsubset, I used Glyphs to open the OTF files, and then exported them to woff and woff2. Chrome can decode the files generated by Glyphs.

**Comment by anthrotype** [comment]
@alphachung I don't think this has to do with the WOFF or WOFF2 compression per se. it might be the subsetted font is being rejected by the opentype sanitizer (used to decode fonts by Firefox and Chrome) for other reasons.
try passing the font to `ots-sanitize` tool https://github.com/khaledhosny/ots/, or send me a copy if you wish. 
Thanks

**Comment by alphachung** [comment]
[Archive.zip](https://github.com/fonttools/fonttools/files/1492351/Archive.zip)

- source.otf - Source
- pyftsubset_regular.otf - Source subsetted by pyftsubset
- pyftsubset_regular.woff & pyftsubset_regular.woff2 - Source subsetted by pyftsubset, woff & woff2 flavour
- glyphs_regular.woff & glyphs_regular.woff2 - pyftsubset_regular.otf exported to woff & woff2 via Glyphs

**Comment by behdad** [comment]
I won't get to debug this immediately, so if @anthrotype can triage a bit would be nice. Thanks.

**Comment by anthrotype** [comment]
Running ots-sanitize on the source.otf file yields
```
ERROR: CFF : Failed to parse table
Failed to sanitize file!
```
Same error, consequently, for the pyft-subsetted fonts.

The glyphs_regular.woff and woff2 fonts sanitize successfully.

How was the original source.otf generated? The name table says the font is called "Inter UI".
https://rsms.me/inter/

**Comment by anthrotype** [comment]
If you dump to TTX the source.otf, and remove these two lines, then re-compile to OTF using ttx, then the font passes OpenType Sanitizer successfully.

```diff
diff --git a/source.ttx b/source.ttx
index 9fdfea3..b237f99 100644
--- a/source.ttx
+++ b/source.ttx
@@ -10768,8 +10768,6 @@
       <Private>
         <BlueValues value="-32 0 1536 1556 2048 2076"/>
         <OtherBlues value="-576 -512"/>
-        <FamilyBlues value=""/>
-        <FamilyOtherBlues value=""/>
         <BlueScale value="0.039625"/>
         <BlueShift value="16"/>
         <BlueFuzz value="0"/>
```

**Comment by anthrotype** [comment]
This reminded me of this
https://github.com/googlei18n/ufo2ft/pull/115

**Comment by anthrotype** [comment]
It's unclear whether empty Blues operators in PrivateDict is illegal or not. I just filed a issue against the OpenType Sanitizer.
https://github.com/khaledhosny/ots/issues/156

/cc @readroberts

**Comment by anthrotype** [comment]
I think we can close this issue as it's not related to fonttools. We are simply keeping the original CFF table's private dict operators (of unknown provenance) intact as we subset or compress to woff.
The issue, if any, is either in the source font (it has such empty Blues values) or in the OpenType Sanitizer that rejects it.
We can keep on discussing this on the OTS issue tracker.

**Comment by behdad** [comment]
> It's unclear whether empty Blues operators in PrivateDict is illegal or not. I just filed a issue against the OpenType Sanitizer.

I suggest we fix here as well.  I thought I fixed that.

**Comment by anthrotype** [comment]
What is the fix then? And why is it broken?

**Comment by benkiel** [comment]
Is it up to fontTools to fix an error in a source file? I'm not so sure it is.

**Comment by anthrotype** [comment]
I think @behdad thinks the subsetter was responsible for leaving behind empty dict operators.
But I checked the original "source.otf" file from the OP, and that already contained such empty operators. ttLib simply roundtrips the original CFF table.

**Comment by benkiel** [comment]
Subsetter shouldn't leave empty, but yeah, if it's in the original, then it's not for fontTools to do anything to.

**Comment by behdad** [comment]
> But I checked the original "source.otf" file from the OP, and that already contained such empty operators. ttLib simply roundtrips the original CFF table.

How come that font works but subset one doesn't then?  Or maybe I didn't read all the details correctly.

**Comment by anthrotype** [comment]
The original (I am not sure how original) font source.otf doesn’t work because of that issue. Of course the subsetted doesn’t either.

**Comment by readroberts** [comment]
Any reason not close this? Looks to me as if the issue has been fixed and related issues closed.

FYI: It is legal to have an empty BlueValue array. You have to go back to the Adobe T1 specification, end of section '5.3 Blue Values':
"""The BlueValues array is required in the Private dictionary. If no
alignment zones are necessary, use an empty array for the value
of BlueValues:
/BlueValues [ ] def"""
