### ISSUE TITLE
How to get the font title

### ISSUE THREAD

**Issue by rxy007** [fonttools/fonttools#1529]
hi, i use python3, Can `fonttools` get the title of the font?
![image](https://user-images.githubusercontent.com/21076858/53779566-85af7680-3f3b-11e9-8404-6e56a3187672.png)
thanks.

**Comment by m4rc1e** [comment]
```
from fontTools.ttLib import ttFont

font = TTFont('path/to/font.ttf')

for name in font['name'].names:
    if name.nameID == 1:
        print(name.toUnicode())
```

The above will print all name records which have nameID 1, https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids

**Comment by rxy007** [comment]
> ```
> from fontTools.ttLib import ttFont
> 
> font = TTFont('path/to/font.ttf')
> 
> for name in font['name'].names:
>     if name.nameID == 1:
>         print(name.toUnicode())
> ```
> The above will print all name records which have nameID 1, https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids

thanks
