### ISSUE TITLE
[feaLib] Octal numbers are parsed as decimal

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fonttools#1541]
[The OpenType feature file spec](https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9.e) says, “Decimal numbers must begin with a non-0 digit, octal numbers with a 0 digit, and hexadecimal numbers with a 0x prefix to numbers and hexadecimal letters a-f or A-F.” Octal numbers are accepted after `nameid`, `name`, and `sizemenuname`; makeotf also accepts them after `Character`. feaLib’s parser does not recognize octal numbers and just treats them as decimal.

**Comment by khaledhosny** [comment]
Do you have a sample feature file to test with?

**Comment by dscorbett** [comment]
```pycon
$ python3 -q
>>> from io import StringIO
>>> from fontTools.feaLib.parser import Parser
>>> Parser(StringIO("feature dist { position a 010; } dist;")).parse().statements[0].statements[0].pos[0][1].xAdvance
10
```

**Comment by khaledhosny** [comment]
Can octal or hexadecimal numbers be prefixed by `-`?

**Comment by dscorbett** [comment]
[It doesn’t look like it.](https://github.com/adobe-type-tools/afdko/blob/be1e5d33f09f14e67d1c3b57e0cdb43b826532be/c/makeotf/makeotf_lib/source/hotconv/featpars.dlg#L615-L618) It also looks like non-decimal numbers are only allowed in certain contexts, after the keywords in my original comment. So I think my 'dist' example should be a syntax error.

**Comment by khaledhosny** [comment]
Looks like feaLib already accepts hexadecimals everywhere, but I think with octals it might be worse. Need to find what makeotf does here and see if we can follow it.
