### ISSUE TITLE
crash on using mutator to instantiate from a VF

### ISSUE THREAD

**Issue by laerm0** [fonttools/fonttools#1548]
Hi. I am using [a script](https://gist.github.com/chrissimpkins/763ae5f23fa260fcc54d6a0ec2c41942) @chrissimpkins wrote to instantiate statics from a VF. It looks like mutator/ttLib is crashing on the `gvar` table. 

```
Traceback (most recent call last):
  File "/Users/stupakm/Documents/freelance/code_apps_etc/vf2s.py", line 170, in <module>
    main()
  File "/Users/stupakm/Documents/freelance/code_apps_etc/vf2s.py", line 118, in main
    instantiateVariableFont(font, instance_location, inplace=True)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/fontTools/varLib/mutator.py", line 178, in instantiateVariableFont
    gvar = varfont['gvar']
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 392, in __getitem__
    table.decompile(data, self)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 111, in decompile
    numPointsInGlyph, sharedCoords, axisTags, gvarData)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 227, in decompileGlyph_
    sharedTuples, data, 4, offsetToData)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 553, in decompileTupleVariationStore
    tableTag, axisTags, tupleData, pointDeltaData))
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 596, in decompileTupleVariation_
    len(points), tupleData, pos)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 414, in decompileDeltas_
    runHeader = byteord(data[pos])
IndexError: index out of range
```

The file I'm using here is the Italic in my [Open Sans repo](https://github.com/laerm0/opensans/tree/master/variable_ttf). (The Roman works fine.)

**Comment by anthrotype** [comment]
by looking at the error it appears that the gvar table is corrupt. how was it generated in the first place?

**Comment by laerm0** [comment]
fontmake, but it used the complex build process I described briefly when we last spoke. (Scripts [here](https://github.com/laerm0/opensans/tree/master/source/tools), documentation [here](https://docs.google.com/document/d/10zal3PbYX-Mku1c_6xtPcwlGtR8zGr3l81EuoB2In5c/edit?usp=sharing)

I haven't seen any issues with using the font, nor does fontbakery complain. (It doesn't pass `ots-sanitize` but that's in `STAT` and `GDEF`.)

**Comment by anthrotype** [comment]
ok I see that mutator fails do decompile the gvar table for this font:
https://github.com/laerm0/opensans/blob/master/variable_ttf/OpenSans-Italic-VF.ttf

I'm afraid I don't have time to debug your custom build scripts, but I you provide a reproducer by using only vanilla fontmake that would be great.

E.g. very concise command lines that I can run to compile that font from source and trigger the possibly faulty gvar table

**Comment by laerm0** [comment]
Sure thing. I'll take a look. Thanks @anthrotype .

**Comment by anthrotype** [comment]
The "Open Sans Italic V.glyphs" file in your repo contains some bracket layers with multiple axes, which glyphsLib rejects as invalid (https://github.com/googlei18n/glyphsLib/issues/468).
If I delete them and then try to build with fontmake, the generated variable font does not have the faulty gvar table and can be decompiled and run through mutator just fine.

**Comment by laerm0** [comment]
That makes sense, but the Roman has the same bracket layers with multiple axes, so I didn't think that was the issue.

**Comment by anthrotype** [comment]
it turns out this error was the result of using VTT autohinter which sometimes modifies the glyf coordinates (unless you "disable outline modification" option in setttings).

**Comment by laerm0** [comment]
Eh, no, I have VTT always set not to modify the outlines. I'm still trying to figure out what happened. Please keep this issue open.

**Comment by anthrotype** [comment]
oh I misunderstood.
In any case, whatever tool you're using to post-process OpenSans as fontTools varLib originally built it, that may be modifying the glyph point indexes in the glyf table, will inevitably break gvar.

**Comment by laerm0** [comment]
Yep, I wanted to figure out which part of the process broke it, so I was going to go through step-by-step and see where it collapses. I'll update this issue at a later date. Thanks @anthrotype .

**Comment by benkiel** [comment]
@laerm0 FWIW, that setting doesn't stick, you have to turn it on each time you open a font in VTT (yes, this drives me crazy)

**Comment by laerm0** [comment]
@benkiel Huh, I don't have that problem. It used to be the case, though: are you on the newest VTT? It's at v6.31.

![Apr-08-2019 12-58-47](https://user-images.githubusercontent.com/10780161/55742656-2c38dc80-59fe-11e9-93c6-4f942bac5f32.gif)

On the other hand, I have gone at the VTT registry entries with a baseball bat and machete to get it to work properly, so maybe I've really done a thing to it.

**Comment by benkiel** [comment]
@laerm0 Oh man, if it stopped doing that I'd be so happy. I doubt I'm on the latest, I pick VTT up every couple months, so I'm not frequently using it. Thank you for the tip!

**Comment by behdad** [comment]
So, non-issue then?
