### ISSUE TITLE
Add support in varLib for building a VVAR table

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#1549]
@behdad  @anthrotype I am looking at adding VVAR support in varLib/__init__.py, and have a question about optimization. The current code for the HVAR table builds a version with and without an advanceWidthMappingOffset delta-set index map, and uses whichever is smaller. With the VVAR table, the simplest approach is to always build both advanceHeightMappingOffset and vOrgMappingOffset delta-set index maps, and add the delta tuples the same ItemVariationData subtable. I could also try to build  a directly mapped ItemVariationData for the advanceHeight deltas, and use a different  ItemVariationData subtable with a  vOrgMappingOffset, and use that combination if it is smaller. Left to myself, I wouldn't bother with this optimization. Opinions?

**Comment by behdad** [comment]
I'm fine without the optimization.

**Comment by anthrotype** [comment]
fixed with https://github.com/fonttools/fonttools/pull/1551
