### ISSUE TITLE
[subset] Reorder glyphs & compress cmap

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#156]
Idea for extra minification in subset.py:

Since many cmap subtable formats like format 12 compress the cmap if there is a continuous sequence of codepoint-to-GID mappings, you could add an option to reorder the encoded glyphs by their Unicode codepoint.

Some testing would be needed if all web platforms (browser+OS)\* support the cmap 3.10. If they do, that option could result in only cmap 3.10, without 3.1 is written. I.e. if there already is a 3.10, keep it and drop 3.1, and if there is none, move all 3.1 mapping to 3.10 and drop 3.1. And always do the reordering I mentioned.

Since the spec recommends the 3.10 subtable to use the sequence-compressing format 12, you'll pretty much always shave off some bytes.

*) By "all web platforms" I mean "all relevant/of interest", i.e. those that support WOFF.Since EOT, as the only oprion, was used only in older IE which did not expose user-controlled OTL features, reasonable webfont-making tools should make different subsets for the purpose of EOT creation than for WOFF creation anyway.

**Comment by cbreeden** [comment]
@behdad has the status changed with respect to reordering glyphs?  I have a situation that essentially requires me to redorder glyphs if I don't want to thrash the CMAPs, but it it didn't seem to work out well.  In particular it does seem that the  GSUB/GPOS/GDEF tables arent updated accordingly.

**Comment by cbreeden** [comment]
It also appears that the `CFF{2}` table also needs to be updated.

**Comment by behdad** [comment]
> @behdad has the status changed with respect to reordering glyphs?

No.

> I have a situation that essentially requires me to redorder glyphs if I don't want to thrash the CMAPs, but it it didn't seem to work out well. In particular it does seem that the GSUB/GPOS/GDEF tables arent updated accordingly.

Correct.

Can you elaborate a bit more?  How much is the cmap size difference in your experience?  I haven't got to implement this because it doesn't look like a particularly useful operation...

**Comment by cbreeden** [comment]
@behdad well, I might be doing something terrible, but I was working on a math rendering engine that needed to communicate glyph ids.  Ideally for something like SVG.  The issue with most math fonts is that for many variants the glyphs aren't accessible from the CMAP (as an example a left brace has 9 different size variants in STIX2).  To fix this, I placed the variants I needed in the PUA.  This increased the number of groups in format 4/12 from something like 1100 to 2200.

I fiddle around with fonttools to see what I could get working, and these were my observations.  To properly update the Math tables in the font I needed to:
1. Manually `decompile` each Math table that references a GlyphID.  This would force each table to decompile and obtain the correct glyph name for which they referenced.
2. Modify the glyph order in the CFF table (topDictIndex), both the `charset` and the `charStrings`.

This worked, except that the names seemed to be a little scrambled in the end.  I didn't pursue the approach any further, but it felt like I needed to for an update on `charStrings` somewhere else in a particular order.

Though, I will agree.  This is a particularly niche operation.

**Comment by davidseah** [comment]
@cbreeden did you managed to find a solution for the reordering of the glyph? I needed this feature for a project and found this thread.

**Comment by behdad** [comment]
I feel like we should just close this. Not worth it.

**Comment by justvanrossum** [comment]
What is the main issue here? Reordering the glyphs should be easy if you make sure all tables are loaded. Just assign a new glyph order, no?

**Comment by behdad** [comment]
Reordering is not that easy. The Coverage table in GSUB/GPOS assumed that Coverage numbers are ascending by glyphs covered. We don't abstract Coverage away in the more complex lookups.

We do however have a hack to generate what it's in fact invalid OpenType fonts but works everywhere for that case. Search for brokenOrder in otTables.py.

That's the only case that I can think of.

**Comment by cbreeden** [comment]
@davidseah I ended up using fontforge.  It seems that fontforge tries to order the glyphs in an optimal way when saving.
