### ISSUE TITLE
Check if font supports multi code point emoji

### ISSUE THREAD

**Issue by COM8** [fonttools/fonttools#1569]
I'm trying to check if a font has a glyph for a multi codepoint emoji like "👱🏼‍♂️", "🐱‍🐉" or "🖐🏼" in Python 3.x.

For single codepoint emoji like "😄" or "😉" I'm able to validate their support via the following code:
```python
from fontTools.ttLib import TTFont

def __isEmojiSupportedByFont(emoji: str) -> bool:
    font = TTFont(r"C:\Windows\Fonts\seguiemj.ttf")
    emojiCodepoint = ord(str) # Only works for single codepoint emoji
    for table in font['cmap'].tables:
        for char_code, glyph_name in table.cmap.items():
            if char_code == emojiCodepoint:
                return True
    return False
```

How do I do this for multi codepoint emoji (is there a method for this), since `cmp ` only has single codepoint emoji in it?

[Link](https://stackoverflow.com/questions/55373103/python-fonttools-check-if-font-supports-multi-codepoint-emoji) to my stackoverflow question for this.

**Comment by khaledhosny** [comment]
Such combinations are usually implemented as ligatures, so you will need to check the `GSUB` table. A simpler way would to shape the string with HarfBuzz and check the output.

**Comment by COM8** [comment]
OK looks like I have to find out how to use HarfBuzz in python since I don't really know how to traverse the `GSUB` [Lookup List](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub) using `fonttols`.

Any chance you have any references on how to solve my problem using HarfBuzz ([harfpy](https://github.com/ldo/harfpy))?

**Comment by justvanrossum** [comment]
Aren't these often implemented with Unicode Variation Sequences? In that case you'd get the info from a format 14 cmap subtable. https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-14-unicode-variation-sequences

**Comment by justvanrossum** [comment]
(I may be completely wrong here.)

**Comment by justvanrossum** [comment]
HarfBuzz: either use the hb-shape command line tool that comes with HarfBuzz, or use the uharfbuzz module (available with pip).

**Comment by khaledhosny** [comment]
> Aren't these often implemented with Unicode Variation Sequences? In that case you'd get the info from a format 14 cmap subtable.

That would work for Emoji vs Text presentation (which uses variation selectors), but ZWJ sequences and skin color modifiers don’t use variation selectors and are implemented as regular `GSUB` ligatures (or in `morx` table in case of Apple Color Emoji font).

**Comment by COM8** [comment]
> 
> 
> HarfBuzz: either use the hb-shape command line tool that comes with HarfBuzz, or use the uharfbuzz Python module (available with pip).

uharfbuzz looks like a good lib for HarfBuzz. I think this will work for me.

**Comment by COM8** [comment]
Got it working, thanks for your help!
And for reference here my code:
```python
from uharfbuzz import Face, Font, Buffer, ot_font_set_funcs, shape

def __isEmojiSupportedByFont(self, emoji: Emoji) -> bool:
    # Load font:
    with open(r"C:\Windows\Fonts\seguiemj.ttf", 'rb') as fontfile:
        self.fontdata = fontfile.read()

    # Load font (has to be done for call):
    face = Face(self.fontdata)
    font = Font(face)
    upem = face.upem
    font.scale = (upem, upem)
    ot_font_set_funcs(font)

    # Create text buffer:
    buf = Buffer()
    buf.add_str(emoji.emoji)
    buf.guess_segment_properties()

    # Shape text:
    features = {"kern": True, "liga": True}
    shape(font, buf, features)
    return len(buf.glyph_positions) == 1
```

**Comment by khaledhosny** [comment]
> ```python
>     return len(buf.glyph_positions) == 1
> ```

I’d check `glyph_infos` here, though it makes no difference in practice. Since this can also use this to check for single code point emojis, you should check that the glyph index is not zero.

**Comment by COM8** [comment]
@khaledhosny right thanks.
Updated it to fix some single codepoint emoji like `☹️`:

```python
from uharfbuzz import Face, Font, Buffer, ot_font_set_funcs, shape

def __isEmojiSupportedByFont(self, emoji: Emoji) -> bool:
    # Load font:
    with open(r"C:\Windows\Fonts\seguiemj.ttf", 'rb') as fontfile:
        self.fontdata = fontfile.read()

    # Load font (has to be done for call):
    face = Face(self.fontdata)
    font = Font(face)
    upem = face.upem
    font.scale = (upem, upem)
    ot_font_set_funcs(font)

    # Create text buffer:
    buf = Buffer()
    buf.add_str(emoji.emoji)
    buf.guess_segment_properties()

    # Shape text:
    features = {"kern": True, "liga": True}
    shape(font, buf, features)
    # Remove all (0, 0, 0, 0) positions:
    res = [pos for pos in buf.glyph_positions if not all(p == 0 for p in pos.position)]
    return len(res) == 1
```

**Comment by khaledhosny** [comment]
If you want to check glyph indices, positions is not the right place to check :slightly_smiling_face:, you should check for `codepoint` of `glyph_infos` (that is the glyph index, despite its name).

**Comment by COM8** [comment]
OK but for which values should I check there for then?
For example the `🐿` Emoji will result in:
![image](https://user-images.githubusercontent.com/11741404/55674557-875fb780-58b6-11e9-8672-1af818194398.png)

And the `👨‍👨‍👧‍👦` Emoji in:
![image](https://user-images.githubusercontent.com/11741404/55674548-69925280-58b6-11e9-99f4-0adfc804fc83.png)

**Both** of them are supported by the font.

**Comment by khaledhosny** [comment]
If `codepoint` is zero, then glyph is not supported. You should check that all `glyph_infos` don’t have zero `codepoint`’s instead of filtering them an checking the length (e.g. the font might support one glyph in a ZWJ sequence but not the rest).

**Comment by COM8** [comment]
That's it! Thank you very much for your help!

And again as reference, my code:
```python
from uharfbuzz import Face, Font, Buffer, ot_font_set_funcs, shape

def __isEmojiSupportedByFont(self, emoji: Emoji) -> bool:
    # Load font:
    with open(r"C:\Windows\Fonts\seguiemj.ttf", 'rb') as fontfile:
        self.fontdata = fontfile.read()

    # Load font (has to be done for call):
    face = Face(self.fontdata)
    font = Font(face)
    upem = face.upem
    font.scale = (upem, upem)
    ot_font_set_funcs(font)

    # Create text buffer:
    buf = Buffer()
    buf.add_str(emoji.emoji)
    buf.guess_segment_properties()

    # Shape text:
    features = {"kern": True, "liga": True}
    shape(font, buf, features)
    return all(info.codepoint for info in buf.glyph_infos)
```

**Comment by khaledhosny** [comment]
Or `len(buf.glyph_infos) == 1 and buf.glyph_infos[0].codepoint` since the individual characters might not be supported but not the ligature (depending on your definition of supported, the presence of the ligature might be significant or not).
