### ISSUE TITLE
AttributeErrors on missing OT table fields after TTFont.importXML

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1584]
there seems to be a mismatch between loading a TTFont from a binary font, and importing it from XML, as far as the otTables are concerned (i.e. those auto-generated from otData declarations).

Upon decompiling from (or compiling to) a binary font, all the missing fields in otTables (those with NULL offsets) are automatically set to `None`.
Also, the `Count` attributes are (re-)computed only upon compiling the tables.

When dumping a TTFont to TTX with `saveXML`, all these either missing or None struct fields in OT tables are simply omitted from the TTX dump.
Similarly, Count attributes are only written out to XML comments.
 
The issue is that, when one imports a TTFont with `importXML` method, all these missing fields that were not written out in the TTX dump will cause AttributeError -- unless one first compiles the TTFont to, say, a temporary BytesIO (to trigger the generation of the missing fields) then and reloads if off that, before processing it. (That's what I sometimes end up doing, e.g. when I need to import a TTX file for some unit tests).

**Comment by anthrotype** [comment]
related discussion https://github.com/fonttools/fonttools/commit/e846cc33c381176e292af1c94e3574c3dff12554#comments

**Comment by behdad** [comment]
It's supposed to work.  Grep for `populateDefaults`.  You see it called from xmlRead from Struct in otConverters.py.

**Comment by anthrotype** [comment]
Thanks, I'll check

**Comment by anthrotype** [comment]
Tests/subset/data/TestGVAR.ttx has this empty GSUB table:

```xml
  <GSUB>
    <Version value="0x00010000"/>
  </GSUB>
```

after TTFont.importXML, it only has Version attribute, and no LookupList attribute:
```python
>>> from fontTools.ttLib import TTFont
>>> f = TTFont()
>>> f.importXML("Tests/subset/data/TestGVAR.ttx")
>>> vars(f["GSUB"].table)
{'Version': 65536}
>>> f["GSUB"].table.LookupList
AttributeError: LookupList
```

**Comment by anthrotype** [comment]
Calling table.populateDefaults() at the end of `BaseTTXConverter.fromXML` fixes it:

```diff
diff --git a/Lib/fontTools/ttLib/tables/otBase.py b/Lib/fontTools/ttLib/tables/otBase.py
index 81ab354e..816f1cd0 100644
--- a/Lib/fontTools/ttLib/tables/otBase.py
+++ b/Lib/fontTools/ttLib/tables/otBase.py
@@ -104,6 +104,7 @@ class BaseTTXConverter(DefaultTable):
                        tableClass = getattr(otTables, self.tableTag)
                        self.table = tableClass()
                self.table.fromXML(name, attrs, content, font)
+               self.table.populateDefaults()
 
 
 class OTTableReader(object):
```

it looks like for top-level Tables (like GSUB or GPOS) the populateDefaults is never called otherwise. Only their children's converters xmlRead methods are called (which in turn will call the sub-table's populateDefaults()).

@behdad does that fix sound correct to you?

Or should I subclass BaseTable for top-level tables (e.g. GSUB, GPOS) inside otTables, and have their fromXML method call back their own populateDefaults()?

**Comment by anthrotype** [comment]
about the missing CompCount in Ligature subtables in LigatureSubst lookup subtables.
This seems to be related to the fact that LigatureSubst has a custom class implementation in otTables, and its fromXML doesn't set the `Ligature.CompCount` upon reading XML. I'll fix that.

**Comment by anthrotype** [comment]
I fixed it with https://github.com/fonttools/fonttools/commit/71812bbb293a97aa609735cc0491f86ee865fdf8 and 5a7fe05.
@behdad I can revert and further fix up if needed.

@miguelsousa you can rebase #1582 and remove that commit that uses `getattr`, it should work then.

**Comment by miguelsousa** [comment]
@anthrotype will do

**Comment by behdad** [comment]
Looks good.  Thanks.
