### ISSUE TITLE
can't run 'setup.py'

### ISSUE THREAD

**Issue by lemzwerg** [fonttools/fonttools#1585]
[5a7fe0556f63b3d17d6fee889537e980ba5851bc]

Executing `setup.py` (with either python 2 or 3) gives
```
error in fonttools setup command:
  'extras_require' must be a dictionary whose values are strings or lists of strings
  containing valid project/version requirement specifiers.
```

**Comment by justvanrossum** [comment]
Sounds like your setuptools is outdated: `pip install --upgrade setuptools`

**Comment by anthrotype** [comment]
Yes, like Just said.
I think this has to do with the use of so called “environment markers” in extras_require for conditional dependencies: e.g. “:python_version < ‘3.3’”.
Which I think was introduced with setuptools 18.0 (we are now at version 40 something)
There may be ways to make it more compatible with older setuptools but not sure if worth it.

**Comment by lemzwerg** [comment]
Thanks, that was it.  I don't use python very often, so I wasn't aware of this.

I think it would be fully sufficient if the standard sequence for calling `setup.py` gets mentioned, together with a hint that at least version xxx is necessary.

**Comment by anthrotype** [comment]
I don’t recommend to call setup.py script directly, but to use pip to install the released fonttools. People who wish to install the development version of fonttools from git source would usually know what to do.

**Comment by anthrotype** [comment]
The README already contain instructions to install in editable mode from local git source. When you use a virtualenv, you always get the latest version of pip and setuptools.

**Comment by miguelsousa** [comment]
> When you use a virtualenv, you always get the latest version of pip and setuptools.

I think that's true for Py2 but not for Py3.
