### ISSUE TITLE
Error decompiling OTL tables when CFF glyph names contain duplicates

### ISSUE THREAD

**Issue by mkraetke** [fonttools/fonttools#1602]
Thank you guys for developing this great tool and made it Open Source! Even if I rarely have issues with pyftsubset, it failed while creating a subset of the italic and bold-italic variant of Linux Libertine OTF. No file was created and I got this terminal output. My fonttools version is 3.39.0.

```
$ pyftsubset LinLibertine_RBI.otf --output-file=test.subset.otf --verbose --unicodes="U+0020"
Text: ''
Unicodes: [32]
Glyphs: []
Gids: []
maxp pruned
cmap pruned
post pruned
CFF  pruned
GPOS pruned
GSUB pruned
name pruned
Added .notdef to subset
Closing glyph list over 'GSUB': 2 glyphs before
Glyph names: ['.notdef', 'space']
Glyph IDs:   [0, 1]
Closed glyph list over 'GSUB': 2 glyphs after
Glyph names: ['.notdef', 'space']
Glyph IDs:   [0, 1]
Closing glyph list over 'CFF ': 2 glyphs before
Glyph names: ['.notdef', 'space']
Glyph IDs:   [0, 1]
Closed glyph list over 'CFF ': 2 glyphs after
Glyph names: ['.notdef', 'space']
Glyph IDs:   [0, 1]
Retaining 2 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
cmap subsetted
post subsetted
CFF  subsetted
WARNING: FFTM NOT subset; don't know how to subset; dropped
GDEF subsetted
Traceback (most recent call last):
  File "/usr/bin/pyftsubset", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2830, in main
    subsetter.subset(font)
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2633, in subset
    self._subset_glyphs(font)
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2579, in _subset_glyphs
    retain = table.subset_glyphs(self)
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1419, in subset_glyphs
    lookup_indices = self.table.LookupList.subset_glyphs(s)
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1204, in subset_glyphs
    return [i for i,l in enumerate(self.Lookup) if l and l.subset_glyphs(s)]
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 1176, in subset_glyphs
    self.SubTable = [st for st in self.SubTable if st and st.subset_glyphs(s)]
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 612, in subset_glyphs
    mark_indices = self.MarkCoverage.subset(s.glyphs)
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 400, in subset
    indices = self.intersect(glyphs)
  File "/usr/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 390, in intersect
    return [i for i,g in enumerate(self.glyphs) if g in glyphs]
  File "/usr/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 543, in __getattr__
    self.decompile(reader, font)
  File "/usr/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 640, in decompile
    self.postRead(table, font)
  File "/usr/lib/python2.7/site-packages/fontTools/ttLib/tables/otTables.py", line 533, in postRead
    (r.StartCoverageIndex, len(glyphs))
AssertionError: (28, 25)
```

**Comment by anthrotype** [comment]
can you upload the font here?

**Comment by mkraetke** [comment]
You can download it [here!](https://github.com/fonttools/fonttools/files/3156885/LinLibertine_RBI.zip)

**Comment by mkraetke** [comment]
In the meantime, I've installed version 3.41.0 and with this release, pyftsubset raises no errors. So thanks for your time, I'll close this issue and stick to the most recent version.

**Comment by anthrotype** [comment]
Thanks. I tried to dump that font with ttx and it fails to decompile the GPOS table with the same error, so it's not the subsetter that is the issue here.
Rather that font might have a corrupt GPOS table maybe. Do you know how it was produced?

**Comment by anthrotype** [comment]
well, even with the latest version I cannot decompile the font, so I believe the font itself may be corrupt.

**Comment by mkraetke** [comment]
I've downloaded the file straight from the [repository](https://sourceforge.net/projects/linuxlibertine/) of the font creator. Feel free to close the issue if you think that this font is corrupted. However it would be good to have a better error message then, like _GPOS table, font corrupted_.

**Comment by anthrotype** [comment]
Yes, the error message could be improved a little.
So, this specific error is saying that there is a MarkCoverage subtable (Format 2, i.e. using ranges) which has an invalid or unexpected StartCoverageIndex.

Here's the relevant spec:
https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#coverage-format-2

**Comment by anthrotype** [comment]
hm.. debugging a bit more it seems that the problem is that the CFF table contains some glyphs with duplicate names. FontTools library works internally with glyph names rather than glyph indexes so the mapping between the two must be one-to-one. In this font this is not the case:

```python
>>> from fontTools.ttLib import TTFont
>>> f = TTFont("~/Downloads/LinLibertine_RBI.otf")
>>> glyphOrder = f.getGlyphOrder()  # ordered list of glyph names from the CFF table's TopDict.charset
>>> len(glyphOrder)
1711
>>> len(set(glyphOrder))
1710
>>> from collections import Counter
>>> [glyphName for glyphName, count in Counter(glyphOrder).items() if count > 1] 
['uni0350',
 'acute.cap',
 'circumflex.cap',
 'caron.cap',
 'hungarumlaut.cap',
 'space_uni030F.cap',
 'breveinvertedcmb.cap',
 'breve.cyrcap',
 'breve.cyr',
 'dieresis.cap',
 'hookabovecomb.cap']
```

For TTF we make sure that the post glyph names are unique. We should do the same for CFF.

@mkraetke thanks for reporting this!

**Comment by behdad** [comment]
> Ok then if glyph names must be unique in CFF...

It's not like they are allowed non-unique in non-CFF...

**Comment by justvanrossum** [comment]
> It's not like they are allowed non-unique in non-CFF...

I can't find anything in the [`post` table documentation](https://docs.microsoft.com/en-us/typography/opentype/spec/post) that requires glyph names to be unique.

**Comment by anthrotype** [comment]
I guess it's implied by the fact that 'post' is for postscript glyph names and in postscript fonts glyph names must be unique.

**Comment by khaledhosny** [comment]
We already handle non-unique glyphs in `post` table, and I’m sure I have seen this in the wild (I don’t remember the fonts, though):
https://github.com/fonttools/fonttools/blob/ffc98baa0f28af7c4d4c173cca9f01b8c9baac14/Lib/fontTools/ttLib/tables/_p_o_s_t.py#L111-L117

**Comment by anthrotype** [comment]
yes, I was referring exactly to that when I commented earlier 

> For TTF we make sure that the post glyph names are unique.

Should we do the same (and issue a warning) for CFF?

I wonder how broken/invalid that Libertine font with duplicate glyph names actually is. FWIW, it passes the opentype-sanitizer.
