### ISSUE TITLE
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by BoldMonday** [fonttools/fonttools#1608]
It appears the Python 2 version of FontTools contains a bug making it impossible to run the current version of afdko:
https://github.com/adobe-type-tools/afdko/issues/796

**Comment by BoldMonday** [comment]
Here is the traceback:
```
Traceback (most recent call last):
  File "/Users/paulus/Library/Python/2.7/bin/makeotf", line 6, in <module>
    from afdko.makeotf import main
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/afdko/makeotf.py", line 14, in <module>
    from afdko import convertfonttocid, fdkutils, ufotools
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/afdko/ufotools.py", line 17, in <module>
    from fontTools.ufoLib import UFOReader
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fontTools/ufoLib/__init__.py", line 9, in <module>
    import fs
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fs/__init__.py", line 8, in <module>
    from .opener import open_fs
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fs/opener/__init__.py", line 14, in <module>
    from . import appfs, ftpfs, memoryfs, osfs, tarfs, tempfs, zipfs
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fs/opener/ftpfs.py", line 15, in <module>
    from ..errors import FSError, CreateFailed
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fs/errors.py", line 71, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

**Comment by justvanrossum** [comment]
I suspect a deployment issue. I just installed afdko in a fresh Python 2 virtual env and everything seems to be ok.

The error occurs while importing the fs module, so perhaps your fs install is out of date? Or your install of "six", which is a dependency of fs.

**Comment by BoldMonday** [comment]
I ran `pip install -upgrade afdko` and all requirements appear to be satisfied:
```
[...]
Requirement already satisfied, skipping upgrade: fs<3,>=2.2.0; extra == "ufo" in ./Library/Python/2.7/lib/python/site-packages (from fontTools[lxml,ufo,unicode]==3.41.0->afdko) (2.4.4)
[...]
Requirement already satisfied, skipping upgrade: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from singledispatch>=3.4.0.3; python_version < "3.4" and extra == "lxml"->fontTools[lxml,ufo,unicode]==3.41.0->afdko) (1.4.1)
```

**Comment by anthrotype** [comment]
You’re using the system python which comes with an outdated version of the six library in the System/Library/Frameworks/.../Extra folder which is added to the python path by Apple.

Try to pip install —upgrade six

It won’t let you do it because the folder is read only, but don’t use sudo or don’t remove SIP protection. 

Either install globally with —user flag, or use a virtual environment

**Comment by BoldMonday** [comment]
@justvanrossum For me the problem occurs when I run `makeotf`.

**Comment by BoldMonday** [comment]
Thanks @anthrotype. Will try.

**Comment by BoldMonday** [comment]
After trying the suggestions from @anthrotype it is clear that the problem lies with an outdated version of the six library that comes with the Apple supplied Python 2.7.10 in MacOS Mojave.

`pip install --upgrade six` is not permitted.
`pip install --user six` also does not work ("Requirement already satisfied").

This means that ufoLib – which needs a more recent version of six library – only works in a Python 2 virtual environment. (Or a custom installation of Python 2.)

**Comment by miguelsousa** [comment]
@BoldMonday did you try `pip install --user --upgrade six`?

**Comment by BoldMonday** [comment]
Aha. `pip install --user --upgrade six` does the trick indeed.

Thanks @miguelsousa!
