### ISSUE TITLE
Issue renaming CFF FontName

### ISSUE THREAD

**Issue by kontur** [fonttools/fonttools#1620]
Performing some family name updates on the name table I want to also update CFF font names from a OTF I edit in TTX and then save again. This works fine for `FullName` and `FamilyName` but `FontName` very stubbornly remains the original. I’m not sure if I am going about this the right way to begin with…

My code looks something like this:

```
cff = ttx["CFF "].cff
cffDict = cff[list(cff.keys())[0]].rawDict
cffDict["FontName"] = "FoobarFont-Regular"
cffDict["FullName"] = "Foobar Font Regular"
cffDict["FamilyName"] = "Foobar Font"
```

Is there something in the closing of the font that will ignore my set `FontName`, or is there a more reasonable way to achieve this?

Any and all pointers welcome to why this isn‘t doing what I think it should. (fonttools 3.41.2)

**Comment by benkiel** [comment]
Just a thought, but for FontName, you may need to also update nameid 6 in the name table also, I have a feeling that font tools may not be changing this because the two need to be in sync.

**Comment by miguelsousa** [comment]
This should work:
```python
cff = ttx["CFF "].cff
topDict = cff[cff.fontNames[0]].rawDict
topDict["FullName"] = "Foobar Font Regular"
topDict["FamilyName"] = "Foobar Font"
cff.fontNames = ["FoobarFont-Regular"]
```
As Ben mentioned, you should change `name` table ID 6 as well.

**Comment by benkiel** [comment]
Ah, Miguel is correct. FontTools isn't doing any magic. But, yes, change `nameid 6`

**Comment by kontur** [comment]
Perfect, thanks @miguelsousa. It makes sense, because the "Oldname" is the index itself... didn’t think of that :)

For future readers, the nameID 6 was already updating (other code) but that did neither trigger nor prevent the CFF FontName rewrite. Something along those lines was my thought as well, though, @benkiel.
