### ISSUE TITLE
[varLib.featureVar] Need to be able to generate 'rclt' and/or 'rlig'

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1625]
'rvrn' has some serious limitations, as seen in #1371 and discussed on the OpenType mailing list.

@behdad wrote in that discussion:

> Can we agree to change description of either 'rclt' or 'rlig' to be *the* global feature that should be used for whatever font designer wants, GSUB and GPOS?

So, while the spec would need to be edited to reflect this suggestion, the documented behavior of 'rclt' and 'rlig' are suitable for our needs, and `fontTools.varLib.featureVars` should be extended to make this possible.

Ideally, this should also trickle up to designspaceLib, at least as an option.

**Comment by khaledhosny** [comment]
Instead of having a variable access that is not variable, why not use `dlig` feature for off-by-default ligature which is its spec‘d behavior?

**Comment by arrowtype** [comment]
@khaledhosny that's mostly my preference, but there are pros and cons to either approach. I happened to make a slide show about this earlier in the week:

https://docs.google.com/presentation/d/11POJKckoGBhDk1kyQu3DC1tNUNJWwqF2FigIV6Tfdwo/edit?usp=sharing

**Comment by justvanrossum** [comment]
Fixed by https://github.com/fonttools/fonttools/commit/d96c92f95e908dc7b6df0ed23bebdef16a31a5ae
