### ISSUE TITLE
Forum referenced in contributing.md doesn't seem to exist

### ISSUE THREAD

**Issue by thundernixon** [fonttools/fonttools#1629]
In [CONTRIBUTING.md](https://github.com/fonttools/fonttools/blob/master/CONTRIBUTING.md), there is a link to a mailing list, but that takes me to a page with the following message:

> This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.

![image](https://user-images.githubusercontent.com/7355414/58730759-05be6e80-83bb-11e9-8bde-8696e3ee5f2f.png)

**Comment by justvanrossum** [comment]
You mean the link https://groups.google.com/d/forum/fonttools? Works for me, even though it immediately gets redirected to https://groups.google.com/forum/#!forum/fonttools

**Comment by justvanrossum** [comment]
Oh wait, you must mean https://groups.google.com/d/forum/fonttools-dev, for which I get the same error.

**Comment by anthrotype** [comment]
That one is mostly spam from Travis/Appveyor and Github every time someone pushes a commit to any branch.
No discussions go on over there, the other group should be used instead.

Anyway, you can again now, I changed the dev group visibility to “anyone on the web”.

**Comment by artcs** [comment]
Hmm, the dev group is now visible, but not the original enduser discussion group:

![googlegroup](https://user-images.githubusercontent.com/12881035/58808335-1ddff900-861a-11e9-85d9-d47f106b6172.png)

**Comment by anthrotype** [comment]
hm that's strange. thanks for reporting, I'll fix that

some default settings may have changed in Google Groups, we didn't deliberately change anything on our side

**Comment by anthrotype** [comment]
yes, i'm a member and it says "shared privately"..

![image](https://user-images.githubusercontent.com/6939968/58808887-cee29580-8612-11e9-8647-2d050d95570e.png)

the only owner is @behdad. Can you please set the group visibility to public?

I think this may be related:
https://gsuiteupdates.googleblog.com/2019/02/changes-to-google-groups-settings.html

**Comment by behdad** [comment]
I don't see where to make that change, but made you (@anthrotype) admin.

**Comment by anthrotype** [comment]
Thanks Behdad!
I set the visibility in "Group Directory" settings back to "anyone on the web". I wonder why Google Groups decided to change that... :thinking:
