### ISSUE TITLE
How can I modify a source attribute in a designspace file? I'm so close!

### ISSUE THREAD

**Issue by thundernixon** [fonttools/fonttools#1630]
_I'm not sure if this is the right place to ask a usage question, but the forum mentioned in the contribution guidelines is either down or doesn't exist (https://github.com/fonttools/fonttools/issues/1629). I'm also not able to find anything through Google. However, please let me know if I should move elsewhere with this question._

---

How I might set source `filename` attributes in a designspace file?

**Context:** 

I have [a script that takes in a designspace file and preps sources for interpolation into a prototype variable font](https://github.com/thundernixon/varfont-prep/blob/read-designspace/varfont-prep.py) by simply copying the UFOs into a timestamped folder and chucking out all incompatible glyphs. This is a "stupid" way to prep fonts for building, but it's pretty useful to allow me to check a variable font in browsers, etc, well before it the project has been totally finished.

However, this script currently only works if the designspace only points to UFOs in its own, same directory. I'd like to be able to go through and update the `filename` attribute of sources to correctly point to the new timestamped folder, if they have been copied in from other directories. But, once I have set source attributes to edited values, I'm having trouble making the attributes "stick" while I write a new designspace file.

Here's my current copy and edit function ([from here](https://github.com/thundernixon/varfont-prep/blob/read-designspace/varfont-prep.py#L119)):

```python
def copyDesignSpace(designspacePath):

    # duplicate designspace into new folder
    inputDStail = os.path.split(designspacePath)[1]
    outputDSpath = newFolderPath + "/" + inputDStail

    shutil.copyfile(designspacePath, outputDSpath)

    # update source & instance paths in designspace as needed
    outputDS = DesignSpaceDocument.fromfile(outputDSpath)

    for source in outputDS.sources:
        print(source.filename)  # prints the original value

        fontFilename = os.path.split(source.path)[1]
        setattr(source, 'filename', fontFilename)

        print(source.filename)  # this does change to the value I want

    # this doesn't overwrite the designspace file...
    outputDS.write(outputDSpath.replace(
        ".designspace", ".prepped.designspace"))


copyDesignSpace(designspacePath)
```

I think I'm close, but just missing something. If I find it, I'll update this thread. If someone else is able to point out what I'm missing, I would really appreciate the nudge in the right direction!

**Comment by justvanrossum** [comment]
It works for me if you do `source.path = None` in addition to your `source.filename` manipulation.

That's unintuitive and a bug IMO.

**Comment by justvanrossum** [comment]
Or, after reading the designspaceLib source more, I think you're supposed to manipulate `source.path` to begin with and `source.filename` will calculated from that upon write.

**Comment by thundernixon** [comment]
@justvanrossum Thank you so much for such quick help! 

Indeed, updating the `source.path` attribute automatically updates the `filename` attributes in the designspace XML. Here's where my function has ended up:

```
def copyDesignSpace(designspacePath, newFolderPath):

    # duplicate designspace into new folder
    inputDStail = os.path.split(designspacePath)[1]
    outputDSpath = newFolderPath + "/" + inputDStail

    shutil.copyfile(designspacePath, outputDSpath)

    # update source & instance paths in designspace as needed
    outputDS = DesignSpaceDocument.fromfile(outputDSpath)

    # updates path if sources were originally in a different directory than designspace file
    for source in outputDS.sources:
        newFontPath = newFolderPath + '/' + os.path.split(source.path)[1]
        setattr(source, 'path', newFontPath)

    outputDS.write(outputDSpath)

copyDesignSpace(designspacePath, newFolderPath)
```

**Comment by justvanrossum** [comment]
You can replace

`setattr(source, 'path', newFontPath)`

by

`source.path = newFontPath`

**Comment by thundernixon** [comment]
Oh nice, thank you for the added tip! 

It [looks like](https://teamtreehouse.com/community/so-what-does-setattr-and-getattr-actually-do) so long as an attribute is defined and allows redefinition, `source.path = newFontPath` is equivalent, and that `setattr` is only really needed if I'm calling `source.path` with a variable. Is that basically the distinction here?

**Comment by arrowtype** [comment]
This just came in handy. Thanks for asking this question, past me! And thanks again to Just for his help in answering it. 🤘
