### ISSUE TITLE
[subset] KeyError in EBDT table with msgothic.ttc

### ISSUE THREAD

**Issue by john45676** [fonttools/fonttools#1633]
The font is Microsoft Windows embeded font.

C:\Windows\Fonts\MS UI Gothic

Font number 0 & 1 are fine, but number 2 will subset fail. 

My command code is:
pyftsubset msgothic.ttc --text-file=XXX.txt --output-file=msgothic_subset.ttf --drop-tables= --font-number=2

Here is the message:
`    load_entry_point('fonttools==3.42.0', 'console_scripts', 'pyftsubset')()
  File "fonttools-3.42.0-py3.6.egg\fontTools\misc\loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "fonttools-3.42.0-py3.6.egg\fontTools\subset\__init__.py", line 2873, in main
    save_font(font, outfile, options)
  File "fonttools-3.42.0-py3.6.egg\fontTools\misc\loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "fonttools-3.42.0-py3.6.egg\fontTools\subset\__init__.py", line 2720, in save_font
    font.save(outfile, reorderTables=options.canonical_order)
  File "fonttools-3.42.0-py3.6.egg\fontTools\ttLib\ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "fonttools-3.42.0-py3.6.egg\fontTools\ttLib\ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "fonttools-3.42.0-py3.6.egg\fontTools\ttLib\ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "fonttools-3.42.0-py3.6.egg\fontTools\ttLib\ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "fonttools-3.42.0-py3.6.egg\fontTools\ttLib\tables\E_B_D_T_.py", line 101, in compile
    glyph = curGlyphDict[curName]
KeyError: 'uni4E0A'`

Thanks.

**Comment by anthrotype** [comment]
`EBDT` table is currently not supported by the subsetter. In fact it is included in the default list of `drop-tables`. Since you used `--drop-tables=`, you requested to not drop any the tables. The `EBDT` table is thus kept, but it fails to compile because the rest of the font was subsetted.

You want to pass the option `--passthrough-tables`, which ensures that tables which the tool doesn't know how to subset will not dropped.

**Comment by anthrotype** [comment]
> EBDT table is currently not supported by the subsetter

hm actually I am not sure about that. I see that `EBDT` is listed in `_drop_tables_default` list, however the code for subsetting the `CBDT` table (i.e. the color format version of `EBDT`) defines the `subset_glyphs` method on the parent `EBDT` class (same for CBLC vs EBLC tables).

@khaledhosny I think you touched that code recently, do you know if EBDT/EBLC are supported already or require more work?

Certainly we lack a test for them, unlike the CBDT/CBLC color counterparts.

**Comment by khaledhosny** [comment]
I haven’t touched that code directly (I only updated the documentation to match the reality). The code was written by @rsheeter AFAICT from the git log.

**Comment by anthrotype** [comment]
@khaledhosny do we need to keep `EBDT` and `EBLC` in the `_drop_tables_default` list, now that you fixed the KeyError in #1698?

**Comment by khaledhosny** [comment]
Up to you to decide. The subsetter defaults are aimed for the web where bitmap tables are not of great use IMO.

**Comment by anthrotype** [comment]
alright, let's keep like this
