### ISSUE TITLE
how does fonttools  convert xml file to woff file?

### ISSUE THREAD

**Issue by huenchao** [fonttools/fonttools#1640]
has api for it ?

**Comment by anthrotype** [comment]
by "xml file" do you mean a TTX document (the ones generated by the fonttools `ttx` command line tool)?

you can import the TTX file into a new `TTFont` instance, then set the flavor attribute to `woff` (or `woff2`), then `save` the font to a path or file.

```python
>>> from fontTools.ttLib import TTFont
>>> font = TTFont()
>>> font.importXML("path/to/my/awesome/font.ttx")
>>> font.flavor = "woff" # or "woff2"
>>> font.save("path/to/my/awesome/font.woff")
```

**Comment by anthrotype** [comment]
same can be done from the `ttx` script, by passing the ``--flavor`` option (see `ttx --help`)

**Comment by huenchao** [comment]
emm....
initially , i  have a woff file， and  i wanna add some new words for it 。
secondly,   i use fonttools to convert woff to xml , and operate xml file 。
finally , i wanna use fonttools convert xml file to woff file。

**Comment by huenchao** [comment]
> same can be done from the `ttx` script, by passing the `--flavor` option (see `ttx --help`)

emm....
initially , i  have a woff file， and  i wanna add some new words for it 。
secondly,   i use fonttools to convert woff to xml , and operate xml file 。
finally , i wanna use fonttools convert xml file to woff file。

**Comment by anthrotype** [comment]
The `ttx` tool can dump the WOFF file to xml. After you finished editing the TTX document, you can recompile it with the same `ttx` script, this time passing the `--flavor woff` option.

```sh
$ ttx MyFont.woff
# edit "MyFont.ttx" then recompile back to WOFF
$ ttx --flavor woff MyFont.ttx
# you now have a new "MyFont#1.woff" file in the same directory
```

**Comment by huenchao** [comment]
`#!/usr/bin/python
# -*- coding: UTF-8 -*-

from fontTools.ttLib import TTFont

font = TTFont('1.woff')
font.flavor = "ttx"
font.save("1.ttx")
`

**Comment by anthrotype** [comment]
not quite. If you want to save to XML you use the `font.saveXML("path/to/my/font.ttx")` method. Using your example:

```python
from fontTools.ttLib import TTFont
font = TTFont('1.woff')
font.saveXML("1.ttx")
```

**Comment by huenchao** [comment]
> ```python
> from fontTools.ttLib import TTFont
> font = TTFont('1.woff')
> font.saveXML("1.ttx")
> ```

ok, 3q~
