### ISSUE TITLE
[varLib.cffLib] Bug in merging CFF2 PrivateDicts

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#1643]
varLib.cffLib has a bug which causes the PrivateDict data from the first region font to be uses for all subsequent fonts. 

This is a serious bug. However, This bug will affect only fonts with hinting, and I think that are as yet no shipping CFF2-based fonts with hinting - Adobe hasn't made any. 

The fix is a single on line to correct the list of default data, and I have submitted a PR for it.

**Comment by madig** [comment]
So, can this be closed?
