### ISSUE TITLE
[designspaceLib] Default font not set as described in spec

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#1645]
The designspace spec (see fonttools/Doc/source/designspaceLib/) says "The source with the copyInfo flag indicates this is the default font." This matches what I have always thought, that you add the child element <info copy="1"> to a source file in order to make it be the default source font for a variation font. 

However, poking around in varLib.__init__.py::load_designspace() and experimenting with design space files shows that the default font is now set by setting the  'default' attribute of the axis elements. The source font element whose location matches the axis default attributes is set to be the default font. I am fine with this, but we then need to update the design space spec. Or am I missing something?

**Comment by anthrotype** [comment]
>  "The source with the copyInfo flag indicates this is the default font." 

I think that's a remnant from MutatorMath era. 

> The source font element whose location matches the axis default attributes is set to be the default font.

We indeed need to update the spec. The default font is the netural master, which is at default coordinate along all the axes.

**Comment by madig** [comment]
Spec has been updated: https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#82-older-versions
