### ISSUE TITLE
subset TSI tables

### ISSUE THREAD

**Issue by laerm0** [fonttools/fonttools#1657]
Question: why are TSI tables not subset? They're human-readable, so I figured this tool would have no issues subsetting them.

**Comment by khaledhosny** [comment]
FontTools does not parse any of these tables (with the exception of TSIV, but even that it has no code to write the parsed table back), so the fact they are human readable is irrelevant as they are just blobs of text as far as FontTools is concerned. I think you are highly underestimating the complexity the issue at hand.

**Comment by laerm0** [comment]
Fair enough. I honestly have no real idea of the complexity of the issue, so you're right to call me out on it.

**Comment by behdad** [comment]
Fonttools is developed by superhumans for computers, so human-readable tables pose a particular problem.

;)

**Comment by laerm0** [comment]
@behdad I knew it was a serious problem. Thoughts and prayers.

;)
