### ISSUE TITLE
bug in overlayFeatureVariations

### ISSUE THREAD

**Issue by underware** [fonttools/fonttools#1659]
Declaring two rules for the same base- and replacement-glyph generates an error in      overlayFeatureVariations.

So this:
```
<rule name="var0">
	<conditionset>
		<condition maximum="100" minimum="0" name="ANIM" />
	</conditionset>
	<sub name="a" with="a.alt1" />
</rule>
<rule name="var1">
	<conditionset>
		<condition maximum="800" minimum="600" name="ANIM" />
	</conditionset>
	<sub name="a" with="a.alt1" />
</rule>
```

Generates this error:
File ".../fontTools/varLib/featureVars.py", line 110, in overlayFeatureVariations
    key = tuple(sorted(hashdict(cleanupBox(k)) for k in key))
TypeError: '<' not supported between instances of 'hashdict' and 'hashdict'

**Comment by behdad** [comment]
I'm looking into this.

**Comment by behdad** [comment]
Reproduces with python3.

**Comment by behdad** [comment]
This is because `fontTools.misc.dictTools.hashdict` is not comparable under Python3.  It shouldn't be.  Let me try fixing on the varLib side.

**Comment by behdad** [comment]
Looks to me like this happens if two rules have the same conditions.
