### ISSUE TITLE
varLib slants transformed components in the incorrect direction for a font w/ slnt axis

### ISSUE THREAD

**Issue by thundernixon** [fonttools/fonttools#1662]
(I have searched for an existing issue on this topic, but couldn't find one. Apologies if it does exist, and I just missed it).

If a component has a mirror transformation in a variable font with a `slnt` axis, the slant occurs in the wrong direction in the output.

As a concrete example, the project [Inter](https://github.com/rsms/inter) uses a mirrored `p` for the `q` glyph, and uses a similar strategy for several other glyphs. Unfortunately, this doesn't work well for the output font:

![Kapture 2019-07-12 at 15 25 29](https://user-images.githubusercontent.com/7355414/61154519-53e78700-a4bc-11e9-9f79-bbcfd7c42654.gif)

I'm not quite sure whether the issue could be solved in varLib, or if this is purely a problem with Inter. However, if this were corrected, it would allow Inter fonts to be around 25%–45% smaller. [Here's an issue describing this](https://github.com/rsms/inter/issues/169). 

I am also making a variable font with a slant axis, so I'm really hoping to avoid this problem, one way or another. In the short term, is there anything to avoid in component tranformations? E.g., can they be rotated and slanted, so long as they are not reflected? I may end up testing this, but if someone knows the answer offhand, that would be awesome.

Is this something fixable in varLib? Are there any short-term workarounds for font designers?

**Comment by behdad** [comment]
> I am also making a variable font with a slant axis, so I'm really hoping to avoid this problem, one way or another. In the short term, is there anything to avoid in component tranformations? E.g., can they be rotated and slanted, so long as they are not reflected? I may end up testing this, but if someone knows the answer offhand, that would be awesome.

Whatever you do, the transformation will transform the slanted glyph, which most likely is not what you desire eg. for rotation.

> Is this something fixable in varLib? Are there any short-term workarounds for font designers?

I'm afraid not to both.
