### ISSUE TITLE
TTC font support 

### ISSUE THREAD

**Issue by menon92** [fonttools/fonttools#1664]
Hello, 

I'm try to run this code, 
```python
from fontTools.ttLib import TTFont
font = TTFont('path/to/font_name.ttc')
```
But, I'm getting this error, 
```bash
raise TTLibError("specify a font number between 0 and %d (inclusive)" % (numFonts - 1))
fontTools.ttLib.TTLibError: specify a font number between 0 and 3 (inclusive)
```
I works great for `ttf` font but I'm getting this error when I use `ttc` font.

Does this library support `ttc` font ? or I'm doing anything wrong.

Thanks

**Comment by miguelsousa** [comment]
`font = TTFont('path/to/font_name.ttc', fontNumber=0)`

**Comment by menon92** [comment]
**Great! It works.**

Thanks @miguelsousa

**Comment by miguelsousa** [comment]
You can also leverage `fontTools.ttLib.TTCollection` for easier access to the many fonts inside the TTC.
