### ISSUE TITLE
Invalid RegionAxisCount in varLib for single master VF's

### ISSUE THREAD

**Issue by underware** [fonttools/fonttools#1670]
Compiling a single master designspace (where the master is located at the default of the axis) generates a VF which is not sanitizing. Duplicating this master solves the problem, but is not practical. 
See also  https://github.com/googlefonts/fontmake/issues/565

**Comment by behdad** [comment]
Not sanitizing with what?  It's *their* bug :|

**Comment by behdad** [comment]
Using a null offset to varStore should also be supported IMO...
