### ISSUE TITLE
Lookup indexes dumped, but not read

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#1673]
It seems like lookup indexed are detemined by order of the lookups in the GSUB table, and not by the actual index in the attribute.

Changing this:

```xml
<GSUB>
  ... 
  <FeatureList>
    <!-- FeatureCount=1 -->
    <FeatureRecord index="0">
      <FeatureTag value="ccmp"/>
      <Feature>
        <!-- LookupCount=1 -->
        <LookupListIndex index="0" value="0"/>
      </Feature>
    </FeatureRecord>
  </FeatureList>
  <LookupList>
    <!-- LookupCount=1 -->
    <Lookup index="0">
      ...
    </Lookup>
  </LookupList>
</GSUB>
```

to this:

```xml
<GSUB>
  ... 
  <FeatureList>
    <!-- FeatureCount=1 -->
    <FeatureRecord index="0">
      <FeatureTag value="ccmp"/>
      <Feature>
        <!-- LookupCount=1 -->
        <LookupListIndex index="0" value="999"/>
      </Feature>
    </FeatureRecord>
  </FeatureList>
  <LookupList>
    <!-- LookupCount=1 -->
    <Lookup index="999">
      ...
    </Lookup>
  </LookupList>
</GSUB>
```

I would expect this to work, _or_ see a comment indicating the indexes are not used when compiling the .ttx back to a font.

**Comment by justvanrossum** [comment]
Your observation is correct, and the behavior is as designed, and I agree it's a little counter-intuitive. I'm not sure what the best solution is. I wouldn't want to litter the dump with comments. Open for suggestions.

**Comment by RoelN** [comment]
If the order of lookup tables were to simply be ordered by index value when compiling, would that cause any unwanted side effects?

```xml
<LookupList>
  <Lookup index="0">
    <!-- first -->
  </Lookup>
  <Lookup index="990">
    <!-- third -->
  </Lookup>
  <Lookup index="123">
    <!-- second -->
  </Lookup>
</LookupList>
```

**Comment by justvanrossum** [comment]
To be honest, I think the current behavior is just fine, and it's more a question of how do we communicate this better to the user.

**Comment by typoman** [comment]
I'm not sure if this would help, you can open the font using python and append the lookups to the end of LookupList and change the LookupCount. Then you need to find out how you can reference the lookups based on their index in this list.
```
from fontTools.ttLib import TTFont
f = TTFont(font_path)
print(f["GSUB"].table.LookupList.Lookup # the list of lookups)
```

**Comment by RoelN** [comment]
Maybe a comment similar to the one with `GlyphOrder`, put at the top of the `GSUB` or `LookupList` table?

```xml
<LookupList>
  <!-- A Lookup's 'index' attribute is only for humans; it is ignored when parsed. -->
  <!-- LookupCount=2 -->
  <Lookup index="0">
  ...
```

Or, as this apparently is by design and not a bug, we could leave it like it is and close this issue :-)

**Comment by justvanrossum** [comment]
Something like that could perhaps work. However, the same principle is used everywhere in the GPOS/GSUB dumps, pretty much everywhere you see `index="N"`.

**Comment by behdad** [comment]
> Or, as this apparently is by design and not a bug, we could leave it like it is and close this issue :-)

I wanted to change this to respect the index.  But then editing the XML to remove / add / reorder lookups would cause surprises to user if they don't update index...  I think commented-out index numbers are not too ugly actually.

**Comment by readroberts** [comment]
I also like to have the commented out lookup index values. Useful when I am looking at the source font sour other tools.

**Comment by justvanrossum** [comment]
Should we change
```xml
<Lookup index="0">
```
into something like:
```xml
<Lookup> <!-- index: 0 -->
```
?

**Comment by behdad** [comment]
Yes, that's what I had in mind.

**Comment by justvanrossum** [comment]
We have a similar case in CFF, although there's at least a comment that explains:

```xml
        <Subrs>
          <!-- The 'index' attribute is only for humans; it is ignored when parsed. -->
          <CharString index="0">
            -99 callgsubr
            18 -23 18 -19 rlinecurve
            -95 callgsubr
            return
          </CharString>
```

We also have some cases where we output an index that isn't useful to begin with, and probably should just be skipped, like in these `PairValueRecord` elements:
```xml
          <PairSet index="1">
            <!-- PairValueCount=3 -->
            <PairValueRecord index="0">
              <SecondGlyph value="W"/>
              <Value1 XAdvance="-10"/>
            </PairValueRecord>
            <PairValueRecord index="1">
              <SecondGlyph value="yen"/>
              <Value1 XAdvance="-15"/>
            </PairValueRecord>
            <PairValueRecord index="2">
              <SecondGlyph value="Ydieresis"/>
              <Value1 XAdvance="-15"/>
            </PairValueRecord>
          </PairSet>
```

**Comment by behdad** [comment]
True. But the otData ones are all generated by on array write XML piece of
code. So just changing that is a good start.

**Comment by behdad** [comment]
I think at this point we should just close this as not planned.

**Comment by RoelN** [comment]
Agreed, it'd be a nice to have but I imagine resources are best spent on other parts. Thanks for considering this nonetheless!
