### ISSUE TITLE
how does fonttools convert woff to ttf

### ISSUE THREAD

**Issue by shiqinying** [fonttools/fonttools#1694]

**Comment by anthrotype** [comment]
you can use the `ttx` tool to dump your WOFF font to a XML file, then again run `ttx` to compile the xml file back to a binary OpenType font.

Or via python code, you can

```python
from fontTools import ttLib

font = ttLib.TTFont("MyFont.woff")
font.flavor = None  # was "woff"; `None` restores the default value, for non-compressed OpenType
font.save("MyFont.ttf")
```

**Comment by shiqinying** [comment]
> you can use the `ttx` tool to dump your WOFF font to a XML file, then again run `ttx` to compile the xml file back to a binary OpenType font.
> 
> Or via python code, you can
> 
> ```python
> from fontTools import ttLib
> 
> font = ttLib.TTFont("MyFont.woff")
> font.flavor = None  # was "woff"; `None` restores the default value, for non-compressed OpenType
> font.save("MyFont.ttf")
> ```

thank you very much
