### ISSUE TITLE
PY2 symbol in py23?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1695]
How b/w compatible is py23 supposed to be? There used to be symbol called PY2 available, but code using it (on Py 3) currently breaks:

https://github.com/typemytype/drawbot/issues/288

**Comment by anthrotype** [comment]
Those two symbols PY2 and PY3 were not exported in `__all__`, and they are quite trivial (just checking `sys.version_info`. But I don't mind restoring them to ease transition.

**Comment by justvanrossum** [comment]
Let me discuss with @typemytype, we don't use it a lot, and we haven't released a Py2 version of DrawBot in a while now, so we might as well get rid of that code.

**Comment by justvanrossum** [comment]
We'll fix it in DrawBot. Thanks!
