### ISSUE TITLE
instancer should update name table with correct style, postscript name, etc.

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1704]
When creating an instance from a variable font, the name table is simply pruned of the dropped axes and named-instance names. However the default (legacy & preferred) style names, full name, postscript names are not updated accordingly.
The instancer should use the same names from one of the existing named instances, when the requested location matches exactly one of these.
Otherwise it should make these name up, preferably using the information present in the STAT table.

**Comment by jbmorizot** [comment]
The instancer could use the styleName in the designspace and rebuilt the name table with it.

**Comment by anthrotype** [comment]
Fixed by #2189
