### ISSUE TITLE
[subset]  the subsetter should optimize lookup types for SinglePos as well

### ISSUE THREAD

**Issue by qxliu76** [fonttools/fonttools#1709]
SingleSubst optimizes lookup format in custom "preWrite":
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/otTables.py#L725

I think we should do the same optimization for SinglePos as well

**Comment by behdad** [comment]
We can't change how ttLib reads/writes them.  Bu t can make subsetter change to different subtable indeed.  Might need slight massaging in subsetter.  We don't do things like that (changing type of an object during subsetting) currently.

**Comment by behdad** [comment]
Can use `fontTools.otLib.builder` as needed.
