### ISSUE TITLE
Strange Windows "Access is denied" error [WinError 5] for `fonttools.exe` file.

### ISSUE THREAD

**Issue by capn-freako** [fonttools/fonttools#1710]
Hi,

I'm getting the following error in response to a `conda build ...` command issued from an **Anaconda** command prompt on an up-to-date **Win7Pro** system:

```
error: [WinError 5] Access is denied: 'C:\\Users\\dbanas\\Anaconda3\\conda-bld\\chaco_1567087677622\\_h_env\\Scripts\\fonttools.exe'
```

The funny thing is if I list the contents of the directory mentioned immediately after the build failure, the `fonttools.exe` file is there! So, clearly, the build process is not actually being denied access. (Oh, unless it's _read_ access, as opposed to _write_ access, that is being denied; hmmm.)

I've tried giving several different command line options to the `conda build ...` command, including:

- `--no-locking`,
- `--no-test`, and
- `--keep-going`.

No matter what I try, I always get the same access denied error for the same file: `fonttools.exe`.

I've asked around in the _Anaconda_ community and haven't found an answer.

I'm sorry to be posting a `conda build`-related question to your _Issues_ list, but am hoping to find that, maybe, someone else has noticed strange _Windows_ OS errors centered around this file for some other, seemingly unrelated, activity.

Thanks!
-db

**Comment by behdad** [comment]
I'm afraid we cannot help with that environment setup.
