### ISSUE TITLE
ascender and ascent

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1714]
The [opentype spec ](https://docs.microsoft.com/en-gb/typography/opentype/spec/hhea) calls the first two substantive entries in the `hhea` table "`ascender`" and "`descender`". fonttools calls them "`ascent`" and "`descent`".

This was surprising! Maybe it's too late to change then but can we at least have an alias?

**Comment by justvanrossum** [comment]
The spec changed at some point, and fonttools didn't change with it. 

A pr for aliases would be good.
