### ISSUE TITLE
pytest 5.1.2 breaks tests on windonws appveyor CI

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1722]
workaround was to pin to pytest==5.1.1 (https://github.com/fonttools/fonttools/pull/1721)

we need to understand why tests were failing when using latest pytest 5.1.2 on Windows, or revert the version pinning if/when upstream issue is fixed

**Comment by behdad** [comment]
Outdated?

**Comment by anthrotype** [comment]
@behdad thanks for going through the old issues and cleaning things up along the way!
