### ISSUE TITLE
[designspaceLib] ValueError: path is on mount 'C:', start on mount 'D:'

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1735]
On Windows, the snippet below will error if the input and output paths are not in the same drive.

```python
import sys
from fontTools.designspaceLib import DesignSpaceDocument

in_path, out_path = sys.argv[1:3]

ds_doc = DesignSpaceDocument.fromfile(in_path)
ds_doc.write(out_path)
```

```
Traceback (most recent call last):
  File "save_dsdoc.py", line 7, in <module>
    ds_doc.write(out_path)
  File "fontTools\designspaceLib\__init__.py", line 1060, in write
    self.updatePaths()
  File "fontTools\designspaceLib\__init__.py", line 1114, in updatePaths
    descriptor.filename = self._posixRelativePath(descriptor.path)
  File "fontTools\designspaceLib\__init__.py", line 1065, in _posixRelativePath
    relative = os.path.relpath(otherPath, os.path.dirname(self.path))
  File "C:\Users\labuser\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:'
```

**Comment by justvanrossum** [comment]
What I think is happening is that doc.write() wants to fix all relative paths to master files, and this is not possible, as you can't create a relative path from one drive to another. Maybe you should shutil.copy() the designspace file instead?

**Comment by miguelsousa** [comment]
What about using the absolute path if the relative one can't be computed?

**Comment by justvanrossum** [comment]
As per https://github.com/LettError/designSpaceDocument, the `filename` attribute of both the `SourceDescriptor` class and the `<source>` XML element are specced as relative, this this is not possible: https://github.com/LettError/designSpaceDocument#6-notes

**Comment by miguelsousa** [comment]
OK, let me think about what can be done on our end.

The snippet is the simplest example I came up with to trigger the problem. The real scenario is happening in our test suite where a temporary designspace file ends up being saved in a different drive.

**Comment by justvanrossum** [comment]
The spec says (about source filenames) “The path can be at the same level as the document or lower”. The intention behind this is that relative pathnames that start with `../` should not be allowed. However, `designspaceLib` currently does not enforce that. (And it may be too late to change that.)

It does imply that saving a `.designspace` file to an arbitrary temp location is dubious thing to do to begin with.

**Comment by miguelsousa** [comment]
> It does imply that saving a .designspace file to an arbitrary temp location is a dubious thing to begin with.

Understood. The intention of using a proper `tempfile` location was to avoid littering the host directory with a desired subset of the original designspace file; but it's clear now that that causes problems.

Anyways, it's resolved https://github.com/adobe-type-tools/afdko/pull/976. Thanks for the feedback.

**Comment by justvanrossum** [comment]
> hm, I had missed that one. Perhaps we should just remove that clause?

And simply allow `../../../../../root/folder1/folder2/etc/etc/master.ufo`? Because that is what currently happens if you do `doc.write(tmpfile)`.

(I'm not sure either way.)

**Comment by anthrotype** [comment]
yeah..
FWIW, fontmake also uses `tempfile` to write a temporary (modified) designspace document before feeding it to MutatorMath (which only accepts paths, since it uses its own reader):
https://github.com/googlefonts/fontmake/blob/b12c53ba945ea851b13e69abfa2e7bdf2e62ee6a/Lib/fontmake/font_project.py#L91

**Comment by justvanrossum** [comment]
So, that code is currently also broken on Windows, if temp files go to a different drive than the source :)
