### ISSUE TITLE
unicodedata.ot_tag_to_script: returns None for "math"

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#1737]
The function `ufo2ft.featureWriters.ast.getScriptLanguageSystems` determines the OT tag for scripts, but `unicodedata.ot_tag_to_script` does not seem to have a script name for `math`. 

The font https://github.com/madig/DejaVu-Font-Sandbox/tree/master/sources/cubic/DejaVuSans.ufo happens to have some GSUB features dealing with math glyphs, with this declaration at the top: `languagesystem math dflt;` (see https://github.com/madig/DejaVu-Font-Sandbox/blob/master/sources/cubic/DejaVuSans.ufo/features.fea).

According to https://en.wikipedia.org/wiki/Script_(Unicode)#List_of_scripts_in_Unicode, `ot_tag_to_script` should return ISO 15924's `Zmth`, even though this isn't an official script in Unicode? Or should it return something else? Or should ufo2ft do something different?

**Comment by wollmers** [comment]
It should use the script tags of the OpenType Specification wich include `math`. https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags

**Comment by behdad** [comment]
`Zmth` is correct.

**Comment by wollmers** [comment]
@behdad 
> `Zmth` is correct.

"Correct" regarding to which reference? In this case we have 3 conflicting standards, e.g. for 

```
$ uni print U+1D400
     cpoint  dec    utf-8       html       name
'𝐀'  U+1D400 119808 f0 9d 90 80 &#x1d400;  MATHEMATICAL BOLD CAPITAL A (Uppercase_Letter)
````

- OpenType: `math`
- [ISO 15924](https://www.unicode.org/iso15924/codechanges.html): `Zmth`
- Unicode: `Zyyy` Code for undetermined script = Common

A usual solution would be to define both `math` (as alias, maybe with with a deprecation warning) and `Zmth`.

`Zyyy` makes no sense in font context.

IMHO OpenType should review their specification and deprecate `math` in favour of `Zmth`.

**Comment by behdad** [comment]
> > `Zmth` is correct.
> 
> "Correct" regarding to which reference?

I mean, the return value of `unicodedata.ot_tag_to_script` for `math` should be `Zmth`. That's what HarfBuzz uses.

**Comment by behdad** [comment]
@madig does this work for you:
```diff
diff --git a/Lib/fontTools/unicodedata/OTTags.py b/Lib/fontTools/unicodedata/OTTags.py
index a9d8cd1ce..ba25cfba1 100644
--- a/Lib/fontTools/unicodedata/OTTags.py
+++ b/Lib/fontTools/unicodedata/OTTags.py
@@ -22,6 +22,7 @@ SCRIPT_EXCEPTIONS = {
     "Yiii": "yi  ",
     "Nkoo": "nko ",
     "Vaii": "vai ",
+    "Zmth": "math",
     "Zinh": DEFAULT_SCRIPT,
     "Zyyy": DEFAULT_SCRIPT,
     "Zzzz": DEFAULT_SCRIPT,
```

**Comment by madig** [comment]
It probably would 👀
