### ISSUE TITLE
OpenType Font Variation Using fontTools

### ISSUE THREAD

**Issue by AlirezaAlipour** [fonttools/fonttools#1744]
How can I implement Open Type Font Variation for a type project using fontTools' libraries in Python?

**Comment by AlirezaAlipour** [comment]
The ["interpolate.py"](https://github.com/fonttools/fonttools/blob/master/Snippets/interpolate.py) in the ["Snippets"](https://github.com/fonttools/fonttools/tree/master/Snippets) directory is a good sample for Open Type Font Variation.

**Comment by behdad** [comment]
We should remove Snippets/interpolate.py I think.  That's from way before varLib.

**Comment by behdad** [comment]
You should look into fontmake.
