### ISSUE TITLE
Writing coordinates to CFF glyph

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1745]
I can read a set of coordinates from a CFF glyph using a RecorderPen. What is the best/right way to write them back into a CFF glyph? Is there an example for this?

**Comment by justvanrossum** [comment]
With `T2CharStringPen`.

**Comment by simoncozens** [comment]
Thanks, that's a helpful pointer. And then I can write the returned charstring into the font with something like `font.["CFF "].cff.topDictIndex[0].CharStrings["g"]`? Would that work?

**Comment by justvanrossum** [comment]
It's a bit messy. Have a look how `fontBuilder.py` deals with it, perhaps that can point you in the right direction.

**Comment by typoman** [comment]
You can get the private dictionary and reuse in the pen:

```
fontname = cff.keys()[0]
cff = otf["CFF "].cff
cffFont = cff[fontname]
cffFont.decompileAllCharStrings()
globalSubrs = cff.GlobalSubrs
topDict = cffFont
private = cffFont.Private
charStrings = cffFont.CharStrings
charStringsIndex = cffFont.CharStrings.charStringsIndex
strings = cffFont.strings
```

**Comment by simoncozens** [comment]
That's it, thank you! Would you believe what I was missing was the capital P in `Private`.

**Comment by ivangrozny** [comment]
Hi @simoncozens did you manage to do it without `FontBuilder.py` ? Would you like to share your code ? I don't understand the private dict stuff... I'm stuck here : `font.["CFF "].cff.topDictIndex[0].CharStrings["g"] = pen.getCharString()`

**Comment by simoncozens** [comment]
This was four years ago. I'm sorry, I can't remember what I was doing at the time or where to look.

**Comment by ivangrozny** [comment]
oh ok, I've open a [discussions](https://github.com/fonttools/fonttools/discussions/3267), hope this will lead to something !
