### ISSUE TITLE
basePen.py Assertion Error

### ISSUE THREAD

**Issue by aaronbell** [fonttools/fonttools#1755]
I'm trying to run ufo2ft.compileTTF and am running into this really irritating error:

```
Traceback (most recent call last):
  File "build.py", line 74, in <module>
    instance_font_nf = ufo2ft.compileTTF(instanceNF, removeOverlaps=True, inplace=True)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 195, in compileTTF
    glyphSet = preProcessor.process()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/preProcessor.py", line 49, in process
    func(ufo, glyphSet)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/filters/__init__.py", line 219, in __call__
    if include(glyph) and filter_(glyph):
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/filters/removeOverlaps.py", line 50, in filter
    self.union(contours, pen)
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/booleanOperationManager.py", line 101, in union
    return _performOperation("union", contours, [], outPen)
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/booleanOperationManager.py", line 70, in _performOperation
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/booleanOperationManager.py", line 70, in <listcomp>
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/flatten.py", line 69, in __init__
    self.segments = _convertPointsToSegments(points)
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/flatten.py", line 441, in _convertPointsToSegments
    willBeReversed=willBeReversed
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/flatten.py", line 171, in __init__
    for pt1, pt2 in decomposeQuadraticSegment(pointCoordinates[1:]):
  File "/usr/local/lib/python3.7/site-packages/fontTools/pens/basePen.py", line 359, in decomposeQuadraticSegment
    assert n > 0
AssertionError
```

I've tried cleaning up the original UFO quite a bit, and even round-tripped an exported OTF through TTX to see if that process would catch any problems (it didn't). Any ideas what might be causing this? Thanks!

**Comment by justvanrossum** [comment]
Try with `removeOverlaps=False`; _or_ add the option `overlapsBackend="pathops"`.

It looks like it's an issue with booleanOperations support for quadratics.

**Comment by aaronbell** [comment]
Thanks @justvanrossum! Setting 'removeOverlaps=False' resolved it. Wonder why booleanOperations was having such a problem with the outlines :/

**Comment by justvanrossum** [comment]
> Wonder why booleanOperations was having such a problem with the outlines 

I suspect that its support for quadratics is buggy.

**Comment by justvanrossum** [comment]
Looking through booleanOperations sources: _or_ it could be you have a "qcurve" segments in your source file with _zero_ preceding off curve points. Would be interesting to know whether that is the case.

**Comment by aaronbell** [comment]
The issue is coming from a third party font source that I'm trying to work with. It was in quadratic format, and I converted the entire thing to cubics to do some cleanup. Also figured it'd be easier to merge in with my existing cubic work. Not sure if that gives you any more info. 

What does 'qcurve' refer to? Quadratic?

**Comment by justvanrossum** [comment]
Yeah, "qcurve" is the segment type of a quadratic curve segments in a UFO.

Your error message suggests the source (or at least one glyph) is in quadratics format.

**Comment by justvanrossum** [comment]
(Wait, I'm not sure I can say that so confidently: there is probably a cubic to quadratic converter (cu2qu) involved in the process.)

You probably can't share the source UFO with me privately to investigate?

**Comment by aaronbell** [comment]
Yeah, I looked through and didn't find any qcurves.

No problem. I'll email you the UFO that you can take a look at.

**Comment by justvanrossum** [comment]
Hm, I can't reproduce it with the latest fontmake/ufo2ft. Can you try to upgrade?

**Comment by justvanrossum** [comment]
My build script is this:
```python
from defcon import Font
import ufo2ft

path = "YourFont.ufo"
ufo = Font(path)

ttf = ufo2ft.compileTTF(ufo, removeOverlaps=True, inplace=True)
```

I assume that's equivalent to what you're doing.

**Comment by aaronbell** [comment]
I have ufo2ft version 2.9.1, which looks like the latest. 

The difference in my code is that I'm loading the UFO in via ufolib2 (rather than defcon). Maybe that's the weak link?

**Comment by justvanrossum** [comment]
Hm, can't reproduce with ufoLib2, either. My booleanOperations is at version 0.8.2.

**Comment by aaronbell** [comment]
Same. Strange. Well, maybe it is just me :/. 

In any case, I'm able to get the result I was aiming for even without booleanOperations', so I'm OK with that. Thanks for helping Just!
