### ISSUE TITLE
why is Symbol cmap (3, 0) classified as isUnicode()?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1760]
the cmap OT spec lists "Symbol" (platform=3, platEncId=0) among the "other non-Unicode encodings":

https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#windows-platform-platform-id--3 

but isUnicode() method of cmap subtable includes Symbol among the Unicode subtable:

https://github.com/fonttools/fonttools/blob/4e9fa7a44c13f4adb88c67f1c1751d2cbc788949/Lib/fontTools/ttLib/tables/_c_m_a_p.py#L210-L215

I wonder why that's the case?

**Comment by anthrotype** [comment]
Ah, I found this commit with git blame:

https://github.com/fonttools/fonttools/commit/4e616d2f7fac5101c30135dba0fb9fd4a379b7d0

> Accept MS Symbol cmap tables as Unicode-compatible
> Apparently these days these tables are used to encode symbols in
> PUA, so they are still Unicode-compatible...
> This follows a similar change in fontconfig.

**Comment by twardoch** [comment]
That's correct. The 3.0 fonts (TTF only) these days generate PUA. This used
to be different. But these days, cmap 3.0 TTFs can be considered a
simplified keyboard access method to the U+F020–U+F0FF Unicode characters.

**Comment by anthrotype** [comment]
thanks!
