### ISSUE TITLE
How to get font name using fonttools?

### ISSUE THREAD

**Issue by RomulBY** [fonttools/fonttools#1764]
Hello.
Is it possible to get a PostScript font name use Python and fonttools?

Ideally, I would like to extract all the internal names - "Full name", "Family name", "Subfamily name" and "Postscript name".

**Comment by justvanrossum** [comment]
```python
from fontTools.ttLib import TTFont

p = ...path to otf/ttf/woff/etc...

f = TTFont(p)
nameTable = f["name"]
psName = nameTable.getName(6, 3, 1)  # ps name, windows, unicode
if psName is not None:
    psName = str(psName)
```
Check https://docs.microsoft.com/en-us/typography/opentype/spec/name for details about the numbers supplied to `getName()`.
