### ISSUE TITLE
Is it possible to create bitmap array of every symbol in font? 

### ISSUE THREAD

**Issue by vega0** [fonttools/fonttools#1769]

**Comment by justvanrossum** [comment]
Not out of the box, and since fonttools isn't really a rasterizer this would be out of scope.

**Comment by m4rc1e** [comment]
Use [freetype-py](https://github.com/rougier/freetype-py). Here's an example to output a sentence, https://github.com/rougier/freetype-py/blob/master/examples/hello-world.py.
