### ISSUE TITLE
AAT tables support: kern (format > 0), feat, mort, morx, ...)

### ISSUE THREAD

**Issue by olivierberten** [fonttools/fonttools#178]
Since it is the easiest one, I started with the `feat` table but Apple seems to have added undocumented data between the _Feature name array_ and the _Setting name array_... Has anybody heard about it? The new spec doesn't bring anything new...

**Comment by behdad** [comment]
Supporting mort/morx and more complex kern/kerx tables is a huge task. I don't see a point keeping an issue open for it.
