### ISSUE TITLE
[ufoLib/glifLib] .glif parser does not accept XML comments

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1784]
I just noticed that if a `.glif` file contains an XML comment, the data is rejected by `ufoLib.glifLib`. The following snippet causes an error:

```python
from fontTools.ufoLib.glifLib import readGlyphFromString

s = """<?xml version='1.0' encoding='UTF-8'?>
<glyph name="A" format="2">
  <advance width="1290"/>
  <unicode hex="0041"/>
  <!-- a comment -->
</glyph>
"""

class Glyph:
    pass

g = Glyph()
readGlyphFromString(s, g)
```
Exception:
`fontTools.ufoLib.errors.GlifLibError: Unknown element in GLIF: <!-- a comment -->`

I bet this is unintentional.

(Note that I don't really mind this behavior, I just wanted it to be recorded.)

**Comment by anthrotype** [comment]
I think we should let them through.
I believe this only happens when using lxml. The built-in etree doesn't parse the comments.
With lxml one can check if an element is a comment by doing `element.tag is etree.Comment`.

**Comment by anthrotype** [comment]
or we can use custom `XMLParser(remove_comments=True)` as documented in https://lxml.de/parsing.html -- but this is lxml specific I think
