### ISSUE TITLE
OTF to TTX from the Python program?

### ISSUE THREAD

**Issue by RomulBY** [fonttools/fonttools#1789]
How to convert font (OTF or TTF) to TTX and save to a *.ttx-file inside a program in Python?

Sorry, but I did not find the answer to this simple question.

**Comment by justvanrossum** [comment]
Something like this should work:

```python
from fontTools.ttLib import TTFont

p = "path/to/my/font.otf"

with TTFont(p) as f:
    f.saveXML(p + ".ttx")
```
