### ISSUE TITLE
[designspaceLib] opening and saving a designspace looses postscript names

### ISSUE THREAD

**Issue by benkiel** [fonttools/fonttools#1791]
Opening a designspace file with designspaceLib and then saving it seems to loose the `postScriptFontName`, `styleMapFamilyName`, and `styleMapStyleName` for instances.

**Comment by benkiel** [comment]
Ok, a quick test shows what's going on:

The documentation says the attributes are camelcase (i.e. `postScriptFontName`, `styleMapFamilyName`, and `styleMapStyleName`), but if they are so in the designspace file, they are thrown away. Only `postscriptfontname`, `stylemapfamilyname`, and `stylemapstylename` works.

Either the docs should be updated, or behavior changed. I don't know which.

**Comment by justvanrossum** [comment]
The have to be lowercase in the XML, and they are camelcase as attributes on the Python objects. I think that's what https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib says, but let us know if you think it can be made clearer.

**Comment by justvanrossum** [comment]
Unknown XML attributes are apparently ignored, so that should explain why they disappear if misspelled.

**Comment by benkiel** [comment]
@justvanrossum You are correct, it's clearly documented, but I'm going to put in a PR for the scripting file that notes this, just so folks don't get confused (as apparently some have)

**Comment by benkiel** [comment]
Clarified and closed in #1792
