### ISSUE TITLE
Enable LGTM.com analysis on PRs

### ISSUE THREAD

**Issue by josh-hadley** [fonttools/fonttools#1798]
Hi fonttools folks,

LGTM (AKA Semmle) is a free-for-open-source code analysis service, recently acquired by GitHub. It has [already been running an analysis on the fonttools codebase](https://lgtm.com/projects/g/fonttools/fonttools/history/) (among many other open source projects), and has identified lots of alerts of varying severity. In [adobe-type-tools](https://github.com/adobe-type-tools)-land, we've been running LGTM on [AFDKO](https://lgtm.com/projects/g/adobe-type-tools/afdko/?mode=tree) and [psautohint](https://lgtm.com/projects/g/adobe-type-tools/psautohint/?mode=tree) Pull Requests  for a few months now, and have been very pleased with the results. It has identified many potential issues that would not likely have been picked up by our test suite.

I propose enabling LGTM's analyze-on-PR for fonttools/fonttools repo as well. It's a fairly unobtrusive check, not too chatty, and does not block merging (it's informational-only). And addressing the existing [backlog of alerts](https://lgtm.com/projects/g/fonttools/fonttools/?mode=list) might be a good way for folks to contribute to the project and get familiar with the codebase.

See https://lgtm.com/ for more info.

**Comment by josh-hadley** [comment]
With help from @anthrotype , LGTM analyze-on-PR is now active! Thanks, Cosimo!

**Comment by anthrotype** [comment]
I think this LGTM bot is a bit too noisy. I'm constantly distracted by its notifications or when I am reading the PR messages. Would it be possible to only have its checks in the PR's "Checks" tab but not also have it spam the main PR's message board?

**Comment by justvanrossum** [comment]
I agree, it's too noisy.

**Comment by josh-hadley** [comment]
Comments on PRs can be disabled [here](https://lgtm.com/projects/g/fonttools/fonttools/ci/) by repo owners (which I'm currently not). If you can make me owner long enough to disable it I'll change the setting, or an owner can do it.

**Comment by anthrotype** [comment]
I just deactivated them. Thanks Josh
