### ISSUE TITLE
[interpolatable] fails to detect bad contours with wrong starting point

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1801]
Running `fonttools varLib.interpolatable` tool on the set of master TTFs generated from NotoRashiHebrew-MM.glyphs source (from noto-source repo) does not detect this interpolation issue, where the starting point on a contour is different across master but the contours have the correct order and the same number and type of segments, leading to this rendering issue:

![ezgif-6-3a4fd6acd4c0](https://user-images.githubusercontent.com/6939968/72394789-41107200-36ec-11ea-9238-33d453fed4a8.gif)

Here are the files to repro:
[NotoRashiHebrew-interpolatable-issue.zip](https://github.com/fonttools/fonttools/files/4062492/NotoRashiHebrew-interpolatable-issue.zip)

Question (mainly for @behdad): was the interpolatable.py intentended to spot these sort of issues? If not, can/should it be extended to detect these?

**Comment by behdad** [comment]
So far my code only detects wrong order of components. Same algorithm should also be run against points of each contour.

**Comment by anthrotype** [comment]
Can this be closed after #2571?

**Comment by behdad** [comment]
Yes.
