### ISSUE TITLE
error: in __getitem__     return self.metrics[glyphName] KeyError: 'A'

### ISSUE THREAD

**Issue by peterennis** [fonttools/fonttools#1804]
Using this as a reference: https://groups.google.com/forum/#!topic/fonttools/ll4G3dOrDBc

I have this py script:

```
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

font = TTFont("./Center-Point-2026.ttf")
glyphSet = font.getGlyphSet()
svgpen = SVGPathPen(glyphSet)
glyph = glyphSet["A"]
glyph.draw(svgpen)
path = svgpen.getCommands()
print(path)
```

It is run against the a ttf I am developing.

Result:

```
C:\ae\adaept.com\ae-pytools>python .\ae-outglyph.py
Traceback (most recent call last):
  File ".\ae-outglyph.py", line 7, in <module>
    glyph = glyphSet["A"]
  File "C:\Users\peter\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fontTools\ttLib\ttFont.py", line 717, in __getitem__
    horizontalMetrics = self._hmtx[glyphName]
  File "C:\Users\peter\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fontTools\ttLib\tables\_h_m_t_x.py", line 136, in __getitem__
    return self.metrics[glyphName]
KeyError: 'A'

C:\ae\adaept.com\ae-pytools>
```

GitHub will not allow me to attach the file.

What is the next step in this process?

Windows 10 x64

```
C:\ae\adaept.com\ae-pytools>python --version
Python 3.8.0
```

Using fonttools 4.2.4

**Comment by justvanrossum** [comment]
You can attach the font as a zip file.

**Comment by anthrotype** [comment]
Does your font contain a glyph named "A"?

**Comment by justvanrossum** [comment]
> Does your font contain a glyph named "A"?

It doesn't, the font doesn't contain a proper post table with glyph names it seems.

**Comment by peterennis** [comment]
The font was created using glyphter.com

How do I make it have a "proper post table"?

**Comment by behdad** [comment]
See this for how to correctly get the glyph index for character "A":
https://github.com/fonttools/fonttools/blob/cdc5307d1b0110271dab45d79319c28bd4d08066/Lib/fontTools/pens/svgPathPen.py#L216-L217
