### ISSUE TITLE
[otData] how to handle Count value appearing after the array?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1812]
I'm trying to convert `COLR` table to `otData`-style class. Here's is what I've got so far:

```python
	('COLR', [
		('uint16', 'Version', None, None, 'Table version number (starts at 0).'),
		('uint16', 'BaseGlyphRecordCount', None, None, 'Number of Base Glyph Records.'),
		('LOffsetTo(BaseGlyphRecordArray)', 'BaseGlyphRecordArray', None, None, 'Offset (from beginning of COLR table) to Base Glyph records.'),
		('LOffsetTo(LayerRecordArray)', 'LayerRecordArray', None, None, 'Offset (from beginning of COLR table) to Layer Records.'),
		('uint16', 'LayerRecordCount', None, None, 'Number of Layer Records.')
	]),

	('BaseGlyphRecordArray', [
		('BaseGlyphRecord', 'BaseGlyph', 'BaseGlyphRecordCount', 0, 'Base Glyph records.'),
	]),

	('BaseGlyphRecord', [
		('GlyphID', 'BaseGlyphID', None, None, 'Glyph ID of reference glyph. This glyph is for reference only and is not rendered for color.'),
		('uint16', 'FirstLayerIndex', None, None, 'Index (from beginning of the Layer Records) to the layer record. There will be numLayers consecutive entries for this base glyph.'),
		('uint16', 'NumLayers', None, None, 'Number of color layers associated with this glyph.'),
	]),

	('LayerRecordArray', [
		('LayerRecord', 'Layer', 'LayerRecordCount', 0, 'Layer records.'),
	]),

	('LayerRecord', [
		('GlyphID', 'LayerGlyphID', None, None, 'Glyph ID of layer glyph (must be in z-order from bottom to top).'),
		('uint16', 'PaletteIndex', None, None, 'Index value to use with a selected color palette.'),
	]),

```

The problem I have is that in COLR table the count value which tells how many records are in the LayerRecordArray only comes _after_ the offset to the LayerRecordArray.
See `numLayerRecords` in https://docs.microsoft.com/en-us/typography/opentype/spec/colr#header

But the assumption in otBase is that count fields always **precede** the actual arrays they are counting, whereas in the case of COLR, the layer count comes after the layers array (i.e. after its offset, but Offset converters are decompiled to the Table they point to).
I believe -- though I'm not 100% sure -- this is the reason why I get the following error when I try to decompile the table:

```
~/Github/fonttools/Lib/fontTools/ttLib/tables/otBase.py in decompile(self, reader, font)
    631                                         if conv.aux and not eval(conv.aux, None, table):
    632                                                 continue
--> 633                                         table[conv.name] = conv.read(reader, font, table)
    634                                         if conv.isPropagated:
    635                                                 reader[conv.name] = table[conv.name]

~/Github/fonttools/Lib/fontTools/ttLib/tables/otConverters.py in read(self, reader, font, tableDict)
    534                         table.font = font
    535                 else:
--> 536                         table.decompile(reader, font)
    537                 return table
    538 

~/Github/fonttools/Lib/fontTools/ttLib/tables/otBase.py in decompile(self, reader, font)
    625                                         else:
    626                                                 # conv.repeat is a propagated count
--> 627                                                 countValue = reader[conv.repeat]
    628                                         countValue += conv.aux
    629                                         table[conv.name] = conv.readArray(reader, font, table, countValue)

~/Github/fonttools/Lib/fontTools/ttLib/tables/otBase.py in __getitem__(self, name)
    213 
    214         def __getitem__(self, name):
--> 215                 return self.localState and self.localState[name]
    216 
    217         def __contains__(self, name):

KeyError: ('LayerRecordCount', 'Layer', 'LayerRecordArray')
```

Any suggestions how to work around this? Perhaps, would I need to define a custom subclass of `BaseTable` in `otTables` module for the `COLR` table, that in the `decompile` method would somehow get the `LayerRecordCount` before decompiling the `LayerRecordArray`?

**Comment by khaledhosny** [comment]
No answer to your question, but would such a change be backward compatible? I have a few scripts here and there that create/manipulate COLR/CPAL tables using fonttools.

**Comment by anthrotype** [comment]
@khaledhosny right.. Maybe I could make so that the change isn't backward incompatible. The ttLib classes can keep the same interface but would use the otData classes underneath. The reason I want to port them to data-driven apprach is to make it easier to experiment with @behdad's COLRv1 proposal (with gradients)

**Comment by anthrotype** [comment]
my current workaround is to seek to LayerRecordCount and store that in the reader's internal state, then call the superclass' BaseTable.decompile...

```diff
diff --git a/Lib/fontTools/ttLib/tables/otTables.py b/Lib/fontTools/ttLib/tables/otTables.py
index 302c9b2f..decd88ef 100644
--- a/Lib/fontTools/ttLib/tables/otTables.py
+++ b/Lib/fontTools/ttLib/tables/otTables.py
@@ -1152,6 +1152,15 @@ class LigatureSubst(FormatSwitchingBaseTable):
                        ligs.append(lig)
 
 
+class COLR(BaseTable):
+
+       def decompile(self, reader, font):
+               subReader = reader.getSubReader(offset=12)
+               conv = self.getConverterByName("LayerRecordCount")
+               reader[conv.name] = conv.read(subReader, font, {})
+               return BaseTable.decompile(self, reader, font)
+
+
 # For each subtable format there is a class. However, we don't really distinguish
 # between "field name" and "format name": often these are the same. Yet there's
 # a whole bunch of fields with different names. The following dict is a mapping
```

**Comment by justvanrossum** [comment]
+1 for API compatibility.

**Comment by behdad** [comment]
I don't have a good answer here.  Except that maybe we can hack this table to load some things using custom otData code and then move them to the existing table strructure, and do that again preWrite.

**Comment by rsheeter** [comment]
Can we change otData to read the entire local record (COLR here) before it follows offsets? - the count would then be available.

**Comment by behdad** [comment]
> Can we change otData to read the entire local record (COLR here) before it follows offsets? - the count would then be available.

That's generally not done because items can be variable-length and need to be parsed in order.  In this case is doable since an offset is fixed-length.  It just disrupts the generic reading algorithm.

**Comment by rsheeter** [comment]
Assuming LOffsetTo is a fixed width offset I would have thought Cosimo's metadata sufficient for a generic parser to successfully read the table. I would imagine modifying otData to defer resolution of offset items until we either reach their offset or finish the current records inline fields. Is this plausible?

**Comment by behdad** [comment]
> Assuming LOffsetTo is a fixed width offset I would have thought Cosimo's metadata sufficient for a generic parser to successfully read the table. I would imagine modifying otData to defer resolution of offset items until we either reach their offset or finish the current records inline fields. Is this plausible?

If that was the only problem, we could find a way around it.  But there seem to be bigger questions here.

**Comment by behdad** [comment]
Close this?

**Comment by behdad** [comment]
The COLRv1 usecase is out of the way. Closing this until we need it again.
