### ISSUE TITLE
How to replace a range of character with space?

### ISSUE THREAD

**Issue by yingshaoxo** [fonttools/fonttools#1813]
The range is 4E00-9FA5

**I have used the following way to do that, it's not working:**

## Export ttx table from ttf

```python
from fontTools.ttLib import TTFont

font = TTFont('droid.ttf')
font.saveXML("ttx.xml")
```

## Replace all chinese characters to space

```python
import xml.dom.minidom
import pprint
```

```python
doc = xml.dom.minidom.parse("ttx.xml")
```

```python
print(doc.firstChild.tagName)
pprint.pprint(doc.firstChild.childNodes[:3])
```

    ttFont
    [<DOM Text node "'\n\n  '">,
     <DOM Element: GlyphOrder at 0x7f1535cd2800>,
     <DOM Text node "'\n\n  '">]

```python
elements = doc.getElementsByTagName("GlyphID")
print(len(elements))
print(elements[3])
print(elements[3].getAttribute("id"))
print(elements[3].getAttribute("name"))
```

    43681
    <DOM Element: GlyphID at 0x7f1535cd2c28>
    3
    space

```python
def in_range(hex_string):
    return int("4e00", 16) <= int(hex_string, 16) <= int("9fa5", 16)
```

```python
# The chinese character range is 4E00-9FA5
for element in elements:
    name = element.getAttribute("name")
    if len(name) == 7 and name[:3] == "uni" and in_range(name[3:]):
        element.setAttribute("id", "3")
```

```python
elements = doc.getElementsByTagName("map")
for element in elements:
    name = element.getAttribute("name")
    if len(name) == 7 and name[:3] == "uni" and in_range(name[3:]):
        element.setAttribute("code", "0x20")
```

```python
doc.writexml(open("new_ttx.xml", "w"))
```

## Convert it back to TTF

```python
!rm nomorechinese.ttf

!ttx new_ttx.xml

!mv new_ttx.ttf nomorechinese.ttf
```

    rm: cannot remove 'nomorechinese.ttf': No such file or directory
    Compiling "new_ttx.xml" to "new_ttx.ttf"...
    Parsing 'GlyphOrder' table...
    Parsing 'head' table...
    Parsing 'hhea' table...
    Parsing 'maxp' table...
    Parsing 'OS/2' table...
    Parsing 'hmtx' table...
    Parsing 'cmap' table...
    Parsing 'fpgm' table...
    Parsing 'prep' table...
    Parsing 'cvt ' table...
    Parsing 'loca' table...
    Parsing 'glyf' table...
    Parsing 'kern' table...
    Parsing 'name' table...
    Parsing 'post' table...
    Parsing 'gasp' table...

```

**Comment by arrowtype** [comment]
Hi @yingshaoxo, are you trying to map a bunch of unicodes to the `space` glyph?

This issue may be helpful

**Comment by yingshaoxo** [comment]
> Hi @yingshaoxo, are you trying to map a bunch of unicodes to the `space` glyph?
> 
> This issue may be helpful to you:
> 
> [# 1867 – Question: Is there a way to give a glyph multiple unicodes with TTFont?](https://github.com/fonttools/fonttools/issues/1867)

Yes, that's exactly what I want to do. I'll give it a look and do some experiments with it. Thanks a lot.

**Comment by yingshaoxo** [comment]
@arrowtype 

Sorry to disturb you, but here's the result, even if I replaced all characters to `space`, the ttf file I generated by `ttx ttx.xml` is still the same, no effect at all.

[ttx.zip](https://github.com/fonttools/fonttools/files/4407572/ttx.zip)
