### ISSUE TITLE
[fealib] lookup flag ignored if it's declared before a script statement

### ISSUE THREAD

**Issue by typoman** [fonttools/fonttools#1824]
In the following lookup, the lookup flag will be ignored which is different from FDK. In FDK it's not ignored.
```fea
    lookup rlig_arab_0 {
        lookupflag RightToLeft IgnoreMarks;
        script arab;
        sub arAlef arLamPF.i arLamPF.m arHehPF.f by arAllah;
    } rlig_arab_0;
```
But if I move the flag after the script statement, it will be taken:
```fea
    lookup rlig_arab_0 {
        script arab;
        lookupflag RightToLeft IgnoreMarks;
        sub arAlef arLamPF.i arLamPF.m arHehPF.f by arAllah;
    } rlig_arab_0;
```
This is not a major issue as long as the user knows about this difference. I had a situation that I couldn't find an explanation why my lookup flag is ignored in fontmake but not in makeotf.

**Comment by khaledhosny** [comment]
`script` and `language` are not allowed in standalone lookups per the spec.

**Comment by khaledhosny** [comment]
Assuming this is a nested lookup block (i.e. inside a feature block), the [spec says](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#4.d):
> The lookupflag attribute stays the same until explicitly changed, until a lookup reference statement is encountered that changes it, until the script is changed, or until the end of the feature.

So we need a complete test, it might be that the script is not changing (the current script is `arab` already), makeotf not actually following the spec.

**Comment by typoman** [comment]
Thank you Khaled, this was a nested lookup as you described. I can send you the UFO file to your email for your testing.

**Comment by khaledhosny** [comment]
> I can send you the UFO file to your email for your testing.

Yes, please.

**Comment by typoman** [comment]
I just send you the file to your email, please let me know if you've received it or not.

**Comment by khaledhosny** [comment]
Sorry for the delay, I got the files, and I checked what makeotf is doing, but got distracted. Will make a PR soon.

**Comment by khaledhosny** [comment]
https://github.com/fonttools/fonttools/pull/1883 should fix the output to match makeotf's, but note that the first rlig lookup will still have its lookup flags reset (in both makeotf and feaLib) because the current script is different from the new one. Since all lookups in your rlig feature use the same script, you should set it outside the lookup blocks instead (also `RightToLeft` has effect only on cursive attachment lookups, it is ignored by layout engines for all other lookups, so you don’t need to set it).

**Comment by typoman** [comment]
Thank You Khaled, noted! Just for the reference I didn't write the feature, it's taken from an auto-generated feature of Glyphs app.

**Comment by khaledhosny** [comment]
Allowing script and language statement inside nested lookups was really a bad idea, they are also feature-global and will affect subsequent lookups as well.

**Comment by justvanrossum** [comment]
I'm still running into this in 2024: a wrongly placed script statement causes the lookupflag to be ignored, causing a silently broken font. Can we perhaps issue a warning in this case?

Or do we say, "thanks Glyphs", shrug, and move on?

**Comment by anthrotype** [comment]
> a wrongly placed script statement (in a feature generated by Glyphs) causes the lookupflag to be ignored, causing a silently broken font

isn't that a Glyphs.app bug then?

**Comment by anthrotype** [comment]
> Can we perhaps issue a warning in this case?

maybe yes
