### ISSUE TITLE
Missing the downloadable artifact for v4.4.1

### ISSUE THREAD

**Issue by chenrui333** [fonttools/fonttools#1840]
Hi, it seems for the latest release (v4.4.1), it does not have the zip downloadable artifact.

**Comment by anthrotype** [comment]
Thanks. I don't know what's happening with Travis, but the 3.6 build is not running anymore (and the deployment was happening on that build). I don't think we changed anything on our side. 
I will publish the wheel and sdist package manually for this release and will debug this before the next update.

**Comment by anthrotype** [comment]
here https://pypi.org/project/fonttools/4.4.1/

**Comment by anthrotype** [comment]
i think I got it working again

**Comment by chenrui333** [comment]
Sounds good!!
