### ISSUE TITLE
Snippet to add a glyph to an OT-CFF font?

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1841]
Is there a snippet to add a glyph to an OT-CFF font (CFF, cmap, etc.) from a source UFO?

Something like add a CFFGlyph to the glyphset, get a pen, draw the glyph from the UFO to the pen …

I know that something like this could be pieced together from ufo2ft, but that builds a whole font, and I just would like to add a single glyph to an existing font without changing too much.

**Comment by khaledhosny** [comment]
Check the `fontBuilder` module, I used it together with glyphsLib to build fonts from Glyphs files, and UFO (say defcon) should be even simpler.
