### ISSUE TITLE
How to get the unicode of glyph in otf?

### ISSUE THREAD

**Issue by wizardk** [fonttools/fonttools#1845]
Hi,

In ttf and ttc, I can get the unicode of glyph from it's name such as 'uniXXXX'.
But in otf, the glyph's name is 'cidXXXX' and it's just an ID, not unicode.

**Comment by justvanrossum** [comment]
You need to go the other way around, via the `cmap` table.

**Comment by twardoch** [comment]
Note that one glyph can be mapped to multiple Unicode alternative codepoints. The relevant cmap subtable is 3.10, in its absence 3.1, in its absence 0.3, and finally 3.0 (which always points to the PUA).

**Comment by justvanrossum** [comment]
And if you're using code, the easiest way is to use `cmap = font.getBestCmap()`, which gives you a dictionary mapping code points to glyph names.

**Comment by wizardk** [comment]
@twardoch Thanks.

@justvanrossum Thanks. I'will use the font.getBestCmap().keys() to find out the supported charset of font.
