### ISSUE TITLE
Unusual argument type?

### ISSUE THREAD

**Issue by schriftgestalt** [fonttools/fonttools#1847]
https://github.com/fonttools/fonttools/blob/eb6b4b596cef376761fd086a05fd83b2e4135be6/Lib/fontTools/cffLib/__init__.py#L202

The method is defined as 
```
def __init__(self, file=None, cff2GetGlyphOrder=None, topSize=0, isCFF2=None):
```

So calling
```
self.topDictIndex = TopDictIndex(None, cff2GetGlyphOrder, None)
```
means that the topSize is set to `None`? Is that intentional? I would expect 0 (or any other int) or omitting the argument? Or was it supposed to set `isCFF2`? (There are some more calls like this)

And why is the default for `isCFF2=None`? From the variable name, I would expect a bool?

**Comment by behdad** [comment]
I think you are right.

> And why is the default for `isCFF2=None`? From the variable name, I would expect a bool?

Apparently it uses `isCFF2=None` as a separate value from false/true.
