### ISSUE TITLE
GlobalState not used

### ISSUE THREAD

**Issue by schriftgestalt** [fonttools/fonttools#1848]
https://github.com/fonttools/fonttools/blob/eb6b4b596cef376761fd086a05fd83b2e4135be6/Lib/fontTools/cffLib/__init__.py#L768

The GlobalState-object in globalState is never used as the globalState is assigned a dict in line 772. So I wonder it that the GlobalState class is needed at all?

**Comment by behdad** [comment]
Sounds like something that I removed long ago, yes.
