### ISSUE TITLE
unrelevent question: converting two types of kerning

### ISSUE THREAD

**Issue by aminabedi68** [fonttools/fonttools#1854]
hi
sorry but someone told me i can find my answer here.
i want to expand the Unicode range for my fonts so i have to manage a huge number of kerning pairs code and this is a big challenge for me, i decide to group them as classes(="kerning by classes", not working for Arabic and even for Latin in some cases) and then convert the result to "kerning pairs"(which is used and working everywhere(with two value for Arabic(X placement and X Advance))), could you help me about the solution?

**Comment by khaledhosny** [comment]
>  "kerning by classes", not working for Arabic and even for Latin in some cases

Kerning classes should work anywhere kerning pairs can work (excluding the legacy `kern` table of course).

**Comment by aminabedi68** [comment]
I did not mean kerning by classes not working at all, but for Arabic, it's not working, i try it many times (i always use kerning by classes for Latin section and everything is OK, especially on the web) if I'm wrong(I'm not sure but maybe it's fontforge fault) please show me a working example(an Arabic font with kerning by classes)

**Comment by benkiel** [comment]
If you are in fontforge, you'll likely need to be sure to set the writing direction in the kerning feature. I've not used that in fontforge, but that may be the root of your problem.

**Comment by aminabedi68** [comment]
yes, direction is important in fontforge(i don't know why?!) i tried both ways, working wrong on the web and not working in Adobe and MS products

**Comment by aminabedi68** [comment]
sorry, I was wrong. kerning classes working for Arabic, it's a fontforge issue:
https://github.com/fontforge/fontforge/issues/4226
