### ISSUE TITLE
Always generate gvar table for VFs, even when empty?

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#1855]
We found that Adobe apps like InDesign  seem to require a `gvar` table to show a VF axis slider in the UI. Not sure this is just a bug. Also, OT Master won't display glyphs in a VF without a `gvar`.

Our use case is a single-source font that contains a lot of alternates that get swapped out along a single axis, no interpolation going on.

**Comment by anthrotype** [comment]
if adding an empty gvar table doesn't have other unwanted side effects elsewhere, then we may decide to always add one in varLib.build, to work around issues like these.

**Comment by cjchapman** [comment]
Excerpt from the spec:

>If a variable font has TrueType outlines in a 'glyf' table, the outline variation data will be provided in the glyph variations ('gvar') table, which is required.

Source: https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#variation-data-tables-and-miscellaneous-requirements

**Comment by justvanrossum** [comment]
I bet that part of the spec was written before FeatureVariations solidified...

But given that's what's written, we can't really argue against an empty `gvar` table.

**Comment by anthrotype** [comment]
I had missed that part..
I added the code that doesn't output empty gvar in this PR (https://github.com/fonttools/fonttools/pull/1752).
Ok, I guess we should revert to always output empty gvar.
