### ISSUE TITLE
feaLib should build simple contextual lookups when no backtrack/lookahead

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1856]
The Adobe FEA spec does not distinguish between contextual positioning/substitution lookups (GPOS 7, GSUB 5), on the one hand, and _chaining_ contextual pos/subst lookups (GPOS 8, GSUB 6), on the other. The two types of lookups are essentially the same except that the latter also can define optional backtrack/lookahead sequences.

FeaLib builder currently always encodes contextual pos/subst rules with Format 3 (Coverage-based) ChainContex{Pos,Subst} lookup subtables.

https://github.com/fonttools/fonttools/blob/42dcfddfb9687de106e5deb59cea015280dd507f/Lib/fontTools/feaLib/builder.py#L1246

https://github.com/fonttools/fonttools/blob/42dcfddfb9687de106e5deb59cea015280dd507f/Lib/fontTools/feaLib/builder.py#L1293

Ideally it could use the more efficient types of non-chaining contextual lookups when a contextual rule contains no backtrack nor lookahend sequences.

http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#5e-gsub-lookuptype-5-contextual-substitution
http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6g-gpos-lookuptype-7-contextual-positioning

I haven't had the chance to check, does makeotf do anything like that?

**Comment by simoncozens** [comment]
I'll work on this, but just for info, makeotf does not do this - it treats all contextuals as chaining contextuals.
