### ISSUE TITLE
[merge] OS/2 table Mixed Versions Crash

### ISSUE THREAD

**Issue by ClintGoss** [fonttools/fonttools#1865]
Got a crash in _pyftmerge_ when merging several fonts with OS/2 tables that have mixed versions.

If a font with a v5 OS/2 table **follows** font(s) with v4 OS/2 tables, I get:

  File "C:\App\Python37\lib\site-packages\fontTools\misc\loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "D:\Kurinto\Bin\Bin_CG\kmerge.py", line 1196, in main
    font.save(outfile)
  File "C:\App\Python37\lib\site-packages\fontTools\ttLib\ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "C:\App\Python37\lib\site-packages\fontTools\ttLib\ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "C:\App\Python37\lib\site-packages\fontTools\ttLib\ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "C:\App\Python37\lib\site-packages\fontTools\ttLib\ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "C:\App\Python37\lib\site-packages\fontTools\ttLib\tables\O_S_2f_2.py", line 152, in compile
    d['usLowerOpticalPointSize'] = round(self.usLowerOpticalPointSize * 20)
AttributeError: 'table_O_S_2f_2' object has no attribute 'usLowerOpticalPointSize'

Confession: I have not done any serious debugging here. I am hypothesizing the cause of the failure ... but it does seem reasonable given that, when I hacked my one font with a v5 OS/2 table to v4, the issue went away.

**Comment by ClintGoss** [comment]
Hit this again trying to merge fonts A and B, with A and B having OS/2 table versions of 1 and 3, respectively.

**Comment by anthrotype** [comment]
I see that OS/2 v5 has a `# TODO` in fontTools.merge

https://github.com/fonttools/fonttools/blob/c89c9487f131d16a6b45b5280efdcafd8f842580/Lib/fontTools/merge.py#L298

we just need to handle the new attributes.

**Comment by anthrotype** [comment]
from what I can tell in https://docs.microsoft.com/en-us/typography/opentype/spec/OS2#lps, it should be enough that we take the min() of all the fonts' `usLowerOpticalPointSize` and the max() of the fonts' `usUpperOpticalPointSize`.

**Comment by anthrotype** [comment]
> Hit this again trying to merge fonts A and B, with A and B having OS/2 table versions of 1 and 3, respectively.

@ClintGoss that's strange, v1 and v3 are supported and the merger should already take the maximum between the OS/2 versions. Can you provide a test font, the exact command you run and the error you got?

**Comment by anthrotype** [comment]
Ah I see.  The merger is not handling attributes like `sxHeight`, `sCapHeight`, `usDefaultChar`, `usBreakChar` that were only added in version 2 and are missing from version 1, so when merging v1 with v > 1 you get the AttributeError. I'll fix this

**Comment by ClintGoss** [comment]
Glad you see the issue ... because it is actually difficult for me to isolate a demonstration case. I've got merge and pyftsubset running hundreds of times in a rather arcane and massive pipeline / build process.
