### ISSUE TITLE
Question: Is there a way to give a glyph multiple unicodes with TTFont?

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#1867]
I'm hoping to produce a "trial font" that:
1. Is subset down to a basic set of characters (english alphabet, numbers, and a few symbols)
2. Maps many other unicodes to a `.notdef` glyph
3. Updates font names to append the suffix "Trial"

Part 1 can easily be done with pyftsubset, with the unicode values I wish to keep, with something like:

```bash
pyftsubset <fontPath> --unicodes="U+0020-007F --notdef-outline --name-IDs='*'
```

Part 3 can easily be done with TTFont, via the `.setName()` method for the `name` table.

However, I'm having trouble with Part 2. My guess, one could probably use TTfont and the `cmap` table, and assign multiple unicode codepoints to the `.notdef` glyph. 

I can do so directly in a TTX file, adding extra lines to the end of the format 4 tables in a cmap like:

```xml
<map code="0x2197" name=".notdef"/><!-- NORTH EAST ARROW -->
<map code="0x2198" name=".notdef"/><!-- SOUTH EAST ARROW -->
```

However, it would be much more ideal to do this kind of manipulation from a single Python script.

I see that I can open a font as a TTfont object, get a dictionary of the cmap table, and append new key-value pairs into that table. However, I am unsure of how (or whether) I can then save that edited cmap dict back into the TTfont.

```Python
ttfont = TTFont(fontPath)
currentCmap = ttfont['cmap'].buildReversed()
currentCmap['.notdef'] = {8596, 8597}
```

I have tried using the `compile()` and `decompile()` methods to save the edited cmap table back into the font, but these don’t seem to work (I admit, I don’t understand quite what these do, and whether they are useful to external scripts, or more for use within TTFont).

Is there a way to edit / append new values to a cmap table with TTFont? 

Is this a sensible approach, or am I missing a better way that this might be done?

Thanks so much for any advice or insight!

P.S. I'm not entirely sure, but it seems like issue https://github.com/fonttools/fonttools/issues/1813 may be a question another user trying to do something similar, replacing a range of glyphs with the `space` glyph. If so, I assume the answer might be similar to both.

**Comment by khaledhosny** [comment]
> Maps many other unicodes to a `.notdef` glyph

Mapping a code point to `.notdef` is the same as not mapping it at all (mapping to glyph ID 0 is used to indicate not supported character in many `cmap` subtables). So I’m not sure what you are trying to do.

The keys in cmap subtables are code points not glyphs, so you can map any code points to the same glyph. `buildReversed()` returns a dict of reversed glyph to code point map, but edit on this does not affect the `cmap` subtable in anyway, you should iterate over all the `cmap` subtable and update the `cmap` dict of each.

**Comment by arrowtype** [comment]
Hey Khaled, thanks so much for the quick reply!

> Mapping a code point to .notdef is the same as not mapping it at all (mapping to glyph ID 0 is used to indicate not supported character in many cmap subtables). So I’m not sure what you are trying to do.

It's not really about mapping to the .notdef glyph per se, but rather about mapping many unicodes to a placeholder glyph to indicate that a font is a trial font. So, this would be somewhat similar to how FontStand replaces the `f` character with a FontStand logo in test fonts (but instead of impacting the basic alphabet, it would appear in slightly-less common but still-common glyphs, like é, ñ, #, etc. Ultimately, I may not map to a "notdef" glyph, but rather to something like a logo or a black rectangle and an @ glyph, etc.

> iterate over all the cmap subtable and update the cmap dict of each.

Sorry for the probably basic question, but how might I update the cmap dicts of each subtable? I've tried the following to add codepoints to a cmap entry, but it is not quite there yet...

```
ttfont = TTFont(subsetPath)

for table in ttfont['cmap'].tables:
	table.compile(ttfont)['at'] = {8596, 8597, 8598, 8599} # does not yet work
```

Result: 

```
Traceback (most recent call last):
  File "source/scripts/create-trial_font.py", line 42, in <module>
    table.compile(ttfont)['at'] = {8596, 8597}
TypeError: 'bytes' object does not support item assignment
```

**Comment by khaledhosny** [comment]
```python
for table in ttfont['cmap'].tables: 
     for c in [8596, 8597, 8598, 8599]: 
         table.cmap[c] = "at"
```

**Comment by twardoch** [comment]
Think of cmap as mapping from Unicodes (that must be unique) to glyphs (that don't need to be), not as mapping from glyphs to Unicodes. cmap is the entry point to the font.

**Comment by arrowtype** [comment]
Amazing, that works perfectly, @khaledhosny! Thanks so much for pointing out what I now realize is fairly obvious. Thanks also, @twardoch, for helping clarify exactly why it works like this. That makes a lot of sense. Cheers!

**Comment by arrowtype** [comment]
Interestingly, I find that this seems to work well with any glyph _except_ the `.notdef`. That's fairly logical, as that glyph is a special case, but I just wanted to note it for others who may come across this.
