### ISSUE TITLE
error compiling OpenType from UFO/designspace

### ISSUE THREAD

**Issue by laerm0** [fonttools/fonttools#1877]
I have a file that's been complicated to make a repeatable build of: the OT was hand-written, but seems pretty good. Maybe it's got a layer of complexity or length or just some odd syntax. When fontmake goes to build OT, I get [an error](https://pastebin.com/hsVJFkzi) (long error so link). [These are the files](https://github.com/laerm0/inku/tree/dev/sources).

Build process so far is:
```
glyphs2ufo Inku.glyphs -d fontmake.designspace
fontmake -m Inku.designspace -o ttf --keep-direction --keep-overlaps
```

Much obliged. 🤠

**Comment by justvanrossum** [comment]
I was lucky and found the problem almost accidentally: It's because your `kernHorizontalKerninginEthiopiclookup0` lookup is empty. Add something (valid) there and the font compiles.

**Comment by justvanrossum** [comment]
FWIW makeotf also chokes on these features, without a decent error message, too.

It would be nice if feaLib gave a better error message in this case.

**Comment by laerm0** [comment]
Oh huh, thanks @justvanrossum ! I didn't write the OT, just helping the process along, so I didn't have any inside info of that. :)
