### ISSUE TITLE
[subset] FeatureVariations subsetting is wrong

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1881]
originally reported by @behdad at https://github.com/harfbuzz/harfbuzz/issues/2334#issue-602270174
> We cannot drop FeatureVariationsRecords that have empty substitutions. That changes the behavior. A FeatureVariationsRecords stops the search when the conditions match; so even if there's no susbstitutions we cannot drop the record as that will keep the search going.
> The only optimizations we can do are 1. dropping from the end of the array any records with no susbtitutions, and 2. dropping records earlier with no susbstitution only after analysing the conditions and proving that the dropping does not change functionality.
> Both of those are unnecessary right now. We should fix the functionality.
> This seems to be wrong in FontTools as well:
> https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/subset/__init__.py#L1325

**Comment by behdad** [comment]
I'll try submitting a minimal fix and a simple pruning but won't be able to contribute tests.  I hope there are tests for those code path already.

**Comment by anthrotype** [comment]
thanks Behdad, i'll fix up the tests as needed

**Comment by anthrotype** [comment]
To test this dropping-from-end-of-array of FeatureVariationRecords with no substitutions, we need create a VF where FeatureTableSubstitutions contain more than one SubstitutionRecords referencing different FeatureIndex; then we'd drop one feature while keeping another and assert that the thus emptied FeatureVariationRecords at the end of the FeatureVariations are dropped, and that empty records that precede non-empty ones are kept.
The current featureVars API can only create FeatureVariations for a one feature at a time (e.g. rvrn). Making a test font manually is not fun.. I will try again when I get the chance. I'll keep this open in the meantime as reminder.

**Comment by anthrotype** [comment]
@behdad when the subsetter has dropped all the existing FeatureVariationRecords, should it not also remove the emptied FeatureVariations table and downgrade the GSUB/GPOS table version to 0x00010000 (inside `prune_post_subset`)?

**Comment by behdad** [comment]
> @behdad when the subsetter has dropped all the existing FeatureVariationRecords, should it not also remove the emptied FeatureVariations table and downgrade the GSUB/GPOS table version to 0x00010000 (inside `prune_post_subset`)?

Yes.  I thought that's implemented.

**Comment by behdad** [comment]
> The current featureVars API can only create FeatureVariations for a one feature at a time (e.g. rvrn). Making a test font manually is not fun.. I will try again when I get the chance. I'll keep this open in the meantime as reminder.

Right.  You will hit same situ in partial instancing as well.  I don't know how to share such pruning code....

**Comment by anthrotype** [comment]
> I thought that's implemented.

if you mean this:

https://github.com/fonttools/fonttools/blob/9279f93de6afbbe0a4916b237c30c72a7139696a/Lib/fontTools/subset/__init__.py#L1637-L1639

then nobody seems to be setting table.FeatureVariations = None when FeatureVariationRecords list is empty

**Comment by behdad** [comment]
> then nobody seems to be setting table.FeatureVariations = None when FeatureVariationRecords list is empty

Right...  That's normally done when `subset()` return false.  But clearly not in this case..

**Comment by anthrotype** [comment]
@behdad something like this https://github.com/fonttools/fonttools/pull/1903

**Comment by anthrotype** [comment]
> You will hit same situ in partial instancing as well. I don't know how to share such pruning code....

I didn't quite get what you meant here.

**Comment by behdad** [comment]
> > You will hit same situ in partial instancing as well. I don't know how to share such pruning code....
> 
> I didn't quite get what you meant here

I mean, I assume you implemented FeatureVariations updating in your partial-instancer code.  That code can also do some pruning and possibly removing FeatureVariations if empty.

**Comment by anthrotype** [comment]
ah yes, we do remove FeatureVariations when left empty in the instancer.

**Comment by behdad** [comment]
Fixed in https://github.com/fonttools/fonttools/pull/1903

**Comment by behdad** [comment]
Humm. Not sure.

**Comment by behdad** [comment]
Was fixed in cab7d13dc
