### ISSUE TITLE
avar mapping values are not translated correctly

### ISSUE THREAD

**Issue by arialcrime** [fonttools/fonttools#1889]
Hello,

When I generate a variable font using fontmake I run into the problem that the weight values in the font are not the ones defined in the mapping of the designspace file. Back in January I was able to generate a font with the correct values.

While generating I get this (correct) output, so my guess is that something goes wrong when normalizing the values.

```
INFO:fontTools.varLib:Axes:
[{'default': 900.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [(100.0, 100.0),
          (300.0, 260.0),
          (400.0, 420.0),
          (600.0, 580.0),
          (700.0, 740.0),
          (900.0, 900.0)],
  'maximum': 900.0,
  'minimum': 100.0,
  'name': 'weight',
  'tag': 'wght'},
```
But instead of 100, 300, 400, 600, 700, and 900 I get 100, 325, 387.5 ,612.5 ,675, and 900.

Do you have a suggestion of how this can get fixed? 
Should I be doing something differently?

The designspace file used can be found [here](https://github.com/undercasetype/Fraunces/blob/master/sources/Roman/Fraunces.designspace), the generated font is [this one](https://github.com/undercasetype/Fraunces/blob/master/fonts/Fraunces%5BSOFT%2CWONK%2Copsz%2Cwght%5D.ttf). I am running the most recent versions of fonttools and fontmake.

Thanks for your help.

**Comment by justvanrossum** [comment]
> But instead of 100, 300, 400, 600, 700, and 900 I get 100, 325, 387.5 ,612.5 ,675, and 900.

I'm not 100% sure I understand this correctly. Are you talking about named instances? You expect 300, not 325, but from what user input?

Note that:

- axes are defined in user space coordinates
- sources and instances are defined in designspace coordinates
- map maps user space (`input`) to designspace (`output`)

**Comment by arialcrime** [comment]
Looking at it with a pair of fresh eyes, I can see that I had the sources/instance coordinates set wrongly again. Thanks for the pointer.
