### ISSUE TITLE
[pyftsubset] Failing on variable font when using ignore-missing-glyphs

### ISSUE THREAD

**Issue by nickyblissAviva** [fonttools/fonttools#1894]
I am trying to subset sourceSansPro Variable font using the subsets I have used in the past but they require --ignore-missing-glyphs to be set as I have set wide ranges in some cases. When I set ignore-missing-glyphs the woff files come out at 2kb every time. If I use a reduced subset without ignore-missing-glyphs I get a larger file (9kb)

Outputs 2kb file:
`pyftsubset SourceSansVariable-Roman.ttf.woff –unicodes="U+0020-007F,U+00A0-00FF,U+02B0-02FF,U+0300-036F" --ignore-missing-glyphs --layout-features="" --flavor="woff"`

Outputs 9kb file:
`pyftsubset SourceSansVariable-Roman.ttf.woff –unicodes="U+0020,U+0041-005A,U+0061-007A" --layout-features="" --flavor="woff"`

**Comment by anthrotype** [comment]
The option `--ignore-missing-glyphs` is meant to be used with either `--glyphs` or `--gids` option (that is, with inputs as either glyph names or glyph indexes).

You are using `--unicodes` as inputs. By default the subsetter will `--ignore-missing-unicodes`, unless you tell it not to (with `--no-ignore-missing-unicodes`).

The command you want is this, _without_ the `--ignore-missing-glyphs` option:

```
fonttools subset SourceSansVariable-Roman.ttf --unicodes="U+0020-007F,U+00A0-00FF,U+02B0-02FF,U+0300-036F" --layout-features="" --flavor="woff"
```

**Comment by anthrotype** [comment]
Also I wouldn't recomment to use `--layout-features=""`, as that drops _all_ layout features, including features that may be required for correct shaping such as ccmp, locl (in GSUB), or mark, mkmk, kern (in GPOS).
Do `fonttools subset --layout-features=?` to see the list of features that are kept by default.
If you want to remove some unneeded feature from that default list (e.g. frac, numr, dnom), you can pass `--layout-features-=frac,numr,dnom` (note the `-=` symbol)

**Comment by nickyblissAviva** [comment]
@anthrotype Thank you for the help. The above worked for the first subset I needed to create (I got a 25kb file out), but it fails on all the other subsets I need to create with the following stack trace. Any ideas what I'm doing wrong?

```
fonttools subset SourceSansVariable-Roman.ttf --unicodes="U+0100-024F" --layout-features="" --flavor="woff" --with-zopfli
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python37-32\Scripts\fonttools.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python37-32\lib\site-packages\fontTools\__main__.py", line 28, in main
    runpy.run_module(mod, run_name='__main__')
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files (x86)\python37-32\lib\site-packages\fontTools\subset\__main__.py", line 6, in <module>
    sys.exit(main())
  File "c:\program files (x86)\python37-32\lib\site-packages\fontTools\misc\loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "c:\program files (x86)\python37-32\lib\site-packages\fontTools\subset\__init__.py", line 2891, in main
    subsetter.subset(font)
  File "c:\program files (x86)\python37-32\lib\site-packages\fontTools\subset\__init__.py", line 2693, in subset
    self._closure_glyphs(font)
  File "c:\program files (x86)\python37-32\lib\site-packages\fontTools\subset\__init__.py", line 2512, in _closure_glyphs
    raise self.MissingGlyphsSubsettingError(self.glyphs_missing)
fontTools.subset.MissingGlyphsSubsettingError: {'-–unicodes=U+0100-024F'}
```

**Comment by anthrotype** [comment]
that's very weird, I just tried and it worked for me..

```
fonttools subset SourceSansVariable-Roman.ttf --unicodes="U+0100-024F" --layout-features="" --flavor="woff" --with-zopfli
```

I'm on macOS, I see you are using Windows. I don't understand why you would get that error. It looks like as if the subsetter command line parsing is misunderstanding your `--unicodes=` option with glyph names passed in as positional argument.

Can you please upload the font file you are using and the exact command line you are running, along with info about python version and OS name and version?

I hope somebody with access to a Windows machine can help you out.

**Comment by nickyblissAviva** [comment]
Font file is available here:
https://github.com/adobe-fonts/source-sans-pro/blob/release/VAR/SourceSansVariable-Roman.ttf

The command that does work for me is:
`fonttools subset SourceSansVariable-Roman.ttf --unicodes="U+0020-007F,U+00A0-00FF,U+02B0-02FF,U+0300-036F" --layout-features="" --flavor="woff" --with-zopfli`

 The ones that are failing:
`fonttools subset SourceSansVariable-Roman.ttf -–unicodes="U+0100-024F" --layout-features="" --flavor="woff" --with-zopfli`

`fonttools subset SourceSansVariable-Roman.ttf -–unicodes="U+20A0-20BF" --layout-features="" --flavor="woff" --with-zopfli`

`fonttools subset SourceSansVariable-Roman.ttf -–unicodes="U+2010-204F,U+2070-209F,U+2150-218F" --layout-features="" --flavor="woff" --with-zopfli`

`fonttools subset SourceSansVariable-Roman.ttf –-unicodes="U+0250-02AF,U+0370-03EF,U+0400-047F,U+0490-04FF,U+1D40-1D5F,U+1D90-1DBF,U+1E00-1E6F,U+1E80-1FFF,U+2110-212F,U+2190-231F,U+2E20-2E3F" --layout-features="" --flavor="woff" --with-zopfli`


- **OS** - Windows 10
- **Python version** - 3.7.3

**Comment by justvanrossum** [comment]
FWIW: I just ran all these commands on Win 10 with the latest fonttools (4.8.1), using Python 3.8.2, and none of them fail.

**Comment by nickyblissAviva** [comment]
@justvanrossum I'll try updating python and see if that makes a difference. Very odd

**Comment by nickyblissAviva** [comment]
Updated Python so now running Python 3.8.2 and fonttools 4.8.1 and its still blowing up

**Comment by nickyblissAviva** [comment]
@anthrotype @justvanrossum Sorry guys found the issues. Somehow a rogue endash/emdash crept in which I couldn't see in notepad or powershell. Working now. Thank you

**Comment by anthrotype** [comment]
Ha! No problem, I'm glad you managed to solve it :)
