### ISSUE TITLE
[feaLib] feaLib parses nonsensical alternate rule without complaining

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1901]
This is a *very* low-priority issue, but... feaLib has provision for prefix and suffix contexts on alternate rules. The OpenType spec doesn't. :-) Given this obviously silly feature file:

```
feature aalt {
    sub uni0061' uni0062 from [glyph01 glyph02 glyph03];
} aalt;
```

This works sucessfully (but I think it shouldn't):

```
from fontTools.feaLib.parser import Parser
file = open("test.fea","r")
parsetree = Parser(file, ()).parse()
print(parsetree)
```

And then trying to build that into a font gives a really weird error.

```
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/builder.py", line 1189, in setInputCoverage_
    coverage = otl.buildCoverage(g, self.glyphMap)
  File "/usr/local/lib/python3.7/site-packages/fontTools/otlLib/builder.py", line 11, in buildCoverage
    self.glyphs = sorted(glyphs, key=glyphMap.__getitem__)
KeyError: 'u'
```

Clearly nobody should ever try to do this, so it might be a "you get what you deserve" thing. But I think your parser is more generic than it can actually handle. :-)

**Comment by khaledhosny** [comment]
I think contextual alternates should be valid, whether it is sensible or not. The issue here, though, might be related to `aalt` feature specifically as the code will try to restrict it to single and alternate substitutions only, and it might not be prepared to uncontextualizing alternate substitutions like these.

**Comment by khaledhosny** [comment]
I can’t reproduce this actually, I get a font with the following (expected) GSUB table:
```xml
  <GSUB>
    <Version value="0x00010000"/>
    <ScriptList>
      <!-- ScriptCount=1 -->
      <ScriptRecord index="0">
        <ScriptTag value="DFLT"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=1 -->
            <FeatureIndex index="0" value="0"/>
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
    </ScriptList>
    <FeatureList>
      <!-- FeatureCount=1 -->
      <FeatureRecord index="0">
        <FeatureTag value="aalt"/>
        <Feature>
          <!-- LookupCount=1 -->
          <LookupListIndex index="0" value="0"/>
        </Feature>
      </FeatureRecord>
    </FeatureList>
    <LookupList>
      <!-- LookupCount=1 -->
      <Lookup index="0">
        <LookupType value="3"/>
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <AlternateSubst index="0" Format="1">
          <AlternateSet glyph="uni0061">
            <Alternate glyph="glyph01"/>
            <Alternate glyph="glyph02"/>
            <Alternate glyph="glyph03"/>
          </AlternateSet>
        </AlternateSubst>
      </Lookup>
    </LookupList>
  </GSUB>
```

**Comment by simoncozens** [comment]
Try it in a different feature.

**Comment by khaledhosny** [comment]
Right, I get that now. Will at least `aalt` is uncontextualizing it correctly.

**Comment by khaledhosny** [comment]
#1902

**Comment by cmyr** [comment]
Bumping a zombie, but curious what the rationale was for adding support for this non-standard syntax? Is this being used in any actual fonts? I would personally prefer this to just be a parse error.

**Comment by khaledhosny** [comment]
It is valid OpenType lookup, why should we refuse to compile it?

**Comment by khaledhosny** [comment]
https://github.com/simoncozens/fonttools/commit/db49f20d6b2629e1ba25c4afd3fb60817387f3d6

**Comment by khaledhosny** [comment]
In general, the point of feaLib has always been so we xan easily extend it to do things makeotf couldn't do, if it were bug-for-bug compatible it would have largely been a pointless exercise.

**Comment by cmyr** [comment]
The reason not to compile it is that it leads to a second, informal specification. This is a headache for future implementors, who can no longer rely on the spec as a source of truth; and it also makes it more difficult to do things like run different implementations against a common set of inputs, and compare the results.

I think it is entirely reasonable to make extensions to the specification, to solve particular problems (e.g. simon's work supporting variable fonts in FEA) but I would discourage arbitrarily relaxing constraints imposed by the spec, even if those constraints seem arbitrary, unless there is a very compelling reason.

**Comment by cmyr** [comment]
> In general, the point of feaLib has always been so we xan easily extend it to do things makeotf couldn't do, if it were bug-for-bug compatible it would have largely been a pointless exercise.

I'm definitely not arguing for bug-by-bug compatibility, but I am arguing for not adding support for syntax that is explicitly disallowed per the spec, in this case (emphasis added):

>If there is only a single substitution operation, and it is **either single substitution or ligature substitution**, then the operation can be specified in-line and its type will be auto-detected from the input and replacement sequence in the same way as in their corresponding standalone (i.e. non-contextual) statements.

Another way I would think about this: is there any *downside* to just following the spec? Are these rules significantly more convenient to specify inline? Are there a bunch of existing tools that generate FEA and generate these rules, which would break if we did not support this syntax? If not, then all things being equal, I think we should err on following the spec. Otherwise, if we have a strong case that the spec should change, then we should go through the process to try and make that happen.

**Comment by khaledhosny** [comment]
That would have been nice in an ideal world, but the reality is that feature file spec has always been a description of what makeotf does (and iften incorrect or incomplete at this) not a formal spec, and makeotf can arbitrarily change as they seem fit (and it did so on several occasions, I think including last year when it was ported to ANTLR 4). So to limit ourselves to arbitrary and often changing makeotf implementation details seems to be unfair.

**Comment by cmyr** [comment]
I mean I broadly agree, I just think it's worth being judicious about where and how we deviate. :)

**Comment by khaledhosny** [comment]
In this particular case, it was a generalization of an existing syntax and now we already support it it makes little sense to break our own backward compatibility and disallow it. Other implementations are free to decide not to follow feaLib here and if users complain, they can always be told this is non-standard.
