### ISSUE TITLE
fontTools.cu2qu.cu2qu

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#1906]
Shouldn’t the `cu2qu` sub module (or whatever that is called) be the root `fontTools.cu2qu` module?

**Comment by anthrotype** [comment]
No, because we need to be able to run that module through cython (optionally) and `__init__` module can't be a compiled extension module

**Comment by khaledhosny** [comment]
I see, I was mislead by https://fonttools.readthedocs.io/en/latest/cu2qu/cu2qu.html. In hindsight may be a different name like core on convert would have been better instead of the repetition, but meh.
