### ISSUE TITLE
[TTX] glyph order when dumping glyphs

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#1907]
I just noticed that `gvar` uses the glyph order to dump the glyph deltas to XML, but `glyf`, `hmtx` and `vmtx` use a sorted list.

I think `gvar` should do the same: I'm currently looking at an extremely noisy diff in a `gvar` table, just because the glyph orders differ across the fonts I'm looking at.

In general, we try not to expose the glyph order in the XML format, except for the `<GlyphOrder>` element.

**Comment by anthrotype** [comment]
Yes, I agree it should be sorted alphabetically, surprised that it isn't already

**Comment by twardoch** [comment]
I think this is great for consistency. However, I wonder if there might be a chance for a switch that'd dump all tables in GID order then. Just a thought.

**Comment by justvanrossum** [comment]
That's precisely what I don't want, because, as I wrote above, it messes up diffs when only the glyph order is different.

**Comment by anthrotype** [comment]
Now it will probably still mess up other diffs, just like it did for our own test, but it was indeed an oversight and it's better to keep things consistent
