### ISSUE TITLE
[feaLib/otLib] Support class-based contextuals (6.2) 

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1910]
Tracking bug for @behdad. The following feature file (when added to [Fallback Plus Small](https://github.com/simoncozens/test-fonts/blob/master/FallbackPlus-Small.otf)) produces a lookup (id 3) with 12 GSUB6.3 subtables; total GSUB length 426 bytes. It could instead be expressed with 1 GSUB6.2 subtable, total GSUB length 390 bytes. That's not a huge difference right now, but this is a simple example. If you have lots of rules, moving to GSUB6.2 would save even more bytes; also if the classes used non-contiguous glyphs (format 1 coverage), and there would be a lot of repetition in the GSUB6.3 subtables which would be avoided by moving to GSUB6.2.

```
@uc1 = [uni0041 uni0042 uni0043 uni0044 uni0045 uni0046];
@uc2 = [uni0047 uni0048 uni0049 uni004A uni004B uni004C];

@lc1 = [uni0061 uni0062 uni0063 uni0064 uni0065 uni0066 uni0067 uni0068];
@lc2 = [uni0069 uni006A uni006B uni006C uni006D uni006E uni006F uni0070];
@lc3 = [uni0071 uni0072 uni0073 uni0074 uni0075 uni0076 uni0077 uni0078];

lookup ucswash1 {
	sub @uc1 by [glyph01 glyph02 glyph03 glyph04 glyph05 glyph06];
	sub @uc2 by [glyph07 glyph08 glyph09 glyph10 glyph11 glyph12];
} ucswash1;

lookup ucswash2 {
	sub @uc1 by [glyph13 glyph14 glyph15 glyph16 glyph17 glyph18];
	sub @uc2 by [glyph19 glyph20 glyph21 glyph22 glyph23 glyph24];
} ucswash2;

lookup ucswash3 {
	sub @uc1 by [glyph25 glyph26 glyph27 glyph28 glyph29 glyph30];
	sub @uc2 by [glyph31 glyph32 glyph33 glyph34 glyph35 glyph36];

} ucswash3;

feature rlig {
    sub @uc1' lookup ucswash1 @lc1 @lc1;
    sub @uc1' lookup ucswash2 @lc1 @lc2;
    sub @uc1' lookup ucswash3 @lc1 @lc3;
    sub @uc1' lookup ucswash2 @lc2 @lc1;
    sub @uc1' lookup ucswash3 @lc2 @lc2;
    sub @uc1' lookup ucswash1 @lc2 @lc3;
 
    sub @uc2' lookup ucswash3 @lc1 @lc1;
    sub @uc2' lookup ucswash1 @lc1 @lc2;
    sub @uc2' lookup ucswash2 @lc1 @lc3;
    sub @uc2' lookup ucswash3 @lc2 @lc1;
    sub @uc2' lookup ucswash1 @lc2 @lc2;
    sub @uc2' lookup ucswash2 @lc2 @lc3;
} rlig;
```

Here is what is currently produced:
[current-gsub63.ttx.txt](https://github.com/fonttools/fonttools/files/4557056/current-gsub63.ttx.txt)

Here is what it would look like as a GSUB6.2 class-based format instead:
[as-gsub62.ttx.txt](https://github.com/fonttools/fonttools/files/4557057/as-gsub62.ttx.txt)

**Comment by simoncozens** [comment]
I actually really need this now, so I'm working on it. May need help later, but I'll see how far I get.

**Comment by simoncozens** [comment]
OK, I have a thing. It seems to work. All tests will probably fail because it will turn things into format 2 pos/sub rules if it saves space to do so. In a fairly pathological case I am working on, it saves *staggering* amounts of space:

```
$ ls -al NNU-dropdots-noclass.otf NNU-dropdots.otf
-rw-r--r--+ 1 simon staff 1342652 May 15 17:12 NNU-dropdots-noclass.otf
-rw-r--r--+ 1 simon staff  174736 May 15 17:11 NNU-dropdots.otf
```

But:
* I'm not convinced that some of the code is right. (Use of `populateDefaults()` is needed but I haven't seen other similar code doing the same.)
* It doesn't handle splitting the ruleset into multiple subtables - either all the rules fit into a class-based sub/pos or none of them do.
* Because of that, large rulesets can still overflow the table.

**Comment by davelab6** [comment]
With #1960 merged, can this be closed?

**Comment by behdad** [comment]
> * I'm not convinced that some of the code is right. (Use of `populateDefaults()` is needed but I haven't seen other similar code doing the same.)

Typically we just set all required attributes manually.

> * It doesn't handle splitting the ruleset into multiple subtables - either all the rules fit into a class-based sub/pos or none of them do.

Thanks. I'll check out the algorithm.
