### ISSUE TITLE
Font Tools smallest supported optical size seems to be 12. Please fix this!

### ISSUE THREAD

**Issue by EbenSorkin** [fonttools/fonttools#1918]
I admit that in the vast majority of contexts 12 could be OK ( web fonts don't get tiny) but I would like to make a case for supporting at least down to 6 if not 4-5pt simply because micro design and especially in print is genuinely interesting and useful.

Is it possible that my local build of fontmake is out of date and this is fixed already?

I am working on learning how to check my version today.

**Comment by justvanrossum** [comment]
I don't know of anything in fontmake, fonttools or ufo2ft that would impose such a limit. Can you describe what you're trying to do, what outcome you would expect, and what outcome you're actually getting?

**Comment by EbenSorkin** [comment]
I got a comment back in my terminal when I ran font make that said

fontmake: Error: In 'Merriweather-Italic.glyphs' ->
'master_ufo/Merriweather-Italic.designspace': Generating fonts from
Designspace failed: Source or instance 'Merriweather Light Italic' has
out-of-range location for axis 'Optical size': is mapped to 7.0 but must be
in mapped range [12.0..144.0] (NOTE: all values are in user-space).


It would be great if I misunderstood and in mapped range was not fontmake
specific but something mapped in my source. I ended up changing the min
values to 12 and then I didn't get this error.


I'll recheck the Glyphs file for consistency and then try 7 again.


-e.

**Comment by justvanrossum** [comment]
It means that the source file defines minimum and maximum for the axis as from 12 to 144, yet a source or instance is set it something out of that range.

**Comment by justvanrossum** [comment]
You should be able to find those values in the generated .designspace file.

**Comment by EbenSorkin** [comment]
I was able to find the problem originated with the metadata/.designspace in my source. It was not a Fontmake issue.
