### ISSUE TITLE
Duplicate glyph names: Disambiguated names are invalid

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1942]
The [addition of hash characters](https://github.com/fonttools/fonttools/issues/1119#issuecomment-347512821) to disambiguate glyph names just bit me again, as the resulting glyph names are invalid.

In my case this is a problem because I'm using an input file in a text format to add information to a font, and there I need to use the glyph names that FontTools is assigning. So I need to use `Delta#1`, but the input file parser treats the `#` as a comment marker, thus breaking my input file.

Could we reconsider to change the logic to produce valid glyph names, as [Just suggested](https://github.com/fonttools/fonttools/issues/1119#issuecomment-347512821)? Maybe for compilation, we could still support the `#` notation as not to break existing files.

https://github.com/fonttools/fonttools/blob/1d6dd50d5246e0ee295eb5d2d363c68973be3a43/Lib/fontTools/ttLib/tables/_p_o_s_t.py#L112-L118

**Comment by anthrotype** [comment]
> the resulting glyph names are invalid

what do you mean by invalid?

> the input file parser treats the # as a comment marker

and I suppose you can't change that?

**Comment by anthrotype** [comment]
fontTools does _not_ compile invalid postscript names with `#`, it keeps duplicate glyph names in post table as they were when roundtripping. But since fontTools needs glyph names to be unique it has to internally disambiguate between them by adding the `#<digit>` suffix.
see my comments in the other thread
https://github.com/fonttools/fonttools/issues/1119#issuecomment-347486107
https://github.com/fonttools/fonttools/issues/1119#issuecomment-347514627

**Comment by jenskutilek** [comment]
Yes, I have read the comments. I know the names containing a `#` are not written back into the font. But they are used while the font is decompiled, so every script that deals with the font through `TTFont` and insists on validity of glyph names will have a problem.

I can change the input format parsing, but it's a bit of a hack, as it requires a certain formatting of comments (I can't change the comment marker that is being used, only under which circumstances it denotes a comment, e.g. only at the start of a line or surrounded by whitespace).

```
# This is a comment
# The line below does not contain a comment
Delta#1
   # But this again is a comment
  #Whataboutthis?
```

**Comment by justvanrossum** [comment]
Doesn't the fact that disambiguation is need point to a problem in the source font?

I'm not opposed to a change here, but I do think that a font containing duplicate glyph names in the post table is problematic in other ways, too.

**Comment by jenskutilek** [comment]
The source font doesn't actually contain duplicate names in `post`, but one glyph maps to a standard name (not contained in `post`) that is also assigned to another glyph via the post table.

The font is generated from FontLab 5 with glyphs `Delta` (U+0394) and `increment` (U+2206) FL omits the name for `increment` from the post table. Below is a font to reproduce.

**Comment by justvanrossum** [comment]
That's a bit nitpicky... If one glyph refers to the standard mac array and another refers to a "custom" name that happens to be the same as a standard name, then the font still defines two glyphs as having the same name.

If a FontLab file contains a glyph named "increment", yet generates a font that refers to name 168 in the standard list (which is Delta) then what else is that but a bug in FL 5?

**Comment by justvanrossum** [comment]
By "source font" I didn't mean FL or UFO, just the OTF/TTF that you're operating on, which _does_ contain a duplicate glyph name.

**Comment by jenskutilek** [comment]
OK, I agree the source font is probably not entirely without issue.

So I will try and fix this in the editor.
