### ISSUE TITLE
varLib.models locations parameter - how does it work?

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1943]
I'm trying to document `fonttools varLib.models`, which has two modes of operation: you can give it a designspace file, which I can understand; or you can pass it "locations":

		axes = [chr(c) for c in range(ord('A'), ord('Z')+1)]
		locs = [dict(zip(axes, (float(v) for v in s.split(',')))) for s in args]

I can't work out what "args" ought to be here - obviously a list of comma-separated numbers, but everything I try gives this error:

```
$ fonttools varLib.models 0,100,200 200,300,400
...
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/varLib/models.py", line 230, in getMasterLocationsSortKeyFunc
    raise VariationModelError("Base master not found.")
fontTools.varLib.errors.VariationModelError: Base master not found.
```

**Comment by anthrotype** [comment]
it needs to have a base master (one which is at 0 in normalized coordinates on all the axes)

**Comment by simoncozens** [comment]
```
$ PYTHONPATH=Lib fonttools varLib.models '0,100' '0,200'
...
fontTools.varLib.errors.VariationModelError: Base master not found.

$ PYTHONPATH=Lib fonttools varLib.models '-100,0,100' '-200,0,200'
...
fontTools.varLib.errors.VariationModelError: Base master not found.
```

**Comment by anthrotype** [comment]
a least one (base) master with all 0s

**Comment by simoncozens** [comment]
Thanks, got it!
