### ISSUE TITLE
bezierTools.splitLine/splitQuadratic/etc. are upside down

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1953]
While documenting this package, I ran across this docstring:

```
'where', which is an x coordinate if isHorizontal is False, a y coordinate if isHorizontal is True
```

I know this is one of those "horizontal stem"/"vertical stem" things, but it's confusing, at least to me: if `isHorizontal` is true, then the `where` coordinate is a point on the vertical axis.

I'm sure we can rename `isHorizontal` to something less ambiguous.

**Comment by dscorbett** [comment]
Changing a positional-or-keyword parameter name is backwards-incompatible.

**Comment by simoncozens** [comment]
Fixing bugs is also backwards incompatible. Someone might have been relying on that behaviour!

**Comment by justvanrossum** [comment]
The description is not complete and is ambiguous, but it's _not_ upside down: the `isHorizontal` flag is about the line to be used for intersection: if that line is horizontal, we're interested in y coordinates, if that line is vertical, we need x coordinates.

**Comment by justvanrossum** [comment]
In _three_ function calls use such a name consistently, please first consider your understanding may be off before you assume the code is wrong :)

**Comment by simoncozens** [comment]
Oh, I am perfectly capable of being confused more than once. :-) Like I said, I know it's one of those "horizontal stem"/"vertical stem" things, but I still think the description is confusing.

Perhaps the way to document this more clearly, without having to change things, is to say that `isHorizontal` describes the direction of the ray which is intersecting the line/quadratic/cubic.

**Comment by justvanrossum** [comment]
> Perhaps the way to document this more clearly, without having to change things, is to say that isHorizontal describes the direction of the ray which is intersecting the line/quadratic/cubic.

Exactly, that's the way to go. A change in code here is undesirable.

**Comment by khaledhosny** [comment]
> Fixing bugs is also backwards incompatible. Someone might have been relying on that behaviour!

Breaking API is not the same thing as changing behavior, breaking API is always bad even if the API was wrong as it means client code will suddenly stop working. Changing behavior can be tolerated if it can be argued that the old behavior was completely wrong and no one could have possibly been relying on it.

**Comment by simoncozens** [comment]
OK, I'm going with

```
    Args:
        pt1: Start point of line as 2D tuple.
        pt2: End point of line as 2D tuple.
        where: Position at which to split the line.
        isHorizontal: Direction of the ray splitting the line. If true,
            ``where`` is interpreted as a Y coordinate; if false, then
            ``where`` is interpreted as an X coordinate.
```

Even I can understand that now.
