### ISSUE TITLE
design for a new processor or dispatch module implementing visitor pattern

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1959]
This has come up a few times, e.g. https://github.com/fonttools/fonttools/pull/1668#issuecomment-628970150 or https://github.com/fonttools/fonttools/issues/1951#issuecomment-628174958

quoting @behdad

> I'm also thinking about a new modules (possibly called processor or dispatch) that will improve on and centralize the programming scheme used in the merge, subset, and varLib modules. That will simplify a lot of things.

**Comment by anthrotype** [comment]
In https://github.com/fonttools/fonttools/pull/1668#issuecomment-629173201, I mentioned https://github.com/mrocklin/multipledispatch/.

There is also another one called [methoddispatch](https://github.com/seequent/methoddispatch) that provides a `singledispatch` decorator (similar to the stdlib one) but designed to work with instance methods. This one also supports inheritance, by ensuring that each subclass has it's own independant copy of the dispatch registry

> Subclasses can extend the type registry of the function on the base class with their own overrides.

**Comment by justvanrossum** [comment]
I don't like the limitation of the above-mentioned methoddispatch that specific implementations need to have distinct names.

Perhaps an external dependency isn't needed, as it's not super hard to just implement it ourselves. Here's a naive try that seems to work:

```python
def instancedispatch(generic_func):
    registry = {}
    def register(tp):
        def deco(func):
            registry[tp] = func
            return wrapper
        return deco
    def wrapper(self, arg0, *args, **kwargs):
        # TODO: traverse type(arg0).__mro__ instead of only looking at type(arg0)
        func = registry.get(type(arg0), generic_func)
        return func(self, arg0, *args, **kwargs)
    wrapper.register = register
    return wrapper


class A:

    @instancedispatch
    def myfunc(self, arg):
        print("A generic arg:", arg)

    @myfunc.register(int)
    def myfunc(self, arg):
        print("A int arg:", arg)


class B:

    @instancedispatch
    def myfunc(self, arg):
        print("B generic arg:", arg)

    @myfunc.register(int)
    def myfunc(self, arg):
        print("B int arg:", arg)

    
a = A()
a.myfunc("abc")
a.myfunc(123)

b = B()
b.myfunc("def")
b.myfunc(456)
```

**Comment by anthrotype** [comment]
your implementation doesn't do more than the built-in `singledispatchmethod`, which is actually quite short and nice piece of code. It uses the [descriptor](https://docs.python.org/3/howto/descriptor.html) protocol (i.e. defines `__get__`), and delegates to `functools.singledispatch` looking up the concrete implementation for a given type (thus, includes resolving MRO and memoizing subsequent calls for the same type):

https://github.com/python/cpython/blob/07bd5cf3d9551ae84100e6400836163fcd507f07/Lib/functools.py#L887-L921

We could even check that code in fontTools, along with the PSF license, if we don't want to have third party requirement for pythons < 3.8.

The problem with that approach, as explained in https://bugs.python.org/issue36457, is that because the dispatch registry is local to the generic dispatcher method, when a subclass wants to register its own concrete implementation of the generic method, they end up modifying the base class registry as well.

**Comment by behdad** [comment]
All of that. :)

The dispatch part is easy to get working with subclassing.  I already have that here: https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/varLib/merger.py#L26

Is the other parts of the system I'm still designing.  I'll share something before Monday...

**Comment by behdad** [comment]
I've thought about this for days.  I have most of it mapped out but some questions remain.  Now I need to find a way to write them all down...

I also have been thinking about pens more, since we are tackling that in HarfBuzz now: https://github.com/harfbuzz/harfbuzz/issues/2145

I keep coming back to "cooperative inheritance" and/or mixin ideas which almost address everything we need but not fully.

While I figure out how to write that all down, those interested can familiarize themselves with the concepts by reviewing the following article and its references: https://www.artima.com/weblogs/viewpost.jsp?thread=281127

**Comment by behdad** [comment]
I finally sketched this here:
https://github.com/behdad/pyvisitor

**Comment by behdad** [comment]
It's based on the varLib.merger code. I'll try to port various code we have to it and see how it fares. Or more interesting, see how easy it is to write, eg. code that collects all VarIdx'es from GPOS code with minimal effort. Or how to nuke them all.

**Comment by behdad** [comment]
Here's a better look: https://github.com/fonttools/fonttools/pull/2718
