### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'UFOFormatVersion'

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#1964]
I’m getting this error from `checkoutlinesufo` after updating FonTools:
```
$ checkoutlinesufo -e -q tests/checkoutlinesufo_data/input/ufo2.ufo
Traceback (most recent call last):
  File "python/afdko/checkoutlinesufo.py", line 1109, in <module>
    main()
  File "python/afdko/checkoutlinesufo.py", line 1103, in main
    run(sys.argv[1:])
  File "python/afdko/checkoutlinesufo.py", line 1092, in run
    font_file.save()
  File "python/afdko/checkoutlinesufo.py", line 136, in save
    layerName=PROCD_GLYPHS_LAYER_NAME, defaultLayer=False)
  File "/fonttools/Lib/fontTools/ufoLib/__init__.py", line 1440, in getGlyphSet
    self._formatVersion < UFOFormatVersion.FORMAT_3_0
TypeError: '<' not supported between instances of 'int' and 'UFOFormatVersion'
```

**Comment by khaledhosny** [comment]
Hmm, checkoutlinesufo is directly setting `_formatVersion`, so I guess it is doing something unsupported.

**Comment by benkiel** [comment]
That's likely due to this: https://github.com/fonttools/fonttools/pull/1786. I see what checkout lines has to do here (pretend it's a UFO3 when it's a UFO2). FontTools added a class here for the types, and checkoutlines isn't using that for the version. If you change checkoutlines to pull that in from fonttools, it should be fine.

@anthrotype clearly this is an unintended side effect, likely we should add `__eq__` to the UFOFormatVersion class

**Comment by anthrotype** [comment]
That checkoutlinesufo code is setting a private method (prefixed with underscore), and in the inline comments it is describing itself as a "hack"

https://github.com/adobe-type-tools/afdko/blob/071efbb4d4626962424db7c53b5ed7bebbe12ee0/python/afdko/checkoutlinesufo.py#L133

I don't think this is a fontTools bug. When accessing a private attribute they are doing at one's risk. It should be easier to just update the code in checkoutlinesufo.

**Comment by khaledhosny** [comment]
Yes, I don't think it is a FontTools bug. What it is trying to do seems also hackish, opening UFO 2 files then pretending they are version 3 then saving them as version 2!

**Comment by benkiel** [comment]
It's a hack, yes, but I do think that there will be code that has UFO versions as `int` and is trying to compare version with `ufoLib`, that's there this is breaking down. An `__eq__` for the version class would smooth that over.

**Comment by benkiel** [comment]
(changed mind)

Agreed, @khaledhosny I think that if the hack uses the versions specified by the new class, all will be well.

**Comment by khaledhosny** [comment]
Not really a FontTools bug.

**Comment by josh-hadley** [comment]
> I know full well why that hack is there, it's just for RF UFO2's layers that was a hack, you can't get around that, so...hack on.

AFDKO will "hack on", but not forever: https://github.com/adobe-type-tools/afdko/issues/1135
