### ISSUE TITLE
extTables big and slow compilation

### ISSUE THREAD

**Issue by mhosken** [fonttools/fonttools#1965]
A few years ago, I was given some sage advice: treat OT and fea as an assembler. So I did. One font I am working on has around 800 lookups and 1900 contextual chaining strings. Why? To implement collision avoidance kerning.

The problem: The fonttools way of handling extension lookups is very slow: wait to see if a lookup has an out of range pointer somewhere, turn it into an extension lookup and recompile from the top. Talk about O(N^2)! In addition, there is no sharing of resources like coverage tables between extension lookups, even though the lookup being extended may be quite small.

I'm wondering if there is a way to change the processing model to identify that once a lookup needs to be turned into an extension lookup, all future encountered lookups will need to be extension lookups. In addition, there is no need to recompile all lookups from the top. Just regather their data (perhaps by not overwriting the .items attribute, but gathering into a new .gathereditems attribute and using that forward).

Secondly, currently each extension lookup is given its own items dict. I'm wondering if such dicts could be shared with groups of extensions just like the dict is shared between all non-extension lookups.

These suggestions as to solutions are merely that. But there is clear need for sub 20 minute compile times for big fonts!

**Comment by anthrotype** [comment]
hi Martin, thanks for bringing this up. I believe there's another issue tracking this https://github.com/fonttools/fonttools/issues/1105

@behdad was working on a new algorithm for packing otTables in https://github.com/fonttools/fonttools/tree/99proof branch. Not sure what the status of that is. 
If you have big overflowing fonts that you can share with Behdad, I think it would help testing this out with real-world fonts.

**Comment by behdad** [comment]
The cheapest way to a fast compiler is to upgrade *all* lookups to Extension when we hit first one.  The non-sharing results in bigger fonts but at least something to work with right now.

**Comment by mhosken** [comment]
I think that is probably overkill for those fonts which only have a few extension lookups. I think we need something more sophisticated than that.

**Comment by simoncozens** [comment]
I am working on an optimizer for contextual chaining lookups, which selects the best subtable format to compress multiple lookups into a single subtable. It doesn't handle extension lookups, (so 99proof is still relevant) but it makes lookup compilation a lot faster and a lot more efficient in cases like yours.

**Comment by behdad** [comment]
With hb-repacker we can close this now.
