### ISSUE TITLE
[merge] Expected all items to be equal: [NotImplemented, 'vhea']

### ISSUE THREAD

**Issue by jm4R** [fonttools/fonttools#1966]
I've tried to merge previously prepared subset of NotoCJK (converted to ttf) with Noto Regular. I received some warnings and at the end an error. Here is part of logs:

```
WARNING:fontTools.merge:Dropped cmap subtable from font [1]:    format 14, platformID  0, platEncID  5
(...)
WARNING:fontTools.merge:Dropped mapping from codepoint 0XF904 to glyphId 'uniF904'
WARNING:fontTools.merge:Dropped mapping from codepoint 0XF908 to glyphId 'uniF908'
(... and many simillar warnings here ...)
Traceback (most recent call last):
  File "/some/path/noto_based_on.py", line 305, in <module>
    main()
  File "/some/path/noto_based_on.py", line 271, in main
    font = merger.merge(valid_files)
  File "/home/someuser/.local/lib/python3.6/site-packages/fontTools/merge.py", line 996, in merge
    table = clazz(tag).merge(self, tables)
  File "/home/someuser/.local/lib/python3.6/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/home/someuser/.local/lib/python3.6/site-packages/fontTools/merge.py", line 1044, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/home/someuser/.local/lib/python3.6/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [NotImplemented, 'vhea']
```

If this operation is for some reason technically not possible, the error message should be more descriptive, I think.

**Comment by anthrotype** [comment]
I think the merge tool is expecting that all fonts have either vhea tables or none of them have, whereas in your case one of the fonts does not have vhea, hence the error. Yes, I agree with you that the error message could be improved.

**Comment by jm4R** [comment]
Why merge tool has such expectation? Is it technical or library limitation? Should we consider it as a bug?

**Comment by anthrotype** [comment]
i believe it's by design, but @behdad can confirm. The merger tool can't merge vhea tables of different fonts if any of them does not specify one. It's kind of undefined what the result should be in that case.

**Comment by jm4R** [comment]
I have no deep kowladge about the topic, but shouldn't the result be just the copy of vhea table from the font that actually contains it? Or merge from the list that contains it, ignored ones that doesn't? I think it could be the question for @behdad .

**Comment by behdad** [comment]
> I have no deep kowladge about the topic, but shouldn't the result be just the copy of vhea table from the font that actually contains it? Or merge from the list that contains it, ignored ones that doesn't? I think it could be the question for @behdad .

"It depends" is all.

**Comment by behdad** [comment]
The merger expects all fonts to have the same tables. You can pass `--drop-tables=vhea` to instruct it to do just that.
