### ISSUE TITLE
ttx CFF table CharString hstem parameters

### ISSUE THREAD

**Issue by paratype-andrei** [fonttools/fonttools#1972]
Pardon my ignorance - started using ttx just recently. Often times hstem command has an odd number of parameters. What does the first one denote?

**Comment by justvanrossum** [comment]
The width. From https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5177.Type2.pdf:
![image](https://user-images.githubusercontent.com/4246121/82878178-6b482b00-9f3b-11ea-879f-0f29d2eea426.png)

**Comment by paratype-andrei** [comment]
Thanks! The doc I read (https://docs.microsoft.com/en-us/typography/opentype/spec/cff2charstr) doesn't mention w?:

   3.1 CFF2 CharString Organization
   The sequence and form of a CFF2 CharString program may be represented as:
   {hs* vs* cm* hm* mt subpath}? {mt subpath}*

but the one from Adobe:
   w? {hs* vs* cm* hm* mt subpath}? {mt subpath}* endchar

**Comment by justvanrossum** [comment]
You're looking at CFF2 documentation. This is one of the differences with CFF.

**Comment by paratype-andrei** [comment]
Thanks again! I've got a lot of fun ahead of me :-)
