### ISSUE TITLE
Remove MacOS module in macCreatorType

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1978]
utils.macCreatorType uses either the `xattr` module or the `MacOS` module to do its thing. But the MacOS module has been removed from Python 3.x. If we only support 3.x, we should remove the `MacOS`-related code.

**Comment by justvanrossum** [comment]
Agreed.

**Comment by simoncozens** [comment]
Additionally if the `xattr` module is not available then `setMacCreatorAndType` *silently* fails.

**Comment by justvanrossum** [comment]
> Additionally if the xattr module is not available then setMacCreatorAndType silently fails.

This is intentional. It's a legacy thing, that is nice to have still around, but nothing more than that.
