### ISSUE TITLE
Should we respect explicit subtable breaks?

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#1989]
As part of #1910 I'm about to do some major surgery on building contextual pos/subs. The basic idea is that there are multiple strategies (format 1 / format 2 / format 3) for laying out the subtables, and the task is to organise the rules into subtables forming the most efficient grouping.

Now the question comes when there are explicit subtable breaks in the rules. Should we respect those when grouping? I would imagine the answer is yes, but I am looking at `Tests/feaLib/data/PairPosSubtable.fea` and `Tests/feaLib/data/PairPosSubtable.ttx`. I would expect this to make four subtables:

```
lookup kernlookup {
    pos A V -34;
    subtable;
    pos @group1 @group2 -12;
    subtable;
    pos @group1 @group3 -10;
    pos @group3 @group2 -20;
    subtable;
    pos @group4 @group1 -10;
    pos @group4 @group4 -10;
} kernlookup;
```

In reality, it reorders the rules into three subtables:

```
<!-- SubTableCount=3 -->
```

Is that correct? If so, then the task is to organise the rules into compact subtables regardless of what the user asks for; if not, then I need to respect subtable breaks when grouping the rules.

**Comment by khaledhosny** [comment]
AFAIK, the code should be doing that already (for most lookup types, not all), if it is not then that is probably a bug.

**Comment by khaledhosny** [comment]
In the example you are citing, `@group4` is empty (deliberately for this test IIRC), so the last subtable is ignored because it does nothing.

**Comment by khaledhosny** [comment]
> (deliberately for this test IIRC)

See baf4f560bbe2e191f71a698f84fbef9550cd9a34.

**Comment by simoncozens** [comment]
Ah, OK, that figures. So we *do* want to respect explicit subtable breaks. We don't currently support choosing alternative formats (e.g. format 2), so this is new code. I wanted to check whether or not it's acceptable to reorder rules across subtable boundaries to compress them into the best representation.

**Comment by khaledhosny** [comment]
Reordering can change the semantics of coverage overlaps, otherwise it should be fine AFAIK (coverage overlap does not make sense of course, but it can be seen in the wild either by mistake on lazy building tools not filtering duplicates).
