### ISSUE TITLE
[subset] recalculate hhea.advanceWidthMax

### ISSUE THREAD

**Issue by moyogo** [fonttools/fonttools#1993]
fontTools.subset does not update hhea.advanceWidthMax.

**Comment by arialcrime** [comment]
Wanted to report just that. Is there a way around this? Or a timeline to fix it?

**Comment by justvanrossum** [comment]
It should do that (and many other things) when passing `--recalc-bounds` to the subsetter.

**Comment by arialcrime** [comment]
Thanks for the swift reply, that solves my issue.

**Comment by moyogo** [comment]
I guess this can be closed then.
