### ISSUE TITLE
Default instance is not selectable on macOS Catalina (Fixed in macOS 11)

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#1994]
This issue has come up for me and others in several fonts, so I have worked on documenting and testing it today. 

To summarize:
1. Working in a macOS app like TextEdit, try to select the default instance of a variable font.
2. If the font’s default instance is not “Regular,” the style cannot be selected, and the style selection instead goes to something else (usually a Medium weight, for whatever reason).

It seems most likely that this is a macOS bug, so I have filed an Apple Feedback ticket `FB7734904` (leaving this here in case anyone from Apple comes across this).

However, it is also possible that there is something that could be do to the fonts to make this work.

https://github.com/arrowtype/vf-default-instance-test

A simple example: this 2-source font in which Light is the default instance:

![textedit-test_1](https://user-images.githubusercontent.com/45946693/84540213-e0995700-acc2-11ea-817a-1b7c3997650c.gif)

This happens on the following fonts, and presumably others:
- Recursive
- Commissioner
- Encode Sans
- Name Sans

Have others experienced this problem? Have you found any solutions / ways to get around it?

**Comment by jenskutilek** [comment]
I can confirm in macOS 10.13.

**Comment by jjgod** [comment]
Thanks for the detailed report. This should be addressed in macOS 11 developer seed now. Please try that once you get a chance.

**Comment by arrowtype** [comment]
Awesome, looks like this is working well in macOS 11! Thanks to you and your team for your work on this, @jjgod. (Nice session with Loïc at WWDC, too!)

![image](https://user-images.githubusercontent.com/45946693/86308295-ccbc8300-bbe6-11ea-93e3-1d700bd987d2.png)

![image](https://user-images.githubusercontent.com/45946693/86308380-0db49780-bbe7-11ea-9302-df6786440b29.png)
