### ISSUE TITLE
[ttLib.ttCollection] TTCollection memory usage

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2019]
See https://twitter.com/ken_lunde/status/1281042388132089856

`TTCollection` copies .ttc data as many times as there are fonts in the .ttc, unless `lazy=True` is passed.

The font "SourceHanNotoCJK.ttc" from https://github.com/adobe-fonts/source-han-super-otc/releases/tag/20190603 contains 216 fonts and is 389 MB big, so opening this font will (try to) use at least 88 GB of memory.

**Comment by behdad** [comment]
@justvanrossum looks like it's already implemented that you can pass `shareTables` to the TTCollection constructor.

**Comment by behdad** [comment]
It's even documented.

**Comment by behdad** [comment]
Sharing tables is implemented. It's the extra copy in TTFont that is killing it.

**Comment by behdad** [comment]
This is really stuck on https://github.com/fonttools/fonttools/pull/2330
there's nothing TTCollection-specific about it.

**Comment by behdad** [comment]
Closing as duplicate of #2330
