### ISSUE TITLE
pyftsubset sometimes can not subset punctuation correctly

### ISSUE THREAD

**Issue by AceCLee** [fonttools/fonttools#2031]
original font: 
[汉仪旗黑-80S ExtraBold.zip](https://github.com/fonttools/fonttools/files/4977848/-80S.ExtraBold.zip)
cmd param:
`pyftsubset "C:\WINDOWS\Fonts\汉仪旗黑-80S ExtraBold.ttf" "--text= !-.0124?EHILMORSTWXacehiklmoz×…「」こにのはみやらチブ一三上下不与且东丝两並个中为主举乃么之乎乙也习书乱乳乾亂了事二于云互些交人什仅今介从他代令以们任份伙会传伦伴似但住体何作你使來供侵便係促保個們倒候倫偏做停偷備傢傳僅像先光入內全兩关兴其具养内再冒冲准出击划删別刪别到制刻前副割劃力办功加动動勢勾包化区區千单即却卻历厉压厌原厭厲去参參又反发取受变口只叫可叶各同名后向吗君吧听吶吸告员呢命和咦員哦哪唯啊問啦喜喝單嗎嗯嘛嘲嘴噩回因团园圍園團在地场型城報場境增壁壓声处备复外多夜够夠夢大天太失夹夾奇奏女她好如妄始姬姿子字存学孩學它安宙定实害家實对寺封将將對小就尽屁居山工巨差己已巴市布带帮帶常幕幫干平并幹床应底店度开弃引弩強强当形彻往待很後得從微徹心必忍志忘忙快态怎怕思急怪总恐恥息悅您情惡想愉意愚感愧態慌慾應成我战戰房所手才打托扮找把抓抗护报抱拉拍招拜拾拿损捡换掉排接提換損搞摄摔撿擅擊擋擒擺攝收攻放敏教敲斗新方於无既日早时明星映昨是時景暂暫暴曆更書替最會有服期本材束来東果柔校样桃桜梅梦棄楚模樣橙次欢欲欸歉歡止正此歷死殖段母比毫求沉沒没法泽洗活流浮消深添清温源準溫溺滅滑滴漫澤灭炎炮点為烈烦無然照煩父牧物状独獎獨玉王玛现珍現球理琦瑪生產用由画略番畫當疑疼痛發白百的盡目直相看真眼着知砲硬碍碰磨礙社离种秩称程稍種究空穿立竖竟竹笑笔笛笨筆等简算管節簡籍类糊系紅級紧終組絕給絲經網緊總繁红级组终经给绝网置美羞羽翅習翻翼考者而耐耻聲聽肆肉股育胖胸能脚脸腳膀臉自與興舉舔舞般色节花苦葉著藏處虚虛虫虽蟲蠢行街衝衣表袜被装裝裡裤製複褲襪西要見規覺见规觉角解触觸計討託記許訴話該誇說誰調請諒諧謙謝證警譯護讀變讓计讨让记许证诉译话该说诶请读谁调谅谐谢谦谷象負責質负责质赞走起越趣跟路跳身躲軟軸載软轴载辛辦边达过迎近还这进远连迷退逃选這通逞連進逼過道達遠遮遵選避還邊那部都里重量錯铺错長长門閃開間關门闪问间阉队阶阻院除险隊階隔際隨險难雖離難雪雲需露青非面音題類题飛飞館馆首馬驗马验體高鬥鮮麻麼黑點！：？" "--output-file=汉仪旗黑-80S-subfont.otf"`
with the cmd param above, “…” and "U+201C" in subset font will be incorrect.
like this:
![incorrect](https://user-images.githubusercontent.com/54193973/88483524-69363300-cfa3-11ea-8e65-5d00d631185e.png)

another cmd param:
`pyftsubset "C:\WINDOWS\Fonts\汉仪旗黑-80S ExtraBold.ttf" "--text= !-.012346789?EHLMNORSWXY\abcehiklmovz ×—…「」こにのはみやら一万上下不与且世业东两严个中为主乃么义之乎也习乱乾亂了事于亏云五些亡交亮人什仅今介从他仗代以们任份伊伙会传伸似但位住体何作你使來供侣侵俏保俩修倆個倍們倒候值做偶傢傳僅像先光入內全兩公共关其兼内再决况冷净凛凜出击刚初删別刪别到制前剛副力办加劲勁勉化匙区區十千半博危即却卷卻厉压厌厕厚原厭厲去又双反发叔取受变句只叫可司各合同名后向吓吗君否吧听吸呀员呢周命和咦咬哟員哥哦哪啊問啦善喜喲喵嗎嗯嘛嚇嚴四回因围圍在地场坚型城堅場增壓士声处外多够夠夢大天太失头夺奇奔奪女她好如妄妹始娘子字存学孩學它宇守安完宙定实室害家容密實对寻封将將尋對小少就尺尽居屍工巨差己已市布希带帮帶常幕幫干平年幹应底廁开弄式引弟弩強强当彻往很後徑得從微徹心忆忍忘忙忧快态怎思性怪总恋恥恩恶您情想愁意愛感愧態慢慮憂憶懂應戀成我战戰戲所手才扑打扮找抄把护抱拍拒拥拼指挥挺捉换捲掉接插換握揮搞搬摸播擁擊支收改放故效敏救数整數文斗新方於无既日旦早时明星春昨是時暗更曾替最會有服望期本条来東极构果某柔校样根格桜梅條業極構樣次欢欲欸歉歌歡止正此死段母每比毫民決沉沒没油況法洁活流浓浮海消淨混渐温湿源溫滅滴漂演漠漸潔潮濃濕火灭灵炎点為烈烦無焰然照煩燃爱牧物牵特牽状狀独獨玉王玩现現球理琦琳生用由男界留略當疼痛癖發百的盖盡目盯直相看真眯眼着知破确碰確礼禮秀种秘积称稍種稱積穿突站竟竹笑笔笨第筆等答算管節米类粗糙約級素組絕給經維緩練總繁约级练组经绕给绝维缓缺置罵美羞群義習翻耀老考者而耐耗耶耻聊聚聞聲聽肆肉肯能脆脑腔腦腳自至與興舞色节芒花芳英茬萬著蓋處虧虫蛋蛻蛾蜕蟲行街衣补表被袭装補裝裡裸製褪襲西要覆見規視覺见规视觉解触觸討記試話該說誰請諒謂謝證識譯護變讓计讨让记设证识词译试话该说诶请谁谅谓谢象質质走赶起超越趕足跑跟路蹟身躺軸較載轉转轴载较辦边达过近还这进连迹退逃选逐途這通逛造連進過道達選還邊那郁部都醇醒里重量鋼錯鎖鎮鐵鑰钢钥铁锁错镇長閃閉開間關闪闭问间闻队阿际限除险陷隊随際隨險难雄集雌雙雜難雲需靈青静靜非靠面音頭題願類顰题颜颦飛飞首馬騷马骚體高鬥鬱魂鳥鸟麻麼黃黄點！：？" "--output-file=汉仪旗黑-80S-subfont.otf"`
“…” and "U+201C" in subset font will be correct.
like this:
![correct](https://user-images.githubusercontent.com/54193973/88484040-a9e37b80-cfa6-11ea-8225-df7669ac4d73.png)

And we tried to add "b" to the text, “…” and "U+201C" in subset font can be correctly displayed.

**Comment by AceCLee** [comment]
And we have tried other fonts randomly, they have the same problem.

**Comment by yisibl** [comment]
Did you try Source Han Sans(思源黑体)?

**Comment by AceCLee** [comment]
I didn't try Source Han Sans.

**Comment by behdad** [comment]
I can't reproduce this.
