### ISSUE TITLE
[subset] Retain GSUB Script system for Indic scripts

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#204]
Such that HarfBuzz shaper selection works the same even for subset fonts that don't need any GSUB rules.  This would also fix this:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1080739

Note that I don't want to retain all empty script systems, as that would make subsetting, eg, Arial too bulky.  And only do this for GSUB.  GPOS can remain empty.

Perhaps based on Unicode script of the retained characters...

**Comment by khaledhosny** [comment]
I believe this was fixed in https://github.com/fonttools/fonttools/issues/518.
