### ISSUE TITLE
[otvar] Rule conditionsets conflict with OT layout (shaping)

### ISSUE THREAD

**Issue by ctrlcctrlv** [fonttools/fonttools#2040]
Considering [this `.designspace`](https://github.com/ctrlcctrlv/Noto-Sans-Tagalog/blob/f73914a8fa0620059a15fc101310e51f8b359033/NotoSansTagalog.designspace#L11) excerpt:

```xml
    <rule name="ra_crossing">
      <conditionset>
        <condition name="weight" minimum="625" maximum="700"/>
      </conditionset>
      <sub name="uni170D" with="uni170D.avar"/>
    </rule>
```

And [this OTLayout feature](https://github.com/ctrlcctrlv/Noto-Sans-Tagalog/blob/f73914a8fa0620059a15fc101310e51f8b359033/features.fea#L50):

```fea
# Ra to archaic Ra
feature hist {
  lookup hist_1 {
    sub uni170D by uni171F;
  } hist_1;
} hist;
```

Why, when `hist` is active, does a `wght` &ge; 625 cause `uni170D`, shaped to `uni171F`, to become `uni170D.avar`?

To confirm that this bug exists, open https://ctrlcctrlv.github.io/baybayin/ , type <kbd>ra</kbd> as input, tick "Archaic _ra_" checkbox, and increase weight above 625.

**Comment by anthrotype** [comment]
because the rules in `rvrn` are processed first before any others, that's how rvrn works. You should add `processing="last"` attribute to your `<rules>`  element, this will make fonttools use a different feature tag (`rclt`) that respects the lookup order and will be applied last.

https://fonttools.readthedocs.io/en/latest/designspaceLib/readme.html#rules-element

**Comment by ctrlcctrlv** [comment]
Thank you :-) I was having trouble figuring out if this was a bug, or intended behavior I wasn't understanding.

**Comment by ctrlcctrlv** [comment]
By the way @anthrotype , part of the reason this is not intuitive is that it's on the `<rules>` element and not the `conditionset`s. Just something to think about: it seems strange that either _all_ the rules must be processed last or _none_ of the rules must be; unless there can be multiple `<rules>`? 🤔  But `designspaceLib` doesn't support that.

**Comment by justvanrossum** [comment]
What `.designspace` supports is a high level simplification of what is theoretically possible with FeatureVariations, based on use cases we were aware of at the time. While what you suggest is possible, it would make everything a lot more complex.

Do you have a specific use case in mind where this could be handy?

**Comment by ctrlcctrlv** [comment]
@justvanrossum Thanks for replying. Not at present, but I reserve the right to think of one! 
# 🤔 💭 
## 🤔 💭 
### 🤔 💭
