### ISSUE TITLE
struct.error in g_v_a_r.py when gvar table is too big

### ISSUE THREAD

**Issue by underware** [fonttools/fonttools#2048]
I am getting a struct.error when the gvar table is too big.
At a certain moment it is not possible anymore to merge the gvar table with a ttf.
Here the error message I get with version 4.13.0.
/fontTools/ttLib/tables/_g_v_a_r.py", line 220, in compileGlyph_
    struct.pack(">HH", tupleVariationCount, 4 + len(tuples)) + tuples + data
struct.error: 'H' format requires 0 <= number <= 65535

**Comment by anthrotype** [comment]
The OT spec only allows from 1 to 4095 tuples per glyphs (the first 12 bits of the uint16 are used to encode the `tupleVariationCount`).
https://docs.microsoft.com/en-us/typography/opentype/spec/gvar#the-glyphvariationdata-table-array

Ideally varLib should give the user a better error message than struct.error.

**Comment by anthrotype** [comment]
In the particular font that Akiem is working on, the values for `tupleVariationCount` is 34453, so it's not the count that is overflowing.

A value of 34453 means the number of tuple variation tables for that glyph is 1685 (i.e. the low 12 bit fields of 34453), and that the SHARED_POINT_NUMBERS flag (0x8000) is set (in the high 4 bits of tupleVariationCount).

It is the following uint16 field, the `dataOffset`, that is exceeding the max limits for uint16. When printing  `4 + len(tuples)` in Akiem's font it gives `411444` (which is > 65536).

The offset is from the start of the GlyphVariationData table to the serialized data. The stuff before the serialized data and immediately after the GlyphVariationData header (which is 2 shorts long, thus 4 bytes) is the array of TupleVariationHeaders. There are 1685 TupleVariationHeaders, but each of these can be variable length, depending on whether peak or intermediate tuple records are included.
https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats#tuplevariationheader

It appears that in your particular font, the length of this array of TupleVariationHeaders is so large that the offset to the serialized data (which follows it in the GlyphVariationData table) overflows the uint16 limits.
Again.. there is not much fonttools can do to fix the issue, but it can certainly provide a better error message to help the user deal with this.
Maybe in a future gvar revision we could suggest to make these counts and offsets 32-bit long.

**Comment by anthrotype** [comment]
> TupleVariationHeaders can be variable length, depending on whether peak or intermediate tuple records are included.

the size of a TupleVariationHeader also depends on the number of axes defined, since each tuple record contains an F2DOT14 coordinate (16 bits) for each of the axes in fvar. Akiem's font probably has a lot of axes.

How many axes, out of curiosity?

**Comment by underware** [comment]
> On 18 Aug 2020, at 12:22, Cosimo Lupo <notifications@github.com> wrote:
> 
> 
> TupleVariationHeaders can be variable length, depending on whether peak or intermediate tuple records are included.
> 
> the size of a TupleVariationHeader also depends on the number of axes defined, since each tuple record contains an F2DOT14 coordinate (16 bits) for each of the axes in fvar. Akiem's font probably has a lot of axes.
> 
> How many axes, out of curiosity?
> 
Around 50...

But just to double-check: the gvar table which I am trying to merge with this font only has 7 axis. What I would like to do is to ‘spread’ the deltas on various axis. The 7 axis of the original font are of course included in the 50 axis font.

It would be great if there would be a work-around or solution to get this done.

Greetings, 
Akiem

**Comment by anthrotype** [comment]
ah! maybe that explains why after increasing the fvar axis count from 7 to 50, your gvar doesn't compile any more. Each tuple records in your 1685 TupleVariationHeaders will get (50 - 7) * 2 bytes bigger (2 bytes for each added axis). I don't see any other solution that reducing the number of axes... :(

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axis, if can not compile 50+ axis.

**Comment by underware** [comment]
Hmm, shouldn't that be changed in the future?
I mean what's the logic of 64k possible axes, if can not compile 50+ axes.

**Comment by justvanrossum** [comment]
(Let's also not forget that 1685 tuples (1686 masters!) for a single glyph is a _huge_ number no matter how you look at it...)

**Comment by anthrotype** [comment]
> (1686 masters!) for a single glyph is a huge number

right.. So to fit with the current gvar, you'd either have to reduce the number of axes or the number of masters until it compiles. There's probably an equation for that but I'm too lazy right now.

**Comment by underware** [comment]
I agree that 1685 tuples for one glyph _may currently_ sound like a huge number. 

And I only realised that it is 1685 after Cosimo asked me about it. Linking this number to masters (read UFO's) though can be a bit confusing, because depending on your design-process you may not have any masters at all.

While I am aware of the need for effective data-types, I am at the same time wondering if we would accept a limitation of points per glyph (because of data-types)? Saying this, I believe that when we can make a font with 64.000 glyphs with 1 tuple per glyph, we should also be able to compile a font with 1 glyph with 5000+ tuples. This seems to be fair to me.

**Comment by justvanrossum** [comment]
There are all kinds of limits all over the place in OpenType. Keep in mind that gvar was developed more than 25 years ago, at a time when it was a small miracle to have a font with three axes and eight masters... It is no wonder the format starts creaking at the seams when pushed to the limits, and it is another small miracle that it still works as well as it does under most circumstances today.

That said: I'm looking forward to a future when there will hopefully be font formats with fewer arbitrary limitations.

**Comment by behdad** [comment]
I plan to address this in my updates to OpenType Variations. But other than that there's nothing we can do here.
