### ISSUE TITLE
Feature request: allow designspace files to control both rvrn & rclt, rather than forcing an either/or option

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#2050]
Currently, the `rules` element in a designspace must _either_ make all substitutions before or after all other opentype feature substitutions. As @anthrotype explained it in https://github.com/fonttools/fonttools/issues/2040:

> the rules in `rvrn` are processed first before any others, that's how `rvrn` works. You should add `processing="last"` attribute to your `<rules>` element, this will make fonttools use a different feature tag (`rclt`) that respects the lookup order and will be applied last.

In that issue, the conclusion presented by @ctrlcctrlv is:

> it seems strange that either all the rules must be processed last or none of the rules must be; unless there can be multiple <rules>? 🤔 But designspaceLib doesn't support that

@justvanrossum responded with:

> What .designspace supports is a high level simplification of what is theoretically possible with FeatureVariations, based on use cases we were aware of at the time. While what you suggest is possible, it would make everything a lot more complex.
> 
> Do you have a specific use case in mind where this could be handy?

I agree with @ctrlcctrlv, and in respond to Just’s question, I do have a use case:

In Recursive (as of [`dc36c9e`](https://github.com/arrowtype/recursive/tree/dc36c9e450a6115e4bd832f62578526902e45e4b)), there is a relatively complex set of `rules` to activate cursive italics & mono or sans-specific glyphs at various axis locations. Many of these glyph substitutions are then used in logic by other OT features, so by now it would very likely be disruptive to the family to now change the rules with `processing="last"`.

_But_, I am now trying to make arbitrary fractions possible, where the fraction bar is split in the default proportional/“Sans” styles (`MONO < 0.5`) but solid in the monospaced/“Mono” styles (`MONO >= 0.5`). 

The intent is for the default to use `fraction.split`, and the mono to use `fraction`.

This`frac` feature relies on detecting the `slash` and subbing it for a `fraction.split` (plus subbing in numerators/denominators for numbers). 

But because `rvrn` happens first, it requires a workaround for `frac` to work afterwards. The font has to have a `slash.split` glyph which is subbed in by `rvrn` rules, so the `frac` logic can be basically `sub [fraction.split fraction] by [slash.split slash]`. And unfortunately, right now adding the extra glyph is breaking the static build for mysterious reasons which are still being determined. Ironically, the sub with the `slash.split` seems to be throwing the Recursive build for a recursive loop. 😅 Probably, that extra glyph needs to be decomposed... But in any case, you can probably see how this becomes a hacky workaround, and requires extra/redundant glyphs to be added to fonts.

If it were possible to control both `rvrn` and `rclt` via a designspace, this logic would be much simpler to set up, and designers would have a helpful extra bit of flexibility to decide when an axis-based substitution should happen, relative to other features.

Without that flexibility, it is now necessary to either have to keep the otherwise-unnecessary `slash.split` & debug the build, or else overhaul the whole set of substitution logic to allow `rclt` (which may or may not be possible with the current system of features).

So, this may best be summarized as:

Question: When does a designspace need to be able to control both rvrn & rclt?
Answer: It needs it when it needs it 😄

I suspect this will become more necessary as more complex variable font projects are made. Once you get 99% of your gsub working with rules processing first, it is really painful to run into this problem at the last 1%.

## How might this look in a designspace file?

I see three main possibilities:

1. My preference: `processing="last"` could be placed in a `<rule>` element, so the designspace would continue to only have a single `rules` element with multiple rules inside.
2. Alternatively, a user could have multiple `<rules>` elements, e.g. it would be fine to have both `<rules>` and `<rules processing="last">` in one designspace.
3. A less attractive option: `processing=last` could conceivably even make sense at the individual `sub` element level, too. However, I feel like this wouldn’t be helpful, as it would encourage users to mix up `rvrn` and `rclt` subs, without a very clear benefit.

Of course, I realize that if Just says “it would make everything a lot more complex” to implement this, it is probably beyond my current understanding just how much complexity it might add. But, I do think there are a good number of scenarios in which people would appreciate the flexibility, so I wanted to cite one such case here. Thanks!

**Comment by juandelperal** [comment]
Thanks @arrowtype for filling this issue, and @justvanrossum for the deep explanation.
I just wanted to add my 2 cents here: even though life is easier with rules last, at this time Adobe doesn't seems to support `rclt`, so if your fonts happens to be "adobe users oriented", you might be in problems.
I added some tests in https://github.com/fonttools/fonttools/issues/2079

**Comment by tphinney** [comment]
If anybody cares about the Adobe issue, the place to register your concern is here, I think: https://indesign.uservoice.com/forums/601180-adobe-indesign-bugs/suggestions/45229612-indesign-should-apply-variating-substitutions-from

**Comment by ctrlcctrlv** [comment]
I voted on the issue at that link, you only need a Google account to do it, thankfully.

**Comment by anthrotype** [comment]
Have you tried seeing if maybe using `calt` instead of `rclt` works?

**Comment by tphinney** [comment]
Maybe in addition to would be wisest? I am sure that could be hacked in as a post-process.
But just to test, I will try 'calt' right now....

**Comment by tphinney** [comment]
Brilliant. That works in InDesign at least, and I suspect it will in other CoolType apps (at least those that have 'calt' on which should include Illustrator and Photoshop at least).

This means people can turn it off when we don’t want that to even be an option, but compared to “doesn’t work at all” that is a pretty huge improvement.

I hope Adobe will fix it, but this is super helpful. Thanks Cosimo!  😊

**Comment by tphinney** [comment]
BUT, again I need BOTH in the final font. Currently I can only do either/or in designspace.  :(

**Comment by justvanrossum** [comment]
> BUT, again I need BOTH in the final font.

Can you briefly describe why?

**Comment by anthrotype** [comment]
I suppose to catch two birds with one stone. If both features reference the same substitution lookup, result should be idempotent even when both are enabled

**Comment by tphinney** [comment]
@anthrotype That is my current assumption for how we will do it. It is the kind of hackery I don’t like adding to the build chain automation, but will if I have to.

@justvanrossum 'calt' is on by default but is something users can turn off. I will do this hack to make things work in Adobe’s broken apps, but other than that, I don’t want this axis functionality to have a separate (and non-obvious) override from an OpenType feature that is under user control. Therefore both instead of just 'calt'.

**Comment by anthrotype** [comment]
note I was referring to calt + rclt (both applied last, only the former working in indesign), not both rvrn + rclt (first and last) which don't make much sense to me

**Comment by justvanrossum** [comment]
So (if I'm getting this straight), the desire to do both calt and rclt simultaneously is to work around an Adobe bug. I don't see why the designspace format should even be accomodating this. This is a typical case for a gftools-like afterburner tool.

**Comment by tphinney** [comment]
That’s fair.

**Comment by twardoch** [comment]
What if I want the same feature variations be accessible via both "ss01" and "salt"? This has nothing to do with "an Adobe bug". 

The OT feature definitions allow assigning the same lookup to many features, AFDKO supports it and it's been a standard element of many people's normal workflows. 

Why assigning the same feature variations to multiple features should not be given the same treatment, I'm not sure. :)
