### ISSUE TITLE
Disable checksum-checking

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#2057]
In sfnt.py, the `SFNTReader` constructor defaults to `checkChecksums=1`. I suggest we default to off.

**Comment by khaledhosny** [comment]
Because no one checks or needs to check for them. What does it mean practically if the checksum is wrong?

**Comment by justvanrossum** [comment]
The TTFont constructor actually has `checkCheckSums` set to False by default, it's only the SFNTReader's constructor that has it set to 1.

**Comment by anthrotype** [comment]
> The TTFont constructor actually has checkCheckSums set to False by default, it's only the SFNTReader's constructor that has it set to 1.

Ah ok, sorry, I misunderstood. In that case it make sense to align SFNTReader to the TTFont default value.
We should use a bool type instead of an int 0/1 value.

**Comment by alerque** [comment]
@anthrotype See my commit message for 7e3c4ac, it is not an INT 0/1 value, it is an INT 0/1/2 value — hence using boolean type is not appropriate.

**Comment by behdad** [comment]
Thank you all.

I didn't realize that this is off in TTFont. My intention was to turn it off in TTFont, because checksum-checking serves no purpose and as such should be disabled to damage the planet less.

I should have known better though, since in 10 years of using this tool I never saw a checksum-mismatch warning.

Anyway. Turning off in SFNTReader is okay, but also insignificant.  Cheers

**Comment by behdad** [comment]
> If it's only the desire to remedy the logic dissonance of the different defaults between TTFont and SFNTReader, then I am not sure this is really worth it, considering this has been like this for more than 20 years and nobody ever complained.

I'm pushing towards deprecating checksums in SFNT and that's why I opened this as well.

**Comment by anthrotype** [comment]
thanks Behdad for the clarification. FWIW I also in favour of deprecating checksums.
