### ISSUE TITLE
issues while attempting to reorder glyphs in a TTFont

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#2060]
TTFont.setGlyphOrder() simply does what it says on the tin, it sets the TTFont.glyphOrder list.
This works ok when one wants to _rename_ existing glyphs while keeping the same order (e.g. like ufo2ft.postProcessor does for uniXXXX names).
However, if one wants to _reorder_ glyphs (i.e. keeping the same names but changing the glyph indexes) in a font, simply doing TTFont.setGlyphOrder() and TTFont.save() may or may not achieve the result depending on the current state of the TTFont: i.e. depending on whether a given table (that uses this glyphOrder upon save/compile) had in turn been fully decompiled beforehand or not. That's because by design fonttools won't attempt to re-compile (and thus potentially update glyph indexes of) a table that was not previously loaded.

This is further complicated by the fact that some tables (e.g. glyf, OT layout ones, etc.) use the TTFont.lazy attribute to decide whether to fully decompile themselves on read, whereas others like cmap seem to always be decompiled lazily, no matter the lazy attribute.

Moreover, if a TTFont was not opened with lazy=False, there's no straightforward way to make that TTFont instance "eager" or non-lazy (it works if I save to temporary stream and re-open with lazy=False, but seems unelegant).

My immediate problem is I need to re-order glyphs of an existing TTFont in order to make use of OT-SVG glyph sharing feature, whereby glyphs defined within the same OT-SVG document must have contiguous glyph indexes (being referenced as ranges with min/max glyph IDs).

I wish fonttools provided an easier way to change glyph indexes without me having to remember to un-lazify the various tables that use such glyph indexes.

Granted, I could -- should? -- circumvent the issue by computing the final glyphOrder before my TTFont is generated to avoid having to modify its glyphOrder later in the build. But before I end up doing that, I wonder if anybody else faced a similar problem.

**Comment by justvanrossum** [comment]
How about:
- new method to reorder, say `ttf.reorderGlyphs(...)`
- this method requires `lazy` to be False (will throw an error when lazy=True)
- loads all tables (perhaps warns when there are tables that fonttools doesn't know about)
- has some workaround for tables that load lazily even when lazy=False, such as cmap

How difficult this is to implement probably depends on how many tables always load lazily, regardless of the lazy flag.

**Comment by anthrotype** [comment]
> this method requires lazy to be False (will throw an error when lazy=True)

to make this work on lazy TTFonts as well (lazy=True or None), we could save them to temporary BytesIO, re-open them with lazy=True, load all tables from this new TTFont object, and replace all the current TTFont's tables with the new, eagerly loaded ones. Perhaps not very elegant but should work.

**Comment by anthrotype** [comment]
There's another problem while reordering glyphs. The `_g_l_y_f` table module has a `glyphOrder` attribute that is set on decompile/fromXML to the `ttFont.getGlyphOrder()`; but when one does `ttFont.setGlyphOrder(reordered_glyphs)` only the `TTFont.glyphOrder` attribute is set, whereas the glyf table's `glyphOrder` is still the old one... `TTFont.setGlyphOrder` does not update the list in place but resets the attribute to the new value -- the old list is still held by the glyf table object.
I see also fontBuilder and fontTools.subset have to directly update the glyf.glyphOrder when the font glyphOrder is created or changed.
I am wondering we should automatically set the glyf's glyphOrder (only if the glyf is loaded) whenever one calls TTFont.setGlyphOrder()?

```diff
diff --git a/Lib/fontTools/ttLib/ttFont.py b/Lib/fontTools/ttLib/ttFont.py
index 9948d4e2..692f99ac 100644
--- a/Lib/fontTools/ttLib/ttFont.py
+++ b/Lib/fontTools/ttLib/ttFont.py
@@ -451,6 +451,8 @@ class TTFont(object):
                self.glyphOrder = glyphOrder
                if hasattr(self, '_reverseGlyphOrderDict'):
                        del self._reverseGlyphOrderDict
+               if self.isLoaded("glyf"):
+                       self["glyf"].setGlyphOrder(glyphOrder)

        def getGlyphOrder(self):
                """Returns a list of glyph names ordered by their position in the font."""
```

**Comment by behdad** [comment]
> > I think we should just always sort the glyphs by gid regardless ...
> 
> actually, it's not that easy, because changing the Coverage glyphs order also changes the samantics for all the subtables that are ordered by Coverage index which is like almost all lookup subtables..

Exactly..................

**Comment by behdad** [comment]
> Now, we do have code to fix this for Format2 Coverage tables (range-based), but we don't also fix it for simple Format1 Coverages:

It's better than you think. If brokenOrder, we use Format2:
https://github.com/fonttools/fonttools/blob/71a5bf1b512e51044fe2af31d86f2e73bd3a3eaa/Lib/fontTools/ttLib/tables/otTables.py#L566

So, it kinda works...

**Comment by rsheeter** [comment]
The current experience is pretty confusing. glyf used to cache glyph order, one thing logs it fixes itself but others neither log nor fix themselves, ... fun times. 

We have exploratory code in nanoemoji that goes and reorders coverage, including reordering any parallel lists. As far as I know nothing in the current metadata tells you that this list is in the same order as that coverage so Cosimo kindly made a list of everything we need to repair. As Just notes, it's kind of a long list. 

Once we are convinced that code works well we could consider upstreaming.

**Comment by behdad** [comment]
> Once we are convinced that code works well we could consider upstreaming.

Yes please. We also need this in the merger.

**Comment by rsheeter** [comment]
> We also need this in the merger

Amusingly I need it for a process that involves merging parts of two fonts.

**Comment by behdad** [comment]
> whereby glyphs defined within the same OT-SVG document must have contiguous glyph indexes (being referenced as ranges with min/max glyph IDs).

Is this true? Different ranges can have the same offset/length to reuse the same SVG.

**Comment by rsheeter** [comment]
> Different ranges can have the same offset/length to reuse the same SVG

https://learn.microsoft.com/en-us/typography/opentype/spec/svg#svg-document-list agrees, "Two or more records can point to the same SVG document. In this way, a single SVG document can provide glyph descriptions for discontinuous glyph ID ranges. "

Amusingly I'm quite sure we wrote code believing this was not the case during the development of nanoemoji.

**Comment by anthrotype** [comment]
I'll take the blame :)

**Comment by rsheeter** [comment]
I demand a share of the blame!
