### ISSUE TITLE
Help on getting numFonts for TTC

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fonttools#2072]
Hello.

I am new to Python and in the process of writing a program to process fonts. I am trying to do the following 2 things:
1. get the number of fonts in a TTC.
2. get the individual names for each font in a TTC.

I deduced that (1) is possible as FontTools are able to detect the number of fonts here:
https://github.com/fonttools/fonttools/blob/0b413be45a92bb75e64362c1e38309f41d06cafd/Lib/fontTools/ttLib/sfnt.py#L60

How can I access the numFonts? It seemed to be linked to `sfnt.readTTCHeader` (https://github.com/fonttools/fonttools/blob/0b413be45a92bb75e64362c1e38309f41d06cafd/Lib/fontTools/ttLib/sfnt.py#L598) but I can't figure out what goes into the `file` variable.

Thanks in advance.

**Comment by justvanrossum** [comment]
Question 1: the easiet way is to use the TTCollection class:

```python
from fontTools.ttLib.ttCollection import TTCollection

ttc = TTCollection("/path/to/myfonts.ttc")
print(len(ttc))
```

For your second question you will need to look at the name table of each individual font. Something like this should work:

```python
from fontTools.ttLib.ttCollection import TTCollection

ttc = TTCollection("/path/to/myfonts.ttc")
for font in ttc:
    print(font["name"].getName(4, 3, 1))
```

**Comment by justvanrossum** [comment]
Note that you should use `lazy=True` due to issue #2019.

**Comment by NightFurySL2001** [comment]
ok i got it, thanks a lot for your help! There seems to be little to none info for the TTCollection so that confused me for a looooong time.... 😭

**Comment by twardoch** [comment]
Though it's rather rare, note that several fonts in a TTC can share the same name table.

**Comment by NightFurySL2001** [comment]
Thanks for the info. For my purpose of checking what characters are available in a font, I'll just need to check the characters available in a user-choosable font, which i would (hopefully) assume that the font makers are aware of what they're doing 🤣

Program here: github.com/NightFurySL2001/CJK-character-count

Side rant: tkinter is so hard. Im just a newbie torturing myself with tkinter…

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
