### ISSUE TITLE
[varLib] Possible bug in varStore.py?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2073]
I am trying to learn how VarStores work, and am running into a bit of source code that looks off, even though I'm not sure I fully understand what's going on there.

Compare this fragment:
https://github.com/fonttools/fonttools/blob/e4b0486b31a50c368a794bb20692903ee55313e5/Lib/fontTools/varLib/varStore.py#L71-L73

With this:
https://github.com/fonttools/fonttools/blob/e4b0486b31a50c368a794bb20692903ee55313e5/Lib/fontTools/varLib/varStore.py#L107-L111

Shouldn't the former also test for `0xFFFF` instead of `0xFFF`?

**Comment by anthrotype** [comment]
yeah, looks like a typo to me

**Comment by anthrotype** [comment]
ItemVariationData.ItemCount is a uint16 so there can be max `0xFFFF` items (deltaset rows) per VarData subtable
