### ISSUE TITLE
Rules order. Browsers vs Adobe Apps

### ISSUE THREAD

**Issue by juandelperal** [fonttools/fonttools#2079]
We are having trouble with the consistency of how rules work across different software.
Maybe this is an Adobe bug, but I wanted to know how this could be addressed.

The desired behavior is 
`oslash` -> `oslash.bold`
`oslash.sc` -> `oslash.sc.bold`

Using rules with `first` works well in Illustrator but replaces `oslash.sc` by `oslash.bold` in Chrome
Using rules with `last` works well in Chrome but doesn't do anything in Illustrator.

<img width="1284" alt="screenshot" src="https://user-images.githubusercontent.com/2414972/95331974-0c140300-08ab-11eb-92d9-72c2db871960.png">

I posted the files here:
https://github.com/juandelperal/FonttoolsRulesTest

You can take a look at the design space here
https://github.com/huertatipografica/Alegreya/blob/78b3afbdde40327e4e57a0427242951198fb82d8/sources/Alegreya.designspace

**Comment by justvanrossum** [comment]
It is because Adobe doesn't support 'rclt' in the apps you've tested with (support for this feature is neccesary to implement "last" behavior).

I'm not sure, but perhaps switching to the Adobe "World-Ready Composer" can make a difference.

**Comment by juandelperal** [comment]
<img width="915" alt="Screen Shot 2020-10-07 at 14 56 23" src="https://user-images.githubusercontent.com/2414972/95333709-6910b880-08ad-11eb-8a7e-7d177f04efb1.png">

**Comment by justvanrossum** [comment]
A workaround is to build with "first", and add a `oslash.bold -> oslash.sc.bold` substitution to your smcp feature.

**Comment by juandelperal** [comment]
Thanks Just!
I can confirm that Illustrator doesn't make the substitutions with any of these options:

![image](https://user-images.githubusercontent.com/2414972/95334763-cf4a0b00-08ae-11eb-9f7f-e637834800b2.png)



OK, will give it a try to your workaround. Thanks

**Comment by juandelperal** [comment]
InDesign Word-Ready paragraph composer doesn't support `rclt` either. 
As this font and others I am working have many users using in Adobe apps, is there a chance that we can use last and specify a different feature tag instead of `rclt` for this?

**Comment by justvanrossum** [comment]
You'd need a feature that is always on, and is traditionally a GSUB feature (Adobe apps like to distinguish GPOS and GSUB more than needed). `rclt` is exactly that, and I don't know of another one that Adobe does support. Potentially you could hack it onto `calt`, but then the user can turn it off.

**Comment by juandelperal** [comment]
Thanks Just!
I changed the tag using ttx. 
By using last with `calt` instead of `rclt` now the default is OK both in Adobe and Chrome:

<img width="1204" alt="screenshot" src="https://user-images.githubusercontent.com/2414972/95345248-d2e38f00-08ba-11eb-8468-c76ae80531f2.png">
<img width="927" alt="Screen Shot 2020-10-07 at 16 22 11" src="https://user-images.githubusercontent.com/2414972/95345106-b182a300-08ba-11eb-9e05-3ae1b81baf28.png">

I know this could allow user to deactivate the substitutions, but it's less tragic than don't having any possibility for using rules  in Adobe.

**Comment by juandelperal** [comment]
Anyway, if you think we can use a another feature enabled by default it would be great.

**Comment by justvanrossum** [comment]
> Anyway, if you think we can use a another feature enabled by default it would be great.

@anthrotype, we could use a DesignSpace lib key for this, what do you think? Might be useful for glyphsLib, too.

**Comment by anthrotype** [comment]
yes, a designspace lib key would be nice

**Comment by justvanrossum** [comment]
Ok, I'll work on a PR. In the meantime, what would be the correct lib key prefix? It will be read by fontTools.varLib.

**Comment by anthrotype** [comment]
use a prefix like `"com.github.fonttools.designspaceLib.*"`, like we already do in ufoLib or feaLib

**Comment by punchcutter** [comment]
I have reported the `rclt` issue in Adobe apps to the relevant teams.

**Comment by anthrotype** [comment]
Thanks Zachary!

**Comment by khaledhosny** [comment]
I think there should be support for explicitly setting the feature tag, since no single (or couple of) feature tag will work with all situation. Due to the mess that is OpenType script-specific shaping, different features are enabled by default for different scripts, and even the same feature tag might be applied at different stags (grouped with other features or not), so a feature tag that works for, say, Latin for “late” processing, might not have the same effect in Arabic or Devanagari.

**Comment by khaledhosny** [comment]
Never mind, that is the consensus already!

**Comment by justvanrossum** [comment]
But feel free to review #2080 :)
