### ISSUE TITLE
Issue with addMultilingualName

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fonttools#2084]
I'm currently trying to add a nameID entry to my font. It keeps giving me this error:
```
File ".\rename_font.py", line 42, in add_font_name
    ttTableName.addMultilingualName(namerecord_list, name_list, ttFont=tt, nameID=1127, windows=True, mac=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\fontTools\ttLib\tables\_n_a_m_e.py", line 269, in addMultilingualName
    self.names = []
AttributeError: 'list' object has no attribute 'names'
```

Simplified code as below:
```
tt = ttLib.TTFont(font_path)
namerecord_list = tt["name"].names
string_name1127 = "English unique font"
name_list = {"en":string_name1127}
ttTableName.addMultilingualName(namerecord_list, name_list, ttFont=tt, nameID=1127, windows=True, mac=False)
```
From the [docs](https://fonttools.readthedocs.io/en/latest/ttLib/tables.html?highlight=table__n_a_m_e#fontTools.ttLib.tables._n_a_m_e.table__n_a_m_e):
> ‘names’ is a dictionary with the name in multiple languages, such as {‘en’: ‘Pale’, ‘de’: ‘Blaß’, ‘de-CH’: ‘Blass’}. The keys can be arbitrary IETF BCP 47 language codes; the values are Unicode strings.

My suspection is that https://github.com/fonttools/fonttools/blob/b1cb5ce1e5c334878db364de65dd3c6143f0769e/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L269 should have been `self.names = {}` but wellll… I'm just a beginner lol.

Thank you in advance.

**Comment by justvanrossum** [comment]
You're not showing what `ttTableName` is, but I suspect it is not tt["name"], as it should be. Or rather, in the simplified code your call should look like this:

```
tt["name"].addMultilingualName(namerecord_list, name_list, ttFont=tt, nameID=1127, windows=True, mac=False)
```
Yes, I can reproduce your error when ttTableName refers to the name table class, but that's not correct.

**Comment by justvanrossum** [comment]
Correction:
```python
tt["name"].addMultilingualName(name_list, ttFont=tt, nameID=1127, windows=True, mac=False)
```

**Comment by NightFurySL2001** [comment]
Oops, I forgot that lol.
ttTableName is the importing from module:
```
from fontTools.ttLib.tables._n_a_m_e import table__n_a_m_e as ttTableName
```
Ill check that when I have the time. Thanks.

**Comment by NightFurySL2001** [comment]
Checked, it is the issue. Thanks for the help.

**Comment by justvanrossum** [comment]
> But doesn't adding the tt['name'] as the parameter self works too?

Yes, `MyClass.methodName(instance, ...)` is often equivalent to `instance.methodName(...)`, but the latter is the usual way to write it in Python.
