### ISSUE TITLE
font2svgs?

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#2087]
Is there a fonttools snippet anywhere to do what https://github.com/shinnn/node-font2svg does - to take a font as input and output a set of SVGs, sort of an inverse to https://github.com/fonttools/fonttools/blob/master/Snippets/svg2glif.py ? :)

**Comment by justvanrossum** [comment]
Should be relatively easy to do with drawbot-skia.

**Comment by twardoch** [comment]
hb-view can also do it, or FreeType, or with the SVGPen from

https://github.com/adobe-type-tools/opentype-svg/blob/master/lib/opentypesvg/fonts2svg.py

**Comment by twardoch** [comment]
Actually
https://github.com/adobe-type-tools/opentype-svg/blob/master/lib/opentypesvg/fonts2svg.py
should do just what you need

**Comment by khaledhosny** [comment]
Here is a quick one:
```python
import sys

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ufoLib.filenames import userNameToFileName

font = TTFont(sys.argv[1])

os2 = font["OS/2"]
hmtx = font["hmtx"]

glyphset = font.getGlyphSet()
glyphorder = font.getGlyphOrder()
for name in glyphorder:
    glyph = glyphset[name]
    pen = SVGPathPen(glyphset)
    glyph.draw(pen)

    width, lsb = hmtx.metrics[name]
    height = os2.sTypoAscender - os2.sTypoDescender

    svg = f"""<?xml version="1.0" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="{lsb} 0 {width} {height}">
  <g transform="matrix(1 0 0 -1 0 {os2.sTypoAscender})">
    <path fill="currentColor" d="{pen.getCommands()}" />
  </g>
</svg>
    """

    with open(userNameToFileName(name) + ".svg", "w") as fp:
        fp.write(svg)
```

**Comment by behdad** [comment]
svgPathPen kinda does this now.

**Comment by behdad** [comment]
Feel free to improve.
