### ISSUE TITLE
SVGPathPen closes open paths

### ISSUE THREAD

**Issue by martinleopold** [fonttools/fonttools#2089]
I'm using SVGPathPen to transform SVG paths, something like this:
```python
from fontTools.svgLib.path import parse_path
from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
		
path = 'M 25 25 L 50 75 L 75 25' # V-shaped path
transform = fontTools.misc.transform.Transform().scale(10)
svgpen = SVGPathPen(None)
pen = TransformPen(svgpen, transform)
parse_path(path, pen)
transformed_path = svgpen.getCommands() # M250.0 250.0 500.0 750.0 750.0 250.0Z  # <-- added 'Z'; path is closed; triangle shape instead of V
```
The problem I'm facing is that SVGPathPen seems to close ALL paths, by automatically adding a closePath command in the end:
https://github.com/fonttools/fonttools/blob/10413d947ad92c2f307d7b61de06d7144e4e0198/Lib/fontTools/pens/svgPathPen.py#L166

Is there a specific reason to do this? I think this is a bug, and the line should be removed.
Alternatively, a `closePaths` switch could be added to the SVGPathPen constructor which defaults to `True` to not break existing programs.

**Comment by behdad** [comment]
Pull Request will be accepted.

**Comment by anthrotype** [comment]
it's arguably a bug more than a feature that was there in the original version of this code => https://github.com/typesupply/ufo2svg/blob/master/Lib/ufo2svg/svgPathPen.py

in the pen protocol, endPath should not close, there's closePath for that.

**Comment by behdad** [comment]
I think we should remove that `_closePath` call. @justvanrossum?

**Comment by justvanrossum** [comment]
I'm not familiar with this code, but the `_closePath()` call indeed seems wrong there.

**Comment by anthrotype** [comment]
> I think we should remove that _closePath call. @justvanrossum?

sgtm
