### ISSUE TITLE
[Merge] Cannot merge several font files

### ISSUE THREAD

**Issue by arttet** [fonttools/fonttools#2091]
I have [NotoSerif-Italic.ttf](https://www.google.com/get/noto/#serif-lgc) and [NotoSerifCJKjp-Regular.otf, NotoSerifCJKkr-Regular.otf, NotoSerifCJKsc-Regular.otf, NotoSerifCJKtc-Regular.otf](https://www.google.com/get/noto/help/cjk/).

I need to merge all these fonts. The result should include italic font for English and regular font for CJK.
So, I had used `fonttools merge`, but I got the exception:
```
  File "\afdko_env\lib\site-packages\fontTools\cffLib\__init__.py", line 1062, in __getitem__
    charString = self.charStrings[name]
KeyError: 'cid00001#1'
```

- Version fonttools: v4.16.1
- OS Version: Windows 10

Steps to Reproduce:

1. `fonttools merge NotoSerif-Italic.ttf NotoSerifCJKjp-Regular.otf NotoSerifCJKkr-Regular.otf NotoSerifCJKsc-Regular.otf NotoSerifCJKtc-Regular.otf`

[NotoSerif-Italic.zip](https://github.com/fonttools/fonttools/files/5408813/NotoSerif-Italic.zip)
[NotoSerifCJKjp-Regular.zip](https://github.com/fonttools/fonttools/files/5408826/NotoSerifCJKjp-Regular.zip)
[NotoSerifCJKkr-Regular.zip](https://github.com/fonttools/fonttools/files/5408827/NotoSerifCJKkr-Regular.zip)
[NotoSerifCJKsc-Regular.zip](https://github.com/fonttools/fonttools/files/5408822/NotoSerifCJKsc-Regular.zip)
[NotoSerifCJKtc-Regular.zip](https://github.com/fonttools/fonttools/files/5408817/NotoSerifCJKtc-Regular.zip)

**Comment by khaledhosny** [comment]
Regardless of the error message, what you want can’t be achieved:
* You can’t merge fonts with `glyf` table (*.ttf) with fonts with `CFF` table (*.otf).
* Noto CJK fonts contain 65535 glyphs each, which the maximum number of glyphs possible in OpenType, so they can’t take anymore glyphs.

**Comment by arttet** [comment]
How can I replace the regular font with the italic font for English into CJK?

**Comment by khaledhosny** [comment]
No guarantee this will work, but you can try:
* Convert the italic font using [`otf2ttf.py`](https://github.com/fonttools/fonttools/blob/master/Snippets/otf2ttf.py)
* Sunset the Latin glyphs out of the CJK fonts using `fonttools subset` (i.e. keeping all characters except Latin).
* Merge each of the CJK fonts with the Latin individually.

**Comment by arttet** [comment]
I had tried to do these steps.

I run this script:
```sh
otc2otf NotoSerifCJK-Medium.ttc
otf2ttf NotoSerifCJKjp-Medium.otf

python filter_unicode_characters.py NotoSerifCJKjp-Medium.ttf NotoSerifCJKjp-Medium.codes

fonttools subset NotoSerifCJKjp-Medium.ttf ^
    --output-file=New-NotoSerifCJKjp-Medium.ttf ^
    --unicodes-file=NotoSerifCJKjp-Medium.codes ^
    --layout-features='*' ^
    --glyph-names --symbol-cmap --legacy-cmap --notdef-glyph --notdef-outline ^
    --recommended-glyphs --name-IDs='*' --name-legacy --name-languages='*' ^
    --hinting-tables=''

fonttools merge New-NotoSerifCJKjp-Medium.ttf NotoSerif-MediumItalic.ttf
```

But I have got the error.
```
  File "afdko_env\lib\site-packages\fontTools\merge.py", line 88, in sumDicts
    d.update(item)
TypeError: 'NotImplementedType' object is not iterable
```

I use the script to remove glyphs:
```python
#!/usr/bin/env python3

import itertools
import sys

from fontTools.ttLib import TTFont
from fontTools.unicode import Unicode


def main():
    filename: str = sys.argv[1]
    output: str = sys.argv[2]

    with TTFont(filename, 0) as ttf:
        chars = itertools.chain.from_iterable(
            [y + (Unicode[y[0]],) for y in x.cmap.items()] for x in ttf["cmap"].tables)

        with open(output, "w") as file:
            for char in list(chars):
                decimal_code, _, title = char
                if 'CJK' in title:
                    file.write("U+{:02X}\n".format(decimal_code))


if __name__ == '__main__':
    main()
```

I can save the font to a file:
```sh
fontplot2 New-NotoSerifCJKjp-Medium.ttf
```
The result of `fonttools subset` is OK. 
However, I couldn't merge two fonts.

Could you give me a piece of advice?

**Comment by NightFurySL2001** [comment]
@arttet I actually had the same problem, here's my code:
```
#import font subsetting
import sys
from fontTools import subset
import os

###get glyph list###
from itertools import chain
from fontTools.ttLib import TTFont
from fontTools.unicode import Unicode

def font_import(filename, font_id=-1):
    #open font with given number
    ttf = TTFont(filename, 0, allowVID=0,
                    ignoreDecompileErrors=True,
                    fontNumber=font_id)
    #get font glyph list from CFF/glyf
    glyph_list = ttf.getGlyphOrder()
    return glyph_list
    #close font
    ttf.close()
###end of get glyph list###

#options for subsetter
def _get_default_options():
    opt = subset.Options()
    opt.name_IDs = ["*"]
    opt.name_legacy = True
    opt.name_languages = ["*"]
    opt.notdef_outline = True
    opt.recalc_bounds = False
    opt.recalc_timestamp = False
    opt.recommended_glyphs = True
    opt.glyph_names = True
    opt.legacy_cmap = True
    opt.symbol_cmap = True
    opt.prune_unicode_ranges = False
    return opt 


font_file = "input_font.ttf"
subset_file = "characters-to-be-removed.txt"
output_name = "output_font.ttf"

#get glyph list from font
font_list = font_import(font_file)

glyph_remove = []
for lines in open(subset_file, encoding="utf-8"):
    uni_char = lines.strip("\r\n") #unicode glyph name
    uni_name = "u" + str(hex(ord(uni_char)))[2:].upper()
    glyph_remove.append(uni_name)

font_glyph_list=[]
for glyph in font_list:
    if glyph in glyph_remove:
        continue
    else:
        font_glyph_list.append(glyph)

#original code to run:
#   pyftsubset.exe .\sample-font-a.ttf --glyphs=A,B --output-file=sample-font-a-id.ttf 
#   --layout-features=* --glyph-names --symbol-cmap --legacy-cmap
#   --notdef-glyph --notdef-outline --recommended-glyphs --drop-tables=
#   --name-IDs=* --name-legacy --name-languages=* --no-prune-unicode-ranges
options = _get_default_options()
#open font
font = subset.load_font(font_file, options)
#prepare subsetter
subsetter = subset.Subsetter(options)
#select all glyphs
subsetter.populate(glyphs=font_glyph_list)
#subset font
subsetter.subset(font)
#save font
subset.save_font(font, output_name, options)

print("Subset done. Font name: " + output_name)
```
where `characters-to-be-removed.txt` is:
```
A
B
C
D
```
and so on. Hope this helped you.

**Comment by arttet** [comment]
This problem is not already relevant.
