### ISSUE TITLE
Possibility to modify font on a glyph level

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fonttools#2097]
I am currently trying to merge two fonts but wanted to do it my style. Is it possible to copy one glyph at a time so I can control the glyph name individually? (criteria: two glyph with same name/codepoint will both be renamed to different names individually)

**Comment by behdad** [comment]
It's more complicated than that. You need to trick fonttools to load the fonts with new glyphnames. See the fontTools.merge module for how this is done.
