### ISSUE TITLE
Connected axes for non-linear interpolation

### ISSUE THREAD

**Issue by ctrlcctrlv** [fonttools/fonttools#2099]
A recent trending topic on Twitter is the idea of using connected axes to implement a type of non-linear interpolation. 

Does the designspace format support this?

**Comment by justvanrossum** [comment]
Since .designspace uses axis _names_ as location identifiers, it may work with non-unique tags. That said, fonttools uses fvar axis tags as axis identifiers all over the place, so there's a bigger challenge there.

**Comment by behdad** [comment]
Closing in favor of:
https://github.com/fonttools/fonttools/issues/1581
https://github.com/fonttools/fonttools/pull/2113
