### ISSUE TITLE
Remove semicolon left over in break statement

### ISSUE THREAD

**Issue by kontur** [fonttools/fonttools#2126]
Chanced upon this when browsing the code related to something else.

https://github.com/fonttools/fonttools/blob/c990a5b4e0385ec9372615783da01251a32d453c/Lib/fontTools/varLib/merger.py#L56

Not sure why this doesn't throw a syntax error but I suppose the semicolon does not belong there either way.

**Comment by anthrotype** [comment]
thanks. semicolons are no-op in python (allow to join multiple lines in a single one). When we'll set up black autoformatter those will be stripped out

**Comment by kontur** [comment]
Oh, I didn't know! I guess it joins `break` with _nothing_, so there's no harm, just looking like left-over / C'ish syntax
