### ISSUE TITLE
Support subsetting COLRv1

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#2127]
the subsetter can subset CORLv0 fonts, we need to teach it how to subset COLRv1 as well.

**Comment by rsheeter** [comment]
We should ping @garretrieger once this is ready; we'll want similar support in hb-subset and ideally to add it to the Progressive Font Enrichment demos.

**Comment by yisibl** [comment]
https://github.com/harfbuzz/harfbuzz/issues/2843

**Comment by anthrotype** [comment]
Fixed by https://github.com/fonttools/fonttools/pull/2177
