### ISSUE TITLE
Remove `gasp` with pyftsubset --no-hinting

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#2131]
If I'm correct, `gasp` can be dropped as well [here](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/subset/__init__.py#L2328) when removing hinting data?

**Comment by anthrotype** [comment]
i think one may want to keep a gasp table in an unhinted font, e.g. in gftools there's a script to fix-unhinted-fonts that sets all gasp ranges to smooth for unhinted fonts: 
https://github.com/googlefonts/gftools/blob/d285d05e2f2643fdfabfffd2a2d5cec2d8a4e4c2/Lib/gftools/fix.py#L142-L143

**Comment by anthrotype** [comment]
if you don't want to keep gasp you can always pass `--drop-tables+=gasp`

**Comment by RoelN** [comment]
One could argue that `--no-hinting` woud remove _all_ hinting-related stuff, but I trust your judgement :-) Agreed that it's always possible to manually remove it, so I'm closing this issue.

For Wakamai Fondue I'm trying to detect hinting (without going overboard in complexity). I ignore this specific [here](https://github.com/Wakamai-Fondue/wakamai-fondue-engine/pull/40), to avoid false positives.
