### ISSUE TITLE
support post format type 5.0

### ISSUE THREAD

**Issue by gaoxinge** [fonttools/fonttools#2134]
I found that the `post` in fonttools only supports format type less than `5.0`:

https://github.com/fonttools/fonttools/blob/70958dca86008aaa52086618876755968f3e82be/Lib/fontTools/ttLib/tables/_p_o_s_t.py#L28-L43

which are all described in [apple developer ttrm post](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6post.html).

However I am stuck at a font file [JinMeiMaoLiPoLieTiFan-1.zip](https://github.com/fonttools/fonttools/files/5722669/JinMeiMaoLiPoLieTiFan-1.zip) with `post` format type `5.0`, which is described in [postscript wiki type 5](https://en.wikipedia.org/wiki/PostScript_fonts#Type_5).

I want to ask: does foottools have any plan to support `post` format type `5.0`?

**Comment by gaoxinge** [comment]
This font may be an invalid font.

**Comment by justvanrossum** [comment]
It must be an invalid font, as `post` table format 5 does not exist. Not in the MS OpenType spec, nor in the Apple TT spec.

(Btw. PostScript font type numbers are completely unrelated to `post` table format versions.)
