### ISSUE TITLE
ttx slow

### ISSUE THREAD

**Issue by bjg2** [fonttools/fonttools#2136]
ttx tool can be very slow for me, especially for the big files (like > 2 minutes for 2mb file). Is there any flag to make it faster, like some multiprocessing or something or some extra library? 

I'm installing ttx in alpine linux with `apk add --no-cache py3-fonttools --repository http://dl-cdn.alpinelinux.org/alpine/edge/community`

**Comment by bjg2** [comment]
Tried installing with `apk add -no-cache build-base python3-dev libxml2-dev libxslt-dev` + `pip3 install fonttools[ufo,lxml,woff,unicode]`, doesn't seem to be much better. It spends ~1 minute on work, which is ~15s on my machine.

It might be that remote machine has much worse CPU, when I start the docker on my machine it lasts similar as outside of the docker. When looking at my resource manager, it takes ~5% of my CPU on my machine, are ttx very single-processor heavy? That might explain it, as remove single processor might be much worse than mine, if it doesn't parallelize at all...

**Comment by justvanrossum** [comment]
TTX doesn't parallelize explicitly at all, so it's single CPU indeed.

**Comment by bjg2** [comment]
So, nothing I can do?

My usecase is this: (due to interoperation with some other app) I need to 'prepare' the fonts by explicitly removing complete name table and replacing it with my name table. I do this by creating ttx from ttf/otf, replacing name table with mine, and creating ttf/otf from that ttx again.

Is there any better tool for my usecase?

**Comment by justvanrossum** [comment]
With TTX you can dump a single table, and merge a modified one with the original TTF. That should be a lot faster. See the `-t` and `-m` options.

**Comment by bjg2** [comment]
Thank you very much! I'm just not sure I nailed the syntax, though. Let's say I created ttx file with my desired name table:

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.18">

  <name>
    <namerecord nameID="0" platformID="1" platEncID="0" langID="0x0" unicode="True">
      A
    </namerecord>
  </name>

</ttFont>
```

What's the explicit syntax to merge it with ttf into new ttf file? I tried something like `ttx -m change.ttx -o out.ttf in.ttf` but that seems slow as well, not sure if I'm using the -m param as intended, as I don't see any examples anywhere.

**Comment by justvanrossum** [comment]
Something like:

    ttx -m org.ttf changedname.ttx

**Comment by Lorp** [comment]
BTW the result of the above will be `org#1.ttf`. I think Just means `org` to imply “original” ;)

One way to remember whether `-m` takes the ttf or the ttx is to recall that ttx always transforms ttx into ttf/otf (or ttf/otf into ttx). All options, including `-m`, modify how it does that.

**Comment by bjg2** [comment]
Thank you very much, kind gentlemen! It works and is fast now. Thanks!!
