### ISSUE TITLE
fail in Python 2

### ISSUE THREAD

**Issue by schriftgestalt** [fonttools/fonttools#2142]
https://github.com/fonttools/fonttools/blob/d0ea03c23b6eb81f80f0f8c6d85ae2119a759bf3/Lib/fontTools/misc/py23.py#L6

This line fails with an import error in python2. That makes the 2to3 compatibility quit incompatible.

**Comment by anthrotype** [comment]
We dropped python2 support long time ago. We kept that module not to break scripts written in py2.py3 style

**Comment by anthrotype** [comment]
Fonttools requires python 3.6

https://github.com/fonttools/fonttools/blob/d0ea03c23b6eb81f80f0f8c6d85ae2119a759bf3/setup.py#L453

The README also says that. We don't plan to restore support for python 2, sorry.

**Comment by schriftgestalt** [comment]
I thought so. I is just funny that in some parts it still works and it only fails in the former compatibly layer ;)

But a user has installed the latest version in python2.7. Shouldn't that be blocked?

**Comment by anthrotype** [comment]
yes, it should be blocked. That's what the `python_requires` does in setup.py. Pip will refuse to download and install versions marked that way if the host python version doesn't match.
How did the user install it?
