### ISSUE TITLE
Code duplication between bezierTools and cu2qu

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#2156]
cu2qu contains cython `calc_cubic_points` and `calc_cubic_parameters` routines which work on complex parameters, as well as various `split_cubic_...` routines. Arguably these are generic routines for working with bezier paths.

bezierTools contains Python `calcCubicPoints` and `calcCubicParameters` routines which work on tuple parameters.

I think this could be tidier, but there are a few potential approaches of increasing severity:

- It's not a problem to have duplicate routines, leave things as they are.
- It's not really a problem to have duplicate routines, but since they are generic bezier-handling routines, move the ones in `cu2qu` into `bezierTools`, renaming them `calcCubicPointsComplex` or similar. (And changing bezierTools, not cu2qu, to rely on cpython).
- We should really have one implementation; do the above, but change the original `calcCubicPoints` etc. into helper routines to adapt parameters from tuples to complex numbers and back.
- We should really have one representation of points and one implementation of these routines.

**Comment by behdad** [comment]
> * It's not really a problem to have duplicate routines, but since they are generic bezier-handling routines, move the ones in `cu2qu` into `bezierTools`, renaming them `calcCubicPointsComplex` or similar. (And changing bezierTools, not cu2qu, to rely on cpython).
> * We should really have one implementation; do the above, but change the original `calcCubicPoints` etc. into helper routines to adapt parameters from tuples to complex numbers and back.

Yes, this is my preference. The complex idea is too good to pass. So I think we should introduce them, and have the existing API convert to and back; that still results in speedup in those.

**Comment by behdad** [comment]
I now see why the duplication. cu2qu declares those as `cython.cfunc` for performance. Such functions cannot be imported from another module. Let's keep things as is.
