### ISSUE TITLE
[varLib.instancer] L4) moving the default location of an axis

### ISSUE THREAD

**Issue by KatjaSchimmel** [fonttools/fonttools#2157]
Hey hey. I just wanted to bring the pending L4 feature to your attention. 
I think the instancer is already a handy function and will be very useful in the future. But implementing "L4) Move the default position of an axis" is definitely something that would make the tool even more useable in the workflow. 

Is anyone currently working on L4? And is there anything I can do to further the implementation efforts?

**Comment by anthrotype** [comment]
Hi, thanks for filing this

> Is anyone currently working on L4?

No, I don't think so.

> implementing "L4) Move the default position of an axis" is definitely something that would make the tool even more useable

could you please elaborate on that? I'm curious to understand how you'd find this feature useful for your workflow.

Among the main goals of the instancer was to produce a partial VF that contains less variation data and is thus smaller in size. Changing the default position would not necessarily yield a result that reduces the amount/size of variation data in the VF (though in some situations it may).

**Comment by KatjaSchimmel** [comment]
Thanks for your quick reply!

> could you please elaborate on that?

Sure! Let's say I want to generate a partial variable font with an axis range that does not include the default position.
Currently, I have to do a work-around, open the Glyphs file, change the variable font origin to something within the desired range, export the variable font again, and then run instancer.AxisRange with the desired values. 

Moving the default position of an axis may not change the file size, but in combination with the other functions of the Instancer, it allows you to create a larger number of subsets without having to manipulate the source file.

**Comment by Mark2Mark** [comment]
Joining here again, and bringing the [already mentioned stuff from this issue](https://github.com/fonttools/fonttools/issues/1537) over here.

"… To specify, I meant, if you subset a variable font that has 2 axes originally, but the subset will only have one of the axes, what will happen with the origin location if that one originally sits on the dropped axis? …"

As far as I see you cannot slice/subset an axis range, when the target range does not include the variable font origin, right? That’s exactly the problem. So if you have an input font with 

`weight 0..1000` and the origin lies on `200`, it’s currently not possible to get a subset to a range of e.g. `400…1000`. The instancer will just spit an error (as documented).

**Comment by behdad** [comment]
I've been thinking about this. And like to see it happen. Solving the general-case can be a bit hairy to think about. But I think is doable.

I looked at the instancer code. Currently, using the following function, it splits desired subset designspace into axes that got "pinned" and those that remain a range:
```py
def splitAxisLocationAndRanges(axisLimits, rangeType=AxisRange):
    location, axisRanges = {}, {}
    for axisTag, value in axisLimits.items():
        if isinstance(value, rangeType):
            axisRanges[axisTag] = value
        elif isinstance(value, (int, float)):
            location[axisTag] = value
        elif isinstance(value, tuple):
            axisRanges[axisTag] = rangeType(*value)
        else:
            raise TypeError(
                f"Expected number or {rangeType.__name__}, "
                f"got {type(value).__name__}: {value!r}"
            )
    return location, axisRanges
```

to support L4, we would allow an axis to be returned in both of those sets, both as "pinned" to new default, as well as carrying a range.

Then we need to update the entire code for that change.

A utility function which I thought of, that might make the code easier to navigate and understand, is a function that then takes the output of the above function as well as a delta+support, and returns a list of delta+support, as well as the "bias" to add to the value being variated.  This is similar to `limitTupleVariationAxisRange`, but can be written more generally and reused.

Perhaps those should be added right into `varLib.models`.

**Comment by KatjaSchimmel** [comment]
Hey @behdad. This is good news. Thanks for doing the research and thinking about the implementation. Excited to see it happen!

**Comment by KatjaSchimmel** [comment]
Hey @behdad. I was wondering if there is news on the implementation of L4?

**Comment by behdad** [comment]
Hi @KatjaSchimmel. I won't have the time or focus to do this myself. But I've pinged a couple people who might be able to help.

**Comment by KatjaSchimmel** [comment]
thanks you!

**Comment by KatjaSchimmel** [comment]
Hi! It's me again. Just checking in if there is news on L4 support? I still think it would be a very helpful function.

**Comment by chrissimpkins** [comment]
Has anyone been able to take this on?

**Comment by behdad** [comment]
As far as I know no one is looking into it.

**Comment by behdad** [comment]
I'm working on this in https://github.com/fonttools/fonttools/pull/2728

**Comment by behdad** [comment]
I think my work is ready. Take it for a test drive and let me know!

Word of caution: changing default of multi-axis variable fonts can result in font size blowup...

https://github.com/fonttools/fonttools/pull/2728

**Comment by anthrotype** [comment]
hey @KatjaSchimmel, would you like to test @behdad's implementation of L4 instancing? You could install fonttools from that git branch directly using pip:

pip install -e git+https://github.com/fonttools/fonttools.git@instancer-l4#egg=FontTools

Or you could git clone fonttools, switch to `instancer-l4` branch and install from there. 
Let us know thanks!

**Comment by KatjaSchimmel** [comment]
@anthrotype I'm really excited to run a test and will hopefully get to it next week. 🤞 Thanks for the additional info on how to test

**Comment by behdad** [comment]
This is merged now!
