### ISSUE TITLE
[WISH: pyftmutate] Tool for interpolating on the binary font level

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#216]
Given that Erik van Blokland has opensourced MutatorMath ( https://github.com/LettError/mutatorMath ), I've recently realized that the process of "mutation" (blending, superpolation, metapolation) is very much a format-agnostic process. It doesn't really matter what kinds of numbers you "mutate" as long as there is some logical correspondence between them. The .designspace document that the MutatorMath documentation refers to points to .ufo files, but one could easily imagine using .ttx or .ttf. 

For complex scripts, UFO isn't really the best source format. Indic and other such scripts rely on GPOS much more heavily than Latin fonts, and the only "legal" format of expressing GPOS in UFO is the AFDKO FEA format which, well, is not really very easily parseable. 

But SFNT is actually very well structured. Except for "CFF ", one can easily produce two SFNT fonts which are structurally very compatible in terms of glyph coordinates, composites, GPOS, hhea and OS/2 linespacing values, and even UPM size or hinting. 

I think it could be extremely worthwhile to investigate a scenario where one would use two or more TTF/TTX "fonts" along with a MutatorMath .designspace document, and then produce interpolated ("mutated") instances strictly on the binary level. Of course that would require figuring out which "things" in SFNT actually are "coordinates" of some sort (rather than, say, glyph or lookup IDs), so interpolating them would be meaningful, and of course the TTF/TTX fonts would need to be compatible in structure (same number and order of contours, points, but also GPOS lookups and the structures used within them etc.). 

Having a fontTools-based mutate tool would also allow hybrid scenarios: even if mutating the "CFF " tables on the fontTools level were not possible, one could perform the mutation on the UFO level for the outline data using a .designspace document, but could then use the same .designspace setup to mutate the "kern", "GPOS", "kerx" etc. on the SFNT level, and then merge the resulting tables with the fonts generated from the mutated UFOs. 

Do you think it's sensible? 
A.

**Comment by behdad** [comment]
We are kinda heading that way, though I was more thinking of working in robofab space.  We'll see.

**Comment by twardoch** [comment]
Robofab effectively only does glyph points and kerning, perhaps anchors. It's probably useful for GLIF files (esp. in CFF) but I think everything else (particularly GPOS) would be better off in fontTools space.

**Comment by behdad** [comment]
Right.  Yes.

**Comment by davelab6** [comment]
@twardoch what's your take today?

**Comment by behdad** [comment]
I will have this in a few weeks...  GPOS part has not happened yet.

**Comment by behdad** [comment]
This has been done now, in fontTools.varLib.mutator
