### ISSUE TITLE
[WISH] Split GLYF and CFF tables into glyph-per-file instead of per-table

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#217]
It is very useful for keeping fonts in version control systems and for dealing precisely with font data that SFDIR and UFO have a glyph-per-file disk structure.

Similarly it is useful that ttx has a `--split` argument to split a sfnt file into a table-per-file disk structure.

I would like a `--glyph-split` argument to split 
- [ ] the GLYF table
- [ ] the CFF table

in the same way, so that TTX can be used by font editors as a source format in the same way as SFDIR and UFO

**Comment by bluebat** [comment]
maybe -S for split tables and glyphs?

**Comment by anthrotype** [comment]
duplicate of #153
