### ISSUE TITLE
Change default branch to main from master

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#2176]
It would be good to change default the branch name to `main` from `master`

I have asked @felipesanches to do this for all repos in the [github.com/googlefonts](http://github.com/googlefonts) org, and our docs refer to this repo's default branch, and he found that going to eg https://github.com/fonttools/fonttools/settings and changing the default branch setting will close all open PRs, so it would be good to triage all open PRs here (27 at time of writing and recreate them if needed)

**Comment by felipesanches** [comment]
thanks, @davelab6!

To be more precise, it is not the act of changing the default branch that auto-closes pending PRs, but instead, the deletion of the original `master` branch after its contents have been pushed to a new `main` branch that will trigger the auto-closing of the PRs.

I've noticed this behaviour when following the steps in this tutorial on a few other font-repos: https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

**Comment by davelab6** [comment]
Good news! Since that was written, GitHub made official guidance and a feature for changing the default branch name for GitHub repositories without auto closing. 

https://github.com/github/renaming

Seems there are no objections so I'd like to propose proceeding. @anthrotype what do you think? :)

**Comment by anthrotype** [comment]
quoting from that doc

> Renaming a branch will:
> - Re-target any open pull requests
> - Update any draft releases based on the branch
> - Move any branch protection rules that explicitly reference the old name
> - Update the branch used to build GitHub Pages, if applicable
> - Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
> - Show a notice to contributors who git push to the old branch
> - Redirect web requests for the old branch name to the new branch name
> - Return a "Moved Permanently" response in API requests for the old branch name

it sounds good to me. I would probably first try this on a smaller, lower-traffic project and confirm that there're no issues, then do it here as well.

**Comment by anthrotype** [comment]
done => https://github.com/fonttools/fonttools/tree/main

to update your local repos, do:

```sh
git checkout master
git branch -m main
git fetch origin
git branch -u origin/main main
```

**Comment by justvanrossum** [comment]
What are the correct steps to update a fork? I just messed mine up, so I will just delete and re-fork I suppose...

**Comment by justvanrossum** [comment]
(Although, I think I managed to fix it: my open PR seems unharmed.)

**Comment by anthrotype** [comment]
I think you need to go to settings, rename "master" -> "main" and do the same thing as with the upstream repo (I haven't tried, I normally work directly on upstream)
