### ISSUE TITLE
[feaLib] Contextual Positioning with in-line base mark single positioning rules fails

### ISSUE THREAD

**Issue by moyogo** [fonttools/fonttools#2186]
feaLib doesn't support Contextual Positioning with in-line base mark single positioning rules.

For example https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#example-4-2
```
mark sukun <anchor 0 0> @TOP_CLASS;

position base lam_meem_jeem' <anchor 625 1800> mark @TOP_CLASS alef;
```

feaLib fails with the errors:
`Expected ';'`
or
 `The following glyph names are referenced but are missing from the glyph set: base`

**Comment by cmyr** [comment]
this looks like it is potentially a dupe of #1746.

**Comment by moyogo** [comment]
Duplicate of #1746.

Thanks @cmyr
