### ISSUE TITLE
zopfli doesn’t have wheels for Python 3.9

### ISSUE THREAD

**Issue by liZe** [fonttools/fonttools#2188]
py-zopfli, used as a dependency for woff fonts, doesn’t have wheels for Python 3.9. Their last commit is more than one year ago, and they don’t respond to obp/py-zopfli#7, so we can think that the project is not active anymore.

Having no wheel is bad, because the installation from source requires a compiler. It makes the installation of fontools[woff] fail if no compiler is available.

zopfli is a dependency of fonttools with woff support, but I think that it’s actually not required: there’s a fallback if the package is missing. So we could be possible to remove zopfli from the dependencies, and make it installable with a dedicated "zopfli" option if possible. There’s also the possibility to use another package (like zopflipy), but we have no guarantee that other packages will be maintained in the future.

**Comment by mbarkhau** [comment]
x-ref for anybody who encounters this
- https://pypi.org/project/zopflipy/#files
- https://github.com/hattya/zopflipy

**Comment by anthrotype** [comment]
Hey, sorry I didn't see this when it was first posted. I have commit access to py-zopfli and can try to push updated wheels for 3.9 next week. I didn't know about the other zopflipy, we can support both of they have a compatible interface.

**Comment by liZe** [comment]
Thanks a lot for the wheels. I think that we can close this issue, unless you want to support zopflipy too.

**Comment by behdad** [comment]
@anthrotype is this still valid?
