### ISSUE TITLE
[varLib] VarLibCFFPointTypeMergeError raised for both points and hints

### ISSUE THREAD

**Issue by punchcutter** [fonttools/fonttools#2197]
In [buildcff2vf](https://github.com/adobe-type-tools/afdko/blob/1f47c7ac8a7b2d19c7dbeb0e626416a4a7853b59/python/afdko/buildcff2vf.py#L572) we check for `VarLibCFFPointTypeMergeError`, but this can be raised from `varLib.cff`'s `add_hint` and `add_hintmask` as well as `add_point`. Would it make sense to have a separate `VarLibCFFHintTypeMergeError` to differentiate points and hints?

**Comment by anthrotype** [comment]
Sure, if you think it might help to differentiate the two. Can you send a PR?
