### ISSUE TITLE
Breaking change with AbstractPen

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#2198]
I understand why and I probably need to embrace the typing future

but :)

This https://github.com/fonttools/fonttools/commit/f6a62e0db127c01f4d23f3398d70df21bbc6dccc PR is a breaking change.

```python
from fontTools.pens.basePen import AbstractPen

class D(AbstractPen):
    
    def moveTo(self, pt):
        print(pt)
    def lineTo(self, pt):
        print(pt)
    def curveToOne(self, *pts):
        print(pts)
    def closePath(self):
        print("close")
        
d = D()
```

results in:

```console
Traceback (most recent call last):
  File "<untitled>", line 15, in <module>
TypeError: Can't instantiate abstract class D with abstract methods addComponent, curveTo, endPath, qCurveTo
```

Maybe this had to be discussed more to envision the impact of such a change. Pens and pointPens are the core of lots of tools. 

For example a pen only dealing with components didnt need the requirement to implement all the extra `NotImplemented callbacks (like moveTo, lineTo, ... ) 

I dont know enough about `abc` to make it less strict  :) or maybe optionally at init of such a class to not raise an error. 

again, I dont have an issue with changing my code, but getting a breaking change is huge

**Comment by justvanrossum** [comment]
I admit that I didn't think things through when I suggested @madig to turn our Abstract[Point]Pen classes into Actual Abstract Base Classes.

I'm not sure what to do. It's true that this is a breaking change, even if the change may point out broken or dodgy code.

@typemytype showed me a real breaking example (adapted from real code):

```python
class SomeFilterPen(AbstractPointPen):

    def __init__(self, glyphSet, outPointPen):
        self.beginPath = outPointPen.beginPath
        self.endPath = outPointPen.endPath
        self.addPoint = outPointPen.addPoint

    def addComponent(self, baseGlyphName, transformation, identifier=None):
        ...

SomeFilterPen(None)
```

This class behaved perfectly before, but now raises TypeError upon instantiation.

**Comment by anthrotype** [comment]
Oh. I'm fine with reverting the change

**Comment by typemytype** [comment]
thanks!

**Comment by madig** [comment]
(Mind you the breaking change was making Abstract*Pen an explicitly abstract base class, the typing stuff is orthogonal to that.)
