### ISSUE TITLE
[varLib] varLib.models.VariationModel assumes all locations are full-range

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#2207]
VariationModel seems to be based on the idea that all "master" locations apply across the full range of the axes:

```
	def _computeMasterSupports(self, axisPoints):
		...
		# Compute min/max across each axis, use it as total range.
```

but it suggests that one day this will change and it will be possible to specify location that only apply to certain areas of the design space:

```
		# TODO Take this as input from outside?
```

It would be helpful, particularly in the case of variable layout, if locations were able to specify their box min/max points explicitly.

This would require some upheaval - a new interface design for `VariationModel.__init__(locations)` at least.

**Comment by justvanrossum** [comment]
I have been wondering whether the behavior could be better even without explicit input.

The top image is the current bahavior with a single intermediate master, but the bottom image would be much better, as the first half of the axis range would then only have one participating delta, and the exact middle position would be the sum of two integers (exact), instead of the sum of two integers plus an interpolated value (needs to be rounded).

![image](https://user-images.githubusercontent.com/4246121/109787894-ff53cb00-7c0e-11eb-8f01-ee06480731f2.png)

**Comment by justvanrossum** [comment]
In my ideal world, on a single axis with several intermediates, there would only ever be two deltas participating at a time: no more than two "tents" ever overlap. Currently, all deltas always participate, so is more work for a renderer.

(I'm not sure of the implictions for multiple axes.)

**Comment by simoncozens** [comment]
I think VariationModel already does what you suggest in the second diagram, thanks to [this code here](https://github.com/fonttools/fonttools/blob/07a5e2de62b5806517accffa088c8dc8ac1ec95a/Lib/fontTools/varLib/models.py#L317-L347). (But I have to admit that I *barely* understand all this, so you may be talking about something else.)

```
>>> v = VariationModel([ { "wght": 0}, { "wght": +0.5 }, { "wght": +1}])
>>> v.supports
[{}, {'wght': (0, 0.5, 1)}, {'wght': (0.5, 1, 1)}]
```

But this is somewhat orthogonal to the need for explicit region support.

**Comment by justvanrossum** [comment]
I barely understand either, and you may be right. And indeed let's not distract from your actual issue. (I'll try to more precisely find what I'm unhappy about and will post a new issue if/when I manage.)

**Comment by simoncozens** [comment]
I think I'm going to refactor `_computeMasterSupports` into three parts: one which turns locations into boxes, one which splits the boxes and sets the supports, and one which computes the delta weights for those supports. I think that should allow an advanced user of the class to inject their own set of boxes into the process, and hopefully make it clearer what needs to be done to allow supplying explicit regions by default.

**Comment by justvanrossum** [comment]
Here's my issue. Yes, it may be orthogonal to your desire for explicit regions, but if I'd file a new issue I'd use the exact same title as this one...

Have a look at this single-axis model with 5 masters total:
```python
from fontTools.varLib.models import VariationModel

locations = [
    dict(),
    dict(wght=0.25),
    dict(wght=0.5),
    dict(wght=0.75),
    dict(wght=1),
]
model = VariationModel(locations)
for s in model.supports:
    print(s)
```
The regions (supports) it calculates are these:
```
{}
{'wght': (0, 0.25, 1)}
{'wght': (0.25, 0.5, 1)}
{'wght': (0.5, 0.75, 1)}
{'wght': (0.75, 1, 1)}
```
However,  it would be much better (for reasons I tried to describe in https://github.com/fonttools/fonttools/issues/2207#issuecomment-789590780 ) if the regions were these instead:

```
{}
{'wght': (0, 0.25, 0.5)}
{'wght': (0.25, 0.5, 0.75)}
{'wght': (0.5, 0.75, 1)}
{'wght': (0.75, 1, 1)}
```

**Comment by behdad** [comment]
Simon, hold on a bit. I need to make a few drawings and explain the constraints.. will get to tomorrow if not in a few minutes. Is 3:30am and I can't seem to fall asleep.

**Comment by behdad** [comment]
> I think I'm going to refactor `_computeMasterSupports` into three parts: one which turns locations into boxes, one which splits the boxes and sets the supports, and one which computes the delta weights for those supports. I think that should allow an advanced user of the class to inject their own set of boxes into the process, and hopefully make it clearer what needs to be done to allow supplying explicit regions by default. It's a bit of a crazy long method already, so refactoring is good practice even if it doesn't end up helping with my issue...

That sounds good to me generally. However, there's a couple of things to keep in mind:

- The boxes should form a partial subset order. Two boxes cannot overlap unless one is fully inside the other. Otherwise you need to solve a full system of equations to find the deltas. I haven't convinced myself that there's even a guaranteed solution. With the partial-order way that VariationModel currently sets the boxes up, there's always a simple solution.

- The way boxes are solved does not make ANY difference to the perceived behavior of the interpolated function on a single axis. So, if you want to do things in a single axis and you think changing this function is needed, I think you might be misunderstanding how things work.

Put another way: can you tell me what you want to be able to do as an example, which you cannot do by providing just enough master points?

**Comment by justvanrossum** [comment]
> The way boxes are solved does not make ANY difference to the perceived behavior of the interpolated function on a single axis. 

That is only true when you consider rounding errors non-perceivable. Deltas are stored as integers, so the more boxes overlap, the harder it is to get an exact match with the source masters. This is the case at region peaks that combine several scaled deltas (such as the second and third peaks in my 5-master example). This problem gets worse proportional with the number of intermediate masters.

Things do start to wobble visibly with multi-segment HOI, but perhaps that's a case where a specialized delta algorithm can be better than a general solver.

And of course I take your word for the mathematical impossibilities that other "solutions" may cause. If it isn't solvable, it isn't solvable! And everything looks simple when you only consider one axis...

**Comment by simoncozens** [comment]
> Put another way: can you tell me what you want to be able to do as an example, which you cannot do by providing just enough master points?

I'm kind of convinced. It seems a bit crazy that I have to turn a set of regions into a set of masters that then get turned back into a set of regions, but if that means I can use someone else's already-existing code for the hard part it's probably worth doing...

**Comment by simoncozens** [comment]
> That sounds good to me generally. However, there's a couple of things to keep in mind

I'm not planning to change any functionality at all, just split a long function up into three smaller ones.

**Comment by behdad** [comment]
> It seems a bit crazy that I have to turn a set of regions into a set of masters that then get turned back into a set of regions

Again, I still don't understand what you are starting from that has regions.

**Comment by behdad** [comment]
> > The way boxes are solved does not make ANY difference to the perceived behavior of the interpolated function on a single axis.
> 
> That is only true when you consider rounding errors non-perceivable. Deltas are stored as integers, so the more boxes overlap, the harder it is to get an exact match with the source masters. This is the case at region peaks that combine several scaled deltas (such as the second and third peaks in my 5-master example). This problem gets worse proportional with the number of intermediate masters.

You are absolutely right. I wasn't responding to the (valid) issue that you raised, but to Simon's different issue.

I'll reply to you soon about why it was done that way, and how to improve it now. In fact, it was originally done the way you suggest. Was changed after. I remember the full details. But either need to produce some drawings, or make a video drawing things on paper or something.

> Things do start to wobble visibly with multi-segment HOI, but perhaps that's a case where a specialized delta algorithm can be better than a general solver.

True. Also why I'm open to adding constructors that take the tents from the client. I'm thinking about it since last night. I think I have some new insights. I'll report soon as I validate some of them.

> And of course I take your word for the mathematical impossibilities that other "solutions" may cause. If it isn't solvable, it isn't solvable! And everything looks simple when you only consider one axis...

Yes, the one-axis always has solution. The general case, I have proved it neither possible nor impossible. That's what I'm working on now. Just thinking about it algebraically I *think* there's always a solution where all masters span the entire space. How does that *look* on the generated surface and whether that's desirable is another question. I'm taking the dust off my pyplot module for this that I showed at one of the TYPO Labs; that conference is indeed when I changed this algorithm (the part you noticed) after @LettError showed a deficiency of varLib compared to MutatorMath.

**Comment by behdad** [comment]
> Have a look at this single-axis model with 5 masters total:
> 
> ```python
> from fontTools.varLib.models import VariationModel
> 
> locations = [
>     dict(),
>     dict(wght=0.25),
>     dict(wght=0.5),
>     dict(wght=0.75),
>     dict(wght=1),
> ]
> model = VariationModel(locations)
> for s in model.supports:
>     print(s)
> ```
> 
> The regions (supports) it calculates are these:
> 
> ```
> {}
> {'wght': (0, 0.25, 1)}
> {'wght': (0.25, 0.5, 1)}
> {'wght': (0.5, 0.75, 1)}
> {'wght': (0.75, 1, 1)}
> ```
> 
> However, it would be much better (for reasons I tried to describe in [#2207 (comment)](https://github.com/fonttools/fonttools/issues/2207#issuecomment-789590780) ) if the regions were these instead:
> 
> ```
> {}
> {'wght': (0, 0.25, 0.5)}
> {'wght': (0.25, 0.5, 0.75)}
> {'wght': (0.5, 0.75, 1)}
> {'wght': (0.75, 1, 1)}
> ```

VarLib used to do what you suggest. I changed it after Erik pointed out issues with my implementation:

  https://www.youtube.com/watch?v=3RRoIYeJ3YQ

The immediate reason it turned into what we have now is that it was easier (but not necessary) to fix the code to do what Erik expected (and I agree with) by just making it behave at it does currently. So, that we can improve on. Here's the commit, with extensive commit log: https://github.com/fonttools/fonttools/commit/42bef176a33dc7321eb70f5d49c90317e59ad0e5

However, there's a legitimate reason for why the current output *might* be desirable: it produces smaller (and many more 0) deltas, which saves bytes. In a common example where eg. Regular and Black masters are designed, then Bold interpolated and imported as a new master and slightly modified, in the scheme that you propose, Bold datas will all be encoded separately. Whereas if the support for Black master reaches all the way to Regular as current code does, then the Bold master will only encode any data for actual manual modifications that were made to it, and nothing for just the interpolated-then-imported-unmodified parts.

Obviously there's a filesize vs runtime tradeoff. Ideally we should be finding the sweet-spot of that tradeoff given the actual master configuration. But I don't have good ideas about how to do that currently. I'm still thinking about it.

And yes, the error accounting is sloppy and errors add up. It could be done better, to account of accumulated rounding errors from previous deltas when computing deltas for each master. That way, the total error for any interpolation point will still be limited to 0.5.

**Comment by behdad** [comment]
> And yes, the error accounting is sloppy and errors add up. It could be done better, to account of accumulated rounding errors from previous deltas when computing deltas for each master. That way, the total error for any interpolation point will still be limited to 0.5.

Please review my PR: https://github.com/fonttools/fonttools/issues/2213

**Comment by justvanrossum** [comment]
> Also why I'm open to adding constructors that take the tents from the client

Or a constructor that takes a tent builder func – that may be necessary to have subModels do the right thing? Or is that a case where the general algorithm necessarily has to take over anyway? (A tent builder func could indicate "I can't handle this master configuration, please fall back to the general algorithm.")

**Comment by behdad** [comment]
@justvanrossum here's another pathological case that neither approach works very well for:

  https://github.com/fonttools/fonttools/pull/2217

It can be encoded using just two deltas; but both approaches end up encoding numMasters.

**Comment by behdad** [comment]
[err. nevermind. deleted previous commit. didn't make sense.]

**Comment by behdad** [comment]
> [err. nevermind. deleted previous commit. didn't make sense.]

Humm. It does make some sense. Let me rephrease:

In the test I implemented in:

  https://github.com/fonttools/fonttools/pull/2217

There's one axis and (say) 100 masters on it. The default-master has value of 0, all the others have 100. That particular function can be encoded using just two deltas. However, currently we always solve the system only based on locations. That is, we build a model that can handle arbitrary values at all masters. We fail to find simpler solutions if, eg, many master values happen to be the same.

This shows that the optimal model CANNOT be inferred Just from master locations. Problem just became much harder. :))

**Comment by simoncozens** [comment]
> Again, I still don't understand what you are starting from that has regions.

OK, I’m convinced. The tooling can easily make sharp cornered regions by adding or subtracting epsilon from the previous master location. I have enough to do what I want in terms of variable layout.

**Comment by twardoch** [comment]
This is very important, but I’m afraid it’ll confuse people if there are not enough explanations provided. I don’t think I quite understand the repercussions for, say, two axes with 4 corner masters and just 1 extra master somewhere in the middle.

**Comment by simoncozens** [comment]
Adam, it took me a while to realise there are two different levels here. On one level, the user-visible effect of the combined set of deltas. On the other level, the internal representation of each individual delta. There are different ways of creating regions for each delta which makes up the whole variation function. We are talking about changing the layout of the individual deltas while keeping the user-facing effect the same.

**Comment by twardoch** [comment]
In Oct 2021, I’ve made this issue elsewhere — https://github.com/daltonmaag/file-format-discussion/issues/10 — which illustrates a common problem: 4-master config with a 5th master on the edge. That intermediate master should ideally have its "end" ("max" of the range) defined at all opposite edges, so that it no longer influences the other edges at full force.

**Comment by behdad** [comment]
I fixed this in https://github.com/fonttools/fonttools/pull/2717
