### ISSUE TITLE
[varLib.varStore] Return 0xFFFFFFFF if there's no variation

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#2211]
Forking from https://github.com/simoncozens/fontFeatures/issues/39#issuecomment-790001038

Back when I was writing this code, there was no varIdx value that meant "no variation". So the callers of the OnlineVarStoreBuilder had to do the check themselves. Now'ish we added 0xFFFFFFFF to mean "no variations" to OpenType, so we can use that to make the client's job simpler.

I don't think it's an issue with backward compatibility. We'll update all our internal callsites and be done.

The optimizer can also choose to through empty ones out and return 0xFFFFFFFF. Currently it ends up spending a few bytes registering a region that has no variation and one data item with no deltas for it...

Note that, in constrained uses of the ItemVariationStore, like in HVAR/VVAR tables, it might be still beneficial to encode no-variations explicitly. So the builder should have a mode to do that.

**Comment by behdad** [comment]
Also possibly make `OnlineVarStoreBuilder.finish()` return `None` if the resulting varStore holds no variations?  That would be a bigger API break... Currently in some places we do things like:
```
        store = merger.store_builder.finish()
        if not store.VarData:
                return
```

**Comment by behdad** [comment]
My bad typo. I meant 0xFFFFFFFF.

**Comment by behdad** [comment]
> Also possibly make `OnlineVarStoreBuilder.finish()` return `None` if the resulting varStore holds no variations? That would be a bigger API break...

@anthrotype WDYT?

**Comment by anthrotype** [comment]
> return None if the resulting varStore holds no variations

I guess it'd be ok, I don't believe the OnlineVarStoreBuilder has extensively been used by used code outside of fontTools.varLib

**Comment by behdad** [comment]
Sounds good. Thanks.
