### ISSUE TITLE
[subset] Drops variation Device tables if `--drop-hinting`; ouch!

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#2272]
We discovered this in:
https://github.com/harfbuzz/harfbuzz/pull/2957

Basically, code from before variations always dropped Device tables if no-hinting was requested. And we reused the Device table mechanism for variations. We never updated the code!

In the subsetter code just search for `Drop device tables`. There's ~5 places.

**Comment by anthrotype** [comment]
ouch, so basically if you subset an hinted variable font and request to --no-hinting we also strip out all the Device tables, including those with DeltaFormat = 0x8000 that contain indices into ItemVarStore

**Comment by behdad** [comment]
Correct. I'm on it.

**Comment by behdad** [comment]
Is uglier than I like it to be. :)
