### ISSUE TITLE
[ttLib/varLib] Implement 32 bit VarStore variant, so we can fully support COLRv1

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2279]
Opening this issue to discuss how to approach, and who can do what. We (@BlackFoundry and me) have some capacity to contribute, and would like to see variable COLRv1 working.

This is (at least) about:

- VarStore
- OnlineVarStoreBuilder
- VarStoreInstancer
- VarStore optimizer

Cc. @behdad, @horasio, @JeremieHornus, @rsheeter, @drott, @davelab6

**Comment by behdad** [comment]
Related: https://github.com/fonttools/fonttools/issues/2211

**Comment by behdad** [comment]
For reference, here's the relevant part of the change (from https://github.com/googlefonts/colr-gradients-spec/blob/main/OFF_AMD2_WD.md):

In 7.2.3.4, in the table for the ItemVariationData subtable structure, replace the field name "shortDeltaCount" with "wordDeltaCount", and replace the description of that field with the following:"

A packed field: the high bit is a flag—see details below.

Following the table for the ItemVariationData subtable structure, replace the remainder of 7.2.3.4 (including the table for the DeltaSet record structure) with the following:

The wordDeltaCount field contains a packed value that includes a flag and a “word” delta count. The format of this value is as follows:

Mask | Name | Description
-- | -- | --
0x8000 | LONG_WORDS | Flag indicating that “word” deltas are long (int32)
0x7FFF | WORD_DELTA_COUNT_MASK | Count of “word” deltas

The representation of delta values uses a mix of long types (“words”) and short types. If the LONG_WORDS flag is set, deltas are represented using a mix of int32 and int16 values. If the flag is not set, deltas are presented using a mix of int16 and int8 values. See the description of the DeltaSet record below for additional details.

The count value indicated by WORD_DELTA_COUNT_MASK is a count of the number of deltas that use the long (“word”) representation, and shall be less than or equal to regionIndexCount.

**Comment by behdad** [comment]
Mostly done in https://github.com/fonttools/fonttools/pull/2285

The VarStore optimizer still needs to learn about 32bit encoding. But that branch is already useful and correctly builds 32bit VarStores, just not necessarily fully optimal in size.

**Comment by behdad** [comment]
Instancer, subsetter, etc, already work and need to no change.

**Comment by davelab6** [comment]
@justvanrossum what is needed to close this out?

**Comment by justvanrossum** [comment]
> what is needed to close this out?

Not much, see #2285

**Comment by anthrotype** [comment]
fixed by #2285
