### ISSUE TITLE
Merge ttc and dfont logic

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#228]
Right now TTFont has different indices for them, and with different default behaviors:

``` python
        def __init__(self, file=None, res_name_or_index=None,
                        sfntVersion="\000\001\000\000", flavor=None, checkChecksums=False,
                        verbose=False, recalcBBoxes=True, allowVID=False, ignoreDecompileErrors=False,
                        recalcTimestamp=True, fontNumber=-1, lazy=None, quiet=False):
```

The `res_name_or_index` is the dfont index, and fontNumber is the ttc index.

**Comment by behdad** [comment]
(Related to #229)

**Comment by anthrotype** [comment]
Doesn't "res_name_or_index" also apply to the old resource-fork suitcase format, as well as the data fork (.dfont) one?
Or maybe we don't care anymore about resource forks? (cf. https://github.com/behdad/fonttools/issues/221)

**Comment by twardoch** [comment]
We shouldn't care about these.

**Comment by behdad** [comment]
We want to kill all Mac-specific code after adding Carbon-independent dfont support.

**Comment by behdad** [comment]
Let's leave that stuff as is...
