### ISSUE TITLE
Fonts that throws errors at the start of decompiling

### ISSUE THREAD

**Issue by 0xff00ff** [fonttools/fonttools#2283]
Found some fonts that throws errors at the start of decompiling 
https://fonts.google.com/specimen/Noto+Sans+JP?query=noto+sans+
https://fonts.google.com/specimen/Noto+Serif+JP?query=noto+serif
![image](https://user-images.githubusercontent.com/669518/116717859-07976f00-a9e2-11eb-8dfd-5a68122f1628.png)

**Comment by anthrotype** [comment]
@0xff00ff can you upload the font file you're using? and the exact `ttx` command line that triggers this. thanks
