### ISSUE TITLE
typo in ttLib.tables._g_l_y_f.py

### ISSUE THREAD

**Issue by Eigi** [fonttools/fonttools#2289]
in line 401 parameter glyphname of method _synthesizeVMetrics is written in all lowercase.
in line 415 variable glyphName (camelcase) is used: raises NameError: name 'glyphName' is not defined

in line 418 parameter glyphName of method getPhantomPoints is written in all camelcase.
in line 423 variable glyphname (lowercase) is used

**Comment by justvanrossum** [comment]
A PR would be great!

This a regression caused by https://github.com/fonttools/fonttools/commit/51a76e319e51cd225b41ddec101d93284a03ca9c.
