### ISSUE TITLE
Support dfont

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#229]
Related to #221, implement the dfont container format in pure Python.

The dfont format is pretty simple. GNU Classpath has a pure Java implementation for dfont loading that might serve as inspiration for handling this. (As the original author, I'll gladly grant copyright to the fonttools project).
https://gcc.gnu.org/viewvc/gcc/trunk/libjava/classpath/gnu/java/awt/font/opentype/MacResourceFork.java?view=co&content-type=text%2Fplain

**Comment by brawer** [comment]
See also the section “Resource File Format” in [Inside Macintosh: More Macintosh Toolbox](
https://developer.apple.com/legacy/library/documentation/mac/pdf/MoreMacintoshToolbox.pdf#page=151), Addison-Wesley Publishing Company, 1993; pages 1–121 to 1–125.

**Comment by twardoch** [comment]
Is this needed? :) .dfont was a relatively short-lived container for OS X system fonts that Apple abandoned in favor of .ttc some years ago now. You might as well implement support for the "typ1" SFNT table :)

**Comment by anthrotype** [comment]
Yes, it's not a priority. On OS X, the current `fontTools.ttLib.macUtils` module can still read sfnt resources stored in the data fork. However, it could be one those “low hanging fruits”..
Actually some months ago, I started implementing the resource fork reader, using Sasha's java code as a starting point. I didn't pull a request yet because I was waiting for full Font Collections support to be defined first.

**Comment by brawer** [comment]
Here’s some test data for reading Mac resource forks; maybe somebody finds it useful when implementing unit tests on dfont parsing. Personally I would agree that this is rather low priority. However, what I like about supporting dfont is that it can help when rescuing old fonts from earlier decades. (It may not be obvious, but on MacOS X, dfont files can be built from an old MacOS font via a simple `cp` command).

```
$ cat testdata.r
data 'TEST' (128) { $"4865 6C6C 6F" };
data 'TEST' (129) { $"576F 726C 64" };
data 'test' (128) { $"486F 7720 6172 6520 796F 753F" };

$ /usr/bin/Rez testdata.r -o compiled
$ hexdump -v compiled/..namedfork/rsrc
0000000 00 00 01 00 00 00 01 22 00 00 00 22 00 00 00 52
0000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000080 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000090 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000100 00 00 00 05 48 65 6c 6c 6f 00 00 00 05 57 6f 72
0000110 6c 64 00 00 00 0c 48 6f 77 20 61 72 65 20 79 6f
0000120 75 3f 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000130 00 00 00 00 00 00 00 00 00 00 00 1c 00 52 00 01
0000140 54 45 53 54 00 01 00 12 74 65 73 74 00 00 00 2a
0000150 00 80 ff ff 00 00 00 00 00 00 00 00 00 81 ff ff
0000160 00 00 00 09 00 00 00 00 00 80 ff ff 00 00 00 12
0000170 00 00 00 00                                    
```

**Comment by brawer** [comment]
The next task for this bug is writing .dfont files, correct?

**Comment by anthrotype** [comment]
Yeah, I guess... Though I don't see much purpose in making new .dfonts in 2016 (unless one deliberately wants to prevent the font from working on non-Mac platforms).

**Comment by anthrotype** [comment]
my opinion is we should focus on making the TTC work first (so that one may convert existing .dfont to .ttc, for example).
https://github.com/behdad/fonttools/issues/17

**Comment by anthrotype** [comment]
but of course, if you wish to work on the mac resource writer, you're welcome! ;)

**Comment by brawer** [comment]
Oh, I was just going through the open bugs and wasn’t sure what to do about this one. I guess we leave it open for now.

**Comment by HinTak** [comment]
Some system fonts are still shipped as dfont's as of Yosemite. I don't know about El Capitan.
