### ISSUE TITLE
[feaLib] Bug in ChainContextPos compilation?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2293]
I have this fea snippet:
```
@uppercase = [A B C];
@shift = [at hyphen];
feature calt {
    pos @uppercase @shift' @uppercase <0 200 0 0>;
    pos @uppercase space @shift' @uppercase <0 200 0 0>;
    pos @uppercase @shift' space @uppercase <0 200 0 0>;
    pos @uppercase space @shift' space @uppercase <0 200 0 0>;
} calt;
```
The resulting font works for the first two cases (eg. `/A/hyphen/A` and `/A/space/hyphen/A`), but not for the latter two (eg. `/A/hyphen/space/A` and `/A/space/hyphen/space/A`).

Good:
```
$ hb-shape chaincontextpos_bug.ttf "A-A"
[gid4=0+1000|gid3=1@0,200+1000|gid4=2+1000]
$ hb-shape chaincontextpos_bug.ttf "A -A"
[gid4=0+1000|gid1=1+1000|gid3=2@0,200+1000|gid4=3+1000]
```
Not good:
```
$ hb-shape chaincontextpos_bug.ttf "A- A"
[gid4=0+1000|gid3=1+1000|gid1=2+1000|gid4=3+1000]
$ hb-shape chaincontextpos_bug.ttf "A - A"
[gid4=0+1000|gid1=1+1000|gid3=2+1000|gid1=3+1000|gid4=4+1000]
```

In the TTX I see that the first two `ChainPosClassSet` items do have a `PosLookupRecord`, but the latter two do not.

The same snippet compiled with makeotf results in a correctly working font.

The attached archive contains a font, ttx dump and a script that creates the font.

**Comment by justvanrossum** [comment]
> The same snippet compiled with makeotf results in a correctly working font.

FWIW, with feaLib it compiles to `<ChainContextPos index="0" Format="2">`, and with makeotf it compiles to `<ChainContextPos index="0" Format="3">`

**Comment by justvanrossum** [comment]
The problem happens at the parser-level, and I just found a work-around (write the value record right after the affected input glyph):

```
@uppercase = [A B C];
@shift = [at hyphen];
feature calt {
    pos @uppercase @shift' <0 200 0 0> @uppercase;
    pos @uppercase space @shift' <0 200 0 0> @uppercase;
    pos @uppercase @shift' <0 200 0 0> space @uppercase;
    pos @uppercase space @shift' <0 200 0 0> space @uppercase;
} calt;
```

**Comment by anthrotype** [comment]
are the two notations meant to be equivalent?

**Comment by justvanrossum** [comment]
> are the two notations meant to be equivalent?

Good question. They seem to be in makeotf, but I can't find conformation in the spec (but I didn't look yet very hard).

**Comment by justvanrossum** [comment]
I'm fairly sure this is the relevant bit of code:
https://github.com/fonttools/fonttools/blob/9c18e2a07d10d61dd377cca285bbd11dc188d1b0/Lib/fontTools/feaLib/parser.py#L475-L484

**Comment by justvanrossum** [comment]
This is the makeotf error message if you do it wrong:
```
makeotfexe [ERROR] <SourceSansPro-Master0> Positioning values are allowed only in the marked glyph sequence, or after the final glyph node when only one glyph node is marked. [features 2]
```

The shortes reproducer I found is this:
```
feature aaaa {
    pos a' b c <0 200 0 0>;
} aaaa;
```
While this one works:
```
feature aaaa {
    pos a' b <0 200 0 0>;
} aaaa;
```
So more than one lookahead glyph/class makes it not work.

**Comment by justvanrossum** [comment]
On it, cooking PR.
