### ISSUE TITLE
undefined variable in method _synthesizeVMetrics() of class table__g_l_y_f

### ISSUE THREAD

**Issue by Eigi** [fonttools/fonttools#2295]
While fixing issue #2292 I found another one. Variable "topSideBearing" in method _synthesizeVMetrics() is not defined. I' not sure if topSideBearing is ment to be the same as topSideY.

**Comment by anthrotype** [comment]
ouch, this probably broke when the code was reshuffled in https://github.com/fonttools/fonttools/pull/2266

it should be `topSideBearing = otRound(topSideY - glyph.yMax)`

**Comment by behdad** [comment]
Ugh. I'm really sorry for making this mess. Thanks Eigi & Cosimo.
