### ISSUE TITLE
[colorLib/ttLib.tables.otTables] Should default for VariableValue.varIdx be 0xFFFFFFFF?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2297]
The default varIdx for a VariableValue object is 0.

When building color glyphs with colorLib, when a field in a Var structure is not a tuple but a simple value, this default varIdx is used.

To me it would make more sense for this default to be 0xFFFFFFFF, meaning "no variations". This would be more convenient when constructing variable COLRv1 glyphs. At the moment I have to set 0xFFFFFFFF explicitly in my color glyph Paint dict.

What do you think, @anthrotype and @behdad?

https://github.com/fonttools/fonttools/blob/9c18e2a07d10d61dd377cca285bbd11dc188d1b0/Lib/fontTools/ttLib/tables/otTables.py#L1259-L1264

**Comment by anthrotype** [comment]
I think that predates the addition of the non-variable Paint formats. The idea (untested tbh) was that zeros would compress away better than 0xFFFFFFFF when woff2-ing the fonts, and the actual varIdx value is ignored when a COLR table has no VarStore.
But you're right, 0xFFFFFFFF is better as default value now that we do have `PaintVar*` variants.

**Comment by justvanrossum** [comment]
Should I make a PR?

I'm using these values for fields that have no variations in an otherwise variable PaintVarXxxx, with a non-NULL VarStore, so 0x0 has an actual meaning there.

I assume with the current state of things it makes no sense to have PaintVarXxx tables in a COLRv1 table without a VarStore?

**Comment by anthrotype** [comment]
> Should I make a PR?

yes thanks!

> it makes no sense to have PaintVarXxx tables in a COLRv1 table without a VarStore?

no, it doesn't. fwiw nanoemoji only uses the non-var paints currently.
