### ISSUE TITLE
function posix(path) in designspaceLib does not work with Windows UNC path

### ISSUE THREAD

**Issue by Eigi** [fonttools/fonttools#2299]
On Windows UNC (Uniform Naming Convention) paths have the following form:  
`\\SERVER\SHARE\FOLDER-NAME\FILE-NAME` or  
`\\IP-ADDRESS\SHARE\FOLDER-NAME\FILE-NAME`  
the possix function translates this to `SERVER/SHARE/FOLDER-NAME/FILE-NAME`. Therefore all path attributes for sources and instances are invalid if a DesignSpaceDocument is loaded via an UNC path.

**Comment by anthrotype** [comment]
@Eigi I see in 84d77e5 you add a `//` prefix, does that still work for UNC paths? I don't have a Windows machine to test with. Should we instead maybe restore the original backslashes `\\` or even just leave the UNC paths untouched?

**Comment by madig** [comment]
Where are the UNC paths coming from?

**Comment by anthrotype** [comment]
I suppose from the user? why not, it's perfectly valid to wanting to store one's sources on some server

**Comment by madig** [comment]
I mean, doesn't the DS format always want relative paths? We had this problem before, with CI tmp dirs mounted on a different drive.

**Comment by anthrotype** [comment]
well, it is possible that both the designspace _and_ the sources are on the same UNC drive..

**Comment by anthrotype** [comment]
ah, I see what you mean. If both were on the same drive, they would be using relative paths and there would not be this problem.. only when they are on different drives that one may incur in absolute paths, including UNC paths 🤔

**Comment by anthrotype** [comment]
> doesn't the DS format always want relative paths?

I'm actually not sure

**Comment by anthrotype** [comment]
The designspace spec says only relative paths are allowed, so that would basically exclude UNC paths

> filename: required, string. A path to the source file, relative to the root path of this document. The path can be at the same level as the document or lower.

**Comment by Eigi** [comment]
Yes, in my case designspace, sources and instances are on the same UNC share.
See my comment in the pull request.

**Comment by Eigi** [comment]
> @Eigi I see in [84d77e5](https://github.com/fonttools/fonttools/commit/84d77e5c3ac35dbea123b4dcbf4197ff81ac0a22) you add a `//` prefix, does that still work for UNC paths? I don't have a Windows machine to test with. Should we instead maybe restore the original backslashes `\\` or even just leave the UNC paths untouched?

Yes it works with forward slashes. Tested in my environment.

**Comment by anthrotype** [comment]
I meged #2306, thank you
