### ISSUE TITLE
[subset] Add support for TrueType Collection (TTC) fonts

### ISSUE THREAD

**Issue by andjc** [fonttools/fonttools#23]
Many East Asian fonts are available as TTC fonts, and it would be useful if pyftsubset could access individual fonts om a TTC font to allow subsetting of CJK fonts.

**Comment by anthrotype** [comment]
subsetter already supports selecting the --font-number in a collection 

https://github.com/fonttools/fonttools/blob/455158f2bfd9eae2135a5f85bb96549a545cac82/Lib/fontTools/subset/__init__.py#L412-L413
