### ISSUE TITLE
Parsing of 'post' tables version 2.0

### ISSUE THREAD

**Issue by eric-muller** [fonttools/fonttools#2314]
The current code in table__p_o_s_t.unpackPSStrings, used for post version 2.0, assumes that all bytes in the 'post' table after the glyphNameIndex array are glyph names, and decodes all those bytes accordingly. Consider a font where there are 2 glyphs

- the first is name ".notdef" and the second is named "eric". 
- post.glyphNameIndex [0] = 0 and post.glyphNameIndex [1] = 258
- post.stringData [0..4] = {4, 'e', 'r', 'i', 'c'}

Bytes in the post table after post.stringData [4] are not referenced, and arguably could be anything. Of course, it's not a good idea to have such extra bytes, but I ran into a font like that, and it's arguably  valid. The spec issue is that the size of the stringData array is not well defined: if could be "what it takes to exhaust the rest of the post table" (what fonttools does today) or it could be "what it takes to resolve all the indices in glyphNameIndex", which is what many other tools do (spot, aots, DLT OT Master).

Should fonttools be changed to the second interpretation?

**Comment by anthrotype** [comment]
If I understand correctly, the issue here is that `unpackPStrings` is attempting to parse anything that looks like a PS string it can until it uses up the the stringData, but instead you suggest it should only parse up to numGlyphs and ignore the tail (perhaps with a warning)?

https://github.com/fonttools/fonttools/blob/604bfdb2fbfe38d713eb91780330859532fde826/Lib/fontTools/ttLib/tables/_p_o_s_t.py#L255-L263

Sounds reasonable, I'm not opposed to that.
What exactly happens now, you get extra garbage strings in the post.extraNames? Do you get an error?

**Comment by emuller-amazon** [comment]
> until it uses up the stringData
more precisely until the end of the post table

> you suggest it should only parse up to numGlyphs
Up to the number of strings referenced in glyphNameIndex

See pull request <https://github.com/fonttools/fonttools/pull/2318> for details.

> What exactly happens now, you get extra garbage strings in the post.extraNames? Do you get an error?

There is no direct failure in unpackPStrings: data[index+1:index+1+length] will silently stop at len(data) if index+1+length is past the end of the data, and tostr accepts any byte sequence. But when using ttx to decompile, I end up with random bytes in the generated XML, in particular U+0000, which is illegal in XML.

**Comment by anthrotype** [comment]
I see, thanks for the PR and for clarifying that.

**Comment by behdad** [comment]
Let's kill `extraNames` please.

**Comment by behdad** [comment]
> Let's kill `extraNames` please.

It's one of those useless faulty parts of ttFont that breaks roundtripping.

**Comment by emuller-amazon** [comment]
I am afraid my python skills are not good enough for that. Sorry.

**Comment by twardoch** [comment]
I'm for killing extraNames. I never used it myself and found it confusing. 

AFAIR there was a problem that AFDKO use(d?) a different internal set of "standard Mac names" than the Apple TT spec, and there were problems around it. "middot" vs. "periodcentered" and all that. I know we had to work around that in FontLab some years ago.
