### ISSUE TITLE
[ufoLib]: GlyphSet.rebuildContents: file existence checking necessary?

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#2321]
My profiling in https://github.com/madig/readwrite-ufo-glif/issues/1 shows that roughly 12% of total loading time in that particular benchmarking script is spent checking for the existence of files referenced in contents.plist. Is that necessary? Accessing a non-existent glif already raises.

**Comment by madig** [comment]
(It is specifically only checked when validating.)

**Comment by anthrotype** [comment]
well It's a pity that fs makes checking file existance so slow. I suggest that we remove the fs.exists() call altogether from the rebuildContents method. Firstly, it's bad that so much extra work is being done inside a constructor. Secondly, the readGlyph (via getGLIF) method is going to fail _anyway_ as soon as you call on a non-existant glif file name so it's really not worth paying that cost upfront.

**Comment by justvanrossum** [comment]
But isn't that what validating is about? That you know as soon as possible that something is wrong?

If validating otherwise must be on, perhaps use a different flag for the glyph file existence check?

I agree that in most cases you don't want or need this check, but I can also imagine client code that wants to inform a user up front if the UFO is not quite valid.

**Comment by anthrotype** [comment]
hm ok. what about have a checkAllFilesExist as separate method that clients can call if they really care

**Comment by anthrotype** [comment]
(i'm also ok with leaving things as they are, since one can turn off validation already, eg. fontmake doesn't validate, just politely crashes)

**Comment by justvanrossum** [comment]
(I'm also ok with leaving things as they are. Yes, if performance matters: don't validate)

**Comment by benkiel** [comment]
If I remember correctly, one also has fine grained control of which validators to run
