### ISSUE TITLE
Subsetter does not remove empty feature

### ISSUE THREAD

**Issue by Eigi** [fonttools/fonttools#2324]
QUESTION:
Empty features (lookupCount==0) are not removed in any case.
If the feature is a stylistic set with an UI name (FeatureParams), the feature is kept even if no lookups are assigned.
I think the source for this behaviour is here:
subset.__init__py lines 1298
```python
@_add_method(otTables.Feature)
def subset_lookups(self, lookup_indices):
	""""Returns True if feature is non-empty afterwards."""
	self.LookupListIndex = [l for l in self.LookupListIndex
				  if l in lookup_indices]
	# Now map them.
	self.LookupListIndex = [lookup_indices.index(l)
				for l in self.LookupListIndex]
	self.LookupCount = len(self.LookupListIndex)
	return self.LookupCount or self.FeatureParams
``` 
Is this intended and if so, what is the background?
Thanx
Eigi

**Comment by anthrotype** [comment]
yes, I think it's intentional, given that the mere presence of features carry meaning for shaping engines, e.g. for complex indic scripts. But @behdad can confirm

**Comment by behdad** [comment]
> yes, I think it's intentional, given that the mere presence of features carry meaning for shaping engines, e.g. for complex indic scripts.

Right. But the block after what Eigi quoted seems to be more relevant for that.
https://github.com/fonttools/fonttools/blob/ee2aa264d5e99158d71dc6a279e38ba6021e557a/Lib/fontTools/subset/__init__.py#L1313-L1322

As this line says clearly:
```
	return self.LookupCount or self.FeatureParams
```
the mere presence of `FeatureParams` is enough to retain a feature. That's useful for the `size` feature, and only that feature, but useless for pretty much all other features. So I suggest we adjust the logic to reflect that.

**Comment by behdad** [comment]
cc @garretrieger @qxliu76 to keep HB subsetter in sync.

**Comment by anthrotype** [comment]
ah ok, I mis-remembered. We do drop empty feature records, except for "pref"

https://github.com/fonttools/fonttools/blob/ee2aa264d5e99158d71dc6a279e38ba6021e557a/Lib/fontTools/subset/__init__.py#L1313-L1322

> the mere presence of FeatureParams is enough to retain a feature. That's useful for the size feature, and only that feature

so the fix would be drop empty features (no lookups) unless they have FeatureParams and the tag is "size", correct?

**Comment by behdad** [comment]
> so the fix would be drop empty features (no lookups) unless they have FeatureParams and the tag is "size", correct?

That's my current inclination.
