### ISSUE TITLE
[varLib] support building variable COLRv1 table from set of masters

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#2328]
Now that we have support for 32-bit VarStore, required to variate some of the COLRv1 fields, fontTools.varLib should be updated to create a COLRv1.VarStore from a set of master fonts containing compatible COLRv1 tables.

**Comment by behdad** [comment]
First step would be to produce a set of masters to use for testing / merging.

Do you suggest adapting `varLib` to do merging? Or update your toolchain to generate variations directly? We can do the former, but would require idential-structure limitations.

**Comment by anthrotype** [comment]
yes, I was thinking varLib would do the merging, similarly to how it handles the other tables.
Indeed, COLR master tables would have to have identical structure.
nanoemoji currently can build a variable color font when given (via a config file) groups of SVG glyphs associated with a given location. It creates UFO masters for each and hands them off to ufo2ft to compile the variable font (which internally uses fontTools.varLib). But the COLR table is not varLib-merged yet, so only the outlines, metrics, etc. vary.
