### ISSUE TITLE
Cambria ttx roundtrip fail

### ISSUE THREAD

**Issue by stasoid** [fonttools/fonttools#2335]
ttx version: 4.24.4
OS: Windows 10

The second of these two commands:
```
ttx -y0 -d. C:\Windows\Fonts\cambria.ttc
ttx cambria.ttx
```
gives this error in _k_e_r_n.py, line 167:
```
struct.error: 'H' format requires 0 <= number <= 65535
```
Also, Cambria.ttf can be downloaded from [here](https://github.com/wchargin/compinit/raw/master/fontdata/fonts/Cambria.ttf), it gives the same error.

Removing `<DSIG>` doesn't fix the error.
If this is a problem in the font, how it can be worked around?

**Comment by stasoid** [comment]
I figured it can be worked around by removing `<kern>` table (which I don't need).

**Comment by stasoid** [comment]
OK, I finally noticed the warning that produces the first command:
```
WARNING: 'kern' subtable longer than defined: 178304 bytes instead of 47232 bytes
```
So *it is* something wrong with Cambria font. 
So, is this behavior of ttx program by design? Is user supposed to fix such warnings/errors manually before feeding .ttx-file back to ttx?

**Comment by behdad** [comment]
This is a known issue. I *think* we read the kern entries beyond the subtable length. But when writing, we don't special-case this situation. We should.

**Comment by justvanrossum** [comment]
Looking at the code, there is some attempt to write beyond what length can contain, but it seems something is not working correctly.
