### ISSUE TITLE
How can i get the advance-width table in hmtx?

### ISSUE THREAD

**Issue by hot-dog** [fonttools/fonttools#2341]
I have tried font["hmtx"].aWidth and font["hmtx"].advanceWidth, but it raises AttributeError: 'table__h_m_t_x' object has no attribute 'aWidth'.
So is there a API that can give me the advance-width table in hmtx? Or how can i get the advance-width table? Thank you!

**Comment by justvanrossum** [comment]
Here's an example: https://github.com/fonttools/fonttools/wiki/How-do-I...%3F#metrics-how-to-measure-various-things

**Comment by hot-dog** [comment]
Thank you very much, it really do me a favor!
