### ISSUE TITLE
when do we drop support for python 3.6?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#2350]
python 3.6 (released 5 years ago) officially reaches end of life at the end of this year, python 3.10 is in beta (stable is due around october).

It would be nice to be able to depend on python3.7+ only features like dataclasses, customization of module attributes, better typing, dict always ordered, etc.

I propose we drop python 3.6 by the time 3.10 reaches stable (sometime in autumn), if not even earlier.

Is anybody still using python 3.6 who would prefer to extend this further?

**Comment by behdad** [comment]
> customization of module attributes

Ooh. Let's make `import fontTools.ttLib.tables.glyf`, etc work then!

**Comment by behdad** [comment]
> Ooh. Let's make `import fontTools.ttLib.tables.glyf`, etc work then!

Or even `from fontTools.ttLib.tables import GlyfTable`. That would be a bit trickier.

**Comment by anthrotype** [comment]
> Is anybody still using python 3.6 who would prefer to extend this further?

having not heard any objections, I will assume nobody is still interested in extending support for Python 3.6 so I propose we make the next release the last one that supports 3.6 and require 3.7 from the one following.

**Comment by QuLogic** [comment]
I suggest following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) for dependency bumps.
