### ISSUE TITLE
TFM parsing module?

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#2352]
I needed to parse dome TFM (TeX Font Metrics) files for a project, and I ended up writing a TFM parser (probably 80% complete, but I only tested it on a handful of files so far).

Since I’m eternally cursed with having to deal with such legacy files, I was wondering if it makes sense to add it to FontTools? I’m asking first because I know there were suggestions to drop parsers for legacy font formats before (t1Lib and afmLib I think), so I don’t want to spend work to find out the module is unwelcome here.

**Comment by justvanrossum** [comment]
I'm in camp "yes this is useful".

**Comment by anthrotype** [comment]
Thanks! SGTM, as long as you or someone who knows TFM volunteer to maintain that module
