### ISSUE TITLE
Improve the performance of SVG table

### ISSUE THREAD

**Issue by ACCia** [fonttools/fonttools#2360]
In decompileentrylist function, can I use struct library instead of sstruct library to parse

`docIndexEntry, data2 = sstruct.unpack2(doc_index_entry_format_0, data2, DocumentIndexEntry())`

This behavior results in slow parsing when the SVG table is retained by the subset

**Comment by behdad** [comment]
If you can speed up the code, please send a Pull Request.

Also, how slows is the code for you? How do you know it's the unpack2 that is slow/ I highly doubt it.

**Comment by behdad** [comment]
> Also, how slows is the code for you? How do you know it's the unpack2 that is slow? Did you profile the code?

I can see how this is slow...
