### ISSUE TITLE
Convert SVG font to COLR?

### ISSUE THREAD

**Issue by sogen** [fonttools/fonttools#2367]
Hi, 
Would appreciate any tips or guidance:

Can fonttools convert a ttf SVG color font to a COLR ttf font? 
The final output I'm aiming for are WOFF/WOFF2 webfonts in COLR format, so it works in all browsers.

Or, if using fonttools as a middle step could I convert the SVG .ttf to a different format, ie UFO, and then convert the UFO file into a COLR ttf or webfont. 

Thanks.

Edit: 
Dumb related/unrelated question: 
Tried to research this as well, but why do UFO files _don't_ support external SVGs?

**Comment by arrowtype** [comment]
@sogen I don’t know for sure – there may be a workflow to do this – but COLR/CPAL fonts don’t support quite the same things as SVG color fonts – in particular, I know that SVG fonts can have gradients, while COLR/CPAL fonts currently cannot.

Do you have access to the actual font sources? e.g. not just SVGs, but GlyphsApp files or UFOs? If so, the most direct route may be setting up one workflow to output SVG fonts for Adobe and a second workflow to output COLR fonts for browsers.
