### ISSUE TITLE
RFE: switch from distutils setuptools

### ISSUE THREAD

**Issue by kloczek** [fonttools/fonttools#2369]
Looks like fonttools still uses distutils  instead setuptools.
Because of that it is not possible to generate documentation like below:
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx

Application error:
config directory doesn't contain a conf.py file (.)
```

**Comment by anthrotype** [comment]
we use setuptools already. what makes you think we use distutils?

**Comment by anthrotype** [comment]
@kloczek please have a look at this https://github.com/fonttools/fonttools/tree/main/Doc for instructions to build the docs, and let us know if it's missing something

/cc @chrissimpkins

**Comment by kloczek** [comment]
> we use setuptools already. what makes you think we use distutils?

There are still places where `distutils` is used.
https://github.com/fonttools/fonttools/blob/main/setup.py#L11
https://github.com/fonttools/fonttools/blob/main/setup.py#L12
https://github.com/fonttools/fonttools/blob/main/setup.py#L240
https://github.com/fonttools/fonttools/blob/main/setup.py#L241
https://github.com/fonttools/fonttools/blob/main/setup.py#L422
https://github.com/fonttools/fonttools/blob/main/setup.py#L429

**Comment by anthrotype** [comment]
we are only importing the distutils logger or some exception classes, we are not using distutils setup() function, we are using setuptools.setup() function as you can see https://github.com/fonttools/fonttools/blob/12d66ded1230c46a0e62afedfe0a16bd99d78105/setup.py#L9

I don't think simply importing a bunch of distutils functions should confuse Sphinx..
I actually don't know how sphinx integration with setuptools works to be honest.
I believe your `python setup.py build_sphinx` is just an alias for the `sphinx-build` command line tool, which comes with sphinx.

The doc readme says that without using make, one can build with sphinx-build by running `sphinx-build -b html source build`. Have you tried running that, does it work?

Maybe also try to run `python setup.py build_sphinx -b html source build` and see if that works

**Comment by kloczek** [comment]
> I don't think simply importing a bunch of distutils functions should confuse Sphinx..

It colides.
`distutils` provides the same functionalities as `setuptools` but distutils is not plugable like `setuptools`.
Uting it causes that `setup.py build_sphinx -b <format>` is not able locate copy.py file.

**Comment by anthrotype** [comment]
I have no idea what you're talking about. If you have a patch to fix that, please send a PR

**Comment by chrissimpkins** [comment]
You are looking for something along these lines Tomasz?

https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html

**Comment by chrissimpkins** [comment]
Is the [`sphinx-build` approach ](https://www.sphinx-doc.org/en/master/man/sphinx-build.html) in the [documentation](https://github.com/fonttools/fonttools/tree/main/Doc#build-documentation) **not** working for you for some reason?

**Comment by kloczek** [comment]
> Is the [`sphinx-build` approach ](https://www.sphinx-doc.org/en/master/man/sphinx-build.html) in the [documentation](https://github.com/fonttools/fonttools/tree/main/Doc#build-documentation) not working for you for some reason?

Using setuptools `build_sphinx` commanbd allow build documentation without care where is copy.py file.

**Comment by kloczek** [comment]
> You are looking for something along these lines Tomasz?
> 
> https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html



> You are looking for something along these lines Tomasz?
> 
> https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html

Yes.

**Comment by kloczek** [comment]
After year since that ticked has been opened I think that I'll close it.
All because in bean time setuptools<>sphinx integration has been marked as deprecated and I've switched to direct use sphinx-build command.
I found some issie with that method however those issues have nothing to do with this issue.

Closing.

**Comment by kloczek** [comment]
Ha I've alredy opened ticked for those issues 😋 
https://github.com/fonttools/fonttools/issues/2358
