### ISSUE TITLE
[ttLib] font.importXML() always sets sfntVersion from imported TTX

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2370]
When using `ttx -m` or `font.importXML()`, the font's `sfntVersion` is unconditionally taken from the imported TTX. That is correct if we're doing a full import (starting with an empty TTFont) but is dubious when importing some tables into an existing font. Importing (say) a name table from an .otf into an existing .ttf will set `sfntValue` to "OTTO", which is incorrect for TTF.

Perhaps we should not set `sfntVersion` if `importXML()` is called on a non-empty font.

**Comment by justvanrossum** [comment]
(I only found this because for better or for worse, FreeType rejects "OTTO" fonts that don't have a CFF or CFF2 table.)

**Comment by punchcutter** [comment]
Because of this I have a bunch of duplicate TTX files where the only difference is the sfntVersion so I can apply one to the OTF and one to the TTF. It would be nice if I could use a single file for both.

**Comment by anthrotype** [comment]
> not set sfntVersion if importXML() is called on a non-empty font.

yes, makes sense
