### ISSUE TITLE
Trouble writing 360 degrees out in color-fonts test sample glyph script

### ISSUE THREAD

**Issue by drott** [fonttools/fonttools#2371]
In the `colrv1-var-idx-map` branch using the color-fonts repo test generation script, I run into trouble with `endAngle` being 360, for 359 it works. I'd prefer if fontTools handles the mapping to the correct F2DOT14 even for large values. 

```
    colr = {
        "Format": ot.PaintFormat.PaintGlyph,
        "Glyph": glyph_name,
        "Paint": {
            "Format": ot.PaintFormat.PaintSweepGradient,
            "ColorLine": {
                "ColorStop": [
                    (0.0, *_cpal("red")),
                    (0.5, *_cpal("yellow")),
                    (1.0, *_cpal("red")),
                ]
            },
            "centerX": 500,
            "centerY": 500,
            "startAngle": 0,
            "endAngle": 360,
        },
    }

```

Error message:

```
  File "/usr/local/google/home/drott/dev/fonttools/Lib/fontTools/ttLib/tables/otConverters.py", line 434, in write
    writer.writeShort(fl2fi(value, 14))
  File "/usr/local/google/home/drott/dev/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 448, in writeShort
    assert -32768 <= value < 32768, value
AssertionError: (32950, 'float', 'Paint', 'Paint', 0, 'BaseGlyphPaintRecord[]', 'BaseGlyphList')
```

What values should I best use for a full circle?

**Comment by anthrotype** [comment]
yes, 360 doesn't fit the new angles defined as fractions of half circle and encoded as F2Dot14, because 360 / 180 == +2.0 can't be encoded as F2Dot14. But -2.0 can, so the full circle from -360 to 0 (or -1 to 359) would fit...

**Comment by drott** [comment]
Ack, I'll use -360 to 0, thanks. I agree with the discussion in https://github.com/fonttools/fonttools/pull/2359#discussion_r664800008
