### ISSUE TITLE
saveXML should use the same line ending on all platforms

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#2383]
It is 2021, `newlinestr` should default to `\n` or even be deprecated and `\n` always used.

**Comment by khaledhosny** [comment]
There should be 0 occurrences of `os.linesep` in the repo.

**Comment by anthrotype** [comment]
> newlinestr should default to \n

fair enough

> or even be deprecated and \n always used.

I don't see why we should restrict that.

**Comment by khaledhosny** [comment]
> I don't see why we should restrict that.

Because it is not something FontTools should have ever been concerned about. If someone wants to use different line endings for whatever reasons, there are no shortage of tools that can convert between line breaks. By disabling this functionality we can later remove the API entirely if we get to break the API. Just like how `XMLWriter` no longer support any encoding other than UTF-8 (it will raise if any other encoding is used, but line spacing is more minor IMHO so I just warn and ignore).
