### ISSUE TITLE
HTML entities not remaining as actual characters when dumping via TTX

### ISSUE THREAD

**Issue by laerm0** [fonttools/fonttools#2389]
I.e. if one of your tables has a `<` in it for whatever reason, ttx dumps that as the HTML entity code `&lt;`. Now I'm not sure if this is a bug – there very well might be some reason for it to exist in ttx – but some of those characters are used in TT hints and it makes me nervous if ttx can't keep them as they should be.

**Comment by justvanrossum** [comment]
ttx is an XML format, and you can't use `<` unescaped in XML, so it has to become `&lt;`. The reverse will be done during parsing, so there's no reason to be nervous. It just looks a little ugly.

**Comment by laerm0** [comment]
That was what I was thinking. Sorry for the obvious question: I have COVID and fever-brain is definitely a real thing. 😁 Thanks @justvanrossum !
