### ISSUE TITLE
How to find out what characters a given font supports

### ISSUE THREAD

**Issue by workingxx92** [fonttools/fonttools#2392]
Hello,
How to find out what characters a given font supports.?
EX: I have an input font https://www.dafont.com/cf-halloween.font.

output expect:
Only supported: A-Z ( uppercase) and 0-9

**Comment by anthrotype** [comment]
you can dump the font to XML using the `ttx` command included in FontTools, and inspect its `cmap` (or character mapping) table.

**Comment by workingxx92** [comment]
Hi.
Could you tell me more? I tested with this code and It's not working.
```
font = TTFont('data/FONTS/CFHalloween-Regular.ttf')

def has_glyph(font, glyph):
    for table in font['cmap'].tables:
        if ord(glyph) in table.cmap.keys():
            print(glyph)
            return True
    return False

print(has_glyph(font, 'A'))

font.close()
```

**Comment by workingxx92** [comment]
Here font
[cf_halloween (3).zip](https://github.com/fonttools/fonttools/files/6962458/cf_halloween.3.zip)
