### ISSUE TITLE
Not cleaning up ClipRecord when subsetting COLRv1?

### ISSUE THREAD

**Issue by rsheeter** [fonttools/fonttools#2408]
```
pyftsubset --unicodes='U+004e U+006f U+0074 U+0020 U+0043 U+006c U+0072 U+0045 U+006d U+006a U+0069 U+0063 U+0066 U+0030' color-fonts/fonts/noto-cff_colr_1.otf 
WARNING: ClipRecord[0] range references missing glyph IDs: [13-13]
...many more such warnings...
```

color-fonts is https://github.com/googlefonts/color-fonts. Guessing we aren't subsetting the clip records yet.

**Comment by rsheeter** [comment]
Hm. I don't see this on main and I do on the latest release. Might be all we need is a release.

**Comment by anthrotype** [comment]
Yes, sorry, I had fixed this directly on main branch but didn't cut a release since. I'll do that today
https://github.com/fonttools/fonttools/commit/99743c14

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/releases/tag/4.27.0
