### ISSUE TITLE
Unable to find the codepoint where the ttf file does have

### ISSUE THREAD

**Issue by Zaoyee** [fonttools/fonttools#2429]
I am unsure if this case belongs to this repo, or it may be a general issue.
In my project, I cannot find a specific codepoint in the font through cmaps of `tonttools` lib. Meanwhile I am not able to find that glyph through some other font glyph viewer program. But the font is able to display that character in Windows, Android as well as Android `hasGlyph()` check. It gets confused. 

Agin, Thanks for your work.

**Comment by jenskutilek** [comment]
What kind of font? (TTF, OTF, CID-keyed ...) For looking up codepoints in the cmap table, you can use the `TTFont.getBestCmap()` function.
