### ISSUE TITLE
[otlLib] `buildCoverage` does not remove duplicate glyphs

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fonttools#2433]
If a class in a feature file includes duplicate glyphs, `buildCoverage` is called on a list that includes duplicate glyphs. `buildCoverage` sorts the input glyphs but does not remove duplicates.
```pycon
>>> import fontTools.otlLib.builder
>>> fontTools.otlLib.builder.buildCoverage(['A', 'B', 'A'], {'A': 1, 'B': 2}).glyphs
['A', 'A', 'B']
```
[The spec](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#coverage-table) says “A Coverage table defines a unique index value, the _Coverage Index_, for each covered glyph”, but a glyph listed multiple times won’t have a unique index.

This can cause a problem when using the OpenType Sanitizer: if a CoverageFormat1 table lists more glyphs than are declared in 'maxp', OTS reports an error.

**Comment by anthrotype** [comment]
I'm actually not sure about this. Can @khaledhosny or @simoncozens take a look?

**Comment by simoncozens** [comment]
Related problem I've been wanting to fix for a while: feaLib allows empty classes, which it then hands to the builder, and the builder dies. Both issues should be caught earlier.

**Comment by khaledhosny** [comment]
I defer to @dscorbett expertise here, but it looks like the right thing to do in general.
