### ISSUE TITLE
feaLib miscompiles chaining rules with non-single substitution lookup references

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fonttools#2469]
When a chaining substitution rule contains multiple lookup references, and those references are to anything more complex than single substitution lookups, then feaLib is liable to miscompile that rule.

[Example 1 of section 5.f.i of the feature file spec](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#example-1-1) contains such a rule:
```fea
    substitute [ a e i o u] f' lookup CNTXT_LIGS i' n' lookup CNTXT_SUB;
```
The spec explains that given the input glyph sequence `a f i n`, the output glyph sequence will be `a f_i n.end`. That means that lookup references are written after the glyphs they apply to, without considering how other referred-to lookups might shift sequence indices. In other words, this rule does what it seems like it obviously should do.

However, this is not what feaLib does. feaLib compiles each lookup reference with a sequence index of whatever the index is of the glyph in the rule, and the references are ordered in ascending order by sequence index. `f` is at index 0, so `lookup CNTXT_LIGS` gets a sequence index of 0. `n` is at index 2, so `lookup CNTXT_SUB` gets a sequence index of 2.  `CNTXT_LIGS` is applied before `CNTXT_SUB`. This produces the wrong behavior: by the time `CNTXT_SUB` applies, the input glyphs are `f_i n`, so there is nothing at index 2.

Here is a full example. It uses Noto Sans as a base for convenience but replaces its GSUB with something based on the spec’s example.
```
$ curl -LOs https://github.com/googlefonts/noto-fonts/raw/6ba0153eb79a01d69f96fbd87512fe1ca1e778ef/unhinted/otf/NotoSans/NotoSans-Regular.otf
$ python3 <<'EOF'
from fontTools.feaLib.builder import addOpenTypeFeaturesFromString
from fontTools.ttLib.ttFont import TTFont
with TTFont('NotoSans-Regular.otf') as font:
    del font['GPOS']
    addOpenTypeFeaturesFromString(font, '''
lookup CNTXT_LIG {
    substitute f i by fi;
} CNTXT_LIG;

lookup CNTXT_SUB {
    substitute e by uni2C78;
    substitute n by eng;
} CNTXT_SUB;

feature liga {
    substitute [a e i o u] f' lookup CNTXT_LIG i' n' lookup CNTXT_SUB e';
} liga;
''')
    font.save('test.otf')
EOF
$ hb-shape --no-positions test.otf afine
[a=0|fi=1|n=3|uni2C78=4]
```

The rule is clearly meant to apply `CNTXT_SUB` to `n`, not to `e`, so the correct output is `a fi eng e`.

One way to fix this is to compile the lookup references with sequence indices in descending order, instead of the current ascending order. That is, `CNTXT_SUB` would be applied at index 2, _then_ `CNTXT_LIG` would be applied at index 0. People could be relying on the current order, but unfortunately I don’t see another way to make the example in the spec work.

**Comment by simoncozens** [comment]
This would be an extremely breaking change.

**Comment by dscorbett** [comment]
Moreover, makeotf also has the same issue.
```bash
$ curl -LOs https://github.com/silnrsi/font-nokyung/archive/refs/tags/v1.490.tar.gz
$ tar -zxf v1.490.tar.gz
$ cat >features.fea <<'EOF'
languagesystem DFLT dflt;
languagesystem latn dflt;

lookup CNTXT_LIG {
    substitute f i by fi;
} CNTXT_LIG;

lookup CNTXT_SUB {
    substitute e by E;
    substitute n by N;
} CNTXT_SUB;

feature liga {
    substitute [a e i o u] f' lookup CNTXT_LIG i' n' lookup CNTXT_SUB e';
} liga;
EOF
$ makeotf -f font-nokyung-1.490/source/Nokyung-Regular.ufo -o Nokyung-Regular.otf -ff features.fea >/dev/null
$ hb-shape Nokyung-Regular.otf afine
[a=0+936|fi=1+1016|n=3+991|E=4+970]
```
So the example in the spec is wrong. Never mind then.
