### ISSUE TITLE
How to rename fvar instances?

### ISSUE THREAD

**Issue by juandelperal** [fonttools/fonttools#2470]
Hi fonttools team!
We are working on a big project, with 5 axes and more than 180 named instances.
- We are generating the fonts with fontmake.
- After that, we are working with `fontTools.varLib.instancer` for making partial variable fonts, including different _subspaces_ of the whole design space. 
- And we would like to rename the family name and `fvar instances` accordingly.

So, instead of 
**Family** - Extended Black

We'd like to use
**Family Extended** - Black

We can do it by manipulating the .designspace file and regenerating it, but regenerating the files is painfully slow in such a big family.
 
What is the most straightforward approach for doing this?

**Comment by jenskutilek** [comment]
Not sure how the instancer handles the STAT table, but it might contain enough data after instancing to extract a family and style name, apply some logic via script to it (in your case, adding the width axis name to the family name), and after that rewriting the name table.

**Comment by juandelperal** [comment]
Thanks Jens!
Yes, that's how we made it, also hardcoding some naming exceptions.
