### ISSUE TITLE
Missing left part of Khmer surrounding vowels

### ISSUE THREAD

**Issue by sovichet** [fonttools/fonttools#2482]
The `pyftsubset` lib doesn't include the left part of Khmer surrounding vowels:
ើ (17BE) `oeSign-khmer`
ឿ (17BF) `yaSign-khmer`
ៀ (17C0) `ieSign-khmer`
ោ (17C4) `ooSign-khmer`
ៅ (17C5) `auSign-khmer`

The left part of these vowels is (េ) 17C1 `eSign-khmer`. The left part is available in the subset font unless there is the 17C1 in the text.

**Test font**: https://fonts.google.com/specimen/Khmer?subset=khmer
**Test txt:** ក្កក្ខកើកឿកៀកោកៅ
**Subset result:** .notdef, ka-khmer, kha-khmer, oeSign-khmer, ieSign-khmer, coeng-khmer, coeng_ka-khmer, coeng_kha-khmer, ieSign-khmer.pstf0 (no presence of `eSign-khmer`)

Shaped by Simon's `shape` perl script
![image](https://user-images.githubusercontent.com/1669566/146759634-70384d2f-faaa-4b37-817c-2c827da2d2cd.png)

Issue on Google Fonts
![image](https://user-images.githubusercontent.com/1669566/146759934-5ffb61b0-ec3f-4c77-bb18-0e69d20a9c72.png)

**Comment by dscorbett** [comment]
This is #2387.

**Comment by sovichet** [comment]
> This is #2387.

Thank you!

**Comment by anthrotype** [comment]
thanks for the report, closing as duplicate
