### ISSUE TITLE
Had to install two dependencies manually to run pyftsubset

### ISSUE THREAD

**Issue by aral** [fonttools/fonttools#2486]
I was running glyphhanger, which uses pyftsubset.

I’d installed fonttools with:

`sudo pip install fonttools` 

(because without sudo, glyphhanger couldn’t find pyftsubset) :man_shrugging: 

Ran glyphhanger and got the following pyftsubset error:

```
ModuleNotFoundError: No module named 'zopfli'
```

`pip install zopfli`

Ran glyphhanger and got the following pyftsubset error:

```
ImportError: No module named brotli
```

`pip install brotli`

Ran glyphanger and it worked.

**Comment by chrissimpkins** [comment]
zopfli and brotli are optional dependencies. They are installed automatically with the `woff` [extras dependencies](https://stackoverflow.com/a/52475030/2848172) configuration:

```
pip install fonttools[woff]
```

or in your requirements.txt file:

```txt
fonttools[woff]==4.28.5
```
