### ISSUE TITLE
Cross-platform Rasterisation Pen?

### ISSUE THREAD

**Issue by takaakifuji** [fonttools/fonttools#2492]
Is there a handy way to rasterise the paths obtained via pen protocol in a cross-platform manner?

- `CocoaPen`/`QuartzPen` is pretty handy unless you are on a non-macOS environment (e.g. Google Colab)
- `QtPen`/`WxPen` is useful only if it's already used within your codebase as a widget toolkit
- `skia-pathops` is a library dedicated to boolean operations but not for drawing

I might be missing something, but I couldn't find a solution that fully suits my needs. After all, I wrote a pen that finds the existing FreeType installation on the system, constructs `FT_Outline` and let FreeType rasterise the paths. As mentioned in #1769, I agree this is out of scope, but on the other hand I think it makes more sense to wrap it as a pen. If you are interested, I'll share and compile a PR.

**Comment by anthrotype** [comment]
I think it would be nice to have a pen that uses freetype-py to rasterize a glyph, yes please send a PR thanks!

**Comment by takaakifuji** [comment]
Thanks for the comment! I've just sent a PR, and please  have a look when you have time.
