### ISSUE TITLE
Error about pyftsubset.exe --name-languages='*'

### ISSUE THREAD

**Issue by husk0808** [fonttools/fonttools#2493]
There is a.ttf
Not inside
     <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
....
He only has
     <namerecord nameID="0" platformID="3" platEncID="1" langID="0x0x404">
Preset
--name-languages only 0x409
So use this code
pyftsubset "Y:\a.ttf" --text="ABCD" --output-file="Y:\b.TTF"
There will be no name information
but
Use --name-languages='*'
There is no data for name

**Comment by behdad** [comment]
> --name-languages='*'

Try `--name-languages="*"`
