### ISSUE TITLE
[T1Font] Unable to save charstrings in T1Font after changing them

### ISSUE THREAD

**Issue by derwind** [fonttools/fonttools#2503]
Currently, T1Font does not allow `saveAs` after `parse`. This means that we can't save charstrings after changing them. I wanted to change the hints, so I implemented the ability to recreate the PS stream: https://github.com/derwind/fonttools/commit/49b673b3ba04f71cb3da61c0168f4e18374ddda7

Type 1 is already a legacy format, and Adobe will discontinue support for it next year. If you think the improvement described above is still worthwhile, I would like to make a pull request. What do you think?

In addition to T1_SPEC.PDF, 5015.Type1_Supp.pdf, and PLRM.pdf, I referred to AFDKO's [t1write.c](https://github.com/adobe-type-tools/afdko/blob/develop/c/shared/source/t1write/t1write.c) a lot, because I am only familiar with Type 1 files converted from other formats (e.g. UFO) by AFDKO. Also, I am sorry to say that I have not do tests exhaustively, and it may be an immature implementation.

**Comment by justvanrossum** [comment]
I am not against this although I fear it won't get a lot of use.

I'd be happy to review. Glad to see you wrote tests.

@anthrotype, would you consider this addition to t1Lib?

**Comment by anthrotype** [comment]
Of course, please send a PR! Though I don't know much about T1 fonts so I can only do a superficial review

**Comment by derwind** [comment]
Thank you very much.
At first I hesitated to implement these immature codes by myself, but I was the one who wanted the feature, so rather than bothering you, I thought I would implement it and share it with you.
It may not be used often, but I will make a pull request to help anyone in any way I can.
