### ISSUE TITLE
TTX hangs with (Hit any key to exit)

### ISSUE THREAD

**Issue by bjg2** [fonttools/fonttools#2507]
Hi all, and thank you very much for this tool!

I call TTX programmatically from another golang process, and once in a while it happens that ttx runs into the error. Problem is it does not error out, write and dies, but writes "(Hit any key to exit)". And I don't know how to recognize I need to send keypress to the process, nor do I know how to send that keypress to another process programmatically.

Is it possible to provide some flag or anything not to hang on this? Or what do you advise?

Thanks, Aleksandar

**Comment by anthrotype** [comment]
hi, thanks for the report. It appears you are running ttx on windows, am I right? There's a old feature whereby ttx forces the windows command prompt window to stay open. I think it was added because some Windows users have ttx as a batch command where they drag and drop a font on it, a new cmd.exe windows fires then closes automatically on completion, but when an error occurred you don't get to see the error message..

https://github.com/fonttools/fonttools/blob/f7653a577db40d7e7bb25e75da4df07289e67ab6/Lib/fontTools/ttx.py#L390-L396

We should probably detect whether we are running in an interactive shell session, and if not, don't wait for key press.

**Comment by anthrotype** [comment]
actually forget what I just said about interactive mode, that's something else.
We have two options: 1) remove the feature altogether (I would consider this "legacy"), or 2) add a new flag to ttx command line to opt-out from the wait for key press.
I am leaning towards option 1. /cc @justvanrossum

**Comment by anthrotype** [comment]
ok yeah, there's a 3) option to try, which is check [`sys.stdout.isatty()`](https://docs.python.org/3/library/io.html#io.IOBase.isatty) which "Return True if the stream is interactive (i.e., connected to a terminal/tty device)." If False, don't wait for key press ('cause there can't be any).

**Comment by anthrotype** [comment]
I don't have a windows machine at hand to try this; if @bjg2 would like to give it a shot and make a PR to disable waitForKeyPress if not isatty(), you're welcome thanks!

**Comment by justvanrossum** [comment]
Oh this was added a looong time ago. I wonder if @twardoch may remember. If it was because of a .bat script (on which you could drop files?), then this behavior should perhaps be part of the .bat script itself.

**Comment by bjg2** [comment]
Hey guys, thanks for the quick turnaround!

Yes, I can confirm I am using ttx on windows. Unfortunately, I never coded in this workspace, nor do I have python setup, nor did I work in python for a long time (just one project many years ago)... I guess you would not want me just to send an untested PR with a new if. and I'm afraid it would take me a bit of disproportional amount of time to set it up and test it... Would someone else be able to pop this if inside easier?

**Comment by anthrotype** [comment]
I made a PR #2509 to remove the legacy waitForKeyPress. The same can be achieved by using the [`pause`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/pause#:~:text=You%20can%20insert%20the%20pause,to%20stop%20the%20batch%20program.) command in a windows batch script

**Comment by bjg2** [comment]
Thank you very much for quick turnaround! You are the best!

Just another question, I install the tool via `pip install fonttools[ufo,lxml,woff,unicode]`. When can I expect this change to reach the pip, and where can I check if that happened? This is nothing urgent, nothing is on fire, everything works, this is just a question to know when to update the tool as I don't know the release procedure.

Thanks very much again!

**Comment by anthrotype** [comment]
you can click the repository's "Watch" button to get notified by Github about new releases. I think we can cut a new one before the end of this week. Stay tuned

**Comment by bjg2** [comment]
I tested it and it is working as expected! Thank you very much!
