### ISSUE TITLE
[designspaceLib] parameterised constructors for Descriptor objects

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fonttools#2519]
I'm probably being dense here but is there a reason why descriptor objects don't have parameterised constructors?

We currently have to initialise and then populate its attribs.

```PYTHON
source = SourceDescriptor()
source.path = "mysource.ufo"
source.name = "My Font"
```

Wish

```PYTHON
source = SourceDescriptor(path="mysource.ufo", name="My Font")
```

**Comment by anthrotype** [comment]
probably just historical reasons. I also think the latter is more idiomatic. I like when the default constructor gives you a fully constructed object, and there's no in-between state where the object is not fully defined. I think @madig was working on turning designspaceLib descriptors into dataclasesses..

**Comment by anthrotype** [comment]
wait.. you _can_ use keyword arguments! Maybe the docs are outdated?

https://github.com/fonttools/fonttools/blob/69fc06a1af6a3108b6983b8bf96935327b873916/Lib/fontTools/designspaceLib/__init__.py#L97-L125

**Comment by anthrotype** [comment]
I had forgotten my previous self actually added those https://github.com/fonttools/fonttools/pull/1860

**Comment by m4rc1e** [comment]
Thanks! my bad, I've just seen the repo I'm looking at is using the deprecated designspaceLib.

**Comment by justvanrossum** [comment]
Note that you can also write `doc. addSourceDescriptor(**kwargs)` for even more convenience.
