### ISSUE TITLE
Problems under pyftsubset

### ISSUE THREAD

**Issue by husk0808** [fonttools/fonttools#2523]
Problems with special symbols in VERTICAL
parameters used
pyftsubset "\\DS3617\方正准圆_GBK.TTF" --text="「」" --output-file="\\DS3617\CO8FABC0.TTF" --font-number="0" --layout-features='*'
normal
![1](https://user-images.githubusercontent.com/75479368/152386142-e65e322a-9d64-44e8-ae3b-e44171905767.jpg)
pyftsubset
![2](https://user-images.githubusercontent.com/75479368/152386153-26a9321b-64a2-435a-9a23-0f9232ada442.jpg)
'
What parameters do I need to enter to be the same as the original?
[方正准圆_GBK.zip](https://github.com/fonttools/fonttools/files/7996435/_GBK.zip)

**Comment by husk0808** [comment]
There is a paragraph in GSUB
           <Substitution in="uni300C" out="uniFE41"/>
pyftsubset
Because should keep uni300C uniFE41
There are also relevant information on the GSUB table

**Comment by behdad** [comment]
This works for me.
