### ISSUE TITLE
TypeError: setCoordinates() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#2535]
If I update the FontTools dependency of https://github.com/arrowtype/recursive-code-config from `fonttools==4.17.0` to `fonttools[lxml,ufo,unicode]>=4.26.1` (as is suggested by pip when I install `ttfautohint-py`, I suddenly run into the following error: 

```
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/recursive-code-config/scripts/instantiate-code-fonts.py", line 240, in <module>
    splitFont()
  File "/Users/stephennixon/type-repos/recursive-code-config/scripts/instantiate-code-fonts.py", line 157, in splitFont
    dlig2calt(outputPath, inplace=True)
  File "/Users/stephennixon/type-repos/recursive-code-config/scripts/dlig2calt.py", line 71, in dlig2calt
    font['glyf'].setCoordinates(glyphName, newCoords, font)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fontTools/misc/loggingTools.py", line 529, in wrapper
    return func(*args, **kwargs)
TypeError: setCoordinates() takes 3 positional arguments but 4 were given
```

If I re-install the older version, that works fine.

I don’t think I’m giving 4 args to `setCoordinates()`, but I’m probably misunderstanding something basic. It’s probably not super necessary for me to update FontTools in that project, as the older version is working fine, but I’d like to learn about it if I’m missing something obvious, or if there is a bug, I wanted to maybe help point to it.

Any insights appreciated! Thanks so much.

**Comment by justvanrossum** [comment]
Hm, it seems the deprecated-but-should-be-bw-compatible method is wrong: it doesn't even take a `coords` argument.

https://github.com/fonttools/fonttools/blob/3e0caa881e58ad9d3685725f198ef4f196ab2536/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L483-L489

You should probably use `_setCoordinates` instead as the comment suggests (which has a different signature):

https://github.com/fonttools/fonttools/blob/3e0caa881e58ad9d3685725f198ef4f196ab2536/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L391-L404
