### ISSUE TITLE
pyftinstance?

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#2537]
There is `pyftsubset` and `pyftmerge`... should there be a `pyftinstance`?

**Comment by anthrotype** [comment]
Because we want to avoid having too many scripts installed and prefer that all future console entry points are sub commands of the `fonttools` main CLI.

**Comment by anthrotype** [comment]
At least, that was my preference, open to discuss and change my mind

**Comment by behdad** [comment]
> Because we want to avoid having too many scripts installed and prefer that all future console entry points are sub commands of the `fonttools` main CLI.

Agreed. pyftsubset / pyftmerge / ttx are grandfathered.
