### ISSUE TITLE
Pyftmerge doesn't recalculate xAvgCharWidth

### ISSUE THREAD

**Issue by aaronbell** [fonttools/fonttools#2538]
I'm running a script to merge a small set of glyphs (xAvgCharWidth 1024) into a Japanese font that contains a large number of 2048 width glyphs (with xAvgCharWidth of 1991).

The xAvgCharWidth output of pyftmerge is 1507, which is the average of the xAvgCharWidth for each of the fonts. However, the correct xAvgCharWidth should be 1965, which reflects the actual composition of the merged font. 

Fontbakery flags this as an issue. 

I'd suggest re-calculating the xAvgCharWidth value post merge to ensure correctness of the output. Potentially the code could be pulled directly from the [fontbakery check](https://github.com/googlefonts/fontbakery/blob/main/Lib/fontbakery/profiles/os2.py)?

**Comment by davelab6** [comment]
Script is now @ https://github.com/googlefonts/morisawa-biz-ud-mincho/blob/180fac5e407fe3f047c2edbed1cd683bf9eebaca/sources/build.py#L152

**Comment by davelab6** [comment]
@simoncozens would you be interested to fix this as I guess it may be needed for Noto CJK work?
