### ISSUE TITLE
Disable GPOS7 optimisation

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#2539]
I've just discovered, through a horrible chain of events, that Apple's CoreText shaper does not support GPOS7 positioning rules.

```fea
feature kern {
    pos b' 1000;
    pos c  1000;
} kern;
```
![shape](https://user-images.githubusercontent.com/106728/156845047-b155c731-d83c-4aa4-91bc-bbb7c6038d17.png)

Turn them into GPOS8 positioning rules by changing

https://github.com/fonttools/fonttools/blob/ac4d5611ac793e4815f64eb05d46e0cb46ec4612/Lib/fontTools/otlLib/builder.py#L372

to

```
chaining = True
```

and you get 

![shape](https://user-images.githubusercontent.com/106728/156845206-5680d57f-a479-427b-b7fb-f192666403f6.png)

I haven't tested support for GSUB5 versus GSUB6 because I'm tired and angry. I've filed a bug with Apple, but we should probably disable this for now.

**Comment by simoncozens** [comment]
GSUB5 seems to work, it's just GPOS 7.

**Comment by simoncozens** [comment]
But [GSUB5 does not work well on certain versions of Windows](https://typedrawers.com/discussion/4360/indic-shaping-issue-in-devanagari-font).

**Comment by khaledhosny** [comment]
CoreText seems to have been fixed (testing on macOS 13.2.1), should we re-enable the optimization?

**Comment by anthrotype** [comment]
maybe it's safer to wait a bit more, not everyone upgrades immediately (I for one have been delaying update forced upon my corp device by IT admin for weeks as I don't want to reboot 😅 )

maybe if you like, we can add an option to enable that optimization? we could potentially define one in the fontTools.config (so it's accessible in TTFont.cfg)

**Comment by khaledhosny** [comment]
> maybe it's safer to wait a bit more, not everyone upgrades immediately (I for one have been delaying update forced upon my corp device by IT admin for weeks as I don't want to reboot 😅 )

Understandable.

> maybe if you like, we can add an option to enable that optimization? we could potentially define one in the fontTools.config (so it's accessible in TTFont.cfg)

That would be nice.

**Comment by khaledhosny** [comment]
> > maybe if you like, we can add an option to enable that optimization? we could potentially define one in the fontTools.config (so it's accessible in TTFont.cfg)
> 
> That would be nice.

https://github.com/fonttools/fonttools/pull/3034
