### ISSUE TITLE
Subsetting CFF font requires unused character to be included for correct rendering

### ISSUE THREAD

**Issue by drott** [fonttools/fonttools#2554]
Subsetting Noto Sans CJK JP to U+3084, U+304d, U+306b without U+302B leads to unexpected pixel positioning artefacts in vertical layout.

![image](https://user-images.githubusercontent.com/1021784/159036157-ffaccad4-78f2-4062-ad8e-14509d209d45.png)
[repro.zip](https://github.com/fonttools/fonttools/files/8305907/repro.zip)

Repro:
* Unpack zip
* Open vertical.html in Chrome Linux (_Edit:_ Easiest to repro on Linux)
* Observe positioning of third ideograph

Expected: Red overlay should appear in the same position as the black underlying glyph and not be positioned further down.

The subsetted font is produced with:
`$ pyftsubset --output-file=notosanscjkjpsub.otf notosanscjkjp.otf --unicodes=3084,304d,306b`

If I add **U+302B** to the subsetted file, the rendering and positioning look correct. "Correct" because I would not expect an unused character to have an effect on the output.
`$ pyftsubset --output-file=notosanscjkjpsub.otf notosanscjkjp.otf --unicodes=3084,304d,306b,302b`

**Comment by drott** [comment]
TTX Diff: https://gist.github.com/drott/fcec7ea929282dfb20e03404fc2b33bb

**Comment by behdad** [comment]
I don't think this is a subsetter bug. See https://github.com/harfbuzz/harfbuzz/issues/3486#issuecomment-1074224102
