### ISSUE TITLE
`SVG ` and `head::[xy][Min|Max]`

### ISSUE THREAD

**Issue by bungeman** [fonttools/fonttools#2566]
The `glyf`, `CFF `, and `CFF2` glyphs all update the bounds in the `head` table, but it looks like `SVG ` glyphs are not currently considered. Some `SVG ` fonts will have a `glyf` table with a `.notdef` and maybe a few other entries, so the `head` bounds end up being the size of these few `glyf` entries. The union of the bounds of the `SVG ` glyphs should be determined and also unioned into the `head` bounds.

**Comment by anthrotype** [comment]
Hm, parsing SVG is notoriously tricky, and I suspect our current parser in fontTools.svgLib may not work reliably on any arbitrary svg glyph. [picosvg](https://github.com/googlefonts/picosvg), among other things, can compute the bounding box of svg shapes (we use it in [nanoemoji](https://github.com/googlefonts/nanoemoji) to compile COLRv1 fonts from SVGs), however I'm not sure that we want to pull that in as a dependency.
By the way, does the OT spec say anything about head bounds needing to include SVG glyphs?

**Comment by bungeman** [comment]
It looks like the specification addresses the question of individual glyph bounding boxes in [Coordinate Systems and Glyph Metrics](https://docs.microsoft.com/en-us/typography/opentype/spec/svg#coordinate-systems-and-glyph-metrics),

> The “ink” bounding box of the rendered SVG glyph should be used if a bounding box is desired; this box may be different for animated versus static renderings of the glyph.

However, it doesn't specify anything about the `head` table bounds. I suppose it's difficult since in theory the SVG could be animated. I'll just have to remember to mark any font which may draw a glyph out of `SVG ` that the `head` table bounds can't be used. Considering the difficulty with this, I think it's fine for `SVG ` to make the font slow for damage and clipping purposes
