### ISSUE TITLE
breaking tools... ufo2ft

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#2592]
in https://github.com/googlefonts/ufo2ft/blob/main/Lib/ufo2ft/__init__.py#L6

```python
from fontTools.otlLib.optimize.gpos import GPOS_COMPACT_MODE_ENV_KEY
```

```traceback
ImportError: cannot import name 'GPOS_COMPACT_MODE_ENV_KEY' from 'fontTools.otlLib.optimize.gpos'
```

**Comment by anthrotype** [comment]
hm yeah, no good. Though we did say the env var was going to be temporary/experimental hack. I'll just fix ufo2ft now.

**Comment by anthrotype** [comment]
Actually the fix in ufo2ft is a bit more involved (requires we add new api to specify/pass down fonttools config options), while we think about it in the meantime I think we need to reintroduce the environment variable hack in fonttools.
Apologies for any disruptions, for now please pin your fonttools to the previous version while we fix this.

**Comment by typemytype** [comment]
thanks!

**Comment by arialcrime** [comment]
Came here to report the same issue preventing fontmake/fontbakery from running. Great to see it already being taken care of, thanks!
