### ISSUE TITLE
designspaceLib isinstance fails for custom descriptors

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#2631]
in Designspace editor we have custom descriptor objects that works nicely with NSObjects 

https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/designspaceLib/__init__.py#L1448-L1452

patch:

hasattr(axisObject, "values") --> DiscreteAxisDescriptor
hasattr(axisObject, "minimum") and hasattr(axisObject, "maximum") --> AxisDescriptor

**Comment by belluzj** [comment]
Agreed, I'll open a PR with the fixes.

**Comment by LettError** [comment]
Can we add `AxisLabelDescriptor` to `__all__` in https://github.com/fonttools/fonttools/blob/feb4e75469910d239fb72d80bbc979a121a6f87c/Lib/fontTools/designspaceLib/__init__.py#L24

**Comment by belluzj** [comment]
I opened a second MR to add missing classes to `__all__`: https://github.com/fonttools/fonttools/pull/2640/files

**Comment by LettError** [comment]
Thanks!
