### ISSUE TITLE
[varLib] Generate variable fonts with deltas larger than original data type?

### ISSUE THREAD

**Issue by drott** [fonttools/fonttools#2641]
Is the intention with COLRv1 deltas for various fields that it should be possible to generate deltas that are larger than the representable numbers in the underlying font data type?

Example, should it be possible to provide an angle delta to a sweep gradient of something that's larger than the F2DOT14 angles, for example 720 degrees?

If so, I did not find a way so far to represent that in master I am generating in the test font generator script. Is there a way? 

Or is the intention that that should not be possible and deltas and resulting values do need to be clamped to the underlying type? I am finding ambiguous statements in the OpenType spec on that.

**Comment by behdad** [comment]
It is allowed for drops deltas to be larger, at least in the COLR table. Its a limitation of the master-based workflow.

You can edit the ttx of the variable font and edit the deltas for example.

**Comment by drott** [comment]
> I am finding ambiguous statements in the OpenType spec on that.

Filed https://github.com/MicrosoftDocs/typography-issues/issues/939

**Comment by drott** [comment]
> @behdad  this as completed 8 hours ago.

As in "WAI", or did anything change?

**Comment by behdad** [comment]
> > @behdad  this as completed 8 hours ago.
> 
> As in "WAI", or did anything change?

Yes, I believe so. And I see you filed spec issue for clarification. Is there anything to be done here?

**Comment by behdad** [comment]
> If so, I did not find a way so far to represent that in master I am generating in the test font generator script. Is there a way?

It's not possible to do that in our master-focus workflow, but is possible if you build the variation-store yourself. Let me know what you see as needing to be done here.

**Comment by behdad** [comment]
This is not possible in the generate-varfont-from-masters workflow. That's by design.
