### ISSUE TITLE
Does (should?) fontTools enforce "valueCount must == Coverage glyphCount" for SinglePosFormat2?

### ISSUE THREAD

**Issue by josh-hadley** [fonttools/fonttools#2658]
Per [OTSpec](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#single-adjustment-positioning-format-2-array-of-positioning-values) in SinglePosFormat2 subtables, the `valueCount` "_must_ equal `glyphCount` in the Coverage table." The attached ttx dump uses a SinglePosFormat2 with Coverage glyphCount of 2 and no ValueRecords (i.e. count = 0). `ttx` compiles this with the format2 subtable's `valueCount` set to zero and a non-empty Coverage (count = 2), with no error or warning issued. Is this expected?

cc: @punchcutter 
[gpos1_2_valueCount0.ttx.zip](https://github.com/fonttools/fonttools/files/8943497/gpos1_2_valueCount0.ttx.zip)

**Comment by behdad** [comment]
There's generally dozens, if not hundreds, of places that there are such relationships in a font. Fonttools does not enforce any of them, and to me, it's good that it doesn't.

**Comment by behdad** [comment]
> it's good that it doesn't.

Because the byte format allows for divergent numbers, and it's good that ttx/fonttools allow for constructing what the byteformat allows.

**Comment by josh-hadley** [comment]
Thanks for your thoughts @behdad
It would perhaps be appropriate for fontbakery and/or OTS to check though, no?

**Comment by behdad** [comment]
> OTS to check though, no?

Yes, this is the kind of things that OTS does I believe.

**Comment by josh-hadley** [comment]
I'll poke around there and see what's going on. The current version doesn't seem to flag it.

I'll close this out as there's no action needed here.
