### ISSUE TITLE
[feaLib] "Ambiguous glyph name" warning is unhelpful

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#2664]
We have lost the battle; glyph names have hyphens in them now.  The constant deluge of

```
WARNING:fontTools.feaLib.parser:foo.fea:123:36: Ambiguous glyph name that looks like a range: 'finalnun-hb'
WARNING:fontTools.feaLib.parser:foo.fea:123:48: Ambiguous glyph name that looks like a range: 'finalpe-hb'
```

warnings just doesn't help anyone. It should be silenced.

**Comment by anthrotype** [comment]
that's right, you need to feed the Parser the font's glyph names so it can disambiguate real ones with a hyphen from glyph ranges. So it makes sense to warn if no glyphNames are passed.
