### ISSUE TITLE
pyftsubset fails to subset some fonts

### ISSUE THREAD

**Issue by hzineb** [fonttools/fonttools#2666]
Hello,
I use pyftsubset in order to subset ttf and otf fontes, but in 3 cases pyftsubset can't do subsetting and the catched exceptions tells the followings error message:

Case 1: SimSun18030.ttf
Exception type : TTLibError 
Exception message : specify a font number between 0 and 1 (inclusive)

Case 2: Batang.ttf
Exception type : AssertionError 
Exception message : ('Unsupported version 0x00001000', 'Version')

Case 3: timesi.ttf
Exception type : TTLibError 
Exception message : not enough 'glyf' table data

In order to reproduce the errors, you will find attached a folder holding the fonts to subset, the glyphs list to keep in the subset and a batch file to launch pyftsubset.
Let me know the problem with those cases.

NB: I use the version 44.33.3 of fonttools.
[Pyftsubset_TestCase.zip](https://github.com/fonttools/fonttools/files/8968598/Pyftsubset_TestCase.zip)

Regards

**Comment by justvanrossum** [comment]
- Case 1: this appears to be a TTC that is misnamed as .ttf
- Case 2: this font has a GSUB table Version field of `0x00001000`, which is not an existing version (probably a typo for `0x00010000`)
- Case 3: this font has a corrupt `glyf` or `loca` table

None of these cases are expected to be handled by pyftsubset.
