### ISSUE TITLE
Unstable gradient export with fontmake after fontools/ufo2ft update -

### ISSUE THREAD

**Issue by lenaweber404** [fonttools/fonttools#2686]
Hello everyone,
I've been experimenting with generating variable Colrv1 font files with fonttools for the last couple of weeks. 
The ultimate goal is to build a Colrv1 font with variable outlines as well as variable gradients - which I know not possible yet. 
So a goal for now is to build a Colrv1 font with gradients but variable outlines only.

With fonttools 4.33.3 and ufo2ft 2.27.0 i have been able to create working .ttfs with `fontmake myfile.glyphs -o variable`.
I have been following [this](https://github.com/SophiaDesign/Foldit/issues/2) thread.
I am new to GitHub issues/reporting, please redirect me in case this is the wrong way/place to post.

After the update to fonttools 4.34.0 and ufo2ft 2.28.0 I am not able to export variable and gradient displaying .ttfs. I use FontGoggles (1.4.1) and [https://fontgauntlet.com](url) to preview files (works for the correct export with fonttools 4.33.3 and ufo2ft 2.27.0)
In some cases they are displayed in a broken way however the export of something visible in the .ttf is inconsistent – to my understanding. Variability is not displayed.

Glyphs file for testing:
[amb_var_2.glyphs.zip](https://github.com/fonttools/fonttools/files/9076339/amb_var_2.glyphs.zip)

Export with old version:
![ambig var1](https://user-images.githubusercontent.com/45010446/178103529-f65b4512-36b8-4442-a2e3-c5ba2cb6eab7.gif)
Output File: 
[AMBIG-VF1.ttf.zip](https://github.com/fonttools/fonttools/files/9076347/AMBIG-VF1.ttf.zip)

Export with new version:
Output File (nothing visible) from attached .glyphs file: 
[AMBIG-VF.ttf.zip](https://github.com/fonttools/fonttools/files/9076349/AMBIG-VF.ttf.zip)

Output File (some gradients visible):
[AMBIG_PROP-VF.ttf.zip](https://github.com/fonttools/fonttools/files/9076352/AMBIG_PROP-VF.ttf.zip)
<img width="808" alt="Bildschirmfoto 2022-07-07 um 17 16 26" src="https://user-images.githubusercontent.com/45010446/178103163-4fcf9547-5969-403e-9f2a-cb36f5133034.png">

Does somebody have an idea where the issue could be?

**Comment by anthrotype** [comment]
> I am not able to export

You'll have to be a bit more specific than that, what error do you get, if any?

**Comment by lenaweber404** [comment]
> > I am not able to export
> 
> You'll have to be a bit more specific than that, what error do you get, if any?

no errors, the output is just different than expected

**Comment by anthrotype** [comment]
You said your font does not vary in the COLR table, only in the outlines, is that right? So you don't want a variable COLR table to be built at all. However your master may contain some differences in their respective COLR tables which trigger fonttools to build a variable COLR table from them, even if you didn't request one. But then the applications you were using to preview the font do not support displaying variable COLR table,l. FontGggles has been updated only yesterday with preliminary support for variable COLR, make sure you are using the latest one.

**Comment by anthrotype** [comment]
Another thing you can try to do is force to exclude the COLR table from the list of tables to be merged in the variable font. Fontmake doesn't expose an option for that so you'll have to use `fonttools varLib` command directly yourself, instead of through fontmake.
First you use fontmake to export -o ttf-interpolatable (instead of -o variable as usual), this will create a set of fonts and a designspace file inside the master_interpolatable_ttf directory. It's not yet the variable font.
Then you can call `fonttools varLib -x COLR master_interpolatable_ttf/NameOfYourFont.designspace` and it will build the VF next to it, without a variable COLR table because we explicitly excluded it.

**Comment by lenaweber404** [comment]
Thank you for your reply!
I'll try that. With the new fontGoggles version I was able to display the gradients. 
My font has multiple Axis, one of them also including variable COLR. 
So far I haven't been able to export variable outlines + variable gradient (multiple axis), but on their own (1 axis only) I was able to export variable Gradients for the first time just now! Thank you, very exiting!

**Comment by anthrotype** [comment]
Btw, that's a cool font 👍

**Comment by lenaweber404** [comment]
> Btw, that's a cool font 👍

Thank you :)
