### ISSUE TITLE
Potentially infinite loop while trying to fix GPOS offset overflow with HarfBuzz

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#2691]
At least it hasn't terminated in over an hour on the full sources I'm looking at. Cut the sources down for a repro but can't share publicly. Potentially related to #2668 (works fine in 4.33.3), @garretrieger see sources shared privately.

Make sure uharfbuzz is installed and run `fontmake -m asdf.designspace -o variable`

**Comment by garretrieger** [comment]
Looking into this.

**Comment by garretrieger** [comment]
Confirmed packing will succeed under the pure fonttools path. I'll figure out what's going wrong under hb.

**Comment by garretrieger** [comment]
Looks like this font ends up with a large number of table splits which requires hb repacker to do a bunch of space splits, but we run out of resolution rounds before the space splits are finished. Increasing the max # of rounds fixes the issue.

**Comment by garretrieger** [comment]
Potentially yes, we'll need to find an appropriate max rounds limit that should cover any realistic font. For now I've doubled the previous limit. The point of bounds is to prevent the repacker from getting stuck an infinite loop type scenario (like fonttools did in this case) since hb is generally used in performance sensitive use cases.

**Comment by garretrieger** [comment]
The rounds are similar in concept to the resolution attempts that fonttools does, except in harfbuzz we can typically apply multiple resolutions per round vs only a single one per fonttools iteration.

**Comment by garretrieger** [comment]
Another option, which I think I'll implement is have space splitting attempts not count against the rounds limit since space splitting is guaranteed to terminate eventually.

**Comment by garretrieger** [comment]
Better fix that will scale with bigger fonts: https://github.com/harfbuzz/harfbuzz/pull/3723

**Comment by madig** [comment]
Thanks. Is there some way to signal that HB ran out of rounds and packing should abort? Just to rule our infinite loops in general.

**Comment by garretrieger** [comment]
That shouldn't be necessary with my last commit which allows the space isolation to run as many rounds as it needs. That should allow the hb repacker to arrive at a working repacking whenever fonttools is able to arrive at one. The problem was that space isolation wasn't fully finishing which didn't allow extension lookups to be isolated when needed, which happens by default in fonttools.

**Comment by garretrieger** [comment]
Requested a new uharfbuzz release with the bugfix: https://github.com/harfbuzz/uharfbuzz/issues/127

**Comment by anthrotype** [comment]
I just cut a pre-release of uharfbuzz v0.27.0b1 that includes the upstream HB repacker fix that Garret pushed:

https://github.com/harfbuzz/uharfbuzz/releases/tag/v0.27.1b1
https://pypi.org/project/uharfbuzz/0.27.1b1/

@madig can you confirm it works with your private font project?

`pip install --upgrade --pre uharfbuzz` as usual

**Comment by roberto-arista** [comment]
I have the same issue even though I am using `uharfbuzz` 0.30.0

```
>>> import uharfbuzz
>>> uharfbuzz.__version__
'0.30.0'
>>> 
```

**Comment by garretrieger** [comment]
Should be solved by: https://github.com/fonttools/fonttools/commit/1b9731dd8c3a5477c5f46656155e5a30e6a916b4

**Comment by roberto-arista** [comment]
I installed `fontTools` directly from the repository and it works, thanks.
When do you think these changes will be included in a new release?

**Comment by anthrotype** [comment]
I should be able cut a new release as early as tomorrow, when I'm fully back from vacation
