### ISSUE TITLE
[feaLib.builder] Irrelevant "Must save GDEF when compiling a variable font" error when adding GSUB-only to VF

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2694]
feaLib.builder insists on building GDEF, even if GPOS is not requested, for example if I only want to add GSUB to a VF.

I think the `elif self.varstorebuilder:` line below should read `elif "GPOS" in tables and self.varstorebuilder:`

https://github.com/fonttools/fonttools/blob/4139d8914abe788cc396dcb6ccc7c9cdb365ee89/Lib/fontTools/feaLib/builder.py#L227-L234

See also https://github.com/fonttools/fonttools/discussions/2690#discussioncomment-3131706

**Comment by behdad** [comment]
Even then it's possible that the GPOS not have any variations...

**Comment by justvanrossum** [comment]
Maybe this would be more useful behavior:

```python
    gdef = self.buildGDEF():  # unconditionally
    if "GDEF" in tables:
        if gdef:
            self.font["GDEF"] = gdef
        elif "GDEF" in self.font: 
            del self.font["GDEF"]
    elif gdef:
        log.warning("GDEF is not requested, but is needed")
```

**Comment by anthrotype** [comment]
But why build if explicitly not requested?

**Comment by justvanrossum** [comment]
The idea of this test is to prevent mistakes of this form:
- use variable .fea for GPOS
- request GPOS, but not GDEF
- without GDEF the variable GPOS won't work, so should error (or at least warn)

The current test is too strict, and one way (the easiest way?) to find out whether GDEF is in fact needed (so we can error or warn if it is not requested) is to simply build it.

If there's a different way to do this that avoids a pointless error as well as addresses Behdad's concern, we can consider of course.

**Comment by anthrotype** [comment]
I see, ok.

Regarding your proposed change in https://github.com/fonttools/fonttools/issues/2694#issuecomment-1183534216, should you not check both `if gdef and self.varstorebuilder`, rather than just `elif gdef:`?

```python
    elif gdef and self.varstorebuilder:
        log.warning("GDEF is not requested, but is needed when compiling variable font")
```

**Comment by anthrotype** [comment]
actually nevermind ignore my last comment, your suggested code is correct already. Please send a PR, thanks!

**Comment by justvanrossum** [comment]
Ok, thanks!

**Comment by justvanrossum** [comment]
Reopening, as now there still can be a needless warning, via 

https://github.com/googlefonts/ufo2ft/blob/036cb54e44e7cbdd1889d83c5f1bf02dee51a842/Lib/ufo2ft/util.py#L230

I *think* it is possible that the featureFile in that call contains .fea code that would produce GDEF, but we're not interested in that at all there. So a warning about GDEF not being requested is out of place. Will try to come up with a fix.

**Comment by justvanrossum** [comment]
For your entertainment, the spurious warning caused this failure in the FontGoggles test suite: https://github.com/justvanrossum/fontgoggles/runs/7842927450?check_suite_focus=true
