### ISSUE TITLE
[designspace 5] Specific axis subsets needing to have a source isn't documented

### ISSUE THREAD

**Issue by benkiel** [fonttools/fonttools#2713]
From https://github.com/googlefonts/fontmake/issues/920: I'm not sure if this is a spec issue or a fontmake issue, but if the current fontmake behavior is expected, the documentation should state that if you have a specific value for an axis in a subset, it needs to have a corresponding source in the axis sources.

**Comment by belluzj** [comment]
In the other issue I replied just now to say it's an implementation issue. We could add to the documentation of the format that as of today, not having a source is not implemented, and point to the issue you've opened, to manage user expectations? But I think the spec is fine, what you're asking for makes sense. What do you think?

**Comment by benkiel** [comment]
Agree that nothing needs to change here, but maybe a note would be nice. I was sorely disappointed when I  couldn't just run a make and get the 20+ variable fonts I needed! I'll make a PR
