### ISSUE TITLE
Gracefully handle TrueType fonts that misuse `post` table format 1 ?

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#2736]
⚠️ **The attached font is broken** ⚠️ . It uses `post` table format 1 which [requires it to contain exactly the 258 glyphs in the standard Macintosh TrueType font file](https://docs.microsoft.com/en-us/typography/opentype/spec/post#version-10). This font has a lot more glyphs than that, and the first 258 are not ordered as expected by the spec.

Dumping the `hmtx` table with TTX fails with,
```
> ttx -t hmtx post_format_1.ttf
Dumping "post_format_1.ttf" to "post_format_1.ttx"...

ERROR: An exception occurred during the decompilation of the 'hmtx' table
Traceback (most recent call last):
  File "fontTools/ttLib/ttFont.py", line 420, in _readTable
    table.decompile(data, self)
  File "fontTools/ttLib/tables/_h_m_t_x.py", line 51, in decompile
    glyphName = glyphOrder[i]
IndexError: list index out of range
```

Other font tools I tried handle this font just fine.
Can FontTools be made to gracefully handle this broken font?

[post_format_1.ttf.zip](https://github.com/fonttools/fonttools/files/9303651/post_format_1.ttf.zip)

**Comment by justvanrossum** [comment]
Perhaps this code should compare the length of `glyphOrder` to `self['maxp'].numGlyphs`?

https://github.com/fonttools/fonttools/blob/2963fa503aadb2ef06dfbd5a2208d373c6813f9c/Lib/fontTools/ttLib/ttFont.py#L479-L480

If `glyphOrder` is too short, we could do two things:
- consider `glyphOrder` broken and fall back to `self._getGlyphNamesFromCmap()`
- extend `glyphOrder` with generic `glyph<gid>` names

**Comment by miguelsousa** [comment]
@justvanrossum Thanks for the guidance.
