### ISSUE TITLE
[instancer] _instantiateFeatureVariations() limitation when a range rule becomes applicable

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#2737]
With current logic, it's possible that, as a result of pinning one axis, a rule becomes default-applicable, but we do not apply it by default. That is wrong.

Let me take an example from the test suite's `InstantiateFeatureVariationsTest::test_partial_instance`, second test.  Imagine the font has these rules:
```
        font = makeFeatureVarsFont( 
            [ 
                ([{"wght": (0.20886, 1.0)}], {"uni0024": "uni0024.nostroke"}), 
                ([{"cntr": (0.75, 1.0)}], {"uni0041": "uni0061"}), 
                ( 
                    [{"wght": (-1.0, -0.45654), "cntr": (0, 0.25)}], 
                    {"uni0061": "uni0041"}, 
                ), 
            ] 
        ) 
```

Now if we pin `{"wght": -1.0}`, currently the test suite says no `appliedSub`, and the following `expectedRecords`:
```
                [ 
                    ({"cntr": (0, 0.25)}, {"uni0061": "uni0041"}), 
                    ({"cntr": (0.75, 1.0)}, {"uni0041": "uni0061"}), 
                ], 
```

However, this is wrong. Because now the rule `({"cntr": (0, 0.25)}, {"uni0061": "uni0041"})` is default-applicable because it starts at 0, so we should also copy its substitution into `appliedSub`.

But if we do that, the `appliedSub` will be applied to the entire space. So we then need to *disable* that at the end with a catch-all rule. That is:

```
                [ 
                    ({"cntr": (0, 0.25)}, {"uni0061": "uni0041"}), 
                    ({"cntr": (0.75, 1.0)}, {"uni0041": "uni0061"}), 
                    ({}, {}),
                ], 
```

Fixing this is hard but doable. I can do it but I prefer to do after merging the L4 branch.

**Comment by anthrotype** [comment]
I'm not sure I understand what you mean by "default-applicable because it starts at 0"..
We don't want to apply the substitution to the entire space, but only apply it when "cntr" is within 0 and 0.25.
It's not clear to me why we would need a catch-all rule at the end. E.g. if one selects an instance at cntr=0.5 (in the partial VF with only cntr, without wght), I would expect that since none of the ranges match, no substitution happens.

**Comment by behdad** [comment]
> I'm not sure I understand what you mean by "default-applicable because it starts at 0"..

Because the rule includes 0, it should apply by the default instance.

**Comment by anthrotype** [comment]
> it should apply by the default instance

hm so what? If one then selects a different location (e.g. cntr=0.5) I expect it to no longer trigger the rule. Is it not what's happening? I may be missing something right in the face.

**Comment by behdad** [comment]
> hm so what?

So it should become the default lookup!

**Comment by behdad** [comment]
> > hm so what?
> 
> So it should become the default lookup!

What I mean is that, most implementations do NOT process variation-specific tables at the default-instance (0) location. As such, if there's a condition that applies at 0, it won't be processed. So its substitutions *must* be promoted to be the default lookup. But since we don't want the default lookup to apply to the entire designspace, we need to undo its effect by adding a catch-all rule and no-substitutions.

**Comment by anthrotype** [comment]
> most implementations do NOT process variation-specific tables at the default-instance (0) location

I see.. that's the part I was missing...

**Comment by behdad** [comment]
I like to attack this one soon. Need to get in the zone.
