### ISSUE TITLE
[gvar] lazy loading

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#2740]
We're probably not going to fix this, but I noticed that unlike `glyf` table which loads individual glyphs lazily, `gvar` table loads all glyphs. So when creating eg. a glyphSet for a font, if the glyphset is variable (as in PR https://github.com/fonttools/fonttools/pull/2738) then there's significant delay loading the gvar table.

Ideally gvar should also lazily load per glyph variations like glyf table works.

**Comment by justvanrossum** [comment]
I've noticed that, too, and I think we _should_ fix it. At some point I tried to see how it could be done, and I vaguely remember seeing that it should be quite doable. I may have another look.
