### ISSUE TITLE
LGTM.com is shutting down

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#2749]
"LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead. Read more in [our blog post on the GitHub blog](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/)."

**Comment by anthrotype** [comment]
FWIW I never used it. Let's remove it and try out its replacement from github

**Comment by josh-hadley** [comment]
You've been using it (it is a non-blocking check that runs on every PR). The "replacement" is the same thing, just triggered by a GitHub Actions Workflow. They are transitioning repos actively using LGTM.com (as fonttools is), some time in October they will generate a PR that contains the Security Scan workflow that will also run on PRs (or I guess whatever other GH Actions triggers you want).

**Comment by behdad** [comment]
Okay then we just will wait for their PR or shutdown notice...

**Comment by anthrotype** [comment]
Thanks Josh, I know it's there, I meant I never looked at its report or waited for its status check to become green (it's also quite slow to complete). It may contain valid checks though, I'm fine to keep in its new form.

**Comment by josh-hadley** [comment]
I figured that's what you meant 😸  I'm hoping its new form might be streamlined in terms of runtime (we run it on AFDKO and psautohint repos and I agree it can be quite slow).
