### ISSUE TITLE
[ttx] cmap format 13 not merged correctly

### ISSUE THREAD

**Issue by ctrlcctrlv** [fonttools/fonttools#2752]
Cf. https://twitter.com/fr_brennan/status/1560057391684763649
Related commit https://github.com/MFEK/Mienai.ttf/commit/e1d99216b75274deaa58cea0ae610d07446c4f39

I fixed it by temporarily overwriting the `_IsInSameRun` function:

```python3
class cmap_format_13(cmap_format_12_or_13):

    _format_step = 0

    def __init__(self, format=13):
        cmap_format_12_or_13.__init__(self, format)

    def _computeGIDs(self, startingGlyph, numberOfGlyphs):
        return [startingGlyph] * numberOfGlyphs

    def _IsInSameRun(self, glyphID, lastGlyphID, charCode, lastCharCode):
        return (glyphID == lastGlyphID)
```

I don't know if this is the right fix in general, or just for Mienai. Please advise.

Thanks @kenlunde for his help.

**Comment by behdad** [comment]
That definitely doesn't look like the right fix.

**Comment by behdad** [comment]
How do you generate this font?

**Comment by ctrlcctrlv** [comment]
Just by running `ttx`.

**Comment by behdad** [comment]
If you want format13 to cover everything you need to list everything in ttx. That's inconvenient, I know.

That's why I coded mine in hex instead:
https://github.com/behdad/tofudetector/blob/master/tofu.ttx

**Comment by behdad** [comment]
> If you want format13 to cover everything you need to list everything in ttx. That's inconvenient, I know.

That is, you need to have all one million different entries in your ttx file.

**Comment by ctrlcctrlv** [comment]
@behdad Would you accept a PR that would add an element to be called `ConstantMapGroup` as per https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-13-many-to-one-range-mappings ?

**Comment by behdad** [comment]
I defer to @anthrotype. It would be a change of the ttx format. But I don't think many rely on the cmap format 13 subtable.

**Comment by ctrlcctrlv** [comment]
Okay. It's not a major change, and I'd support make it support both. :-)

**Comment by anthrotype** [comment]
feel free to propose a PR to support that -- but which doesn't break backward compat
