### ISSUE TITLE
[ttLib] Variable GlyphSet: odd behavior with components.

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2774]
If I draw a composite glyph multiple times, the diacritic component shifts. This doesn't happen at all locations.

This reproduces it nicely:

`python -m fontTools.pens.svgPathPen MutatorSans.ttf ÁÁÁ --variations wght=1000`

Test font: [MutatorSans.ttf.zip](https://github.com/fonttools/fonttools/files/9418680/MutatorSans.ttf.zip)

Screen grab of the resulting SVG:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/4246121/186500213-e946c2e6-aa22-4e97-9c83-93b6c42bb81d.png">

My suspicion is that something gets mutated that shouldn't get mutated.

**Comment by justvanrossum** [comment]
Replacing the `copy` with `deepcopy` here fixes it:
https://github.com/fonttools/fonttools/blob/2fcac63a74b45129869798ff7d286097983f57b3/Lib/fontTools/ttLib/ttGlyphSet.py#L214

@behdad would that be a reasonable fix, or is there a better/cheaper way to fix this?

**Comment by justvanrossum** [comment]
This also fixes it:
```python
		glyph = copy(glyf[self._glyphName]) # Shallow copy
		if glyph.isComposite():
			# Shallow copy components
			glyph.components = [copy(c) for c in glyph.components]
```

**Comment by behdad** [comment]
How about you move the copy to line 156?

**Comment by justvanrossum** [comment]
> How about you move the copy to line 156?

Perfect, thanks!
