### ISSUE TITLE
missing assignment?

### ISSUE THREAD

**Issue by schriftgestalt** [fonttools/fonttools#2777]
https://github.com/fonttools/fonttools/blob/d5a08b3b96f405b0fdca42e3f1f6baa32c59c687/Lib/fontTools/ttLib/tables/otBase.py#L965

Am in missing something or is this `CountReference(table, conv.repeat, value=countValue)` never assigned to anything?

**Comment by anthrotype** [comment]
it doesn't assign to a local variable, but the constructor has a side-effect of setting the count value (when not None) in the table (or if already set, asserts it's the same), see:

https://github.com/fonttools/fonttools/blob/d5a08b3b96f405b0fdca42e3f1f6baa32c59c687/Lib/fontTools/ttLib/tables/otBase.py#L766-L780

**Comment by anthrotype** [comment]
yeah, it looks confusing. It could be refactored to make it look clearer

**Comment by schriftgestalt** [comment]
Ok. But that is confusing. Relying on side effects sounds like a hack. Could we just set the table directly?

**Comment by anthrotype** [comment]
yes as long as the logic in CountReference.setValue is maintained:

https://github.com/fonttools/fonttools/blob/d5a08b3b96f405b0fdca42e3f1f6baa32c59c687/Lib/fontTools/ttLib/tables/otBase.py#L777-L780
