### ISSUE TITLE
fonttools doesn't take care of USE_MY_METRICS flag in glyf table

### ISSUE THREAD

**Issue by qxliu76** [fonttools/fonttools#2780]
Hi, according to the spec: `If set, this forces the aw and lsb (and rsb) for the composite to be equal to those from this component glyph. This works for hinted and unhinted glyphs.` 
However, I don't find any code in fonttools that honors this flag. Is this something that needs to be fixed?

Background: I was working on instancing glyf/hmtx tables in harfbuzz. When I compare the result between harfbuzz and fonttools, there're diffs for some composite glyphs in the hmtx table, but no diffs in the glyf table, I debugged into this and found that harfbuzz would copy component's phantom points if this flag is set, while fonttools doesn't do this. 
I'm not an expert but I feel harfbuzz is doing the right thing and fonttools isn't. So this might be an issue that needs to be fixed.

**Comment by qxliu76** [comment]
code in harfbuzz: https://github.com/harfbuzz/harfbuzz/blob/main/src/OT/glyf/Glyph.hh#L270

**Comment by behdad** [comment]
This happens during rasterization. So I'd argue that instancing should not copy these values. I might be wrong.

**Comment by qxliu76** [comment]
> This happens during rasterization. So I'd argue that instancing should not copy these values. I might be wrong.

so I should update code in harfbuzz to not consider this flag during instancing?

**Comment by behdad** [comment]
> > This happens during rasterization. So I'd argue that instancing should not copy these values. I might be wrong.
> 
> so I should update code in harfbuzz to not consider this flag during instancing?

I think so.

**Comment by qxliu76** [comment]
> > > This happens during rasterization. So I'd argue that instancing should not copy these values. I might be wrong.
> > 
> > 
> > so I should update code in harfbuzz to not consider this flag during instancing?
> 
> I think so.

thank you!
