### ISSUE TITLE
[COLRv1] Drop DeltaSetIndexMap when not needed

### ISSUE THREAD

**Issue by drott** [fonttools/fonttools#2800]
In an experimental font generated with:
https://github.com/drott/color-fonts/tree/noDeltaSetIndexMap
fontTools creates and empty DeltaSetIndexMap. 

```
    <VarIndexMap Format="0">
      <!-- Omitted values default to 0xFFFF/0xFFFF (no variations) -->
      <Map index="0" outer="0" inner="0"/>
    </VarIndexMap>
```

I suggest to drop this when not needed for saving space. 

I am in the process of fixing this part in [FreeType in this issue (#1178)](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1178).

PS: FF nightly seems to support those already.

**Comment by anthrotype** [comment]
unless, of course, the VarStore VarData items are interspersed with lots of zeros to replace those NO_VARIATION_DATA but I'm not actually sure that would produce a smaller COLR table in the end (as opposed to an optimized VarStore plus an indirect DeltaSetIndexMap)
