### ISSUE TITLE
Reading STAT table 

### ISSUE THREAD

**Issue by guidoferreyra** [fonttools/fonttools#2813]
Hi! Not sure if its correct to create an issue for a question. Is possible to read the STAT table of a font? 
Couldn’t find anything here https://fonttools.readthedocs.io/en/latest/ttLib/tables/S_T_A_T_.html

thanks in advance!

**Comment by Lorp** [comment]
What do you mean by *read*? Do you want to read it yourself, or do you want a program to parse it into a data structure for further processing?

Probably the simplest method of generating a human-readable representation of the STAT table is to use `ttx`. If you have installed fontTools correctly, then `ttx` will be available.

```
ttx -t STAT <font.ttf>
```

**Comment by guidoferreyra** [comment]
Apologies for the lack of detail. The latter, parse it into a data structure for processing it after.

**Comment by Lorp** [comment]
I’m not very familiar with fontTools code, but the `instantiateSTAT()` function probably does what you want, given a varfont and a set of axis limits:

https://github.com/fonttools/fonttools/blob/1f8803af961aa4800e0542f87c7caf52c525b41d/Lib/fontTools/varLib/instancer/__init__.py#L1002

**Comment by guidoferreyra** [comment]
This is exactly what I needed, thank you for point me in the right direction

```
stat = ttFont['STAT'].table

for axis in stat.DesignAxisRecord.Axis:
    print (axis)

for axisRecord in stat.AxisValueArray.AxisValue:
    print (axisRecord)
```
