### ISSUE TITLE
Calling instantiateVariableFont can lead to negative advance widths in hmtx

### ISSUE THREAD

**Issue by liZe** [fonttools/fonttools#2821]
Hi!

Calling `instantiateVariableFont` can introduce negative advance widths in the `hmtx` table:

https://github.com/fonttools/fonttools/blob/796c1f13303f0af515166e95bff1191f8d4e7f16/Lib/fontTools/varLib/mutator.py#L121-L149

We could probably replace line 146 by `entry[0] = max(0, entry[0] + width_delta)`. I can open a PR if you want.

(Carefully crafted fonts shouldn’t trigger this problem, but I’ve got it using a subset font where advance of unused glyphes has been set to 0.)

**Comment by anthrotype** [comment]
I think the varLib.instancer already takes care of that, can you use that instead of mutator? It's supposed to be a replacement of the latter, which we want to deprecate at some point.

**Comment by anthrotype** [comment]
We can backport the fix to mutator as well, I can take a look tomorrow

**Comment by liZe** [comment]
> I think the varLib.instancer already takes care of that, can you use that instead of mutator?

I can’t, because I get `Instancing CFF2 variable fonts is not supported yet` (as you explained in #2681 😁️).
