### ISSUE TITLE
[instancer] STAT: ElidedFallbackNameID is removed from 'name' table

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2822]
When creating a static instance from a VF that has an `ElidedFallbackNameID` in the `STAT` table, the name record referred to by `ElidedFallbackNameID` is deleted, but the field is not cleared.

I'm not sure what the fix should be:
1. don't delete the `name` table entry
2. clear the `ElidedFallbackNameID` field

**Comment by anthrotype** [comment]
who deletes that name table entry? I can't find the code that's responsible for that

**Comment by justvanrossum** [comment]
Good question, I'll try to find out.

**Comment by anthrotype** [comment]
I'm not entirely sure what the fix should be either. What are the implications of 1) or 2)

**Comment by justvanrossum** [comment]
Hm, I don't think that's the culprit.

I'm investigating further, there's something odd going on in our VF, where nameID 2 == "Regular", yet "ElidedFallbackNameID" is 382, and nameID 382 is *also* "Regular". But nameID 2 only exists as (3, 1), and 382 was added as (1, 0) and (3, 1). It's 382 that gets zapped somehow.

**Comment by anthrotype** [comment]
Oh! I think it's the pruningUnusedNames context manager defined in instancer.names module, which wraps calls to instantiateSTAT. The method calls getVariationNameIDs (also defined in instancer.names module) but for STAT table it does _not_ also considers that ElidedFallbackNameID can "use" a name ID. So it assumes it's unused and later it will be dropped on exit.

**Comment by anthrotype** [comment]
assuming we want to retain that ElidedFallbackNameID, then you should add it to the set of used nameIDs as returned from getVariationNameIDs.
Do we want to retain that? When does it make sense to drop it?

**Comment by anthrotype** [comment]
in any case, the pruningUnunsedNames logic should be amended to take into account that the ElidedFallbackNameID may in fact be still used and not drop it accordingly. The instantiateSTAT method can decide when is appropriate to unset that ElidedFallbackNameID

**Comment by justvanrossum** [comment]
I'm working on a fix in `getVariationNameIDs`, I just need to check whether `stat.ElidedFallbackNameID` is None or missing in version 1.0 STAT tables.

**Comment by anthrotype** [comment]
probably just missing
