### ISSUE TITLE
[varLib.cff] Suboptimal packing of deltas, or flaw in CFF2?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2838]
With a CFF2 VF built from the attached designspace project (modified from MutatorSans), the `S` rendered at `wdth=1000`, `wght=595` has a bump on the right hand side, even though its corresponding source does not:

![letter_S](https://user-images.githubusercontent.com/4246121/193420150-b9315322-f0c0-4b7f-8c0c-d2ecf056c1cd.svg)

The bump is at the start/end point of the contour.

The design space has five sources, one on each corner, and a support master between Light Wide and Bold Wide.

    Light    Medium   Bold
    Wide     Wide     Wide
    o--------o--------o
    |                 |
    |                 |
    |                 |
    |                 |
    |                 |
    |                 |
    O-----------------o
    Light             Bold
    Condensed         Condensed
    (neutral)

The _Medium Wide_ source is at the location shown (`wdth=1000`, `wght=595`)

What I _think_ happens is:

- The delta for that location is relative to the interpolation between _Light Wide_ and _Bold Wide_
- This interpolation has fractional coordinates
- The delta's are calculated for _relative_ coordinates (the differences between one point and the next), rounded to integers
- Leading to an accumulation of rounding errors
- To the extent that the final point is no longer coinciding with the starting point.
- (The difference between start and end point is ≈3 units horizontally, and ≈1.5 units vertically.)

On the one hand, in theory the varLib CFF2 packer could do a better job, but looking at the code this seems far from trivial. On the other hand this shows that CFF2 has pretty terrible properties for cases like this.

[mutator_sans_S.zip](https://github.com/fonttools/fonttools/files/9690800/mutator_sans_S.zip)

**Comment by justvanrossum** [comment]
Btw. props to @behdad for the wonderful main prog in `svgPathPen.py`:
```
python -m fontTools.pens.svgPathPen MutatorSans-VF.otf S --variations "wght=595 wdth=1000" > letter_S.svg
```

**Comment by behdad** [comment]
This fixes it:
```diff
diff --git a/Lib/fontTools/varLib/cff.py b/Lib/fontTools/varLib/cff.py
index b2fb51f1..2dac5123 100644
--- a/Lib/fontTools/varLib/cff.py
+++ b/Lib/fontTools/varLib/cff.py
@@ -502,7 +502,7 @@ class CFF2CharStringMergePen(T2CharStringPen):
        """
        def __init__(
                                self, default_commands, glyphName, num_masters, master_idx,
-                               roundTolerance=0.5):
+                               roundTolerance=0.1):
                super().__init__(
                                                        width=None,
                                                        glyphSet=None, CFF2=True,
```

**Comment by justvanrossum** [comment]
The CFF2 table size goes from 624 bytes to 858 bytes with this change.

(`glyf` + `gvar` don't have this same problem despite not supporting floating-point numbers.)

**Comment by behdad** [comment]
A smarter encoder can work around this by accumulating the error while rounding. That's hard to implement. Let me think about it.

**Comment by justvanrossum** [comment]
That would be very cool, but I'm currently in a "CFF2 is bad, please give me cubics in glyf" kind of mood :)

**Comment by Lorp** [comment]
One thing I realized only when rewriting the CFF2 spec is that, if a Postscript-style outline ends with a curve, the start point is effectively specified twice. With statics this doesn’t matter but with variable, if the start point is moved, the “extra start point” needs to be moved too! Otherwise extra little straight line segments will appear. I wonder if the CFF2 compiler takes this into account.

**Comment by justvanrossum** [comment]
> if the start point is moved, the “extra start point” needs to be moved too

It does move, but because of the accumulated error over all relative coordinates + deltas, the end point doesn't always move the exact same distance as the start point. Which is what we're seeing here.

**Comment by behdad** [comment]
@justvanrossum what do you suggest we do here? I suggest we make the change, ie. prefer correctness over size.

**Comment by justvanrossum** [comment]
Maybe yeah. I'm not having a good view of possible unintended side-effects, though.

**Comment by behdad** [comment]
> possible unintended side-effects

Is only size.

**Comment by behdad** [comment]
Non-integer CFF was tested in the field in 2015:
https://blog.typekit.com/2015/10/01/smoother-curves-with-decimal-coordinate-values/

**Comment by justvanrossum** [comment]
Cool, let's go for it then!

**Comment by khaledhosny** [comment]
I just fixed a bug with fractional CFF coordinates in LibreOffice subsetter the other day, which suggests they work fine elsewhere.
