### ISSUE TITLE
variationModel.interpolateFromMasters doesn't extrapolate as expected

### ISSUE THREAD

**Issue by LettError** [fonttools/fonttools#2843]
With `extrapolate=True` there is an issue with`variationModel.interpolateFromMasters` as it clips results in 2 value models. Results are as expected in 3 value models. 

```python
from fontTools.varLib.models import VariationModel

# extrapolate under and over a 3 value system
locations = [
    dict(wght=-1),
    dict(wght=0),
    dict(wght=1),    
]

values = [30, 40, 50]

m = VariationModel(locations, extrapolate=True)
assert m.interpolateFromMasters(dict(wght=-1.5), values) == 25
assert m.interpolateFromMasters(dict(wght=-1), values) == 30
assert m.interpolateFromMasters(dict(wght=0), values) == 40
assert m.interpolateFromMasters(dict(wght=0.5), values) == 45
assert m.interpolateFromMasters(dict(wght=1), values) == 50
assert m.interpolateFromMasters(dict(wght=1.5), values) == 55


# extrapolate under and over a 2 value system
locations = [
    dict(wght=0),
    dict(wght=1),    
]

values = [40, 50]

m = VariationModel(locations, extrapolate=True)

# values under 0 are clipped.
print(m.interpolateFromMasters(dict(wght=-1), values))
print(m.interpolateFromMasters(dict(wght=-2), values))
print(m.interpolateFromMasters(dict(wght=-3), values))

#> 40.0
#> 40.0
#> 40.0

# this one fails
#assert m.interpolateFromMasters(dict(wght=-1), values) == 30

# the rest works as expected
assert m.interpolateFromMasters(dict(wght=0), values) == 40
assert m.interpolateFromMasters(dict(wght=0.5), values) == 45
assert m.interpolateFromMasters(dict(wght=1), values) == 50
assert m.interpolateFromMasters(dict(wght=1.5), values) == 55
```

**Comment by anthrotype** [comment]
at least it appears to be intentional e.g. see the docstring of VariationModel (emphasis mine)

https://github.com/fonttools/fonttools/commit/5284ac3c588fd329729ed29d0270e1c394b53d27

> If the extrapolate argument is set to True, then location values are
    interpretted [sic] in the normalized space, ie. in the [-1,+1] range, and
    values are extrapolated _outside this range_.

I'm sure @behdad can clarify that.

**Comment by behdad** [comment]
What @anthrotype said. Current extrapolation implementation extrapolations the values at -1 and +1.

**Comment by LettError** [comment]
Would it be possible to express the hope it would eventually also work for values between [0,1]?

**Comment by behdad** [comment]
I have to check the code. I think it's possible, yes. In that case it wouldn't need any specific range and would adapt to the min/max specified.

**Comment by LettError** [comment]
True. In MutatorMath that was a bit of work ([lines starting here](https://github.com/LettError/MutatorMath/blob/f7a7d7b0ea4a380ff164e2c303f96734ede245fd/Lib/mutatorMath/objects/mutator.py#L304) ). This is too specific and can't be re-used for varlib. But I imagine it will be similar enough: a couple of different cases that need to be calculated separately.
