### ISSUE TITLE
[designspaceLib] "ordering" attribute on labels missing in documentation

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#2848]
https://github.com/fonttools/fonttools/blob/main/Doc/source/designspaceLib/xml.rst#labels-element-axis

I think the "ordering" attribute is missing here.

It is evaluated in the code.

```py
            labelElement = axisElement.find(".labels")
            if labelElement is not None:
                if "ordering" in labelElement.attrib:
                    axisObject.axisOrdering = int(labelElement.attrib["ordering"])
```

**Comment by belluzj** [comment]
Yes indeed, it's also in the tests here, so it's just the documentation missing it: https://github.com/fonttools/fonttools/blob/main/Tests/designspaceLib/data/test_v5.designspace#L33

**Comment by belluzj** [comment]
@jenskutilek There's [a PR for this addition to the docs](https://github.com/fonttools/fonttools/pull/2854), and you can preview the result here: https://fonttools--2854.org.readthedocs.build/en/2854/designspaceLib/xml.html#labels-element-axis

**Comment by jenskutilek** [comment]
LGTM, thank you!
