### ISSUE TITLE
Error for cmap in saving a subset font: "OverflowError: unsigned short is greater than maximum"

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#2868]
I have [a script that makes a "trial font"](https://gist.github.com/arrowtype/db9562858a56ab45010e390c3f788b84#file-make-trial-ttf-font-py) by subsetting a font, then assigning cut-out unicodes to a single glyph.

This has worked well for me many times, but I am currently confused by an error that is triggered when I try to save a modified font in the script:

```
Traceback (most recent call last):
  File "/Users/stephennixon/project/build/helpers/make-trial-font.py", line 234, in <module>
    main()
  File "/Users/stephennixon/project/build/helpers/make-trial-font.py", line 209, in main
    tempFont.save(tempFontPath.replace(f".temporary.{filetype}",f".{nameSuffix}.{filetype}"))
  File "/Users/stephennixon/project/venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 185, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/stephennixon/project/venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 225, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/stephennixon/project/venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/stephennixon/project/venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 680, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/stephennixon/project/venv/lib/python3.10/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 184, in compile
    chunk = table.compile(ttFont)
  File "/Users/stephennixon/project/venv/lib/python3.10/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 911, in compile
    charCodeArray = array.array("H", endCode + [0] + startCode)
OverflowError: unsigned short is greater than maximum
```

Other issues suggest that the fix might be something like setting the format of the post table, but this seems to be a problem relating to the cmap table. (Also, setting a format 3 post table doesn’t seem to make a difference, in my initial attempts.)

The cmap table in the current font is version 4, similar to other fonts I’ve successfully run this script on.

Is there anything else I might try to get past this?

Thanks so much for any advice!

**Comment by anthrotype** [comment]
cmap format 4 is the character mapping subtable

>  for fonts that support only Unicode Basic Multilingual Plane characters (U+0000 to U+FFFF).

https://learn.microsoft.com/en-us/typography/opentype/spec/cmap#format-4-segment-mapping-to-delta-values

I think you want to use format 12 if your codepoints > 0xFFFF

**Comment by justvanrossum** [comment]
If you indeed have code points > 0xFFFF, using format 12 should be the solution.

That said, I seem to recall cases where the packing algorithm breaks down for (very) big fonts and lots of unicode ranges not running parallel to gid ranges. Creating a glyph order that has more in common with the character order would help in such cases (ie. building a glyph order based on code points where possible). Perhaps the algorithm also breaks down in your case, where you map many (arbitrary?) code points to the same glyph.

Encoding format 4 cmap is rather non-trivial, and I see that most of the code that does it is still my original code from > 20 years ago. I wouldn't be surprised if there were subtle bugs in it.

Unless you indeed use code points > 0xFFFF, I wouldn't mind having a look at your font.

**Comment by arrowtype** [comment]
Thanks so much for the quick and thoughtful responses!

The input font does have glyphs such as “🅒” (U+1F152) which have code points > 0xFFFF, and the input font does have a cmap with format 12.

Also, yes, the script is trying to assign unicodes such as U+1F152 to a single glyph. The order may be somewhat arbitrary, though I could try sorting by codepoint and trying this again, if that might be a potential workaround.

What I’ve tried so far:
- Trying to set format 12 in my script doesn’t make a difference for the output... maybe pyftsubset is setting this back to 4, because it subsets the font back to a simple glyph set, before I try to map extra unicodes into the cmap table.
- Adjusting my script to not remove the higher codepoint glyphs seems to dodge the issue, but that misses part of the script’s goal of limiting the included character set while assigning cut-out unicodes to a replacer glyph.

I suppose an alternative workaround might be to really refactor the script in a way that avoids subsetting any glyphs, and instead overwrites glyph data with new outlines... though, an earlier attempt at this showed that it had more complexity than expected.

I would be happy to share this font & current script via email, if that would be welcome!

**Comment by arrowtype** [comment]
Yes, I’ve confirmed more fully that the script works well to remove/obfuscate anything that doesn’t have code points > 0xFFFF. So, basically it works well, but leaves in the letters circled in black. This isn’t terrible, but it would be amazing to get it fully working to handle those, as well.

**Comment by anthrotype** [comment]
> the input font does have a cmap with format 12.

I think you should then simply _not_ set non-BMP (>0xFFFF) codepoints in format-4 cmap, but only do that for format 12:


this loop here from your script:

```python
            for table in tempFont['cmap'].tables: 
                for c in unicodesToHide:
                    table.cmap[c] = args.replacer
```

if your `c` codepoint is > 0xFFFF check the table.format and only set if format is 12

**Comment by behdad** [comment]
> if your `c` codepoint is > 0xFFFF check the table.format and only set if format is 12

But also need to make sure there's a format 12 table, since the subsetter is dropping it in this case.

**Comment by arrowtype** [comment]
Thanks!

Okay, so if I leave out pyftsubset, I can manipulate the format 12 cmap table successfully, and save it successfully.

```py
    for table in tempFont['cmap'].tables: 
        for c in unicodesToHide:
            if c < 0xFFFF:
                table.cmap[c] = args.replacer
            else:
                if table.format == 12:
                    table.cmap[c] = args.replacer
```

@behdad sorry if this is a basic question, but is there a way to prevent pyftsubset from dropping cmap format 12?

I’ve separately tried args `--legacy-cmap`, `--no-subset-tables+='cmap'`, `--no-subset-tables+=CMAP`, and `--passthrough-tables`, but it keeps cutting out the format 12 subtable.

**Comment by anthrotype** [comment]
how about you subset it after you have manipulated the cmap subtables? the subsetter would then no longer drop the format 12 ones, since they will no longer be identical to the respective format 4 ones

**Comment by behdad** [comment]
> @behdad sorry if this is a basic question, but is there a way to prevent pyftsubset from dropping cmap format 12?

Not currently. If you want to hack the fontTools code to get your code working I can tell you which lines to change.

**Comment by behdad** [comment]
> how about you subset it after you have manipulated the cmap subtables? the subsetter would then no longer drop the format 12 ones, since they will no longer be identical to the respective format 4 ones

This would be my advice also.

**Comment by arrowtype** [comment]
Good point! I did actually try that as well, but it is still dropping the format 12 table.

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/45946693/198749263-91e7ff2c-bca1-498b-b29d-6411f05ebdd7.png">

Though, that is strange, because it leaves the table if I don’t subset the glyphs like 🅒. So, maybe there’s something I am missing...

**Comment by arrowtype** [comment]
Ah, this is reminding me why I placed the subsetter first, originally: if I place the subsetter after the cmap manipulation, it removes all the cmap entries that point unicodes to the asterisk, because I am trying to remove those glyphs and unicodes, and then add them, pointing to the replacer glyph.

So, I almost have to subset the font, then add in a format 12 cmap, then point those glyphs to the replacer glyph.

**Comment by anthrotype** [comment]
it looks like you are passing subset.main() the old `fontPath` not the modified one, you need to save it back to disk if you want to call subset.main

**Comment by anthrotype** [comment]
i think you need to tell the subsetter that you want to keep _all_ the unicodes, it will automatically figure out that some glyphs are unreachable and prune those

**Comment by arrowtype** [comment]
Ahhh, brilliant!!  Those two tips got me there, after a little bit of adjustment. Thank you so much for your insights on this! I don’t think I would have ever thought to "keep all the unicodes" in the subsetting step.

The code is a little ugly, but I think these multiple temporary fonts are helpful, because I’m calling a subprocess... (should I be calling the subsetter as a python module, somehow, and feeding in the TTFont?)

I’ll work with this code a little further, and update the GitHub Gist once I am confident things are working as expected.

```py

            # # -------------------------------------------------------------------------------------------------
            # # then, add many additional unicodes to the replacer glyph to cover all diacritics, etc

            ttfont.save(tempFontPath0)
            tempFont = TTFont(tempFontPath0)

            for table in tempFont['cmap'].tables: 
                for c in unicodesToHide:
                    if c < 0xFFFF:
                        table.cmap[c] = args.replacer
                    else:
                        if table.format == 12:
                            table.cmap[c] = args.replacer

            # save a temporary font to run through the subsetter
            tempFontPath1 = tempFontPath0.replace("temporary0.","temporary1.")
            tempFont.save(tempFontPath1)

            # set up temporary font for the remaining process
            tempFontPath2 = tempFontPath1.replace("temporary1.","temporary2.")

            # Subset input font. Keep specified unicodes only. Keep all font name IDs. Keep glyph names as-is. Keep notdef from font. Output to temporary path.
            # We have already remapped unicodes to our replacer glyph, so we keep use --unicodes=* here, and the subsetter trims everything that is unreachable
            # Note: you may wish to remove '--layout-features=*' from this list to limit opentype features.
            subset.main([tempFontPath1, f'--unicodes=*', "--name-IDs=*", "--glyph-names", '--notdef-outline', f'--output-file={tempFontPath2}'])
            
            # open new temporary font
            tempFont2 = TTFont(tempFontPath2)
```

Cheers, and have a great weekend!

**Comment by anthrotype** [comment]
glad it worked

> should I be calling the subsetter as a python module, somehow, and feeding in the TTFont?

up to you; in that case at the very least you'd need to create an subset.Options() passing in as keyword arguments all the options you want, then instantiate a subset.Subsetter(options), call populate method with the set of unicodes or glyphs to keep, and finally call its subset(font) method which will modify the TTFont instance in-place. Something like this

```
    from fontTools import subset
    options = subset.Options(glyph_names=True, name_IDs=["*"], notdef_outline=True)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=["*"])
    subsetter.subset(font)
    font.save(output_file)
```

**Comment by justvanrossum** [comment]
Alternatively you could rebuild the cmap from scratch. FontBuilder.setupCharacterMap() makes this fairly trivial, and will add the right subtables depending on the character set. Something like:

```python
from fontTools.fontBuilder import FontBuilder

newCmap = {....}  # code points => glyph names
fb = FontBuilder(font=<a-TTFont-instance>)
fb.setupCharacterMap(newCmap)
fb.save(<new-file-name>)
```

**Comment by arrowtype** [comment]
Amazing, thank you so much to both of you for teaching me a few very valuable things in this thread!

**Comment by arrowtype** [comment]
I am happy for this issue to be closed, if there is no further action you’d like to take on it!
