### ISSUE TITLE
[varLib Instancer] Adjust usWeightClass and names

### ISSUE THREAD

**Issue by guidoferreyra** [fonttools/fonttools#2885]
When instantiating a variable font and the default axes values has has been moved, should the instancer adjust usWeightClass and nameID 1 and 6?

**Comment by anthrotype** [comment]
I think we already do that, have you used --update-name-table option?

**Comment by guidoferreyra** [comment]
You are right! I neglected about `updateFontNames` 🤦 

So only usWeightClass doesn’t get up updated

**Comment by anthrotype** [comment]
> So only usWeightClass doesn’t get up updated

that should also be supported, see

https://github.com/fonttools/fonttools/blob/12bf60aee01e65a1fef2d74814abb7259cfc974d/Lib/fontTools/varLib/instancer/__init__.py#L1170

**Comment by guidoferreyra** [comment]
So I will double check my code because it didn’t worked for me. Thanks!

**Comment by anthrotype** [comment]
how are you calling the instancer? Are you creating a static instance (with all axes fully instantiated) or a new VF with axis defaults changed?

**Comment by anthrotype** [comment]
ah I think I see the problem now.. We only use `axisLimits.pinnedLocation()` when setting default OS/2 weight/width (so we only update those if wght/wdth are pinned), whereas we should also consider the modified axis defaults when the axes are retained. I'll fix that, thanks!
