### ISSUE TITLE
[ttLib] scale-upem should not scale vsindex

### ISSUE THREAD

**Issue by punchcutter** [fonttools/fonttools#2893]
Same as https://github.com/fonttools/fonttools/issues/2840#issuecomment-1267434947
and not a bad font. In `visit` all ops are sent to `_cff_scale`, but `vsindex` should be skipped. Otherwise we scale the index and get `index out of range`. If I skip scaling `vsindex` here I don't get an error...

```
            for op, args in commands:
                if op == 'vsindex':
                    continue
                _cff_scale(visitor, args)

```

**Comment by anthrotype** [comment]
want to send a PR?

**Comment by punchcutter** [comment]
Ok, I tried to edit and make a PR with the iOS app for the first time. I think it worked.

**Comment by anthrotype** [comment]
can you think of any other operators that don't need scaling in addition to vsindex?

**Comment by punchcutter** [comment]
I feel like there's probably something, but this is the one that was blocking use of the scale script so we couldn't even test it at all.

**Comment by behdad** [comment]
> can you think of any other operators that don't need scaling in addition to vsindex?

I can't think of any others. There's hintmask which is not represented as a number.

**Comment by behdad** [comment]
> > can you think of any other operators that don't need scaling in addition to vsindex?
> 
> I can't think of any others. There's hintmask which is not represented as a number.

And these are desubroutinized, so there's no subroutine numbers. And we don't support arithmetic or boolean operations.

**Comment by khaledhosny** [comment]
Some arithmetic operators are supported, I’m pretty sure at least div is supported.

**Comment by behdad** [comment]
> Some arithmetic operators are supported, I’m pretty sure at least div is supported.

Yeah I just checked and you are right. I'm surprised that one is supported. I don't understand why.  It goes back to 1999 apparently.

**Comment by khaledhosny** [comment]
Some Type 1 and CFF fonts use it to encode fractional numbers, CFF does not need this but I think it was carried over from Type 1 fonts.
