### ISSUE TITLE
ReadTheDocs builds fail with "could not find remote ref"

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#2929]
E.g. in this PR https://github.com/fonttools/fonttools/pull/2928  (unrelated to docs) the ReadTheDocs checks fails with the following: https://readthedocs.org/projects/fonttools/builds/18905856/

I have no idea what's going on, anybody knows? /cc @chrissimpkins @madig

**Comment by chrissimpkins** [comment]
I signed in to my RTD account and see this message:

"The project fonttools doesn't have a valid webhook set up, commits won't trigger new builds for this project. See [the project integrations](https://readthedocs.org/dashboard/fonttools/integrations/) for more information."

Looking into it.

**Comment by chrissimpkins** [comment]
@anthrotype I receive an error that I don't have sufficient permissions to resync the webhook.  It looks like you also have admin access on the RTD build.  Mind using this link to see if you are able to resync?

https://readthedocs.org/dashboard/fonttools/integrations/

**Comment by anthrotype** [comment]
ok thanks Chris. I went to that link and clicked Resync Webhook button. What now?

**Comment by chrissimpkins** [comment]
I confirmed that a manually triggered build through the RTD UI functions without issues.  There is no problem with the git clone or build completion on that end.  It seemed to indicate that the webhook was the issue.  If it is resync'd, I think that we can test with a new commit push to main to see if it builds it.

**Comment by anthrotype** [comment]
it's seems like it's working now, closing for now, thanks Chris!
