### ISSUE TITLE
feaLib: order of features referenced by aalt

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#2935]
According to the [FEA spec](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#8a-the-all-alternates-feature-aalt),

> The aalt feature block must appear before the feature block of any <feature tag> it references in the above manner. 
> It will also always be created as the first feature in the font (i.e. its lookups will be at the beginning of the GSUB LookupList).

However It appears that feaLib does not enforce this constraint, and [includes test cases](https://github.com/fonttools/fonttools/blob/main/Tests/feaLib/data/aalt_chain_contextual_subst.fea) where referenced features appear before the aalt feature block.

I assume that this is by design, but I'm curious if anyone has any additional information about this choice?

**Comment by behdad** [comment]
I doubt anyone remembers. @brawer

**Comment by khaledhosny** [comment]
It sounds one of those arbitrary restrictions that are essentially makeotf implementation details leaking to the soec.

**Comment by cmyr** [comment]
But is there a good reason to arbitrarily relax the spec? This feels bad to me, even if the spec contains some arbitrary constraints...

**Comment by anthrotype** [comment]
regarding the test case @cmyr referenced, which I added in https://github.com/fonttools/fonttools/pull/1878/files, I don't think it is deliberately testing that an aalt feature block appearing _after_ the feature blocks it references continues to work; it is testing for a different bug about retrieving alternate glyphs when aalt-referenced features use chaining contextual substitutions.
In any case, you'll see that in the generated GSUB, the `aalt` feature is still compiled as the first feature record and its lookup is at index=0, so we are still abiding by the second part of the FEA spec snippet you quoted above, no matter where aalt block appears in the feature file (whether before or after the features it references).
I don't see any benefit to enforcing aalt to appear before any referenced features besides consistency with makeotf.. That can be desirable but on the other hand it does look to me like an arbitrary implementation detail as Khaled noted.
So I'm inclined to close as WONTFIX

**Comment by cmyr** [comment]
The main argument I would make for respecting the spec as written is just that deviating from it leads to a proliferation of FEA that will not be compiled correctly by makeotf. I do agree that the constraint is likely just a case of the spec enshrining the particular behaviour of makeotf, and that this is not a great way to write a spec.

In any case, I am happy to follow fonttools and handle this correctly regardless of order.

**Comment by khaledhosny** [comment]
Our position on makeotf comparability: if it compiles under makeotf it should compile under feaLib, but not vice versa.
