### ISSUE TITLE
feaLib: handling of duplicate lookup references

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#2946]
Given the following FEA:

```fea
languagesystem DFLT dflt;
languagesystem latn dflt;

feature test {
    lookup alt1 {
	sub a by A;
    } alt1;
    lookup alt2 {
        sub b by B;
    } alt2;


    script latn;
    lookup alt1;

} test;
```

because `latn dflt` is one of the declared language systems, it inherits the two lookups that are declared at the top of the feature. The reference to `lookup alt1` under `latn` is redundant.

Currently, feaLib adds an extra lookup for this feature, even though it occurs earlier in the feature list. `makeotf` ignores the duplicate lookup, and the `latn/dflt` feature includes the two lookups inherited from `DFLT/dflt`.

I think that feaLib is incorrect here, although I'm not sure if this results in just slightly larger files, slightly less efficient shaping, or possibly errors in shaping?

(this test case is a reduction of an issue I found in about a hundred sources used by google fonts, so it may be worth some attention)

**Comment by khaledhosny** [comment]
The extra lookup is probably harmless since it is the same feature so each lookup will be applied only once, at least HarfBuzz seems to apply each lookup only once:
```
$ hb-shape -V c.otf ab --features=+test
trace: start table GSUB	buffer: [a=0|b=1]
trace: start lookup 0 feature 'test'	buffer: [a=0|b=1]
trace: replacing glyph at 0 (single substitution)	buffer: [a=0|b=1]
trace: replaced glyph at 0 (single substitution)	buffer: [A=0|b=1]
trace: end lookup 0 feature 'test'	buffer: [A=0|b=1]
trace: start lookup 1 feature 'test'	buffer: [A=0|b=1]
trace: replacing glyph at 1 (single substitution)	buffer: [A=0|b=1]
trace: replaced glyph at 1 (single substitution)	buffer: [A=0|B=1]
trace: end lookup 1 feature 'test'	buffer: [A=0|B=1]
trace: end table GSUB	buffer: [A=0|B=1]
trace: start fallback mark	buffer: [A=0+525|B=1+525]
trace: end fallback mark	buffer: [A=0+525|B=1+525]
[A=0+525|B=1+525]
```

**Comment by cmyr** [comment]
Sorry, I should've updated this issue: on closer look, the opentype layout algorithm (as [summarized in the FEA spec](https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#7a-an-opentype-layout-engines-layout-algorithm)) says,

> 3. Assemble all lookups in these features, in LookupList order, removing any duplicates. (All features and thus all lookups needn't be applied to every glyph in the run.)

So I agree that this isn't a correctness issue, just a bit of extra work for the shaper.
