### ISSUE TITLE
[feaLib] ignore statements without marked glyphs

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#2949]
Another instance where it feels like there is a discrepancy between the spec and feaLib's behaviour.

Per the spec ([5.f.ii. Specifying exceptions to the Chain Sub rule](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#5fii-specifying-exceptions-to-the-chain-sub-rule)):

>The backtrack and lookahead sequences may be omitted, but there must be at least one marked glyph or glyph class.

However the [GSUB_5_formats.fea](https://github.com/fonttools/fonttools/blob/main/Tests/feaLib/data/GSUB_5_formats.fea) test case consists of `ignore sub` statements that do not have any marked glyphs or glyphclasses.

My understanding is that in the absence of any marked glyphs, feaLib chooses to interpret all glyphs/classes as belonging to the input sequence.

So: Is this intentional? If so, is there any particular rationale?

cc @simoncozens, who added this particular test case.

**Comment by cmyr** [comment]
Interesting; you're correct, given the input,

```fea
feature cool {
    ignore sub e x;
} cool;
```

makeotf produces a type-6 lookup where 'e' is the input sequence and 'x' is lookahead. feaLib, on the otherhand, produces a type-6 lookup where both 'e' and 'x' are part of the input sequence.

I'm not really sure what to think about this? I suppose for my purposes it makes more sense to copy the feaLib behaviour, *if it is intentional*, but I think I would also print a warning indicating that this syntax is ambiguous.


also for further fun: if I change the above to,

```fea
feature cool {
    ignore sub e x;
    sub y e' by f;
} cool;
```

then the ignore statement gets promoted to type 6, but then the second statement seems to get added to the same subtable, which is probably a bug? the ttx looks like,

```xml
<LookupList>
      <!-- LookupCount=2 -->
      <Lookup index="0">
        <LookupType value="6"/>
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <ChainContextSubst index="0" Format="1">
          <Coverage>
            <Glyph value="e"/>
          </Coverage>
          <!-- ChainSubRuleSetCount=1 -->
          <ChainSubRuleSet index="0">
            <!-- ChainSubRuleCount=2 -->
            <ChainSubRule index="0">
              <!-- BacktrackGlyphCount=0 -->
              <!-- InputGlyphCount=2 -->
              <Input index="0" value="x"/>
              <!-- LookAheadGlyphCount=0 -->
              <!-- SubstCount=0 -->
            </ChainSubRule>
            <ChainSubRule index="1">
              <!-- BacktrackGlyphCount=1 -->
              <Backtrack index="0" value="y"/>
              <!-- InputGlyphCount=1 -->
              <!-- LookAheadGlyphCount=0 -->
              <!-- SubstCount=1 -->
              <SubstLookupRecord index="0">
                <SequenceIndex value="0"/>
                <LookupListIndex value="1"/>
              </SubstLookupRecord>
            </ChainSubRule>
          </ChainSubRuleSet>
        </ChainContextSubst>
      </Lookup>
      <Lookup index="1">
        <LookupType value="1"/>
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <SingleSubst index="0">
          <Substitution in="e" out="f"/>
        </SingleSubst>
      </Lookup>
    </LookupList>
```

**Comment by khaledhosny** [comment]
In this particular case, I think you are better off following the spec and erroring here. On feaLib side, we need to figure out if feaLib was always not following makeotf here or one if the two changed its behavior and act accordingly.

**Comment by khaledhosny** [comment]
> but then the second statement seems to get added to the same subtable, which is probably a bug?

Does it matter from the shaping engine prescriptive whether it is one subtable or two? I’d assume it gives the same output regardless.

**Comment by cmyr** [comment]
I *think* it does in the case of ignore statements: an ignore statement works by inserting a subtable that matches the input, but has no associated lookups. When evaluating the lookup, the shaping engine stops at the first matching subtable.

**Comment by khaledhosny** [comment]
I test fonts produced by feaLib and makeotf and HarfBuzz gives me the same output:
```fea
feature rlig {
    ignore sub e x;
    sub y e' by f;
} rlig;
```

$ hb-shape a1.ttf "ye yex yea" --no-clusters --no-positions
[y|f|space|y|e|x|space|y|f|a]
$ hb-shape a2.ttf "ye yex yea" --no-clusters --no-positions
[y|f|space|y|e|x|space|y|f|a]

**Comment by khaledhosny** [comment]
https://github.com/fonttools/fonttools/pull/2950

**Comment by cmyr** [comment]
So I remain really confused by that example I posted, it really doesn't seem to compile how I expect and I have a nagging suspicion that it is producing the correct result accidentally, although I don't trust my intuition very much here. I'm going to look at it with a fresh brain tomorrow, and will open a separate issue if I identify a possible problem.
