### ISSUE TITLE
feaLib: rsub class length mismatch

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#2951]
I'm not really sure how to think about this, but I thought I would at least open an issue and see if anyone else has some insight.

Given the following FEA:

```fea
feature test {
    rsub a b [c d]' e by Q;
} test;
```

fontmake produces a lookup that replaces both c and d by Q, and makeotf errors, saying that:

> Target glyph class in rule doesn't have the same number of elements as the replacement class; the target has 2, the replacement, 1

This doesn't really feel like a bug exactly, it's just not clear if this behaviour is intentional or desirable.

**Comment by khaledhosny** [comment]
It looks like a desirable behavior and probably intentional. I think makeotf is just being inconsistent since the same syntax works for `sub`.

**Comment by cmyr** [comment]
Works for me.
