### ISSUE TITLE
pyftsubset on COLRv1 font gives unexpected results

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#2965]
I'm trying to isolate the "foreground_color" glyphs shown on https://roettsch.es/var_colrv1.html

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/4570664/214676694-3fc4ec3b-9c61-4f42-8995-d7cbeb48124f.png">

Downloading the font used on that page, and using pyftsubset:

```
pyftsubset --verbose --unicodes="U+F0B00U+F0B01U+F0B02U+F0B03U+F0B04U+F0B05U+F0B06U+F0B07" test_glyphs-glyf_colr_1_variable.ttf
```

Then using the font in my own test page:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/4570664/214677544-03e29bcb-d163-4fbe-a202-3683e503282a.png">

It looks like a `ClipList` has wrong values, except for the first glyph (0xf0b00). The first glyph has the same ClipBox as in the original font, the other 7 get a different ClipBox applied.

**Comment by anthrotype** [comment]
Hey Roel, thanks for the report!
I cannot seem to reproduce the issue on my end. I downloaded the font and run the same pyftsubset command as yours, then made two test page for the original and subsetted font (you'll find them attached below).

[test_glyphs-glyf_colr_1_variable.zip](https://github.com/fonttools/fonttools/files/10508840/test_glyphs-glyf_colr_1_variable.zip)

When I load the pages (e.g. running a local http server with `python -m http.server 8081`) in either Chrome (both latest stable and canary) or Firefox both fonts display correctly.

Can you check the font you made is the same as the one I made?
What fonttools and browser version are you testing with?

**Comment by RoelN** [comment]
Hey Cosimo,

I'm on TTX 4.38.0, currently the newest when installed via Homebrew. I haven't tried a local build of FontTools yet. But I guess there's a difference in those versions, as my subsetted version from the original ttf in your zip differs from your subsetted version:

```diff
diff --git a/differ.ttx b/differ.ttx
index d8f6188..c1b1c58 100644
--- a/differ.ttx
+++ b/differ.ttx
@@ -18,7 +18,7 @@
     <!-- Most of this table will be recalculated by the compiler -->
     <tableVersion value="1.0"/>
     <fontRevision value="1.0"/>
-    <checkSumAdjustment value="0x6c7b2c40"/>
+    <checkSumAdjustment value="0xfa84d3c0"/>
     <magicNumber value="0x5f0f3cf5"/>
     <flags value="00000000 00000001"/>
     <unitsPerEm value="1000"/>
@@ -638,17 +638,79 @@
     <ClipList Format="1">
       <Clip>
         <Glyph value="uF0B00"/>
+        <ClipBox Format="1">
+          <xMin value="100"/>
+          <yMin value="250"/>
+          <xMax value="900"/>
+          <yMax value="950"/>
+        </ClipBox>
+      </Clip>
+      <Clip>
         <Glyph value="uF0B01"/>
+        <ClipBox Format="2">
+          <xMin value="0"/>
+          <yMin value="500"/>
+          <xMax value="500"/>
+          <yMax value="1000"/>
+          <VarIndexBase value="68"/>
+        </ClipBox>
+      </Clip>
+      <Clip>
         <Glyph value="uF0B02"/>
+        <ClipBox Format="2">
+          <xMin value="0"/>
+          <yMin value="0"/>
+          <xMax value="500"/>
+          <yMax value="500"/>
+          <VarIndexBase value="68"/>
+        </ClipBox>
+      </Clip>
+      <Clip>
         <Glyph value="uF0B03"/>
+        <ClipBox Format="2">
+          <xMin value="500"/>
+          <yMin value="0"/>
+          <xMax value="1000"/>
+          <yMax value="500"/>
+          <VarIndexBase value="68"/>
+        </ClipBox>
+      </Clip>
+      <Clip>
         <Glyph value="uF0B04"/>
+        <ClipBox Format="2">
+          <xMin value="500"/>
+          <yMin value="500"/>
+          <xMax value="1000"/>
+          <yMax value="1000"/>
+          <VarIndexBase value="68"/>
+        </ClipBox>
+      </Clip>
+      <Clip>
         <Glyph value="uF0B05"/>
+        <ClipBox Format="2">
+          <xMin value="250"/>
+          <yMin value="250"/>
+          <xMax value="750"/>
+          <yMax value="750"/>
+          <VarIndexBase value="68"/>
+        </ClipBox>
+      </Clip>
+      <Clip>
         <Glyph value="uF0B06"/>
+        <ClipBox Format="2">
+          <xMin value="100"/>
+          <yMin value="100"/>
+          <xMax value="900"/>
+          <yMax value="900"/>
+          <VarIndexBase value="72"/>
+        </ClipBox>
+      </Clip>
+      <Clip>
         <Glyph value="uF0B07"/>
         <ClipBox Format="1">
           <xMin value="100"/>
           <yMin value="250"/>
-          <xMax value="900"/>
+          <xMax value="1200"/>
           <yMax value="950"/>
         </ClipBox>
       </Clip>
```

So it doesn't look like a browser issue, but maybe something that is changed in the latest version of ttx/FontTools?

**Comment by anthrotype** [comment]
very strange, I'll take a look..
are we at least sure we are using the same input font before subsetting?
I got mine from https://roettsch.es/test_glyphs-glyf_colr_1_variable.ttf

**Comment by RoelN** [comment]
Yes, that's the font I use as well. And to verify I tried it with the `test_glyphs-glyf_colr_1_variable.ttf` from your zip file too. But both the same result.

For completeness sake, my pyftsubset output:

```
$ pyftsubset --verbose --unicodes="U+F0B00U+F0B01U+F0B02U+F0B03U+F0B04U+F0B05U+F0B06U+F0B07" test_glyphs-glyf_colr_1_variable.ttf
Text: ''
Unicodes: [985856, 985857, 985858, 985859, 985860, 985861, 985862, 985863]
Glyphs: []
Gids: []
maxp pruned
cmap pruned
post pruned
gvar pruned
name pruned
glyf pruned
Added gid0 to subset
Closing glyph list over 'COLR': 9 glyphs before
Glyph names: ['.notdef', 'uF0B00', 'uF0B01', 'uF0B02', 'uF0B03', 'uF0B04', 'uF0B05', 'uF0B06', 'uF0B07']
Glyph IDs:   [0, 146, 147, 148, 149, 150, 151, 152, 153]
Closed glyph list over 'COLR': 9 glyphs after
Glyph names: ['.notdef', 'uF0B00', 'uF0B01', 'uF0B02', 'uF0B03', 'uF0B04', 'uF0B05', 'uF0B06', 'uF0B07']
Glyph IDs:   [0, 146, 147, 148, 149, 150, 151, 152, 153]
Closing glyph list over 'glyf': 9 glyphs before
Glyph names: ['.notdef', 'uF0B00', 'uF0B01', 'uF0B02', 'uF0B03', 'uF0B04', 'uF0B05', 'uF0B06', 'uF0B07']
Glyph IDs:   [0, 146, 147, 148, 149, 150, 151, 152, 153]
Closed glyph list over 'glyf': 9 glyphs after
Glyph names: ['.notdef', 'uF0B00', 'uF0B01', 'uF0B02', 'uF0B03', 'uF0B04', 'uF0B05', 'uF0B06', 'uF0B07']
Glyph IDs:   [0, 146, 147, 148, 149, 150, 151, 152, 153]
Retaining 9 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
cmap subsetted
loca subsetting not needed
post subsetted
COLR subsetted
CPAL subsetting not needed
HVAR subsetted
STAT subsetting not needed
fvar subsetting not needed
gvar subsetted
name subsetting not needed
glyf subsetted
head pruned
glyf pruned
CPAL pruned
Input font:  72184 bytes: test_glyphs-glyf_colr_1_variable.ttf
Subset font:  29900 bytes: test_glyphs-glyf_colr_1_variable.subset.ttf
```

**Comment by anthrotype** [comment]
ok I managed to reproduce by installing fonttools==4.38.0 inside a clean venv, I'll keep you updated as I find out

**Comment by anthrotype** [comment]
now this is very weird. I am getting different results, but _not_ between HEAD and 4.38.0 as originally reported, but _between python3.10 and python3.11_ where each one is using the same editable installation of local fonttools checkout (be it at HEAD or at the latest tagged commit doesn't make a difference within each minor python version)...

I don't undestand what's going on but it's something to do with loading the font in lazy mode. In fact @RoelN I suggest you try to pass the `--no-lazy` option to pyftsubset (which forces to load the font non lazily all at once). That seems to work around the bug and produces same, correct results for both python 3.10 and 3.11.

I will continue to investigate.

**Comment by behdad** [comment]
Now this is a bug!

**Comment by anthrotype** [comment]
@RoelN this will be fixed in the next release, for now keep doing --no-lazy. Thanks again for filing the bug!

**Comment by RoelN** [comment]
Great! Thank you for the quick fix!
