### ISSUE TITLE
Discrepancy in applying `xMin-lsb` shift to components or not

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#2981]
Full details in thread starting at:
https://github.com/fonttools/fonttools/pull/2958#discussion_r1096152415

- HarfBuzz, FreeType, and Windows, and FontTools `_g_l_y_f.Glyph.getCoordinates` do NOT apply shift to component glyphs.
- Mac, and FontTools `DecomposingPen` apply.

**Comment by anthrotype** [comment]
should we keep this open? Or we're just happy to live with the inconsistency between DecomposingPen and ttGlyphSet as regards xMin-lsb?

**Comment by behdad** [comment]
> should we keep this open? Or we're just happy to live with the inconsistency between DecomposingPen and ttGlyphSet as regards xMin-lsb?

I fixed the discrepancy in the VarComposite patchset. We now follow the Windows/FreeType/HarfBuzz convention

**Comment by anthrotype** [comment]
what about your https://github.com/fonttools/fonttools/pull/2958#discussion_r1096187751

> The implications for FontTools is that DecomposingPen cannot work as it does, and the Composite decomposing should also be moved to ttGlyphSet

**Comment by behdad** [comment]
> what about your [#2958 (comment)](https://github.com/fonttools/fonttools/pull/2958#discussion_r1096187751)
> 
> > The implications for FontTools is that DecomposingPen cannot work as it does, and the Composite decomposing should also be moved to ttGlyphSet

I cheated and made `ttGlyphSet` keep a `depth` state and if depth is not zero, not apply the offset.

**Comment by anthrotype** [comment]
oh ok, I somehow was under the impression this would only apply for varcomposites, but I see it works for both regular composites and var ones. Sgtm

**Comment by anthrotype** [comment]
I wonder if we should bring this to the attention of https://github.com/MicrosoftDocs/typography-issues/ and make this behavior explicit in the OT spec.

**Comment by justvanrossum** [comment]
For variable fonts this has been taken care of [in the head table](https://learn.microsoft.com/en-us/typography/opentype/spec/head):

> Note that, in a variable font with TrueType outlines, the left side bearing for each glyph must equal xMin, and bit 1 in the flags field must be set.
