### ISSUE TITLE
[`basePen`] `decomposeSuperBezierSegment()`

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#2989]
Looks like the argument to segment pen's `curveTo` is a "super-Bezier", and is decomposed by `BasePen` via `decomposeSuperBezierSegment()`.

I have a hard time finding any references to the definition of this super-Bezier curve type. Moreover, it's not clear to me if anyone is using this.

This came up as I'm trying to add cubics to the glyf table, and it would be convenient if the cubic Bezier splines can use the same implied-oncurve-point optimization as the quadratic splines. That is, a `decomposeBezierSegment` that would insert midpoint oncurves between offcurves 2-3, 4-5, ...

https://github.com/fonttools/fonttools/pull/2988

WDYT? @justvanrossum @anthrotype

**Comment by justvanrossum** [comment]
I don't think that anyone uses it, but I don't know.

It's something that I came up with when trying to use cubics in a TTF-style on-curve/off-curve sequence of points. It makes nice connected cubics with good continuity, but I don't have the science to prove it. Also: it lacks a version for a "blob" (no on-curve points).

It's probably fine if cubic-glyf-1 requires 2-off-curve-points always, although it would be nice to define what a renderer should do if it encounters the wrong number. Fontra's current behavior:

- if there's only one off-curve point: fall back to quad
- if there's more than two off-curve points: use the first and the last off-curve point, ignore the rest

https://github.com/googlefonts/fontra/blob/20f243e9ae0fb9ed03d33fd78aedb87aca2ca45f/src/fontra/client/core/var-path.js#L649-L663

But then again, if you think the "super bezier" concept is usable/sellable, I'm all for it, and I'll happily add support for it in Fontra, too.

**Comment by justvanrossum** [comment]
Ha, RoboFont has some support for super beziers. This glyph:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<glyph name="a" format="2">
  <advance width="500"/>
  <unicode hex="0061"/>
  <outline>
    <contour>
      <point x="261" y="84" type="curve" smooth="yes"/>
      <point x="321" y="84"/>
      <point x="331" y="136"/>
      <point x="370" y="147"/>
      <point x="370" y="225" type="curve" smooth="yes"/>
      <point x="370" y="302"/>
      <point x="321" y="365"/>
      <point x="261" y="365" type="curve" smooth="yes"/>
      <point x="201" y="365"/>
      <point x="152" y="302"/>
      <point x="152" y="225" type="curve" smooth="yes"/>
      <point x="152" y="147"/>
      <point x="201" y="84"/>
    </contour>
  </outline>
</glyph>
```

Is rendered like this:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/4246121/217483975-1d93caa2-a2db-488b-91a0-a928e59eef2f.png">

**Comment by justvanrossum** [comment]
Besides fitting the TTF on/off model, the idea was that super beziers would be a convenient way to draw curve segments with more freedom than a single cubic segment, without the added cost of splitting the segment into two cubics. Just add one point, and the continuity at the (implied) connection comes for free.

**Comment by anthrotype** [comment]
there's this online NURBS editor you can play with http://nurbscalculator.in/, make sure to select the type of the curve to 
"B-Spline" instead of the default "NURBS", so the control weights are all 1 and can't be modified; and also select clamp at start/end checkboxes so the knot vector is adjusted accordingly.

**Comment by behdad** [comment]
> TrueType-style curves with implied mid on-curves can similarly be understood as a 2nd degree (quadratic) non-rational, uniform B-spline.

But in the case of the TT-style one there's no "uniform spacing" happening. Am I missing something?

**Comment by behdad** [comment]
At any rate, I don't think we want this for the glyf table. Is too complicated and not useful for most cases. I do want to allow the implied-on-curve optimization. So far my model is that the cubic off-curve points should come in even numbers at a time or glyph is malformed.

If `basePen`'s behavior cannot be changed that's fine. I'll change my patch to decompose things differently.

**Comment by behdad** [comment]
It does mean that the pointPen cannot retain the points of a cubic glyf exactly though.

**Comment by anthrotype** [comment]
> But in the case of the TT-style one there's no "uniform spacing" happening

yes the internal knots in the middle of the knot vector are uniformly spaced at even intervals between 0 and 1, only the endpoint knots (first and last 3 knots) are set respectively to 0.0 and 1.0. The length of the B-spline knot vector is len(control points) + degree + 1; for quadratic curves (be them Bezier or b-spline) we need at least 3 control points (degree + 1); so for a TT-style quadratic B-spline there are _at least_ 6 knots in the simplest case where there's only one off-curve point in addition to the start and end on-curve point (this simple b-spline _is_ an atomic quadratic bezier). As you add more off-curve points in between, you add one knot for each additional off-curve point, while also making sure that they are evenly spaced (this is to uphold the invariant whereby implied on-curve points are exactly in the middle between two consecutive off-curves).

E.g.

- knots for quad bezier-like curve with 3 control points (1 off-curve): [0, 0, 0, 1, 1, 1]
- knots for quad b-spline with 4 control points (2 off-curves): [0, 0, 0, 0.5, 1, 1, 1]
- knots for quad b-spline with 5 control points (3 off-curves): [0, 0, 0, 1/3, 2/3, 1, 1, 1]
- etc.

**Comment by anthrotype** [comment]
> Is too complicated and not useful for most cases

I may agree on the 'too complicated' (or rather less familiar) but disagree on the not useful. And if we allow quad b-splines already I don't see why we should not allow cubic b-splines..

**Comment by behdad** [comment]
> not useful

Designers don't design in it. What I like to add instead is implied *on-curve* point, which is something designers do use.

**Comment by anthrotype** [comment]
> implied on-curve point

yes, that's exactly what I also mean..

**Comment by anthrotype** [comment]
in the case of cubic b-splines, when the number of control points is even (a multiple of 2, e.g. 2, 4, 6, etc.), then the effect of the B-spline math I hinted at above is to produce this "implied on-curve point in the middle of two consecutive off-curve points".. When it's odd, like the picture of the oval that Just posted above, the effect is less intuitive perhaps but it follows the same b-spline math

**Comment by behdad** [comment]
> in the case of cubic b-splines, when the number of control points is even (a multiple of 2, e.g. 2, 4, 6, etc.), then the effect of the B-spline math I hinted at above is to produce this "implied on-curve point in the middle of two consecutive off-curve points"..

The nurbs calculator you linked to shows otherwise:
![image](https://user-images.githubusercontent.com/142891/217617601-cb1638ee-d91e-4424-ac1a-e83f1310c485.png)

**Comment by anthrotype** [comment]
to be honest, I have limited knowledge of b-splines, I've only played with them many years ago while I read this book by G. Farin's [Curves and Surfaces in CAGD](https://www.amazon.co.uk/Curves-Surfaces-CAGD-Practical-Kaufmann/dp/1558607374). I may have to read it again..

**Comment by anthrotype** [comment]
you need to adjust the knot vector values to make them evenly spaced, that editor doesn't do it for you

**Comment by anthrotype** [comment]
ah the internal knots also need to be repeated twice...

<img width="446" alt="Screenshot 2023-02-08 at 18 27 04" src="https://user-images.githubusercontent.com/6939968/217619490-f51adab9-46a8-4e6a-ad3d-d1274f64512b.png">

<img width="358" alt="Screenshot 2023-02-08 at 18 27 15" src="https://user-images.githubusercontent.com/6939968/217619509-3da35a6f-6444-49f9-9235-625da2e5ea3f.png">

**Comment by justvanrossum** [comment]
> What I like to add instead is implied on-curve point, which is something designers do use 

But only in the context of quads, and it is not a very common or poular way of editing curves.

I don't think implied on-curve points make much sense for cubics. They do for quads, because without them they're impossible to work with, and very inefficient to store.

No design tool that I know supports implied on-curve points for cubics.

> So far my model is that the cubic off-curve points should come in even numbers at a time or glyph is malformed

If we're going to impose restrictions, we might as well require "exactly two off-curve points" between on-curves for cubics.

**Comment by behdad** [comment]
@justvanrossum Does your decomposeSuperBezierSegment do what Cosimo describes? If you add four offCurve cubic points in RoboFont, how does it look?

**Comment by anthrotype** [comment]
I believe so, but I don't have RF at hand to test

**Comment by behdad** [comment]
> > What I like to add instead is implied on-curve point, which is something designers do use
> 
> But only in the context of quads, and it is not a very common or poular way of editing curves.
> 
> I don't think implied on-curve points make much sense for cubics. They do for quads, because without them they're impossible to work with, and very inefficient to store.

I was thinking as an optimization pass. Most smooth curves have the on-curve point at mid-point of the side off-curve points. No?

**Comment by anthrotype** [comment]
even if no design tool currently supports it, it doesn't mean that it shouldn't be possible for an optimizing compiler to get rid of on-curve points if they can be inferred to save up bytes..

**Comment by justvanrossum** [comment]
> I was thinking as an optimization pass. Most smooth curves have the on-curve point at mid-point of the side off-curve points. No?

I don't think that's very common actually, with hand-drawn cubics.

**Comment by justvanrossum** [comment]
If it's an optimization step, then we don't need pen support for it, no?

**Comment by behdad** [comment]
> > If it's an optimization step, then we don't need pen support for it, no?
> 
> The pen support comes when replaying a glyf to the pen.

As I said, I can decompose it myself into separate oneCurveTo calls. The only downside is that it wouldn't retain the exact points. That's not a big deal maybe.

**Comment by behdad** [comment]
*If* the SuperBezier indeed does what Cosimo describes, then I like it, as it solves the issue of what to do with odd number of off-curves. It just complicates drawing of the outline as one cannot just pump out curveTo's as the points come in.

**Comment by anthrotype** [comment]
FWIW here's how the odd-number cubic b-spline looks in the nurbs editor, I tried to draw it similarly to the one Just posted early on:

<img width="309" alt="Screenshot 2023-02-08 at 18 41 16" src="https://user-images.githubusercontent.com/6939968/217622420-c04ad246-b888-47b1-8167-4513198092bb.png">

**Comment by justvanrossum** [comment]
Red: super bezier points
Blue: decomposed cubic points

<img width="742" alt="image" src="https://user-images.githubusercontent.com/4246121/217623598-27b5db7f-7eca-47f1-81e5-2fe9c7ba36e8.png">

Messy drawbot script:
[super_bezier_play.py.zip](https://github.com/fonttools/fonttools/files/10688925/super_bezier_play.py.zip)

**Comment by justvanrossum** [comment]
> I wonder how the "jvr" author of the commit from 20 years go derived the decomposeSuperBezierSegment function, 

- ▓▓▓▓▓▓▓▓▓▓▓░ [43 votes] whether only from geometric intuition
- ▓░░░░░░░░░░░ [3 votes] or based on the NURBS literature..

**Comment by behdad** [comment]
![image](https://user-images.githubusercontent.com/142891/217627009-0c3a9e90-447b-46c5-b208-61c64614b098.png)

**Comment by anthrotype** [comment]
lol

ok, now I remember, the process of converting b-spline to a series of bezier curves is called "knot insertion" or Bohem's algorithm. If I only I can find that old piece of code my previous self wrote for that..

**Comment by behdad** [comment]
> > I was thinking as an optimization pass. Most smooth curves have the on-curve point at mid-point of the side off-curve points. No?
> 
> I don't think that's very common actually, with hand-drawn cubics.

I measured this for `NotoSansArabic-MM`.  ~12% of the on-curve points matched and can be elided.  That translates to maybe 3% total font size optimization. Given that I saw only 10% savings from adding cubics at all, that extra 3% is not too bad...

**Comment by anthrotype** [comment]
ok so, yes Just was right, the decomposeSuperBezierSegment does _not_ directly produce the implied mid-point on-curve every successive pair of off-curve points which @behdad proposed in https://github.com/harfbuzz/boring-expansion-spec/blob/main/glyf1-cubicOutlines.md.

However, it accomplishes the very same task and with _less_ control points, so it produces more savings than just omitting one mid-on-curve point every 2 successive cubics.
Note that the super-bezier describes _exactly_ the same set of atomic cubic beziers with less control points, and can easily split be back as needed.
( I believe the exact terminology to describe these pairs of consecutive bezier curves where the on-curve point joining them is midway between the last off-curve of the first and the first off-curve of the second, is "parametric" C1 continuity, which is established when the tangent vector (1st derivative) at the end of the first curve is the same as at the start of the following one, i.e. they have the same direction _and_ magnitude - as opposed to G1 geometric continuity when the tangent vectors are parallel but have different magnitude. )

E.g. 2 successive cubics normally take up 7 control points (1 + degree * 2 = 7); if these are C1 continuous, and we omit the mid-oncurve, we have 6 points; but if we encode the same two curves using a "super-bezier", we only need 5 points, thus we save 2 points.

<img width="567" alt="Screenshot 2023-02-09 at 10 40 56" src="https://user-images.githubusercontent.com/6939968/217789960-6d5e04c4-2e38-4b0b-be7a-8898e5a1d9a1.png">

For 3 successive C1-continuous cubics, we go from 10 initial control points down to 8 if we only omit the mid-on-curve point, or 6 for a super-bezier, thus 4 points saved; For 4 cubics, we save 6 points, and so on...

So in general, for a series of `n` C1-continuous beziers, with the implied mid-oncurve method we save `n - 1` control points; with a "super-bezier" equivalent representation, we save twice as many control points, i.e. `(n - 1) * 2`.

I think it's worth considering this as a further optimized encoding when the source outline contains pairs of successive cubics that are C1 continuous. Instead of simply omitting the on-curve point in the middle, we compute the control points of the super-bezier spline that describes this sequence of beziers. Basically the reverse of decomposeSuperBezierSegment. Then wen drawing or rendering these contours, when there's only 2 off curve points, we treat the segment as a regular atomic cubic bezier curve; if there's more than 2 off-curves, we decompose it using decomposeSuperBezierSegment.

How about that?

**Comment by behdad** [comment]
> How about that?

I'm open to considering it. Two issues with it:
1. Complicates the drawing, but it does resolve the issues of what to do with odd number of off-curve points,
2. Needs a rather complicated optimizer.

**Comment by anthrotype** [comment]
> Needs a rather complicated optimizer.

**Comment by anthrotype** [comment]
> Needs a rather complicated optimizer.

Isn't it the same or equivalent to optimizer that only removes one implied on-curve point if two consecutive cubics are C1 continous? Only that in the super-bezier case, instead of removing one point for each pair of cubics, we remove 3 points and add 1 (net gain 2).

**Comment by behdad** [comment]
> > Needs a rather complicated optimizer.
> 
> Isn't it the same or equivalent to optimizer that only removes one implied on-curve point if two consecutive cubics are C1 continous? Only that in the super-bezier case, instead of removing one point for each pair of cubics, we remove 3 points and add 1 (net gain 2).

Sure if you say so. :)

Still concerned about the draw side. But we can experiment with it. We need fonts built with it first.

**Comment by anthrotype** [comment]
Presumably the fonts sources will not (for the foreseable future, i.e. unless we change them) contain odd number of off-curves for cubics. So when compiling them to binary, and we find two or more cubics with opposing offcurves at equal distance from the joining on-curve (C1 continous), we upgrade them to a super-bezier

**Comment by anthrotype** [comment]
> Sure if you say so. :)

I haven't actually reversed the decomposeSuperBezierSegment yet but it seems feasible

**Comment by behdad** [comment]
> Presumably the fonts sources will not (for the foreseable future, i.e. unless we change them) contain odd number of off-curves for cubics.

Pen protocol currently says cubics should have exactly two off-curve points.

**Comment by behdad** [comment]
> you mean, UFO glif spec says cubics should have exactly two off curve points. The FontTools BasePen allow more than 2 off-curve points (aka "super-bezier")

Correct.

**Comment by anthrotype** [comment]
> Having to do this super-bezier brings in conversion error again

I don't think there's any conversion error, besides floating point math sort of errors, it's just a few multiplications

**Comment by anthrotype** [comment]
it's reversible, I mean

**Comment by anthrotype** [comment]
(now I have to prove it 😅 )

**Comment by behdad** [comment]
> > Having to do this super-bezier brings in conversion error again
> 
> I don't think there's any conversion error, besides floating point math sort of errors, it's just a few multiplications

Rounding to int coordinates.

**Comment by anthrotype** [comment]
oh, by .5 you mean rounding to int...

**Comment by anthrotype** [comment]
shoot, I had not considered that. Yeah the "there's no conversion error" argument won't hold any more. Maybe it's not worth it after all. Or we can make some experiments and measure if any gains are worth it.

**Comment by behdad** [comment]
> Or we can make some experiments and measure if any gains are worth it.

Given how the curves need to align, my guess is that we won't find it worth it at all.

**Comment by anthrotype** [comment]
how did you measure the gains for the implied on-curve removal? because my understanding so far is, whenever we can remove 1 on curve point, we can _always_ remove 3 control points and add one "super" offcurve point, leading to twice the savings as the simple method

**Comment by behdad** [comment]
> Isn't it the same or equivalent to optimizer that only removes one implied on-curve point if two consecutive cubics are C1 continous?

My understanding is that that's not enough condition.

**Comment by anthrotype** [comment]
what is not enough? And enough to do what?
C1 continous means the tangent vectors have same direction ("smooth" transition) and same magnitude as well, so the two offcurves are at equal distance relative to the middle on-curve which can thus be omitted

**Comment by behdad** [comment]
> how did you measure the gains for the implied on-curve removal?

```
diff --git a/Lib/fontTools/pens/ttGlyphPen.py b/Lib/fontTools/pens/ttGlyphPen.py
index 3374ebcda..dc3638067 100644
--- a/Lib/fontTools/pens/ttGlyphPen.py
+++ b/Lib/fontTools/pens/ttGlyphPen.py
@@ -15,6 +15,8 @@ from fontTools.ttLib.tables._g_l_y_f import GlyphCoordinates
 __all__ = ["TTGlyphPen", "TTGlyphPointPen"]
 
 
+match = notmatch = 0
+
 class _TTGlyphBasePen:
     def __init__(
         self,
@@ -132,6 +134,27 @@ class _TTGlyphBasePen:
             raise PenError("Didn't close last contour.")
         components = self._buildComponents(componentFlags)
 
+        flags = self.types[:]
+        cubic = 3 in flags
+        quadratic = 2 in flags
+        assert (
+            not cubic or not quadratic
+        ), "Can't mix cubic and quadratic curves in the same glyph"
+        flags = [
+            1 if flag in {1, 2, 3} else (0x80 if cubic else flag) for flag in flags
+        ]
+
+        pt = self.points
+        global match, notmatch
+        for j in range(0, len(self.points) - 1):
+            if flags[j] == 1 and flags[j-1] == flags[j+1] == 0x80:
+                if (pt[j][0] - pt[j-1][0] == pt[j+1][0] - pt[j][0] and
+                    pt[j][1] - pt[j-1][1] == pt[j+1][1] - pt[j][1]):
+                    match += 1
+                else:
+                    notmatch += 1
+        print("yo match %d notmatch %d\n", match, notmatch)
+
         glyph = Glyph()
         glyph.coordinates = GlyphCoordinates(self.points)
         glyph.coordinates.toInt()
```

> because my understanding so far is, whenever we can remove 1 on curve point, we can _always_ remove 3 control points and add one "super" offcurve point, leading to twice the savings as the simple method

No, look at that drawing, the offcurves also need to align in a particular way...

**Comment by anthrotype** [comment]
but the counter-argument about rounding errors actually is a big one and enough to let go of this optimization

**Comment by anthrotype** [comment]
> the offcurves also need to align in a particular way...

sorry I don't understand what you mean by "align".

**Comment by behdad** [comment]
> what is not enough? And enough to do what?
> C1 continous means the tangent vectors have same direction ("smooth" transition) and same magnitude as well, so the two offcurves are at equal distance relative to the middle on-curve which can thus be omitted

If the points are (capital for off-curve): p0, P1, P2, p3, P4, P5, p6, then the condition to drop p3 is simply that `P4 - p3 == p3 - P2`.  However for the Super-Bezier to work, it looks to me like you also need: `P2 + (P2 - P1) == P4 + (P4 - P5) == Po` where Po is the new Super-Bezier off-curve point. No?

**Comment by anthrotype** [comment]
> p0, P1, P2, p3, P4, P5, p6, then the condition to drop p3 is simply that P4 - p3 == p3 - P2

correct

> However for the Super-Bezier to work, it looks to me like you also need: P2 + (P2 - P1) == P4 + (P4 - P5) == Po where Po is the new Super-Bezier off-curve point

I have an intuition that given the previous condition, the latter one would still hold, but need to think a bit more (also gotta run home as it's late).
Thanks Behdad for indulging me!

(PS: playing with Just's drawbot script helps a lot visualize things better)

**Comment by behdad** [comment]
> I have an intuition that given the previous condition, the latter one would still hold, but need to think a bit more (also gotta run home as it's late).

No, if you move the P2,p3,P4 around, then it won't. It only will hold for one position of that group.

**Comment by behdad** [comment]
> how did you measure the gains for the implied on-curve removal?

Err, that snippet does not apply anymore...

**Comment by behdad** [comment]
> > how did you measure the gains for the implied on-curve removal?
> 
> Err, that snippet does not apply anymore...

I was wrong. It does.

**Comment by behdad** [comment]
> If the points are (capital for off-curve): p0, P1, P2, p3, P4, P5, p6, then the condition to drop p3 is simply that `P4 - p3 == p3 - P2`. However for the Super-Bezier to work, it looks to me like you also need: `P2 + (P2 - P1) == P4 + (P4 - P5) == Po` where Po is the new Super-Bezier off-curve point. No?

Based on this condition, if correct, NotoSansArabic has just a few super-Beziers:
```
yo match 4391 notmatch 37801 supermatch 28
```
In the not-worth-it range.

Code (on top of the fonttools `cubic-glyf` branch):
```
diff --git a/Lib/fontTools/pens/ttGlyphPen.py b/Lib/fontTools/pens/ttGlyphPen.py
index 3374ebcda..dacd44889 100644
--- a/Lib/fontTools/pens/ttGlyphPen.py
+++ b/Lib/fontTools/pens/ttGlyphPen.py
@@ -15,6 +15,8 @@ from fontTools.ttLib.tables._g_l_y_f import GlyphCoordinates
 __all__ = ["TTGlyphPen", "TTGlyphPointPen"]
 
 
+match = notmatch = supermatch = 0
+
 class _TTGlyphBasePen:
     def __init__(
         self,
@@ -132,6 +134,39 @@ class _TTGlyphBasePen:
             raise PenError("Didn't close last contour.")
         components = self._buildComponents(componentFlags)
 
+        flags = self.types[:]
+        cubic = 3 in flags
+        quadratic = 2 in flags
+        assert (
+            not cubic or not quadratic
+        ), "Can't mix cubic and quadratic curves in the same glyph"
+        flags = [
+            1 if flag in {1, 2, 3} else (0x80 if cubic else flag) for flag in flags
+        ]
+
+        pt = self.points
+        global match, notmatch, supermatch
+        for j in range(0, len(self.points)):
+            thisj = j
+            prevj = j - 1
+            prevj2 = j - 2
+            nextj = j + 1
+            nextj2 = j + 2
+            if nextj == len(self.points):
+                nextj = 0
+            if nextj2 >= len(self.points):
+                nextj2 -= len(self.points)
+            if flags[thisj] == 1 and flags[prevj] == flags[nextj] == 0x80:
+                if (pt[thisj][0] - pt[prevj][0] == pt[nextj][0] - pt[thisj][0] and
+                    pt[thisj][1] - pt[prevj][1] == pt[nextj][1] - pt[thisj][1]):
+                    match += 1
+                    if (pt[prevj][0] * 2 - pt[prevj2][0] == pt[nextj][0] * 2 - pt[nextj2][0] and
+                        pt[prevj][1] * 2 - pt[prevj2][1] == pt[nextj][1] * 2 - pt[nextj2][1]):
+                        supermatch += 1
+                else:
+                    notmatch += 1
+        print("yo match %d notmatch %d supermatch %d\n" % (match, notmatch, supermatch))
+
         glyph = Glyph()
         glyph.coordinates = GlyphCoordinates(self.points)
         glyph.coordinates.toInt()
```

**Comment by behdad** [comment]
> Based on this condition, if correct, NotoSansArabic has just a few super-Beziers:
> 
> ```
> yo match 4391 notmatch 37801 supermatch 28
> ```
> 
> In the not-worth-it range.

This is with no rounding error.

**Comment by behdad** [comment]
> > Based on this condition, if correct, NotoSansArabic has just a few super-Beziers:
> > ```
> > yo match 4391 notmatch 37801 supermatch 28
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the not-worth-it range.
> 
> This is with no rounding error.

With up to .5 error the results don't change.

**Comment by behdad** [comment]
> > > Based on this condition, if correct, NotoSansArabic has just a few super-Beziers:
> > > ```
> > > yo match 4391 notmatch 37801 supermatch 28
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In the not-worth-it range.
> > 
> > 
> > This is with no rounding error.
> 
> With up to .5 error the results don't change.

Error up to 1:
```
yo match 4391 notmatch 37801 supermatch 67
```
Still, negligible.

**Comment by behdad** [comment]
> > p0, P1, P2, p3, P4, P5, p6, then the condition to drop p3 is simply that P4 - p3 == p3 - P2
> 
> correct
> 
> > However for the Super-Bezier to work, it looks to me like you also need: P2 + (P2 - P1) == P4 + (P4 - P5) == Po where Po is the new Super-Bezier off-curve point
> 
> I have an intuition that given the previous condition, the latter one would still hold,

It's also clear that the super-Bezier doesn't follow from the mid-point condition, from a degree-of-freedom point of view. If you can drop two points instead of one, you are reducing the degree of freedom by 4 instead of two, so you need two equalities of point vectors instead of one.

**Comment by behdad** [comment]
No curve discussion is complete without @raphlinus

**Comment by anthrotype** [comment]
Ok yeah, I was wrong. Thanks for explaining and testing this!
I guess we can just expect that the number of offcurves is even and do the implied oncurve, and reject an odd number as invalid.

**Comment by raphlinus** [comment]
Skimmed this. My understanding is that it allows eliding an oncurve point in the "mirror" case? Also I'm wondering if you might get more hits if you allow +/- 1 ppem error. This seems valid to me as it likely improves the continuity and is unlikely to distort the shape in an undesirable way.

I'd be worried about implementations getting it wrong if it's a rare case, but perhaps a test suite could help with that.
