### ISSUE TITLE
varLib is creating multiple, disconnected feature variations groups from a single rule with a single condition

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#3003]
I have a variable font in which I am trying to do the typical GSUB of a simplified Q and Ø at heavy weights, when the inner counter can no longer support a bar.

I am compiling this from UFOs and a (v5) designspace, using FontMake version `3.5.1` and fonttools version `4.38.0`.

I have a `rule` that looks like this:

```xml
    <rule name="Open Rounds">
      <conditionset>
        <condition name="Weight" minimum="728" maximum="1000"/>
        <condition name="Optical Size" minimum="8" maximum="72"/>
      </conditionset>
      <sub name="Q" with="Q.open"/>
      <sub name="Oslash" with="Oslash.open"/>
      <sub name="oslash" with="oslash.open"/>
    </rule>
```

(I have also tried the above without any `Optical Size` condition, but the docs seem ambiguous about whether it is suggested to include axes if a rule should happen throughout the whole thing)

I don’t have any other rules that reference the `Q` or `Q.open`. However, this is the result I’m getting:

https://user-images.githubusercontent.com/45946693/221049580-a5bfd7c8-1b10-446e-bd16-0fa527676b7e.mov

Interestingly, this "flickering" doesn’t happen on the max end of `opsz`.

If I use TTX to see the GSUB table, I can see that the substitution lookup is referenced in multiple different `FeatureVariationRecord`s, which is somewhat surprising to me, but I don’t know enough about those to know whether that is significant.

My axes look like this, if it is useful:

```xml
  <axes elidedfallbackname="Regular">
    <axis tag="opsz" name="Optical Size" minimum="8" maximum="72" default="8">
      <labelname xml:lang="en">Optical Size</labelname>
      <map input="72" output="72"/>
      <map input="20" output="40"/>
      <map input="8" output="8"/>
    </axis>
    <axis tag="wght" name="Weight" minimum="1" maximum="1000" default="700">
      <labelname xml:lang="en">Weight</labelname>
      <map input="1000" output="1000"/>
      <map input="900" output="850"/>
      <map input="800" output="775"/>
      <map input="700" output="700"/>
      <map input="600" output="600"/>
      <map input="500" output="500"/>
      <map input="400" output="400"/>
      <map input="300" output="300"/>
      <map input="200" output="200"/>
      <map input="100" output="100"/>
      <map input="1" output="1"/>
      <labels>
        <label uservalue="1" name="Hairline"/>
        <label uservalue="50" name="ExtraThin"/>
        <label uservalue="100" name="Thin"/>
        <label uservalue="200" name="ExtraLight"/>
        <label uservalue="300" name="Light"/>
        <label uservalue="400" name="Regular" elidable="true" linkeduservalue="700"/>
        <label uservalue="500" name="Medium"/>
        <label uservalue="600" name="SemiBold"/>
        <label uservalue="700" name="Bold" linkeduservalue="400"/>
        <label uservalue="800" name="ExtraBold"/>
        <label uservalue="900" name="Black"/>
        <label uservalue="1000" name="Ultra"/>
      </labels>
    </axis>
    <axis tag="ital" name="Italic" values="0 1" default="0">
      <labels>
        <label uservalue="0" name="Roman" elidable="true"/>
        <label uservalue="1" name="Italic"/>
      </labels>
    </axis>
  </axes>
```

I’m happy to share any info that might be helpful here, or email source files to someone, if useful. If you’d like to inspect the font files themselves, these glyphs and this same issue occurs in the partially subset "trial" fonts in here:

[ArrowType-NameSans-v08-Trial.zip](https://github.com/fonttools/fonttools/files/10819265/ArrowType-NameSans-v08-Trial.zip)

I assume I’m probably doing something silly and not realizing it, as that is often the case in issues like this. If anyone sees anything, I would very much appreciate being steered in the correct direction! 

If it’s not obviously my fault, then it is possible this is a problem in varLib (or maybe somewhere else in the FontMake chain?). If a simplified reproduction case is required for further action, I can make one, but I wanted to ask more broadly before duplicating things.

Thanks so much for any insight!

**Comment by behdad** [comment]
Thanks for the detailed report.  If you can email me the sources I can try to debug this. Is hard otherwise.

**Comment by arrowtype** [comment]
Wow, thank you! Sure, no problem at all. I’ll zip up the sources and email them in a few moments!

**Comment by arrowtype** [comment]
Okay, email sent!

Quick update here: I do see that I get this warning from FontMake:

```
WARNING:fontTools.ttLib.tables.otBase:hb.repack failed to serialize 'GPOS', attempting fonttools resolutions ; the error message was: RepackerError
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 1, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 24)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 24)
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
WARNING:fontTools.ttLib.tables.otBase:hb.repack failed to serialize 'GPOS', attempting fonttools resolutions ; the error message was: RepackerError
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 1, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
```

That seems like it might be related, but I don’t know for sure.

**Comment by behdad** [comment]
> That seems like it might be related, but I don’t know for sure.

No, that's harmless and expected.

**Comment by behdad** [comment]
Okay I took a look. I don't think it's your fault.

Initially from your report I thought you only have the Q rules. But looking at your sources you have other rules too, that overlap the Q rules. The solver has to split the rules into non-overlapping regions. That's why you see the Q rule lookup referenced from multiple regions.

The code for this wasn't strongly tested in the field. Let me see if I can get my head around it. I wonder if it's just that we should encode the lookups in the inreverse order of what we do...

cc @justvanrossum

**Comment by behdad** [comment]
It's a bit hard to debug because there's many rulesets involved...

**Comment by arrowtype** [comment]
Thanks so much for the update!

Thanks also for the explanation of why there are multiple featureVariations – that makes more sense, now.

I suppose I'll try chopping out certain rules and seeing if something fixes this. My mental model here was somewhat like media queries in CSS / breakpoints in responsive web design. But yes, they did lead to quite a bit of complexity with everything put together.

**Comment by behdad** [comment]
I'm confident we can make it work..

**Comment by behdad** [comment]
BTW, do the "Italic a" rules work for you? I don't see them in the compiler...

**Comment by arrowtype** [comment]
Awesome! I'm happy when I can help improve a system in some small way. So grateful to you and others who make this stuff possible!

**Comment by arrowtype** [comment]
Yes, they seem to!

**Comment by behdad** [comment]
Oh, it builds two varfonts from the same designspace. That's new to me...

**Comment by arrowtype** [comment]
Yup! I was about to say:

The italic axis is non-continuous, so the "italic a" rule makes the single-story a the default in the italic VF.

Designspace v5 is super nice for this! (Also because it lets a STAT table get constructed from designspace data).

**Comment by behdad** [comment]
I see the bug..

**Comment by behdad** [comment]
Okay, I have a fix in https://github.com/fonttools/fonttools/pull/3005
Some tests need updating there.

**Comment by arrowtype** [comment]
Wow, that was fast! 🔥 Thanks for working on it so quickly!

**Comment by arrowtype** [comment]
I’m sure you’ve already tested this on your end, but: it works well when I build with the varLib in the branch!

https://user-images.githubusercontent.com/45946693/221205933-cf8443b3-3b2e-4965-883d-19dd09a95afc.mov
