### ISSUE TITLE
Error on sorting NameRecords, comparison not implemented?

### ISSUE THREAD

**Issue by kontur** [fonttools/fonttools#3006]
Compiling a font with the Fontmake toolchain and with Fonttools 4.38.0 I get:

```
  File "/Users/johannes/.pyenv/versions/3.10.4/envs/mrhandy/lib/python3.10/site-packages/fontTools/ttLib/tables/_n_a_m_e.py", line 62, in compile
    names.sort() # sort according to the spec; see NameRecord.__lt__()
TypeError: '<' not supported between instances of 'NameRecord' and 'NameRecord'
```
in https://github.com/fonttools/fonttools/blob/111d2c5c0f3de8804843ad5dfdf4b18c8b107966/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L62

Checking the [NameRecord.__lt__()](https://github.com/fonttools/fonttools/blob/111d2c5c0f3de8804843ad5dfdf4b18c8b107966/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L581) method it seems something is obscuring the actual error in this blanket try block, and as per the comments, it explains:

```
			# This can only happen for
			# 1) an object that is not a NameRecord, or
			# 2) an unlikely incomplete NameRecord object which has not been
			#    fully populated, or
			# 3) when all IDs are identical but the strings can't be encoded
			#    for their platform encoding.
			# In all cases it is best to return NotImplemented.
			return NotImplemented
```

The original source of the error for my case was `'charmap' codec can't encode character '\u0132' in position 35: character maps to <undefined> SELF Alternative form of ‘J’ and Dutch ‘Ĳ’` for a stylistic set name that uses the encoded `Ĳ` (not `I` `J`). This probably falls under 3) but not obscuring this error with a generic `NotImplement` would be heeeeeeaps more helpful. In fact, emitting a warning and passing might actually be a viable option, too. I reckon accidental encoding mishaps or impossibilities might happen rather frequently.

This should be reproducible with a font with this in it's features:

```
feature ss01 {
	featureNames {
		name "Alternative form of ‘J’ and Dutch ‘Ĳ’";
                name 1 "Alternative form of ‘J’ and Dutch ‘Ĳ’";
	};
        #...
} ss01;
```

It's the second line with the platform ID (and omitted script ID which falls back to Latin) that is causing the issue.

**Comment by anthrotype** [comment]
ok so you're suggesting we let the UnicodeEncodeError propagate as such instead of handling it as "I don't know how to sort this"?

**Comment by anthrotype** [comment]
> not obscuring this error with a generic NotImplement would be heeeeeeaps more helpful

maybe yes, feel free to send a PR. thanks

**Comment by kontur** [comment]
> ok so you're suggesting we let the UnicodeEncodeError propagate as such instead of handling it as "I don't know how to sort this"?

Not sure how bad of an idea it is, but at least not raising a `NotImplement` in this case would be helpful. The code comment seems to imply that the encoding issue happens after already attesting that the IDs are identical. I don't think it actually does, but it could be made to explicitly check the IDs first. Then comparing things that possibly trigger the encoding error. Or the other way around, first do the `toBytes()` calls (and catch encoding errors, and emit or not emit a warning), then do the current comparison — in case of encoding errors we could still sort the NameRecords by the other IDs, at least.

Imo this is not a show stopper for compiling a font, but of course something a font engineer might want to address for other reasons — e.g. in my case the string probably won't render correctly either if indeed rendered in that encoding; either way, the comparison should not fail.

Happy to send something in a couple of days.
