### ISSUE TITLE
hhea.numberOfHMetrics not correct for monospace

### ISSUE THREAD

**Issue by aaronbell** [fonttools/fonttools#3014]
Microsoft makes a [specific recommendation for monospace fonts](https://learn.microsoft.com/en-us/typography/opentype/spec/recom#hhea-table) to set the hhea.numberofHMetrics value to `3`.

Following that guidance, Fontbakery recently [implemented a check](https://github.com/googlefonts/fontbakery/pull/4025) that issues a FAIL if this is not set per Microsoft's recommendation. 

However, as far as I can tell, fonttools does not consider whether a font is monospaced when calculating hhea.numberOfHMetrics. In my current project, I'm noting that I'm getting a value of `1010` out rather than `3`. And evaluating a variety of monospace fonts in the Google Fonts library (as well as my own Cascadia Code which is built using fonttools), none list a hhea.numberOfHMetrics of `3`.

I believe a special casing needs to be added to the hhea compile / decompile to account for monospace fonts.

**Comment by justvanrossum** [comment]
Regardless of what fonttools will have to do, a fontbakery FAIL is rather overreaching, especially since the quoted recommendation uses the word "suggested".

**Comment by behdad** [comment]
Most monospace fonts these days are not truly "monospaced" because of zerowidth marks. That's probably why you see a large value calculated by fonttools.

**Comment by dscorbett** [comment]
Why does Microsoft recommend this? I assume it is based on [their old advice](https://learn.microsoft.com/en-us/typography/opentype/otspec170/recom#first-four-glyphs-in-fonts) that “Glyph 1 should have no contours and zero advance width”. That is, if the font’s monospace width is _n_, then .notdef has width _n_, glyph 1 has width 0, and the rest have width _n_. That requires a minimum of 3 longHorMetric records in 'hmtx'. However, that is an optimization; it’s not wrong for a font to have multiple trailing longHorMetric records with the same advanceWidth, it’s just inefficient. Therefore, a FAIL seems too strong.

Microsoft’s current advice doesn’t mention a special width for glyph 1 (.null) anymore. That means all glyphs in a monospace font could have the same width, so only 1 longHorMetric record is necessary, so hhea.numberOfHMetrics should be 1 (under a strict definition of monospace font, without zero-width marks).

**Comment by anthrotype** [comment]
if fontbakery's check merely asserts that `hhea.numberofHMetrics == 3` "because the spec recommends so", then it is completely bogus and should simply be ignored/removed

**Comment by felipesanches** [comment]
@madig suggested adding that FAIL. I have now downgraded it to a WARN and changed a bit the wording of the message, directing users to come read this conversation.

I'm open to further improving the check by either completely removing this WARN, or by making it more informative to the users.
