### ISSUE TITLE
italic statics made from VF with slant axis are having incorrect caret slope/run

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fonttools#3016]
The caret slope/run is the only missing piece concerning the static italic binaries instantiated from a VF with a slant axis. At the moment they are set as an upright font.

@yanone wrote this little snippet to fix it when we need it on our side: 
```
font["hhea"].caretSlopeRise = font["head"].unitsPerEm
font["hhea"].caretSlopeRun = round(math.tan(math.radians(-font["post"].italicAngle)) * font["head"].unitsPerEm)
```
But it would awesome if it would be in fonttools directly :)

cc @m4rc1e @simoncozens

**Comment by RosaWagner** [comment]
I just updated to the main branch instead of last release and notice it was in. Closing then, thanks!

**Comment by yanone** [comment]
But you posted this in fonttools, not fontbakery, so you want fonts to be generated with the correct values, not checked, right?

_visible confusion_

**Comment by RosaWagner** [comment]
I wanted varLib.instancer to set up the correct values when slicing a VF with slant axis, and there is also a separate issue in Fontbakery to check caret slope/rise. I don’t know if it was integrated or not yet in FB. What is the confusion about?

**Comment by yanone** [comment]
The confusion is about you closing this issue after you learned about the existing fontbakery check even though the check doesn't solve the actual instantiation issue.

But when you said "I just updated to main branch", maybe you meant fonttools, not fontbakery, so maybe the confusion is on my side

**Comment by RosaWagner** [comment]
sorry @yanone my comment was not about fontbakery, only fonttools :)
