### ISSUE TITLE
Let ttx read from stdin instead of a file

### ISSUE THREAD

**Issue by ygoe** [fonttools/fonttools#3019]
ttx can already dump a font file to XML format to stdout so that an automated process does not need to create files on disk. But the reverse way is not possible. To write a modified XML back to a font file, the in-memory XML must always be written to a file that ttx will read from and that should be deleted again afterwards. I tried passing nothing or "-" as file name and pipe in the XML but it would complain about the missing file name parameter.

**Comment by anthrotype** [comment]
@ygoe with #3020, the special "-" value as input file name now means read from standard input, works both when dumping a font to .ttx and when compiling a .ttx file to font binary.
