### ISSUE TITLE
ConditionSets and VariableScalars should have `avar` applied to coordinates

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#3040]
I found a case where a mapping in a Designspace file like so:

```xml
  <axes>
    <axis tag="wght" name="Weight" minimum="100" maximum="900" default="100">
      <map input="100" output="22"/>
      <map input="600" output="115"/>
      <map input="900" output="185"/>
    </axis>
  </axes>
  <rules processing="last">
    <rule name="conditional_sub">
      <conditionset>
        <condition name="Weight" minimum="116" maximum="185"/>
      </conditionset>
      <sub name="e" with="a"/>
    </rule>
  </rules>
```

means that "e" is substituted by "a" at wght=606 and upwards (116 in design coordinates is a tad over 600 in user coordinates), whereas with a feature file snippet like this:

```
lookup conditional_sub {
    sub e by a;
} conditional_sub;

conditionset test {
    wght 606 900;
} test;

variation rlig test {
    lookup conditional_sub;
} rlig;
```

it is substituted at wght=644 and upwards.

**Comment by anthrotype** [comment]
From @simoncozens' https://github.com/adobe-type-tools/afdko/pull/1350#issuecomment-955038971

> userspace values as taken from the fvar table (wght=400 in the Nunito example), which is how we’ve interpreted things so far

so, yes, whenever fvar userspace coordinates are given, avar needs to be taken into account when normalizing. 

E.g. by doing https://github.com/fonttools/fonttools/blob/032616b10685bfca139ff702d1ffc6458891d980/Lib/fontTools/varLib/instancer/__init__.py#L1069-L1074

**Comment by simoncozens** [comment]
This is similarly true for locations used in variable scalars.

**Comment by madig** [comment]
Hm, so, at what level/where should I fix this? There are a couple of normalization functions floating around, i.e. `feaLib.builder.Builder.add_conditionset` is using `varLib.models.normalizeValue`.

**Comment by madig** [comment]
So, at least when changing add_conditionset like so:

```
        if "avar" in self.font:
            mapping = self.font["avar"].segments
            value = {
                axis: tuple(
                    floatToFixedToFloat(piecewiseLinearMap(v, mapping[axis]), 14)
                    for v in condition_range
                )
                for axis, condition_range in value.items()
            }
```

I get almost the same cross-over point (606 instead of 605 with the Designspace). So I guess there's a rounding issue in here somewhere.

**Comment by anthrotype** [comment]
> So I guess there's a rounding issue in here somewhere.

the rounding issue is entirely possible, because the avar mappings are stored as f2dot14 so.. it's unlikely you'll be able to get exactly the same value as using the DS axis maps (which use floats). Since you no longer have that from FEA, but only the avar, that's all you got.

**Comment by anthrotype** [comment]
there's no way around it

**Comment by anthrotype** [comment]
@simoncozens notes that VariableScalars, used in FEA to construct variable ValueRecords in GPOS pos or GDEF anchors will also need to be avar-mapped.
