### ISSUE TITLE
pyftmerge OTF changes width of glyphs in output file

### ISSUE THREAD

**Issue by KatjaSchimmel** [fonttools/fonttools#3069]
I'm trying to merge two OTF (one with only Latin Glyphs, one with only Arabic glyphs). In the output file, the right sidebearing of the glyphs change depending on which OTF is named first in the terminal command.
For example:
- Latin OTF first (LA-Regular.otf)
`pyftmerge L-Regular.otf A-Regular.otf --output-file=LA-Regular.otf
`
The right sidebearing of all Arabic glyphs change.
- Arabic OTF first (AL-Regular.otf)
`pyftmerge A-Regular.otf L-Regular.otf --output-file=AL-Regular.otf
`
The right sidebearing of all Latin glyphs change.

I did several tests to find out the value added or subtracted from the right sidebearing. 
In my latest test I merged a Latin OTF containing only **H** with an Arabic OTF containing only **alef** and **space**. The output file showed following:
- Latin OTF first (LA-Regular.otf)
LSB of H = 100 units
RSB of H = 100 units
LSB of alef = 95
RSB of alef = 335 (should be 95, 240 units are added)
width of space = 500 (should be 260, 240 units are added)
- Arabic OTF first (AL-Regular.otf)
LSB of H = 100 units
RSB of H = -148 units (should be 100, 248 units are subtracted)
LSB of alef = 95
RSB of alef = 95
width of space = 260

The value of 240 is being added to the Arabic Glyphs, in the merged "LA" file. The value of 248 subtracted from the Latin glyphs, in the merged "AL" file. I'm adding a screenshot of the CFF table. 

I also found out that this value changes, when merging bigger charactersets. For example I merged one Latin OTF with Latin Plus characterset and one Arabic OTF with Arabic Language coverage. The value added/subtracted from the right sidebearing was 176 units for both merged output files.

I have no idea why the width of the glyphs change and where the values come from. Do you know what is happening here?

Merging two TTF is no problem. All widths are maintained.

<img width="1033" alt="Screenshot 2023-03-29 at 15 01 16" src="https://user-images.githubusercontent.com/32390109/228543617-90cdbd77-3900-455c-9c0e-a2f650b98d21.png">

**Comment by anthrotype** [comment]
could it be that the two CFF fonts have different nominalWidthX/defaultWidthX attributes and the merger doesn't take care of updating those? I don't see them mentioned in the [merge code related to CFF table](https://github.com/fonttools/fonttools/blob/3b9a73ff8379ab49d3ce35aaaaf04b3a7d9d1655/Lib/fontTools/merge/tables.py#L239-L287).

**Comment by anthrotype** [comment]
I believe that, if we keep the nominalWidthX/defaultWidthX of the first font in the merge, then all the charstrings for the subsequent fonts will have to be updated so that they encode the correct width (no width if equal to defaultWidthX, or width - nominalWidthX if different)

**Comment by anthrotype** [comment]
good. now the problem is you can't simply change those two values (e.g. make them the same) because it will change all the glyphs advances. What the merger should do is fix each of the glyph's charstrings such that the width command is set according to whatever the default/nominal widths are.

**Comment by behdad** [comment]
I don't think I'll get to fix this soon. :(

**Comment by behdad** [comment]
> I don't think I'll get to fix this soon. :(

I put a PR together in https://github.com/fonttools/fonttools/pull/3070
Can you test please?

**Comment by behdad** [comment]
> I put a PR together in #3070
> Can you test please?

I don't think it works currently. Still debugging. Any chance you can email your test fonts to me?

**Comment by behdad** [comment]
It might work actually.
