### ISSUE TITLE
Default source is unable to be found if re-mapped (<map>)

### ISSUE THREAD

**Issue by ryanbugden** [fonttools/fonttools#3071]
I have gotten the following error (upon trying to generate a variable font with fontmake), when trying to map a `0–1000` `wght` axis to `400–800` with [map element](https://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#map-element) .

`"Cannot determine default source to look up family name."`
https://github.com/fonttools/fonttools/blob/3d2fa8a342e2ca9328e06d8af8b2b6470a50b055/Lib/fontTools/designspaceLib/statNames.py#L67

This seems to mean that `DesignSpaceDocument().findDefault()` is no longer able to find the default source (at `0 wght`), when the map value is like so: `<map input="0" output="400"/>`

https://github.com/fonttools/fonttools/blob/3d2fa8a342e2ca9328e06d8af8b2b6470a50b055/Lib/fontTools/designspaceLib/__init__.py#L2744

Is `findDefault()` taking the mapping into full account when attempting to establish the default source?

**Comment by anthrotype** [comment]
the default source is by definition the one which is at the default location along all the axes. The axes min/default/max are specified in user-space coordinates (the "input" of axis mappings). The source locations use internal design-space coordinates (the "output"). Make sure that the source that you want to be considered "the default" has a location that corresponds to all the axes defaults.

**Comment by ryanbugden** [comment]
I have a source at `0 wght`, `0 slnt`, `8 opsz`. These are the default values of all 3 axes as well.

When my map values for `wght` start like `<map input="0" output="0"/>`, everything generates correctly.
Running a script to parse the designspace, `findDefault()` comes up with the correct source.

When my map values for `wght` start like `<map input="0" output="400"/>`, I get the following error upon an attempted fontmake variable font generation:
```
WARNING:fontTools.designspaceLib.statNames:Cannot determine default source to look up family name.
fontmake: Error: In 'path/to/file.designspace': Generating fonts from Designspace failed: 'en'
```
Running a script to parse the designspace, `findDefault()` comes up with `None`

**Comment by anthrotype** [comment]
Perhaps you just confused input and output, it's not uncommon. Think of "input" as the coordinates that the user of the font sees when selecting an instance location along the axes as defined in the fvar table. The "output" of the mappings are the internal design coordinates (arbitrary numbers used for interpolation in the designspace, normalized to -1, 0 and +1 in the compiled variation tables), i.e. the result of avar mapping.

**Comment by anthrotype** [comment]
basically you want that wght=400 (user-space location, what the user of the font selects) gets mapped to wght=0 internally, not the other way around, so you should write `<map input="400" output="0"/>`

and the weight axis definition should use user-space coordinates as well, e.g. `<axis minimum="100" default="400" maximum="900" />`

**Comment by ryanbugden** [comment]
That was the problem, thank you! Apologies for the mis-issuing, and thanks for the clarity.
I see designspace files as production-centric, rather than user-centric, so input and output made sense as internal design coordinates and user-space coordinates respectively. Now I know for the future!
