### ISSUE TITLE
Faulty metrics in italic TTFs

### ISSUE THREAD

**Issue by ryanbugden** [fonttools/fonttools#3072]
Upon generating TTFs, some round glyphs with oblique left-most "extremes" slide sideways in their glyph boxes. 

See issue started here  (I think misdirected at FDK) for more background, and a sample to help reproduce:
https://github.com/adobe-type-tools/afdko/issues/1516

I'm not sure where the issue lies. Maybe one of the below places?

https://github.com/fonttools/fonttools/blob/501353f3df2de69a126587da22cb0c6fb1db5acc/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L1153-L1154
https://github.com/fonttools/fonttools/blob/3b9a73ff8379ab49d3ce35aaaaf04b3a7d9d1655/Lib/fontTools/ttLib/ttFont.py#L78

**Comment by anthrotype** [comment]
generating with what exactly? In the other linked thread, @jenskutilek suggests that the hmtx lsb is incorrectly being set. But fontmake (ufo2ft) always use the minimum x coordinate of the _control points_, not the minimum x coordinate of tighest bounds of the curve. And that also always corresponds to the glyph's xMin in the glyf tabke, so the head table flag 1 is always set.

**Comment by justvanrossum** [comment]
Reproduced in RoboFont. It has nothing to do with italic, but indeed with the control box being bigger than the (tight) bounding box.

The glyph `B` has such a shape in this test UFO:
[LSBTTFBug.ufo.zip](https://github.com/fonttools/fonttools/files/11114333/LSBTTFBug.ufo.zip)

The left-most control point of `B` is at x=0, so an lsb of 0 is expected. FontMake builds this correctly, but when generating in RoboFont this is the built `hmtx` table:

```xml
  <hmtx>
    <mtx name=".notdef" width="500" lsb="50"/>
    <mtx name="a" width="50" lsb="0"/>
    <mtx name="b" width="500" lsb="48"/>
    <mtx name="space" width="500" lsb="0"/>
  </hmtx>
```
The lsb of 48 roughly corresponds with the xMin of the *tight* bounding box. But xMin in a TTF glyph should be the xMin of the control bounds. So 48 is wrong, it should be 0.

I'm pretty sure that RF uses afdko to generate TTF, so the bug is rather there than in fonttools.

**Comment by frankrolf** [comment]
The afdko does not generate TTFs directly, as commented earlier.

**Comment by anthrotype** [comment]
Wait! Maybe it _is_ our bug...

ufo2ft uses T2CharString.calcBounds to compute the bounds of the CFF charstrings:

https://github.com/googlefonts/ufo2ft/blob/0c0a570b84d1351ab704ba1fa5ae03aeef51179f/Lib/ufo2ft/outlineCompiler.py#L1167-L1202

that method is defined in fonttools here:

https://github.com/fonttools/fonttools/blob/3b9a73ff8379ab49d3ce35aaaaf04b3a7d9d1655/Lib/fontTools/misc/psCharStrings.py#L1150-L1153

This is using the BoundsPen, whereas it should have used the ControlBoundsPen to match a similar calculation as done for the TrueType glyfs, I think, if I am not mistaken.

For TTF, ufo2ft uses the xMin that fonttools TTGlyph.recalcBounds returns, and the latter I am pretty sure uses the min x coordinate of the control points, not the tight bounds.

**Comment by anthrotype** [comment]
... but the OP said this happens "Upon generating TTFs", which supposedly already use control bounds, so maybe it's not that.

BTW, do you remember why in T2CharString.calcBounds we use BoundsPen instead of ControlBoundsPen, maybe we did that intentionally but can't remember.

**Comment by anthrotype** [comment]
I don't even know if RoboFont uses ufo2ft honestly, so maybe this is not even relevant to this issue.

**Comment by justvanrossum** [comment]
I somehow believe for CFF one is supposed to use the tight bounding box. At the same time I think hmtx lsb should be ignored for CFF. I have no desire to dig through the spec right now.

**Comment by typemytype** [comment]
(RoboFont can use fontmake as compiler by user preference)

**Comment by typemytype** [comment]
(and FYI RoboFont does not use fdk to generate ttf binaries)
