### ISSUE TITLE
Problem with merging two specific fonts

### ISSUE THREAD

**Issue by NinzMeister** [fonttools/fonttools#3081]
Hi all,

I'm trying to merge the following two fonts:
`SourceHanSerifK-Light.ttf` and `NotoSansArabic-VariableFont_wdth,wght.ttf `

but I get the following error: Assertion Error: `Expected all items to be equal: [0, NotImplemented]`

Any suggestions on this? TIA 😄

**Comment by anthrotype** [comment]
doesn't the full error message say _what_ is expected to be equal?

**Comment by NinzMeister** [comment]
> 

![image](https://user-images.githubusercontent.com/130746784/232708090-70bed202-404f-4411-8b79-ed167478f18e.png)
This is the full error, but if I'm honest I've no clue what that means 😢

**Comment by behdad** [comment]
Or that the second seems to be a variable font.

**Comment by NinzMeister** [comment]
You are probably right, it seems it's too complicated to merge those types of fonts e.g. Arabic and Chinese symbols 

But! my issues are sorted now that I found a font file that seems to cover basically everything. phew 🙂 
file here: https://github.com/kaienfr/Font/blob/master/font/ARIALUNI.TTF

info here: https://learn.microsoft.com/en-us/typography/font-list/arial-unicode-ms
