### ISSUE TITLE
Glyphs are renamed when exporting?

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fonttools#3083]
I am writing a Python code uses FontTools to modify the font `cmap` and `name` table without modifying glyph names. After parsing the whole code, when I double check with `ttx -t post`, the original glyph name of `Idotaccent` is missing from the `post` table. There is no modification to any of the other tables in the font. Opening it with FontCreator shows the glyph name to be `Idot`.

The full Python code is included in the ZIP file with thenecessary files to recreate the problem.
`py cp_converter.py I.Ming-Regular.ttf`
[cp.zip](https://github.com/fonttools/fonttools/files/11261397/cp.zip)

**Comment by justvanrossum** [comment]
Here's what's happening:
- post table v2 uses a mix between a list of "standard" glyph names and font-specific glyph names
- Idotaccent is (according to the [Apple TT spec](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6post.html) and [FontTools](https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/ttLib/standardGlyphOrder.py)) part of the standard set
- This issue's font has `Idotaccent` encoded as a font-specific glyph name
- When compiling, FontTools sees `Idotaccent`, sees that it's part of the standard set, and encodes it as such, and not as a font-specific glyph name
- Apparently, FontCreator thinks this standard glyph is named `Idot`, and shows it as such

**Comment by NightFurySL2001** [comment]
Hmm... I see. It seems that this might be FontCreator problem? There are some glyph names that FontCreator doesn't show any glyph names at all, such as Plane 2 characters (e.g. u20000, u2ABCD) and highly complex name (e.g. fullwidthexclamationmark.crnr.vert).

**Comment by kenmcd** [comment]
> It seems that this might be FontCreator problem

Yes. I have found other errors with the FC names.
And there is no way to fix them.
FontLab for example enables you to edit the name list files.
Never found a file to edit in FC.

Discovered the FontCreator glyph names issues while trying to update/fix some old Type1 conversions - and found some names wrong and/or missing. So now just use FontLab as it does a much better job in that situation.

**Comment by NightFurySL2001** [comment]
Ok, thank you for the information.
