### ISSUE TITLE
feature variations lookup order only rvrn should be first

### ISSUE THREAD

**Issue by punchcutter** [fonttools/fonttools#3097]
https://github.com/fonttools/fonttools/pull/2867/files

This change seems to have broken processing=last features because they are also getting forced to reorder unless I'm looking at something wrong. With the update from 4.38.0 in afdko we have a broken build now.

**Comment by behdad** [comment]
> processing=last features

Excuse my fading memory. What are those?

**Comment by punchcutter** [comment]
rclt by default usually, but could be subbed for rlig. Could of course be anything in the world and should still work.

**Comment by behdad** [comment]
My question was where does the terminology come from. Now I see it's from designspace.

**Comment by punchcutter** [comment]
Ah, yes. Of course I'd expect it always in lookup order except for the ridiculous case of rvrn.
