### ISSUE TITLE
[subset] Support removing glyphs from requested set

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#31]
As Adam requested:

If possible, please implement a special \* glyph identifier which means „entire glyph set”. It would be useful if one wanted to do the non-subsetting optimizations. And, it would be particularly useful when combined with a - prefix for glyph identifiers. 

For example, I’d like to run pyftsubset as follows: 

pyftsubset font.ttf \* -A -B -U+E000 

Then, the subsetter would remove the glyphs A, B and the character U+E000 but would retain all other glyphs. 

The "*" part is implemented already.

**Comment by arrowtype** [comment]
Has there been any change on this? Based on the docs at https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/subset/__init__.py, it doesn't seem like it. But, maybe there is still a way to do what I'm trying...

I'm hoping to make three subsets of a font:
1. Google Fonts Latin Basic
2. Vietnamese-specific characters
3. Everything else ("Latin Extended")

I would like to set up two lists: one for Latin Basic, and one for Vietnamese. These would be used as glyphs to keep for subsets 1 & 2, and then combined as a list of glyphs to remove for subset 3. (Though I believe would have to keep glyphs `ĨŨĩũ` for both Vietnamese and Latin Ext.)

Without this feature, I believe I may have to find a slightly more complex way to determine which unicodes a font has that aren't in my concatenated two lists. Something like...

```
latinExt = [uni for uni in basicPlusVietnamese if uni not in allUnicodes]
```

**Comment by BoldMonday** [comment]
Judging by the documentation that you get from `$ pyftsubset --help` it appears that the subsetter only accepts lists of glyphs/unicodes/gids to *keep* and not lists of items to *remove*.

You probably need to keep track of the unicodes for all three subsets anyway because you need those in css to define your font stack?

**Comment by behdad** [comment]
Fixed I believe.
