### ISSUE TITLE
Demote "feature has not been defined" to a warning

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#3109]
Consider this feature code:

```
feature liga {
    # I'm definitely defining a feature here, I just haven't put any rules in it.
    lookupflag 0;
} liga;

feature aalt {
    feature liga;
} aalt;
```

This currently refuses to compile, complaining that the `liga` feature has not been defined. I think this is wrong on its face, but it's also annoying as well. When generating automatic feature code, or automatically refactoring feature code, you may not want to go back and check whether a feature has any substantive rules and then, if not, remove all references to it; you just want to dump out all the features with the code that it's in them.

Any opinions on demoting the current error to a warning? I'm always in favour of "being permissive in what you accept".

**Comment by anthrotype** [comment]
ok but what do you expect the compiler to do in this case? Skip the feature or add an empty feature record?

**Comment by anthrotype** [comment]
ah this has to do with building `aalt` only:

https://github.com/fonttools/fonttools/blob/86291b6ef62ad4bdb48495a4b915a597a9652dcf/Lib/fontTools/feaLib/builder.py#L298

yes, it's fine to warn and skip in this case

**Comment by khaledhosny** [comment]
Empty feature blocks get skipped, right? I guess because we wouldn’t know what table to put them in.
