### ISSUE TITLE
Merging kerning lookup statements fails when default source has value of 0

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#3111]
A font with contextual kerning had the following line in a lookup for the default source:

```fea
pos @group1 @group2 @group3' 0;
```

while the other masters had different values. This fails when merging into a VF, because the default source's zero gets turned into a `None`, which then looks to varLib merging as if the default source was missing, raising a `VariationModelError`.

**Comment by anthrotype** [comment]
I believe the culprit is this use of ValueRecord.getEffectiveFormat() (instead of getFormat) in the varLib.merger that turns 0s into Nones:

https://github.com/fonttools/fonttools/blob/65bc6105f7aec3478427525d23ddf2e3c8c4b21e/Lib/fontTools/varLib/merger.py#L359-L361

**Comment by behdad** [comment]
Can I have a test please?

**Comment by madig** [comment]
```py
from fontTools.designspaceLib import DesignSpaceDocument
from ufo2ft import compileVariableTTF
from ufoLib2 import Font

ds = DesignSpaceDocument()
ds.addAxisDescriptor(name="wght", tag="wght", minimum=100, maximum=900, default=400)
ds.addSourceDescriptor(font=Font(), location=dict(wght=100))
ds.addSourceDescriptor(font=Font(), location=dict(wght=400))
ds.addSourceDescriptor(font=Font(), location=dict(wght=900))

ds.sources[0].font.newGlyph("a").unicode = ord("a")
ds.sources[0].font.newGlyph("b").unicode = ord("b")
ds.sources[0].font.features.text = "feature kern { pos a b b' 100; } kern;"

ds.sources[1].font.newGlyph("a").unicode = ord("a")
ds.sources[1].font.newGlyph("b").unicode = ord("b")
ds.sources[1].font.features.text = "feature kern { pos a b b' 0; } kern;"

ds.sources[2].font.newGlyph("a").unicode = ord("a")
ds.sources[2].font.newGlyph("b").unicode = ord("b")
ds.sources[2].font.features.text = "feature kern { pos a b b' -100; } kern;"

font = compileVariableTTF(ds, inplace=True)
font.save("test.ttf")
```

Change 0 to 1 and it werks.

**Comment by behdad** [comment]
Alternate fix. I prefer this one:
```diff
diff --git a/Lib/fontTools/otlLib/builder.py b/Lib/fontTools/otlLib/builder.py
index 7a5848ad8..af166401a 100644
--- a/Lib/fontTools/otlLib/builder.py
+++ b/Lib/fontTools/otlLib/builder.py
@@ -2385,10 +2385,7 @@ def buildSinglePosSubtable(values, glyphMap):
     ]
     if all(v == valueRecords[0] for v in valueRecords):
         self.Format = 1
-        if self.ValueFormat != 0:
-            self.Value = valueRecords[0]
-        else:
-            self.Value = None
+        self.Value = valueRecords[0]
     else:
         self.Format = 2
         self.Value = valueRecords
```
The `self.Value = None` doesn't make any difference in the binary; in fact, reading the binary back we probably never get `self.Value = None` even if `self.ValueFormat = 0`. So this issue only happens when not going through the binary.

**Comment by behdad** [comment]
> The `self.Value = None` doesn't make any difference in the binary; in fact, reading the binary back we probably never get `self.Value = None` even if `self.ValueFormat = 0`. So this issue only happens when not going through the binary.

Tests are failing though. Debugging.

**Comment by behdad** [comment]
> > The `self.Value = None` doesn't make any difference in the binary; in fact, reading the binary back we probably never get `self.Value = None` even if `self.ValueFormat = 0`. So this issue only happens when not going through the binary.
> 
> Tests are failing though. Debugging.

False alarm. The change is harmless:
```diff
--- /home/behdad/fonttools/Tests/feaLib/data/ZeroValue_SinglePos_vertical.ttx
+++ /tmp/tmpcb8hdmeq/tmp1.ttx
@@ -39,6 +39,7 @@
             <Glyph value="B"/>
           </Coverage>
           <ValueFormat value="0"/>
+          <Value/>
         </SinglePos>
       </Lookup>
     </LookupList>
```

**Comment by behdad** [comment]
> reading the binary back we probably never get `self.Value = None` even if `self.ValueFormat = 0`.

I'm wrong there. So probably the former fix is needed.
