### ISSUE TITLE
pyftsubset documentation seems need to be updated

### ISSUE THREAD

**Issue by aminabedi68** [fonttools/fonttools#3149]
Hi

from pyftsubset documentation [here ](https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/subset/__init__.py)and [here](https://fonttools.readthedocs.io/en/latest/subset/index.html):

> –name-IDs=’*’
>        keep all ‘name’ table entries

the argument should be like: `–name-IDs=*` (without commas)

also for subset tables argument:

>Example:
>    –no-subset-tables+=FFTM
>            Keep ‘FFTM’ table in the font by preventing subsetting.

the table name should be between commas, like:  `–no-subset-tables+='FFTM'`

also these comma: `‘’` seems need to be replaced with the simple commas: `''` in all over of the documentation.

**Comment by behdad** [comment]
Thanks. We should remove all of those quotation marks.
