### ISSUE TITLE
[designspaceLib] floating point rounding causes "Cannot determine default source to look up family name"

### ISSUE THREAD

**Issue by rsms** [fonttools/fonttools#3154]
Say I have a designspace with axis mappings affecting the "default design location", like this:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<designspace format="5.0">
  <axes>
    <axis tag="wght" name="Weight" minimum="100" maximum="900" default="374.390244">
      <map input="100" output="100"/>
      <map input="400" output="428"/>
      <map input="900" output="900"/>
    </axis>
  </axes>
  <sources>
    <source filename="X-Thin.ufo" name="X Thin" familyname="X" stylename="Thin">
      <location><dimension name="Weight" xvalue="100"/></location>
    </source>
    <source filename="X-Regular.ufo" name="X" familyname="X" stylename="Regular">
      <location><dimension name="Weight" xvalue="400"/></location>
    </source>
    <source filename="X-Black.ufo" name="X Black" familyname="X" stylename="Black">
      <location><dimension name="Weight" xvalue="900"/></location>
    </source>
  </sources>
```

The default value is generated by glyphsLib in this case, but even if it's manually written to the most exact representation, the bug still occurs.

Now, if I run `designspaceLib.getStatNames(designspaceDoc: DesignSpaceDocument)` it calls `designspaceDoc.findDefault()` which tries to match the "default" to a source, doing the following:

```py
def findDefault(self):
  defaultLoc = self.newDefaultLocation()
  for sourceDescriptor in self.sources:
    if sourceDescriptor.getFullDesignLocation(self) == defaultLoc: # <—— bug!
      self.default = sourceDescriptor
      return sourceDescriptor
```

If `findDefault` returns `None` the call fails and a warning is logged (by `designspaceLib.getStatNames`)

```
WARNING:fontTools.designspaceLib.statNames:Cannot determine default source to look up family name.
```

The issue is this comparison:

```py
sourceDescriptor.getFullDesignLocation(self) == defaultLoc
```

If we print the value of `defaultLoc` it's clear what is going on:

```py
>>> defaultLoc
OrderedDict([('Optical size', 28.0), ('Weight', 400.0000001066667)])
```

Let's also print the source descriptors which are being tested for equivalence:

```py
{'Weight': 100.0}
{'Weight': 400.0}
{'Weight': 900.0}
```

Aha! `400.0 != 400.0000001066667`

The `newDefaultLocation` produces the default location like this:

```py
def newDefaultLocation(self):
  loc = collections.OrderedDict()
  for axisDescriptor in self.axes:
    loc[axisDescriptor.name] = axisDescriptor.map_forward(
      axisDescriptor.default)
  return loc
```

Which goes through `AxisDescriptor.map_forward`:

```py
def map_forward(self, v):
  from fontTools.varLib.models import piecewiseLinearMap
  if not self.map:
    return v
  return piecewiseLinearMap(v, {k: v for k, v in self.map})
```

Which uses `piecewiseLinearMap`:

https://github.com/fonttools/fonttools/blob/4.39.3/Lib/fontTools/varLib/models.py#L502-L519

Summary: Lookup of "default" design location fails because it goes through axis mapping using IEEE 754 floating point math, which has limited precision; the result is a computed value that is technically different from the actual source axis values.

**Comment by anthrotype** [comment]
I believe the expectation is that there is a explicit axis map for the default value, in your case it's missing hence it gets interpolated and might fail for the reasons you outlined

**Comment by rsms** [comment]
> Also, the source locations xvalue attributes are supposed to be definied in the internal design-space coordinate system (the "output" of the axis map elements), whereas it appears you are using user-space coordinates (the "input" in axis map, as used in fvar axis definitions)

Interesting! Thank you for the help.
I think Glyphs.app might have its UI backwards.

If I do this in Glyphs:

<img width="850" alt="Screen Shot 2023-06-06 at 08 29 58" src="https://github.com/fonttools/fonttools/assets/47046/c6174e2f-db56-4ce6-bf16-4c922f4ae98b">

_Notice how the "internal coordinates" say 400 and "external coordinates" say 350._

(how I read this: "Map 400 from your internal sources to 350. When user says 350 they actually get 400")

Then this is what designspace gets generated by fontmake:

```xml
<designspace format="5.0">
  <axes>
    <axis tag="wght" name="Weight" minimum="100" maximum="900" default="445.454545">
      <map input="100" output="100"/>
      <map input="400" output="350"/>
      <map input="900" output="900"/>
    </axis>
  </axes>
  <sources>
    <source filename="X-Thin.ufo" name="X Thin" familyname="X" stylename="Thin">
      <location><dimension name="Weight" xvalue="100"/></location>
    </source>
    <source filename="X-Regular.ufo" name="X Regular" familyname="X" stylename="Regular">
      <location><dimension name="Weight" xvalue="400"/></location>
    </source>
    <source filename="X-Black.ufo" name="X Black" familyname="X" stylename="Black">
      <location><dimension name="Weight" xvalue="900"/></location>
    </source>
  </sources>
```

Which is not correct.

However if I invert the mapping in Glyphs, by setting the internal value on the external axis and vice versa, like this:

<img width="850" alt="Screen Shot 2023-06-06 at 08 29 48" src="https://github.com/fonttools/fonttools/assets/47046/8e6782e8-7546-4401-88e2-a0ef8c9d1fc1">

(how I read this: "Map 350 from your internal sources to 400. When user says 400 they actually get 350")

Then—with the inverted mapping—the correct mapping is produced in the designspace:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<designspace format="5.0">
  <axes>
    <axis tag="wght" name="Weight" minimum="100" maximum="900" default="350">
      <map input="100" output="100"/>
      <map input="350" output="400"/>
      <map input="900" output="900"/>
    </axis>
  </axes>
  <sources>
    <source filename="X-Thin.ufo" name="X Thin" familyname="X" stylename="Thin">
      <location><dimension name="Weight" xvalue="100"/></location>
    </source>
    <source filename="X-Regular.ufo" name="X Regular" familyname="X" stylename="Regular">
      <location><dimension name="Weight" xvalue="400"/></location>
    </source>
    <source filename="X-Black.ufo" name="X Black" familyname="X" stylename="Black">
      <location><dimension name="Weight" xvalue="900"/></location>
    </source>
  </sources>
```

I'm probably just confused about what is what here.

Really what I'm trying to do is to make it so that when the user asks for wght=350 the outlines for wght=400 is used. When the user asks for wght=400, outlines for something like wght=430 is used. Essentially making everything a bit bolder around wght=400 as seen by the users.
