### ISSUE TITLE
[varLib instancer, L4] Applying a new default location shifts up weight of Bold, etc

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#3177]
I have a variable font with a wght range of 1–1000, with a default location of 700. More details about the project and designspace in [this related, previous issue](https://github.com/fonttools/fonttools/issues/3139).

I’m attempting to use the varLib Instancer to create a new default location at wght=400, for the desktop fonts only (leaving the webfonts without the added filesize). This is mostly working well, but I’ve noticed a small but meaningful issue: the upper end of the weight range gets shifted to become bolder than before. This deviates from my design intent, and also creates a difference between variable desktop and web fonts, plus between variable and static desktop fonts.

My best guess at a cause is that perhaps the AVAR table is interacting with the font outlines in an unexpected way, after the additional location is added. My weight axis is mapped in the 700–1000 range, and this issue seems to occur between 400 and 1000, and is most visible around 700. 

Here’s a before/after of setting the new default:

> <img width="1101" alt="image" src="https://github.com/fonttools/fonttools/assets/45946693/e7c15c29-5b15-46f3-a84b-6bce81020716">

Here’s a closer view of the two, overlapped:

> <img width="498" alt="image" src="https://github.com/fonttools/fonttools/assets/45946693/707d366a-a768-4f9b-8c85-cee81ae2e5ce">

I’ve come across this issue whether running the Instancer via Python or via a terminal command. For example, I can set the new default like this, and it produces the error:

```bash
fonttools varLib.instancer "AT-NameSansVariable.Trial.ttf" wght=1:400:1000
```

Version: FontTools 4.40.0

Thank you so much for taking a look!

### Test fonts

The following fonts show the before/after example of this. They are trial fonts, so feel free to use them as needed to reproduce and test this issue (or other varLib/fontTools stuff, if relevant).

[AT-NameSansVariable.Trial.ttf.zip](https://github.com/fonttools/fonttools/files/11805876/AT-NameSansVariable.Trial.ttf.zip)
[AT-NameSansVariable.Trial.varLibTest-dflt400.ttf.zip](https://github.com/fonttools/fonttools/files/11805877/AT-NameSansVariable.Trial.varLibTest-dflt400.ttf.zip)

**Comment by behdad** [comment]
Thanks Stephen! This is bad. And indeed quite probably avar related. I'll take a look.

**Comment by arrowtype** [comment]
Glad I could perhaps help uncover something here. Thanks so much for taking a look!

**Comment by behdad** [comment]
Humm. Issue persists even if I nuke the avar table.

**Comment by behdad** [comment]
> Oh, hmm. Did you remove AVAR before or after running the instancer? I could also test that out...

I tested both. Didn't seem to matter. So problem seems to be in gvar instancing. Investigating.

**Comment by behdad** [comment]
This is going to be tricky to debug. :))

**Comment by behdad** [comment]
I've reviewed the instancer.solver code now. Found a bug in it but that doesn't seem to fix the issue. :(

**Comment by behdad** [comment]
This is what's going on... It's something I always suspected we are doing wrong. Now I see we do... It's tricky to fix in the presence of `avar` mappings. I have to think about it more.

Imagine a font with current min/default/max of 100,700,1000. And new setting of 100,400,1000. The current `normalizeLocation` will calculate the new location for 700 to be +.33, whereas it should calculate +.5!  This is because 400 translates to -.5, so 700 will be normalized to -1,-.5,+1 and get +.33...

We need a special `normalizeLocation` that is aware of the "distance" between min/default/max, ie. the non-normalized values.  Then it will be clear that the distance from 400 to 700 is equal to 700 to 1000, and as such 700 should be normalized to .5, not .33...  I'm still trying to figure out the case where `avar` is present.

The wiring to get the non-normalized axis values into the code is also annoying at best.

**Comment by arrowtype** [comment]
Oh, wow, that does seem complex! 

I really appreciate you looking into this. I also appreciate that it is probably quite a ways beyond my mathematical abilities to figure out something like this. So, thank you for the work you do, and there’s no rush on my end (not that it really matters, but all the same). If it takes time before the L4 works in this case, that is understandable.

**Comment by behdad** [comment]
I have a fix!!

**Comment by behdad** [comment]
> I have a fix!!

Just need to fix tests.

**Comment by behdad** [comment]
@arrowtype Can you test https://github.com/fonttools/fonttools/pull/3179

**Comment by behdad** [comment]
Humm. Seems wrong with avar still :(((((((((.

**Comment by behdad** [comment]
> Humm. Seems wrong with avar still :(((((((((.

I think I fixed that.

**Comment by arrowtype** [comment]
Okay, checking the update now!

**Comment by arrowtype** [comment]
Amazing, it now seems to work perfectly for me!

I made a font with a new default of 400. Here’s the file size, somewhat larger:

<img width="764" alt="image" src="https://github.com/fonttools/fonttools/assets/45946693/e9c25850-353f-47d3-9477-8109ae27e752">

Here’s a font before and after setting the new default of 400 (and then putting both to 700). They look the same!

<img width="1461" alt="image" src="https://github.com/fonttools/fonttools/assets/45946693/71e1fe9d-565d-4298-8f05-24e7e0c9e510">

Overlapping a screenshot of the two seems to confirm that they are the same:

<img width="1317" alt="image" src="https://github.com/fonttools/fonttools/assets/45946693/e6c788c8-1e09-4a56-a654-19b4e54da453">

And they have exactly the same glyph widths. 

So, this seems to be solved, from what I can tell! 

I’ll keep poking at the newly instanced/defaulted font, and see whether any other issues are there. But, from my first visual check, it seems like you’ve cracked the issue.

Amazing work!

**Comment by behdad** [comment]
Thanks for checking!
