### ISSUE TITLE
Fonttools for aarch64

### ISSUE THREAD

**Issue by Ahd999** [fonttools/fonttools#3192]
Hi there,
Ive been compiling app through python for android and I'm getting error like,

fonttools/misc/beziertools.so" is for em_x86_64 (62) instead of em_aarch64 (183)

**Comment by anthrotype** [comment]
where do you get that error? how exactly are you installing fonttools on python for Android?

**Comment by Ahd999** [comment]
Python for android is a packaging library so it does the work for me, but good question tho, what this lib does is creates a fir containing all modules and they are installed through pip

**Comment by anthrotype** [comment]
if it's the precompiled binary wheel that is causing issues for some reasons (which we still haven't figured out), there's always the possibility of telling pip to install from the pure-python source distribution files by passing the `--no-binary` option to pip: e.g. `pip install --no-binary=fonttools fonttools`

**Comment by Ahd999** [comment]
Its not about precompiled wheel, actually it's about not installing the right precompiled wheel, i need a aarch64 wheel and my system is x86_64, that's what causing issue, anyways i feel its not something that can be solved on your side so you could close, also a humongous thanks to you for helping, thanks a lot
