### ISSUE TITLE
Docs say source name is required, implementation doesn't match

### ISSUE THREAD

**Issue by rsheeter** [fonttools/fonttools#3193]
https://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#source-element says name is required. https://github.com/cmyr/norad, used by fontc, adheres to this. However, designspaceLib apparently doesn't actually treat it as required, it generates names where it's missing ("when not present, designspacelib inserts "temporar_master#" or some such").

Could we please update either the docs or the implementation? Since existing projects observably rely on lack of name perhaps the docs is the wiser choice?

**Comment by rsheeter** [comment]
@justvanrossum, IIUC you are one of the owners of this?

**Comment by justvanrossum** [comment]
No, I don't own this. @LettError authored, @belluzj is a major contributor. Etc.

> Since existing projects observably rely on lack of name

Indeed, a quick look at some projects here and there reveal not a single one that has a `name` attribute on `<source>` elements.

Suggest changing the doc.

(Embarrassed to admit: I didn't really know `name` existed. Could be useful for Fontra, but it doesn't even attempt to read it.)

**Comment by anthrotype** [comment]
I'm ok to make source.name optional, but note that there is a pattern in designspaceLib (which we inherited when the original code was moved to fonttools) whereby basically every attribute (regardless of whether they are deemed "required" by the DS spec) is de-facto optional in the designspaceLib code that reads them? I.e. set to None when missing, and client is left to check for None-ness and wonder what to do with missing values

https://github.com/fonttools/fonttools/issues/1219
