### ISSUE TITLE
[feaLib] Compiling lookups with mixed rules?

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#3195]
In the course of debugging something else, I noticed that feaLib will compile lookup statements that include different rule types, (or least mixed single/multi-sub rules), promoting everything to be multiple substituion.

e.g., for this input:

```fea
lookup mixed {
    # single sub rules:
    sub [c d] by E;
    sub b by B;
    # ligature decomposition/multi sub rules:
    sub F by f f;
} mixed;

feature test {
    lookup mixed;
} test;
```

you will end up with a single type 2 lookup (the ttx for the feature/lookup tables looking like,)

```xml
<FeatureList>
  <!-- FeatureCount=1 -->
  <FeatureRecord index="0">
    <FeatureTag value="test"/>
    <Feature>
      <!-- LookupCount=1 -->
      <LookupListIndex index="0" value="0"/>
    </Feature>
  </FeatureRecord>
</FeatureList>
<LookupList>
  <!-- LookupCount=1 -->
  <Lookup index="0">
    <LookupType value="2"/>
    <LookupFlag value="0"/>
    <!-- SubTableCount=1 -->
    <MultipleSubst index="0">
      <Substitution in="F" out="f,f"/>
      <Substitution in="b" out="B"/>
      <Substitution in="c" out="E"/>
      <Substitution in="d" out="E"/>
    </MultipleSubst>
  </Lookup>
</LookupList>
```

Is this intentional? Is there any particular rationale for supporting this? Afdko produces an error for the same input.

**Comment by behdad** [comment]
To me this is desired behavior?

**Comment by cmyr** [comment]
I think this makes sense in a feature block where the mapping of rules -> lookups is generally loose, but in the context of a named lookup block it feels degenerate?

**Comment by khaledhosny** [comment]
https://github.com/fonttools/fonttools/pull/1133

**Comment by anthrotype** [comment]
> Is this intentional? 

yes, although it looks like the changes that Read Roberts agreed on never actually made it to the FEA spec:

https://github.com/adobe-type-tools/afdko/issues/224#issuecomment-537215163

**Comment by cmyr** [comment]
Okay thanks for the reference, I'll match the behaviour here.
