### ISSUE TITLE
Performance regression in 4.41.0?

### ISSUE THREAD

**Issue by imran-iq** [fonttools/fonttools#3213]
See: https://github.com/satbyy/go-noto-universal/issues/59

Using 4.41.0 the builds take longer than 6 hours, but using 4.40.0 it takes 20ish minutes. Not too sure what is going on since I am not familiar with either project but just thought I would point it out

**Comment by anthrotype** [comment]
Thanks for the report. However I don't immediately see anything related to pyftsubset in the changes since 4.40.0 that might have caused such regression:

https://github.com/fonttools/fonttools/compare/4.40.0...4.41.0

I'll keep investigating

**Comment by behdad** [comment]
Perhaps we can call the visitor only on certain tables. I'm guessing that it's expanding all glyf's here causing the slowdown.
