### ISSUE TITLE
cu2qu conversion of cubics with zero handles

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#3220]
"Zero handles" are considered bad drawing style, nonetheless they exist in some source files.

I noticed that converting such curves with cu2qu results in a quadratic offcurve point on top of the start or end point of the curve. Is this point really required? I think it would be cleaner if cu2qu optimized it away.

![cu2qu](https://github.com/fonttools/fonttools/assets/3185950/3192ecae-8890-4db0-af3e-79725b6ba62b)

I think the solution would be when at some point the intersection between lines AB and CD is calculated, and A == B as in the image on the left, the intersection should be calculated between lines AC and CD instead (the intersection point would thus be C). Analogous for the case C == D.

I tried to add some code to switch the reference points in the conversion algorithm, but failed to get an improved result.

**Comment by jenskutilek** [comment]
Demo UFOs: 
[cu2qu.zip](https://github.com/fonttools/fonttools/files/12130011/cu2qu.zip)

**Comment by behdad** [comment]
I'm leaning towards not doing anything specific here.

> I tried to add some code to switch the reference points in the conversion algorithm, but failed to get an improved result.

This is where you want to modify, if you didn't find it quite:
https://github.com/fonttools/fonttools/blob/bc5f6e1e32fa9f20048be6730d187c3ea14e3855/Lib/fontTools/cu2qu/cu2qu.py#L237C1-L237C1

**Comment by anthrotype** [comment]
it should be trivial to filter these duplicate nodes after cu2qu (of course ensuring the pruning maintains curves interpolatable)

**Comment by behdad** [comment]
Ah right. Interpolatibility is also a good reason to not do anything here.

**Comment by jenskutilek** [comment]
Removing the point in the quadratic outline changes the outline, because if it is present, there is an implied on-curve point halfway between the start point and the first actual off-curve point. When the point is removed, the start point _is_ the on-curve point.

I thought the creation of this off-curve point could be avoided by changing the way the cubic curve is analyzed, but maybe it is mathematically correct and should stay this way.

(Re. interpolatibility, in our sources such a construction is usually consistent in all masters.)

**Comment by justvanrossum** [comment]
To me this sounds like a source-level operation that would also be useful for otf. I wouldn’t expect it as part of cu2qu.

**Comment by behdad** [comment]
Do note that removing that point in the cubic form also changes the outline.

**Comment by jenskutilek** [comment]
Thank you for your opinions! Closing ...
