### ISSUE TITLE
[designspace] clarify structure of `<lib>` element

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#3224]
Is the `<lib>` element used in various parts of the designspace document expected to be an inline plist object? I think this makes sense (matching the `<lib>` element in GLIF files) but it is not stated explicitly in the spec, although the example does use plist syntax.

If this is *not* the case, then I think it would be very helpful to impose some set of constraints around what the allowed structure is for the lib; since XML does not provide much semantic guidance (for instance a tag named `<string>` does not mean anything special in XML) the `<lib>` is very difficult to interpret currently.

Can we improve this, by enforcing that if present the `<lib>` must always be a plist dict?

**Comment by anthrotype** [comment]
> enforcing that if present the <lib> must always be a plist dict?

yes, it's meant to mimic the GLIF's `<lib>` element so it should be interpreted as a plist embedded in the larger xml document. We can and should make that explicit in the designspace spec.

**Comment by behdad** [comment]
> > enforcing that if present the  must always be a plist dict?
> 
> yes, it's meant to mimic the GLIF's `<lib>` element so it should be interpreted as a plist embedded in the larger xml document. We can and should make that explicit in the designspace spec.

See https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#lib
