### ISSUE TITLE
CFF2: interpret empty glyphs from non-default sparse master as missing, like with gvar

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#3233]
in https://github.com/fonttools/fonttools/pull/2082, @justvanrossum added support in varLib for interpreting empty glyphs as missing (thus not participating) if they occur in non-default sparse masters, but this only works for TrueType-flavored VFs:

https://github.com/fonttools/fonttools/blob/7fce3444046485846118c1eda86d4ed0a541a94c/Lib/fontTools/varLib/__init__.py#L320-L326

Ideally we would do the same thing for variable CFF2 fonts, but I am not familiar enough with the varLib.cff module to know exactly how/where this change should best be placed.

If one attempts to use this pattern (default master has a non-empty glyph, non-default master has an empty glyph with the same name) one would get the following error:

```
fontTools.varLib.errors.VarLibCFFPointTypeMergeError: Glyph '.notdef': 'rlineto' at point index 4 in master index 1 ...
```

Maybe @behdad or @justvanrossum can help?

**Comment by behdad** [comment]
Good news is that it's supposed to work from glancing at the code:
```
def merge_charstrings(glyphOrder, num_masters, top_dicts, masterModel): 
 
    vsindex_dict = {} 
    vsindex_by_key = {} 
    varDataList = [] 
    masterSupports = [] 
    default_charstrings = top_dicts[0].CharStrings 
    for gid, gname in enumerate(glyphOrder): 
        all_cs = [_get_cs(td.CharStrings, gname) for td in top_dicts] 
        if len([gs for gs in all_cs if gs is not None]) == 1: 
            continue 
        model, model_cs = masterModel.getSubModel(all_cs) 
```

**Comment by anthrotype** [comment]
well.. it does not as I have shown above. I get an VarLibCFFPointTypeMergeError if I try to pass such a sparse empty glyph setup. That code you linked, _get_cs, returns None if the glyph is not present in a master; here it is present, but empty

**Comment by behdad** [comment]
> well.. it does not as I have shown above. I get an VarLibCFFPointTypeMergeError if I try to pass such a sparse empty glyph setup. That code you linked, _get_cs, returns None if the glyph is not present in a master; here it is present, but empty

Yeah. We just need to change `_get_cs` to filter out empty (for CFF2) or just endchar (for CFF1) and return None.

**Comment by anthrotype** [comment]
right.. detecting when a charstring is empty is what I couldn't figure it out. Checking its `program` length doesn't work because it has to be decompiled or something
