### ISSUE TITLE
[merger] Cursive attachment merging fails when all anchors are NULL

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#3247]
Carried over from https://github.com/googlefonts/fontmake/issues/1022.

When all anchors in all masters are of the form:

```
    pos cursive _0 <anchor NULL> <anchor 25 0>;
```

the merger creates an ExitEntryAnchor like this:

```python
        rec = ot.EntryExitRecord()
        rec.EntryAnchor = ot.Anchor()
        rec.EntryAnchor.Format = 1
        rec.ExitAnchor = ot.Anchor()
        rec.ExitAnchor.Format = 1
        self.EntryExitRecord.append(rec)
```

This means that deep inside `mergeThings`, when trying to merge the entry anchors, we hit this code path:

```python
            if allNone(lst):
                if out is not None:
                    raise FoundANone(self, got=lst)
```

All entry anchors are None, but the target entry anchor is an `Anchor` so merging fails.

**Comment by simoncozens** [comment]
Confirmed, it works at 56731a9f1 but not at b14a29c35.

Bad Behdad. ;-)

**Comment by anthrotype** [comment]
how does one reproduces exactly? could you push a failing test case in varLib/merger_test.py so Behdad can fix it

**Comment by simoncozens** [comment]
Will do. I could probably fix it myself, TBH; it just needs a custom merger for EntryAnchor/ExitAnchors.
