### ISSUE TITLE
ERROR: Invalid requirement: '[ufo,lxml,woff,unicode,pathops]'

### ISSUE THREAD

**Issue by fmotion1** [fonttools/fonttools#3266]
For some reason I'm getting an "Invalid Requirement" error when trying to install with the following extras: `[ufo,lxml,woff,unicode,pathops]`. What am I doing wrong?

I'm using `Python 3.11.5`

Thanks for any enlightenment.

**Comment by anthrotype** [comment]
I just tried locally and worked for me. I did

```
$ python3.11 -m venv .venv
$ source .venv/bin/activate
$ pip install fonttools[ufo,lxml,woff,unicode,pathops]
[...]
Installing collected packages: unicodedata2, brotli, appdirs, zopfli, skia-pathops, six, lxml, fonttools, fs
Successfully installed appdirs-1.4.4 brotli-1.0.9 fonttools-4.42.1 fs-2.4.16 lxml-4.9.3 six-1.16.0 skia-pathops-0.8.0 unicodedata2-15.0.0 zopfli-0.2.2
```

can you please paste the full pip install command?

**Comment by fmotion1** [comment]
It was my fault. The command I used had a spelling error. Sorry about that.
