### ISSUE TITLE
[designspace] Where to store varible font-specific data

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#3272]
It is common to set different family name and other related name data on variable fonts and static instances, but looking into DesignSpace v5, I see no designated place to store these.

There is `<variable-font>` but it seems to be designed mainly for creating subsets of designspace (to build a variable font, all axis settings needs to be duplicated as any missing axis will be sliced at its default value, if my reading of documentation is correct) and it does not seem to have any of `instance` attributes other than `name` and `filename`.

Should `<variable-font>` be extended to be able to handle this, or this not what it was designed for?

**Comment by khaledhosny** [comment]
I think this is related to https://github.com/fonttools/fonttools/issues/2608, we can probably support the new lib keys in both `<instance>` and `<variable-font>`, if `<variable-font>` is the right place for this.

**Comment by belluzj** [comment]
Yes that would make sense I think

**Comment by anthrotype** [comment]
> that would make

what exactly would make sense?

Not clear to me why the current `<variable-font>` element is not suitable for this. Is the supposed duplication of the per-VF axis settings the main concern?

my understanding is if no `<variable-font>` elements are provided, then the DS is intented to build only _one_ implicit VF target. But if one or more such `<variable-font>` elements are explicitly provided _all_ of those get built.

**Comment by anthrotype** [comment]
on rereading this I see now, you're proposing to add additional attributes to variable-font element for setting different family name and other related name data. Sure, we can do that. Or we can use the lib...

**Comment by belluzj** [comment]
I wanted to say the proposal from Colin to have <lib> fontinfo data for instances (and so for variable fonts too) would make sense to me.

In splitVariableFonts, when making a per-VF designspace, the lib of that designspace is the lib of the <variable-font> element mixed with the lib of the original full designspace that we're splitting. So it means the full designspace V4 representing only 1 VF can also have in its global lib the same fontinfo data.

**Comment by anthrotype** [comment]
> fontinfo data for instances (and so for variable fonts too)

but instances (at least for the static instance UFO build pipeline) do correspond to UFOs with their own fontinfo.plist, and it's the UFO spec that defines the meaning of those attributes. For variable-fonts there is not such correspondance.. It would feel weird to link to UFO spec for VF attributes.

**Comment by belluzj** [comment]
That's the discussion Colin was having in the other issue: https://github.com/fonttools/fonttools/issues/2608

I'm not sure it's that weird to rely on the UFO spec for the meaning of these fields; sure the UFO and designspace specs are two separate things but the UFO spec is good at describing this fontinfo stuff, why not reuse it?

**Comment by anthrotype** [comment]
hm maybe we could restrict to support only the fontinfo fields that start with openType...

**Comment by guidoferreyra** [comment]
I mentioned a similar situation here: https://github.com/fonttools/fonttools/issues/2916

**Comment by colinmford** [comment]
My intention with #2608 was reducing the amount of adjusting I need to do via a build script after those UFOs are generated, I would still love fontinfo.plist-level manipulation of individual instances there. I grant that it is not _as_ useful for the `<variable-font>` section because the relationship to a UFO is not 1-to-1, but certain non-interpolatable values may be useful to set directly in the same manner. Particularly names.

I would still love to have the same amount of control over things like `familyName` and `styleName`, etc that I already have with `<instance>` element, so that at least may be a starting point.

**Comment by colinmford** [comment]
Similar to #2606
