### ISSUE TITLE
OpenType Tag padding

### ISSUE THREAD

**Issue by bramstein** [fonttools/fonttools#3280]
I discovered a strange discrepancy in the OS/2 `achVendID` value between a font generated through the fontmake toolchain (fontmake -> ufo2ft -> fontTools) and other font editors. When the vendor ID is shorted than 4 characters, fontTools pads it with `null` (0x00) bytes, whereas other editors pad the value with a space (0x20).

The OpenType specification has this to say on padding (emphasis mine):

> A Tag value is a uint8 array. Each byte within the array must have a value in the range 0x20 to 0x7E. This corresponds to the range of values of Unicode Basic Latin characters in UTF-8 encoding, which is the same as the printable ASCII characters. As a result, a Tag value can be re-interpreted as a four-character sequence, which is conventionally how they are referred to. Formally, however, the value is a byte array. When re-interpreted as characters, the Tag value is case sensitive. It must have one to four non-space characters, _padded with trailing spaces_ (byte value 0x20). A space character cannot be followed by a non-space character.

Based on that, I believe the fontTools behaviour to be incorrect. It appears the [vendor ID is packed](https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/ttLib/tables/O_S_2f_2.py#L70) with the following settings:

```python
	achVendID:     4s      # font vendor identification
```

The [Python documentation for `struct.pack`](https://docs.python.org/3/library/struct.html) explains that values are padded with `null` bytes:

> For packing, the string is truncated or padded with null bytes as appropriate to make it fit. 

There are a couple of other places in the code where this happens from what I can tell:

* The `sfnt` table directory entries
* The `fvar` tags
* The `sbix` glyph data
* The `meta` table

What is the preferred fix here (if any)? I could open a PR to fix just the vendor ID (by pre-padding the value with a space), but this feels like a larger problem.

**Comment by anthrotype** [comment]
Thanks. I think only the vendor id can ever be smaller than 4 bytes, the other tags are all 4 bytes so need no padding. 
Yes please send a PR to pad vendor ID with trailing spaces

**Comment by anthrotype** [comment]
it's better if ufo2ft ensures the achVendID gets padded to 4 bytes with spaces. It's a easy fix, I can take care of it thanks

**Comment by bramstein** [comment]
Thanks!
