### ISSUE TITLE
[varLib.instancer] hhea metrics not matching typoMetrics when instancing VFs

### ISSUE THREAD

**Issue by vv-monsalve** [fonttools/fonttools#3297]
We are using variable vertical metrics in a super-VF from which we are instantiating 45 different families (static and VFs) through `varLib.instancer`.  This allows us to proportionally adjust the metrics of the instantiated families based on the provided axis positions.

This is working well for the `OS/2.sTypo` metrics both in the static and variable fonts. However, the `hhea` metrics ~~in the variable font~~ are still using the default values instead of adjusting proportionally.

**Resources and steps needed to reproduce**

This is happening with: fonttools 4.42.1. and also after updating it to fonttools 4.43.1.

Recipe to one of the instantiated fonts
````
fonttools varLib.instancer path/to/orig-font SPED=25 YEXT=520 wght=100:400 slnt=18 -o path/to/instantiated-font
````

files
[varLib-test-fonts.zip](https://github.com/fonttools/fonttools/files/12864141/varLib-test-fonts.zip)

**Comment by simoncozens** [comment]
I'm not sure I understand this. In your example files, all statics have the same hhea metrics:

```
    <ascent value="1275"/>
    <descent value="-375"/>
    <lineGap value="0"/>
```

and the instantiated variable also has these same values. So that looks correct to me. Which metrics were you thinking of, and what values do you think they should have?

One thing to note is that the MVAR table does *not* specify a way to vary `hhea.ascent` and `hhea.descent`, only the OS/2 values, because Microsoft.

**Comment by anthrotype** [comment]
> One thing to note is that the MVAR table does not specify a way to vary hhea.ascent and hhea.descent, only the OS/2 values, because Microsoft.

https://learn.microsoft.com/en-us/typography/opentype/spec/mvar

I just checked the spec and was surpised that this is the case..
Note though that 'vasc' (equivalent for 'hasc' for vertical ascender) does mention vhea.ascent. I think the instancer could/should update hhea ascent/descent/lineGap when in the input font they do match the respective OS/2 metrics.

**Comment by vv-monsalve** [comment]
> I'm not sure I understand this. In your example files, all statics have the same hhea metrics:

Ugh, yes, then they are bad too.

> Which metrics were you thinking of, and what values do you think they should have?

To match the OS/2 ones.

```
    <sTypoAscender value="1452"/>
    <sTypoDescender value="-525"/>
    <sTypoLineGap value="0"/>
```

> I think the instancer could/should update hhea ascent/descent/lineGap when in the input font they do match the respective OS/2 metrics

This would be ideal

**Comment by vv-monsalve** [comment]
> I think the instancer could/should update hhea ascent/descent/lineGap when in the input font they do match the respective OS/2 metrics

@anthrotype This would solve a clipping issue we are currently receiving in Word Mac. Do you think this could be adopted soon?

**Comment by anthrotype** [comment]
it should be easy to do, I'll do that now

**Comment by anthrotype** [comment]
@vv-monsalve I merged https://github.com/fonttools/fonttools/pull/3337 and will cut a release later today

**Comment by vv-monsalve** [comment]
Awesome,@anthrotype. Thanks!
