### ISSUE TITLE
[subset] WISH: Support glyphtext for defining subsets

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#33]
From Adam:

Currently, pyftsubset allows to specify a text string with the --text option and a list of space-separated glyph names as direct arguments. 

The Perl ttfsubset tool written by Martin Hosken (SIL) allows to also specify an external text file where the subset definition is stored. That's very handy. 

But I'd like to propose to go a slightly different route: 

In FontLab apps, we're using what I call "glyphtext", which is a way to provide a text file or string which uses normal UTF-8 characters to refer to glyphs which have a Unicode codepoint assign, but provides several escapement methods to refer glyphs as well: 

a) Escaped glyphname: /nnnn (e.g. /adieresis or /a.smcp), i.e. the slash followed by the glyphname.

b) Escaped CID*: /DDD (e.g. /123 or /5436), i.e. the slash followed by a decimal number corresponding to the CID (character ID). This is supported in CID-keyed fonts only.

c) Escaped glyph ID*: \gDDD (e.g. \g123 or \g0), i.e. the backslash followed by the letter g and followed by a decimal number representing the GID (the SFNT glyph ID).

d) Escaped Unicode codepoint: \XXXX or \uXXXX (e.g. \20ac or \u20AC), i.e. the backlash followed by an optional letter u and followed by the hexadecimal Unicode codepoint — for glyphs that have a Unicode codepoint assigned. XXXX can be 4 or 5 hexadecimal digits; XXXX is case-insensitive.

e) Unescaped character: a single Unicode text character (e.g. A, Ä, Ą, Я) — for glyphs that have a Unicode codepoint assigned. This is the preferred method for glyphs that have a Unicode codepoint assigned.

f) To input the actual slash text character /, the user can enter // (i.e. two slashes). Those two slashes are treated like one unescaped character. To input the actual backslash text character \, the user can enter \ (i.e. two backslashes). Those two backslashes are treated like one unescaped character.

*) These are currently not supported by FontLab apps but will be supported in future. 

Each glyph in the glyph string can be represented using any character escaping convention method (discussed above). When an an escaped Unicode codepoint or an escaped glyphname is followed by an unescaped text character, the unescaped text character must be separated by a space, which does not count as a text character. Any space between two unescaped characters or between two escaped items is treated as a text character.

Examples
A/Aacute V means a sequence of three glyphs: A, Aacute, V
/A/Aacute/V means the same
A V means s a sequence of three glyphs: A, space, V
/Aacute /V means a sequence of three glyphs: Aacute, space, V

To implement this method, we'd need a fontTools parser module for such files which would take the glyphtext in and produce a list of glyph references out. Glyphtext (aka "FontLab text escapement") is also used by other applications including RoboFont. 

So my proposal would be that the user could specify: 
--text=%text string%
--text--file=%path to text file%
--glyphtext=%glyphtext string%
--glyphtext-file=%path to glyphtext file%

At FontLab, we're committed to documenting, supporting and publicizing glyphtext. (There will be an official spec published somewhere soon. But the above description pretty much IS the official spec :) ).

**Comment by brawer** [comment]
This seems to be mostly handled by #113. If anyone disagrees, free to re-open this bug.
