### ISSUE TITLE
Fix `SyntaxWarning` in Python 3.12

### ISSUE THREAD

**Issue by bersbersbers** [fonttools/fonttools#3311]
The line containing `(¯\_(ツ)_/¯)` makes Python issue a `SyntaxWarning` here:
https://github.com/fonttools/fonttools/blob/5cd2b1cc50d8714a7b6a84f167983767e24d2761/Lib/fontTools/cffLib/specializer.py#L44C1-L45C1

See also https://docs.python.org/3/whatsnew/3.12.html#other-language-changes

**Comment by khaledhosny** [comment]
Should use 🤷 instead

**Comment by anthrotype** [comment]
do it!
