### ISSUE TITLE
[TTX] head table flags bit1 disappearing when converting back to TTF

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fonttools#3312]
process:
1. `ttx font.ttf`
2. modify a value in the glyf table
3. `ttx font.ttx`

head table before:
`<flags value="00000000 00001011"/>`
head table after:
`<flags value="00000000 00001001"/>`

For what I tested, it happens only for italic fonts wether I modify the TTX file or not. So my guess is that there is a reason for that but I don't it and the designer of the font doesn't like that data was lost.

-- 
I did this to fix this issue:
```
vttLib.VTTLibInvalidComposite: Component 1 in 'uacute' has wrong x offset: expected 309, found 305. (Bold Italic)
vttLib.VTTLibInvalidComposite: Component 1 in 'uacute' has wrong y offset: expected -5, found -9. (Bold Italic)
vttLib.VTTLibInvalidComposite: Component 1 in 'ugrave' has wrong x offset: expected 309, found 305. (Bold Italic)
vttLib.VTTLibInvalidComposite: Component 1 in 'ugrave' has wrong y offset: expected -5, found -9. (Bold Italic)
```

Files to replicate the process: 
[files.zip](https://github.com/fonttools/fonttools/files/13164044/files.zip)

**Comment by anthrotype** [comment]
https://learn.microsoft.com/en-us/typography/opentype/spec/head

> Bit 1: Left sidebearing point at x=0 (relevant only for TrueType rasterizers)

it means your font is claiming one thing ("left sidebearing point at x=0") but it's doing something else. When recomputing the bounding boxes upon compile, fonttools detects that some glyphs's left sidebearings are not actually at 0 and if any glyph's bbox.xMin != lsb, then the bit should _not_ be set.

If you want fonttools not to touch that, try use `ttx -b`, it should not attempt to recalc the bounding boxes but use the value from the .ttx file as is

**Comment by RosaWagner** [comment]
thanks a lot for that explanation :)
