### ISSUE TITLE
[instancer] --update-name-tables unnecessarily strict?

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#3318]
In order to update the name tables, the instancer looks in the STAT table and expects to see an entry for every axis and every axis value which is being instantiated. I wonder if this is overly strict; my feeling is that if there is an axis which doesn't affect style naming at all, it does not need to be in the STAT table, and therefore the instancer should be able to ignore that axis when it comes to generating the style names. But maybe there is a good reason for this behaviour.

**Comment by anthrotype** [comment]
> an axis which doesn't affect style naming at all

IIUC, are you suggesting that if an axis is not defined in STAT it should be ignored when updating the name table?
I thought STAT requires that all fvar axis have a corresponding design axis.

> In a font with an 'fvar' table, this value must be greater than or equal to the axisCount value in the 'fvar' table.

**Comment by simoncozens** [comment]
OK. But the same argument applies for axis values.

**Comment by anthrotype** [comment]
if STAT doesn't contain some axis values at the new desired default location, the update_name_table method would not know what to put there. Should it skip those and leave them emtpy? Or make something up based on the coordianate value itself? The safest was to expect them all to be there. /cc @m4rc1e the author of the code

**Comment by simoncozens** [comment]
> Should it skip those and leave them emtpy?

I suppose one way to see it would be that if there any values listed for an axis, then trying to instantiate the name table for a value which is not listed (e.g. "wght=650") should fail, because we're expecting a name but there isn't a valid one; but if the axis is listed but there are no axis values, then it's an axis which doesn't affect naming so just ignore it.

**Comment by anthrotype** [comment]
> if the axis is listed but there are no axis values, then it's an axis which doesn't affect naming so just ignore it.

I see what you mean know, makes sense. I'm fine with relaxing it that way.

**Comment by m4rc1e** [comment]
Agree with relaxing if there are no axis values.
