### ISSUE TITLE
[varLib.instancer] adding a new default location seems to flip some contours

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#3320]
I’ve noticed that when building a variable font and using the varLib.instancer to add a new default location, it causes an unexpected "flipping" of the dots at the lower end of my weight range. Here’s a video capture of variable fonts before versus after adding a new default of wght=400:

https://github.com/fonttools/fonttools/assets/45946693/d00440df-1a2c-4dbb-889b-b9a921960b0c

They variable fonts are exactly the same, except for adding that new default with [this script](https://gist.github.com/arrowtype/9fefe9633cae500bbaf0000230f6a3ed).

Extra notes:
- This is with `fonttools==4.43.1`
- Possibly related to using support layers / sparse sources.
- Possibly related to changes made for https://github.com/fonttools/fonttools/issues/3291

[ArrowType-NameSans-v1-Trial-for_FontTools_Issue_Report-2023_11_01.zip](https://github.com/fonttools/fonttools/files/13227764/ArrowType-NameSans-v1-Trial-for_FontTools_Issue_Report-2023_11_01.zip)

I can email fuller sources, etc, if that is helpful. Thank you!

**Comment by behdad** [comment]
Thanks. I'll debug. That's probably still a bug in the solver.

**Comment by behdad** [comment]
Weird. I cannot reproduce using the command-line instancer:
```
$ ./fonttools varLib.instancer AT-NameSansVariable.Trial.ttf wght=1:400:1000
$ hb-view AT-NameSansVariable.Trial-partial.ttf . --variations=wght=160 | display
```
shows the same result as the original font.

@arrowtype can you try reproducing as above?

**Comment by arrowtype** [comment]
Oh, hmm. Thank you for checking it! Maybe I have FontTools installed from an early dev branch... I'll check again when I'm back at my computer in a couple of hours!

**Comment by arrowtype** [comment]
Dang – indeed, it was something weird with my specific fonttools/setup in that venv. After I removed the venv and made a new one, then re-installed the latest FontTools, the instancer is working just as expected, and I am no longer getting the contour reversing in those dots. 

Sorry for the false alarm, and thank you for helping me debug that!
