### ISSUE TITLE
otLib & varLib use different orderings for classes in a GlyphClass

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#3321]
@behdad helped track down something that was causing me a bunch of confusion:

When otLib builds a Glyph class, it orders the classes by reversing `(len(class), class)`: https://github.com/fonttools/fonttools/blob/c3d87683461e04ebdd861b84d2803788fbfe0ce4/Lib/fontTools/otlLib/builder.py#L2677

but when varLib performs the merge, it reorders the classes using the `classifyTools` module, which sorts based on `(-len(class), class)`: https://github.com/fonttools/fonttools/blob/c3d87683461e04ebdd861b84d2803788fbfe0ce4/Lib/fontTools/misc/classifyTools.py#L77

Which causes the order to change. This also means that fontmake will use a different sort order based on whether or not it is building a variable font.

It would be nice if these were consistent. I probably prefer the second approach (large classes first, then lexicographic order on the glyphs) but I don't have strong feelings about that; but my life would be easier if this was at least consistent.

**Comment by behdad** [comment]
> It would be nice if these were consistent. I probably prefer the second approach (large classes first, then lexicographic order on the glyphs)

+1.
