### ISSUE TITLE
[instancer] Allow not specifying any of `min:default:max` values.

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#3322]
It would be nice to be able to just change default, or just change max, etc, without having to find and spell out the rest.

Proposed syntax: allow not specifying any of them. Ie. `wght=:500:` will change the default only. `wght=::700` will change the max only. `wght=300::700` is the same as `wght=300:700` in which the default is not changed.

**Comment by behdad** [comment]
cc @arrowtype

**Comment by arrowtype** [comment]
That sounds nice! I could see it being especially useful, perhaps, for adjusting a collection of fonts (e.g. if a font publisher wanted to add a wght=400 default to a bunch of variable fonts).

> `wght=::700` will change the max only.

I would somewhat expect `wght=:700` to work as well (with only a single colon). Would that make sense, or not really?

**Comment by behdad** [comment]
> I would somewhat expect `wght=:700` to work as well (with only a single colon). Would that make sense, or not really?

Good point. I'll make that work as well.
