### ISSUE TITLE
Iterating the glyf table does not expand Glyph

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#3326]
This had me seriously confused, so I’m not sure if it intended behaviour:

```py
font = TTFont("tests/data/IBMPlexSans-Regular.ttf")
[
    len(ttglyph.program.getBytecode())
    for ttglyph in font["glyf"].glyphs.values()
    if hasattr(ttglyph, "program")
]
```

will always return `[]` because the `_g_l_y_f.Glyph` object is not expanded when using `.glyphs.values()`.

But

```py
len(font["glyf"]["A"].program.getBytecode())
```

will return the actual length of the program, because `__getitem__` auto-expands the `Glyph` object.

**Comment by anthrotype** [comment]
yes, `__getitem__` auto expands, but you are iterating over the inner `.glyphs` dictionary, not the `glyf` table itself. Try to iterate over the latter's `keys()` (I think it does not have a `.values()` method of its own yet, we may add one if you need), and then auto-expand them as you get them with `glyph = glyf[glyphName]`

**Comment by jenskutilek** [comment]
Thank you! Works for me.
