### ISSUE TITLE
table_O_S_2f_2.getCodePageRanges() can raise an AttributeError with fonttools=4.44.1

### ISSUE THREAD

**Issue by Lucas-C** [fonttools/fonttools#3334]
Hi!

I spotted this in https://github.com/py-pdf/fpdf2/issues/1021.

We have a couple of cases in our test suite where this error is raised with `fonttools=4.44.1`:
`AttributeError: 'table_O_S_2f_2' object has no attribute 'ulCodePageRange1'`

Could this be caused by a backward compatible change in `fonttools`,
or is it now expected that user code handle those errors?

**Comment by khaledhosny** [comment]
I think we need to add OS/2 table version checks to the code from #3328, since not all versions of the table has these two fields.

**Comment by anthrotype** [comment]
> I think we need to add OS/2 table version checks

@khaledhosny can you please take care of this? Thanks

>  just downgrade to v4.44.0 and wait for the fix by another version?

yes please

**Comment by anthrotype** [comment]
In the meantime I have just "yanked" 4.44.1 from PyPI so pip should no longer install that (unless one specifically requests it).
The 4.44.2 deployment failed for unrelated reasons so it has not been published to PyPI (despite being shown in the Github releases). I will push a bugfix 4.44.3 release once Khaled pushes the fix. Or I can do it later today myself, just le me know.

**Comment by khaledhosny** [comment]
Who knew there are that many fonts with OS/2 table version 0 out there.

**Comment by anthrotype** [comment]
probably old system fonts

**Comment by Lucas-C** [comment]
Thank you for fixing this in a new release! 👍
