### ISSUE TITLE
Move `LerpGlyphSet` somewhere more accessible?

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#3361]
Currently in `interpolatable.py` I have a `LerpGlyphSet` that takes two glyphsets and draws shapes linearly interpolated between the two:

https://github.com/fonttools/fonttools/blob/207a67e7d5a2d48072e57ddf2254c44dd5b3dd10/Lib/fontTools/varLib/interpolatable.py#L362-L391

I think this belongs somewhere more prominent. Perhaps not `pens`, but `misc`?

**Comment by anthrotype** [comment]
maybe move it to https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/ttLib/ttGlyphSet.py ?

**Comment by behdad** [comment]
Works for me. Thanks. Will send a PR.
