### ISSUE TITLE
[designspaceLib] sources should not allow anisotropic location

### ISSUE THREAD

**Issue by LettError** [fonttools/fonttools#3369]
This [diagram for the designspace format](https://fonttools.readthedocs.io/en/latest/_images/v5_class_diagram.png) indicates it is possible to allow anisotropic locations for sources.

![no_anisotropy_for_sources](https://github.com/fonttools/fonttools/assets/1243961/5582f335-6a33-4c77-ac01-55ff785c50d9)

- Mutatormath does not support anisotropic locations for **sources**. (it does for instances)
- It would surprise me if Varlib supports it (but love to hear)
- I can't think of any practical applications for this (but love to hear)
- If there are no strong arguments in favor, we could remove it from the requirements?

**Comment by anthrotype** [comment]
> It would surprise me if Varlib supports it (but love to hear)

no varLib doesn't support those

**Comment by belluzj** [comment]
Yes I discussed it with Erik by email, and I'll update the diagram. Just FYI for another time it's a PlantUML diagram using this tool: https://plantuml.com/class-diagram

The source code of the diagram is in the repo here: https://github.com/fonttools/fonttools/blob/main/Doc/source/designspaceLib/v5_class_diagram.puml

There's a nice VS Code extension with live preview of the PNG as you edit the code: https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml
