### ISSUE TITLE
fixedToFloat incorrect for F2DOT14?

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#3381]
It's really hard to grok all the TrueType internals, so forgive me if I'm wrong.

The [OTSpec](https://learn.microsoft.com/de-de/typography/opentype/spec/otff) says F2DOT14 is a signed, 2's complement integer and an unsigned fraction.

It seems the functions from `fontTools.misc.fixedTools` don't take the signedness into account?

```py
from fontTools.misc.fixedTools import *
fixedToFloat(0b1100000000000000, 14)  # 0xC000 -> 3.0 -- should be -1.0?

# Examples from the OTSpec
fixedToFloat(0x7fff, 14)  # 1.99993896484375, OK
fixedToFloat(0x7000, 14)  # 1.75, OK
fixedToFloat(0x0001, 14)  # 6.103515625e-05, OK
fixedToFloat(0x0000, 14)  # 0.0, OK
fixedToFloat(0xffff, 14)  # 3.99993896484375 -- should be -0.000061
fixedToFloat(0x8000, 14)  # 2.0 -- should be -2.0
```

**Comment by jenskutilek** [comment]
Maybe I'm using it wrong ...

I want to write TrueType assembly that sets the projection vector to the negative y-axis. `SPVFS[]` (Set Projection Vector From Stack) takes two F2DOT14 arguments for x and y components of the vector. The length of the vector must be 1.

Am I mistaken that I need to pass -16384 or 0xC000 to the instruction? It seems to work in VTT.

```
PUSHB[]
0
PUSHW[]
-16384
SPVFS[]
```

which is compiled to

```
B0    PUSHB[000]
00    0
B8    PUSHW[000]
C000  -16384
0A    SPVFS[]
```

Can fixedToFloat not be used to validate my number?

It doesn't help that FontValidator complains about the 0xC000 as "E6053 Value exceeds capacity of 2 byte number" either, and the help file doesn't work anymore. All very confusing.

**Comment by anthrotype** [comment]
you have to signed python integer as the input. Normally fixedToFloat is called from the result of struct.unpack(">h",...) 

for -1.0, that would be floatToFixed(-1.0, 14) => -16384

the value 0b1100000000000000 or 0xC000 does not include a sign so it's interpreted as positive and as such it would exceed the F2Dot14 bounds -2.0<=x<2.0

**Comment by anthrotype** [comment]
> I need to pass -16384 or 0xC000 to the instruction?

you want to use -16384 (which means -1.0 when decoded as F2Dot14)

**Comment by anthrotype** [comment]
don't confuse the underlying bytes with the python integer value representing them; the same bytes can be interpreted as a signed or unsigned integer, a fixed point number, a float, etc. The fact that a python int literal can be written with 0b or 0x notation means nothing, it still has an implicit sign just like its usual decimal representation.

**Comment by jenskutilek** [comment]
Thank you! I think I get it now :)
