### ISSUE TITLE
Woff2 file has different checksum each time it is saved. 

### ISSUE THREAD

**Issue by inklinea** [fonttools/fonttools#3385]
I'm using fonttools 4.29.1 with python 3.10.12.
Ubuntu 22
``
For this simple code: 

```
font_object = TTFont(ttf_filepath)
font_object.flavor = 'woff2'
font_file_disk = f'/filepath/{font_name}.woff2'
font_object.save(font_file_disc)
```
The checksum of the woff2 file changes every time the same font is saved.
I not sure why this is ? 

At a guess I think it might be due to the way Brotli compresses to woff2, and the compression although valid is not the exactly the same each time ? 

I'm converting the woff2 font into a base64 @font-face for use on the web.

If I can have the same base64 string each time, it gives a simple way to check if the document already contains this font (even if the name is different) 

Many thanks for any advice.

**Comment by Lorp** [comment]
More likely to be the timestamps in the `head` table.

**Comment by Lorp** [comment]
If you use the command line tool [woff2_compress](https://github.com/google/woff2), the resulting WOFF2 file will be identical each time.

**Comment by inklinea** [comment]
Fantastic, thanks for you response.

All I needed was 

`font_object.recalcTimestamp = False`

and the problem is solved :)

**Comment by Lorp** [comment]
Great!
