### ISSUE TITLE
ttx converts otf font to ttf via ttx file - how to get otf?

### ISSUE THREAD

**Issue by Moini** [fonttools/fonttools#3403]
Hi all, 

I don't know much about font internals, but I've been playing with making my own color font, which I'd like to share at openfontlibrary later, using only Inkscape, https://github.com/13rac1/scfbuild and this project here. 

The font library requires correct metadata, and that is why I'm using ttx - to edit the font's metadata.

However, when I convert my font to ttx and back again, it turns from an otf svg-in-open-type color font to a ttf without any color font features (as far as I can see).

How can I force ttx (or use the python library) to get my color font back, only with edited metadata?

Seems I need to zip the font files... 
So here's what's in the zip file:
 - .otf: unedited metadata,
 - .ttx: metadata edited, SVG data contained, 
 - .ttf: result of `ttx font.ttx` (no color :-( )

[nautic_alphabets_font_issue.zip](https://github.com/fonttools/fonttools/files/13773410/nautic_alphabets_font_issue.zip)

Thank you for your help!

`ttx --version` returns 4.46.0

**Comment by justvanrossum** [comment]
You can force the output filename to have an .otf extension with the -o option. Maybe that's all you need?

**Comment by justvanrossum** [comment]
Hm, your input font is actually a TTF, so the .ttf extension isn't incorrect. Also, all tables that are in the otf are also present in the ttf, and I don't see why it wouldn't work. It's not clear to me how your edits can affect the functionality of the font.

**Comment by Moini** [comment]
@justvanrossum Thanks for getting back to me so quickly! You're right, simply renaming or using the -o option work, indeed. I had previously used the -o option incorrectly... 

I'm unsure, though, whether the result is now a valid font file, or whether my font stack here on Linux Mint is just very nice and accepting even towards malformed fonts... ❓ Do you know? I don't want to share something broken widely... And I was intending to make a tutorial out of the process, so others can also learn how to do it (correctly).

What I do not understand is how the input file can be a TrueType font, when TrueType does not support SVG-in-OpenType? It was created by fonttools, too, only via https://github.com/13rac1/scfbuild/tree/master/scfbuild . 
Is that a bug?

There's clearly SVG inside... despite the ttf extension / it apparently being TTF (how can I recognize that from the file?).

**Comment by justvanrossum** [comment]
`ttx -l path/to/font.otf` gives you an overview of the tables that are inside the font. A .ttf generally has a `glyf` table, an .otf generally has a `CFF` or `CFF2` table. I think it is legal (but uncommon) for an .otf file to _be_ TrueType (containing a `glyf` table), but a CFF-based font file must have an .otf extension. It is legal for a font to contain both `glyf` and `CFF` (or `CFF2`) but this is not common practice.

As far as I know, both .ttf and .otf could additionally have an `SVG` table, making it an SVG-in-OpenType font. Why one of these does not work for you I don't know, it may be a platform issue.

**Comment by Moini** [comment]
@justvanrossum Thank you! Then I guess the script I found is only using the wrong extension in some place / uses fonttools incorrectly. I'll stick with TTF for the font, and have since (due to Tavmjong's help) also found https://github.com/googlefonts/nanoemoji/tree/main which remains to be investigated (already used to add some more tables automatically that make the font work with more programs).
