### ISSUE TITLE
ttx.py Generates Invalid Fonts on Windows

### ISSUE THREAD

**Issue by Zacharymk1213** [fonttools/fonttools#3410]
First discussed here: https://gitlab.gnome.org/GNOME/gnome-text-editor/-/issues/585

The BuilderBlocks.TTF font generated by Gnome Text Editor via ttx.py cannot be installed on Windows leading to display errors.

![image](https://github.com/fonttools/fonttools/assets/85691033/06c279d8-27bf-45bb-be16-8cefad74d12c)

**Comment by behdad** [comment]
See my comment there. Not a fonttools issue.
