### ISSUE TITLE
Variation model getMasterLocationsSortKeyFunc called without default location for mismatched anchors

### ISSUE THREAD

**Issue by kontur** [fonttools/fonttools#3412]
Hey,

I'm debugging an issue with a Variable font compilation with fontmake where execution exits at this exception:

https://github.com/fonttools/fonttools/blob/1722dabd845aa03308620b4d2e97035bf1abbdae/Lib/fontTools/varLib/models.py#L301-L303

Looking at where this is getting called from when the `VariationModel` is initialized I've added a simple print to see what the "locations" [here](https://github.com/fonttools/fonttools/blob/1722dabd845aa03308620b4d2e97035bf1abbdae/Lib/fontTools/varLib/models.py#L261C19-L263) actually are, and I get:

```
…
INFO: Axes:
[{'axisLabels': [],
  'axisOrdering': None,
  'default': 400.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [(400.0, 0.0),
          (500.0, 150.0),
          (600.0, 350.0),
          (700.0, 720.0),
          (800.0, 1000.0)],
  'maximum': 800.0,
  'minimum': 400.0,
  'name': 'Weight',
  'tag': 'wght'},
 {'axisLabels': [],
  'axisOrdering': None,
  'default': 0.0,
  'hidden': False,
  'labelNames': {'en': 'Swash'},
  'map': [],
  'maximum': 1000.0,
  'minimum': 0.0,
  'name': 'Swash',
  'tag': 'SWSH'}]
INFO: Internal master locations:
[{'Swash': 0.0, 'Weight': 0.0},
 {'Swash': 1000.0, 'Weight': 0.0},
 {'Swash': 0.0, 'Weight': 1000.0},
 {'Swash': 1000.0, 'Weight': 1000.0}]
INFO: Internal axis supports:
{'Swash': [0.0, 0.0, 1000.0], 'Weight': [0.0, 0.0, 1000.0]}
INFO: Normalized master locations:
[{'Swash': 0.0, 'Weight': 0.0},
 {'Swash': 1.0, 'Weight': 0.0},
 {'Swash': 0.0, 'Weight': 1.0},
 {'Swash': 1.0, 'Weight': 1.0}]
INFO: Index of base master: 0
INFO: Building variable font
INFO: Loading master fonts
INFO: Generating fvar
>>>>>>>>>>locations [{}, {'SWSH': 1.0}, {'wght': 1.0}, {'wght': 1.0, 'SWSH': 1.0}]
INFO: Building variations tables
INFO: Generating avar
INFO: Generating BASE
>>>>>>>>>>locations [{}, {'wght': 1.0}]
INFO: Generating MVAR
INFO: Generating HVAR
INFO: Merging OpenType Layout tables
>>>>>>>>>>locations [{'wght': 1.0}]
ERROR: Base master not found.
```

So the check triggers because there is no `{}` entry when merging the OpenType Layout tables. Curiously enough, though, when I uncomment the check the font compiles seemingly fine. 

I'm struggling to understand what is the problem here and what the check protects against. In this font, the entire `SWSH` axis comes from GlyphsApp brace layers, so maybe somehow this is the reason for why there is no `{}` default?

The designspace looks like this:

```
<designspace format="5.0">
  <axes>
    <axis tag="wght" name="Weight" minimum="400" maximum="800" default="400">
      <map input="400" output="0"/>
      <map input="500" output="150"/>
      <map input="600" output="350"/>
      <map input="700" output="720"/>
      <map input="800" output="1000"/>
    </axis>
    <axis tag="SWSH" name="Swash" minimum="0" maximum="1000" default="0"/>
  </axes>
…

  <sources>
    <source filename="../ufo/masters/Foobar-Regular.ufo" name="Foobar Regular" familyname="Foobar" stylename="Regular">
      <location>
        <dimension name="Weight" xvalue="0"/>
        <dimension name="Swash" xvalue="0"/>
      </location>
    </source>
    <source filename="../ufo/masters/Foobar-Regular.ufo" name="Foobar Regular {0, 1000}" layer="{0, 1000}">
      <location>
        <dimension name="Weight" xvalue="0"/>
        <dimension name="Swash" xvalue="1000"/>
      </location>
    </source>
    <source filename="../ufo/masters/Foobar-Bold.ufo" name="Foobar Bold" familyname="Foobar" stylename="Bold">
      <location>
        <dimension name="Weight" xvalue="1000"/>
        <dimension name="Swash" xvalue="0"/>
      </location>
    </source>
    <source filename="../ufo/masters/Foobar-Bold.ufo" name="Foobar Bold {1000, 1000}" layer="{1000, 1000}">
      <location>
        <dimension name="Weight" xvalue="1000"/>
        <dimension name="Swash" xvalue="1000"/>
      </location>
    </source>
  </sources>
…
```

Particularly because with the check uncommented the compiled font "works" I am wondering if there is some case not considered in fontTools that would otherwise trigger the check for a reason, but not in this instance.

Any idea how to debug this further?

**Comment by anthrotype** [comment]
> the check triggers because there is no {} entry when merging the OpenType Layout tables

the location `{}` is the default or "base" one, the VariationModel requires that at least that one be present, that's how OT variations work. In your case it appears that the default master has no GPOS while some non-default master does have one, hence the VariationModel complains about about it.
Does your Bold contain kerning whereas the Regular does not? Do the anchors (if any) match between the masters (maybe one master gets some mark/mkmk generated whereas the other does not)?

**Comment by kontur** [comment]
Hm, sounds odd that the default master wouldn't have GPOS/GSUB. I suppose brace layers fully inherit their GlyphsApp layer master kerning also, so really all should have GPOS/GSUB. Both "real" master UFOs (Regular and Bold) have the almost exact same features, only a few mark definitions seem to differ, and the two brace layers (No swash, Swash) are UFO layers.

The compiled font (when commenting out that check) has all features I'd expect it to have and seems to work in every aspect.

> the VariationModel requires that at least that one be present

So when there is a single entry in the "locations" trace wouldn't that suggest there is nothing to interpolate? Regardless if the single entry is a `{}` default or some other location? But even so, why wouldn't it find the default master for this merge specifically when clearly it has found it before for other merges.

So `[{}, {'SWSH': 1.0}, {'wght': 1.0}, {'wght': 1.0, 'SWSH': 1.0}]` means each dict axis value uses the default, unless specified, so `{}` means both axes use their default value, `{'SWSH': 1.0}` is a location with default wght value and specified SWSH value?

I'll try dig a bit more where the `[{'wght': 1.0}]` value comes from, and why the default _Regular_ with `wght 0.0` isn't what gets supplied.

**Comment by kontur** [comment]
Hm. Located some missing anchors in the sources, which I thought I had previously double checked had only compatible glyphs, but alas some anchors were missing. So fairly trivial reason.

However, this **definitely** should be a better error message for something as simple as mismatched anchors. I mean, the issue was not a "missing base master" in the sense the message implies. Debugging this from the error up with all these `ttLib.otTables.XXX` objects without a clear signature to look up is fairly arcane. To be fair, e.g. fontmake run via the CLI does run a pre-check to flag this before it reaches fontTools.

Imo the issue can be closed, but I leave it open in case the error log output is something that should be addressed in your opinion.

**Comment by anthrotype** [comment]
so does fontmake compatibility checker catches this or does it not? Are you calling fontmake or building it on your own using fonttools?

**Comment by kontur** [comment]
Sorry if the wording was unclear. `fontmake` ran from the CLI does catch this:
```
$ fontmake -g MismatchedAnchorsFont.glyphs -o ufo
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
INFO:fontmake.font_project:Saving master_ufo/MismatchedAnchorsFont.designspace
INFO:fontmake.font_project:Saving master_ufo/MismatchedAnchorsFont-Regular.ufo
INFO:fontmake.font_project:Saving master_ufo/MismatchedAnchorsFont-Bold.ufo
$ fontmake -m master_ufo/MismatchedAnchorsFont.designspace -o variable
ERROR:fontmake.compatibility:Fonts had differing anchors in glyph A:
ERROR:fontmake.compatibility: * Mismatched Anchors Font Regular had ""
ERROR:fontmake.compatibility: * Mismatched Anchors Font Bold had "top"
fontmake: Error: In 'master_ufo/MismatchedAnchorsFont.designspace': Compatibility check failed
```

The way I'm calling this originally is instantiating a fontmake `FontProject` from a script where it does not run that pre-check and thus fails in the less informative way.

**Comment by anthrotype** [comment]
yeah, we added those pre-checks exactly for things like this. fontmake is primiarily (I'd like to say exclusively) a command line tools, and its use as a library is accidental/not really supported

**Comment by kontur** [comment]
Fair enough.

**Comment by anthrotype** [comment]
> The way I'm calling this originally is instantiating a fontmake FontProject from a script where it does not run that pre-check

that's strange.. my understanding is the compatibility checker should run automatically for variable or interpolatable outputs unless it is disabled. Are you calling with FontProject.run_from_glyphs or run_from_designspace?

**Comment by kontur** [comment]
This is the bit of code with the actual calls. To be honest this hasn't been touched in a while, so maybe the more proper way to call/instantiate ought to be different. Without looking into it right now, I reckon the difference between the `run...` and the `build...` might be what omits the pre-checks? It's really just a CLI call with a bunch of custom options depending on the workflow running, plus not wanting to call a binary from the python script :)

```
import defcon
from fontmake.font_project import FontProject
from fontTools.designspaceLib import DesignSpaceDocument
from ..ufo import init_feature_writers
...
fp = FontProject()
ds.loadSourceFonts(defcon.Font)
options = {}
options["feature_writers"] = init_feature_writers(self.generate)
…
options["output_path"] = …
…
options["flatten_components"] = True
fp.build_variable_fonts(ds, **options)
```

**Comment by anthrotype** [comment]
yes that's it, you're calling build_variable_fonts yourself, the entry points of FontProjects are the ones that `fontmake.__main__` itself (i.e. the CLI) is calling, the others.. are supposed to be private

**Comment by kontur** [comment]
Naughty me calling private methods :) 
Will amend the script to get the benefits of the pre-checks, thanks for the pointers 👍

**Comment by anthrotype** [comment]
> Naughty me calling private methods :)

it's ok. python allows these things to be ambiguous which is good/bad depending on the POV. It's up to us to make these distinctions clearer.

**Comment by kontur** [comment]
> > not wanting to call a binary from the python script
> 
> that's totally legitimate, you'd call `subprocess.run([sys.executable, "-m", "fontmake", ...])` and will work just fine. I should add something to the readme someday

Valid, I suppose. I think concurrency is an issue, as my script can be processing several such VF builds, and do more stuff after fontmake is done, so would have to wait for those... all in all just easier to call the library directly, imo.

> python allows these things to be ambiguous which is good/bad depending on the POV. It's up to us to make these distinctions clearer.

Agree. `_` prefix is the most clear, implicitly. Fontmake has such a chain of forwarded calls when following the CLI entry point, I am pretty sure I initially just went "down" to the source of the most final call to actually trigger the variable font compile.
