### ISSUE TITLE
[Question] Why is Unix censored in the README?

### ISSUE THREAD

**Issue by Zachary-Rude** [fonttools/fonttools#3416]
In the following code snipped, taken from this repository's README, Unix is censored.
``` sh
# download the source code to 'fonttools' folder
git clone https://github.com/fonttools/fonttools.git
cd fonttools

# create new virtual environment called e.g. 'fonttools-venv', or anything you like
python -m virtualenv fonttools-venv

# source the `activate` shell script to enter the environment (Un*x); to exit, just type `deactivate`
. fonttools-venv/bin/activate

# to activate the virtual environment in Windows `cmd.exe`, do
fonttools-venv\Scripts\activate.bat

# install in 'editable' mode
pip install -e .
```
I'm confused as to why you decided to censor Unix as if it's a swear word or an offensive word, even though it's neither offensive nor a swear word (as far as I'm aware). I would really like to know why you decided to censor a completely appropriate and inoffensive operating system name like Unix.

**Comment by khaledhosny** [comment]
https://en.wikipedia.org/wiki/Unix-like

**Comment by Zachary-Rude** [comment]
oh, okay! i'm really used to \*nix being used instead of Un\*x, so i thought you were censoring it as if it's inappropriate or offensive because of how you put the star  in the middle rather than the beginning, so thanks for clearing up my confusion!

**Comment by khaledhosny** [comment]
I’m not used to this form as well, but it seems to have first appeared in this repo in a commit from 23 years ago e5ad9c959b6dbd76e83ed627a9e10e74d34b2cc4, so who knows what were the norms back then.

**Comment by behdad** [comment]
I replaced it with "Unix-like".
