### ISSUE TITLE
Banned content warning for Google Groups link

### ISSUE THREAD

**Issue by Zachary-Rude** [fonttools/fonttools#3417]
When I click on the Google Groups link on this repository, I get this warning: 
![Banned content warning](https://github.com/fonttools/fonttools/assets/84681078/89539fa2-6fdb-453c-9a54-738e3e881a1a)
It thinks that fontTools contains malware or spam, which is completely false about fontTools (as far as I'm aware).
What triggered this warning, and is there anything you can do to fix it?

**Comment by behdad** [comment]
I don't think we use the group at all.. If you open it, indeed you see a lot of spam and no recent discussion.

@justvanrossum should we remove the Google Groups link?

**Comment by behdad** [comment]
Basically the group is superseded by GitHub Discussions.

**Comment by Zachary-Rude** [comment]
gotcha!

**Comment by behdad** [comment]
I took the liberty to remove the Google Groups link.
