### ISSUE TITLE
lxml 5.1

### ISSUE THREAD

**Issue by frenzymadness** [fonttools/fonttools#3418]
We are testing version 5.1.0 of lxml and it seems that fonttools builds fine and all tests pass with it so it might be a good idea to remove the version limit from the following files:

https://github.com/fonttools/fonttools/blob/bf37f5721106afddeec197af5343027e4f487d55/requirements.txt#L19
and
https://github.com/fonttools/fonttools/blob/bf37f5721106afddeec197af5343027e4f487d55/setup.py#L100

**Comment by anthrotype** [comment]
good idea, thanks. Would you like to send a PR?
