### ISSUE TITLE
[feaLib] Tweak sort order of ligatures within a ligature set

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#3428]
In discussion with @anthrotype, it would be nice if we could make fea-rs and fonttools use the same sort order for ligatures within a ligature set. Currently fea-rs sorts by (decreasing) length, breaking ties by GID; fonttools is breaking ties by glyph name. Ultimately both approaches are arbitrary, and it isn't trivial for either of us to adopt the behaviour of the other, so I think there is a simple solution: we shouldn't break ties at all, and just use the declaration order in the source. That is, we should do a stable sort by decreasing length.

This will be changed in fea-rs shortly, and I'm opening this as a tracking issue for eventually making this change here as well.

I have written up my current understanding of this problem (or non problem, I think?) here: https://github.com/adobe-type-tools/afdko/issues/1727#issuecomment-1906703943

**Comment by behdad** [comment]
SGTM.

**Comment by anthrotype** [comment]
SGTM too, I'll send a PR
