### ISSUE TITLE
stripping CFF hints without desub get some glyphs misrendered in FreeType

### ISSUE THREAD

**Issue by jungshik** [fonttools/fonttools#343]
- How to reproduce
1. Grab NotoSansKR-Regular.otf [1] from the AOSP ( git clone https://android.googlesource.com/platform/external/noto-fonts ). The AOSP has 1.001. What I tried is 1.002 and 1.004. 
2. Strip CFF hints using '--no-hinting' option to pyftsubset without '--desubroutinize'. 
3. Run the following 
   
   $ ftview -m '알림 삼진 원섭' 16 NotoSansKR-Regular.otf
   $ ftdiff -f krtext  NotoSansKR-Regular.otf
     where 'krtext' file has '알림 삼진 원섭'
   
   $ hb-view --output-file=krtest.png NotoSansKR-Regular.otf "알림 삼진 원섭"
4. - FT 2.5.5 + Noto Sans KR 1.001 : The positions of '림' and '섭' are incorrect
   - FT 2.5.5 + Noto Sans KR 1.002 : The positions of '림', '진' and '섭' are incorrect. 
   - FT 2.6/ToT + Noto Sans KR 1.002 : The positions of '림' is incorrect while '진' and '섭' are correct. 

Below is the image taken with FT 2.5.5 + Noto Sans KR 1.002
![image](https://cloud.githubusercontent.com/assets/8578343/9448909/244ee2ca-4a54-11e5-8421-31c0dff41036.png)

Below is the screenshot taken with FT 2.5.5 + Noto Sans KR 1.001
![image](https://cloud.githubusercontent.com/assets/8578343/9448943/5db182e8-4a54-11e5-97a0-05d0d43e2cac.png)

[1] This is an Android-specific fallback version and is different from what's available from googlei18n/noto-cjk

**Comment by jungshik** [comment]
The above image should look like this:

![image](https://cloud.githubusercontent.com/assets/8578343/9448991/9edce6d6-4a54-11e5-8aff-fd85f0a971ac.png)


When I used Afdko to strip CFF hints and use pyftsubset to desub and compreoff to resub, I don't have such a problem. 

I expect that using pyftsubset to desub (at the same time as stripping hints) also works fine. I'll try that and report back.

**Comment by jungshik** [comment]
As noted in #144 by Behdad, desub at the same time as stripping made the font work. Resub-ing with compreoff also works  and gives me a slightly smaller  result than obtained with afkdo's hint-stripping followed by fonttool's desub and resub with compreoff.

**Comment by jungshik** [comment]
FYI,  I have to contradict what I wrote above (7 days ago). The final size of Noto Sans {KR,JP,SC,TC} obtained in procedure A is slightly smaller than obtained in procedure B. 

A. Drop hints (afkdo) + desub (pyftsubset) + resub (compreoff)
B. Drop hints + desub simultaneously (pyftsubet) + resub(compreoff)

**Comment by behdad** [comment]
Something's not adding up.  Those two procedures should result in exact same thing.  If they are not, we need to investigate.

Can you diff the resulting TTX files?

**Comment by jungshik** [comment]
@behdad , Proc A uses AFDKO cmd line tools  for dropping hints while Proc B uses pyftsubset for that. Even in that case, you expect the results (CFF table) to be identical?

**Comment by behdad** [comment]
Yes.  Please compare the TTX of after-dehint-after-desub.  There's only one correct way to do those operations, doesn't matter what toolchain you use.  These are deterministic operators afterall.

**Comment by miguelsousa** [comment]
Here's a simple [test font](https://dl.dropboxusercontent.com/u/9904253/TestFont-Regular.otf). Glyph **B** is hinted. When the font is processed with the command `pyftsubset TestFont-Regular.otf --output-file=nohints.otf --no-hinting --glyphs='*' --notdef-outline` the horizontal advance of **B** becomes zero instead of remaining at 400. I think this example illustrates the problem manifested by NotoSansKR-Regular.otf.

**Comment by miguelsousa** [comment]
@behdad regarding [this line](https://github.com/behdad/fonttools/blob/master/Lib/fontTools/subset.py#L1692), where in `fontTools` is the width of the charstring computed? I'm asking because I think it may have something to do with this issue.

**Comment by anthrotype** [comment]
The `width` attribute of T2CharString is set in the `draw` method here:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/misc/psCharStrings.py#L282

**Comment by behdad** [comment]
Ok, let me take a look.  The dehinting code tries to keep the width unchanged.  I'll point you out to the code soon.

The original issue I was observing was more severe: it was leaving bytes leftover.  That triggered OTS to reject the font.

**Comment by behdad** [comment]
Ok, this line is supposed to fix the width:

https://github.com/behdad/fonttools/blob/7f5d5454fc1332815a42ba8b9fb666981680bce4/Lib/fontTools/subset.py#L1694

However, reading it now, I think it wouldn't work for CID-keyed fonts with multiple fontDicts.  Perhaps that's what's happening with the CJK font.

**Comment by behdad** [comment]
This sounds like a great time to start adding tests for the subsetter!

**Comment by Arno-Enslin** [comment]
> When I used Afdko to strip CFF hints and use pyftsubset to desub and compreoff to resub, I don't have such a problem.

With the help of which script in the AFDKO can you strip CFF hints (except from pyftsubset, if it is integrated)?

(I stumbled over this bug today, because I wanted to automatize desubroutinization and dehinting with the help of a batch file. [Sidebearings / glyph widths are damaged. With and without --desubroutinize. Tested with Garamond Premier Pro.)

**Comment by anthrotype** [comment]
Fixed with f7a5d83cbbdc5918947ca7f030ed43e164f98fda 🍷
