### ISSUE TITLE
[designspace] Allow multiple <mappings> elements

### ISSUE THREAD

**Issue by Lorp** [fonttools/fonttools#3435]
Particularly in these early days of building avar version 2 designspace mappings, it would be useful if \<mapping\> elements could be logically grouped, with some kind of description for humans.

For example, implementing a single designspace "fence" requires multiple \<mapping\> elements: one to bring the overflowing values back to the "fence", and another to "pin" values at the fence to ensure values already contained by the fence are not remapped. Thus one conceptual action requires multiple encoded items, and it could be helpful to allow a description attribute to record the purpose of each set of mappings.

While a new \<group\> element within \<mappings\> would be one solution, @behdad suggests a simpler one: allow multiple \<mappings\> elements, each containing multiple \<mapping\> elements. The encoder would treat them as a single \<mappings\> element with all the \<mapping\> elements concatenated.

Example:

```xml
<mappings description="Handle upper XTRA fence when wght is default">
   <mapping>…</mapping>
   <mapping>…</mapping>
</mappings>
<mappings description="Handle upper XTRA fence when wght is not default">
   <mapping>…</mapping>
   <mapping>…</mapping>
   <mapping>…</mapping>
   <mapping>…</mapping>
</mappings>
```

Notes:
* Round-trip is not possible. (This is not seen as a problem.)
* Font editors may offer logical groupings (with description) for avar version 2 mappings, that would get saved into designspace as \<mappings\> groups with description attribute.

**Comment by behdad** [comment]
> * Round-trip is not possible. (This is not seen as a problem.)

Even that can possibly worked out; but I think it's okay not to.

**Comment by sannorozco** [comment]
All this per axis/dimension.

**Comment by behdad** [comment]
> All this per axis/dimension.

A "description" attribute on axis/dimension you mean?

**Comment by Lorp** [comment]
It’s purely for human convenience, so we can see how it works best to split things up.

**Comment by anthrotype** [comment]
Sounds good, no objections from me
