### ISSUE TITLE
[ttLib] Add glyph order reordering functionality

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#3467]
Changing glyph order requires updating various OTL coverage tables that should be sorted by glyph ID. 

`nanoemoji` has this small module, but it makes sense to have something like this in FontTools:
https://github.com/googlefonts/nanoemoji/blob/main/src/nanoemoji/reorder_glyphs.py

**Comment by behdad** [comment]
I vote for moving it into ttLib.reorderGlyphs() and add it as a method on ttFont.

**Comment by khaledhosny** [comment]
Sounds good to me.

**Comment by behdad** [comment]
Let's wait for @anthrotype and I'll go ahead and do it.

**Comment by anthrotype** [comment]
I'm ok if @rsheeter is ok, he wrote that.

**Comment by rsheeter** [comment]
sgtm. Ideally please update nanoemoji to use the FontTools one once it exists.

**Comment by arrowtype** [comment]
Just adding that I’d love for this functionality to exist as a relatively simple method in FontTools!

**Comment by behdad** [comment]
This was fixed in https://github.com/fonttools/fonttools/pull/3468

**Comment by arrowtype** [comment]
Amazing – thank you @behdad, @rsheeter, @khaledhosny, and everyone else who helped on this!
