### ISSUE TITLE
avar-2 support for TTFont.getGlyphSet()?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#3469]
It would be nice if `TTFont.normalizeLocation()` (as used by `getGlyphSet()`) would support the avar-2 format:

https://github.com/fonttools/fonttools/blob/430e364db7baf5494d1bdfe077154edc4dbd6b71/Lib/fontTools/ttLib/ttFont.py#L774-L804

Apart from the usefulness of having getGlyphSet() support avar-2, this would be very useful as a reference / example.

**Comment by behdad** [comment]
Yep, I think there's a couple other places too that need updating.

**Comment by behdad** [comment]
I'm working on this. Might take a few days to update all places.

**Comment by behdad** [comment]
I'm working on this right now. Should have ttFont done today for sure. WIP will go into:
https://github.com/fonttools/fonttools/pull/3473
