### ISSUE TITLE
Instancing CFF2 variable fonts.

### ISSUE THREAD

**Issue by fabiocaccamo** [fonttools/fonttools#3498]
Hi, 
thank you for this great library!

Trying to instantiate a CFF2 variable font, the following error is raised:
```python
Traceback (most recent call last):
  File ...
    instancer.instantiateVariableFont(font, coordinates, **options)
  File "/venv/lib/python3.12/site-packages/fontTools/varLib/instancer/__init__.py", line 1276, in instantiateVariableFont
    sanityCheckVariableTables(varfont)
  File "/venv/lib/python3.12/site-packages/fontTools/varLib/instancer/__init__.py", line 1223, in sanityCheckVariableTables
    raise NotImplementedError("Instancing CFF2 variable fonts is not supported yet")
NotImplementedError: Instancing CFF2 variable fonts is not supported yet
```

The issue for tracking progress about this feature (#1537) has already been closed even if this feature is not supported yet, from the documentation:

> Currently only TrueType-flavored variable fonts (i.e. containing ‘glyf’ table) are supported, but support for CFF2 variable fonts will be added soon.
>
> The discussion and implementation of these features are tracked at https://github.com/fonttools/fonttools/issues/1537

**Comment by behdad** [comment]
#1537 is a weird issue. It talks about `varLib.mutator` (not `varLib.instancer`); but then talks about partial instancing that `varLib.mutator` doesn't support. So I'm confused.

**Comment by fabiocaccamo** [comment]
@behdad thank you for the quick reply.

Considering the confusion in #1537, I think that this feature requires a dedicated issue.

**Comment by anthrotype** [comment]
> https://github.com/fonttools/fonttools/issues/1537 is a weird issue. It talks about varLib.mutator (not varLib.instancer); but then talks about partial instancing that varLib.mutator doesn't support. So I'm confused.

the title of that old issue "[varLib.mutator] Support partial VF instances" pre-dates the varLib.instancer module, but the issue was used to track progress of the development of the latter.

> I think that this feature needs a dedicated issue.

sure, given the latter was marked as closed.

**Comment by behdad** [comment]
Fixed in https://github.com/fonttools/fonttools/pull/3506
