### ISSUE TITLE
calcCubicArcLength RecursionError

### ISSUE THREAD

**Issue by typesupply** [fonttools/fonttools#3502]
I've encountered some curves that cause a `RecursionError` in `calcCubicArcLength`. The curves are oddly formed, but they happened in a designer's drawings so they aren't just theoretical. The first off curve is only different from the first on curve by one y unit while the second off curve is identical to the second on curve. These are the isolated curves for testing:

```python
from fontTools.misc.bezierTools import calcCubicArcLength

calcCubicArcLength(
    (377, 469),
    (377, 468), # off by one unit
    (377, 472),
    (377, 472)
)

calcCubicArcLength(
    (242, 402),
    (242, 403), # off by one unit
    (242, 399), 
    (242, 399)
)
```

if I make the difference 2 units, the `RecursionError` is not raised. Is this a fontTools bug or something that should be caught before calling `calcCubicArcLength`?

**Comment by behdad** [comment]
Definitely a fonttools bug. Let me look into it.

**Comment by behdad** [comment]
Should be fixed.

**Comment by typesupply** [comment]
Thanks!
