### ISSUE TITLE
ttx option parse order

### ISSUE THREAD

**Issue by za3k** [fonttools/fonttools#3507]
For me, the following command fails (tried to write to DejaVuSerif.ttx):

> ttx -t cmap -o - /usr/share/fonts/TTF/DejaVuSerif.ttf

While this one succeeds:

> ttx /usr/share/fonts/TTF/DejaVuSerif.ttf -t cmap -o -

I would like them both to work.

**Comment by anthrotype** [comment]
I just tried your first ttx commandit and it actually works for me, i'm on macos using bash

**Comment by anthrotype** [comment]
hm it seems that it's a limitation of Python's getopt implementation

> Note Unlike GNU getopt(), after a non-option argument, all further arguments are considered also non-options. This is similar to the way non-GNU Unix systems work.

https://docs.python.org/3/library/getopt.html#getopt.getopt

Maybe switching to a different argument parser (e.g. argparse) would fix this, but we'd have to be careful to match the existing command line behavior

**Comment by anthrotype** [comment]
i'm inclined to leave as is and document its behavior in the --help maybe. Unless someone is volunteering to port it over to argparse

**Comment by anthrotype** [comment]
looks like there's a https://docs.python.org/3/library/getopt.html#getopt.gnu_getopt which uses 

> GNU style scanning mode is used by default. This means that option and non-option arguments may be intermixed.

Maybe that works? I'll give it a try and report back

**Comment by anthrotype** [comment]
```diff
diff --git a/Lib/fontTools/ttx.py b/Lib/fontTools/ttx.py
index e7a068748..0adda52d7 100644
--- a/Lib/fontTools/ttx.py
+++ b/Lib/fontTools/ttx.py
@@ -375,7 +375,7 @@ def guessFileType(fileName):


 def parseOptions(args):
-    rawOptions, files = getopt.getopt(
+    rawOptions, files = getopt.gnu_getopt(
         args,
         "ld:o:fvqht:x:sgim:z:baey:",
         [
```

it seems to work! I wonder if this has other side effects though...

**Comment by anthrotype** [comment]
this is the source for gnu_getopts:
https://github.com/python/cpython/blob/fa359dfe07a07eb96e12b0053c5ae7089efdf9cc/Lib/getopt.py#L99-L147

i think it's safe to enable, i'll make a PR

**Comment by za3k** [comment]
Whoa, speedy! thanks
