### ISSUE TITLE
[subset] `--name-IDs='*'` keeps also unused user name IDs

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#3508]
When `--name-IDs='*'` is used, all name IDs in the font are kept including user name IDs, but the option should only affect pre-defined name IDs (or any name ID < 256) and user name IDs should be pruned as usual.

I believe this is caused by https://github.com/fonttools/fonttools/blob/969d09dcafd3669753e30060ccca7e5fd4c356cd/Lib/fontTools/subset/__init__.py#L2915-L2917

I think it should be something like:
```python
    nameIDs = set(options.name_IDs) | visitor.seen
    if "*" in options.name_IDs:
        nameIDs |= {n.nameID for n in self.names if n.nameID < 256}
    self.names = [n for n in self.names if n.nameID in nameIDs]
```

**Comment by behdad** [comment]
SGTM.
