### ISSUE TITLE
Bloated subset when using --retain-gids

### ISSUE THREAD

**Issue by ShubhamJainCimpress** [fonttools/fonttools#3516]
Hello team.

I have a font collection file `Noto Sans CJK` which has a size of ~18MB

When I subset the font using the following comand. `pyftsubset notosanscjksc.ttf --unicodes="0-FF" --output-file="notosanscjksc-2.ttf"  --font-number=2` , it creates a ubset of size 24KB.

But when I use the arg `--retain-gids` as follows `pyftsubset notosanscjksc.ttf --unicodes="0-FF" --output-file="notosanscjksc-1.ttf"  --font-number=2 --retain-gids`, it creates a subset of size 762KB.

I have attached all 3 files here. Can you please help us understand why this flag causes the subset to be so bloated, and is there a way we can reduce the size with this flag?
[Documents.zip](https://github.com/fonttools/fonttools/files/15393489/Documents.zip)

Thanks.

**Comment by behdad** [comment]
That's the nature of how retain-gid works. It has to store empty glyphs for the gid's you didn't include, and that consumes bytes.

**Comment by behdad** [comment]
Though, we *can* trim the empty gid's at the end of the glyph list. That would solve your case. Leaving this open.

**Comment by ShubhamJainCimpress** [comment]
Thanks @behdad for the quick response.
Just to confirm, does this mean you would trim the empty gids after the last non-empty glyph.
And the empty glyphs between 2 non-pty glyphs would still be present in the output?

**Comment by ShubhamJainCimpress** [comment]
Got it. I think this might solve most of our problems then, because we usually won't have discontinuous ranges for subsets.
Im going to go through Opentype docs more tomorrow, and will reach out if I have more questions. Thank you!

**Comment by behdad** [comment]
cc @garretrieger @qxliu76 Did we ever implement the trimming in hb-subset?

**Comment by garretrieger** [comment]
I'm pretty sure we do, https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-subset-plan.cc#L1042. This sets the number of glyphs to the maximum seen in the requested set. That number of glyphs is used when we're building tables that need to include empty gids.

**Comment by ShubhamJainCimpress** [comment]
I did some testing and I realized the glyphs at the end are already trimmed out, and the reason the example I shared is so bloated is because it has a lot of gap of non-empty gids (specifically between 190 and 58913).

Going through OpenType docs, I realized that for all fonts, vmtx and hmtx tables are indexed using glyph ids, which means its not possible to remove empty gids from the start, or in between non-empty gids.

For fonts with glyf/loca based outlines, the loca table is also indexed using glyph ids, and hence even that cannot be optimized. 

For fonts with CFF based outlines and having CID keyed fonts (like the example I shared above), inside the CFF table, CharStrings INDEX is also indexed by glyph ids, so cant be optimized. There are some other structures like fdSelect, Charsets which are also glyph id indexed, but they have formats which can optimize storing data when the values are consecutive for longer periods.
In the above example with retained glyph ids, I have checked all Strings INDEX, Charset, Global Subrs, Local Subrs, CharStrings INDEX, FDArray and FDSelect sizes, but I cant seem to account for a lot of additional size in the CFF table of retained gids subset vs non-retained gid subset. The only major size difference I can account for is the CharStrings Index which is 70KB as compared to 10KB. I also tried using the ttx tool to understand contents of CFF table, but couldnt find anything else there too. 
Could you help me understand what else is causing that file to bloat, and can it be shrinked down?

Please let me know if my understanding of anything above is incorrect.
Thanks!

**Comment by behdad** [comment]
Try `ttx -l` on both subsets to see which tables are taking what size.

**Comment by ShubhamJainCimpress** [comment]
I tried doing that, and apart from vmtx and hmtx, only CFF table is the one taking the extra space. 264866 bytes vs 15151 bytes.

**Comment by behdad** [comment]
What results do you get with `hb-subset`? So, charset wasn't the issue?

**Comment by behdad** [comment]
CFF knowledge (specially CFF1) among us at fonttools is very limited these days, since the Adobe people who were maintaining cffLib are not around anymore.

**Comment by ShubhamJainCimpress** [comment]
I havent tried using hb-subset. I will try it out. But charset isnt an issue, it was only 460 bytes.

**Comment by ShubhamJainCimpress** [comment]
> CFF knowledge (specially CFF1) among us at fonttools is very limited these days, since the Adobe people who were maintaining cffLib are not around anymore.
I understand, and Im going to try and go through code to understand where that extra space is coming from, and also going to try out hb-subset, but if youre able to take a look at it when you get a chance, that'll be really helpful. Thanks!

**Comment by behdad** [comment]
I'll try.

**Comment by behdad** [comment]
> I tried doing that, and apart from vmtx and hmtx, only CFF table is the one taking the extra space. 264866 bytes vs 15151 bytes.

So, I see all three of CFF, hmtx, and vmtx around 250k. Which suggests four bytes per glyph each. I think that's just the CharString INDEX. No?

**Comment by behdad** [comment]
Though the INDEX should take fewer bytes per glyph than 4.

**Comment by behdad** [comment]
Can I also ask why you need retain-gids? I know legitimate reasons for that. Just curious what your use-case is.

**Comment by ShubhamJainCimpress** [comment]
Actually the INDEX in CFF has format 2, which can use information about consecutive encoding in a very compressed format, hence it's not the one taking up that much space.

**Comment by behdad** [comment]
INDEX doesn't have a format. Just a offset-size.

**Comment by behdad** [comment]
You probably mean the FDArray.

**Comment by ShubhamJainCimpress** [comment]
So we have a system where we want to our clients to use font subsets when working with text on their browsers.  We store glyph runs for the text that they work with, and those glyphs are mapped against glyph ids. 
We don't want to have a situation where if we are processing the same text on server not using subsets, the glyph ids don't match and everything gets messed up.

**Comment by ShubhamJainCimpress** [comment]
Oh sorry, Yes I was talking about the Charset INDEX data specifically

**Comment by ShubhamJainCimpress** [comment]
The CharStrings Index is actually bloated, but it only takes 1 byte per empty glyph, that is why it causes an increase of 60Kb for nearly 60K empty glyphs.

**Comment by behdad** [comment]
And each empty glyph has a 1byte endchar.

**Comment by behdad** [comment]
So I'd be surprised if it was actually 1byte offset-size. I would guess 3bytes. In which case, all adds up.

**Comment by behdad** [comment]
> The CharStrings Index is actually bloated, but it only takes 1 byte per empty glyph, that is why it causes an increase of 60Kb for nearly 60K empty glyphs.

It's the offsets, not the payload, I'm talking about.

**Comment by behdad** [comment]
If we drop the endchar's everything will become more compact, but ots-sanitizer doesn't like that.

**Comment by ShubhamJainCimpress** [comment]
I had completely missed counting the offset array size and was just wondering about the actual payload. 
And like you mentioned if the offset size is 3 bytes, then all of it adds up.

Unfortunately I'm away from system, so I can't really check now, but that should definitely be it.  

Thanks for the help. This surely makes it clear  about the extra space.

I don't know what ots-sanitizer is tbh, but if we remove the endChars, it would still require 3 bytes in the offset array right? Per glyph.

**Comment by behdad** [comment]
> I don't know what ots-sanitizer is tbh,

It's something Firefox and Chrome use to "sanitize" the font and refuse bad fonts.

> but if we remove the endChars, it would still require 3 bytes in the offset array right? Per glyph.

No. Because then the total payload will be small and 1 or 2 byte offsets will fit.

**Comment by ShubhamJainCimpress** [comment]
Ah Okay I see. Actually we use harfbuzz for shaping, so will harfbuzz be able to parse such a font, if so, we can probably introduce this as an argument or something. or do you think it's a bad idea to pursue it this way?

**Comment by behdad** [comment]
If you use HarfBuzz, try using the new `cffLib.CFFToCFF2` module... That should produce (in theory; it's still very buggy) a legal font that doesn't have the single-byte endchar operator for empty glyphs.

**Comment by ShubhamJainCimpress** [comment]
Ohh I see, I will try that out then! I don't understand how CFF2 works yet, but I will check that out too.

I will have to continue this discussion tomorrow as it's pretty late here in India. Thanks a lot!

**Comment by behdad** [comment]
You're welcome.

**Comment by behdad** [comment]
```
-rw-r--r--. 1 behdad behdad   654008 May 23 14:28 notosanscjksc-2-CFF2.ttf
-rw-r--r--. 1 behdad behdad   780276 May 23 13:39 notosanscjksc-2.ttf
```

**Comment by garretrieger** [comment]
If you're worried about the size for network transfers then you can also pass the files through woff2, the brotli compression in woff2 should significantly shrink the vmtx/hmtx/loca runs of zeroes for empty glyphs.

**Comment by ShubhamJainCimpress** [comment]
@behdad , I have verified that the font does use 3 bytes for offset, and the total offset array itself around 180KB, and hence it does account for the complete size of the font!

> -rw-r--r--. 1 behdad behdad   654008 May 23 14:28 notosanscjksc-2-CFF2.ttf
> -rw-r--r--. 1 behdad behdad   780276 May 23 13:39 notosanscjksc-2.ttf

This is great, I will definitely try converting CFF to CFF2 using harfbuzz for such cases.

@garretrieger , we did think woff2 could be an option for reducing network traffic and our team also created a capability to decompress woff2 files on a wasm based rust client https://github.com/Cimpress-MCP/woff2-rs , but we use AWS cloudfront to serve font files and we have enabled brotli compression in there. When I checked size of brotli compressed subsets vs woff2 based subsets, I found them to not have a lot of difference that could impact our use case, hence we have kept that on hold.
But if needed, we will utilize woff2 font files like you suggested.

**Comment by ShubhamJainCimpress** [comment]
Yeah in practice, we do work with both kinds of fonts. CFF based and glyf based, so it might be still worthwhile to check.

**Comment by ShubhamJainCimpress** [comment]
I will close this issue as my queries have been answered. Thanks @behdad and @garretrieger !

**Comment by behdad** [comment]
Thank you. I learned a thing or two as well. :)
