### ISSUE TITLE
varLib.interpolatable --json with scipy installed: Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by PeterDekkers** [fonttools/fonttools#3522]
Hello.

It seems that, the moment I install `scipy` into my project, `varLib.interpolatable` starts using it, and then fails outputting JSON with:

```shell
TypeError: ('Object of type int64 is not JSON serializable')
```

To clarify, the above happens when running the following with `scipy` installed:
```shell
fonttools varLib.interpolatable font1.ttf font2.ttf --json
```

I assume this may be due to some conditional `scipy` imports? E.g.:
https://github.com/fonttools/fonttools/blob/90fed08964bba2b81f0e1ec9222c95b0bee05384/Lib/fontTools/varLib/interpolatableHelpers.py#L174-L188
    
https://github.com/fonttools/fonttools/blob/90fed08964bba2b81f0e1ec9222c95b0bee05384/Lib/fontTools/varLib/interpolatableHelpers.py#L306-L308

Happy to dig deeper, and maybe provide a minimal reproduction, with some guidance on how to best supply that?

Thank you :)

**Comment by PeterDekkers** [comment]
I assume that the solution here would be, when `scipy` is installed, to supply a custom JSON encoder that can handle `numpy` types?

So here:
https://github.com/fonttools/fonttools/blob/90fed08964bba2b81f0e1ec9222c95b0bee05384/Lib/fontTools/varLib/interpolatable.py#L915

You could do something like...

```python
json_encoder = json.JSONEncoder
try:
    import scipy
    import numpy as np

    class NumpyEncoder(json.JSONEncoder):
        def default(self, obj):
            if isinstance(obj, np.integer):
                return int(obj)
            if isinstance(obj, np.floating):
                return float(obj)
            if isinstance(obj, np.ndarray):
                return obj.tolist()
            return super(NumpyEncoder, self).default(obj)
   
    json_encoder = NumpyEncoder
except ImportError:
    pass

print(json.dumps(problems, cls=json_encoder), file=f) 
```

**Comment by PeterDekkers** [comment]
I can confirm that the above approach resolves the issue. Should I put together a PR?

**Comment by behdad** [comment]
I think we want to convert back to regular Python types or whatever it is that the non-scipy path is using. Thanks for the report!

**Comment by behdad** [comment]
Would be great if you can send a PR with the approach I suggested.

**Comment by PeterDekkers** [comment]
Ah, yes, that would keep all the `scipy`/`numpy` code contained to the conditional import blocks. Much tidier. Will set up a PR in the coming days, thank you.
