### ISSUE TITLE
How to capture log.warnings() produced from erroring fonts / properly check fonts

### ISSUE THREAD

**Issue by kdipippo** [fonttools/fonttools#3538]
## Table of Contents
- Context of Question
- Questions
- Additional Note

## Context
Downstream in the [WeasyPrint](https://github.com/Kozea/WeasyPrint) project, FontTools gets used to render fonts in the resulting PDFs.

A minimum viable python script using `weasyprint==60.1`, I've titled `weasy.py`:
```py
from weasyprint import HTML

html_string = """
<html>
<head>
<style>
    body {
        font-family: Helvetica;
        font-size: 16px;
    }
</style>
</head>
<body>
    <p>Hello World!</p>
</body>
</html>
"""

weasy_body = HTML(string=html_string).render()
weasy_body.write_pdf("output_file.pdf")
```

`Helvetica` here causes some errors to be displayed to my terminal:
```bash
➜  python3 weasy.py
1 extra bytes in post.stringData array
'created' timestamp seems very low; regarding as unix timestamp
```
Another font like `Arial` does not return these errors. In my investigation ([thread here](https://github.com/Kozea/WeasyPrint/issues/1585#issuecomment-2135433008)), WeasyPrint sees these errors after invoking:

```py
subsetter = subset.Subsetter(options)
subsetter.populate(gids=cmap)
try:
    subsetter.subset(self.ttfont)  # <-- this line
except TTLibError:
    LOGGER.warning('Unable to optimize font')
else:
    self.ttfont.save(optimized_font)
    self.file_content = optimized_font.getvalue()
```

`subsetter.subset()` performs a series of tasks against the subset font and displays `log.warnings()` from the downstream methods to terminal. The prior ([thread here](https://github.com/Kozea/WeasyPrint/issues/1585#issuecomment-2135433008)) contains links to these log.warnings, and I can elaborate if useful.

Ideally, it would be neat to capture those warnings so that a more verbose logging strategy could be employed in WeasyPrint against the font specifics.

## Questions
- What would be the advised validation strategy that would allow for these logs to be more descriptive?
  - Could the `self.ttfont` passed in here be passed into another function in fonttools that returns the messages `"created" timestamp is invalid` as an output?
  - Could the `log` handler be updated in Subsetter to return as output?

## Additional Note
Also, when I click on the link in the CONTRIBUTING.md to the mailing list, I see an error message "Banned content warning: fonttools has been identified as containing spam, malware, or other malicious content."
https://github.com/fonttools/fonttools/blob/353f3808f2ce86b2f0e65712103a20a75f3270c8/CONTRIBUTING.md?plain=1#L11

**Comment by behdad** [comment]
> * Could the `log` handler be updated in Subsetter to return as output?

Yes. We use the logging module. I believe you can redirect.  This is how we configure the logger:
```py
log = logging.getLogger("fontTools.subset")
```

**Comment by anthrotype** [comment]
We use [logging](https://docs.python.org/3/library/logging.html) module, all our logging messages are scoped and namespaced with "fontTools", the top-level module: e.g. "fontTools.subset" is the logger specific to the subsetter, etc.
Those warnings you mentioned about head.created being invalid probably do not come from the subsetter itself but from table modules that decompile each table.
If you want to capture these messages, I think you can register a custom handler that intercepts only the messages which come from loggers whose name starts with "fontTools", and then do whatever you want with them.

**Comment by kdipippo** [comment]
Thank you both @behdad and @anthrotype !! Appreciate the fast follow-ups and the information! This issue is all set to close on my end.
