### ISSUE TITLE
[GSUB] Simplify API for MultipleSubst

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#355]
To simplify dealing with GSUB lookup type 2 (multiple substitutions), write a class MultipleSubst as sub-class of FormatSwitchingBaseTable. This would be similar to SingleSubst in Lib/fontTools/ttLib/tables/otTables.py.

Currently, GSUB lookup type 2 (Multiple Substitution) has no wrapper class in otTables, which makes it a little clumsy to construct that lookup in code. Also, the resulting TTX files are not very readable.

For example, the following feature file, when applying it to some font with Adobe’s `makeotf` tool:

```
feature test {
  sub c_t by c t;
  sub f_f by f f;
} test;
```

currently results in the following TTX dump, with an equally complicated Python representation:

```
  <Lookup index="0">
    <!-- LookupType=2 -->
    <LookupFlag value="0"/>
    <!-- SubTableCount=1 -->
    <MultipleSubst index="0" Format="1">
      <Coverage>
        <Glyph value="c_t"/>
        <Glyph value="f_f"/>
      </Coverage>
      <!-- SequenceCount=2 -->
      <Sequence index="0">
        <!-- GlyphCount=2 -->
        <Substitute index="0" value="c"/>
        <Substitute index="1" value="t"/>
      </Sequence>
      <Sequence index="1">
        <!-- GlyphCount=2 -->
        <Substitute index="0" value="f"/>
        <Substitute index="1" value="f"/>
      </Sequence>
    </MultipleSubst>
  </Lookup>
```

Instead of parallel arrays, we could have a `MultipleSubst.mapping` attribute. In the above example, its vale would be `{'c_t': ('c', 't'), 'f_f': ('f', 'f')}`.

**Comment by behdad** [comment]
Be careful.  You are changing portion api and XML format. That's not
backwards compatible, right?  If we are to do that, we should do it in a
branch and when it's complete, devise a migration plan, and merge and bump
version number.

**Comment by brawer** [comment]
Do we have sample migration plans for similar changes? (Not sure what the plan would state, exactly?)

**Comment by behdad** [comment]
For example:

  - make it compatible. Ie, make ttx accept old XML files and silently
convert; use python tricks like properties to make code using old API
continue working.  Specially code using old API to read tables.  Code
generating tables is much less frequent and we can accept to break.

**Comment by behdad** [comment]
Another plan is to just document, so we'd have a migration-guide.

**Comment by brawer** [comment]
> Another plan is to just document, so we'd have a migration-guide.

Makes sense, I’ll start a draft.

Regarding doing API-breaking development in a special branch, are you sure? This would make development (a lot) more complex imho. Clients who sync with head are probably aware that they’re living on the bleeding edge; if they want stability, wouldn’t they rather take a stable release?

**Comment by brawer** [comment]
Regarding “make ttx accept old XML files and silently convert”, that sounds easy enough; I’m working on this.

**Comment by anthrotype** [comment]
looks like this change broke @typesupply's compositor:

https://github.com/typesupply/compositor/issues/19

Pity that the changelog for 3.1 does not mention this change.

I wonder if we could make the old API work, as @behdad was suggesting in https://github.com/fonttools/fonttools/issues/355#issuecomment-139235864

**Comment by brawer** [comment]
Sorry about that. On the other hand, if there’s only a single breakage, perhaps it’s easier if they just roll forward and update?

**Comment by anthrotype** [comment]
yes, it should be straightforward to update compositor. I'll send a PR.

**Comment by brawer** [comment]
Thank you!
