### ISSUE TITLE
[feaLib] possibly suboptimal compilation of inline multiple substitution rules

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#3551]
I believe this is similar to https://github.com/fonttools/fonttools/issues/2150, but for multiple substitution instead of single substitution.

Given the following input,

```fea
# reduced from the ccmp feature in oswald
feature ccmp {
    lookup ccmp_Other_1 {
        @CombiningTopAccents = [acutecomb brevecomb];
        @CombiningNonTopAccents = [dotbelowcomb ogonekcomb];
        lookupflag UseMarkFilteringSet @CombiningTopAccents;
        sub idotbelow' @CombiningTopAccents by idotless dotbelowcomb;
        sub iogonek' @CombiningTopAccents by idotless ogonekcomb;
        sub idotbelow' @CombiningNonTopAccents @CombiningTopAccents by idotless dotbelowcomb;
        sub iogonek' @CombiningNonTopAccents @CombiningTopAccents by idotless ogonekcomb;
    } ccmp_Other_1;
} ccmp;
```

`fontmake` generates five lookups; one contextual lookup, and then one lookup for each inline sub statement. This means that there are two sets of duplicate lookups, i.e. two copies of `sub iodotbelow by idotless dotbelowcomb;` and two copies of `sub iogonek by idotless ogonekcomb;`.

`fontc`, for this input, generates two identical lookups, where each lookup contains both of the substitutions.

I am not sure that either is correct; I think we should be able to get away with a single lookup, containing both substitutions.

_This has unexpected implications!_ specifically, the presence of duplicate identical lookups (which will be deduplicated during table packing) has unexpectedly (to me) severe impact on binary size, because it means that we can not efficiently deduplicate various `ChainedClassSequenceRule` and `ChainedClassSequenceRuleSet` tables, since even though they are referencing semantically identical lookups those lookups have distinct lookup ids, which is the difference between 140 bytes for the fontmake table and 102 bytes for `fontc`.

Does my reasoning make sense? can we be more aggressive in reusing lookups in this case?

**Comment by behdad** [comment]
> Does my reasoning make sense? can we be more aggressive in reusing lookups in this case?

I think so. @simoncozens

**Comment by simoncozens** [comment]
In theory this can be done with one lookup, yes. (Or fewer! It's possible to combine all non-overlapping "auxiliary" lookups which share the same lookup flags into a single lookup across multiple chaining rules.)

And yes, it makes sense that, because multiple `Rule` tables get generated, the impact of deduplication is limited to "leaf nodes".

**Comment by behdad** [comment]
> Or fewer! It's possible to combine all non-overlapping "auxiliary" lookups which share the same lookup flags into a single lookup across multiple chaining rules

I believe AFDKO does that? I thought feaLib does as well.
