### ISSUE TITLE
[designspaceLib] Does Instance `name` really need to be unique and is it really required?

### ISSUE THREAD

**Issue by colinmford** [fonttools/fonttools#3572]
Hi,

Browsing the designspaceLib docs, I noticed the line for the Instance `name` attribute

> `name`: required, string. A unique name that can be used to identify this font if it needs to be referenced elsewhere.

https://github.com/fonttools/fonttools/blob/aa390ec98bedb5cdd8c4392b0d7898a812db6a6b/Doc/source/designspaceLib/xml.rst?plain=1#L925

It looks like it comes unmodified from @LettError's designSpaceDocument Readme, from 8 years ago:
https://github.com/LettError/designSpaceDocument/blame/4312e8a086664b71ad4d195bce10ec155b0112e4/README.md#L390

But I've looked through designspaceLib, and it doesn't seem to be used for anything, let alone checked for uniqueness. There are many `<instance>`s in the designspaceLib test documents without the `name` attribute, so the "required" line does not seem to be holding water. Does anyone know if it is required as a unique identifier in any other tool or library?

The only place I thought it really might be used is MutatorMath, but it is not required there. See: https://github.com/LettError/MutatorMath/blob/b0a87ec54df25ccbe6cc37825dd1d335efbce4a6/Lib/mutatorMath/ufo/document.py#L199-L205

If not, should we remove "required", "unique", or both?

**Comment by justvanrossum** [comment]
In practice (in the designspaceLib implementation) it is indeed not required, and not checked for uniqueness.

(That said, I _wish_ it was required and unique: in my Fontra designspace reader/writer I need a unique and persistent identifier, and I will make one up if it doesn't exist or isn't unique.)

**Comment by LettError** [comment]
sourcedescriptor has a similar name that was once used for such a purpose. https://github.com/fonttools/fonttools/blob/aa390ec98bedb5cdd8c4392b0d7898a812db6a6b/Lib/fontTools/designspaceLib/__init__.py#L132
Maybe it is enough that the descriptors have an attribute where tools can assign their identifiers to. But with the understanding that it is not a value that need to be editable by people?

**Comment by colinmford** [comment]
> _(Edit: I was not yet fully awake, I thought this was about source descriptors.)_

Yeah, the `name` attribute seems to be crucial for just about every other element other than the Instance element! But since Instance has family and style names, it seems less important. I don't see it as having to be "required", like in other elements.

I don't think we should get rid of `name`, I just wanted clarification of its role and to see if anyone out there is actually using it as described in the spec.
