### ISSUE TITLE
instantiating avar2 font

### ISSUE THREAD

**Issue by gferreira2** [fonttools/fonttools#3587]
I'm trying to generate an instance from a [variable font](http://github.com/googlefonts/amstelvar-avar2/blob/main/Fonts/AmstelvarA2-Roman_avar2.ttf) which contains [avar2 ‘synthetic’ axes](http://github.com/googlefonts/amstelvar-avar2/blob/main/Sources/Roman/AmstelvarA2-Roman_avar2.designspace#L35) using `varLib.mutator.instantiateVariableFont`. it works as expected with standard locations, but not with ‘synthetic’ ones.

```python
varfont  = TTFont('AmstelvarA2-Roman_avar2.ttf')

# this works
instanceA = instantiateVariableFont(varfont, {'XOPQ': 280})

# this doesn't work (outputs default location)
instanceB = instantiateVariableFont(varfont, {'wght': 800})
```

is avar2 not yet supported in `varLib.mutator`, or am I doing something wrong? thanks in advance for your help!

**Comment by justvanrossum** [comment]
If anywhere, I’d expect this to appear in instancer, not mutator (which is pretty much deprecated).

But it looks like it isn’t there yet: #3086.

**Comment by gferreira2** [comment]
ok. thanks!
