### ISSUE TITLE
[ufoLib] Component scale float precision when writing to file

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#3595]
Discovered in https://github.com/LucasFonts/vfbLib/issues/94 ...

AFAIK in UFO floats can have an arbitrary precision. When writing an UFO with a component that has a scale of 0,9999999999999999 (16 decimals), I'd expect it to be written in the glif file precisely, or rounded to 1 not 0. Trying to print the XML string after the component has been added to the etree, I also get the same value:

```xml
<component base="eight.osf" yScale="0.9999999999999999" xOffset="-5"/>
```

But then, after the UFO is written to disk, when I inspect the yScale of the component, it is written as `yScale="0"`.

What may be the reason? A limitation of the XML libraries? The result is the same whether lxml is installed or not.

**Comment by justvanrossum** [comment]
Can you privide a test snippet that shows yScale is written as "0", even though the input is close to "1"?

The output of this snippet:
```python
from fontTools.ufoLib.glifLib import writeGlyphToString

def drawPoints(pen):
    yScale = 0.999999999999999999
    print(yScale)
    pen.addComponent("A", transformation=[1, 0, 0, yScale, 0, 0])

class Glyph:
    pass

g = Glyph()

s = writeGlyphToString("B", g, drawPoints)

print(s)
```

Is this:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<glyph name="B" format="2">
  <outline>
    <component base="A"/>
  </outline>
</glyph>
```
Which is to be expected if the value really becomes 1.0. The highest number of decimals for which this will output yScale is 16.

**Comment by justvanrossum** [comment]
It's a bug in ufonormalizer: https://github.com/unified-font-object/ufoNormalizer/issues/91

**Comment by benkiel** [comment]
Thanks for reviewing that @justvanrossum, I merged the PR and pushed a update to ufoNormalizer, 0.6.2.
