### ISSUE TITLE
[varLib.interpolatable] Does not correctly handle discrete axes

### ISSUE THREAD

**Issue by colinmford** [fonttools/fonttools#3597]
Hi @behdad @anthrotype,

I love the `varLib.interpolatable` tool, and I would love to use it on a designspace with a discrete axis. But, when I try to run one through, it gives the following error:

```
  File "/Users/colinmford/Git/fonttools/Lib/fontTools/varLib/interpolatable.py", line 718, in main
    axis_triples = {
                   ^
  File "/Users/colinmford/Git/fonttools/Lib/fontTools/varLib/interpolatable.py", line 719, in <dictcomp>
    a.name: (a.minimum, a.default, a.maximum) for a in designspace.axes
             ^^^^^^^^^
AttributeError: 'DiscreteAxisDescriptor' object has no attribute 'minimum'
```

Larger context:
https://github.com/fonttools/fonttools/blob/ba20aa2f56c90da06000aac7110a99ccfacb8239/Lib/fontTools/varLib/interpolatable.py#L710-L723

I suppose it should split up the designspace into its subspaces, (probably using `designspaceLib.split.splitInterpolatable`) and then run the interpolatable tests on each subspace, though I can see this being a can of worms.

I can attempt a PR to enable discrete axes with `interpolatable`, but I wanted to check first with the both of you to see that something wasn't already in progress, or if you had any suggestions to start.

Thanks!

**Comment by behdad** [comment]
> I can attempt a PR to enable discrete axes with `interpolatable`, but I wanted to check first with the both of you to see that something wasn't already in progress, or if you had any suggestions to start.

It hasn't been on my radar. Let me think about it. I think it can be done without splitting the designspace. Right now I collect all masters, and for each one, pick a closest master to compare with. I just need to have multiple groups of masters.

**Comment by behdad** [comment]
If you don't mind sending me a reproducer, I can work on it right away. You can email me. Thanks.

**Comment by colinmford** [comment]
@behdad I don't have your email, here it is attached:

[Discrete Axis.zip](https://github.com/user-attachments/files/16474547/Discrete.Axis.zip)

**Comment by behdad** [comment]
> @behdad I don't have your email address, here it is attached. It's just a simple 2-axis set up, with one axis discrete.

Thanks. first.last@gmail works...

**Comment by behdad** [comment]
Thanks. This should fix it: https://github.com/fonttools/fonttools/pull/3599

**Comment by colinmford** [comment]
@behdad Thanks so much!
