### ISSUE TITLE
`varLib.interpolatable` not supporting CFF2 VFs?

### ISSUE THREAD

**Issue by frankrolf** [fonttools/fonttools#3666]
I’ve been playing around with `varLib.interpolatable` after receiving [a few useful reports](https://github.com/adobe-fonts/source-serif/issues/131) – now, I am experimenting with a different font, and it seems like CFF2 VFs are not supported at all.

I would not be too surprised if I’d get an error message communicating as much – instead, the PDF claims “Your font’s good – have a cupcake”. The same command for the same VF in TTF format will produce a 76-page PDF with kink reports.

Is this deliberate, or an oversight?

**Comment by justvanrossum** [comment]
> Is this deliberate, or an oversight?

Option three: no one got around building it. It's always option three.

**Comment by frankrolf** [comment]
The only real complaint I have here is that a CFF2 VF is passed through as “fine”. An error message might be clearer (and doesn’t take that long to build).

**Comment by behdad** [comment]
> The only real complaint I have here is that a CFF2 VF is passed through as “fine”. An error message might be clearer (and doesn’t take that long to build).

It should be rather trivial to fix this. Which font can I use with?

**Comment by frankrolf** [comment]
Didn’t get to say “thank you“ here!
Just used it on a CFF2 VF, and it works impeccably! :-)

**Comment by behdad** [comment]
You're welcome.
Glad it works.
