### ISSUE TITLE
`fonttools.interpolatable` node count false negative

### ISSUE THREAD

**Issue by roberto-arista** [fonttools/fonttools#3694]
Hey!

I don't know if this is a known issue, but I could not find a discussion about this. In case feel free to point me somewhere else.

Consider the following glyphs file.
[dotbelowcomb.glyphs.zip](https://github.com/user-attachments/files/17818912/dotbelowcomb.glyphs.zip)

If I run `fonttools varLib.interpolatable dotbelowcomb.glyphs` I get the following output:

```
  Masters: New Font-Regular, New Font-Bold:
    Node count differs in path 0: 8 in New Font-Regular, 7 in New Font-Bold
```

But if I dump the ufos from the glyphs file with `glyphs2ufo` I get two `glif` files like this (posting only `<contour>`):

- Regular
```
  <outline>
    <contour>
      <point x="810" y="-209" type="line"/>
      <point x="810" y="-121"/>
      <point x="739" y="-50"/>
      <point x="651" y="-50" type="curve" smooth="yes"/>
      <point x="563" y="-50"/>
      <point x="492" y="-121"/>
      <point x="492" y="-209" type="curve" smooth="yes"/>
      <point x="492" y="-211" type="line"/>
      <point x="492" y="-298"/>
      <point x="563" y="-369"/>
      <point x="651" y="-369" type="curve" smooth="yes"/>
      <point x="739" y="-369"/>
      <point x="810" y="-298"/>
      <point x="810" y="-211" type="curve" smooth="yes"/>
    </contour>
  </outline>
```

- Bold
```
  <outline>
    <contour>
      <point x="822" y="-225" type="line"/>
      <point x="822" y="-136"/>
      <point x="748" y="-69"/>
      <point x="647" y="-69" type="curve" smooth="yes"/>
      <point x="545" y="-69"/>
      <point x="470" y="-136"/>
      <point x="470" y="-225" type="curve" smooth="yes"/>
      <point x="470" y="-225" type="line"/>
      <point x="470" y="-314"/>
      <point x="545" y="-381"/>
      <point x="647" y="-381" type="curve" smooth="yes"/>
      <point x="748" y="-381"/>
      <point x="822" y="-314"/>
      <point x="822" y="-225" type="curve" smooth="yes"/>
    </contour>
  </outline>
```

(yes, they are the same amount)

I assume the problem lies on the fact first and last node of the Bold outline share the same location. Glyphs does not highlight the outlines as problematic, neither does Prepolator.

**Comment by behdad** [comment]
Interesting. Thanks. Will look into it.

**Comment by roberto-arista** [comment]
hey @behdad! thanks for the fix : )
when do you think the commit from `ufolib2` will end up in a `fonttools` release?

**Comment by anthrotype** [comment]
ufoLib2 0.17 was released and published to pypi. I believe now fonttools interpolatable needs to be changed so that it calls draw with the new outputImpliedClosingLine=True.

**Comment by anthrotype** [comment]
oh it seems like it already does:
 
https://github.com/fonttools/fonttools/blob/3fe083e8d1ee36ae6573292ad884e8b95c51dcf5/Lib/fontTools/varLib/interpolatable.py#L71

so I think it should be enough for you to upgrade ufoLib2 to the latest 0.17.0

**Comment by roberto-arista** [comment]
beautiful! thanks
