### ISSUE TITLE
[feaLib] Reuse inline ligature substitution lookups?

### ISSUE THREAD

**Issue by cmyr** [fonttools/fonttools#3701]
This is the same as #3551, but for inline ligature substitution rules.

Given the fea,

```fea
lookup locl_latn_1 {
        script latn;
        language CAT;
        sub l' periodcentered' l by ldot;
        sub L' periodcentered' L by Ldot;
} locl_latn_1;
```

feaLib will generate separate lookups for the two inline rules (`sub l periodcentered by ldot` and `sub L periodcentered by Ldot`) when they could more efficiently be placed in the same lookup.

Is there any interest in fixing this here? If not I might remove this optimization in fea-rs for the time being, just to have the two implementations match.

**Comment by behdad** [comment]
> Is there any interest in fixing this here?

I think so, yes.
