### ISSUE TITLE
axisOrdering is not being set

### ISSUE THREAD

**Issue by ryanbugden** [fonttools/fonttools#3710]
## Problem
It seems that setting the `axisOrdering` via a script is not working unless one the following conditions are met:
- There is axis label content. (The fact that this is usually the case makes this issue a lot less important, I know)
- The axisOrdering is greater than zero.
- The axisOrdering is set explicitly as a string.

## Test script
```python
from fontTools.designspaceLib import DesignSpaceDocument, AxisDescriptor, AxisLabelDescriptor

doc = DesignSpaceDocument()
a1 = AxisDescriptor()
a1.minimum = 1
a1.maximum = 1000
a1.default = 400
a1.name = "weight"
a1.tag = "wght"

# Change the 0 below to a 1, and re-run
a1.axisOrdering = 0
doc.addAxis(a1)
print(doc.tostring())
```

### Expectation
The following is expected: `<labels ordering="0"/>`.
### Results
Nothing is written to the doc.

## Thoughts
- I’m thinking that fontTools is interpreting a `0` value without a label context as something akin to `None` and that's why it doesn't write. 
- If the value is meant to be set as a string and not an integer, then I think the example in the documentation needs updating: https://fonttools.readthedocs.io/en/latest/designspaceLib/python.html#axisdescriptor

## Current workarounds
- Set explicitly as a string.
- Add some axis label content.

---
Thank you!

**Comment by justvanrossum** [comment]
Maybe this line:
https://github.com/fonttools/fonttools/blob/fbd89a0f55921a8ecb9f6b6a16f94ecfa711db7b/Lib/fontTools/designspaceLib/__init__.py#L1599
Should be like this instead:
```python
        if axisObject.axisOrdering is not None or axisObject.axisLabels:
```
Can you see if that helps?

**Comment by ryanbugden** [comment]
I cloned the fontTools repo, set it up as an external package for RF, and changed that line, and it worked! Thanks, Just! Is it helpful for me to make a PR?

**Comment by justvanrossum** [comment]
> Is it helpful for me to make a PR?

Yes please!
