### ISSUE TITLE
Simplify cmap subtable format API / XML

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#384]
Currently we use different subclasses for different cmap subtable types.  This makes the API unpleasant.  For example, converting subtable formats needs creating new objects just to assign the same dict to them:

https://github.com/behdad/fonttools/blob/master/Snippets/cmap-format.py

The XML also has the class name in it in terms of elements like <cmap_format_4 ...>.  That's all bogus and unnecessary.  Some of the elements, like format_12, include as attributes things like length-in-bytes, which are not necessary.

We should clean this up in a backwards-compatible way.  Should just have a <cmap_table ...> element that accepts a format attribute.  If format is set to auto, which is default, we will choose format automatically in this way:
- if non-BMP entries are present, choose format 12
- otherwise choose format 4
- possibly, if all entries are < 256, choose format 0?

We should also add a more compact encoding that is suitable for format 13...

Format 14 has a different API, so maybe that one should go through a different subclass / element...

**Comment by s40king** [comment]
.

**Comment by s40king** [comment]
.

**Comment by s40king** [comment]
,

**Comment by s40king** [comment]
,

**Comment by s40king** [comment]
,

**Comment by Pomax** [comment]
format 4 can still be smaller than format 0 if the slice is continuous though, so sticking with the platform agnostic subtables is probably nicer, unless the XML explicitly says `subtable version="0"`?
