### ISSUE TITLE
[ttx] Don't write out "Dumping ..." if output is sent to stdout

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#390]

**Comment by anthrotype** [comment]
with logging, ttx writes to stderr by default.

**Comment by MitchTalmadge** [comment]
@anthrotype Can you verify that writing to `stderr` is the correct behavior when printing out dumping progress? I am working on a javascript/Electron application that uses fonttools through a `child_process` instance (by invoking the python command). I expected the info logs to appear on stdout and errors to appear on stderr, but they all appear on stderr, making it difficult (impossible?) to determine what is and isn't an error.

**Comment by behdad** [comment]
I also expect log messages to go to stdout and not stderr, unless they are warning or error.
