### ISSUE TITLE
Can't subset Google-style color fonts

### ISSUE THREAD

**Issue by rsheeter** [fonttools/fonttools#395]
The subsetter currently always drops CBDT/CLBC (for Google Color fontshttp://google-opensource.blogspot.com/2013/05/open-standard-color-font-fun-for.html). If this is changed (based on discussion w/Behdad) as follows:

subset.py

```
# CBDT will inherit it
@_add_method(ttLib.getTableClass('EBDT'))
def subset_glyphs(self, s):
  self.strikeData = [_dict_subset(strike, s.glyphs) for strike in self.strikeData]
  return True

# add CBLC to _no_subset_tables_default
# remove 'CBLC', 'CBDT' from _drop_tables_default
```

And we then try to subset Noto Color Emoji, say with args `NotoColorEmoji-Regular.ttf --gids=2 --verbose` it fails, saying .notdef is missing:

```
Text: ''
Unicodes: []
Glyphs: []
Gids: [2]
maxp pruned
cmap pruned
name pruned
post pruned
GSUB pruned
Added .notdef to subset
Closing glyph list over 'GSUB': 2 glyphs before
Glyph names: ['.notdef', 'zero']
Traceback (most recent call last):
  File "subset.py", line 2746, in <module>
    main()
  File "subset.py", line 2715, in main
    subsetter.subset(font)
  File "subset.py", line 2496, in subset
    self._closure_glyphs(font)
  File "subset.py", line 2424, in _closure_glyphs
    self.log.glyphs(self.glyphs, font=font)
  File "subset.py", line 2536, in glyphs
    self("Glyph IDs:    ", sorted(reverseGlyphMap[g] for g in glyphs))
  File "subset.py", line 2536, in <genexpr>
    self("Glyph IDs:    ", sorted(reverseGlyphMap[g] for g in glyphs))
KeyError: '.notdef'
```

Perhaps we don't care about notdef and try with `NotoColorEmoji-Regular.ttf --gids=2 --verbose --no-notdef_glyph`. Sadly still unhappy:

```
Text: ''
Unicodes: []
Glyphs: []
Gids: [2]
maxp pruned
cmap pruned
name pruned
post pruned
GSUB pruned
Closing glyph list over 'GSUB': 1 glyphs before
Glyph names: ['zero']
Glyph IDs:     [2]
Closed glyph list over 'GSUB': 1 glyphs after
Glyph names: ['zero']
Glyph IDs:     [2]
Retaining 1 glyphs: 
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
cmap subsetted
name subsetting not needed
post subsetted
CBDT subsetted
CBLC subsetting not needed
GSUB subsetted
GSUB pruned
Traceback (most recent call last):
  File "subset.py", line 2746, in <module>
    main()
  File "subset.py", line 2717, in main
    save_font (font, outfile, options)
  File "subset.py", line 2589, in save_font
    font.save(outfile, reorderTables=options.canonical_order)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 221, in save

  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 650, in _writeTable

  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 663, in getTableData

  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/E_B_D_T_.py", line 97, in compile
KeyError: 'numbersign'
```

**Comment by anthrotype** [comment]
I'm not sure I understood, sorry.
Would you like to subset the font (including the CBDT) and only keep one glyph in it (i.e. the gid 2)?

**Comment by anthrotype** [comment]
Thanks for the report, I will have a look tomorrow.

**Comment by rsheeter** [comment]
> Would you like to subset the font (including the CBDT) and only keep one glyph in it (i.e. the gid 2)?

Yes :)

In particular, to be able to subset a Google-style Color font down to just the selected glyphs and keep only the bitmaps for those glyphs.

**Comment by anthrotype** [comment]
I believe EBLC (and CBLC) also needs to be subsetted, as it contains the `indexSubTables` for each strike, with the names and locations of each glyph. That's why it's raising KeyError upon compiling.

**Comment by rsheeter** [comment]
I had the same notion buy Behdad suggested the locator tables should
rebuild based on the updated data tables. Perhaps that isn't fully wired
though?

**Comment by anthrotype** [comment]
See line 87 in the `compile` method of EBDT:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/E_B_D_T_.py#L87

It's looping through the `curIndexSubTable.names` (which are stored in EBLC) and then attempting to get the glyph data in `curGlyphDict` (stored in EBDT).

**Comment by rsheeter** [comment]
Based on Behdads comments, perhaps we should make it build the locator
strikes based on the data instead? - IIRC loca is handled in this style
(generated rather than relied on).

**Comment by behdad** [comment]
Ignore what I said before.  We should fix this the way it makes most sense.

**Comment by rsheeter** [comment]
Any reason just adding a subset_glyphs method for it much like the one for
the DT table would be a Really Bad Idea?

**Comment by behdad** [comment]
Wouldn't be a Really Bad Idea.  When things can be automated, it's nice to automate.  But in the mean time do what you need to do!

**Comment by rsheeter** [comment]
For my purposes something along these lines (not overly tested) seems like it might suffice:
```
# CBLC will inherit it
@_add_method(ttLib.getTableClass('EBLC'))
def subset_glyphs(self, s):
  for strike in self.strikes:
    for indexSubTable in strike.indexSubTables:
      indexSubTable.names = list(set(indexSubTable.names) & s.glyphs)
    strike.indexSubTables = [i for i in strike.indexSubTables if i.names]
  self.strikes = [s for s in self.strikes if s.indexSubTables]

  return True
```

**Comment by anthrotype** [comment]
does that mean the modified subset.py now works with your color fonts?

**Comment by rsheeter** [comment]
Let's say "sort of"

It makes a nice small font that seems to have less bitmaps but not all of them worked in Chrome. Then Chrome updated itself and now it rejects the font entirely, lol. OTS got smarter: "OTS parsing error: no supported glyph shapes table(s) present".

**Comment by rsheeter** [comment]
#397 shows changes. Seems like a more helpful mechanism than me copying code into comments.
