### ISSUE TITLE
fontTools Roadmap wiki page

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#399]
Guys, 

I've created a first draft of the fontTools Roadmap page which currently holds _my_ suggestions for some longer-term goals of where fontTools could evolve. This is by no means authoritative or definitive. Feel free to delete, edit, add or restructure. I think the wiki format is better for discussing longer-term goals, and I see it as complementary to this issue tracker: 
https://github.com/behdad/fonttools/wiki/Roadmap

Best,
Adam

**Comment by davelab6** [comment]
Thanks adam!

I don't recommend using the github wiki system, I think markdown files
within the main git tree is better, because the contributions to the wiki
aren't counted, and there is no pull request system there.
