### ISSUE TITLE
Add CFF operator specializer

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#403]
There's starting code Sam wrote last year:

https://github.com/samfishman/fonttools/commit/6998f15c4480862fb7f3c2cb314f94f0b243890e

It can be improved, but mostly it need tests to be added and integrated.

**Comment by anthrotype** [comment]
Things have improved with https://github.com/fonttools/fonttools/pull/940.

I was rereading the path operators chapter in the [Type2 spec](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5177.Type2.pdf
), and noticed that it's not just the `rcurveline` and `rlinecurve` operators that combine multiple segments, as Miguel noted, but also all the `*lineto` and `*curveto` ones can take "one or more" line or Bezier segments depending on the number of arguments on the stack.
With Miguel's patch, we currently add one `*lineto` or `*curveto` operator for each segment, even when we the same operator could draw multiple segments of the same kind.
So there's still room for optimization.
If we are happy with this (I am), I could tag a new release.

**Comment by behdad** [comment]
FWIW here's what AFDKO does:
https://github.com/khaledhosny/psautohint/blob/0e920ed195569eeae4b562893afa6c2d75a55d74/python/BezTools.py#L391

I'll comment extensively later.

**Comment by miguelsousa** [comment]
I've hooked up **psOperatorSpecializer.py** to the latest version of `t2CharStringPen` by doing this,
```python
from fontTools.misc.psOperatorSpecializer import simplifyCharstring
#...
program = simplifyCharstring(self._program) + ["endchar"]
```
and the only difference I saw was that the new charstrings use `rcurveline`.
The specializer does not implement `rlinecurve` and does not merge operators that can be combined.
So I think that at this point we're better off enhancing `t2CharStringPen` further.

**Comment by behdad** [comment]
I think we want to revert https://github.com/fonttools/fonttools/pull/940 and go with a separate specializer than the pen calls in the end, like Miguel did in the previous comments.  Main reason for this is such that we can optimize existing programs as well.

I have a design of a specializer (and a "de"specializer to go with it) which avoids the if-tree hell.  I like to give that a try.  The more tests we have the better...

**Comment by behdad** [comment]
Oh, and let's make cffLib a proper module directory and move all PS-related code from misc/ under cffLib and introduce more submodules...

**Comment by anthrotype** [comment]
sgtm

**Comment by behdad** [comment]
Another reason why we need a separate one is, to generate CFF2 varfonts, we want the specializer to take multiple master charstrings and specialize them all together (perhaps even produce blend operators at the same time), the same way that cu2qu converts multiple curves.

**Comment by miguelsousa** [comment]
SGTM too. I'll start working on the test cases.

**Comment by behdad** [comment]
My work is here: https://github.com/fonttools/fonttools/pull/948

**Comment by behdad** [comment]
Ok I'm done.  Please review https://github.com/fonttools/fonttools/pull/948
