### ISSUE TITLE
[wish] Compress `glyf` table via components

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#412]
Would anyone be willing to tackle implementing a "compress via components" function for the `glyf` table? FontForge has the `replaceWithReference`\* method which does this, implemented as [`FVBReplaceOutlineWithReference`](https://github.com/fontforge/fontforge/blob/master/fontforge/search.c). I’m not sure how much work that has been done in [compreffor](https://github.com/googlei18n/compreffor) could be re-used, but at least conceptually, this is not very different. 

> *) **[replaceWithReference](https://fontforge.github.io/python.html)**: Finds any glyph which contains an inline copy of one of the selected glyphs, and converts that copy into a reference to the appropriate glyph. Selection is changed to the set of glyphs which the command alters. If specified the fudge argument specifies the error allowed for coordinate differences.

**Comment by twardoch** [comment]
This is a rundown of the possible implementation: 

1. Identify each "contour set" within all glyphs. By contour set, I mean an "outer contour" and all "inner contours" that are fully encompassed within the outer contour. If one contour is fully within another contour, they belong to the same contour set. If one contour is outside of or intersects with another contour, they belong to separate contour sets. For example, the glyph "o" will typically have one contour set consisting of two contours, the glyph "ó" will typically have two contour sets and the glyph "ö" typically three.

2. Convert all coordinates within each contour set to be relative to the bounding box origin of that contour set, and store the relative offset of that contour set to the glyph's bounding box.

3. Find identical contour sets across all glyphs.

4. For each contour set, try to find its "parent glyph", i.e. the glyph where only that contour set is used and no other contour set is used. If a contour set has multiple candidates for parent glyphs, pick the glyph with the lowest absolute value of its offset, and if it still has multiple candidates, pick the glyph with the lowest glyph ID. For example, the glyph "ó" can be typically replaced by component references to "o" and acutecomb (U+0301) or acute (U+00B4). The glyph "ö" can typically be replaced by component references to "o" and dieresiscomb (U+0308) or dieresis (U+00A8). In some cases, it can be replaced by component references to "o" and two "dotaccentcomb" (U+0307). In that case, dieresiscomb would also typically be replaced by two dotaccentcomb (U+0307).

5. For every glyph consisting only of contour sets that have a parent glyph, replace the contour sets in that glyph with references (TrueType components) to the parent glyphs, taking the relative offsets into account.

6. Optional 2nd recursive operation: for every glyph that consists of >1 components, find a "parent glyph" which contains the same configuration of components (and only those), and replace with references. For example, if dieresiscomb refers to two dotaccentcomb (U+0307), and "ö" refers to "o" and two dotaccentcomb, then after this step, "ö" would refer to "o" and dieresiscomb.

**Comment by behdad** [comment]
This should be a tool on top of fonttools.
