### ISSUE TITLE
Add tests, cleanup, reorganize mtiLib

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#432]
I just pushed out code in fontTools.mtiLib that implements Monotype Imaging's OpenType Layout source format (GSUB/GPOS/GDEF):

http://monotype.github.io/OpenType_Table_Source/otl_source.html

The code is rough, doesn't implement feature and lookup addresses by name, has no tests, and lives at the module toplevel.  All of these need to be fixed!

Monotype has some more formats that will probably become Open Source, so moving the OTL code from **init** to a submodule makes sense.  Or maybe doesn't matter: we'll just introduce more tables to the same parseTable() (or whatever it will get renamed to).

**Comment by anthrotype** [comment]
:100:

**Comment by adrientetar** [comment]
Just wondering, why the interest in MT's format?

**Comment by behdad** [comment]
> Just wondering, why the interest in MT's format?

Because apparently some of the designers at Monotype can't be bothered with learning Adobe's format, so for some Noto fonts (Indic, East-Asian, etc), we are getting source deliveries in this format.  Although, it doesn't look hand-written to me, so I suppose they have a GUI that saves in this format.

The format is so simple and straightforward mapping of the binary, that I find it useful regardless.  I know I'd be hand-writing a few lookups in it (Turing machines!).  We can also use this, and the decompiler that will be added in feaLib, to convert these to Adobe's format in the future.

**Comment by twardoch** [comment]
fontTools supports other such tables, most notably for the VOLT and VTT data. I think it's a great thing that fontTools is aware of all SFNT tables that are publicly specified or are used by larger groups of people. Since Monotype published the spec, it's possible that they may piblish some tools that compile these tables. But even if the tools to compile these are currently proprietary, it's still good to have them. Also, let's not forget that pretty much all the Google Noto fonts are made by Monotype, and possibly that format is used in the sources.

**Comment by twardoch** [comment]
"Bosma joined Monotype in 1992. His role was to oversee TrueType production and hinting. One of Bosma's first projects for the company's UK office was to manage the production of Greek and Cyrillic core fonts for the Windows 3.1 operating system. Known for his work with non-Latin typefaces, Bosma has produced fonts for Hebrew, Thai, Arabic and Indic scripts. He relies a lot on his own software, including a truetype font editor called FontDame." — http://luc.devroye.org/fonts-33309.html

The name "FontDame" appears in the spec of the Monotype formats.

**Comment by behdad** [comment]
> "Bosma joined Monotype in 1992. His role was to oversee TrueType production and hinting. One of Bosma's first projects for the company's UK office was to manage the production of Greek and Cyrillic core fonts for the Windows 3.1 operating system. Known for his work with non-Latin typefaces, Bosma has produced fonts for Hebrew, Thai, Arabic and Indic scripts. He relies a lot on his own software, including a truetype font editor called FontDame." — http://luc.devroye.org/fonts-33309.html
> 
> The name "FontDame" appears in the spec of the Monotype formats.

Indeed.

Monotype released the spec on our request, as we cannot accept source material for Noto in an unpublished proprietary format.  While it would be great if they publish some source in the future, nothing is currently planned for this format as far as I know.

**Comment by miguelsousa** [comment]
> Because apparently some of the designers at Monotype can't be bothered with learning Adobe's format

AFAIK the FDK is not used at Monotype, so there may be no reason to learn its syntax.

**Comment by behdad** [comment]
Closing.  Testing, API, etc, will be continued in https://github.com/behdad/fonttools/issues/585

**Comment by behdad** [comment]
Tests integrated now in https://github.com/fonttools/fonttools/pull/787 as well.
