### ISSUE TITLE
fonttools 3.0 PyCompileError at install with python 2.6.6

### ISSUE THREAD

**Issue by kberry** [fonttools/fonttools#438]
I downloaded fonttools-3.0.tar.gz and ran "python setup.py install --user".
It installed many files, then aborted with this error:

py_compile.PyCompileError: SyntaxError: ('invalid syntax',
('build/bdist.linux-i686/egg/fontTools/merge.py', 467, 26,
'\t\tlookupMap = {id(v):v for v in table.table.LookupList.Lookup}\n'))

This is on centos 6.7, the system-provided python 2.6.6, i686.  I'll attach the full traceback.  At the moment, I'm stymied.  Any directions appreciated.

Thanks so much for ttx.  it is fantastic.  --karl@freefriends.org

[traceback.txt](https://github.com/behdad/fonttools/files/71851/traceback.txt)

**Comment by anthrotype** [comment]
hi @kberry 
I'm afraid, we no longer support Python 2.6.
It is quite tricky already to manage to support both python 2.7 and 3.3 (and above) with the same code base... :-/

**Comment by kberry** [comment]
unfortunate but understandable.  in that case, i suggest having setup bail out early with an explicit error message.

thanks again for the software.
