### ISSUE TITLE
[ttx] Use ttx file modification time for font "modified" timestamp

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#46]
I like to add a mode to ttx, such that when converting a ttx file to a font,
the timestamp of the the ttx file be used as the "modified" field in the font
head table.  Currently the "current time" is used.

With that mode, compiling the same ttx file without modifying it, will always
result in the same ttf file.  That's useful at least for testing.

Not sure whether this should be default.  Asked people on the list for their preference.

**Comment by bugfixtheworld** [comment]
Currently the timestamp will be again modified by default. There is no option to use the font "modified" timestamp. Need to reopen the issue?
