### ISSUE TITLE
Implement FontForge’s PfEd table

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#464]
Implement FontForge’s [PfEd table](http://fontforge.github.io/en-US/documentation/reference/non-standard/#PfEd), especially the GSUB and GPOS sub-tables.

Once implemented in core fontTools, feaLib can populate the names when compiling OpenType feature files. This would make it nicer to edit fontTools-generated fonts in FontForge.

Likewise, once feaLib implements decompilation, we could use table-supplied instead of synthetic names when de-compiling binary OpenType tables to feature files. This would make a fontTools-generated feature file easier to read, provided the font comes with a PfEd table.

If we do the same in mtiLib and voltLib, we can round-trip more information when converting feature files from one format to another.

**Comment by brawer** [comment]
@davelab6, since you’re using FontForge a lot, can you make a test font with an interesting PfEd table for testing? I can’t really promise to implement this anytime soon in fonttools myself, but a test font would clearly help.

**Comment by ctrlcctrlv** [comment]
@brawer Hello! I was just disappointed to see that the `PfEd` subtable was not recognzied at all by TTX and came across this thread.

I know I'm not @davelab6 , but I hope this will help.

I know FontForge well enough to create an interesting OTF file with a `PfEd` table. Below is my attempt. Let me know if you have any questions. The font in the file is extremely silly, its only purpose is to have an interesting PfEd table.

[IPFEDT.zip](https://github.com/fonttools/fonttools/files/1957574/IPFEDT.zip)

**Comment by ctrlcctrlv** [comment]
CC: @behdad @anthrotype

**Comment by anthrotype** [comment]
thanks @ctrlcctrlv for the test fonts. I don't have a urgent need for parsing fontforge's PfEd tables, but pull requests are welcome.

**Comment by ctrlcctrlv** [comment]
@anthrotype Hi! This isn't quite a pull request, but I wrote &approx;300 lines of a parser: https://github.com/ctrlcctrlv/OpenType_PfEd

It has some issues (see Issues tab) but wondering whether your thoughts have changed in three years on whether this is worth it, and if what I have is a good start or not in terms of fonttools/ttx support for the table.

**Comment by behdad** [comment]
I don't see this happening unless someone send a PR.
