### ISSUE TITLE
Can OS/2's usMaxContext be automatically determined during compilation?

### ISSUE THREAD

**Issue by jamesgk** [fonttools/fonttools#466]
If so, that might be a nice feature.

**Comment by benkiel** [comment]
My one request in adding to & changing FontTools is to keep the philosophy that it doesn't do anything 'magic' to a font. In other words, one can roundtrip a font via TTX with no changes to the data, other than what someone may have changed in the ttx file by hand. If you want it to automatically do things, great, but these should be turned on with switches, not part of the default behavior.

**Comment by behdad** [comment]
That field is extremely bogus.  That said, yes, we can add code to calculate it.

**Comment by anthrotype** [comment]
yes, I also think feaLib should be responsible for calculating this.
we can reuse @jamesgk's code from 
https://github.com/googlei18n/ufo2ft/blob/master/Lib/ufo2ft/maxContextCalc.py

**Comment by brawer** [comment]
Put it in otlLib? Then it can also work for other feature file formats, such as Monotype’s feature files or (eventually, once Denis finishes his library) VOLT.
