### ISSUE TITLE
[feaLib] Stripping away ValueRecords with ValueFormat zero

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#471]
When building SinglePos tables moved to otlLib, feaLib started stripping off SinglePos entries whose ValueRecord.ValueFormat is zero. However, `makeotf` emits such entries in its output, so we now have a discrepancy to makeotf. Question: Are we doing a valid optimization here, or are they semantically different? What if SinglePos lookup gets chained from another ChainContextPos lookup?

Sample input:

```
feature test {
    pos zero 0;
    pos four 500;
} test;
```

makeotf output:

```
      <!-- LookupCount=1 -->
      <Lookup index="0">
        <!-- LookupType=1 -->
        <LookupFlag value="0"/>
        <!-- SubTableCount=2 -->
        <SinglePos index="0" Format="1">
          <Coverage>
            <Glyph value="zero"/>
          </Coverage>
          <ValueFormat value="0"/>
        </SinglePos>
        <SinglePos index="1" Format="1">
          <Coverage>
            <Glyph value="four"/>
          </Coverage>
          <ValueFormat value="4"/>
          <Value XAdvance="500"/>
        </SinglePos>
      </Lookup>
```

feaLib output:

```
      <!-- LookupCount=1 -->
      <Lookup index="0">
        <!-- LookupType=1 -->
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <SinglePos index="0" Format="1">
          <Coverage>
            <Glyph value="four"/>
          </Coverage>
          <ValueFormat value="4"/>
          <Value XAdvance="500"/>
        </SinglePos>
      </Lookup>
```

**Comment by behdad** [comment]
This is an unsafe optimization *when and only when* other subtables might be appended after this one.  In other words, the semantic difference is that, when the entry is available (albeit all zero), it will stop searching forward in the subtables that follow.

It does not have any effect in chaining/context.

**Comment by behdad** [comment]
> This is an unsafe optimization when and only when other subtables might be appended after this one.

For this reason, I feel more comfortable if you don't drop it if it was specifically written in the input.

**Comment by brawer** [comment]
After the last change, there still is ine difference in the XML: The fontTools output contains an empty  `<Value/>` entry while the makeotf output does not have this. Probably an artifact, but I’ll fix it nevertheless.

makeotf:
```
      <!-- LookupCount=1 -->
      <Lookup index="0">
        <!-- LookupType=1 -->
        <LookupFlag value="0"/>
        <!-- SubTableCount=2 -->
        <SinglePos index="0" Format="1">
          <Coverage>
            <Glyph value="zero"/>
          </Coverage>
          <ValueFormat value="0"/>
        </SinglePos>
        <SinglePos index="1" Format="1">
          <Coverage>
            <Glyph value="four"/>
          </Coverage>
          <ValueFormat value="4"/>
          <Value XAdvance="500"/>
        </SinglePos>
      </Lookup>
```

fontTools:
```
      <!-- LookupCount=1 -->
      <Lookup index="0">
        <!-- LookupType=1 -->
        <LookupFlag value="0"/>
        <!-- SubTableCount=2 -->
        <SinglePos index="0" Format="1">
          <Coverage>
            <Glyph value="zero"/>
          </Coverage>
          <ValueFormat value="0"/>
          <Value/>
        </SinglePos>
        <SinglePos index="1" Format="1">
          <Coverage>
            <Glyph value="four"/>
          </Coverage>
          <ValueFormat value="4"/>
          <Value XAdvance="500"/>
        </SinglePos>
      </Lookup>
```

**Comment by behdad** [comment]
Ugh. I think I might have confused you.  If valueFormat is 0, no values for that array should be encoded.  I thought you were asking about dropping an item completely from coverage if its value was empty.

**Comment by behdad** [comment]
I think your output is equally valid in this case.

**Comment by behdad** [comment]
In the end, the OT compiler figures both out.

**Comment by brawer** [comment]
Actually, when stripping off the empty ValueRecord, the compiled GSUB table for the above feature file shrinks from 84 to 70 bytes (one less subtable). Since feaLib always puts the result of builder.compileSinglePos() into a separate lookup, and you’ve confirmed that omitting empty ValueRecords would not change the semantics for chaining, I wonder if the optimization should be brought back?

No idea how common it is to have “pos glyph 0” in actual feature files, but it would be a three-line change. On the other hand, we have bigger problems to solve. Such as making the compiler work in the first place.

**Comment by behdad** [comment]
> Actually, when stripping off the empty ValueRecord, the compiled GSUB table for the above feature file shrinks from 84 to 70 bytes (one less subtable). Since feaLib always puts the result of builder.compileSinglePos() into a separate lookup, and you’ve confirmed that omitting empty ValueRecords would not change the semantics for chaining, I wonder if the optimization should be brought back?
> 
> No idea how common it is to have “pos glyph 0” in actual feature files, but it would be a three-line change. On the other hand, we have bigger problems to solve. Such as making the compiler work in the first place.

Let's focus on correctness and completion for now.  Such optimizations can be very tricky to debug if they ever go wrong...

**Comment by brawer** [comment]
Current feaLib behaves like makeotf. Verified with test case `GPOS_1_zero`. Closing bug.
