### ISSUE TITLE
[feaLib] Change lookupType if more efficient

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#487]
Suggested by @twardoch: If the result is more efficient, emit a different lookupType than what is specified in the feature file. For example, these two are semantically equivalent:

```
pos [F T] [period]' -25;
pos [F T] [period] -25;
```

The first version (chain to single positioning) needs more space, and an additional lookup, compared to the second version (pair kerning). I could not find any examples where makeotf would change the lookup type, but perhaps it is worth considering. Just noting as an issue for now so we don't forget, I have no plans to work on this right now.

**Comment by khaledhosny** [comment]
Closing for the same rationale as #508.
