### ISSUE TITLE
only enable Travis/Appveyor email notifications for upstream repo

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#490]

**Comment by anthrotype** [comment]
If one has his own Travis/Appveyor account configured to build from a fork of fonttools repo, the email notifications shouldn't be automatically forwarded to the fonttools googlegroups mailing list.
Only pushes or pull requests to the upstream repo should trigger the email notification.
I'm not sure how to do this though...

**Comment by anthrotype** [comment]
Apologies for all the Travis and Appveyor notifications being forwarded to the googlegroups mailing list.

The only workaround I found is to comment out the notifications settings in the *.yml files with a temporary commit, and then revert that commit once I'm done testing stuff on my fork.
This is far from ideal.. 

BTW, there's an open issue about that on Travis repo:
https://github.com/travis-ci/travis-ci/issues/1094

**Comment by anthrotype** [comment]
I've now disabled the Travis and Appveyor hooks from my fonttools fork, so the mailing list won't get spammed any more.

**Comment by behdad** [comment]
I don't think this is an issue anymore.
