### ISSUE TITLE
define an API for options

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#495]
we need to find a better way to define optional parameters (e.g. "recalculate bounding boxes", "compress this font to WOFF 1.0 using zopfli",  etc.) without needing to change the TTFont constructor's signature every time we define new ones.

Suggestions?

**Comment by anthrotype** [comment]
I was thinking to define a bare `class Options(object): pass` in the `ttLib` module, and initialise that as an `options` attribute when constructing a `TTFont` instance.

I would also add a `**kwargs` argument to the `TTFont.__init__` and use its values to populate `self.options`.

I would also add to this `self.options` all the values of the existing arguments of `TTFont.__init__`, which we currently set as attributes of the TTFont instance itself. For example, I would make, e.g., `self.lazy` into `self.options.lazy` (and use a property decorator to make sure that scripts getting `self.lazy` will get the value of `self.options.lazy`).

I would also add a `**kwargs` argument to `TTFont.save`, specifying the export-time options (e.g. use zopfli), which I would pass on to the `SFNTWriter` instance.  Unlike the load-time options defined in the TTFont constructor, these export-time options would not be remembered by the TTFont instance (e.g. like the current `reorderTables` option).

Comments?

**Comment by behdad** [comment]
Done now I believe?
