### ISSUE TITLE
[feaLib] Optimize context-free chains

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#508]
Optimization idea for a rainy day: When a feature calls a ChainContextSubst/Pos lookup whose backtrack and lookahead are both empty, replace the call by a direct invocation of the chain target. It would not be totally trivial  to find out when exactly this optimization has no side effects, but it should certainly be possible.

This optimization would help when the authors of OpenType feature files were confused by the syntax. For example, the following two statements are semantically equivalent, but the former is more expensive both in terms of space and of execution speed. Also, it seems that Glyphs.app sometimes produces the former when the latter would do; but I have not looked into this in detail.

```
sub f' i' by f_i;
sub f i by f_i;
```

See also https://github.com/behdad/fonttools/issues/506.

**Comment by brawer** [comment]
And see https://github.com/behdad/fonttools/issues/509 for an example where this optimization, should we ever implement it, must _not_ be allowed to trigger.

**Comment by khaledhosny** [comment]
I’d rather close this. This would make feaLib compiler too smart for its own good; if authors choose less optimal syntax either 1) they know what they are doing and should not be silently overridden or 2) they don’t and it is their own fault, either case the compiler should do nothing.

**Comment by miguelsousa** [comment]
Agreed.
