### ISSUE TITLE
[otlLib] Optimization: Globally merge SingleSubst chain targets

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#513]
Optimization idea for a rainy day: Identify SingleSubst (GSUB type 1) lookups that are _only_ reachable as targets of chained contextual substitutions but are not directly part of any feature. Try merging these SingleSubst tables, provided that the combined size is smaller than the sum of the parts. This would be a global, cross-lookup version of a local optimization currently performed by makeotf and feaLib; see https://github.com/behdad/fonttools/issues/512.

Like with all optimizations, it would be important to profile the impact with non-toy workloads/fonts.

Personally, I’ve no intentions to implement this anytime soon, but wanted to write it down so it won’t be forgotten. Maybe somebody else want to give it a try some day.

**Comment by behdad** [comment]
Won't happen IMO.
