### ISSUE TITLE
[feaLib] ChainContextPos with empty lookahead and backtrack

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#516]
Currently, feaLib does not emit chaining contextual positioning tables if both backtrack and lookahead happen to be empty. However, makeotf still emit chains in such cases. For the time being, we should follow makeotf even though it means that our output becomes larger and slower to execute. There is no semantic difference in the example below, but this would be different if the statement happened to be preceded by `ignore pos`.

Input:

```
feature test {
    pos e' t' -10;
} test;
```

This is similar to https://github.com/behdad/fonttools/issues/506, but for `pos` instead of `subst`.

**Comment by khaledhosny** [comment]
Already fixed.
