### ISSUE TITLE
[feaLib] fea file compiler cmdline tool?

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#527]
Should probably take a font XML or binary as well as a fea file, and add GSUB/GPOS/GDEF to the output font XML or binary.

This might be easier if, as we discussed in London, we change ttLib to accept ttx as yet another flavor of fonts, such that ttx XML is automatically accepted everywhere a font file is accepted by our tools.

**Comment by behdad** [comment]
Thanks.  When it's fleshed out, add it as `__main__` to feaLib.

**Comment by brawer** [comment]
Seems done. Thanks, @anthrotype! https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/feaLib/__main__.py
