### ISSUE TITLE
Add http://editorconfig.org/ support

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#533]
To end tab/space issues, let's add editorconfig config file and we all adhere to it.

**Comment by adrientetar** [comment]
Or just check indent on Travis, this is what we do on the TF repo (flake8).

**Comment by behdad** [comment]
Well, I personally like a solution that would instruct my editor (vim) what to do...

**Comment by adrientetar** [comment]
Do you mean that it doesn't follow a file's preexisting indent by default?

**Comment by behdad** [comment]
> Do you mean that it doesn't follow a file's preexisting indent by default?

At the expense of showing my ignorance: no it doesn't.  Perhaps it's my problem.  I'll take a look.

But the issue of spaces whether tabs was brought up both with @anthrotype and @justvanrossum, so it's good to come up with a solution.  But then again, maybe our current "respect the file's style" is good enough.  I'm happy with such a resolution.
