### ISSUE TITLE
file created too early in TTFont.save()

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#536]
If an exception occurs during compilation, an empty file remains. This isn't so bad per se, but when overwriting the original file this destroys the original, which is rather nasty. It can probably be fixed by moving the file creation block to after the SFNTWriter is done.

**Comment by behdad** [comment]
Or maybe create the output in a tmp file and only rename it if compilation was successful, and remove it otherwise.

In general the case of output and input filenames being equal is dangerous, so I wouldn't mind if we disallow that.

**Comment by behdad** [comment]
> But how to best modify in place?

What do you mean?

**Comment by madig** [comment]
> > But how to best modify in place?
> 
> What do you mean?

I often want to do an op on a font without creating a new file, is that discouraged?

**Comment by behdad** [comment]
> I often want to do an op on a font without creating a new file, is that discouraged?

That's fine. Just that internally it creates a new file then rename it onto the old file name. In the operating system it creates a new file, such that if the process was still reading the old file (the source), it can keep doing that uninterrupted.
