### ISSUE TITLE
differences in str(float) between Python 2 and 3

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#549]
The fonttools xmlWriter also has the same problem with `str(float)` in python 2 and 3 as ufoLib, so I pinpoint the issue in here as well:

https://github.com/unified-font-object/ufoLib/issues/19

See for example:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/misc/xmlWriter.py#L146

**Comment by behdad** [comment]
I think we can close this now?
