### ISSUE TITLE
[feaLib] Handle dash in glyph names

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#559]
I know this has been discussed before, but it's still a pain, that glyphs2ufo chained to ufo2ft can fail.  In my example:

```
fontTools.feaLib.error.FeatureLibError: features.fea:12:5179: Bad range: "LL" and "middleWelsh" should have the same length
```

I like to suggest two changes to feaLib, both of which will ideally be pushed to AFDKO / Fea spec as well:
- A dash, when following a backslash, can be part of a glyph name to mean a single 'dash' and as such work around the current limitation that dashes cannot be part of glyph names.  In fact, I'd go as far as suggesting that a backslash would escape any punctuation to be part of the glyph name,
- When the above-mentioned error occurs, ie. when a dash range fails to parse, then try parsing the dashed sequence as a glyph name (only if there were no spaces involved).  In fact, in most cases, either a range or a glyph name is valid, not both.  It's ok to fail if there is ambiguity.

Implementing one or both of these makes the glyphs2ufo+ufo2ft experience much better.  Right now, fontmake replaces dashes with underscores before calling the above tools.  That's too much to ask each client to do.

@schriftgestalt @jamesgk

**Comment by khaledhosny** [comment]
Feature files already use the backslash to escape whole glyph names to avoid conflict with reserved words as well as for CIDs, how would that work here?

**Comment by schriftgestalt** [comment]
I don't think we need new markup. 

In my makeotf fork, I added method that accepts hyphens as part of glyph names and in case if can’t find a glyph to a name and the name has a hyphen, it treats it as a range. This works very well. You suggested a similar solution that first checks for range and then for glyph name. That can work well, too. It depends on the parser what method fits better. 

Adding backslash is not a good idea, very designer unfriendly ;)

**Comment by twardoch** [comment]
@schriftgestalt I remember you told me the MakeOTF implementation of ranges was flawed in some other aspects. Can you remond us what was the problem there?

**Comment by schriftgestalt** [comment]
There is no flaw. The spec and implementation are not matching up.

from the spec:
> For non-CID fonts, the ordering is independent of the ordering of glyphs in the font. 'firstGlyph' and 'lastGlyph' must be the same length and can differ ...

The implementation in makeOTF does the opposite. It does use the GID of the first and second glyph and uses all GIDs in between.

**Comment by schriftgestalt** [comment]
Both approaches have fundamental problems. According to spec it I can’t think of any possibility to make a range with anything else then basic latin letters (A-z) or uniXXXX names. All other glyph names have different length. And it seems to imply to use the unicode index ranges. and those are discontinues and all over the place. 

The implemented version has problems too as the content of the class does depend on the glyph order. So if you have a font and the feature code uses a range, lets say `A-Z` (and assume the glyphs are ordered in a way that it would result in a class of the 26 glyphs of basic latin uppercase. Then someone, at a later points adds an `B.ss01` and puts the glyph just next the `B`. This will break the feature code.

**Comment by behdad** [comment]
> The implementation in makeOTF does the opposite. It does use the GID of the first and second glyph and uses all GIDs in between.

Ouch!

> Both approaches have fundamental problems. According to spec it I can’t think of any possibility to make a range with anything else then basic latin letters (A-z) or uniXXXX names. All other glyph names have different length. And it seems to imply to use the unicode index ranges. and those are discontinues and all over the place.

Sure.  I think they were mostly designed for "a-z".  Their usefulness is beside the point right now.

With your proposal, an ambiguous name will parsed as a glyph name.  I like to make an ambiguous name (one that can legally be parsed as a range, ie. the resulting glyph names also exist) an error.  For that to work, we need a way to resolve the disambiguity.  If the range is desired, space can be placed around the dash.  If the glyph name is desired, then my proposed backslash escaping can use.  Designers don't normally need to know about that; only if an ambiguity arises, and the tool can tell them exactly what to do.  As for computer-generated feature files, the escape will be there; but even that can be optimized to only escape if there is ambiguity.

Any name with more than one dash should always be considered a glyph name and no range-parsing tried.

**Comment by behdad** [comment]
CC @readroberts

**Comment by schriftgestalt** [comment]
I don't thing we need the backslashes. It you where intending to write a range and the parser reads it as a glyph name, it will throw and error because the other side of the substitution is a class and that wouldn't match. 
We need a simple recommendation that if you have names with hyphen, always add spaced to a range. 
And in my list is no possibel ambiguous name. Do you have an example.

**Comment by behdad** [comment]
> I don't thing we need the backslashes. It you where intending to write a range and the parser reads it as a glyph name, it will throw and error because the other side of the substitution is a class and that wouldn't match.
> We need a simple recommendation that if you have names with hyphen, always add spaced to a range.
> And in my list is no possibel ambiguous name. Do you have an example.

It doesn't matter if I have an example or not.  We want to design a well-defined spec / implementation.  That said, I can imagine, eg. HEBREW_LETTER_HE being name he-he, which would be a degenerate case.  THAI LETTER TO might be called th-to, etc.  In these cases, quite possible, the individual pieces won't be a valid glyph name in the font.

So, you are saying, the ambiguous won't happen.  I say if it happens, we escape.  Looks like the two statements can co-exist :).

**Comment by schriftgestalt** [comment]
>  In these cases, quite possible, the individual pieces won't be a valid glyph name in the font.

My point.

If it is handled as a name by default, then the escaping would not be needed.

**Comment by behdad** [comment]
> If it is handled as a name by default, then the escaping would not be needed.

Fine :).  Let's see if we can get @readroberts to agree.

**Comment by benkiel** [comment]
> Right now, fontmake replaces dashes with underscores before calling the above tools. That's too much to ask each client to do.

In my view, this is an issue with an editor deciding to output final glyph names that don't follow a long standing specification. I disagree that changing a long standing specification is the solution, this would be as if someone decided to change the formatting of a scripting language and then asking all the other implementations of that language to also change.

This seems like an issue for glyphs2ufo to solve, not the other way around.

**Comment by twardoch** [comment]
There is a possibility `-` will be accepted in the FEA spec and by FDK after all, see https://github.com/LettError/glyphNameFormatter/issues/11

**Comment by schriftgestalt** [comment]
> In my view, this is an issue with an editor deciding to output final glyph names that don't follow a long standing specification.

That has nothing to do with final glyph names. The final glyph names will not contain hyphens. But the design names and feature code will. Makeotf can switch design name (in char strings and feature files) into production names with the GlyphOrderAndAliasDB file. So nobody asked to change the spec, just a tiny addition to one of the tools we use.

**Comment by LettError** [comment]
Georg, the advantages of the hyphen are rather subjective and only appear to benefit Glyphs. Whereas the potential points of failure this change will introduce in interoperability, existing code, legacy code and legacy projects are much broader than Glyphs. Can we bill the time for cleaning that up to you or Monotype?

**Comment by schriftgestalt** [comment]
There are two points what make potential problems very improbable that could allow me to agree to Eriks request ;)

What can go wrong if hyphens are allowed in glyph names?
With legacy data? Nothing as there is no ambiguity because no hyphen in names. It will always fall back to ranges.

If someone does decide to use hyphens:
1. define glyph names that are not ambiguous (no name be made from two other names connected with a hyphen)
2. use ranges with spaces

Can anyone give me a valid example where this would fail?

**Comment by benkiel** [comment]
> So nobody asked to change the spec (of final fonts (added after Adams comment showed up)), just a tiny addition to one of the tools we use.

@schriftgestalt that's what @behdad is suggesting at the start of this. And, yes, I misspoke (miswrote?) when I said final names, you're right that this is about the feature code not the final names.

However, I had not seen the thread that @twardoch pointed to, so it does seem that this may be changed in the FDK. I do understand why Glyphs does what it does with names and don't have any issues with it doing so, one is free to do whatever they want with their application; my reservation has to do with changing a long standing specification because an application deliberately choose to ignore that spec. I still think that this is better dealt with at the level of things that interact with Glyphs, but I respect whatever @readroberts chooses to do here.

**Comment by brawer** [comment]
Personally, I think fonttools/feaLib should implement the published specification, not deviate from it. The proposed fallback logic sounds quite interesting, but I think it would need to become part of the spec before fonttools implements it. (Otherwise, we'll have a chaos pretty quickly).

**Comment by behdad** [comment]
Closing for now.

**Comment by moyogo** [comment]
`makeotf` supports the hyphen in development glyph names since 2.5.65322 which was released last week.

https://github.com/adobe-type-tools/afdko/blob/2.5.65322/FDK/FDKReleaseNotes.txt#L51

> makeotf
> [...]
> Finally integrated Georg Seifert's code for supporting hyphen in development
	glyph names. This version differs from Georg's branch in that it does not
	allow any of the special characters in final names, the left side names in
	the GlyphAliasAndOrderDB. However, allowing this is a smaller tweak than it
	used to be: just use the same arguments in cb.c:gnameFinalScan() as in
	gnameDevScan(). This update also includes Geeorg Seifert's changes for allow
	source fonts to have CID names in the form 'cidNNNN'.

**Comment by readroberts** [comment]
No. I thought I had updated the MakeOTF user guide, but the new characters are currently documented nowhere. The current set is "- + * : ~ ^ !". Note that the only spec for final glyph names in a font is still the Postscript  and Type 1 specs, which do not permit these characters. I don' t think there should be an official  spec for development glyph names, which can be anything that a set of development tools support. I do agree that a set of shared conventions would be useful. I will add documentation for the FDK names to the MakeOTF user guide.

**Comment by brawer** [comment]
At the risk of waxing philosophical: isn’t the core purpose of a _language specification_ to specify, in very clear and un-ambiguous terms, what exactly the implementations are supposed to implement? If the spec leaves any room for interpretation, feature files are unlikely to work across different compilers. So we’d lose interoperability, causing trouble to font designers.

For that reason, I wonder if the structure of glyph names could be formalized in the feature file syntax specification itself. Actually, (re-)reading the current spec, it seems quite clear what’s permitted in a glyph name. If a compiler implements something different than what the spec says, wouldn’t that be clearly a bug in the compiler that should be fixed? And if people think the language should be changed, the way to go would be changing the spec, so that all implementations can do the same thing?

**Comment by readroberts** [comment]
I do agree that the feature file spec should say what characters are allowed in glyph names.

**Comment by brawer** [comment]
Thanks to @readroberts, the feature file spec has been adjusted: https://github.com/adobe-type-tools/afdko/commit/ca96616549079967c03a19f9ae26f8ae8c18024f (at least in GitHub master, not on the Adobe website yet). I’m now working on the implementation. Not sure yet how to do this re-try logic in fonttools, but I’ll find some way.
