### ISSUE TITLE
[Wish] Option "desubroutinize" in TTX

### ISSUE THREAD

**Issue by Arno-Enslin** [fonttools/fonttools#565]
Subroutinization can cause trouble with regard to the hinting in FontLab Studio 5.0.4. If you autohint a subroutinized font with the AFDKO, open it in FontLab Studio and generate it, the hinting can become partly damaged. By the way, that is one of the reasons, why I would like to have [a bug fixed autohint macro for FontLab.](https://github.com/adobe-type-tools/afdko/issues/119)

FontTools subset has the option "desubroutinize". It would be very nice, if TTX would have that option, too. If possible, an option "subroutinize" would be likewise useful.

As workaround you can use the subset tool, extract the CFF table with TTX and merge it into the source font. But that is not comfortable.

[My workaround](https://github.com/adobe-type-tools/afdko/issues/129)

**Comment by behdad** [comment]
You can write a short script to do that. I don't think we'll add such options to ttx.
