### ISSUE TITLE
Adopt Github's new issue templates system

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#572]
A month ago, Github finally gave repo maintainers an ability to create templates for the issues they're reporting: 
- https://github.com/blog/2111-issue-and-pull-request-templates
- https://help.github.com/articles/helping-people-contribute-to-your-project/
- https://help.github.com/articles/creating-an-issue-template-for-your-repository/

Seems simple enough — just create a `.github/ISSUE_TEMPLATE.md` template file in the repo with some Markdown, and the contents of that file will be pre-populated into the textbox whenever a user opens a new issue. Here's a simple template that could be adopted.

``` md
<!--- Provide a general summary of the issue in the Title above -->

### Type of issue
<!--- What is the type of this issue? Put an `x` in all the boxes that apply: -->
- [ ] Bug report
- [ ] Feature request

### Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

### Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

### Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

### Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

### Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

### Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:
```

**Comment by brawer** [comment]
Just curious, which problem would this solve?

**Comment by twardoch** [comment]
It can be used in an extensive or a lightweight way. The more a product is enduser-facing, the more standardization and guidance its issue tracker requires. fontTools is used mostly by developers so it may not need as much "template". Though perhaps reminding the issue reporter to cite their Python and OS version might be useful. 

So perhaps it's not that relevant for fontTools after all, but may be useful for some other projects like Noto fonts or Google Fonts (@davelab ?). I've set it up in a repo I'm managing and it helps a lot. :)

**Comment by brawer** [comment]
Seems we can live without...
