### ISSUE TITLE
Test Jython on Travis?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#575]
See https://github.com/behdad/fonttools/commit/68500cbfe8e6a9650b3e5676805f6571f020c98c#commitcomment-17091895

Unfortunately tox does not play nicely with jython at the moment.
https://bitbucket.org/hpk42/tox/issues/326/oserror-not-a-directory-when-creating-env

I tried running `py.test` on our test suite from a jython 2.7.0 installed locally on my OS X machine.
There are **28** tests that fail. 

So I guess we do need to have automated tests for Jython if we would like to support it... but, do we?

**Comment by behdad** [comment]
Google Fonts runs subsetter on Jython.  So, we (Google) at least care about parts of the codebase running on Jython.

**Comment by anthrotype** [comment]
Ok. Let's keep this open until we improve the support for jython. In the meantime, we can see the test report with #576
