### ISSUE TITLE
String slicing performance in Python...

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#580]
...is really poor!

In FontTools there still are many places where as we parse binary data, we advance the "cursor" by just slicing the rest of the string.  Eg.:

```
    numInstructions, = struct.unpack(">h", data[:2])
    data = data[2:]
```

You can grep for these:

```
$ git grep 'data = data\['
```

Since strings / bytes are immutable in Python, for many years, I assumed that slicing is cheap.  Ie., strings can share underlying memory or something.  But https://github.com/behdad/fonttools/commit/bf28ca10d70bccce57306e921e36d09a7b353851 proved that that's indeed not the case.

I think I fixed the most egregious instances of this.  Still, it's just annoying that one would have to pass a string and index around, instead of just the string.  Filing here mostly just for documentation, and to see if Just has any insights on this.  I'm not going to bother reporting to Python itself as I'm sure this has had been brought up many times there.

@justvanrossum

**Comment by anthrotype** [comment]
Of course, slicing always returns a copy. We should avoid that whenever not needed.

**Comment by behdad** [comment]
> Of course, slicing always returns a copy. We should avoid that whenever not needed.

I definitely know that it returns a new object.  But the implementation does not *have* to be done by copying underlying memory all the time.  There exist better implementations; it's just that CPython (and probably all other implementations) does it this way.

**Comment by anthrotype** [comment]
Python has memoryviews which can be sliced without copying.

**Comment by behdad** [comment]
> Python has memoryviews which can be sliced without copying.

Ah, excellent.  Had forgotten about that. So, yes, I think we should switch to using those in places that we are doing slicing.  And revert https://github.com/behdad/fonttools/commit/bf28ca10d70bccce57306e921e36d09a7b353851 and fix it properly.

**Comment by behdad** [comment]
> Python has memoryviews which can be sliced without copying.

Ah, excellent.  Had forgotten about that. So, yes, I think we should switch to using those in places that we are doing slicing.  And revert https://github.com/behdad/fonttools/commit/bf28ca10d70bccce57306e921e36d09a7b353851 and fix it properly.

Humm.  Is there a way to implement the buffer interface from Python itself?  All I find is C API.

**Comment by behdad** [comment]
Oh, I see I need to create a buffer() object first.  So, memoryview(buffer(x)) can be used...

**Comment by behdad** [comment]
> Oh, I see I need to create a buffer() object first. So, memoryview(buffer(x)) can be used...

Nope.  Buffer() just creates a sub-buffer of an object that already supports the buffer interface.

**Comment by behdad** [comment]
Ok, I see the buffer protocol is a CPython thing.  Still, I wish the full flexibility of numpy's arrays (ie, multi-dimensions) was available in stock Python.

Also, I don't understand why the array module does not support loading non-native endian directly.  Eg. we have to call byteswap() manually.

**Comment by anthrotype** [comment]
Python2's str and Python3's bytes both support the buffer interface, so they can be used with memoryview

https://docs.python.org/2/library/stdtypes.html#memoryview
https://docs.python.org/3/library/stdtypes.html#memoryview

**Comment by anthrotype** [comment]
Cython offers typed memoryviews, which are as fast and versatile as numpy arrays
http://docs.cython.org/src/userguide/memoryviews.html

**Comment by behdad** [comment]
I also find it bizarre that the mmap module does NOT implement buffer protocol!  I'm trying to speed up TTFont() construction by avoiding actually reading the file, but that doesn't seem to be possible.

**Comment by behdad** [comment]
> Python2's str and Python3's bytes both support the buffer interface, so they can be used with memoryview
> 
> https://docs.python.org/2/library/stdtypes.html#memoryview
> https://docs.python.org/3/library/stdtypes.html#memoryview

Yes, figured that much.  Been reading a lot about buffer protocol since your first comment.

**Comment by behdad** [comment]
> I also find it bizarre that the mmap module does NOT implement buffer protocol! I'm trying to speed up TTFont() construction by avoiding actually reading the file, but that doesn't seem to be possible.

Ok, making progress there.  Will send a PR for this particular issue.

**Comment by HinTak** [comment]
Hmm, many years ago I worked on something similiar to this, and re-worked not-so-recently the two python scripts which unpacks and re-pack PCL XL data in the ghostscript code base. Slice'ing is slow, and same with string concatenation - argh, I remember the performance problem was with string concatenation... and the answer was to keep stuff in arrays (which are mutable) most of the time, until it needs to be in strings.

would cStringIO help?
