### ISSUE TITLE
Finish otlLib and harmonize feaLib, mtiLib, and voltLib APIs

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#585]
Here's a list of things to clean up, preferably before a release.  Perhaps we can all get together in Berlin and hack on these.
- mtiLib: Add tests.  Import from Monotype spec repo.
- otlLib: Finish moving code from mtiLib / feaLib here, and review / polish the API.
- mtiLib & feaLib: Compare API and harmonize.
- mtiLib & feaLib: Add **main**.
- varLib: Refactor and add **main**.

**Comment by behdad** [comment]
* Improve test coverage.

**Comment by behdad** [comment]
* Figure out what to do re new pens / move symfont into proper place.

**Comment by behdad** [comment]
mtiLib error reporting: print line number as well as input line.

**Comment by anthrotype** [comment]
what's the status of this?
maybe is it too general and should be split up into separate issues?
