### ISSUE TITLE
[subset] Add a mode for subsetting to a exact string of text

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#59]
Originally I didn't intend the subsetter to be used like this, but now people are doing things like the autonym font:

  https://github.com/santhoshtr/AutonymFont

We can make those fonts much smaller by subsetting to just enough GSUB/GPOS rules to support a certain input text (as opposed to any combination of a set of input characters).

**Comment by brawer** [comment]
Seems implemented; current pyftsubset has a `--text` option.

**Comment by behdad** [comment]
> Seems implemented; current pyftsubset has a --text option.

Not really.  That's different.  But we can close bug.  I don't think I'll get to implement this any time soon.
