### ISSUE TITLE
Optimization: Emit ClassDef1 if smaller

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#591]
This is an optimization to reduce GDEF size, implemented by makeotf. See https://github.com/adobe-type-tools/afdko/issues/89.

**Comment by behdad** [comment]
Note that we do emit ClassDef1 if smaller.  The issue at hand is to include items with classDef 0, to reduce the number of ranges that need to be emitted in a ClassDef1.

**Comment by behdad** [comment]
Ie. if you have classes for glyphs 10..13 and 15..19, then it's more efficient to include glyph 14 with class 0, such that only one range is emitted...

**Comment by behdad** [comment]
Humm.  I was wrong.  It looks to me like we do this optimization correctly already.  Maybe the difference is only when the format 1 and format 2 will be the same size?

**Comment by behdad** [comment]
I've checked again; I don't think there's anything to do here.
