### ISSUE TITLE
[cffLib] illegal/useless entries in `FontDict` of CID-keyed CFF

### ISSUE THREAD

**Issue by mashabow** [fonttools/fonttools#601]
Currently, `cffLib` allows many illegal/useless entries in `FontDict` of CID-keyed CFF ([cffLib.py#L1434](https://github.com/behdad/fonttools/blob/a796b033660ba0ee0fc04153e09c9b5defd17bec/Lib/fontTools/cffLib.py#L1434)). Please see <https://github.com/adobe-type-tools/afdko/issues/137> for details on the spec.

For example, this is a `FontDict` element from TTX dump of [WidthTest-Regular.otf](https://github.com/adobe-fonts/width-test/blob/master/WidthTest-Regular.otf).

```xml
        <FontDict index="0">
          <FontName value="WidthTest-Regular-Latin"/>
          <isFixedPitch value="0"/>                 <!-- useless -->
          <ItalicAngle value="0"/>                  <!-- useless -->
          <UnderlineThickness value="50"/>          <!-- useless -->
          <PaintType value="0"/>                    <!-- useless -->
          <CharstringType value="2"/>               <!-- useless -->
          <FontMatrix value="0.001 0 0 0.001 0 0"/>
          <FontBBox value="0 0 0 0"/>               <!-- useless -->
          <StrokeWidth value="0"/>                  <!-- useless -->
          <Encoding name="StandardEncoding"/>       <!-- illegal -->
          <Private>
            <BlueValues value="-12 0 638 650"/>
            <BlueScale value="0.0625"/>
            <BlueShift value="7"/>
            <BlueFuzz value="0"/>
            <StdHW value="68"/>
            <StdVW value="86"/>
            <ForceBold value="0"/>
            <LanguageGroup value="0"/>
            <ExpansionFactor value="0.06"/>
            <initialRandomSeed value="0"/>
            <defaultWidthX value="600"/>
            <nominalWidthX value="0"/>
          </Private>
        </FontDict>
```

Regardless of its value, these "useless" entries have no effect in OpenType. Furthermore, the spec explicitly prohibits `Encoding` and `CharStrings` entries.

I think it would be nice if `cffLib` raises warnings or errors for such entries, and the TTX dump would become as follows, though we might have to consider compatibility with existing files.

```xml
        <FontDict index="0">
          <FontName value="WidthTest-Regular-Latin"/>
          <FontMatrix value="0.001 0 0 0.001 0 0"/>
          <Private>
            <BlueValues value="-12 0 638 650"/>
            <BlueScale value="0.0625"/>
            <BlueShift value="7"/>
            <BlueFuzz value="0"/>
            <StdHW value="68"/>
            <StdVW value="86"/>
            <ForceBold value="0"/>
            <LanguageGroup value="0"/>
            <ExpansionFactor value="0.06"/>
            <initialRandomSeed value="0"/>
            <defaultWidthX value="600"/>
            <nominalWidthX value="0"/>
          </Private>
        </FontDict>
```

### Related specs

- [Adobe CMap and CID Font Files Specification #5014](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5014.CIDFont_Spec.pdf)
- [The Compact Font Format Specification #5176](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5176.CFF.pdf)
- [PostScript Language Reference, Third Edition](http://www.adobe.com/products/postscript/pdfs/PLRM.pdf) —5.11 CID-Keyed Fonts

**Comment by moyogo** [comment]
@mashabow the useless entries are not written to XML TTX anymore and are ignored.

Please reopen if you don’t think this has been fixed.
