### ISSUE TITLE
[subset] Name Record default break EOTs

### ISSUE THREAD

**Issue by cjdunn** [fonttools/fonttools#605]
When using fontTools.subset the default should be that all name entries stay the same, unless otherwise specified.

Currently the default setting includes ONLY name entries 1 and 2, but this breaks EOTs as mentioned here:
https://github.com/behdad/fonttools/issues/114

To get around this I currently have to add:
--name-IDs=\*  --name-legacy

**Comment by Arno-Enslin** [comment]
> To get around this I currently have to add:

You also can specify name IDs.

Example: --name-IDs+=3, 4, 5, 6

Just test, which name IDs eot needs.

Maybe you could replace the names of these IDs with a dummy (just one character) for the case, that the pure existence of these IDs is important for eot, but not the content. You could automate that by decompiling (only) the name table first with TTX and with the help of a find and replace tool or script. And then you merge the name table into the source font and run the subset script with the option "--name-IDs=*".

**Comment by cjdunn** [comment]
@Arno-Enslin thank you for your response. I know I can get around this, that's not the problem. My issue is about what should be the default behavior. I spoke with @behdad and @justvanrossum about this a bit, and it sounded like my proposal was reasonable. Perhaps I didn't phrase my initial issue clearly. 

I think that fundamentally a subsetter should be agnostic (not make assumptions) about what font info names I want to keep or not keep by default. The names I put in should be the names I get out, unless I tell it otherwise. 

From the documentation. 

> Example:
>   Produce a subset containing the characters ' !"#$%' without performing
>   size-reducing optimizations:
> 
>   $ pyftsubset font.ttf --unicodes="U+0020-0025"


I think this line of code should subset down to just the requested characters ' !"#$%'  and should otherwise leave my data alone. But currently this will also remove a bunch of my font info names unless I explicitly tell it otherwise, which I think is a bug. If I wanted to remove other font info names I should have to request that explicitly, by using an option such as: 

>   $ pyftsubset font.ttf --unicodes="U+0020-0025" --obfuscate_names

But otherwise I think the subsetter should leave the names as is.

**Comment by behdad** [comment]
I asked CJ to file this to remind us changing default nameIDs to work on all platforms.
We should also add option "profiles"..

**Comment by anthrotype** [comment]
we changed the defaults of subset module to keep all nameIDs from 0 to 6
