### ISSUE TITLE
Request: MTX compression EOT making

### ISSUE THREAD

**Issue by benkiel** [fonttools/fonttools#607]
This may well be outside the scope, but if font tools could make MTX compressed EOTs, I'd be very grateful to never have to deal with sfntly.

**Comment by anthrotype** [comment]
yeah, it's on my list...
for now we only have basic bindings for the Monotype's LZCOMP compression library here:
https://github.com/anthrotype/lzcomp

**Comment by anthrotype** [comment]
@benkiel in the meantime, you could also use this: https://github.com/daltonmaag/sfntly-py
It's still sfntly, but wrapped up as a python subprocess.
Pre-built binaries are available in the Releases section.

**Comment by benkiel** [comment]
@anthrotype that is so helpful, thank you

**Comment by behdad** [comment]
@anthrotype Any progress on this?  Shall we take a look at it together in Warsaw?

**Comment by anthrotype** [comment]
No progress, I've been busy with other stuff.. but sure, we can have a look in Warsaw.

**Comment by madig** [comment]
What is missing to make fonttools read and write EOTs?

**Comment by jenskutilek** [comment]
Is EOT necessary anymore? MS Edge does not support it, IE versions 9+ have WOFF support.

**Comment by madig** [comment]
We have some legacy at DaltonMaag that forces me to deal with EOT 😭

**Comment by campbellgraphics** [comment]
My customers using adobe muse need eot for self hosted solutions.
Unfortunately.

**Comment by anthrotype** [comment]
EOT is pretty much dead nowadays. I don't have the time to work on this, I'm afraid.
The interim solution (until EOT fades away) is to use Google's sfntly Java library.
There's a python wrapper here https://github.com/daltonmaag/sfntly-py

**Comment by benkiel** [comment]
@anthrotype Should we just close this? I understand that it's likely not worth the effort.

**Comment by khaledhosny** [comment]
Closing per above two comments.
