### ISSUE TITLE
Telugu subsetting issue: ˚F

### ISSUE THREAD

**Issue by shyndman** [fonttools/fonttools#616]
w/ degrees Fahrenheit:
http://codepen.io/shyndman/pen/LZpNYz?editors=1100

correct rendering:
http://codepen.io/shyndman/pen/OXyNPd?editors=1100

**Comment by anthrotype** [comment]
same here, I'm afraid I don't understand what the issue is. Could please you elaborate?

**Comment by behdad** [comment]
@shyndman Attach screenshot please.

**Comment by khaledhosny** [comment]
That is a bug in the font, `abvs` feature maps glyph for U+0C48 TELUGU VOWEL SIGN AI to a glyphs that looks like ˚F, and somehow this substitution shows up only in the subset font.

**Comment by khaledhosny** [comment]
Testing with the font from https://github.com/google/fonts/blob/master/ofl/mallanna/Mallanna-Regular.ttf:
```
$ hb-view Mallanna-Regular.ttf "మైన"
```
![full](https://user-images.githubusercontent.com/93914/53689887-7deba880-3d68-11e9-9bb6-87d7adc60ac3.png)

```
$ pyftsubset Mallanna-Regular.ttf --text="మైన"
$ hb-view Mallanna-Regular.subset.ttf "మైన"
```
![subset](https://user-images.githubusercontent.com/93914/53689888-9b207700-3d68-11e9-88ad-c254af34e4ca.png)

@davelab6

**Comment by behdad** [comment]
Still, weird that happens.  We should figure out what's going on.

**Comment by behdad** [comment]
okay probably the fact that HB wants to decompose AI matra into two characters.  Subsetter doesn't know that.  Yeah, probably safe to ignore.  Would be nice if subsetter was smarter though.

**Comment by khaledhosny** [comment]
We have #615 for this.
