### ISSUE TITLE
Move to github.com/fonttools org

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#639]
@anthrotype can you prepare a CL for moving the CI integrations?  I think I also need to do some stuff manually to move coveralls, AppVeyor, etc?

**Comment by anthrotype** [comment]
sure.. but what's a "CL"? 😁

**Comment by twardoch** [comment]
Obviously, a "CL" is "a Cosimo Lupo".

**Comment by behdad** [comment]
Hahaha.  My bad.  The github lingo is a "PR".  CL as in ChangeList; some other code-review systems use that.

**Comment by anthrotype** [comment]
Before we can move the CI, we need to create the the new repository
https://github.com/fonttools/fonttools.

You need to do this first:
https://help.github.com/articles/about-repository-transfers/

**Comment by anthrotype** [comment]
any news on moving the repo to https://github.com/fonttools/fonttools?

**Comment by behdad** [comment]
Yes I wanted to do this and get a release or begir atypi but was busy with opentype-gx branches.  Can we look into it on Tue night?

**Comment by behdad** [comment]
Done.  Please fix up any continuous-integration things it broke!

**Comment by anthrotype** [comment]
Both Travis and Appveyor CI are now hooked up to the new fonttools/fonttools repo.
