### ISSUE TITLE
[hmtx] advanceWidth should be USHORT, why does fonttools reads it as SHORT?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#645]
It seems intentional, but why?
https://github.com/behdad/fonttools/commit/035bc7da2318f0dcacecba2e1e24c0a4bf3cf80c#diff-f1a37102608ecea22d52a8cb91aba526R21

Also see: https://github.com/googlei18n/ufo2ft/pull/60

**Comment by behdad** [comment]
I believe it was like that and in the port from numpy to array I decided not to change semantics.  I agree it needs to be fixed.
