### ISSUE TITLE
ttGlyphPen uses 0 and 1 instead of False and True

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#657]
.

**Comment by anthrotype** [comment]
do you mean in `TTGlyphPen._addPoint`?
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/pens/ttGlyphPen.py#L29

well, that's what the `_g_l_y_f.Glyph.flags` array expects, ie. a list of `0` and `1` for `flagOnCurve`:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L517
