### ISSUE TITLE
[subset] Subset color glyph formats

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#66]
There's four of them...
- [x] CBLC/CBDT
- [x] COLR/CPAL
- [x] sbix
- [ ] SVG (https://github.com/fonttools/fonttools/issues/534)

**Comment by khaledhosny** [comment]
CBLC/CBDT and COLR/CPAL are already done, and SVG is tracked on #534.

**Comment by khaledhosny** [comment]
`sbix` done in #1674.

**Comment by khaledhosny** [comment]
Closing since SVG subsetting is tracked in #534 and the rest are done.
