### ISSUE TITLE
Request for limited extrapolation support in VariationModel

### ISSUE THREAD

**Issue by LettError** [fonttools/fonttools#671]
With the understanding that _extrapolation_ beyond the values defined by the masters is not supported in variable **fonts**, it may still be useful for font authoring tools (using VariationModel and MathGlyphs for instance) to be able to _preview_ extrapolated shapes at designspace locations beyond the furthest master.
- An axis would need to continue at the rate of change it has at the extreme.
- It is understood that this will not be part of a variable font
- It is understood that when moving further away from the last master the shapes will become useless very quickly. 
- Experience shows that there are interesting and useful shapes _near_ the last masters.
- There are benefits for font authoring tools to be able to use the exact algorithm from varlib rather then simulate the effects.

https://github.com/behdad/fonttools/blob/master/Lib/fontTools/varLib/__init__.py#L70

**Comment by twardoch** [comment]
+1

**Comment by behdad** [comment]
I'm temporarily removing this from my TODO list.  But feel free to ping me later, specially when we implement reading axis limits from new designspace syntax.

**Comment by LettError** [comment]
Ok, understood. With "new designspace syntax", do you mean https://github.com/LettError/designSpaceDocument#1-axis-element ?

**Comment by behdad** [comment]
> Ok, understood. With "new designspace syntax", do you mean https://github.com/LettError/designSpaceDocument#1-axis-element ?

Yes.  I'll eventually get to that.  By eventually meaning, hopefully before Labs.

**Comment by behdad** [comment]
I have a PR in https://github.com/fonttools/fonttools/pull/2757
Also, closing in preference to https://github.com/fonttools/fonttools/issues/1252
