### ISSUE TITLE
fontTools.version.__version__ is "unknown"

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#680]
I install fontTools by simply having fonttools/Lib on my sys.path (through a .pth file).
`fontTools.version.__version__` is "unknown" in my case. Am I doing something wrong?

**Comment by justvanrossum** [comment]
The error being hidden in `fontTools/version.py` is
`DistributionNotFound: The 'fontTools' distribution was not found and is required by the application`

**Comment by anthrotype** [comment]
you can do `python setup.py egg_info` so that the version string is stored in the package metadata and pkg_resources can read from that.

**Comment by anthrotype** [comment]
Although I would recommend you do `pip install --editable .` (preferably inside a virtualenv so you don't screw other projects which depend on different versions).

**Comment by justvanrossum** [comment]
I like to live dangerously and went the egg_info route. Thanks! Next up: not to forget to do that again  whenever PKG-INFO gets updated :(

**Comment by anthrotype** [comment]
BTW, `egg_info` is always run before the `test` command, so as a developer you will be running `python setup.py test` quite often.
End-users in font production should install fonttools from the released distribution, so they get a well defined version string.
