### ISSUE TITLE
[varLib] Need to support Platform 1 and 3 in name table

### ISSUE THREAD

**Issue by robmck-ms** [fonttools/fonttools#683]
varLib should generate a variable font with both platform 1 and 3 names. Previously, it did only platform 1. Recently, it switched to only platform 3. These fonts wouldn't work on OSX (though the older ones did): FontBook said that the instances were all duplicates of each other, and all instances other than Regular looked like the light. If I simply add platform 1 entries to the name table for the nameids referenced from var, the font works fantastically.

(already emailed Behdad on this).

**Comment by anthrotype** [comment]
Thanks Rob. For reference, this is the commit in question:
https://github.com/fonttools/fonttools/commit/24346aaa88fbd78299b86caa3411e86ecc3ec001

**Comment by anthrotype** [comment]
@robmck-ms I wonder if we can use platformID=0 (Unicode) instead of platformID=1 (Macintosh). Would that work on OSX?

**Comment by robmck-ms** [comment]
@anthrotype Having platformID=0 makes more sense to me as you wouldn't need both 1 & 3. I tried it, though, with the same symptoms as with a font with platformID=3 only.

**Comment by anthrotype** [comment]
yeah, I also tried Unicode platformID but didn't work. So I guess we are stuck with both MacRoman and Windows. :-/

**Comment by robmck-ms** [comment]
I *think* it was El Capitan (10.11), but I'm not 100% certain. That sounds about right for what I was running at the time, as I didn't switch to Sierra right away. Unfortunately, none of the email I can find on the subject mentioned the OS version.

**Comment by anthrotype** [comment]
Thanks. IIRC, El Capitan was released before OpenType variations became officially supported (Sierra 10.12 I think was the first), so maybe that limitation of platformID=1 was the legacy of the old TrueType GX code.
In whic case, perhaps we could stop adding Mac names in fvar by default, and only use Windows (unicode) names.

/cc @justvanrossum

**Comment by anthrotype** [comment]
after  #3688, varLib no longer adds MacRoman names for variations-related tables (fvar, STAT) unless the name table of the default master ttf already contained some. fontmake/ufo2ft don't normally create those (unless sources have low-level name record definitions with explicit platformID).
