### ISSUE TITLE
Cannot change woff compression level with sfnt.ZLIB_COMPRESSION_LEVEL

### ISSUE THREAD

**Issue by severinmeyer** [fonttools/fonttools#686]
Currently, setting `sfnt.ZLIB_COMPRESSION_LEVEL` to a custom value does not have any effect.

The culprit: [Lib/fontTools/ttLib/sfnt.py#L496](https://github.com/fonttools/fonttools/blob/1eba7b383c785924a33c30f6e38cebd571819a5f/Lib/fontTools/ttLib/sfnt.py#L496)

The problem is that `zlibCompressionLevel` is accessed as an instance variable, but it is actually declared as a class variable at [Lib/fontTools/ttLib/sfnt.py#L481](https://github.com/fonttools/fonttools/blob/1eba7b383c785924a33c30f6e38cebd571819a5f/Lib/fontTools/ttLib/sfnt.py#L481). As a result, it is instantiated once when the module is loaded, and any later change of `sfnt.ZLIB_COMPRESSION_LEVEL` is not propagated.

Possible solution: Ditch the variable and use `ZLIB_COMPRESSION_LEVEL` directly:
```python
if not self.uncompressed:
    compressedData = compress(data, ZLIB_COMPRESSION_LEVEL)
```

**Comment by anthrotype** [comment]
Right. Or you could also set the `WOFFDirectoryEntry.zlibCompressionLevel` class attribute to the value of you choice?

**Comment by brawer** [comment]
@severinmeyer, do you want to send a pull request?

**Comment by anthrotype** [comment]
The thing is, that `zlibCompressionLevel` class attribute was already there when I added Zoplfi support with https://github.com/fonttools/fonttools/commit/7fafe1f9a71f78b371e9b8670c157810c2e60211.
It was set to a constant value, 6, the same as the global variable ZLIB_COMPRESSION_LEVEL that I added.
So the previous as well as current way to set a different zlib compression level is to set that attribute on the WOFF directory entry class. If we remove that, and use the global module variable, then existing code that uses the other approach will break.
I suggest we keep it like that and the user adjust the compression level via the class attribute.

**Comment by severinmeyer** [comment]
That makes sense.

However, it still seems problematic to use **self.**zlibCompressionLevel, because it doesn't exist and falls back to the class variable. Which is why I assumed this is a mistake in the first place.

Now, forgive me if I make a fool of myself, but is there any documentation on how to change the compression level? Because I ended up following the `--with-zopfli` option, which activates zopfli via `sfnt.USE_ZOPFLI` [here](http://github.com/fonttools/fonttools/blob/1eba7b383c785924a33c30f6e38cebd571819a5f/Lib/fontTools/ttx.py#L264). It therefore seemed obvious that the compression level should be changed with `sfnt.ZLIB_COMPRESSION_LEVEL` [right next to it](http://github.com/fonttools/fonttools/blob/1eba7b383c785924a33c30f6e38cebd571819a5f/Lib/fontTools/ttLib/sfnt.py#L136-L141).

In any case, I highly value FontTools and simply try to figure out how to use it correctly.

**Comment by anthrotype** [comment]
> it still seems problematic to use self.zlibCompressionLevel, because it doesn't exist and falls back to the class variable.

I don't think this is problematic, it's just how attribute lookup works in Python.

> there any documentation on how to change the compression level?

Unfortunately not, and it is not exposed at the console scripts level, but that can change if there's demand.

> --with-zopfli option, which activates zopfli via sfnt.USE_ZOPFLI

Yeah, that use of global variable is a temporary hack, and I don't like it either (see also discussion here https://github.com/fonttools/fonttools/pull/493#issuecomment-178041014). I'll shall fix it once I complete refactoring of sfnt module (splitting up a separate woff.py module, similar to woff2.py, using class inheritance to avoid duplication). I have it in my stash but haven't finished yet.

> I highly value FontTools and simply am trying to figure out how to use it correctly.

and we highly value feedback and contributions, so please feel welcome here!

**Comment by severinmeyer** [comment]
Thank you.

Changing the compression level is a bit wonky, but I now understand the reasoning.
A refactoring will solve this issue anyway, so I consider it solved.

**Comment by anthrotype** [comment]
actually, I had a second look at it and I changed my mind :)
Setting the compression level on the WOFFDirectoryEntry class will not have any effect on any compressed WOFF Metadata, which will still use the global default.
So I will apply your suggested change (using the module's `sfnt.ZLIB_COMPRESSION_LEVEL`), but in a retro-compatible way.
Thank you!
