### ISSUE TITLE
Remove top-level sstruct and xmlWriter?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#696]
Now that `extra_path=FontTools` is gone from our setup.py (see https://github.com/fonttools/fonttools/pull/695), I would like to use this opportunity to also drop support for the stand-alone `sstruct` and `xmlWriter` modules that we still install to site-packages alongside the main `fontTools` package.

These were at some point moved by Behdad to their current location, inside fontTools.misc package, but they were subsequently restored to their original position (as aliases) after some users started complaining about sudden ImportErrors.

I think we can now safely drop those, as compatibility with the "sourceforge" fonttools is no longer so important.

Anybody who still relies on importing from those instead of the fontTools.misc.\* counterparts, could keep using version 3.1.2. But future versions would no longer have them.

WDYT?

/cc @justvanrossum @LettError @typemytype @typesupply @benkiel

**Comment by justvanrossum** [comment]
That would have been fine if DeprecationWarnings had been issued for a while. I suggest to do that anyway, and wait a release or two with removing them.

**Comment by anthrotype** [comment]
Ok, let's do that.

**Comment by justvanrossum** [comment]
I think Adobe used these module as well, I remember @frankrolf mentioning it back then.

**Comment by anthrotype** [comment]
It should be easy to replace this:

```python
from xmlWriter import XMLWriter
```
with this:
```python
from fontTools.misc.xmlWriter import XMLWriter
```

The reason I want remove them is that, without the containing "FontTools" folder which was previously created by the deprecated `extra_path` setup keyword, now we are kind of polluting the  site-packages with extra modules which are outside of the `fontTools` namespace.

It is conceivable for another unrelated project to use the names `xmlWriter` or even `sstruct`. With `extra_path`, one would mask another in the sys.path; without the `extra_path`, one risks overwriting the other...

Anyway, I'll just add the deprecation warning for now.

**Comment by typemytype** [comment]
I dont understand what the issue is... Did you encounter other packages using a different `sstruct` and `xmlWriter`?
And if so, it would be nice to send PR to all of these: https://github.com/search?p=1&q=%22from+xmlWriter+import+XMLWriter%22+language%3APython&ref=searchresults&type=Code&utf8=✓ <https://github.com/search?p=1&q=%22from+xmlWriter+import+XMLWriter%22+language:Python&ref=searchresults&type=Code&utf8=%E2%9C%93>

(github seems not to be able to search for an exact match...)



gr Frederik
www.typemytype.com

**Comment by anthrotype** [comment]
Well, my point of view is that ideally `fontTools` as a library should be self-contained in its own package.
There might be historical reasons why `sstruct` and `xmlWriter` were put outside of the core `fontTools` package. But now I think we could all agree on moving those inside it for good.
It's not such a big deal to change one line in the code, no?

**Comment by justvanrossum** [comment]
Indeed historical reasons, or simply not very good reasons. The extra_path things has always been ugly, I had completely forgotten about it. It's just too bad noone thought of adding a deprecation warning before.

**Comment by typemytype** [comment]
+1 for a deprecation warning (for a couple of versions)

my concern is not my code base, its idd one line of code, but all the scripts out there of well willing type designers which will freak out if it doest work. They already will freak out of that warning and ask around what todo...

gr Frederik
www.typemytype.com

**Comment by anthrotype** [comment]
I see.. But if they are knowledgeable enough to now how to use sstruct and xmlWriter, they will definitely know what to do, I think ;)

**Comment by justvanrossum** [comment]
Exactly. Also: I know of people using xmlWriter separately, but I have never even heard of anyone using sstruct directly.

**Comment by pnemade** [comment]
Good to see this getting fixed before any new upstream release.

**Comment by anthrotype** [comment]
I'm going to proceed removing the top-level `sstruct` and `xmlWriter` aliases in the 3.3.0 release in the next few days, if nobody has objections.
