### ISSUE TITLE
varLib `_merge_OTL` assumes presence of GPOS table

### ISSUE THREAD

**Issue by djrrb** [fonttools/fonttools#699]
Is there a reason that a GPOS table is required to generate a GX font using `varLib/__init__.py`? I was trying out a monospaced font and hitting an error. Removing the `"GPOS"` string from the tables argument of `merge_tables()` seemed to fix it, but I wasn't sure if you had reasons for hardcoding that table in.

**Comment by anthrotype** [comment]
passing an empty list to `merge_tables` is like skipping it altogether.
I guess the whole `_merge_OTL` function should be skipped in there's no GPOS -- but I'm not 100% sure. /cc @behdad
