### ISSUE TITLE
support for unregistered axes

### ISSUE THREAD

**Issue by cjdunn** [fonttools/fonttools#703]
Right now the only axes that seem to work are the registered Weight, Width, Slant, Optical. The [spec says](https://www.microsoft.com/typography/otspec/fvar.htm) other axes can be used:

> Tags are registered for commonly-used design axes, but foundry-defined tags may also be used

When I have a non-standard name in my designspace file varLib won't generate a var font. Is there something else I need to do to get this to work?

**Comment by anthrotype** [comment]
I think this might be a duplicate of https://github.com/fonttools/fonttools/issues/701 ?

**Comment by cjdunn** [comment]
ah yep, you're right : )
