### ISSUE TITLE
Move codec for Variation adjustment deltas to another place?

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#704]
While glancing over the code for decoding/encoding Variation Adjustment Deltas, I wondered if [GlyphVariation.decompileDeltas_()](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_g_v_a_r.py#L716) and [GlyphVariation.compileDeltaValues_()](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_g_v_a_r.py#L614) should become public methods. Variation deltas are used both in `gvar` and in `cvar`, so if we ever implement the latter table, it might be good to move it out of `gvar` — but what should be the new place?

**Comment by behdad** [comment]
I wouldn't sweat it.  You can import them from `gvar` into `cvar`.

**Comment by twardoch** [comment]
Agree with Behdad
