### ISSUE TITLE
[varLib] Generated HVAR renders wrong on FreeType CFF2 branch

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#705]
Need to debug.

**Comment by behdad** [comment]
This is bug in FreeType; it double applies the HVAR and glyf tables.

**Comment by robmck-ms** [comment]
Any chance we could get a command-line switch or something for enabling/disabling HVAR support, for those of us who also test on other platforms?

**Comment by behdad** [comment]
Err. Yes.  Can you submit a dirty hack kind of a pull-request?  The whole varLib interface is a dirty hack, so I don't mind at all.

**Comment by robmck-ms** [comment]
Ok. Done. https://github.com/fonttools/fonttools/pull/733

**Comment by brawer** [comment]
@lemzwerg, can FreeType now handle `HVAR` correctly without also handling phantom points in `gvar`? Afaik the bug has been fixed, but thanks for confirming. Once you confirm, we can re-enable `HVAR` generation in fontmake and fonttools.

**Comment by lemzwerg** [comment]
You mean the `OpenType-1.8` branch, right?  Dave Arnold has indeed provided an experimental fix.

http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=410ff09eb6866881907cf51eeae79e41f9375c1b

**Comment by behdad** [comment]
Ok, this should be fixed now.  Waiting for freetype and fontview release before re-enabling.

**Comment by brawer** [comment]
[fontview 0.1.8](https://github.com/googlei18n/fontview/releases/tag/v0.1.8) can handle HVAR because it uses a pre-release version of FreeType (commit hash 01658be6fbda2ff17616158ae5df5dc240a4347c). For example, [Selawik-variable](https://github.com/unicode-org/text-rendering-tests/blob/master/fonts/Selawik-variable.ttf), which has an HVAR table, gets displayed without apparent problems.

**Comment by anthrotype** [comment]
btw, would be nice to also have some unit tests for HVAR.

**Comment by anthrotype** [comment]
Freetype 2.7.1 was released last week. Shall we re-enable HVAR for TTFs?

**Comment by lemzwerg** [comment]
Support of HVAR is not complete yet; it only provides advance variation and still misses LSB (and RSB) handling.

**Comment by behdad** [comment]
Should we remove the --build-HVAR option completely and always build now?  Someone please do that or change the default.

**Comment by anthrotype** [comment]
I just removed the `--build-HVAR` option and re-enabled HVAR for TTFs.
