### ISSUE TITLE
With regard to D_S_I_G_.py: Dummy DSIG does not decompile anymore

### ISSUE THREAD

**Issue by Arno-Enslin** [fonttools/fonttools#715]
TTX is not able to decompile my dummy signatures anymore. I have a few fonts, into which I had merged the following "decompiled" dummy DSIG:

```
<?xml version="1.0" encoding="ISO-8859-1"?> 
<ttFont sfntVersion="OTTO" ttLibVersion="2.2"> 
		<DSIG>
			<hexdata>
44756D6D79
			</hexdata>
		</DSIG> 
</ttFont>
```

44756D6D79 is the hex code for "Dummy". If I open a font file with the dummy signature in a text editor, the text "Dummy" is displayed near to the bottom of the file.

Now I have to merge the following code into a font instead, if I want to create a comparable dummy signature. "RHVtbXk=" is the base64 code for "Dummy".

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="OTTO" ttLibVersion="3.0">
  <DSIG>
    <tableHeader flag="0x1" numSigs="1" version="1"/>
    <SignatureRecord format="1">
RHVtbXk=
    </SignatureRecord>
  </DSIG>

</ttFont>
```

Because I would like to avoid decompiling problems with my dummy signature in future versions of TTX/D_S_I_G_.py, I would like to know, if my new code is the best solution for adding a dummy signature.

**Comment by benkiel** [comment]
@Arno-Enslin Yes. A while (several years, pre-GitHub font tools, possibly in this commit, https://github.com/fonttools/fonttools/commit/91bca4244286fb519c93fe92329da96b0e6f32ee, but I remember it changing earlier than this) the format for de-complied DSIGs changed to your second example. Things shifted from being a dumb hex dump of the table (what TTX does with tables it doesn't know about) to a smarter representation of it.

**Comment by Arno-Enslin** [comment]
Thank you.

If I set raw="True" in the DSIG-Tag, TTX adds the hexdata dummy signature to the font file. I have to do more tests. Just for interest.

**Comment by anthrotype** [comment]
Hi Arno,
in your first xml snippet, the DSIG table hexdata is incomplete, because it lacks required structures like the header, number of signatures, etc.

Note that the dummy DSIG table can also be empty (i.e. containing no actual signature records), as it's just the mere presence of a DSIG table in a font which makes Windows and other MS application treat a .ttf file as an OpenType font rather than a plain TrueType font.

```python
import sys
from fontTools.ttLib import TTFont, newTable


def add_empty_DSIG(font):
    if 'DSIG' in font:
        del font['DSIG']
    dsig = newTable('DSIG')
    dsig.ulVersion = 1
    dsig.usFlag = 0
    dsig.usNumSigs = 0
    dsig.signatureRecords = []
    font['DSIG'] = dsig


def main():
    fontfile = sys.argv[1]
    font = TTFont(fontfile)
    add_empty_DSIG(font)
    font.save(fontfile)

if __name__ == "__main__":
    main()
```

That's how an empty DSIG table looks like in TTX:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.1">

  <DSIG>
    <!-- note that the Digital Signature will be invalid after recompilation! -->
    <tableHeader flag="0x0" numSigs="0" version="1"/>
  </DSIG>

</ttFont>
```

**Comment by Arno-Enslin** [comment]
Well, it should not be empty. With regard to your Python script: How can I put the text "Dummy" into SignatureRecord with the help of that script? It would be better to do this with a Python script like yours, because then I had not to care about the attributes of the ttFont tag. In the past I had used batch scripts, which created decompiled dummy DSIG-tables and merged them into the fonts. But your solution with the Python script is better, because it cares about the sfntVersion and the ttLibVersion.

**Comment by anthrotype** [comment]
as I said, it's better empty than an invalid PKCS7 structure, but if you really want to, here's how to do it:

```python
import sys
from fontTools.misc import sstruct
from fontTools.ttLib import TTFont, newTable, getTableModule


def add_dummy_DSIG(font, data=b"dummy"):
    if 'DSIG' in font:
        del font['DSIG']
    dsig = newTable('DSIG')
    dsig.ulVersion = 1
    dsig.usFlag = 1
    dsig.usNumSigs = 1
    sigrec = getTableModule('DSIG').SignatureRecord()
    sigrec.ulFormat = 1
    sigrec.pkcs7 = data
    sigrec.cbSignature = len(sigrec.pkcs7)
    sigblock_length = sstruct.calcsize(
            getTableModule('DSIG').DSIG_SignatureBlockFormat)
    sigrec.ulLength = sigrec.cbSignature + sigblock_length
    header_length = sstruct.calcsize(
        getTableModule('DSIG').DSIG_HeaderFormat)
    record_length = sstruct.calcsize(
        getTableModule('DSIG').DSIG_SignatureFormat)
    sigrec.ulOffset = header_length + dsig.usNumSigs * record_length
    sigrec.usReserved2 = sigrec.usReserved1 = 0
    dsig.signatureRecords = [sigrec]
    font['DSIG'] = dsig


def main():
    fontfile = sys.argv[1]
    font = TTFont(fontfile)
    add_dummy_DSIG(font)
    font.save(fontfile)

if __name__ == "__main__":
    main()
```

and in TTX:

```xml

<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.1">

  <DSIG>
    <!-- note that the Digital Signature will be invalid after recompilation! -->
    <tableHeader flag="0x1" numSigs="1" version="1"/>
    <SignatureRecord format="1">
-----BEGIN PKCS7-----
ZHVtbXk=
-----END PKCS7-----
    </SignatureRecord>
  </DSIG>

</ttFont>
```

**Comment by Arno-Enslin** [comment]
Thank you!

> as I said, it's better empty than an invalid PKCS7 structure

Okay. But I primary wanted to avoid compiling/decompiling problems with TTX. Now only the PKCS7 structure is invalid. With my origin code, with the help of which I had merged hexdata into the fonts, tableHeader and SignatureRedord were completely missing. But I will consider to spare the dummy text in future. (I only wanted to have it, because I directly can see it at the bottom of a font file, if I open it in a text editor.)
