### ISSUE TITLE
[ttx] make LF the default line endings for all platforms?

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#716]
As you know, the fonttools XMLWriter currently uses the platform-specific line endings when writing TTX files: i.e., LF (`"\n"`) for Unix (e.g. Linux, macOS) or CR+LF (`"\r\n"`) for Windows -- well, CR (`"\r"`) for the old Macintosh platform but we don't support it any more.

So depending on where one produces a TTX file, this may end up with different end of lines characters.

I've added support for overriding the XMLWriter `newlinestr`, and `ttx` script now has a `--newline` option: https://github.com/fonttools/fonttools/pull/714.

Some have suggested in there that we make the LF or `"\n"` the default newline character for all platforms, including Windows.

Personally I'm OK with that, however I would like to first hear from any Windows users, whether they expect to be able to view/edit TTX files in Notepad.exe (in which only CRLF are supported), or whether they OK with using other text editors without such limitation?

**Comment by adrientetar** [comment]
sgtm

**Comment by khaledhosny** [comment]
I’d just always use `\n` and forget about it. It is 2016 already.

**Comment by Arno-Enslin** [comment]
@ anthrotype

**If you** keep the new newline option, I don't understand, why another default newline character could be problematic for Windows users. I am Windows (only) user. If I wouldn't use UltraEdit, but Notepad, I just would set the newline option to CRLF.

**Comment by anthrotype** [comment]
let's keep it as it is for now.
