### ISSUE TITLE
[ttxjson] Best fontTools.ttLib method to force deep decompilation of all SFNT tables?

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#718]
I've written a little tool that does SFNT-to-JSON conversion called **`ttxjson`**: 
https://github.com/twardoch/fonttools-utils/tree/master/ttxjson

I have a simple question:
1. What's the best way to force decompilation of a given SFNT table in a fontTools.ttLib.TTFont object? 
2. What's the best way to force decompilation of **all** SFNT tables in a fontTools.ttLib.TTFont object?

I'm serializing the font into JSON using the [`jsonpickle`](https://jsonpickle.github.io/) module, and it works nice, but right now, I need to resort to a trick to decompile the tables, and would like to know if there is a faster way. BTW, the nice thing about `jsonpickle` is that it also does the reverse, from JSON to Py objects, though I haven't tried. 

Here's what I currently do to force decompilation:

``` python
    templist = [font[tag] for tag in tables]
```

where tables is a set or list of table tags I want decompiled (custom or taken from `font.keys()`). Is there a better way?

**Comment by graphicore** [comment]
[offtopic] Very nice, Adam, thanks for sharing! Did you also have a look at [otfcc](https://github.com/caryll/otfcc)? I like how it uses unix pipes to pass the json around e.g. here [otfcc-cubic2quad](https://github.com/caryll/otfcc-cubic2quad) 
In general I must say I like the idea of using json for this, it's just so much easier to parse than the custom xml like in ttx.

**Comment by anthrotype** [comment]
Hey Adam,

That's cool. I've played once with PyYAML to do something very similar.

> What's the best way to force decompilation of a given SFNT table

`__getitem__` will decompile the table, e.g. `font[tag]`

> What's the best way to force decompilation of all SFNT tables

yes, what you already do is what I'd do, `[font[tag] for tag in font.keys()]`.

**Comment by anthrotype** [comment]
you may also want to load the `TTFont` with `lazy=False` so that stuff like glyphs in the `glyf` table are decompiled immediately.
