### ISSUE TITLE
[varLib] Incorrect component offset 

### ISSUE THREAD

**Issue by djrrb** [fonttools/fonttools#722]
Using the latest fontTools varLib `__init__.py` to create a variable font, components of zero-width combining accents seem to shift to the right as the location gets further and further from the default. The offsets look fine in all of the ttfs generated by `fontmake -o ttf-interpolatable`. 

I've built it several times and get the same result. This could totally be my fault, but since the issue seems to be isolated to the var font, I figured I'd let you know. Happy to e-mail you font data if it's helpful. Thanks!

<img width="871" alt="screen shot 2016-10-24 at 7 49 13 pm" src="https://cloud.githubusercontent.com/assets/6578861/19668089/2ffe647c-9a23-11e6-87a5-205745d1c600.png">

**Comment by behdad** [comment]
Can you please email me your designspace and ttf files?

**Comment by anthrotype** [comment]
has this been fixed?

**Comment by behdad** [comment]
> has this been fixed?

Don't think so.  Though, I'm not sure if I received input files either.

**Comment by behdad** [comment]
@djrrb did you send me the source?  Is this still valid?

**Comment by djrrb** [comment]
I'm so so sorry, not sure why I didn't see these notifications. This seems to no longer be an issue.

**Comment by behdad** [comment]
Humm. No idea what fixed it though...
