### ISSUE TITLE
worrying size changes round-tripping, lost 10% of file size. 

### ISSUE THREAD

**Issue by HinTak** [fonttools/fonttools#726]
All the information is in https://github.com/fonttools/fonttools/issues/725, but since I cannot re-open it, I'll just file another one.

Somebody else can get hold of the font files, and get the right ones based on the md5sums.

I'll eventually get back to this one day, if nobody get beat me to it.

It seems crazy to close  https://github.com/fonttools/fonttools/issues/725 so soon. As I said, I do not want to spend time on this right now, not even just to provide more information. All the information is there. Somebody else can beat me to it and look at it earlier, if they want to.

Please leave this open.

**Comment by justvanrossum** [comment]
It's crazy to start a new issue if your issue isn't reopened within seconds. I'm looking into it right now, I found the files despite you not giving a source, I'll report back in the other issue.
