### ISSUE TITLE
Feature Request: Subsetting and Merging Variable Font axes

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#727]
Per Nick Shinn's proposal in http://typedrawers.com/discussion/comment/23887/#Comment_23887 I suppose that fontTools ought to perform subsetting and merging of Variable Font axes.

Eg, a VF has 34 axes and I'm only interested in 3 of them for my webpage, I'd like to subset the font to make it load faster.

**Comment by PeterCon** [comment]
That would certainly be useful... after FontTools is fully supporting creation of all the new tables in OT1.8.

**Comment by davelab6** [comment]
For sure! Just wanted to file this idea for later, so it wasn't lost =)

**Comment by behdad** [comment]
I call this operation "partially instantiating".  Eg. set the width, but retain weight axis.  There's a tiny issue with doing these with respect to the 0x91 GETVARIATIONS hinting instruction.  We need to go back to rewriting those as 0x92 and use IDEF to fill in the removed axes.

**Comment by davelab6** [comment]
> I call this operation "partially instantiating"

Yes, this sounds like a good name :) 

Related question: is 'full instantiating' a named instance of a VF into a 'legacy' non-VF font supported today in fontTools? If yes, how to do it? :)

**Comment by behdad** [comment]
> Related question: is 'full instantiating' a named instance of a VF into a 'legacy' non-VF font supported today in fontTools? If yes, how to do it? :)

The start of that is in fontTools.varLib.mutator.

I have to merge `varLib.__init__`, `varLib.instantiate_layout`, and `varLib.mutator` into the same architecture, instead of having to implement everything three times.
