### ISSUE TITLE
"make install-user" is slow

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#728]
I use "make install-user" to check that I didn't break setup.py.  However, it takes forever.  16 seconds here.  If that is the "right" way to do it, I don't mind if we remove Makefile again and I've internalized "./setup.py install --user" which only takes 2 minutes.

**Comment by anthrotype** [comment]
> I use "make install-user" to check that I didn't break setup.py.

That's what `tox` is for. It runs `setup.py sdist`, installs that into a temp virtual environment and runs the test suite. We use it for the CI, but you can run it locally too. Just `pip install tox`, then do `tox`, which will do all the above for both python2.7 and python3.5 (these must be on your `$PATH`), or use `tox -e py27` or `tox -e py35`, etc.

I don't know why it takes you so long, on mine it takes 4.9 seconds. Are you using the latest pip 8.1.2? 

`python setup.py install` uses setuptools' `easy_install` and creates an `.egg` package. The latter is being discouraged in favour of the wheel distribution format. `pip install {options} .` still runs `setup.py install` under the hood, but doesn't create an egg, and gives you all the features of pip.

I also don't mind removing Makefile.

**Comment by behdad** [comment]
Just running tox also modified my _version.py.  Just leaving things as is.  All these additional tools just complicate my development environment.  For now the ./fonttools script makes me happy.  Thanks.

**Comment by anthrotype** [comment]
you should clean up your python environment, as there must be something wrong with it.
Search you python path and uninstall any fonttools you find, check that `easy_install.pth` does not contain any dead reference, clean up .pyc/__pycache__ files, check symlinks, etc.
If you can find why it's happening, then it could be a bug in some of the tools.
