### ISSUE TITLE
[varLib] instance names & axis names broken in new version (3.2.1)

### ISSUE THREAD

**Issue by cjdunn** [fonttools/fonttools#735]
after upgrading to the latest version, when I generate a var font with the same files that previously worked the instance names are replace by the copyright info from:
 <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">

and same thing for the axis names, they are also replaced by the copyright info.

**Comment by anthrotype** [comment]
I don't understand what you mean the instance/axis names are replaced by the copyright info.
Could you attach or send privately the TTX dump for the name table and your designspace file?

I wonder if it may be related to this commit:
https://github.com/fonttools/fonttools/commit/14509af47c47fb2862c88f88c93648aa9e834629

**Comment by cjdunn** [comment]
Looking closer I see that this is because I upgraded my env to the latest fonttools, varlib etc. But when generating from the new env I was still using a path to the previous version of: fontTools/varLib/__init__.py

This resulted in:
<AxisNameID>0</AxisNameID>
instead of
<AxisNameID>264</AxisNameID> same for 265, etc

and 
<NamedInstance subfamilyNameID="0">
instead of
<NamedInstance subfamilyNameID="266"> same for 267, 268, 269 etc.
