### ISSUE TITLE
cannot merge NotoSansMyanmar-Regular.ttf with NotoSansLatin-Regular.ttf

### ISSUE THREAD

**Issue by xiangyexiao** [fonttools/fonttools#739]
I accidentally filed the bug in nototools. https://github.com/googlei18n/nototools/issues/305#issuecomment-257218718

Move it to the right place:

I first subsetted the basic Latin from NotoSans-Regular.ttf, then tried to merge the result (NotoSansLatin-Regular.ttf ) with NotoSansMyanmar-Regular.ttf.

These are my commands:
pyftsubset NotoSans-Regular.ttf --unicodes=U+0000-007f
pyftmerge NotoSansMyanmar-Regular.ttf NotoSansLatin-Regular.ttf

Error message:
Traceback (most recent call last):
File "/usr/local/bin/pyftmerge", line 9, in <module>
load_entry_point('fonttools==3.1.2+172.gea958e7', 'console_scripts', 'pyftmerge')()
File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
return func(_args, *_kwds)
File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 943, in main
font = merger.merge(args)
File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 813, in merge
table = clazz(tag).merge(self, tables)
File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 516, in merge
feature = [featureMap[v] for v in langsys.FeatureIndex if featureMap[v].FeatureTag == 'locl']
AttributeError: 'NoneType' object has no attribute 'FeatureIndex'

**Comment by xiangyexiao** [comment]
Thanks for the quick fix!

I can use pyftmerge to merge NotoSans(Latin-Greek-Cyrillic) with NotoSansMyanmar now:
$ pyftmerge NotoSansMyanmar-Regular.ttf NotoSans-Regular.ttf

However, if I first subset the basic Latin glyphs from NotoSans and merge the subsetted Latin font with NotoSansMyanmar, it still failed. My commands:
$ pyftsubset NotoSans-Regular.ttf --unicodes=U+0000-007f --output-file=NotoSansLatin-Regular.ttf
$ pyftmerge NotoSansMyanmar-Regular.ttf NotoSansLatin-Regular.ttf

**Comment by behdad** [comment]
Works for me.  Merging with unsubsetted used to work.  With subset font was failing, and I fixed.  Are you sure you are running the correct version?
