### ISSUE TITLE
[varLib] GPOS error, from merger.py

### ISSUE THREAD

**Issue by cjdunn** [fonttools/fonttools#741]
New error since upgrading to the latest fonttools 3.2.1 when generating a var font. 

```
...lib/python2.7/site-packages/fontTools/varLib/merger.py", line 58, in mergeLists
    assert all(count == len(v) for v in lst), (count, [len(v) for v in lst])
AssertionError: ((2, [3, 2, 3, 3, 3, 3, 3, 2, 3, 2]), 'list', '.SubTable', 'Lookup', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
```
Same files work without error in previous version. I get this error when generating via:
python path/to/fontTools/varLib/__init__.py path/to/file.designspace

Any ideas what's causing this new error and how it can be fixed? Thank you. /cc @behdad

**Comment by jamesgk** [comment]
I think this is caused by https://github.com/fonttools/fonttools/issues/719.

**Comment by cjdunn** [comment]
@jamesgk OK thanks for the info. My master UFOs have identical kerning groups so it seems this shouldn't be happening. 

For testing purposes, I tried making the kerning identical and I don't get this issue. Then, if I remove even one kern or if I set one kern to 0 instead of 1 or -1 then I get this error. 

It's not practical to have the same exact kerns in all masters and we shouldn't have to hack our masters and add a bunch of kerns with a value of 1 or something. Please fix this so we can store just the necessary kerns in our masters. Thanks so much!

**Comment by behdad** [comment]
Has been fixed.
