### ISSUE TITLE
Any non-sfnt available on the internet?

### ISSUE THREAD

**Issue by aaron-elkins** [fonttools/fonttools#746]
Hi,

I want to test fonttool with some non-sfnt fonts, but can not find any on the internet, can anyone point me to some non-sfnt fonts?

**Comment by anthrotype** [comment]
sorry, I'm not sure what you mean by "non-sfnt" fonts. Could you elaborate please?

**Comment by aaron-elkins** [comment]
I mean TrueType, OpenType are all sfnt format fonts, but i need some font that is not sfnt format, any?

**Comment by brawer** [comment]
Some Type 1 fonts are on CTAN: https://www.ctan.org/topic/font-type1

**Comment by aaron-elkins** [comment]
@brawer thank you
