### ISSUE TITLE
varLib.models.normalizeLocation capping

### ISSUE THREAD

**Issue by LettError** [fonttools/fonttools#749]
I'm looking at `varLib.models.normalizeLocation` [(here)](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/varLib/models.py#L14-L17) For positive values that exceed the axis maximum ("upper") the maximum is returned. I assume that is the "capping" [(commit)](https://github.com/fonttools/fonttools/commit/9ed319d0adaf9317fcae8489ca50389eb3a1b1a3) 

However, that raises the expectation that values under the minimum would return the minimum. They cause a ZeroDivisionError instead, when `default == minimum`.

Is **normalizeLocation** only used with values that know to be `minimum < v < maximum` ?
Would it be possible to offer the same capping for `value < minimum` when `default == minimum`?

```python
from fontTools.varLib.models import normalizeLocation

axes = {
	'aaaa': (-1000, 0, 1000),
}
assert normalizeLocation(dict(aaaa=-1000), axes) == {'aaaa': -1.0}
assert normalizeLocation(dict(aaaa=0), axes) == {'aaaa': 0.0}
assert normalizeLocation(dict(aaaa=1000), axes) == {'aaaa': 1.0}

# will be capped
assert normalizeLocation(dict(aaaa=-1001), axes) == {'aaaa': -1.0}
assert normalizeLocation(dict(aaaa=1001), axes) == {'aaaa': 1.0}

axes = {
	'aaaa': (0, 0, 1000),
}
assert normalizeLocation(dict(aaaa=0), axes) == {'aaaa': 0}
assert normalizeLocation(dict(aaaa=1000), axes) == {'aaaa': 1.0}
# will be capped
assert normalizeLocation(dict(aaaa=2000), axes) == {'aaaa': 1.0}
# should be capped? expected {'aaaa': 0.0}, get ZeroDivisionError
assert normalizeLocation(dict(aaaa=-1000), axes) == {'aaaa': 0.0}
```

**Comment by justvanrossum** [comment]
Btw, you also get a ZeroDivisionError instead of capping on the upper end, when `default == maximum`.

**Comment by justvanrossum** [comment]
@behdad, I think that `normalizeLocation()` should look like this:

```python
def normalizeLocation(location, axes):
	"""Normalizes location based on axis min/default/max values from axes."""
	out = {}
	for tag,(lower,default,upper) in axes.items():
		v = location.get(tag, default)
		if v == default:
			v = 0
		elif v < default:
			if default == lower:
				v = 0
			else:
				v = (max(v, lower) - default) / (default - lower)
		else:
			if default == upper:
				v = 0
			else:
				v = (min(v, upper) - default) / (upper - default)
		out[tag] = v
	return out
```

**Comment by LettError** [comment]
That works for me.

**Comment by behdad** [comment]
Right.  Another way is to do the clamping first, then proceed.  I find that more readable but whatever works.  Please feel free to push.  Thanks.

Perhaps add a test as well? :)

**Comment by justvanrossum** [comment]
You were right, that's absolutely more readable. Added doctests as well.

**Comment by behdad** [comment]
Thanks Just!

Might be good also asserting that `lower <= default <= upper`.
