### ISSUE TITLE
gvar floatToFixed

### ISSUE THREAD

**Issue by typemytype** [fonttools/fonttools#751]
A bit confused when setting axis coords... 
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_g_v_a_r.py#L459
 
this number will always be to big (except in a normalised designspace)

```python
def floatToFixed(value, precisionBits):
	"""Converts a float to a fixed-point number given the number of
	precisionBits.  Ie. int(round(value * (1<<precisionBits))).
	"""
	return int(round(value * (1<<precisionBits)))


print floatToFixed(1000, 14)
```
`>>> 16384000`

when sending this to struct `>h`

```
error: 'h' format requires -32768 <= number <= 32767
```

**Comment by justvanrossum** [comment]
These values are generally in normalized coordinates: beteen -1 and 1.

**Comment by typemytype** [comment]
the specs allows to write not normalised min, default, max values, being able to write 0 - 1000 as defined in a designspace file would be nice...

I guess examples from the spec should be possible to compile...


| Axis tag | Minimum value | Default value | Maximum value | Axis name ID |
| --------- | ----------------- | --------------- | -----------------| ----------------|
| 'wght'    | 300 | 400 | 700 | 256 |
| 'wdth'    | 62.5 | 100 | 150 | 257 |


https://www.microsoft.com/typography/otspec/fvar.htm

**Comment by justvanrossum** [comment]
https://www.microsoft.com/typography/otspec/gvar.htm says:

> Tuple records that are in the shared array or that are contained directly within a given glyph variation data table use 2.14 values to represent normalized coordinate values. See the Common Table Formats chapter for details.

**Comment by justvanrossum** [comment]
https://www.microsoft.com/typography/otspec/otvarcommonformats.htm:

> Tuple Records
>
> The tuple variation store formats make reference to regions within the font’s variation space using tuple records. These references identify positions in terms of normalized coordinates, which use F2DOT14 values.

**Comment by justvanrossum** [comment]
The example you quote is for `fvar`, but the error you're getting is from `gvar`. In `fvar`, you specify the design space values, in `gvar` you have to use normalized values.

**Comment by typemytype** [comment]
thanks
