### ISSUE TITLE
py23.round3 is slow

### ISSUE THREAD

**Issue by jamesgk** [fonttools/fonttools#753]
Following from https://github.com/fonttools/fonttools/pull/665

The round3 function in py23 (used prominently in t2CharStringPen) is slow. Would be nice to optimize it somehow. From @behdad:

> It occurs to me that if we avoid rounding if number is already int, and avoiding the power if ndigits is zero, plus other straightforward optimizations, might make this go away.

> I also think we can remove the checks for `__round__` and `__index__`.

**Comment by jamesgk** [comment]
Oh man, adding

```diff
--- a/Lib/fontTools/misc/py23.py
+++ b/Lib/fontTools/misc/py23.py
@@ -310,6 +310,9 @@ def round3(number, ndigits=None):
        Derived from python-future:
        https://github.com/PythonCharmers/python-future/blob/master/src/future/builtins/newround.py
        """
+       if isinstance(number, int) or int(number) == number:
+               return number
+
        return_int = False
        if ndigits is None:
                return_int = True
```

seems to make a huge difference indeed.

**Comment by behdad** [comment]
That's what I thought.  Do you need the first check?  The second might do just fine.

**Comment by behdad** [comment]
Though, you probably get YUUUGE speedup for masters, but not much for interpolated instances.

**Comment by jamesgk** [comment]
Well I have been using it on instances, but it turns out mutatormath rounds coordinates during interpolation by default and fontmath seems to have its own implementation of this: https://github.com/typesupply/fontMath/blob/master/Lib/fontMath/mathFunctions.py#L55.

**Comment by anthrotype** [comment]
See https://github.com/typesupply/fontMath/pull/36

**Comment by anthrotype** [comment]
I think we squeezed what we could from round3.

If you are still concerned, you could try this backport of the built-in Python 3 `round`; it's a C extension module for Python 2.7, with code taken straight off Python 3.5 `floatobject.c`.

https://github.com/anthrotype/round3

**Comment by jamesgk** [comment]
Nah, this has been significantly improved. Thank you!
