### ISSUE TITLE
[varLib] Encode postscriptname for fvar as single-byte encoding

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#756]
For example, MacRoman.  Apparently OS X implementation requires that they be encoded using single-byte encoding (and be unique).

**Comment by behdad** [comment]
cc @rsheeter

**Comment by anthrotype** [comment]
We already write the fvar postscript font name as both single-byte MacRoman (1, 0, 0) and Windows Unicode (3, 1, 0x409) name records:
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/varLib/__init__.py#L77

We added a `addName` method to the name table to do just that:
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L148

When you say "unique", you mean OSX doesn't like that that we also write a windows-unicode one?

**Comment by anthrotype** [comment]
See related issue https://github.com/fonttools/fonttools/issues/683 (closed)

**Comment by behdad** [comment]
Right.  Ok.  Thanks.

**Comment by behdad** [comment]
Let's close then.

**Comment by behdad** [comment]
It is a problem though that subsetter by default removes the macroman names.

**Comment by anthrotype** [comment]
> It is a problem though that subsetter by default removes the macroman names.

I guess we should open a separate issue for this.

**Comment by brawer** [comment]
>>It is a problem though that subsetter by default removes the macroman names.

> I guess we should open a separate issue for this.

Seems related to https://github.com/fonttools/fonttools/issues/146 so I’ve added it there.
