### ISSUE TITLE
Hello world! Snippets contribution

### ISSUE THREAD

**Issue by RimeOCRLIB** [fonttools/fonttools#759]
Start work with your great project. 
How we can contribute the snippets we have? 
In frame of our OCRLib project we can build GUI for FontTool coomon task.

May all be happy:)

```python
#! /usr/bin/env python

#get font namelist


from __future__ import print_function, division, absolute_import
from fontTools.misc.py23 import *
from fontTools.ttLib import TTFont
from fontTools.ttLib.tables import _c_m_a_p


def writeText(text,path):
    with open(path, "w") as text_file:
        text_file.write(unicode(text))

def main():
    font=TTFont("C:\MainYagpoOCR\Font\Yagpo_PALI_OT_21_06_10.ttf")
    cmapTable = font["cmap"]
    cmap=cmapTable.getcmap(0,3)
    text=""
    for code  in cmap.cmap:
        #print (hex(code)+" "+cmap.cmap[code])
        text+=hex(code)+" "+cmap.cmap[code]+"\n"
        
    path="C:\MainYagpoOCR\Font\Yagpo_PALI_OT_21_06_10.uni"
    writeText(text,path)
    print ("done")

if __name__ == "__main__":
    main()
```

**Comment by anthrotype** [comment]
Thank you for using fonttools! Contribution are always welcome.
Could you please send a pull request?
It would be easier to review and merge your code if you do that.

https://help.github.com/articles/about-pull-requests/

**Comment by RimeOCRLIB** [comment]
Good day!

With FontTools we need create 12600 ligatures in Tibetan and Devanagari open type font. 
All this ligatures is composite letters.
We can build this scripts and contribute as snippets with some python front end GUI.

Which tables we will need modify?  
What purpose of <instructions><assembly> table and where we can found documentation on it?

Thank you again for make FontTool free for community.

With best regards.
www.buddism.ru
Alexander Stroganov
