### ISSUE TITLE
Problem with TTX: decompile/recompile generate a buggy font

### ISSUE THREAD

**Issue by jbmorizot** [fonttools/fonttools#770]
I use fonttools 3.0 installed on a Mac (Yosemite) with Homebrew. When I decompile/recompile fonts with TTX, the new generated font can't be installed on the system, because the fontbook detect a serious error ("erreur grave" in French), but doesn't say what it is. The original font is not buggy.
I try on a MacBook Air with Sierra and I have the same issue.

**Comment by brawer** [comment]
Can you tell more details? Which fonts did you recompile? Which exact commands did you run? (Without more information, it’s hard to reproduce your bug report).

**Comment by anthrotype** [comment]
Can you try `brew uninstall fonttools` and then `pip install -U fonttools` and see if that solves the issue?
In any case, I recommend you use pip to install fonttools, as it's more up to date, and we maintain that ourselves.
If you wish you can send us a copy of the font privately?
My name dot surname at daltonmaag dot com

**Comment by jbmorizot** [comment]
Hi, Cosimo, I send you the file.
I just use the command TTX and the font path. I have issue on otf and ttf. the verbose mode doesn't give much information, so it's hard to be mode specific. I use Python 2.7.

**Comment by anthrotype** [comment]
Hm.. I'm also on Yosemite here, and I tried to install the font you sent me via email, and FontBook does not seem to complain:

<img width="1276" alt="screenshot 2016-12-15 11 05 41" src="https://cloud.githubusercontent.com/assets/6939968/21221733/75ed6ac6-c2b6-11e6-818e-72c0f07cf3f0.png">

**Comment by jbmorizot** [comment]
I figured out: my Mac refuse to install fonts when the have a '#' in it.
I don't know if there is a security mechanism in MacOs, but if there is a '#' in a font name I can't install it. Not a big issue, but could be interesting to know.

**Comment by anthrotype** [comment]
Good to know. I guess this can be closed now.
Cheers
