### ISSUE TITLE
Complete voltLib

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#771]
It would be nice to complete @moyogo’s work on voltLib in fontTools at some point. Also, SIL has a Perl script that compiles VOLT to TTF, which might be helpful to look at — thanks to @mhosken for pointing this out.
https://github.com/silnrsi/font-ttf-scripts/blob/master/scripts/volt2ttf

**Comment by behdad** [comment]
@moyogo has this been done, or is it planned?

**Comment by moyogo** [comment]
@khaledhosny finished it and it’s used in [TiroTypeworks/TiroTools](https://github.com/TiroTypeworks/TiroTools).
