### ISSUE TITLE
[feaLib] Generate Adobe feature files from feaLib AST

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#772]
Emit Adobe feature files from the feaLib AST (Abstract Syntax Tree). @mhosken would like to work on it.

**Comment by anthrotype** [comment]
That would be great, thanks!

**Comment by adrientetar** [comment]
Does the ft2fea tool in #479 use the feaLib AST?

**Comment by anthrotype** [comment]
do we keep this open now that #776 has been merged?

@mhosken in his https://github.com/fonttools/fonttools/pull/776#issue-196626145 mentioned two features which are not implemented yet:

> Ranges are expanded in the parser and not contracted in fea generation. This might be worked around by keeping a side copy of the original glyph list specification including ranges.

> nameid attributes are often defaulted and expanded in the parser. These are not defaulted out in the fea generation.

**Comment by anthrotype** [comment]
Ok, both of the above mentioned issues are fixed now, thanks to Martin. 🎉 
Feel free to open new specific issues.
