### ISSUE TITLE
[feaLib] Support non-standard statements

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#773]
@mhosken would like to support non-standard statements in feaLib, so that SIL can do their custom development with a language that is mostly but not fully AFDKO feature files. One way of doing this might be having a registry of non-standard keywords; if a block contains such a statement, it would invoke a custom parser method (which would look similar to the existing ones, but be declared outside feaLib).

**Comment by anthrotype** [comment]
Is this meant to be alternative solution the "feaplus" PR? for https://github.com/fonttools/fonttools/pull/720

**Comment by brawer** [comment]
I think so, but I’ll set @mhosken speak for himself.

**Comment by mhosken** [comment]
Given the inherent insecurities that the feaplus PR introduces, I've gone in a different direction and this is that new direction along with the ability to, in effect, subclass the ast module. Then one can create enhanced fea languages and output pure fea that all compilers can handle as well as building them. #720 may still live on, but much simplified and securely for the core compiler.

**Comment by anthrotype** [comment]
now that #794 is on master, and feaLib parser can be extended through custom ast, so this can be closed. Feel free to reopen if you find any issues.
