### ISSUE TITLE
Import tests from AOTS

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#791]
Similar to the mtiLib test suite, we can import tests from AOTS and roundtrip them to Python to binary & XML and back and compare...

Other test suites that might have interesting stuff: WOFF and WOFF2.

**Comment by behdad** [comment]
I'm working on this.  The test data is a few megabytes.  I'm going to put it in ttLib/testdata/aots.  But I think it's time to move test dat out of Lib/ now?  I don't know if this has any bad implications.  Are they installed? The fact that they have to be listed in manifest confuses me.  If they don't have any extra burden on end users' install, then maybe it's fine the way it is.

**Comment by behdad** [comment]
@anthrotype  ---^

**Comment by anthrotype** [comment]
yes, please, let's move the tests outside the package and no longer install them.
It makes things easier for me.
I can help you with this tomorrow.

**Comment by behdad** [comment]
Thanks Cosimo.  Is it ok if I add them the way we have right now and be done with it, then you do whatever you like?

**Comment by anthrotype** [comment]
yes, thanks!

**Comment by brawer** [comment]
Closing this bug because the work seems done... please re-open if I’m wrong.
