### ISSUE TITLE
ttx should write out output file name

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#801]
Am I right or hallucinating that ttx used to write out the output file name but doesn't anymore?  Given that ttx generates output file name, it should report it somehow.

**Comment by anthrotype** [comment]
well... It _does_ write it (at least to me)

```
$ ttx ~/Desktop/AktivGrotesk_Rg.ttf
Dumping "/Users/cosimolupo/Desktop/AktivGrotesk_Rg.ttf" to "/Users/cosimolupo/Desktop/AktivGrotesk_Rg#1.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'VDMX' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'DSIG' table...
```

**Comment by behdad** [comment]
Humm. It doesn't when I run it as "fonttools ttx ...".  It does if I run as "ttx ...".  The "Dumping .. table" appear in both cases.  Sounds like something is different with level of logging when invoked in those two ways.  Do you know what's going on?  The table one is a log.info() in ttLib.  The filename one is a log.info() in ttx.py.

**Comment by anthrotype** [comment]
I see. It must have to do with the `fontTools.misc.loggingTools.configureLogger` function. I'll investigate...

**Comment by behdad** [comment]
Thanks Cosimo.
