### ISSUE TITLE
Scaling CFF while retaining hints?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#806]
I'm just wondering, that seems a pretty difficult task. Has anyone done that before with fonttools?

**Comment by behdad** [comment]
Humm.  Why?  Sounds straightforward to me.

**Comment by justvanrossum** [comment]
Relative coordinates, hint info interspersed with coordinates. Dealing subroutines one way or another. It's definitely more work than simply applying a transform pen, which is what I would call straightforward :)

**Comment by justvanrossum** [comment]
Either way, it's non-trivial enough that in case anyone ever does this, a snippet contribution would be welcome.

**Comment by behdad** [comment]
Any number of that subroutine numbers will be scaled uniformly.

**Comment by behdad** [comment]
Err. *Any number out than...

**Comment by justvanrossum** [comment]
Not necessarily. The same shape at a different position may end up with different relative coordinates after scaling (with rounding to ints).

**Comment by behdad** [comment]
See. Now you are talking about translation, rounding, etc.  If you just scale and don't do anything else (no translation, no rounding), it should all work.

**Comment by behdad** [comment]
If you accurately define what you need to do, I can assess how feasible it is.  I've written a lot of custom T2CharString decoders to do things of this scale (pun intended!)

**Comment by justvanrossum** [comment]
Well actually, it seems I probably won't need this right now.

**Comment by behdad** [comment]
I wrote scaleUpem module now, but it desubroutinizes.

**Comment by behdad** [comment]
It probably can be done without desubroutinizing...
