### ISSUE TITLE
[cffLib] Some (Global)Subrs dumped as "raw" with ttx

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#808]
I have a font here (that I cannot share publicly) that when dumped with ttx, most subroutine CharStrings are dumped as "raw" instead of nicely decompiled:

```
      <CharString index="167" raw="1">
        15f70b0b   
      </CharString>
```

Is this to be expected?

**Comment by mashabow** [comment]
Related? https://github.com/adobe-fonts/source-han-sans/issues/162

**Comment by justvanrossum** [comment]
Ah, if it means those subrs are simply not referenced, then yes, it probably is, thanks.

Maybe it's rather a subsetting bug somewhere than a makeotf bug. Either way, it must be a bug in the font rather than fonttools.

**Comment by behdad** [comment]
It's impossible by design, to decode an unused subroutine...

**Comment by justvanrossum** [comment]
I know, or rather, I knew, and had forgotten :)
