### ISSUE TITLE
Three implementation questions:

### ISSUE THREAD

**Issue by yanone** [fonttools/fonttools#810]
Hi, I have a few questions.
I hope it’s okay if I ask implementation questions here. If not, please do let me know.
It’s not easy to navigate fontTools.

1.
How do I read the OpenType features in the correct order? So far I’ve accumulated Feature names from `TTFont['GSUB'].table.FeatureList.FeatureRecord` but they’re not in the order I expected.
Additionally, I would also like to parse the contents of GSUB features. How do I do that?

2.
How do I read the names of Stylistic Sets? I'm aware of the name table entries, but their nameIDs confuse me. They seem to not correspond to the Stylistic Set numbers. I couldn't find any Stylistic Set --> nameID mapping.

**Comment by justvanrossum** [comment]
1. FeatureRecords are ordered by tag. But they reference Lookups, which you will find in the expected order. Understanding the TTX dump helps, also to figure out how to access the objects.

2. Should be under FeatureRecord -> Feature -> FeatureParamsStylisticSet -> UINameID, which should map to a name record ID from the name table.

**Comment by yanone** [comment]
Ace, thank you!
