### ISSUE TITLE
add a CFF2CharStringPen

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#812]
The current `t2CharStringPen` only works with Type 2 CharStrings and CFF 1.0.

We need a corresponding `cff2CharStringPen` module, that takes into account the difference between Type 2 and CFF2 CharStrings:

https://www.microsoft.com/typography/otspec/cff2.htm#charStrings

Once we have that, then ufo2ft could use it to generate fonts with CFF2 table.

Of course, all depends on having CFF2 read/write support merged first (see #805).

**Comment by adrientetar** [comment]
Are you opening a new CFF2 PR? What remains to be done before merging?

**Comment by anthrotype** [comment]
there's a `cff2` branch on the upstream fonttools/fonttools repo.
It's a huge patch, and haven't got the time to properly review.
There was one blocking issue regarding the use of a global variable `isCFF2` that modifies the behaviour of classes based on the data that's feed to them, which should be avoided by splitting abstract and concrete sub-classes for CFF and CFF2.
If you want to have a go with it, you'd be most welcome! ;)

**Comment by behdad** [comment]
I made pens.t2CharStringPen take a CFF2 argument.  The differences between T2 and CFF2 are much smaller than you think... Basically it comes down to not appending endchar, and not prepending glyph width.  I also included the different stack sizes.
