### ISSUE TITLE
Translate Hungarian Assignment algorithm to Python

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#815]
I need this to finish "interpolatibility" tool.  I have a tested implementation in Pascal from 2001.  Looking for volunteer to translate it to Python and test it.

https://github.com/behdad/pascalalgs/blob/master/acmalgs/wegtmatc.pas

Please do a "min-cost" version instead of "max-weight".

We probably should add a fontTools.algorithms module instead of adding more things to fontTools.misc.

**Comment by behdad** [comment]
https://en.wikipedia.org/wiki/Hungarian_algorithm

**Comment by behdad** [comment]
FWIW I started that here:
https://github.com/fonttools/fonttools/blame/master/Snippets/interpolatable.py#L100

That's the first five lines ;)

**Comment by anthrotype** [comment]
This is super cool! I mean the algorithm, Pascal not so much....
I wanna give it a try.

I googled around and found a Python implementation of the the Kuhn-Munkres algorithm:
http://software.clapper.org/munkres/

And it's also in `scipy.optimize.linear_sum_assignment`
https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.linear_sum_assignment.html

I'll see what I can do :)

**Comment by anthrotype** [comment]
That `munkres` package is in turn a Python translation from an older Ada implementation, outlined here:
https://web.archive.org/web/20031004202034/http://www.public.iastate.edu/~ddoty/HungarianAlgorithm.html

**Comment by behdad** [comment]
The scipy implementation looks pretty good actually.  I'll see if I can just use that.  Thanks Cosimo!

**Comment by behdad** [comment]
Needless to say, my scipy version is tooooo old to have this ;).
I'll probably import it into fonttools.  Maybe we can have a module for third-party code we carry for a while.

**Comment by anthrotype** [comment]
`pip install scipy` works for me

**Comment by behdad** [comment]
```
pip3 install --user scipy
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib/python3/dist-packages
Cleaning up...
```
when I do --upgrade, it fails with:
```
numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
```
Ok, guess I'll upgrade numpy first.  My point wasn't about my individual situation, but users of fonttools currently don't need to install anything before using it..

**Comment by anthrotype** [comment]
Yeah, I know. You did a lot to remove the dependency on numpy...

**Comment by anthrotype** [comment]
btw, reading from the docstring, the scipy implementation is in turn based on Brian M. Clapper's, which is also the author the pure-python `munkres`.

**Comment by behdad** [comment]
> Yeah, I know. You did a lot to remove the dependency on numpy...

Apparently it's not trivial to fix `numpy.distutils.system_info.NotFoundError: no lapack/blas resources found`. Giving up right now, though I really like to try this.

**Comment by anthrotype** [comment]
munkres is also available on PyPI (https://pypi.python.org/pypi/munkres/1.0.9) so `pip install munkres` should work.
The source is here https://github.com/bmc/munkres

It's strange it doesn't work on your Linux. Numpy has universal `manylinux1` wheels which are supposed to work on any distro.
https://pypi.python.org/pypi/numpy

Have you tried to install everything in a virtualenv?

**Comment by behdad** [comment]
> The source is here https://github.com/bmc/munkres

Yep, thanks.  Will try tomorrow.

**Comment by behdad** [comment]
> It's strange it doesn't work on your Linux. Numpy has universal manylinux1 wheels which are supposed to work on any distro.

Just upgrading numpy works.  Scipy fails.  Need sleep right now!

**Comment by anthrotype** [comment]
sure, get some sleep! :)

**Comment by anthrotype** [comment]
just to confirm, I just tried and it works for me if I install the latest numpy 1.12.0 and scipy 0.18.1 in a virtual environment on Python 3.6.0 on Ubuntu 16.04.

**Comment by behdad** [comment]
I'm on Ubuntu 14.04.. :(((  Anyway, problem solved using fallback for both munkres and scipy.

**Comment by anthrotype** [comment]
nice, Thanks Behdad! now go to sleeeep! :)

**Comment by behdad** [comment]
Thank *you* Cosimo!  Feels good not to have to write code.

**Comment by behdad** [comment]
Actually I didn't test the scipy codepath.  Cosimo, any chance you can try it?  Just run ./interpolatable.py on a few ttf-interpolatable outputs from fontmake..

**Comment by behdad** [comment]
> I didn't test the scipy codepath

Probably need to cast G to a numpy matrix first.
