### ISSUE TITLE
ttx PANOSE element name for Family Type

### ISSUE THREAD

**Issue by PanderMusubi** [fonttools/fonttools#816]
The ttx PANOSE element name for Family Type is bFamilyType. However, the PANOSE specification and other tools refer to this as Family Kind. Perhaps refactor bFamilyType to bFamilyKind?

**Comment by justvanrossum** [comment]
The OpenType spec calls it `bFamilyType`: https://www.microsoft.com/typography/otspec/os2.htm#pan

**Comment by PanderMusubi** [comment]
Okay, thanks. In FontForge we just renamed it from "Family" to "Family Kind" , but I am fine with both so this issue may be closed.

A sort of related question, since there aren't that much people with extensive knowledge of the PANOSE classification, would you happen to know the answer to https://sourceforge.net/p/fontforge/mailman/message/35614219/ ? Thanks.
