### ISSUE TITLE
Formatting TT instruction assembly code?

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#818]
I’ve been reading a lot of TrueType instruction code lately ...

Would you be interested in a patch that makes TT code a little bit more readable by indenting `IF[] … EIF[]` and `FDEF[] … ENDF[]`?

![bildschirmfoto 2017-01-23 um 15 49 44](https://cloud.githubusercontent.com/assets/3185950/22208649/e511406c-e183-11e6-9490-b340e61ddeff.png)

**Comment by anthrotype** [comment]
that would be nice indeed!

**Comment by justvanrossum** [comment]
+1

**Comment by jenskutilek** [comment]
https://github.com/fonttools/fonttools/pull/819 :)
