### ISSUE TITLE
[subset] Features don't get dropped

### ISSUE THREAD

**Issue by yanone** [fonttools/fonttools#820]
Hi.
As opposed to my earlier post regarding dropping features after having frozen them with `pyftfeatfreeze`, I can't seem to get the `--layout-features` setting right.
When I use just `--layout-features-='lnum,tnum,c2sc,smcp'`, all features disappear except for *ccmp, locl, and liga*. But there used to be more, like *frac* and *ordn* for instance.
When I use `--layout-features='*' --layout-features-='lnum,tnum,c2sc,smcp'` all those feature (and the glyphs) stay in the font. Only the *lnum* feature seems to have disappeared.

I could of course calculate the precise amount of features and put it into `--layout-features='XX'`, but I wanted to raise the issue anyway, because this doesn’t look right to me.
Or am I doing something wrong?

The complete call is:
`python '/Users/yanone/Webseiten/wsgi/tools/pyftsubset.py' '/Users/yanone/Schriften/Font Produktion/Fonts/NonameSansOffice-Regular.temp.otf' --name-languages='*' --name-legacy --name-IDs='*' --unicodes='*' --layout-features='*' --layout-features-='lnum,tnum,c2sc,smcp' --output-file='/Users/yanone/Schriften/Font Produktion/Fonts/NonameSansOffice-Regular.otf'`

**Comment by yanone** [comment]
Update: I specifically set all features that I want to keep using `--layout-features='case,ordn,pnum,subs,numr,dlig,sups,dnom,locl,ccmp,hist,ss18,zero,ss19,aalt,sinf,frac,liga'`.
The result: the feature code is gone and the file size is much smaller, yet all `.sc` glyphs are still there.
I'm not getting it.

**Comment by anthrotype** [comment]
you are not using it wrong, but it's the way it currently works, as the --help explains, but maybe its clarity can be improved.

The `-=` or `+=` respectively add/remove from this default list of layout features, which is kept by default:

```sh
$ pyftsubset --layout-features=?
Current setting for 'layout-features' is: ['abvf', 'abvm', 'abvs', 'akhn', 'blwf', 'blwm', 'blws', 'calt', 'ccmp', 'cfar', 'cjct', 'clig', 'cswh', 'curs', 'dist', 'fin2', 'fin3', 'fina', 'half', 'haln', 'init', 'isol', 'kern', 'liga', 'ljmo', 'locl', 'ltra', 'ltrm', 'mark', 'med2', 'medi', 'mkmk', 'mset', 'nukt', 'pref', 'pres', 'pstf', 'psts', 'rclt', 'rkrf', 'rlig', 'rphf', 'rtla', 'rtlm', 'stch', 'tjmo', 'valt', 'vatu', 'vert', 'vjmo', 'vkrn', 'vpal', 'vrt2']
```

And currently you can't do, say, `--layout-features='*' --layout-features-='kern'`, to keep everything except kern...

So you'll have to explicitly set all the features you want to keep, or use -= / += as explained above.

**Comment by anthrotype** [comment]
> yet all .sc glyphs are still there.

did you use pyftfeatfreeze before running pyftsubset? maybe those .sc glyhs are no longer used for smcp but have become the default characters in the cmap?

**Comment by anthrotype** [comment]
this is where the default list of layout_features that are always kept is defined in the source code:
https://github.com/fonttools/fonttools/blob/c63fea0f8f90424d1943478328b90529af4a1f61/Lib/fontTools/subset/__init__.py#L2436-L2453

**Comment by anthrotype** [comment]
I noticed you pass `--unicodes='*'`; here the wildcard means "keep all the characters defined in Unicode cmap subtables"
https://github.com/fonttools/fonttools/blob/c63fea0f8f90424d1943478328b90529af4a1f61/Lib/fontTools/subset/__init__.py#L2961-L2965

**Comment by anthrotype** [comment]
the subsetter wants to know which glyphnames, gids, characters, features, etc. you want to _keep_, instead of which ones you want to _drop_. That's how it was designed.

**Comment by anthrotype** [comment]
Try also using --verbose to figure out what's going on under the hood. I know, it's very verbose...

**Comment by anthrotype** [comment]
just checking, are you 100% sure those `.sc` glyphs don't have any codepoint assigned? Maybe they have some private use are code and hence --unicodes='*' keeps them in.

**Comment by yanone** [comment]
> just checking, are you 100% sure those .sc glyphs don't have any codepoint assigned?

Sure.

Or, let me ask differently: What’s supposed to happen with this call: `pyftsubset font.otf --unicodes='*' --layout-features-='smcp'`
I just check it independently (without *pyftfeatfreeze*) with just dropping the `smcp` as above and only found three features left: `ccmp`, `locl`, and `liga`.
All target glyphs in those remaining feature have Unicodes, such as the `fi` or `Ldot`.

So here's what I think happens: Since I only specified `--unicodes='*'` for glyph repertoire, it basically drops everything that’s doesn’t have a Unicode. Innit?

So, for my understanding: Would it make sense to go through the features and drop the target glyphs of simple substitution features such as from `smcp` from the glyph name wish list, and then hand over that list to the tool?
I can use it in the way it was designed, I just need to understand what's happening.

**Comment by behdad** [comment]
If it's keeping the `.sc` glyphs, it means some feature is substituting otherwise-reachable glyphs with these. Only you know which feature other than `smcp` might be doing that in your font!

**Comment by yanone** [comment]
> If it's keeping the .sc glyphs, it means some feature is substituting otherwise-reachable glyphs with these.

But shouldn't the resulting features then show those `.sc` glyphs somewhere? But they don’t. The `.sc` are ghosts.

***

I’ve now tried setting the glyphs and the features explicitly.
The call now shows `--glyphs='[all glyphs except .sc]' --layout-features='[all features except smcp and c2sc]'` 
The resulting font still has all `.sc` glyphs as ghosts, only the feature code is now missing.
On a side note: I just discovered that the `ordn` and `frac` feature are now broken, both of which involve contextual substitutions and neither of which involves anything with Small Caps.

Also I’ve tried, just for understanding: `--glyphs='a,A' --layout-features='*'`
It nicely keeps `a`, `A`, `a.sc`, as well as `a.sups` with the respective features `smcp`, `c2sc`, `sups`. Everything else is gone. This one works.

Which leads me to the conclusion that *pyftsubset* is completely a Unicode-centric tool for input and isn't designed to just get rid of an OpenType feature whose target glyphs don't have Unicodes.

What do you say?

**Comment by anthrotype** [comment]
I'd say maybe you could send me the font privately for testing? [name dot surname at daltonmaag dot com]

**Comment by behdad** [comment]
What Cosimo said.

**Comment by yanone** [comment]
Awesome, I'll do that tomorrow, together with a clearly described set of commands that I've tried, my expectations and their results. Thanks.

**Comment by behdad** [comment]
Any update @yanone ?

**Comment by yanone** [comment]
I just tested all of my four scenarios again with the latest fontTools version.
I’m sorry to report that nothing changed.

Here’s the email that I sent to Cosimo when he asked me:
>The font is a very standard text font with Small Caps. In all of the examples below I'm trying to get rid of the Small Caps (so that's the smcp and c2sc features) to shrink the file size. The font is a direct export of Glyphs and has not been meddled with (like pyftfeatfreeze). Just to make sure I updated fontTools to the latest build and tried everything again.
I've attached the source .otf as well as the source Glyphs file, just in case.

>Here's what I did:

>Scenario 1:
--glyphs='*' --layout-features-='smcp,c2sc'
Expectation: Deletes all glyphs referenced in the two features smcp and c2sc (as long as those glyph are then ghosts), as well as the respective feature code.
Result: Glyph amount is identical to source font (includes .sc). The only features that remain are ccmp, locl, and liga (all of whose remaining target glyphs have Unicodes, even though I said --glyphs='*' and not --unicodes='*', but maybe that's unrelated).

>Scenario 2:
>--glyphs='*' --layout-features='tnum,ordn,pnum,subs,numr,lnum,dlig,sups,dnom,locl,ccmp,hist,ss18,zero,ss19,aalt,case,sinf,frac,liga' (Which are all features of the source font minus smcp and c2sc)
Expectation: Same as above, deletes all glyphs referenced in the two features smcp and c2sc, as well as the respective feature code.
Result: Glyph amount is identical to source font (includes .sc). Now all wanted features actually remain in the font (which is all except smcp and c2sc).

>Scenario 3:
>--glyphs='[all glyphs of the font minus .sc, see at bottom for exact list]' --layout-features='*'
Expectation: Delete all .sc glyph from the font, as well remove references to them from all feature code, then remove smcp and c2sc features if they're empty. (In my particular case both the smcp and c2sc feature also apply lining figures, so I don't actually expect the features to be gone, just all .sc references from them.)
Result: Pretty identical to source font. All glyphs and all features are present and complete (including .sc substitutions).

>Scenario 4:
>--glyphs='[all glyphs of the font minus .sc, see at bottom for exact list]' --layout-features='tnum,ordn,pnum,subs,numr,lnum,dlig,sups,dnom,locl,ccmp,hist,ss18,zero,ss19,aalt,case,sinf,frac,liga' (Which are all features of the source font minus smcp and c2sc)
Expectations: Now, seriously, I expect the .sc glyph to be gone, alongside their features.
Result: Nope, all glyphs still there (including .sc), except now the smcp and c2sc features are missing. There are no references left to any .sc glyphs in the feature code (none that I can see or know of).

>And by the way, I think it would generally be a very good idea to add a routine to fontTools or subset to remove all ghost glyphs that don't have a Unicode, are not referenced in any feature code, and are not part of a component glyph.
As a final optimization routine. People are sloppy all the time. But that's beside the point of this current exercise. But also not really. In the 4th scenario the .sc effectively become ghosts.

I uploaded the source font file [here](https://www.dropbox.com/s/2049kut5mj14kkp/NonameSansTest.zip?dl=0).
Please let me know if you have trouble downloading the file.

Thank you.

**Comment by yanone** [comment]
I just tried another combination:

Scenario 5:
--glyphs='[all glyphs of the font minus .sc, see at bottom for exact list]' --layout-features-='smcp,c2sc'
Results: The .sc glyph are now actually gone, alhamdulilah. But the features have been reduced to ccmp, locl, and liga (all of whose remaining target glyphs have Unicodes) (like Scenario 1).

**Comment by yanone** [comment]
Hi everyone,

I'm currently writing a subsetter that will remove the features and glyphs that I want.
I've implemented removal of lookups and features so far.

Is there a built-in way to remove a glyph from the font? Otherwise it seems like I need to go through all the tables and remove all references to the glyph, change GID references etc.

Thank you.

**Comment by anthrotype** [comment]
> I'm currently writing a subsetter that will remove the features and glyphs that I want

oh, so you gave up on using the fonttools subsetter and decided to write your own? I'm sorry I didn't have a chance to have a look at this issue yet.. I'll try to get back to it after ATypI is over.

> Is there a built-in way to remove a glyph from the font? Otherwise it seems like I need to go through all the tables...

That's exactly what the fontTools.subset module is meant to do. 
You could import and instantiate a `Subsetter` class with some options, call `populate` method with the glyphs you want to keep (so, to remove some, you include all but those), then call `subset` method passing a TTFont instance as argument, finally save the font. Look at the `main` function in the subset module, the entry point of pyftsubset script.

Please let us know if you have suggestions how we could improve the subsetter API.

**Comment by jenskutilek** [comment]
IIRC, `--layout-features-='smcp,c2sc'` doesn’t work, you have to list all the features you want to keep explicitly.

**Comment by yanone** [comment]
I tried **everything**. It just won't work. See my longer explanation 5 posts above.
Either features get dropped that are not supposed to get dropped, or all unencoded glyphs disappear, or something else happens that I can't explain.

Have you used the tool successfully to drop a certain feature together with their target glyphs? If so, how?

**Comment by jenskutilek** [comment]
Ah sorry, I missed that scenario above. Yes, I have used it successfully a while ago, let me look up how I did it ...

**Comment by jenskutilek** [comment]
I think you need to exclude the `aalt` features from your list of features to keep. It will be rebuilt/subset anyway. If you ‘force keep’ it by including it in the list, it will cause the smallcaps to be kept in the font because the original `aalt` likely contains a reference to the `smcp` and `c2sc` features.

**Comment by jenskutilek** [comment]
Example:
```bash
$ pyftsubset MyFont.ttf --unicodes='*' --layout-features='cpsp,mark,mkmk,rlig,ccmp,locl,subs,sinf,sups,numr,dnom,frac,lnum,pnum,tnum,onum,case,liga,ss14,ss04,ss06,ss09,ss10,ss13,ss20,calt' --glyph-names --notdef-glyph --notdef-outline --recommended-glyphs --name-IDs='*' --name-legacy
```

… successfully gets rid of all the small caps and petite caps glyphs for me.

**Comment by yanone** [comment]
WOW!
Now we're getting places. The main difference is that you used `--unicodes='*'`, whereas I kept using the `--glyphs` parameter with different values.

It works, but the `aalt` feature does not get rebuilt. I may have to do that manually?

**Comment by yanone** [comment]
It now also removes ghost glyphs, like narrow versions of accents that are decomposed in a CFF font. Awesome.

@anthrotype 
So I think we can close this. Thank you all.

The only question that remains is about the `aalt` feature that appears to be necessary to remove for the intended result. I could make a copy of it, then re-add it afterwards, then weed out the now missing glyphs.
But that feels like it should actually be a feature of `pyftsubset`?
Because you're subsetting all the lookups anyway, what about re-adding a copy of the `aalt` feature before doing so?

**Comment by behdad** [comment]
> Now we're getting places. The main difference is that you used --unicodes='*', whereas I kept using the --glyphs parameter with different values.

Huh.  Yeah, if you ask it to keep all glyphs, it will keep all glyphs. :)

> It works, but the aalt feature does not get rebuilt. I may have to do that manually?

Yeah, aalt is not special-cased.  We can have a snippet to do that.

**Comment by jenskutilek** [comment]
Ah, I checked the features in FontLab Studio after subsetting, and FontLab seems to build an aalt feature on import :/ It is not actually in the subsetted font.

**Comment by twardoch** [comment]
It's possible. aalt is an odd thing.

**Comment by miguelsousa** [comment]
> aalt is an odd thing.

I agree. The same can be said of F-lab.

**Comment by khaledhosny** [comment]
Personally I’d just drop `aalt` completely from the font. It seems to have been meant to be used by things like Glyph Palette in InDesign and IIRC it still works just fine without `aalt`.

**Comment by yanone** [comment]
Setting text with the font will work. The functionality of the Glyph Palette in InDesign will be broken, as you said. So for a professional font ´aalt´ is not optional for me.

**Comment by khaledhosny** [comment]
I can’t test this now, but I think the functionality of the Glyph Palette will *not* be broken if `aalt` is missing.

**Comment by yanone** [comment]
Good point. I just checked. The results are mixed.
InDesign does rebuild the feature in a way. But not all links get preserved.

For instance, the original font had a capital version of *ordfeminine* show up in the Glyph Palette alternates, called *ordfeminine.caps*, that gets lost without the `aalt` feature. Glyphs.app (in my case) calculated these links explicitly for the `aalt` feature.
InDesign does rebuild well established alternates like those for the different numeral sets.

In any case I think it's a good idea to preserve a subsetted version of the original `aalt` feature. I actually know people who pull out glyphs from the Glyph Palette.

**Comment by miguelsousa** [comment]
Photoshop's Glyphs palette also heavily relies on the presence of the `aalt` feature.

**Comment by twardoch** [comment]
My impression has been that if aalt isn't defined in the font, Illustrator or InDesign will synthesize it so to speak, i.e. generate the variant relations based on other features. Having aalt is useful however if we want to override this behavior i.e. only specify certain features to be used to generate the variant relations. Some features may not be suitable for being exposed in the "pick alternate from dropdown" style, and then we don't include them in aalt. 

Internally, aalt is just a list of references to lookups. Only FEA uses the style of referring to other features.

**Comment by jenskutilek** [comment]
I have frequently seen fonts with some glyph alternates linked only in the `aalt` feature, like one-off variants or those ten different ampersands that didn’t fit in any other supported feature. Those fonts rely on the `aalt` feature to make these glyphs available (or at least easier discoverable) through the glyphs palette in InDesign and Photoshop.

So I’d second the argument that it’s a good idea to keep and subset the `aalt` feature if its removal is not explicitly specified on the command line.

**Comment by yanone** [comment]
> So I’d second the argument that it’s a good idea to keep and subset the aalt feature if its removal is not explicitly specified on the command line.

And, probably more importantly: exclude the `aalt` feature from the glyph subsetting calculations when it shall be kept.
The biggest obstacle for the Small Caps glyphs that I couldn't get deleted from the font earlier was that I didn’t exclude the `aalt` feature with all the references to the `.sc` glyphs.

**Comment by behdad** [comment]
If there's a concrete proposal re aalt please file a new issue.  We can add code to synthesize aalt, and add option to subsetter to call it.
