### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#823]
I made a significant improvement to variation-font-building process.  I haven't tested it much, but I think it's good enough to go into a release.  Can we have one in a couple of days or so?  Alternatively I can bump fontmake to use the current master.  Thanks.

**Comment by anthrotype** [comment]
I'll do it today

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/releases/tag/3.6.0

**Comment by behdad** [comment]
Thanks!
