### ISSUE TITLE
Option to set output file with `ttx -m`

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#825]
Executing `ttx -m font.ttf extratables.ttx` will create `extratables.ttf` in the same directory. Can you pass a different path and filename? Adding `-o newfont.ttf` results in an `ERROR: Must specify exactly one TTX source file when using -m` error.

**Comment by anthrotype** [comment]
good point. `-o` should work, if it doesn't it's a bug and we shall fix it.
thanks!

**Comment by twardoch** [comment]
It doesn't

**Comment by justvanrossum** [comment]
The `-o` option should come before the "positional" ttx file option. The error message may be confusing, not sure how to improve that.

**Comment by justvanrossum** [comment]
It's actually implied by the help string: `ttx [options] inputfile1 [... inputfileN]`

**Comment by anthrotype** [comment]
Just is right, this works:

` $ ttx -o OutputFont.ttf -m InputFont.ttf InputTTX.ttx`

The `-o` needs to be placed anywhere before the last positional argument, i.e. the `[options]` in the usage string.

It doesn't work if the `-o` or any other option appear after the input files. I haven't checked the code but I think `getopt` doesn't allow that.

I guess this is fixed then.

**Comment by RoelN** [comment]
Duh. Sorry!

**Comment by anthrotype** [comment]
No worries, I myself would have expected it to work regardless of the order. If/when we unify/convert the commandline interface to use argparse you should be able to write the options and positional arguments in any order.
