### ISSUE TITLE
Add ability for parser to handle some comments

### ISSUE THREAD

**Issue by mhosken** [fonttools/fonttools#829]
When processing fea files, particularly when generating fea, it would be good to be able to process some comments. Some applications include processing information in comments and it would be good to be able to see them. When writing a fea to fea type processor, it would be good to pass comments through.

Arbitrary handling of comments is hard, and therefore I propose that we only support comments in certain locations (between statements).

I am happy to do the work.

**Comment by anthrotype** [comment]
That would be nice, thanks for working on this!

**Comment by brawer** [comment]
Adding comments to the syntax tree sounds like a good idea. Thanks for doing it.
