### ISSUE TITLE
XML roundtrip tests

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#830]
Over the past two days I fixed issues with XML rountripping. In both cases I had a test case.  Would be nice if there's a directory and I can just drop a file there (and list it in a .py file) and it will be tested for roundtripping and other stuff ala `tables_test.py`; should probably be in ttLib though, and no need to have the compiled version necessarily.  Anyway, attaching the two tests here.

**Comment by behdad** [comment]
[tests.zip](https://github.com/fonttools/fonttools/files/751783/tests.zip)

**Comment by anthrotype** [comment]
Thanks Behdad!
I'll add that when I get back to work on Monday.

**Comment by jarrodlombardo** [comment]
Did this get in? I'm seeing roundtrip issues with 3.13.1

**Comment by anthrotype** [comment]
@jarrodlombardo could you be please provide more info about the specific issue your are seeing?

**Comment by jarrodlombardo** [comment]
Thanks. https://github.com/fonttools/fonttools/issues/999

**Comment by behdad** [comment]
Anything else we need to do here?

**Comment by jarrodlombardo** [comment]
#1089 fixed the problem I was seeing in #999 .

**Comment by behdad** [comment]
We have a lot of XML roundtripping in our tests now. Not what I was proposing, but good enough...
