### ISSUE TITLE
Issues when reading the table

### ISSUE THREAD

**Issue by shwetamar85** [fonttools/fonttools#832]
Hi

I am always getting the message "The 'loca' table will be calculated by the compiler" in my TTX file . Also for many other tables I get  message "Most of this table will be recalculated by the compiler". Can you please help me on this.

Thanks
Shweta

**Comment by anthrotype** [comment]
This is by design.

**Comment by anthrotype** [comment]
TTX is a high level format, those low level details are not meant to be dumped as they will be recalculated when recompiling to binary.
