### ISSUE TITLE
[varLib] kern feature xadvance getting zeroed

### ISSUE THREAD

**Issue by robmck-ms** [fonttools/fonttools#834]
When I use varLib to build Selawik, GPOS features in the input TTFs (generated by fontmake) have xadvances properly set, but the output variable font has 0 for all the xadvances (see below).

This worked fine for the 11/30 release of Selawik (see https://github.com/unicode-org/text-rendering-tests/commit/80a89e8d8e06612cc0b1166b8dfb964a81f82c11) , but doesn't using the latest fonttools (pulled from master this afternoon).

All the intermediate files (master_* from fontmake, font as it comes out of varLib (Selawik-variations-test-raw.ttf) attached.

This is from the Regular master input ttf:
```
          <PairSet index="0">
            <!-- PairValueCount=65 -->
            <PairValueRecord index="0">
              <SecondGlyph value="C"/>
              <Value1 XAdvance="-20"/>
            </PairValueRecord>
            <PairValueRecord index="1">
              <SecondGlyph value="Cacute"/>
              <Value1 XAdvance="-20"/>
            </PairValueRecord>
            <PairValueRecord index="2">
              <SecondGlyph value="Ccaron"/>
              <Value1 XAdvance="-20"/>
            </PairValueRecord>
            <PairValueRecord index="3">
              <SecondGlyph value="Ccedilla"/>
              <Value1 XAdvance="-20"/>

```
This is the output variable font:
```
         <PairSet index="0">
            <!-- PairValueCount=65 -->
            <PairValueRecord index="0">
              <SecondGlyph value="C"/>
              <Value1 XAdvance="0">     <!-- should be -20 -->
                <XAdvDevice>
                  <StartSize value="0"/>
                  <EndSize value="0"/>
                  <DeltaFormat value="32768"/>
                </XAdvDevice>
              </Value1>
            </PairValueRecord>
            <PairValueRecord index="1">
              <SecondGlyph value="Cacute"/>
              <Value1 XAdvance="0">       <!-- should be -20 -->
                <XAdvDevice>
                  <StartSize value="0"/>
                  <EndSize value="1"/>
                  <DeltaFormat value="32768"/>
                </XAdvDevice>
              </Value1>
              ...
```

Possibly unrelated: I am getting the following errors from varLIb. I don't see any problem with the offsets or subtable segmentation in the input fonts or output fonts. 

...
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 4, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 6, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 8, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 11, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
...
[Selawik-fvar-test.zip](https://github.com/fonttools/fonttools/files/765460/Selawik-fvar-test.zip)

**Comment by behdad** [comment]
Ouch.  Really sorry about that.  Working on it.

**Comment by behdad** [comment]
> Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 4, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
> Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 6, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
> Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 8, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
> Attempting to fix OTLOffsetOverflowError ('GPOS', 'Look

There are expected.  Should be made into INFO messages.  Means some offset overflowed so fonttools is splitting the table and retrying.

**Comment by anthrotype** [comment]
They already are `log.info`:
https://github.com/fonttools/fonttools/blob/80535c224ee4bcbee23a9bf95bff2c27404b88c4/Lib/fontTools/ttLib/tables/otBase.py#L79

**Comment by robmck-ms** [comment]
Thanks guys!
