### ISSUE TITLE
ttx not parsing MVAR correctly

### ISSUE THREAD

**Issue by robmck-ms** [fonttools/fonttools#841]
Here is a tweaked version of Selawik which requires an MVAR table: [Selawik-MVAR-test.zip](https://github.com/fonttools/fonttools/files/772723/Selawik-MVAR-test.zip)

When I try to dump this font with ttx, the MVAR table has tag entries that do not appear to be encoded properly, and deltas that are huge. It seems like fonttools is getting out of synch with the fields (looks like it's 2 bytes off), thus parsing it wrong:

```
 <MVAR>
    <Version value="0x00010000"/>
    <Reserved value="1"/>
    <ValueRecordSize value="8"/>
    <!-- ValueRecordCount=7 -->
    <ValueRecord index="0">
      <ValueTag value="^@Fha"/>
      <VarIdx value="1935867904"/>
    </ValueRecord>
    <ValueRecord index="1">
      <ValueTag value="^@^Chc"/>
      <VarIdx value="1818296320"/>
    </ValueRecord>
    <ValueRecord index="2">
      <ValueTag value="^@^Chc"/>
      <VarIdx value="1818492928"/>
    </ValueRecord>
    <ValueRecord index="3">
      <ValueTag value="^@^Chd"/>
      <VarIdx value="1935867904"/>
    </ValueRecord>
    <ValueRecord index="4">
      <ValueTag value="^@^@hl"/>
      <VarIdx value="1735393280"/>
    </ValueRecord>
    <ValueRecord index="5">
      <ValueTag value="^@^Bsb"/>
      <VarIdx value="2037317632"/>
    </ValueRecord>
    <ValueRecord index="6">
      <ValueTag value="^@^Asp"/>
      <VarIdx value="2037317632"/>
    </ValueRecord>
  </MVAR>
```

The deltas should be along the lines of:
```
        'deltas':     {
            'sbyo': -50,
            'spyo': +100,
            'hasc': +200,
            'hdsc': -200,
            'hlgp': +100,
            'hcla': +200,
            'hcld': +200
        }

```

I believe that the MVAR table is correctly formed in the .ttf.

**Comment by behdad** [comment]
> I believe that the MVAR table is correctly formed in the .ttf.

Humm.  You sure?  The version when you sent me before seemed to use Offset32 to VarStore, whereas as Peter Constable noticed, the spec says Offset16.  Here's my reply to the otfontvar list about that:

```
FWIW, I had a draft implementation in FontTools, just checked it, and I have had independently also assumed that the offset is 32bit.

I also received a test font that Rob has had built.  Just checked it, and it too, has had assumed a 32bit offset!
```

So, I had to temporarily change my code to load Offset32, decode your font, then recompile it with correct offset size.

**Comment by robmck-ms** [comment]
You're right. I got it backwards. Apologies for wasting your time.

**Comment by behdad** [comment]
Np. :)
