### ISSUE TITLE
[feaLib] Make nameid parsing more robust

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#842]
While working on https://github.com/fonttools/fonttools/issues/780 I noticed that the feaLib parser for `nameid` statements is a bit simplistic in terms of encodings. For example, it doesn’t handle names with non-BMP characters such as Emoji, and it wrongly assumes that all Macintosh names are MacRoman encoding. fontTools has quite nice encoding utilities, we just need to call them.

**Comment by twardoch** [comment]
I agree. This is a case where I support diverging from the Adobe implementation, i.e. I think the AFDKO code has some simplistic notions about `nameid` statements and possibly isn’t able to process all of the encoding stuff correctly, but I’d consider that a “deficiency” of AFDKO (perhaps not a bug, but certainly not a feature). It would be great if `feaLib` accepted full UTF-8 `.fea` files with real Unicode contents of the `nameid` statements, and just did the magic.
