### ISSUE TITLE
Shouldn't variable font axis order be user-specified?

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#855]
In fontTools/varLib/__init__.py::_add_fvar(), the line "for iden in sorted(axes.keys(), key=lambda k: axis_map[k][0]):" forces the fvar axis list to be ordered alphabetically. Shouldn't this order be user-controlled? For example, when building the Adobe VF test font, I would like the order to be weight/width/contrast, but it comes out with contrast first.

**Comment by behdad** [comment]
Correct.  There's a TODO item there:
```
# TODO how to provide axis order? 
def _add_fvar(font, axes, instances, axis_map): 
```

**Comment by behdad** [comment]
VariationModel has an axisOrder constructor argument.  We can wire up axisOrder to other places as well.

Best to include the order in designspace document.  In fact, new designspace document has code for axes, we can use the same order.  I'll see if I can look into that soon.  Or feel free to try.  We should fetch min/default/max of axes from the same place as well.

cc @LettError

**Comment by miguelsousa** [comment]
Fixed by #857 and #864.

**Comment by anthrotype** [comment]
what about this `axisOrder` in `VariationModel` that Behdad mentioned? Was that connected to the designspace axes order?

**Comment by readroberts** [comment]
VariationModel __init__ takes axisOrder as an optional argument, which is currently not connected to the axisMap order. The axisOrder argument is currently used only in the test code in models.py.  It looks to me like axisOrder is used to established an intended order for locations, and should be in added to the VariationModel() call in varLib/__init__.py and varLib/interpolate_layout.py, using the axisTags variable.

**Comment by anthrotype** [comment]
Thanks Read. Let's keep this open then until that is done.

**Comment by behdad** [comment]
> VariationModel init takes axisOrder as an optional argument, which is currently not connected to the axisMap order

I removed it now.  Axes should be configured in designspace file.
