### ISSUE TITLE
pyftmerge: gasp table is optional, but pyftmerge uses 'equal' logic to merge it

### ISSUE THREAD

**Issue by zjusbo** [fonttools/fonttools#859]
**Steps to reproduce:**
1. merge a font with gasp and a font without gasp, you will get the error attached at the end of this post.

**Expected result:**
Two fonts are merged successfully.

**Reason:**
[gasp](https://www.microsoft.com/typography/otspec/otff.htm#otttables) is optional, but pyftmerge uses logic 'equal' when merging it. 'equal' requires all fonts contain such table tag.

ttLib.getTableClass('gasp').mergeMap = {
	'tableTag': equal,
	'version': max,
	'gaspRange': first, # FIXME? Appears irreconcilable
}

**Solution:**

1. Change equal to 'firstImplemented'
2. Create 'firstImplemented' logic that returns the first non NotImplemented element in the list.

**Error stack**
(dev) $ pyftmerge noto-fonts/unhinted/NotoSans-Regular.ttf NotoSansCham-Regular.ttf 
Traceback (most recent call last):
  File "/Users/bosong/i18n/fonttools/dev/bin/pyftmerge", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'pyftmerge')()
  File "/Users/bosong/i18n/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/bosong/i18n/fonttools/Lib/fontTools/merge.py", line 1011, in main
    font = merger.merge(args)
  File "/Users/bosong/i18n/fonttools/Lib/fontTools/merge.py", line 881, in merge
    table = clazz(tag).merge(self, tables)
  File "/Users/bosong/i18n/fonttools/Lib/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/Users/bosong/i18n/fonttools/Lib/fontTools/merge.py", line 926, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/Users/bosong/i18n/fonttools/Lib/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: **['gasp', NotImplemented]**

**Comment by anthrotype** [comment]
`gasp` *is* optional, but when it's there if does affect the hinting and rasterization (on Windows, at least). So I believe pyftmerge can't just pick the first one, but rather the `gasp` settings should compatible to begin with, no?

**Comment by zjusbo** [comment]
Agreed on that it affects hinting and rasterization to other glyphs. 
Current logic just pick the first gasp setting and based on the [specification of gasp](https://www.microsoft.com/typography/otspec/gasp.htm) , it seems the gasp is a global setting apply to all glyphs in a font. We can not set an applied codepoint range for it. In other words, it is irreconcilable if two gasp conflicts, we can only respect one of them. And the selected gasp table may hurt the legibility to those glyphs whose gasp table was not selected.

IMO, the font merge is a lossless, irrevertible process. We should try our best to keep the information as much as we can, but sometimes we have to sacrifice some of them. 

Apart from the gasp, I believe there are other tables that are also irreconcilable in merging. I was thinking we can specify a 'dominating' font, say, the first parameter in pyftmerge, that when conflicts happens, we always keep the table in 'dominating' font and drop others. This is sort of what we are currently doing in 'first' logic in merge.py.

For example, for gasp table, we only pass the gasp table from the first font to the result. If the first font does not contain gasp table, we drop it in our result. Any ideas?



This decision do lose information in separate fonts. Any ideas?

**Comment by zjusbo** [comment]
Pull request merged.
