### ISSUE TITLE
Unicode character description missing in comments for codepoints above 0xFFFF

### ISSUE THREAD

**Issue by PanderMusubi** [fonttools/fonttools#870]
Unicode character description in the cmap table in output of `ttx -l` is missing in comments for codepoints above 0xFFFF, e.g.

    <map code="0xffed" name="uniFFED"/>
    <map code="0x1f4ef" name="u1F4EF"/>

The description here `????` should be `POSTAL HORN`, see https://unicode-table.com/en/1F4EF/

**Comment by anthrotype** [comment]
You can install `unicodedata2` backport to use the latest UnicodeData 9.0.0
https://pypi.python.org/pypi/unicodedata2

fontTools will try to use that one if it finds it installed, else will fall back to the `unicodedata` module from the stdlib, whose version varies between python versions.

Python 3.6 has the latest UnicodeData 9.0.0, so its built-in `unicodedata` module is equivalent to the `unicodedata2` backport module.

Yes.. that is one of those extra, implicit dependencies of fontTools, which could at least be better documented.

There has been resistance in the past to adding dependencies to fonttools, though that may change once I manage to convince the rest of us that [Python Packaging Is Good Now](https://glyph.twistedmatrix.com/2016/08/python-packaging.html).

**Comment by PanderMusubi** [comment]
Thanks. Nope, did not know that that existed. I'm using Python 3.5.1-4. I installed it with

    # pip3 install unicodedata2
    Collecting unicodedata2
      Downloading unicodedata2-9.0.0.post4-cp35-cp35m-manylinux1_x86_64.whl (408kB)
        100% |████████████████████████████████| 409kB 2.3MB/s 
    Installing collected packages: unicodedata2
    Successfully installed unicodedata2-9.0.0.post4

but running `ttx` still resulted in `????` in the comment. Is there something else to do to get this working?

**Comment by PanderMusubi** [comment]
PS   I am using fonttools version 3.0-1 on updated Ubuntu 16.10.

**Comment by anthrotype** [comment]
hm.. that's weird. Do you get 'POSTAL HORN' if you do this in an interactive python shell?

```python
>>> import unicodedata2
>>> from fontTools.misc.py23 import unichr
>>> unicodedata2.name(unichr(0x1f4ef))
'POSTAL HORN'
```

**Comment by anthrotype** [comment]
Ah ok! You should uninstall that old fonttools version you have, and re-install it with `pip install fonttools`. The latest version should be 3.7.2.

**Comment by PanderMusubi** [comment]
$ python3
    Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
    [GCC 6.2.0 20160927] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import unicodedata2
    >>> from fontTools.misc.py23 import unichr
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'fontTools'

**Comment by anthrotype** [comment]
Seems like fontTools package is not installed in your python3's site-packages, so you can't import it.
How did you install it in the first place?

**Comment by PanderMusubi** [comment]
Yes, that fixed it, thanks

    # dpkg -P fonttools
    ...
    # pip3 install fonttools
    ...

Hope Ubuntu will upgrade its package soon.

**Comment by anthrotype** [comment]
No, don't use `dpkg` to install fonttools. We don't maintain that.
Use pip to install the latest fonttools.

**Comment by anthrotype** [comment]
Going to keep this issue open so we can discuss with the rest of the team whether to add `unicodedata2` to our `install_requires`, or possibly to `extras_require`.

**Comment by PanderMusubi** [comment]
I try to chase Ubuntu to keep up to date with Python packages. In some organisations, one is not allowed to install outside of the official repositories because of maintenance contracts. So pip might be the fix (for you personal systems) but not everyone is allowed to that on certain (Ubuntu/Debian/Red Hat/etc) corporate servers.

**Comment by PanderMusubi** [comment]
Upvoting https://bugs.launchpad.net/ubuntu/+source/fonttools/+bug/1658041 (after logging in) might help a bit.

**Comment by khaledhosny** [comment]
783707644bfa0d92d924faea745e34f3c0555219 already added `unicodedata2` to `extras_require`.

**Comment by PanderMusubi** [comment]
Super! If you need translations of Unicode character descriptions, please see https://github.com/OpenTaal/python-unicodedata_l10n
