### ISSUE TITLE
Any font validation tool in this project?

### ISSUE THREAD

**Issue by aaron-elkins** [fonttools/fonttools#875]
Is there any truetype and open type font validation tool in this repo?

**Comment by brawer** [comment]
Not really. If a font’s tables are so broken that they can’t be parsed, the tools in this repo will definitely notice. But there’s no checks that would guarantee a font will work fine on a specific platform.

**Comment by anthrotype** [comment]
try https://github.com/HinTak/Font-Validator, or `ftxvalidator` in the Apple Font Tool Suite
https://developer.apple.com/download/more/?=font

**Comment by davelab6** [comment]
There's also ots and fontbakery
