### ISSUE TITLE
[varLib.merger] Limitation in _PairPosFormat2_merge

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#888]
While trying to build a variable version of Source Sans I ran into [this documented limitation](https://github.com/fonttools/fonttools/blob/23511fd302283a68774308c03fa93ae0411987a9/Lib/fontTools/varLib/merger.py#L370-L374),
```
# Currently, if the coverage of PairPosFormat2 subtables are different,
# we do NOT bother walking down the subtable list when filling in new
# rows for alignment.  As such, this is only correct if current subtable
# is the last subtable in the lookup.  Ensure that.
# TODO: Remove this requirement
```
I've put together a [test ~case~ example in the Source Sans repository in a branch named **_PairPosFormat2_merge**](https://github.com/adobe-fonts/source-sans-pro/blob/_PairPosFormat2_merge/RomanMasters/build_vf.py) to help addressing this limitation.

**Comment by behdad** [comment]
Thanks for the concise test case!!  Looking into it.  I think I know of a simple fix...

**Comment by behdad** [comment]
Would be great if you can add a test case for it.  Thanks.

**Comment by miguelsousa** [comment]
Will do. Thanks!

**Comment by miguelsousa** [comment]
Something isn't right. I've spot-checked a few kern pairs and they're not working in the variable font, whereas they're fine in the master sources. See the FontView screenshots below. The result in CoreText is the same (tested via axis-praxis).

<img width="798" alt="vf-master0" src="https://cloud.githubusercontent.com/assets/2119742/24034253/da253516-0aad-11e7-9cbe-4619fc08c8ea.png">
<img width="798" alt="vf-master1" src="https://cloud.githubusercontent.com/assets/2119742/24034258/dd8e0cfa-0aad-11e7-915d-a922010e3452.png">
<img width="712" alt="master0" src="https://cloud.githubusercontent.com/assets/2119742/24034243/d174fb22-0aad-11e7-9c63-c6e1909a6400.png">
<img width="712" alt="master1" src="https://cloud.githubusercontent.com/assets/2119742/24034249/d4fd2e90-0aad-11e7-9406-99e5353fd60c.png">

**Comment by behdad** [comment]
Fix coming soon.

Note that CoreText as far as I know doesn't support GSUB / GPOS variations yet.

**Comment by miguelsousa** [comment]
Thanks Behdad. The kerning now seems to be working in the Black (master1) but it's still not in the ExtraLight (master0). Do you think that this is now a FontView/FreeType/HarfBuzz issue?

<img width="795" alt="vf-master0" src="https://cloud.githubusercontent.com/assets/2119742/24076520/1769e546-0bf0-11e7-9508-37f6391acc8a.png">
<img width="712" alt="master0" src="https://cloud.githubusercontent.com/assets/2119742/24076521/1beef0c0-0bf0-11e7-8349-9d09733fd1fd.png">
<img width="795" alt="vf-master1" src="https://cloud.githubusercontent.com/assets/2119742/24076513/07ca5044-0bf0-11e7-98f8-411374a758f9.png">
<img width="711" alt="master1" src="https://cloud.githubusercontent.com/assets/2119742/24076517/0ecbae10-0bf0-11e7-9e2b-86d90c5a28e5.png">

**Comment by miguelsousa** [comment]
I've made new [master fonts that don't have Greek and Cyrillic class kerning and put them in a branch named **no-greek-cyrillic-kerning**](https://github.com/adobe-fonts/source-sans-pro/tree/no-greek-cyrillic-kerning). While building these fonts there was no `Attempting to fix OTLOffsetOverflowError` message.

The variable font made with these new masters works fine in FontView, in terms of kerning. While building the VF there were two `Attempting to fix OTLOffsetOverflowError` messages.

I think that based on this we can rule out a bug in FontView.

**Comment by behdad** [comment]
Thanks Miguel.  I'll debug.

Sorry for not properly testing my fixes.  I'm of very limited time right now :(.

**Comment by miguelsousa** [comment]
No worries. I appreciate any time you can dedicate to this. I'd do it if I knew how.

**Comment by miguelsousa** [comment]
Thank you very much for the fix Behdad. AFAICT the GPOS merging of that test variable font is working as expected now 🎉 🏆 🎉 🏆 🎉 🏆

However I'm sorry to say that I have another example v-font that ends up with non-functioning kern pairs 😢  The difference between the set of source TTFs referenced in this issue and my other TTFs
is that the GPOS tables of the former were made via fontmake/feaLib, whereas in the latter they were made via makeotf.

I'm going to add test cases to fontTools for the examples that are working, and then provide test files that will show what's not working. I'll open a new issue instead of reopening this one, since I don't know if it's the same exact problem.

**Comment by behdad** [comment]
Thanks. I'll take a look.
