### ISSUE TITLE
[varLib] extrapolate, truncate, or rebase when min/max/default different from implied

### ISSUE THREAD

**Issue by readroberts** [fonttools/fonttools#892]
I just ran into a an annoying bug in a font design space file, which makes me want to suggest a change in the design space file spec.  This currently specifies axis default, max and min values in two places.  These attributes can be  explicitly defined by <axis> elements. They are also always implicitly defined by the master design <source> elements. The coordinates of the base design <source> element are necessarily the 'default' attribute for each axes. The  max and min coordinate values for each axis in all the <source> elements also necessarily is the max and min value for each axis.

This is an issue because it means that every time an editor changes which master design is used as the default, or changes the max or min axis values, they must be changed in both places.  I suggest that we remove or deprecate (e.g. ignore) the default, max and min attributes from the <axis> elements. This is a little sad, because the <axis> element is a very clear and concise place to express these attributes. However, the <source> elements have to have coordinates, and a selector for the default font, and these are the primary definition for the default, min and max value. 

Of course, this is all an issue only if manual editing of the design space file an important mode; if we expect to almost always be generated by another tool, then the need to keep the two definitions the same is not so much of an issue. 

(FYI: if <axis> elements are specified then fonttools/varlib/__init__.py::build()  uses them to define the axis attributes, else it uses the <source> element attributes.)

**Comment by behdad** [comment]
Thanks Read.  Interesting that you bring up.

The duplication is intended.  I want to extend varLib such that:

  * If min/max are different from implied range, either extrapolation happen, or truncation.  See https://github.com/fonttools/fonttools/issues/671

  * Make any default position work by first synthesizing font at that point and then rebase the model on top of it.

**Comment by readroberts** [comment]
Now I understand the rationale, and agree that this is a valid and useful thing to do. I will close the issue.

**Comment by behdad** [comment]
Thanks. I don't mind keeping open and renaming, for tracking purposes.
