### ISSUE TITLE
font.getGlyphSet()[glyphname].draw() does not set width / height

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#893]
We should fetch those from hmtx / vmtx and set.

**Comment by anthrotype** [comment]
actually advance width and left side bearing are already fetched from the hmtx in the objects returned from getGlyphSet:

https://github.com/fonttools/fonttools/blob/8af488a1b3a56694bb44961d2d8e7afcfc40d774/Lib/fontTools/ttLib/__init__.py#L738

We should just add height and top side bearing from vmtx, if available.
