### ISSUE TITLE
ttx fails to read UTF-8 with BOM

### ISSUE THREAD

**Issue by shwetamar85** [fonttools/fonttools#896]
Hi

I have 2 files which are exactly similar but one of them gets converted to TTF but the other one doesn't.
ByTool.ttx - this converts to ttx
ByCode.ttx - this doesn't :(

Please help

Thanks
Shweta 

[FilesForTesting.zip](https://github.com/fonttools/fonttools/files/866228/FilesForTesting.zip)

**Comment by miguelsousa** [comment]
The ByCode.ttx file makes ttx fail at `guessFileType()` because it has three characters at the beginning which are not ASCII: `\xef\xbb\xbf<?xml version`

**Comment by miguelsousa** [comment]
```python
fileName = 'ByCode.ttx'
f = open(fileName, "rb")
print(repr(f.read(16)))
```

**Comment by shwetamar85** [comment]
Thanks a lot

**Comment by behdad** [comment]
That's the UTF-8 Unicode Byte Order Mark (BOM). That's deprecated but valid XML nonetheless. We should support it.

**Comment by anthrotype** [comment]
🙊 sorry, thanks Behdad

**Comment by anthrotype** [comment]
If we were opening the xml file as text rather than bytes, python would take care to decode UTF-8 properly. But I suspect that the expat parser expect bytes. Will check

**Comment by anthrotype** [comment]
Is it enough to simply check for the BOM and strip it if it's there, then proceed reading the bytes as UTF-8 encoded? If so, that's easy.

**Comment by behdad** [comment]
Correct. I think the parser handled that, so we just need to fix the guessFileType code.

**Comment by miguelsousa** [comment]
Is it really necessary to check for the presence of the BOM before stripping it?
I tested changing [this line](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttx.py#L293) to `header = f.read(256).lstrip(b'\xef\xbb\xbf')` and it seems to be enough for both py2 and 3.
