### ISSUE TITLE
Time for a new release? :)

### ISSUE THREAD

**Issue by davelab6** [fonttools/fonttools#898]
I'd like to suggest cutting a new release, since v3.9.1 can't parse STAT tables but master can :)

**Comment by anthrotype** [comment]
Are you sure?

https://github.com/fonttools/fonttools/compare/3.9.1...master

Not much has happened since 3.9.1, and nothing that has to do with STAT table.

What's the error?

**Comment by davelab6** [comment]
> What's the error?

Found between monitor and keyboard :)
