### ISSUE TITLE
Glyf data not ordered as per glyph order table

### ISSUE THREAD

**Issue by shwetamar85** [fonttools/fonttools#905]
# **Below is the glyph order table** 

<GlyphOrder>
    
    <GlyphID id="0" name=".notdef"/>
    <GlyphID id="1" name="glyph00001"/>
    <GlyphID id="2" name="glyph00002"/>
    <GlyphID id="3" name="space"/>
    

- **#

 Below is the order in Glyf table**

 <TTGlyph name=".notdef" xMin="256" yMin="0" xMax="1792" yMax="1536">
      <contour>
        <pt x="256" y="0" on="1"/>
        <pt x="256" y="1536" on="1"/>
        <pt x="1792" y="1536" on="1"/>
        <pt x="1792" y="0" on="1"/>
      </contour>
      <contour>
        <pt x="384" y="128" on="1"/>
        <pt x="1664" y="128" on="1"/>
        <pt x="1664" y="1408" on="1"/>
        <pt x="384" y="1408" on="1"/>
      </contour>
      <instructions>
        <assembly>
         
        </assembly>
      </instructions>
    </TTGlyph>

    <TTGlyph name="A" xMin="-10" yMin="0" xMax="1238" yMax="1489">
      <contour>
        <pt x="-10" y="0" on="1"/>
        <pt x="492" y="1489" on="1"/>
        <pt x="736" y="1489" on="1"/>
        <pt x="1238" y="0" on="1"/>
        <pt x="1029" y="0" on="1"/>
        <pt x="894" y="416" on="1"/>
        <pt x="325" y="416" on="1"/>
        <pt x="190" y="0" on="1"/>
      </contour>
      <contour>
        <pt x="839" y="585" on="1"/>
        <pt x="609" y="1287" on="1"/>
        <pt x="380" y="585" on="1"/>
      </contour>
      <instructions>
        <assembly>
         
        </assembly>
      </instructions>
    </TTGlyph>

    <TTGlyph name="AE" xMin="-39" yMin="0" xMax="1802" yMax="1489">

**Comment by anthrotype** [comment]
The elements of the glyf table are sorted alphabetically in the XML dump, but are compiled using the order from the GlyphOrder when compiling the XML to binary.

**Comment by shwetamar85** [comment]
But shouldn't in xml it be sorted by id as glyphorder  ? Is there a reason they are sorted by name?

**Comment by anthrotype** [comment]
No particular reason, just out of convenience I guess. The order is defined in the GlyphOrder pseudo-table, and other tables are just dumped in a normalized, alphabetical sorting.

**Comment by anthrotype** [comment]
Also, most of the tables, including glyf, are represented internally as python dictionaries which are unsorted collections. It's just easier to have the glyphOrder stored separately and use it when it matters, upon compiling. I don't see a good reason to change that.

**Comment by shwetamar85** [comment]
I am stuck on situation where I have to compare a font version . I have to compare the glyf table. Font has 60000 glyf in it and if I decompile the glyf table it's size is ~483MB . Loading these complete xmls in memory is a bad idea , so I though if I can just pick up node from each side to compare . But for that it has to be ordered .. So thought of checking that. I raised another issue for the same problem https://github.com/fonttools/fonttools/issues/904

**Comment by shwetamar85** [comment]
Just to confirm once again they are sorted by the attribute name of the element TTGlyph
