### ISSUE TITLE
[otlLib] GPOS ValueRecord optimization should be optional

### ISSUE THREAD

**Issue by punchcutter** [fonttools/fonttools#907]
From builder.py
```
    # If a ValueRecord is shared between multiple glyphs, we generate
    # a SinglePos format 1 subtable; that is the most compact form.
```
This kind of optimization is probably fine in most cases, but more than once this has caused major problems with interpolation in the Noto pipeline (one example: https://github.com/googlei18n/fontmake/issues/171). 

For example, we have master sources for Thin, Regular, Bold, and Black. The GPOS for each master has the same number of lookups, but the values within each lookup are just whatever they happen to be to work with the design. Some glyphs in a group might just happen to have the same X or Y. When ValueRecords get compacted each master now potentially has a different binary layout. This makes the binary sources incompatible when running fontmake with `--interpolate-binary-layout`. 

For the Noto Khmer issue I manually went through every glyph and adjusted the anchors so that they would be compacted the same way in each master. Obviously that is rather absurd to alter the sources just to get interpolation working. It would make much more sense to have an option to ignore these compacting optimizations at the source.

**Comment by behdad** [comment]
No.  Merger should know how to merge. And in this case it knows.  If you hit bugs, file them and I'll fix.  Thanks.

**Comment by behdad** [comment]
See `fontTools.varLib.merger:_SinglePosUpgradeToFormat2()`.
