### ISSUE TITLE
vhea table : values changed on compile

### ISSUE THREAD

**Issue by shwetamar85** [fonttools/fonttools#908]
Hi

I decompiled a ttf to ttx and without making any changes just compiled it back 
I notice 2 fields value have changed
1)   **minBottomSideBearing ,** Changed from 1 to 0
2) **yMaxExtent** changed from 1023 to 1024

**Comment by anthrotype** [comment]
It's a feature. Use -b to not recalculate bonding codes upon compile. See ttx --help

**Comment by anthrotype** [comment]
Bounding boxes, not bonding codes.. sorry was typing from my mobile phone.
