### ISSUE TITLE
Issue in compiling EBLC table

### ISSUE THREAD

**Issue by shwetamar85** [fonttools/fonttools#909]
Hi

While running the ttx command I am getting the below error 

 File "c:\users\my\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\ttLib\tables\E_B_L_C_.py", line 183, in compile
    data = indexSubTable.compile(ttFont)
  File "c:\users\my\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\ttLib\tables\E_B_L_C_.py", line 541, in compile
    self.imageDataOffset = min(zip(*self.locations)[0])
TypeError: 'zip' object is not subscriptable 

I don't see any tag by the name of locations in  the file.

Thanks
Shweta

**Comment by shwetamar85** [comment]
Attaching file for reference 
[MyFont.E_B_L_C_.txt](https://github.com/fonttools/fonttools/files/903728/MyFont.E_B_L_C_.txt)

**Comment by adrientetar** [comment]
That's a py2/3 issue, since zip returns a generator in py3. If you replace zip(*self.locations)[0] with next(zip(*self.locations)), that should fix things.

**Comment by anthrotype** [comment]
@adrientetar Sgtm. Mind sending a PR?

**Comment by anthrotype** [comment]
Thanks!
