### ISSUE TITLE
[varLib] Use designspaceDocument?

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#911]
Should `fontTools.varLib` use @LettError’s [designspaceDocument](https://github.com/LettError/designSpaceDocument) class?

* Advantages: Nice API. Less duplication of code between font libraries, such as glyphsLib (which writes designspace) and varLib (which reads them). Files would always be spec-compliant.
* Disadvantage: Our dependency hell gets worse, for a relatively minor piece.

Thoughts? Perhaps designspaceDocument coud become part of fonttools?

**Comment by anthrotype** [comment]
+1 for using designspaceDocument, +2 for including it in fonttools if Erik steps up to maintain it

**Comment by davelab6** [comment]
Are the dependencies really hellish? It seems to be smooth to me. Curious
what the advantages of inlining it are? 🤔

**Comment by brawer** [comment]
Yes, they are.

**Comment by LettError** [comment]
If this is the way to go, I don't mind maintaining it.

**Comment by anthrotype** [comment]
Thanks Erik! You already have push access, so you can create a new branch here on the fonttools repo where we work together on integrating the new subpackage into the library.
I guess it would go inside fontTools.varLib, replacing the current designspace.py. Or do we want to place it one level above, under fontTools.designspaceDocument?

**Comment by anthrotype** [comment]
Maybe outside of varLib, as fontTools.designspaceDocument, would be better.

**Comment by behdad** [comment]
I like folding it in as well. Will review the code / api.

**Comment by khaledhosny** [comment]
Already done #1313.
