### ISSUE TITLE
command not found: pyftsubset

### ISSUE THREAD

**Issue by ivanov-v** [fonttools/fonttools#912]
I have set what is needed, but there is an error
`zsh: command not found: pyftsubset`

**Comment by anthrotype** [comment]
how did you install fonttools?

**Comment by ivanov-v** [comment]
`pip install fonttools`

**Comment by ivanov-v** [comment]
If repeat, I get it
`Requirement already satisfied: fonttools in /Library/Python/2.7/site-packages`

**Comment by anthrotype** [comment]
which python are you using? The macOS built-in python or homebrew or what?

Try to do this to get the full path to the binary called "python":
```sh
$ which python
```

Also, echo the content of your `$PATH` to check that `/usr/local/bin` is in there. That's where it scripts gets installed when you `pip install` globally; with `--user` option they go somewhere else inside your user's library folder and you need to make sure that bin folder is in your $PATH (by adding that to your .bash_profile or .bashrc).
If you pip install from within a virtual environment, the installed console scripts' folder is automatically added to your shell $PATH once you `activate` that virtual environment.

**Comment by kolyaraketa** [comment]
`brew install fonttools` or, if already installed, `brew link fonttools`

**Comment by anthrotype** [comment]
> brew install fonttools 

no, that's not supported (not by us at least).
`pip install fonttools` is the official way.

**Comment by bquarante** [comment]
Hello,

i have the same problem.
When i do echo $PATH in terminal i have : /Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin
> Also, echo the content of your $PATH to check that /usr/local/bin is in there
i suppose that it's ok because usr/local/bin is here.

i tried to reinstall fonttools like this
pip install --ignore-installed fonttools

but i still can't use subset :(

Cheers,
bernard

**Comment by anthrotype** [comment]
looks like you do have another python available, a python3.6 from the official python.org installers.
just use that one to install.

```
python3.6 -m pip install fonttools
```

**Comment by bquarante** [comment]
It works fine now, thanks a lot!

i noticed that this msg below was about python 2.7 :
"Requirement already satisfied: fonttools in /Library/Python/**2.7**/site-packages"

and the echo $PATH was ...Python.framework/Versions/**3.6**....

**Comment by anthrotype** [comment]
if you still want to install fonttools with the built-in macOS python, you have to avoid sudo and pass the --user option, like so:

```
$ python -m pip install --user fonttools
```

When you use --user, the scripts will not go to the global /usr/local/bin directory, but to a user's specific folder (for my user "clupo" this is /Users/clupo/Library/Python/2.7/bin). This folder is not in your $PATH by default, so you have to configure your environment to add this folder to the search path for executables. Google or stackoverflow how to do that.
