### ISSUE TITLE
[name] Support adding entries for multiple languages

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#921]
Name table object has addName(). Would be good to support adding name for multiple languages at the same time.  Eg. if string is a dict (like `{'en':'Weight', 'fa-IR':'وزن'}).  I need this in fvar generation.

**Comment by brawer** [comment]
A while a go I’ve added support for multilingual names to OpenType.js, exposing BCP47 language codes in the API. I didn’t bother with `name` format 1 (since nobody seems to implement this), but I did support `ltag`. https://github.com/nodebox/opentype.js/blob/master/src/tables/name.js

**Comment by behdad** [comment]
@brawer can you work on this?  Initially maybe just map to Windows-platform language codes?
