### ISSUE TITLE
OS_2 : Values should not be converted to string

### ISSUE THREAD

**Issue by shwetamar85** [fonttools/fonttools#922]
Hi

Fields mentioned below should not be converted to string in ttx as the value they have is only significant if available in Unicode format. 

usFirstCharIndex
usLastCharIndex
usDefaultChar
usBreakChar

Thanks
Shweta

**Comment by justvanrossum** [comment]
What do you mean exactly? Does this output not make sense?
```xml
    <usFirstCharIndex value="32"/>
    <usLastCharIndex value="8722"/>
```

**Comment by shwetamar85** [comment]
These values are used to search the first and last glyph in the font file . Since these are not Unicode values we are not able to identity the glyph associated with it.

**Comment by moyogo** [comment]
32 is U+0020 and 8722 is U+2212. How are these not Unicode values?

**Comment by moyogo** [comment]
> 32 is U+0020 and 8722 is U+2212. How are these not Unicode values?

One can get the glyph associated with these in the cmap:
```xml
<map code="0x20" name="space"/><!-- SPACE -->
...
<map code="0x2212" name="minus"/><!-- MINUS SIGN -->
```

**Comment by miguelsousa** [comment]
> These values are used to search the first and last glyph in the font file.

No, they're for the first and last **character** in the font file. If you want the first and last glyph use the glyph order. Also, if the font supports characters outside the BMP, `usLastCharIndex` will always be U+FFFF.
