### ISSUE TITLE
CFF glyphs horizontal metrics

### ISSUE THREAD

**Issue by typoman** [fonttools/fonttools#925]
Hi all,

This is more of a question than a issue. Given that horizontal metrics are stored in 'hmtx' table in a TTF font, when a font contains postscript outlines and a 'CFF' table, modifying the 'hmtx' table does not change the width of the CFF glyphs and saving the font back using the fonttools does not change the postscript glyphs width and still some engines like CoreText read the width from 'CFF' apparently and skip the width from 'hmtx' table. I also inspected the TTX file and couldn't find any information about glyphs widths other than the 'hmtx' table. Is there something I'm missing or fonttools is not suppose to deal with this data?

Thank you

**Comment by miguelsousa** [comment]
The advance width of CFF glyphs is stored in the CFF table. To get the glyph's advance width you need to look at its charstring and also factor in the `defaultWidthX` and `nominalWidthX` values.
Here's the relevant snippet from the [Adobe Tech Note #5177](https://en.wikipedia.org/w/index.php?title=PostScript_fonts#Font_format_specifications):
>  **Width**: If the charstring has a width other than that of **defaultWidthX** (see Technical Note #5176, “The Compact Font Format Specification”), it must be specified as the first number in the charstring, and encoded as the difference from **nominalWidthX**.

FontTools takes care of all of this logic (as well as the handling of subroutines) for you. Look at [these lines](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/subset/__init__.py#L1840-L1854) to get an idea of how to fetch a CFF's glyph width.

**Comment by typoman** [comment]
The code you pointed was extracting the width but the Adobe Note helped me to understand the how the width is calculated in CFF. I was able to change the width by setting the value of the first item in the CharStrings program to the intended value minus the nominalWidthX.

Thank you Miguel

**Comment by behdad** [comment]
Note that as of OpenType 1.7, the hmtx has priority over CFF table advance widths.
