### ISSUE TITLE
I hate easy-install.pth

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#929]
I just spent half hour debugging why setting PYTHONPATH doesn't work.  I tracked it down to this stupid file /usr/local/lib/python2.7/dist-packages/easy-install.pth:

```
import sys; sys.__plen = len(sys.path)
/home/behdad/SSD/distillery/booleanOperations/Lib
./glyphs2ufo-1.0-py2.7.egg
./compreffor-0.1.0-py2.7.egg
/home/behdad/SSD/distillery/ufoLib/Lib
/home/behdad/SSD/distillery/fontmake/Lib
/home/behdad/SSD/distillery/fonttools/Lib
/home/behdad/SSD/distillery/ufo2ft/Lib
import sys; new = sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p = getattr(sys, '__egginsert', 0); sys.path[p:p] = new; sys.__egginsert = p + len(new)
```

So, just making sure: we're not using this easy-install thing for any package anymore, right?  Thanks.

**Comment by anthrotype** [comment]
Not, unless you use pip to install -e (editable), which will internally use setuptools "setup.py develop" command and add an entry to the easy_install.pth.
You are free to not use that if you want.
Those .egg paths are the result of installing via "setup.py install", which is now deprecated. Use `pip install .` instead to install from local source (this will not use setuptools' easy_install, but install as a pip wheel).

**Comment by behdad** [comment]
Thanks.  Sounds to me like setup.py install is actively harmful...
