### ISSUE TITLE
gvar: controlBytes interpretation

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#936]
I have built a variable font which looks correct to me (with one small doubt, see below), on which ttx decompilation fails.

I’m wondering if there may be a mistake in [TupleVariation.compileDeltaValues()](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/TupleVariation.py#L305). In my font, an encoded glyphVariationData table looks like this:

```
      00 01    tupleVariationCount 1
00 08 00 09    offsetToData 8, variationDataSize 9
20 00          tupleIndex 0x2000: privatePointNumbers, sharedTuple 0
      03 02    countByte 3 -> RunCount 3; controlByte 2 -> PointCount 3
00 14 15 02    PointIndex 0, PointIndexDifference 20, PointIndexDifference 21 = Point 41 (RSB), controlByte 2 -> DeltaCount 3
1E 1E 3C 00    DeltaX 30, DeltaX 30, DeltaX 60, controlByte 0
```

Note that the last controlByte is 0 and there are no delta entries following.

As I [understand the spec](https://www.microsoft.com/typography/otspec/otvarcommonformats.htm#PackedDeltas), there should be either a flag on the controlByte indicating that the deltas are all 0, i.e. the control byte should be 0x82 (2 + 1 = 3 zero y deltas), or it should be 0x02 with three zero y delta bytes following.

Am I mistaken? Is there another reason why the 0x00 is interpreted as "all deltas are 0" in this case?

The font works correctly in FontView, but throws an exception when decompiled with ttx:

```
ERROR: An exception occurred during the decompilation of the 'gvar' table
Traceback (most recent call last):
  File "build/bdist.macosx-10.12-x86_64/egg/fontTools/ttLib/__init__.py", line 424, in __getitem__
    table.decompile(data, self)
  File "build/bdist.macosx-10.12-x86_64/egg/fontTools/ttLib/tables/_g_v_a_r.py", line 111, in decompile
    numPointsInGlyph, sharedCoords, axisTags, gvarData)
  File "build/bdist.macosx-10.12-x86_64/egg/fontTools/ttLib/tables/_g_v_a_r.py", line 229, in decompileGlyph_
    sharedTuples, data, 4, offsetToData)
  File "build/bdist.macosx-10.12-x86_64/egg/fontTools/ttLib/tables/TupleVariation.py", line 552, in decompileTupleVariationStore
    tableTag, axisTags, tupleData, pointDeltaData))
  File "build/bdist.macosx-10.12-x86_64/egg/fontTools/ttLib/tables/TupleVariation.py", line 597, in decompileTupleVariation_
    len(points), tupleData, pos)
  File "build/bdist.macosx-10.12-x86_64/egg/fontTools/ttLib/tables/TupleVariation.py", line 412, in decompileDeltas_
    runHeader = byteord(data[pos])
IndexError: string index out of range
```

The font is attached.

[VarFont.ttf.zip](https://github.com/fonttools/fonttools/files/955521/VarFont.ttf.zip)

**Comment by anthrotype** [comment]
Hi Jens, thanks for the bug report and for attaching the font.
How did you generate it, with fontmake (varLib) or another tool?

**Comment by jenskutilek** [comment]
I generated it with a fontTools script which adds tracking as opsz axis, based on the snippet [interpolate.py](https://github.com/fonttools/fonttools/blob/master/Snippets/interpolate.py):

[add_axis.zip](https://github.com/fonttools/fonttools/files/955651/add_axis.zip)

**Comment by jenskutilek** [comment]
Here’s a gist of the script: https://gist.github.com/jenskutilek/cb2777860eceb8907949561361457315

**Comment by anthrotype** [comment]
hm. Maybe you could try using fontmake with a .glyphs file, or some master UFOs + .designspace, or `fonttools varLib ...` with some master TTFs and a .designspace file, and see whether that works?

**Comment by jenskutilek** [comment]
I think the generated `gvar` is faulty. It should read:

```
      00 01    tupleVariationCount 1
00 08 00 0A    offsetToData 8, variationDataSize 10
20 00          tupleIndex 0x2000: privatePointNumbers, sharedTuple 0
      03 02    countByte 3 -> RunCount 3; controlByte 2 -> PointCount 3
00 14 15 02    PointIndex 0, PointIndexDifference 20, PointIndexDifference 21 = Point 41 (RSB), controlByte 2 -> DeltaCount 3
1E 1E 3C 82    DeltaX 30, DeltaX 30, DeltaX 60, controlByte 82 -> 3 zero DeltaY
```

(variationDataSize was off by one, and the last control byte is adjusted)

Not sure where this happens yet ...

**Comment by jenskutilek** [comment]
After the font is corrected manually (in a hex editor), roundtripping through ttx works. So the error is not in the XML path ... will investigate further.

[VarFont.ttx.zip](https://github.com/fonttools/fonttools/files/955795/VarFont.ttx.zip)

**Comment by jenskutilek** [comment]
OK, I think I found it: When modifying a point coordinate, you must supply both x and y deltas, even if y is 0:

```
smallDelta.extend([None, (60, 0), None, None])
```

instead of

```
smallDelta.extend([None, (60, 0), None, None])
```

This could probably be prevented [here](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/TupleVariation.py#L298), or would it interfere with cvt deltas?

**Comment by jenskutilek** [comment]
Sorry about keeping talking to myself ... the weird thing is the 0x00 byte in the original faulty table, is that some kind of padding?

**Comment by anthrotype** [comment]
but do you really need to go down to building a gvar table with an ad-hoc script? I would recommend to first try some interpolatable TTFs + a .designspace fiel that describes their relations, and give them to varLib and see if the compiled font matches your expectations.

**Comment by jenskutilek** [comment]
Some of my reasoning can be seen on this [TypeDrawers thread](http://typedrawers.com/discussion/2109/otvar-changing-tracking-hvar), I initially used two differently tracked TTFs, but varLib doesn’t optimize the deltas in that case: It stores a delta for every point in every glyph, when one delta per contour and one for the RSB point would be sufficient.

**Comment by behdad** [comment]
So, no bug here?

**Comment by jenskutilek** [comment]
Nope, user error ...
