### ISSUE TITLE
gvar: Optimization of delta storage

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#937]
I have started a branch to modify varLib so that deltas are stored in the most compact way: [varlib-delta-opt](https://github.com/fonttools/fonttools/compare/master...jenskutilek:varlib-delta-opt). 

Redundant deltas are omitted (they are stored as None in the delta list). In many cases the ‘optimized’ version is larger than listing all point deltas verbatim, because it makes it necessary to store the point indices which the remaining deltas apply to. The algorithm checks this and chooses the smaller variant.

In my ‘real-world scenarios’ the file size savings are very small, about 3 kB on a variable font of 2.2 MB, which simmer down to 50 bytes on a 770 kB WOFF2.

For special cases like a tracking change with otherwise identical glyphs, the savings are huge though, because only one delta per contour remains where in the old gvar, a delta would be stored for every point.

What’s missing is comparing the raw interpolated points with the explicitly stored deltas. If the result is the same, the explicit delta could be omitted. This could lead to more file size savings, but I’m not sure how complicated it is to implement.

The fonts generated this way can’t be instantiated by mutator.py. There’s a comment in mutator.py that notes this is still TODO.

Any opinions on this?

**Comment by robmck-ms** [comment]
I've often wondered how much the real-world savings be if explicit deltas were thrown out when they are within some small epsilon of implicit deltas. E.g. if you can do IUP and end up with a point that's 1-2 font units away from where it would be with an explicit delta, you could get rid of that delta. An interesting question is: What epsilon would reliably give a savings that offsets the overhead of the current sparse delta representation? 1-2 font units (UPM 2048) might be fine; 10 font units, probably not.

Epsilon would of course be a command-line parameter to let people tune for their use case. Might be nice to make epsilon a percentage of UPM as that more directly represents the impact.

**Comment by jenskutilek** [comment]
Partly implemented when #943 is merged; the one-delta-per-contour optimization is implemented, but not the omission of redundant interpolatable deltas.

**Comment by behdad** [comment]
Reviewing and extending this is on my plate for this week. :)

**Comment by behdad** [comment]
I believe we did this a while back.
