### ISSUE TITLE
font NotoColorEmoji.ttf getGlyphSet failed: Font contains no outlines

### ISSUE THREAD

**Issue by liudanking** [fonttools/fonttools#949]
I try to drew emoji image using fonttools.
The font I am using is [NotoColorEmoji.ttf](https://github.com/googlei18n/noto-emoji/blob/master/fonts/NotoColorEmoji.ttf) by Google.
The font can be loaded, but when I try to get getGlyphSet, it failed:

```
from fontTools.ttLib import TTFont
font = TTFont('NotoColorEmoji.ttf')
gs = font.getGlyphSet()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liudanking/code/dl/pyenv/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 695, in getGlyphSet
    raise TTLibError("Font contains no outlines")
fontTools.ttLib.TTLibError: Font contains no outlines
```

Is there anything I missed?

**Comment by anthrotype** [comment]
Currently, only fonts with TrueType `glyf` table, or with `CFF` table are supported by the TTFont.getGlyphSet() method. NotoColorEmoji is a CBDT/CBLC color font so has no glyf table.
Sorry.

**Comment by liudanking** [comment]
@anthrotype
Thanks for you quick reply.

Do you have any recommended python package to parse CBDT/CBLC color font?

**Comment by anthrotype** [comment]
don't get me wrong. FontTools does support decompiling and compiling CBDT/CBLC color fonts, as well as dumping them as TTX. Have a look at the the `ttx -h` help, specifically the `-z` option, it allows you to optionally store the bitmaps as external files with XML references.

it's the TTFont.getGlyphSet() method that does not support color fonts, but only traditional opentype fonts.

**Comment by liudanking** [comment]
`ttx -z extfile NotoColorEmoji.ttf.ttf` works like a charm.

**Comment by anthrotype** [comment]
glad to hear that :)
