### ISSUE TITLE
try to draw emoji image with windows seguiemj.ttf font failed

### ISSUE THREAD

**Issue by liudanking** [fonttools/fonttools#951]
I am trying to extract high resolution windows color emoji image from [seguiemj.ttf ](https://github.com/BeardDesign1/Material-design-theme-ressources/blob/master/seguiemj.ttf).

What I have already know:
* the font stores emoji in svg format (layered vector drawings in COLR/CPAL)
* the font also has a `glyph` table

My roadmap: 
`use fonttools load seguiemj.ttf --> use fonttools draw high resolution png image --> save to file`

for example, I am trying to try 😀  with glyph name [u1F600](http://www.emojiok.com/p/en/emoji/1f600):

```
#! /usr/bin/env python
# -*- coding: utf-8 -*-

if __name__=="__main__":
    import sys
    from fontTools.ttLib import TTFont
    from reportlab.lib import colors
    from fontTools.pens.reportLabPen import ReportLabPen, Path


    glyphName = 'u1F600'
    imageFile = "%s.png" % glyphName

    font = TTFont('seguiemj.ttf')
    gs = font.getGlyphSet()
    pen = ReportLabPen(gs, Path(fillColor=colors.red, strokeWidth=5))
    g = gs[glyphName]
    g.draw(pen)

    w, h = g.width, 1000
    from reportlab.graphics import renderPM
    from reportlab.graphics.shapes import Group, Drawing, scale

    # Everything is wrapped in a group to allow transformations.
    g = Group(pen.path)
    g.translate(0, 200)
    g.scale(0.3, 0.3)

    d = Drawing(w, h)
    d.add(g)

    renderPM.drawToFile(d, imageFile, fmt="PNG")
```
I only get image with emji ontline filled with red color.

What I have missed? Or am I totally on the wrong direction?

**Comment by anthrotype** [comment]
I would start from reading the spec here:
https://www.microsoft.com/typography/otspec/colr.htm
https://www.microsoft.com/typography/otspec/cpal.htm

Also see this freetype issue tracking the development of CORL/CPAL support in FreeType:
http://savannah.nongnu.org/bugs/?44689

**Comment by anthrotype** [comment]
also have a look at this:
https://github.com/mozilla/emojione-colr

**Comment by PeterCon** [comment]
Besides the fact that the Segoe UI Emoji font does not use SVG (the COLR table references glyph IDs that are assumed to refer to glyphs in a glyf, CFF or CFF2 table)...

I have a suspicion that what you are trying to do may be in violation of the license agreement associated with that font.

**Comment by liudanking** [comment]
It is nice to see you again 😄  @anthrotype 
If I understand resources you provided correctly, it means I need to use COLR/CPAL table with glyph info to draw the emoji, which is really a hard work for me. Is there any functions that I can use to achieve this?

**Comment by anthrotype** [comment]
sorry, I'm no expert on color fonts I'm afraid. Maybe @RoelN would know more about the current state-of-the-art for making COLR/CPAL fonts.

**Comment by liudanking** [comment]
@PeterCon Yep, you are right, it means COLR/CPAL table.
And for you curiosity, I am an emoji fan, I like collecting all kinds of versions of emoji resources.

**Comment by anthrotype** [comment]
@PeterCon sorry, I didn't realise he was talking about Segoe UI.. 😊

**Comment by liudanking** [comment]
So Segoe UI is not allowed to be discussed here?

**Comment by behdad** [comment]
It's easy to do what you want, but you should access COLR and CPAL tables, then use the getGlyphSet() to render each layer with the correct color.

**Comment by behdad** [comment]
I don't think this is against the license of the font, if all you are doing is rendering the font.

**Comment by twardoch** [comment]
I shall add that in case of Segoe UI Emoji (esp. the Windows 10 CU version), “extracting” a set the emoji glyph images is not a sensible way to perform the rendering, because that font doesn't really have a static set of emoji images. 

The Microsoft Segoe UI Emoji font includes incredibly sophisticated contextual substitution tables which dynamically compose Unicode emoji character sequences into images, producing emojis of people with different skin colors and even groupings of people of different ages and genders. 

It uses a lot of clever tricks exploring the COLR format to the fullest. 

Real use of Segoe UI Emoji requires use of the font as it is, utilizing a text processor capable of processing OpenType Layout features and the COLR table.

**Comment by liudanking** [comment]
@behdad I have read doc of fonttools carefully, but I did not figure out how to access COLR and CPAL tables.
It seems that function `getGlyphSet`  only takes `glyf` or `CCF` table.
Can you show me an example?

**Comment by miguelsousa** [comment]
```python
from fontTools import ttLib
font = ttLib.TTFont(myFontFilePath)
glyph_set = font.getGlyphSet()
cpal_table = font['CPAL']
colr_table = font['COLR']
```

**Comment by liudanking** [comment]
May I ask how to use `cpal_table ` with `glyph_set`?

**Comment by jenskutilek** [comment]
My RoboChrome plugin (for the RoboFont editor) contains code to read CPAL/COLR data from a font, maybe this code snippet can help you: https://github.com/jenskutilek/RoboChrome/blob/master/RoboChrome.roboFontExt/lib/colorfont/__init__.py#L198

**Comment by liudanking** [comment]
Code from RoboChrome plugin helps a lot.
I know how to get color data and cpal data from tables now.
But I still can't figure out how to draw the color with reportlab pen  😂
