### ISSUE TITLE
t2CharStringPen takes width

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#956]
This is confusing because the width argument is not the glyph width.  It's width-nominalWidth...  We may as well let caller just prepend the program with the width if they want to...  Anyway, just filing to gather thoughts.

**Comment by anthrotype** [comment]
@behdad yeah, it's a bit useless. We can remove that argument and leave it to the caller to prepend the width. The problem it would change the pen's constructor. Other libraries/scripts than ufo2ft may be using this pen and would need to be updated...
Anybody?

**Comment by justvanrossum** [comment]
Or just document it that it's width-nominalWidth. I recently fell into that trap, but I figured it out quick enough. I do like it as part of the constructor, and would not want to mess with the program directly.
