### ISSUE TITLE
Move fontTools.misc.ps* to cffLib

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#957]
I'll take care of moving psCharStrings.py psLib.py psOperators.py to cffLib after #955 is done.

**Comment by justvanrossum** [comment]
Make sure to add `from fontTools.cffLib.psCharStrings import *` versions of them at the old location.

**Comment by miguelsousa** [comment]
Will do.

**Comment by behdad** [comment]
@miguelsousa do you still plan to do this?

**Comment by miguelsousa** [comment]
@behdad No. Sorry missed your message earlier.
