### ISSUE TITLE
CFF bounds recalculation

### ISSUE THREAD

**Issue by mashabow** [fonttools/fonttools#958]
CFF bounds recalculation hasn't been implemented yet; see [_h_h_e_a.py#L83](https://github.com/fonttools/fonttools/blob/30b804003e700677e72522b78334c3a6e89dc82f/Lib/fontTools/ttLib/tables/_h_h_e_a.py#L83), [_v_h_e_a.py#L82](https://github.com/fonttools/fonttools/blob/30b804003e700677e72522b78334c3a6e89dc82f/Lib/fontTools/ttLib/tables/_v_h_e_a.py#L82), and ~~[_m_a_x_p.py#L47](https://github.com/fonttools/fonttools/blob/30b804003e700677e72522b78334c3a6e89dc82f/Lib/fontTools/ttLib/tables/_m_a_x_p.py#L47)~~ (Edited: no need to recalc `maxp` values, while we have to recalc bounds in `head`). In addition, it would be nice to update Top DICT's `FontBBox` too, whose incorrect values may cause hinting distortion.

**Comment by behdad** [comment]
Thanks.  Perhaps you can try patching this using boundsPen?  Not sure about performance.

**Comment by mashabow** [comment]
Ok, I'll try it next week.
