### ISSUE TITLE
TTFont save performance

### ISSUE THREAD

**Issue by typoman** [fonttools/fonttools#960]
Hi all,

I'm trying to open a 'otf' binary and change its tables once at a time and I don't want to save it on disk I want to access it on memory. For example I want to change a glyph program in the 'CFF ' table then get the whole binary back. While saving the font is pretty fast it's not instant enough. I was wondering since the font is already compiled and working well I don't want the SFNTWriter to check all the tables and compile them then put them together. Also reorderFontTables could be avoided by checking if the orders are already available by the SFNTReader then iterate over the same table order and put them in the byte stream. Is the a way of having all the tables ready and only compile the changed the table then insert in the byte stream? What if I just put all the raw tables together in a same order as the reader is providing. Would that cause a problem later?

Thanks

**Comment by typoman** [comment]
After a lot of digging into how fonttools compiles the tables I came up with this idea of lazy compiling which is if any of tables were changed after the last compile then that table will only be compiled. Also when it comes to CFF, charStrings only get compiled after they have been changed. How does that sound?

**Comment by anthrotype** [comment]
It is already kind of like that. If you have loaded a TTFont from a file, and then later you call `TTFont.save()`, then only the tables that have been decompiled so far (i.e. you called the `__getitem__` method, e.g. `glyf = font['glyf']`) will be re-compiled upon save; the ones which have not been decompiled are simply read from the input file (by the SFNTReader) and written out to the new file (by the SFNTWriter), binary to binary, without intervening decompilation/compilation.

**Comment by anthrotype** [comment]
sometimes other tables are decompiled in addition to the ones you requested: e.g. `maxp` is also decompiled if you get the `glyf` table, for obvious reasons, and the 'post' will be also decompiled because the TTFont needs the postscript glyph names internally.

**Comment by typoman** [comment]
Thank you Cosimo, I realized that. I'm trying to make a compiler using fonttools that constructs the binary as the user adds every bit of data to the font one by one. This makes it possible to have an instant binary as the user makes the font without compiling the whole tables. The most important part is when user changes a glyph the feedback should be instant. What I've realized is that if the font is big (Chinese or a multi script font) then changing a CFF glyph causes the whole table to be compiled and feedback is not instant even though very fast. So now I'm thinking to change the CFFWriter in the cfflib so I when I change a glyph then only that glyph's charString gets compiled. Also I'm thinking about new way to calculate the checksums so the TTFont doesn't calculate it on every table every time when it's saving the font. AFAIK the checksum is calculated on every table even if that table hasn't been changed since the last time.

**Comment by typoman** [comment]
I wanna add the reason to make such compiler is that some typefaces need to be compiled and be in context so the user could see how they look like. Normally when a user changes only a glyph, s/he needs to compile all the tables, so changing a curve and compiling every time could be time consuming.

**Comment by behdad** [comment]
Unless you have a specific suggestion to improve how fonttools saving currently works, I don't think there's much to do here.
