### ISSUE TITLE
how to get code points of a glyphname?

### ISSUE THREAD

**Issue by liudanking** [fonttools/fonttools#961]
I am using the [script](https://gist.github.com/Jolg42/f22676fdfba6dbfe4589aa30f0326fb4) to extract images from sbix table.

The script works well, but I want to save the file by code points, not glyphname.

Is that possible?

**Comment by MitchTalmadge** [comment]
Possible, but probably not easy. I'm working on doing the same thing right now for my application, [Emoji Tools](https://EmojiTools.org/). 

I believe the solution involves taking the names from `sbix`, finding their references in the `morx` table which includes the Zero Width Joiners (ZWJ), then mapping each individual component of the [ZWJ Sequences](http://emojipedia.org/emoji-zwj-sequences/) to their code in the `cmap` table. This is how it works for Google fonts, except that `sbix` is `CBDT`, and `morx` is `gsub`.

**Comment by liudanking** [comment]
I am still working on the issue. If you figure it out before me, I would appreciate if you leave a feadback.
BTW, I am interested in your emoji tools, looking forward that it will be released on time.

**Comment by MitchTalmadge** [comment]
@liudanking Sure thing! Let me know if you figure it out too. I'm hoping to release it on time too lol

**Comment by miguelsousa** [comment]
> how to get code points of a glyphname?

See https://github.com/googlei18n/nototools/blob/master/nototools/hb_input.py#L313-L319

**Comment by MitchTalmadge** [comment]
@miguelsousa This will only work for single code Emojis, but not for ZWJ Sequences. For example, there is no `u1F1E8_u1F1F3` record in the `cmap` table. This glyph is a composition of multiple other glyphs (Warning: don't just split the name by the underscore and try to parse each section one at a time via cmap; this name does not include the ZWJ code, and you won't get the true filename out of it)

**Comment by vXBaKeRXv** [comment]
Semi solution.. 
Open and save as a Apple font with FontForge. GSUB will be added to the font using the Morx. Then you can do your hooking to get convert the names. 

Adding glyphs slots without adjusting the Morx, makes the glyphorder go out of sync. 
Having to do a bunch of tricks to solve.

**Comment by khaledhosny** [comment]
I don’t think there is nothing for FontTools to do here, you need to process `morx` table to find what character sequence maps to what glyph.
