### ISSUE TITLE
GlyphCoordinates loses precision using array('f') instead of array('d')

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#963]
In a commit from 2013 (f2c2b4d38bd7bba23db71936262db984e4b7aebb) @behdad extended the `GlyphCoordinates` class in the `_g_l_y_f` table module to transparently support float coordinataes.

The GlyphCoordinates class wraps an `array.array` object, containing a single two-dimensional array of x and y coordinates. The type code used is `'f'`, which in C corresponds to `float` type, which uses maximum 4 bytes. The python floats are `double` precision floats (max 8 bytes), and are represented with the type code `'d'` in the array.array type code.

https://docs.python.org/3/library/array.html

Using `'f'` instead of `'d'` to store float coordinates means that we risk truncating a double into a float and thus we get the wrong results when we call `round` (e.g. in `GlyphCoordintes.toInt()` method):

```python
>>> from fontTools.misc.py23 import round
>>> from array import array
>>> afloat = array('f', [242.50000000000003])
>>> afloat
array('f', [242.5])
>>> adouble = array('d', [242.50000000000003])
>>> adouble
array('d', [242.50000000000003])
>>> round(afloat[0])
242
>>> round(adouble[0])
243
```

This problem is affecting all fontmake generated TTFs. The fonttools' `TTGlyphPen` receives floats from ufo2ft (and cu2qu) and does not do any rounding; it lets the glyf module do the rounding, but this may produce incorrect results because of the above mentioned double-to-float truncation.

I see two way to fix this:

1) we use doubles (type code `'d'`) instead of floats (`'f'`) in the `GlyphCoordinates` array;
2) we call `round` in the TTGlyphPen before we create `GlyphCoordinates` instances.

/cc @behdad

**Comment by behdad** [comment]
> >>> round(afloat[0]) 242 >>> round(adouble[0]) 243

This looks bizarre!

**Comment by anthrotype** [comment]
what do you suggest?
