### ISSUE TITLE
ttx: cannot specify multiple tables

### ISSUE THREAD

**Issue by frankrolf** [fonttools/fonttools#973]
I remember specifying multiple tables for a TTX XML dump used to be possible, but no longer (or I am doing it wrong):

`ttx -t hhea OS/2 SourceSansPro-Bold.otf`
`ERROR: File not found: "OS/2"`

`$ ttx -x "CFF ", "cmap" SourceSansPro-Bold.otf`
`ERROR: File not found: "cmap"`

**Comment by behdad** [comment]
```
$ ttx -tGDEF -tGPOS -tGSUB ...
```

**Comment by anthrotype** [comment]
The -t or -x options take only one argument, but can be specified multiple times in a single command line.

**Comment by frankrolf** [comment]
Thanks for the clarification. It would be helpful to have this notation show in `ttx -h`.

**Comment by behdad** [comment]
```
    -t <table> Specify a table to dump. Multiple -t options
       are allowed. When no -t option is specified, all tables
       will be dumped.
```

**Comment by frankrolf** [comment]
Thanks @behdad, although I am literate I did not deduce that specific notation from the help documentation. It’s sometimes useful to have a one-line example.

**Comment by anthrotype** [comment]
@frankrolf I also get confused sometimes. Feel free to send a pull request suggesting a different wording which makes more sense to you :)
