### ISSUE TITLE
[OS/2].usLastCharIndex calculated wrong in the presence of chars >= 0x10000?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#982]
I'm getting an error from FontValidator about `usLastCharIndex`:

> actual = 0xffff, calculated = 0xffed

My font contains chars >= 0x10000. It seems FontValidator wants `usLastCharIndex` to be the highest character below 0x10000.

**Comment by khaledhosny** [comment]
FontTools is following the [spec](https://www.microsoft.com/typography/otspec/os2.htm#lci):

> This field cannot represent supplementary character values (codepoints greater than 0xFFFF). Fonts that support supplementary characters should set the value in this field to 0xFFFF.

**Comment by justvanrossum** [comment]
Thanks, I could have checked that myself. Sorry for the noise. Never trusting FontValidator again :)

**Comment by mashabow** [comment]
For reference: https://github.com/Microsoft/Font-Validator/issues/28
