### ISSUE TITLE
[cffLib] UnderlinePosition has no default, but UnderlineThickness does

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#983]
According to the spec `UnderlinePosition` needs to have a default value of -100:
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/cffLib/__init__.py#L1722

@readroberts can you confirm that fonttools is indeed wrong here?

(Btw. this has been in fonttools for a long time, so it's most likely my own bug.)

**Comment by readroberts** [comment]
Yes this is a bug - UnderlinePosition should have a default value of -100. However, it is a minor issue, as it does not affect building a CFF table: whether the value is None or the default value, in  the field will be omitted. This affects only output to ttx files, which shows default values when the field is omitted from the CFF table, presumably to provide a hint for editing the ttx files.

**Comment by justvanrossum** [comment]
Thanks, Read!
