### ISSUE TITLE
include() directive with relative paths

### ISSUE THREAD

**Issue by bobh0303** [fonttools/fonttools#986]
Regarding the `include();` directive, the [Adobe Feature File specification](https://cdn.rawgit.com/adobe-type-tools/afdko/master/FDK/Technical%20Documentation/OpenTypeFeatureFileSpecification.html#3) says this:

>In a typical implementation, if the file name were absolute then that path would be used. If the file name were relative, then it would be appended to the directory of the including feature file.

However it seems to me that neither `makeOTF` nor `fontTools feaLib` obey this.

Given the following file structure:
```
project/
    results/
        project-Regular.fea      ← NB contains: include(../source/opentype/regular.fea);
    source/
        opentype/
            regular.fea          ← NB contains: include(other.fea);
            other.fea
```
if my current directory is `project/results` and I issue a command similar to
```
fonttools feaLib -o x.ttf  project-Regular.fea src.ttf
```
then I get the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'other.fea'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fonttools", line 9, in <module>
    load_entry_point('fonttools==3.13.1', 'console_scripts', 'fonttools')()
...
  File "/usr/local/lib/python3.5/dist-packages/fontTools/feaLib/lexer.py", line 234, in make_lexer_
    raise FeatureLibError(str(err), location)
fontTools.feaLib.error.FeatureLibError: ../source/opentype/regular.fea:18:8: [Errno 2] No such file or directory: 'other.fea'
```
Similarly, on a Windows machine, Adobe's `makeOTF` abends with:
```
makeotfexe [FATAL] <project-Regular> include file <other.fea> not found [.\../source/opentype/regular.fea 18]
```
For its part, FontForge on Linux *does* compile the code per the spec.

If I change the include in `regular.fea` to be:
```
include(../source/opentype/other.fea);
```
then both fonttools and makeOTF are happy, but FontForge is not.

So it seems FontForge and the Adobe Spec do one thing, fonttools and makeOTF do something else.

**Comment by miguelsousa** [comment]
It's the spec that needs to be updated to reflect what `makeotf` actually does. In #838 I made `feaLib` work like `makeotf`.

**Comment by bobh0303** [comment]
Thanks -- at least that confirms I wasn't going crazy. And thanks for the reference which also got me to adobe-type-tools/afdko#164.

**Comment by behdad** [comment]
Would be nice to have a way to make relative includes as well.  Maybe if path starts with "./"?  Or just a different keyword.
