### ISSUE TITLE
Mojibake is displayed in pyftinspect when font contains CJK metadata

### ISSUE THREAD

**Issue by Vdragon** [fonttools/fonttools#988]
[Mojibake \- Wikipedia](https://en.wikipedia.org/wiki/Mojibake)

As the following screenshot, also `(pyftinspect:PID): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()` is emitted in the console.

![- -sourcehanseriftw-semibold otf - pyftinspect_027](https://user-images.githubusercontent.com/1192163/27379372-8956554c-56ad-11e7-88d7-23ba7e842bc4.png)

**Comment by behdad** [comment]
I think you are the only running pyftinspect in the last two years :).

What would happen if you try it with Python 3, if possible?

In general, pyftinspect is a tiny hack that does what you see.  I'll try fixing this name issue, but in general, it's far from perfect, but we don't have plans to develop it further, without rethinking the entire approach.

**Comment by Vdragon** [comment]
> I think you are the only running pyftinspect in the last two years :).
Just downloaded fonttools today and notice the command ;)  
BTW, the version I'm using is 3.0 from Ubuntu 16.04 archive, I do tried the latest version from PyPI, however I can't run pyftinspect due to missing PyGTK module(not seems to be easily installable from PyPI)

> What would happen if you try it with Python 3, if possible?
![- -sourcehanseriftw-semibold otf - pyftinspect_028](https://user-images.githubusercontent.com/1192163/27381098-11cb18da-56b4-11e7-8619-d2d4048ade00.png)

**Comment by behdad** [comment]
pyftinspect was removed long time ago...
