### ISSUE TITLE
Dealing with and reporting GPOS overflow

### ISSUE THREAD

**Issue by MrBrezina** [fonttools/fonttools#989]
I prepare kern, mark, and mkmk features using ufo2ft. There are two issues related to GPOS overflow I would like to put forward:

1. in case a lookup in GPOS table overflows, the code generated by ufo2ft cannot be used by AFDKO which needs the `useExtension` command in the code for the corresponding feature. It would be nice to be able to produce the kern, mark, mkmk features and enforce the use of `useExtension` to solve this. Essentially, make large lookups compatible with AFDKO.

2. when fonttools try to solve the overflow, they report (it reports?) multiple lookups being fixed. Perhaps this could be a bit more concise? When used in a toolchain, e.g., via fontmake, there are too many reports which make spotting actual errors more difficult.

**Comment by behdad** [comment]
We use hb-repacker now which is much better at resolving overflows.
