### ISSUE TITLE
pyftsubset: Delete outline instead of deleting glyph?

### ISSUE THREAD

**Issue by typefacts** [fonttools/fonttools#992]
Hi,
I’d like not only to subset a font, but also to empty some glyphs without deleting them (like what’s happening with notdef) – could this be possible?
Thanks!
Christoph

**Comment by behdad** [comment]
Why do you need that?  You can do that with very small scripts.

**Comment by typefacts** [comment]
Hi Behdad,
Cosimo told me to open a thread since it “might be a useful feature to add”.
If you don’t agree, feel free to close it – and give me a hint about the very small scripts. ;)

**Comment by behdad** [comment]
> Cosimo told me to open a thread since it “might be a useful feature to add”.
> If you don’t agree, feel free to close it – and give me a hint about the very small scripts. ;)

To me, such feature creates a broken font, and that's not good.
Re the very short script, before subsetting do this:
- For TrueType outlines, just:
```
font['glyf'][glyphname].__dict__ = {'data':''}
```
- For CFF it's a bit more involved since we need to preserve width.  That's still less than five lines using the T2CharStringPen

**Comment by typefacts** [comment]
Alright, thanks!

**Comment by khaledhosny** [comment]
There `--retain-gids` now that does this.
