### ISSUE TITLE
Subsetter and CFF CharStrings

### ISSUE THREAD

**Issue by benkiel** [fonttools/fonttools#994]
I've been banging my head against a Windows error with some fonts that have been made with the subsetter: turns out that it is removing the CharString entries that are marked raw="1". This is for the <Subrs> entry. I don't know why these are getting dumped as raw — that's the next thing to figure out, but removing them breaks the font in Windows.

**Comment by behdad** [comment]
They are raw because as far as subsetter sees, they are unreferenced and as such cannot be decoded. Because they are unreferenced, they are removed during unused subroutine removal. Do you have a minimal test case you can attach?

**Comment by benkiel** [comment]
@behdad actually, I can simplify this much more: in this case (again, no idea why this is coming up raw, but it is), the subsetter leaves
```
        <Subrs>
          <!-- The 'index' attribute is only for humans; it is ignored when parsed. -->
        </Subrs>
```
in the CFF table. Taking that out and recompiling with TTX makes the font work.

**Comment by benkiel** [comment]
And, the font is getting mastered via makeOTF v2.0.94 May 23 2016 from a UFO: next is to dig into why TTX sees these subroutines as raw, but at least now I can fix the issue I was having.

**Comment by benkiel** [comment]
@behdad I'll email a test case for you on this.

**Comment by mashabow** [comment]
FYI, AFDKO's subroutinizer genarates some unused subroutines. See https://github.com/adobe-type-tools/afdko/issues/173.

**Comment by benkiel** [comment]
@mashabow That's good to know, thank you.

**Comment by anthrotype** [comment]
So to recap, you're claiming that the subsetter removing charstrings that are marked "raw" in ttx dump (because unused) will break the font in Windows?

> I'll email a test case for you on this.

@benkiel could I get that one as well? thanks.

**Comment by benkiel** [comment]
@anthrotype No, the subsetter isn't removing things because they are raw (afaik) but because the glyphs they reference aren't in the font anymore. Instead of checking the length of the subrs to see if there is anything in there and then writing, fontTools writes the subrs regardless of length. If empty, font won't install in Windows.

This is best a check outside of the subsetter, so that fontTools doesn't write an empty subrs. I know that @behdad prefers that fontTools just writes what's there, vaild or not, so if this falls into that case, then it should be a check in the subsetter.

Email me a good email address and I'll send the test case.

**Comment by anthrotype** [comment]
@benkiel cosimo [at] anthrotype.com

**Comment by benkiel** [comment]
Just updating this, as of 3.21.0.dev0, empty subrs are still being written into the font when subset.

**Comment by benkiel** [comment]
Tested and works. @anthrotype thank you very much!
