### ISSUE TITLE
Roundtrip failures for some of the fonts I'm working with.

### ISSUE THREAD

**Issue by jarrodlombardo** [fonttools/fonttools#999]
Attached is a report generated by roundtrip.py when I run it on a ttf:
[report.txt](https://github.com/fonttools/fonttools/files/1136693/report.txt)

Something is getting messed up in the kern subtables, but I don't understand font internals well enough to know if it's something wrong with the ttf I was given or a bug in fonttools.

**Comment by anthrotype** [comment]
@jarrodlombardo can you send me the font via email?

**Comment by jarrodlombardo** [comment]
Had to wait for some approvals about sharing the font. I'll email now.

**Comment by anthrotype** [comment]
closing in favour of #1089
